"1:15pm. Let me read the UQ Holder thread and then I will resume.
This is such torture. I never thought I'd be this down just as soon as I am nearing the finish line.

1:20pm. Let me do the chores here.

1:40pm. Let me resume. It is time to struggle once more.

Let me make that exploit test. I'll compare it to the orignal.

1:55pm.

```
inl main () =
    inl d = dictm.empty
    inl game = leduc.game()
    loopw.for' (from: 0i32 nearTo: 20) fun i =>
        open agent.cfr_sample_learned_infoset
        loopw.for' (from: 0i32 nearTo: 100 * 2000) fun _ =>
            ignore <| train.run (policy_train d) (policy_cur d) game
            ignore <| train.run (policy_cur d) (policy_train d) game
        inl d_test = dictm.empty
        loopw.for' (from: 0i32 nearTo: 500 * 2000) fun _ =>
            ignore <| train.run (policy_train d_test) (policy_avg d) game
        inl r =
            loopw.for (from: 0i32 nearTo: 20 * 2000) (fun _ r =>
                r +! train.run (policy_cur d_test) (policy_avg d) game
                ) (r2 0)
        $"print('summary -',!i,!r)"
```

Let me try running it.

```
Traceback (most recent call last):
  File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_leduc13 (parallel)/new/cfr_sample_learned_infoset_exploit_test.py", line 4, in <module>
    from cfr_sample_learned_infoset_exploit_test import main
  File "c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc13 (parallel)\new\cfr_sample_learned_infoset_exploit_test.py", line 4, in <module>
    from cfr_sample_learned_infoset_exploit_test import main
ImportError: cannot import name 'main' from partially initialized module 'cfr_sample_learned_infoset_exploit_test' (most likely due to a circular import) (c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc13 (parallel)\new\cfr_sample_learned_infoset_exploit_test.py)
```

What is this error? Ah, I made the run script the same as the pyx file. Let me move on.

2:05pm. Is this thing running. It sure is taking it a while to go through even a single iteration.

```
        inl num_iterations = 20 * 2000
        inl r =
            loopw.for (from: 0i32 nearTo: num_iterations) (fun _ r =>
                r +! train.run (policy_cur d_test) (policy_avg d) game
                ) (r2 0) /! (f64 num_iterations)
```

I forgot to divide by the number of iterations here.

...Holy shit this still hasn't gone through a single round.

```
inl main () =
    inl d = dictm.empty
    inl game = leduc.game()
    inl mult = 1i32
    loopw.for' (from: 0i32 nearTo: 20) fun i =>
        open agent.cfr_sample_learned_infoset
        loopw.for' (from: 0i32 nearTo: 100 * mult) fun _ =>
            ignore <| train.run (policy_train d) (policy_cur d) game
            ignore <| train.run (policy_cur d) (policy_train d) game
        inl d_test = dictm.empty
        loopw.for' (from: 0i32 nearTo: 500 * mult) fun _ =>
            ignore <| train.run (policy_train d_test) (policy_avg d) game
        inl num_iterations = 20 * mult
        inl r =
            loopw.for (from: 0i32 nearTo: num_iterations) (fun _ r =>
                r +! train.run (policy_cur d_test) (policy_avg d) game
                ) (r2 0) /! (f64 num_iterations)
        $"print('summary -',!i,!r)"
```

Let me do it like this. Is it running at all with this?

...I don't know why, but even with this, I can wisibly see it iterating through. It is incredibly slow.

Let me run the old exploitation test so I can see how fast it is.

https://realpython.com/python-timer/

Let me import time, and I'll use perf_counter.

Hmmm, even the old thing is not that fast. Did I wreck something by accident in the new version?

```
        !!!!Import("time")
        inl t = $"time.perf_counter()" : f64
        $"print('start training')"
        loopw.for' (from: 0i32 nearTo: 100 * 2000) fun _ =>
            open agent.cfr_sample_learned_infoset
            ignore <| leduc.start (nodes.nodes_2p true (funsTrain TrainCurrentPolicy d, funsTrain PlayCurrentPolicy d))
            ignore <| leduc.start (nodes.nodes_2p true (funsTrain PlayCurrentPolicy d, funsTrain TrainCurrentPolicy d))
        inl t' = $"time.perf_counter()" : f64
        inl q = t' - t
        $"print('done training -', !q)"
```

Let me try doing it like this.

I'll put this into the old version as well. How long the training for this can be completely faded from my memory.

```
start training
done training - 102.0982556
```

It takes it 102 seconds to run through the main loop. Let me try the old thing.

```
start training
done training - 102.3645013
```

About the same.

```
inl main () =
    inl d = dictm.empty
    inl game = leduc.game()
    inl mult = 100i32
    loopw.for' (from: 0i32 nearTo: 20) fun i =>
        open agent.cfr_sample_learned_infoset
        !!!!Import("time")
        inl t = $"time.perf_counter()" : f64
        $"print('start training')"
        loopw.for' (from: 0i32 nearTo: 100 * mult) fun _ =>
            ignore <| train.run (policy_train d) (policy_cur d) game
            ignore <| train.run (policy_cur d) (policy_train d) game
        inl t' = $"time.perf_counter()" : f64
        inl q = t' - t
        $"print('done training -', !q)"

        inl d_test = dictm.empty
        loopw.for' (from: 0i32 nearTo: 500 * mult) fun _ =>
            ignore <| train.run (policy_train d_test) (policy_avg d) game
        inl num_iterations = 20 * mult
        inl r =
            loopw.for (from: 0i32 nearTo: num_iterations) (fun _ r =>
                r +! train.run (policy_cur d_test) (policy_avg d) game
                ) (r2 0) /! (f64 num_iterations)
        $"print('summary -',!i,!r)"
```

Let me try it like this. The mult is 20x smaller than it should be.

```
start training
done training - 5.024001600000005
```

It is not that bad.

Let me pump it up by 20x. It should be 100s then.

I guess I got impatient, but checking the perf difference is something I should be doing anyway.

I'll let this run for a while. 15m should be enough to give me a sense of where things stand.

```
done training - 99.41757989999999
```

Amazing that it is not any slower despite the closures. Nice.

2:25pm. I guess I'll take a break while this runs.

Let me think. Right now I should not be working on the learned history player before I've done a basic check that learned infoset works as intended.

```
start training
done training - 99.41757989999999
summary - 0 0.11343293060451058
```

Seems about right. Let me read a chapter or two of RI.

```
start training
done training - 99.41757989999999
summary - 0 0.11343293060451058
start training
done training - 97.10497019999997
summary - 1 0.004120978465168313
start training
done training - 94.82315660000006
summary - 2 -0.04218836553832532
```

I think this is right.

In that case, let me stop this here. I'll do the other tabular player next.

3pm.

```
nominal agent_state key2 act = {regret : a u64 f64; avg_policy : a u64 f64; qs : dictm.dict key2 (a u64 wval); actions : a u64 act}
type state key key2 act = dictm.dict key (agent_state key2 act)
inl value (d : state _ _ _) actions = dictm.memoize d fun _ =>
    inl Empty = am.init (length actions) (fun _ => 0)
    agent_state {regret = Empty; avg_policy = Empty; qs = dictm.empty; actions}

inl policy_template is_update epsilon policy_extractor qs_extractor d player_state game_state pid actions =
    inl key = pl2_observations player_state pid
    inl num_actions = length actions
    inl agent_state = value d actions key
    inl policy = regret_match (policy_extractor agent_state)
    inl sample_policy =
        if epsilon = 0 then policy else
        policy |> am.map (fun x => epsilon * (1 / f64 num_actions) + (1 - epsilon) * x)

    inl i' = $"numpy.random.choice(!num_actions,p=!sample_policy)"
    inl p, a = {sample=index sample_policy i'; policy=index policy i'}, index actions i'
    inl sample = p.sample
    (log_prob_from p, a), fun r =>
        inl qs = dictm.memoize agent_state.qs (fun _ => am.init num_actions fun _ => wval (r2 0) 0) (qs_extractor game_state pid)
        inl q_backups s i =
            inl q = ,(index qs i)
            inl r = if i = i' then (r -! q) /! sample +! q else q
            r, s +! r *! index policy i
        match is_update with
        | Some: alpha =>
            inl (u : a _ _),us = am.initFold num_actions q_backups (r2 0)
            inl prob = pl2_probs player_state pid
            inl env_prob = prob.chance +@ prob.op
            inl regret_prob = exp (-prob.self.sample + (env_prob.policy - env_prob.sample))
            set qs i' (index qs i' *, (1 - alpha) +, wval r regret_prob *, alpha)
            agent_state.regret |> am.mapInplace (fun i x => max 0 <| x + regret_prob * !!(index u i -! us) pid)
            inl policy = regret_match agent_state.regret
            inl avg_policy_prob = exp ((prob.self.policy - prob.self.sample) - prob.chance.sample - prob.chance.sample)
            agent_state.avg_policy |> am.mapInplace (fun i x => x + avg_policy_prob * index policy i)
            us
        | None =>
            loop.for (from: 0 nearTo: num_actions) (fun i s => q_backups s i |> snd) (r2 0)

inl policy_avg d = policy_template None 0 (fun x => x.avg_policy) leduc.leduc_state_op_card d
inl policy_cur d = policy_template None 0 (fun x => x.regret) leduc.leduc_state_op_card d
inl policy_train d = policy_template (Some: 2 ** -2) (2 ** -2) (fun x => x.regret) leduc.leduc_state_op_card d
```

Let me give this a try.

3:05pm. While the test runs what should I do next?

Playing against the trained agent in an UI? I do not feel like doing that now.

What I am going to do is run parallel.

That is what I need to do.

That should give me thorough testing.

3:15pm. Hrrrrrmmmm...

Parallel processing is really a poor fit for the current tabular way of doing things.

For these algorithms, I do not want to make 1 thousand moves and do the updates sequentially.

3:40pm. The next step is the parallel training function, but I do not feel like using it on the tabular players.

Right now the realization is finally dawning on me - I am done.

Tabular players are history.

3:50pm. The next step are linear and then neural players.

I know I should put some effort into doing the parallel functions, but forget it. I have no interest in it right now.

The thoughts of working on a neural based player immediatelly lift my mood, it is amazing.

I'll take a break here. I do not feel like programming anymore. I'll take this chance to take a bath and relax.

5:15pm.

```
start training
done training - 97.69538790000001
summary - 0 0.005007626023276979
start training
done training - 93.44818370000002
summary - 1 -0.036868596155139516
start training
done training - 93.49397039999997
summary - 2 -0.02795982722185147
start training
done training - 94.71541470000011
summary - 3 -0.06633460318847537
start training
done training - 93.01731790000008
summary - 4 -0.05003730191567687
start training
done training - 93.45901509999999
summary - 5 -0.052708194402925804
start training
done training - 93.0516703000003
summary - 6 -0.08446659253758126
start training
done training - 93.6244128999997
summary - 7 -0.08889614036338885
start training
done training - 96.38022719999981
summary - 8 -0.05026749833780264
start training
done training - 93.35546900000008
summary - 9 -0.06557887763489405
start training
done training - 91.77145550000023
summary - 10 -0.1026692051639212
start training
done training - 91.03721289999976
summary - 11 -0.0932579413355906
start training
done training - 92.39623800000027
summary - 12 -0.10302741884663426
start training
done training - 90.76150770000004
summary - 13 -0.08421041631521434
start training
done training - 91.40180269999928
summary - 14 -0.05474744293132913
start training
done training - 91.98772709999957
summary - 15 -0.08598070048235892
start training
done training - 92.05979770000067
summary - 16 -0.06081670189864924
start training
done training - 92.04874310000014
summary - 17 -0.098142340585958
start training
done training - 91.82362770000054
summary - 18 -0.11983425942962267
start training
done training - 91.59358539999994
summary - 19 -0.09594201072115098
```

I think that regular policy averaging would work better than the thing I have now. Just what is this thing doing. Despite this many iterations I can't get to what cur policy does by default.

At any rate, I am back. Yeah, the next step is definitely the linear layer. I'll be skipping some intermediate steps to get to it because I am feed up with tabular players.

A linear player does not seem like a big deal, but once I deal with it, I will be over half, maybe 2/3rds done. Once I have the linear agent, it won't be too much work to add extra layers. Since I have my special training method I'll have to hack the backward pass to keep track of various moving averages and such, but that will go through eventually.

I am tired, I am so tired of this. I definitely want a change of pace. Going from programming the computer, to using it to nurture agents is a step that is long overdue for me.

5:25pm. Right now, I am absolute embarassment. Compared to the spirit I showed when working on Spiral, I am a different person entirely.

But it is not hopeless. I feel just a tiny sliver of power when I think about the linear players. So I'll be able to keep going even if it is at a snail's pace.

I am both awed by deep learning's profoundity, and humbled by my own limitations and inability to transcend them. Right now, I am the weakest I've ever been.

But I am going to do it.

Going to deep learning means I can ditch dictionaries and all that other machinery.

Replay buffers are just resizable arrays.

Serialization is a solved problem in Spiral.

5:30pm. Once I train the NN agent for the first time, maybe my motivation will reinvigorate.

Even if I am weak. Even if I cannot program right now, at least I can dream about a stronger me, and that will give me the strength to try again tomorrow."