"2pm. Let me stop resting here and do the chores. I can't believe I am still thinking of how to deal with the data transfer. I am going to simplify things.
2:15pm. Done with chores. Let me get back to it.

2:20pm. Focus me, close down the browser.

2:30pm. Graaaaahhhhh!!!

```
    inl policy_mask : obj = $"torch.full((!len,!actions_size),float('-inf'))"
    am.iteri (fun b => am.iter (fun a => $"!policy_mask[!b,!a] = 0")) action_indices
    inl policy_raw : obj = $"!policy_mask + !policy.forward(!data_value[:,!policy_size])"
    inl policy_probs : obj = $"torch.softmax(!policy_raw,dim=-1)"

    inl policy_probs_detached : obj = $"!policy_probs.detach()"
    inl e = epsilon * (1.0 / f64 (serialization.sparse.int.size schema.actions))
    inl sample_indices : a u64 _ = $"torch.distributions.Categorical(!e + (1.0 - !epsilon) * !policy_probs_detached).sample().numpy()"
    inl policy : a u64 f32 = $"torch.gather(!policy_probs_detached,1,!sample_indices.unsqueeze(-1)).squeeze(-1).numpy()"
    inl l : a _ _ =
        am.map2 (fun policy a =>
            inl policy = f64 policy
            inl sample : f64 = e + (1.0 - epsilon) * policy
            log_prob_from {policy sample}, schema.actions.unpickle a
            ) policy sample_indices
    l, fun (r : a u64 r2) =>
        inl value_raw : obj = $"!value.forward(!data_value)"
        // inl value : a u64 f32 =
        r
```

I want to minize the data transfer done between the CPU and the GPU, but I also want to do most of the work on the GPU. This thing here is really wrecking me.

```
a = torch.zeros(5,requires_grad=True)
a[0] = 3
a
a.backward(torch.tensor([1,2,3,4,5]))
```
```
tensor([3., 0., 0., 0., 0.], grad_fn=<CopySlices>)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Marko\anaconda3\lib\site-packages\torch\tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\Marko\anaconda3\lib\site-packages\torch\autograd\__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: leaf variable has been moved into the graph interior
```

This gives an error.

```
    inl policy_mask : obj = $"torch.full((!len,!actions_size),float('-inf'))"
    am.iteri (fun b => am.iter (fun a => $"!policy_mask[!b,!a] = 0")) action_indices
    inl policy_raw : obj = $"!policy_mask + !policy.forward(!data_value[:,!policy_size])"
```

2:45pm. Hrrmmmm...Ok.

```
inl policy_raw' : obj = $"!policy.forward(!data_value[:,!policy_size]).cpu()"
```

Does this detach it from the graph?

```
$"!!"
```

I just realized this is invalid syntax in macros. Whops. Let me add it to the TODO list.

```
    inl policy_raw : obj = $"!policy.forward(!data_value[:,!policy_size])"
    inl policy_mask : obj = $"torch.full((!len,!actions_size),float('-inf'))"
    am.iteri (fun b => am.iter (fun a => $"!policy_mask[!b,!a] = 0")) action_indices
    inl policy_probs : obj = $"torch.softmax(!policy_mask + !policy_raw.cpu(),dim=-1)"
```

This is right. Though it is annoying, I am going to ensure that data transfers between the CPU and GPU are minimized even if that means doing more work on the CPU.

3:10pm.

```
    inl policy_probs_detached : obj = $"!policy_probs.detach()"
    inl add_noise prob = epsilon / actions_size + (1.0 - epsilon) * prob
    inl sample_probs_detached : obj =
        $"!policy_probs_detached.flatten().numpy()"
        |> am.map add_noise
        |> fun (x : a _ _) => $"torch.from_numpy(!x).reshape_as(!policy_probs_detached)"
    inl sample_indices : obj = $"torch.distributions.Categorical(!sample_probs_detached).sample()"
```

I have this.

```
inl policy : a u64 f32 = $"torch.gather(!policy_probs_detached,1,!sample_indices.unsqueeze(-1)).squeeze(-1)"
```

No need for the gather operations anymore.

```
nominal log_prob = {sample : f64; policy : f64}
```

I'll make these f32.

3:25pm.

```
    inl sample_indices : a u64 _ = $"torch.distributions.Categorical(!sample_probs_detached).sample().numpy()"

    inl l : a _ _ =
        am.mapi (fun b a =>
            inl policy : f32 = $"!policy_probs_detached[!b,!a]"
            inl sample = add_noise policy
            log_prob_from {policy sample}, schema.actions.unpickle a
            ) sample_indices
```

Finally, things should be fine with this.

```
nominal r2 = f64
```

Let me also turn this into f32.

3:25pm. Now things are fine. Amazing how much time the basic forward pass is taking me. But now that I've come this far I finally have enough to do the backward pass.

3:50pm.

```
        inl value_detached : obj = $"!value.detach()"
        am.iteri2 (fun b a (r2 r) =>
            inl policy : f32 = $"!policy_probs_detached[!b,!a]"
            inl sample = add_noise policy
            inl q : f32 = $"!value_detached[!b,!a]"
            $"!value_detached[!b,!a] += (!r - !q) / !sample"
            ) sample_indices r
        $"!value_detached *= !policy_probs_detached"
```

No not like this. I should try to do it all in a single parallel pass...Ah, no.

Also the use of mutation here might cause trouble if that `cpu` call returns a view.

```
https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to
```

Oh, this has an optional copy param.

```
inl value : obj = $"!value.forward(!data_value).to(device='cpu',copy=True)"
```

Ah, damn it. This won't be enough.

> When data is a tensor x, new_tensor() reads out ‘the data’ from whatever it is passed, and constructs a leaf variable. Therefore tensor.new_tensor(x) is equivalent to x.clone().detach() and tensor.new_tensor(x, requires_grad=True) is equivalent to x.clone().detach().requires_grad_(True). The equivalents using clone() and detach() are recommended.

I'll have to clone it.

Set operations really are a lot easier with mutation aren't they?

```
        inl value : obj = $"!value.forward(!data_value).cpu()"
        inl value_detached : obj = $"!value.detach().clone()"
        am.iteri2 (fun b a (r2 r) =>
            inl policy : f32 = $"!policy_probs_detached[!b,!a]"
            inl sample = add_noise policy
            inl q : f32 = $"!value_detached[!b,!a]"
            $"!value_detached[!b,!a] += (!r - !q) / !sample"
            ) sample_indices r
```

Ok, now this makes sense. What I need to do next is calculate the means.

https://pytorch.org/docs/stable/generated/torch.sum.html#torch.sum

I'd want to prevent the multiply from creating a separate matrix.

4:20pm.

```
    l, fun (r : a u64 r2) =>
        inl value : obj = $"!value.forward(!data_value).cpu()"
        inl value_detached : obj = $"!value.detach().clone()"
        am.iteri2 (fun b a (r2 r) =>
            inl policy : f32 = $"!policy_probs_detached[!b,!a]"
            inl sample = add_noise policy
            inl q : f32 = $"!value_detached[!b,!a]"
            $"!value_detached[!b,!a] += (!r - !q) / !sample"
            ) sample_indices r
        inl means : obj = $"torch.sum(!value_detached * !policy_probs_detached,1)"
        inl policy_signal : obj = $"!value_detached - !means.unsqueeze(1)"
        inl value_signal : obj = failwith "TODO"
        $"!means.numpy()" : a u64 r2
```

4:50pm. Had to take a break.

4:55pm. I still can't decide. Do I want to just shove the signals onto the net for efficiency right here? Or do I want to do something fancier?

The plan was to do the first, but that would be inelegant.

```
a = torch.rand((4,5),requires_grad=True)
a[1,2].backward(torch.scalar_tensor(2))
print(a.grad)
```

Let me do it like this then.

```
inl policy_probs : obj = $"torch.softmax(!policy_mask + !policy_raw.cpu(),dim=-1)"
```

Ah, right. Can I tell the log operation it is followed by a softmax?

This is killing me. I am going to have to use the log softmax and exp it later.

5:15pm. Gah, no I can't. I'd rather log it. But that will make it numerically unstable.

Seriously, why isn't there a way to hack this?

5:20pm. No wait. If I think about this, the log_softmax has to keep the softmax values around in order to do the backward pass. Given Python's looseness, I should be able to extract it from the backward function or something else.

Or maybe it exps it itself on the backward pass.

5:40pm. https://github.com/pytorch/pytorch/issues

This thing has 6k open issues.

I can't hack this. I am going to use the log_softmax and then exp it. Yes, this will be unecessarily wasteful. I can also open an issue asking for this.

6pm. https://github.com/pytorch/pytorch/issues/

Opened issue 58822 here. Fat luck getting this implemented amongst the 6k other issues. I might as well be hoping to win a lottery.

Wow it has 2.7k PRs. That is a popular project for you.

6:05pm.

```
inl policy (epsilon : f32) (leduc_net {policy value schema}) l =
    !!!!Import("torch")
    !!!!Import("torch.distributions")

    inl len = length l
    inl policy_size = serialization.dense.array.size schema.policy
    inl value_size = serialization.dense.array.size schema.value
    inl actions_size = f32 (serialization.sparse.int.size schema.actions)

    inl data_value : obj = $"torch.zeros(!len,!value_size)"
    l |> am.iteri fun b (player_state, (leduc_state (p1,p2,community_card)), pid, actions) =>
        inl seq = pl2_observations player_state pid |> obs_to_array
        inl pot = if pid = p1.id then p1.pot else p2.pot
        schema.value.pickle (leduc_policy_input {pid= $"!pid"; pot= $"!pot"; seq},if pid = p1.id then p2.card else p1.card) (0, $"!data_value[!b,:]")
    inl action_indices : a u64 (a u64 _) = l |> am.generic.map fun (_,_,_,actions) => am.map schema.actions.pickle actions
    inl policy_raw : obj = $"!policy.forward(!data_value[:,!policy_size])"
    inl policy_mask : obj = $"torch.full((!len,!actions_size),float('-inf'))"
    am.iteri (fun b => am.iter (fun a => $"!policy_mask[!b,!a] = 0")) action_indices
    inl policy_log_probs : obj = $"torch.log_softmax(!policy_mask + !policy_raw.cpu(),dim=-1)"
    inl policy_probs : obj = $"torch.exp(!policy_log_probs.detach())"

    inl add_noise prob = epsilon / actions_size + (1.0 - epsilon) * prob
    inl sample_probs : obj =
        $"!policy_probs.flatten().numpy()"
        |> am.map add_noise
        |> fun (x : a u64 _) => $"torch.from_numpy(!x).reshape_as(!policy_probs)"
    inl sample_indices : a u64 _ = $"torch.distributions.Categorical(!sample_probs).sample().numpy()"

    inl l : a _ _ =
        am.mapi (fun b a =>
            inl policy : f32 = $"!policy_probs[!b,!a]"
            inl sample = add_noise policy
            log_prob_from {policy sample}, schema.actions.unpickle a
            ) sample_indices
    l, fun (r : a u64 r2) =>
        inl value : obj = $"!value.forward(!data_value).cpu()"
        inl value_sampled : obj = $"!value.detach().clone()"
        am.iteri2 (fun b a (r2 r) =>
            inl policy : f32 = $"!policy_probs[!b,!a]"
            inl sample = add_noise policy
            inl q : f32 = $"!value_sampled[!b,!a]"
            inl dif : f32 = $"!r - !q"
            $"!value[!b,!a].backward(torch.scalar_tensor(!dif))"
            $"!value_sampled[!b,!a] += !dif / !sample"
            ) sample_indices r
        inl means : obj = $"torch.sum(!value_sampled * !policy_probs,1)"
        $"!policy_log_probs.backward(!value_sampled - !means.unsqueeze(-1))"
        $"!means.numpy()" : a u64 r2
```

This should do it.

I've really had to think this one through.

6:15pm. it is easy to say just do the forward and the backward pass, but there is quite a lot of intricacy crammed into this.

```
inl means : obj = $"torch.sum(!value_sampled * !policy_probs,1)"
```

The only thing I could optimize is this. Maybe I should do a jit script function and hope it fuses this.

https://pytorch.org/docs/stable/generated/torch.einsum.html

```
a = torch.ones(3,4)
b = torch.full((3,4),5,dtype=torch.float32)

torch.einsum("ab,ab->a",a,b)
```

Oh, this actually gives me what I want exactly. Nice.

6:30pm. No need to implement a custom loop just for this.

```
inl pot = wrap ((+) -1,(+) 1) (int 13)
```

I think this part might be the opposite of what it should be.

```
inl pot = wrap ((+) 1,(+) -1) (int 13)
```

Yeah, it should be like this. I caught that bug. The second one is in, and the first one is out.

```
inl wrap (in:a out:b) (pu p) =
    pu {size = p.size
        pickle = fun x state => p.pickle (a x) state
        unpickle = fun state => inl x,c = p.unpickle state in b x,c
        }
```

When things get confusing that is the time for keyword args to shine. I finally found the use for these.

6:45pm. Let me stop here. I am being so careful and deliberate to the point of wasting time. When it is time to work I do not feel like it, but when it is time to close, I feel like putting in extra.

I think things are perfect now. Well, minus the potential bugs.

This version is a good first target for the player. The plan is to make this thing work on Leduc, and then move to the following steps.

What are those? In no specific order:

1) Use the transformer architecture.
2) Implement the replay buffer and the training scheme I thought up using it.
3) Hack the linear so I keep track of the variances using moving averages.

Apart from the first, the later two were described in the last monthly PL review.

Tomorrow, I will focus on getting the player to run.

Let me go get lunch."