"1:10m. Done with breakfast. Let me chill for a bit and then come chores. Then I will deal with that side task.
2:10pm. Done with chores. I saw a F# question on the SO, so let me give it a try.

2:20pm. https://stackoverflow.com/questions/60600234/is-there-an-idiomatic-way-in-f-to-reduce-code-duplication-with-nested-if-st

This might be the first time I've given an answer on SO as far as I remember.

Now let me start. I have to do that side job. Focus me, focus.

2:25pm. Ok, let me turn off for a bit here.

2:55pm. This is going ot be a pain in the ass. I am trying to install Ubuntu 14.04 server, and the stupid thing is futilely trying to mount the CD-ROM even though I am installing from USB. This is roughly the par for the usual kind of fuckery I have to deal with when trying to get Linux to work. As it happens the computer has a CD drive, but it seems to be broken. What do I do now?

Do I try to write the USB in DD Image mode? Or something else? I am going to have to do everything in turn.

3:05pm. Let me try DD Image. I'll turn off again.

3:35pm. Just a bit more and I'll be done. Let me turn off again here.

3:55pm. Phew, finally done installing that hotspot. I want to take a break for a while. A batch of Release the Witch chapters came out and I need to chill before I go on the debugging spree.

4:10pm. Wow, the market is down -6.5%. That has not happened in a while. If I were trading right now, I would have taken a long term approach so I would have ridden the rise up and then all the way down with the intention of holding for a few months so I can see how the market digests this news.

You really need a decent stake for this kind of thing, not 3k like I had over half a decade ago.

I doubt the market is just going to collapse even further from here, I'd expect it to bounce over the next month or two. Past that, who knows. It is a definite short-term buy here.

4:30pm. Well, that was my bit of entertainment. Whatever happens, I am not in a position to participate. If a bear market develops I won't be in a position to short, and if it crashes, I won't be in a position to buy cheap. Though I am letting this bother me, I really should not.

4:35pm. Remember the conviction that I had before. Forget the other threads. Just shut them off.

4:40pm. Let me just gather my focus for a bit.

Right now, I feel like it is too late in the day to get any real studying done. Nonetheless, today is when I will start them for real.

And the first step will be to get the `lsp-sample` working with `vscode-languageserver-node` directly.

4:45pm. Focus me. Let me give this a try.

4:50pm. Ok, as the first thing, I need to compile the whole project. Unfortunately, it is giving me a bunch of errors. I have no idea how to deal with them. Let me erase the repo, and I'll try cloning it again.

```
E:\Webdev\vscode-languageserver-node>npm run compile

> vscode-lsp@1.0.0 compile E:\Webdev\vscode-languageserver-node
> npm run compile:types && npm run compile:textDocument && npm run compile:jsonrpc && npm run
compile:protocol && npm run compile:server && npm run compile:client && npm run compile:client-tests

> vscode-lsp@1.0.0 compile:types E:\Webdev\vscode-languageserver-node
> tsc -b ./types/tsconfig.json

types/src/test/edits.test.ts:7:25 - error TS2307: Cannot find module 'assert'.

7 import * as assert from 'assert';
                          ~~~~~~~~

types/src/test/edits.test.ts:12:1 - error TS2582: Cannot find name 'suite'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

12 suite('Edits', () => {
   ~~~~~

...

types/src/test/typeguards.test.ts:188:3 - error TS2582: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
188     test('undefined', () => {
        ~~~~

Found 49 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-lsp@1.0.0 compile:types: `tsc -b ./types/tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-lsp@1.0.0 compile:types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marko\AppData\Roaming\npm-cache\_logs\2020-03-09T15_55_19_669Z-debug.lognpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-lsp@1.0.0 compile: `npm run compile:types && npm run compile:textDocument && npm run compile:jsonrpc && npm run compile:protocol && npm run compile:server && npm run compile:client && npm run compile:client-tests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-lsp@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marko\AppData\Roaming\npm-cache\_logs\2020-03-09T15_55_19_696Z-debug.log
```

...Ahh, I think I need to run `npm install` first.

5pm.

```
E:\Webdev\vscode-languageserver-node>npm run compile

> vscode-lsp@1.0.0 compile E:\Webdev\vscode-languageserver-node
> npm run compile:types && npm run compile:textDocument && npm run compile:jsonrpc && npm run
compile:protocol && npm run compile:server && npm run compile:client && npm run compile:client-tests

> vscode-lsp@1.0.0 compile:types E:\Webdev\vscode-languageserver-node
> tsc -b ./types/tsconfig.json

> vscode-lsp@1.0.0 compile:textDocument E:\Webdev\vscode-languageserver-node
> tsc -b ./textDocument/tsconfig.json

> vscode-lsp@1.0.0 compile:jsonrpc E:\Webdev\vscode-languageserver-node
> tsc -b ./jsonrpc/tsconfig.json

> vscode-lsp@1.0.0 compile:protocol E:\Webdev\vscode-languageserver-node
> tsc -b ./protocol/tsconfig.json

> vscode-lsp@1.0.0 compile:server E:\Webdev\vscode-languageserver-node
> tsc -b ./server/tsconfig.json

> vscode-lsp@1.0.0 compile:client E:\Webdev\vscode-languageserver-node
> tsc -b ./client/tsconfig.json

client/src/codeConverter.ts:418:144 - error TS2694: Namespace '"E:/Webdev/vscode-languageserver-node/client/node_modules/vscode-languageserver-protocol/lib/main"' has no exported member 'DiagnosticCode'.

418  function asDiagnosticCode(value: number | string | { value: string | number; target: code.Uri; } | undefined | null): number | string | proto.DiagnosticCode | undefined {

                                                     ~~~~~~~~~~~~~~

client/src/codeConverter.ts:556:113 - error TS2694: Namespace '"E:/Webdev/vscode-languageserver-node/client/node_modules/vscode-languageserver-protocol/lib/main"' has no exported member 'InsertReplaceEdit'.

556  function asCompletionTextEdit(newText: string, range: code.Range | InsertReplaceRange): proto.TextEdit | proto.InsertReplaceEdit {

                      ~~~~~~~~~~~~~~~~~

client/src/codeConverter.ts:558:17 - error TS2339: Property 'InsertReplaceEdit' does not exist on type 'typeof import("E:/Webdev/vscode-languageserver-node/client/node_modules/vscode-languageserver-protocol/lib/main")'.

558             return proto.InsertReplaceEdit.create(newText, asRange(range.inserting), asRange(range.replacing));
                             ~~~~~~~~~~~~~~~~~

client/src/protocolConverter.ts:225:10 - error TS2339: Property 'DiagnosticCode' does not exist on type 'typeof import("E:/Webdev/vscode-languageserver-node/client/node_modules/vscode-languageserver-protocol/lib/main")'.

225     if (ls.DiagnosticCode.is(diagnostic.code)) {
               ~~~~~~~~~~~~~~

client/src/protocolConverter.ts:226:28 - error TS2532: Object is possibly 'undefined'.

226             result.code2 = { value: diagnostic.code.value, target: asUri(diagnostic.code.target) };
                                        ~~~~~~~~~~~~~~~

client/src/protocolConverter.ts:226:44 - error TS2339: Property 'value' does not exist on type 'string | number'.
  Property 'value' does not exist on type 'string'.

226             result.code2 = { value: diagnostic.code.value, target: asUri(diagnostic.code.target) };
                                                        ~~~~~

client/src/protocolConverter.ts:226:65 - error TS2532: Object is possibly 'undefined'.

226             result.code2 = { value: diagnostic.code.value, target: asUri(diagnostic.code.target) };
                                                                             ~~~~~~~~~~~~~~~

client/src/protocolConverter.ts:226:81 - error TS2339: Property 'target' does not exist on type 'string | number'.
  Property 'target' does not exist on type 'string'.

226             result.code2 = { value: diagnostic.code.value, target: asUri(diagnostic.code.target) };
                                                                                             ~~~~~~

client/src/protocolConverter.ts:475:53 - error TS2694: Namespace '"E:/Webdev/vscode-languageserver-node/client/node_modules/vscode-languageserver-protocol/lib/main"' has no exported member 'InsertReplaceEdit'.

475  function asCompletionRange(value: ls.TextEdit | ls.InsertReplaceEdit): code.Range | InsertReplaceRange {
                                                        ~~~~~~~~~~~~~~~~~

client/src/protocolConverter.ts:476:10 - error TS2339: Property 'InsertReplaceEdit' does not exist on type 'typeof import("E:/Webdev/vscode-languageserver-node/client/node_modules/vscode-languageserver-protocol/lib/main")'.

476     if (ls.InsertReplaceEdit.is(value)) {
               ~~~~~~~~~~~~~~~~~

client/src/protocolConverter.ts:477:4 - error TS2322: Type '{ inserting: undefined; replacing: undefined; }' is not assignable to type 'Range | InsertReplaceRange'.
  Type '{ inserting: undefined; replacing: undefined; }' is not assignable to type 'InsertReplaceRange'.
    Types of property 'inserting' are incompatible.
      Type 'undefined' is not assignable to type 'Range'.

477             return { inserting: asRange(value.insert), replacing: asRange(value.replace) };
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

client/src/protocolConverter.ts:479:4 - error TS2322: Type 'undefined' is not assignable to type 'Range | InsertReplaceRange'.

479             return asRange(value.range);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

client/src/client.ts:1475:4 - error TS2322: Type '{ snippetSupport: true; commitCharactersSupport: true; documentationFormat: MarkupKind[]; deprecatedSupport: true; preselectSupport: true; tagSupport: { valueSet: 1[]; }; insertReplaceSupport: boolean; }' is not assignable to type '{ snippetSupport?: boolean | undefined; commitCharactersSupport?: boolean | undefined; documentationFormat?: MarkupKind[] | undefined; deprecatedSupport?: boolean | undefined; preselectSupport?: boolean | undefined; tagSupport?: { ...; } | undefined; }'.
  Object literal may only specify known properties, and 'insertReplaceSupport' does not exist
in type '{ snippetSupport?: boolean | undefined; commitCharactersSupport?: boolean | undefined; documentationFormat?: MarkupKind[] | undefined; deprecatedSupport?: boolean | undefined; preselectSupport?: boolean | undefined; tagSupport?: { ...; } | undefined; }'.

1475            insertReplaceSupport: true
                ~~~~~~~~~~~~~~~~~~~~~~~~~~

client/src/client.ts:1776:22 - error TS2339: Property 'tagSupport' does not exist on type 'DocumentSymbolClientCapabilities'.

1776    symbolCapabilities.tagSupport = {
                           ~~~~~~~~~~

client/src/client.ts:1838:22 - error TS2339: Property 'tagSupport' does not exist on type 'WorkspaceSymbolClientCapabilities'.

1838    symbolCapabilities.tagSupport = {
                           ~~~~~~~~~~

client/src/client.ts:3398:15 - error TS2339: Property 'complexDiagnosticCodeSupport' does not
exist on type 'PublishDiagnosticsClientCapabilities'.

3398    diagnostics.complexDiagnosticCodeSupport = false;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 16 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-lsp@1.0.0 compile:client: `tsc -b ./client/tsconfig.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-lsp@1.0.0 compile:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marko\AppData\Roaming\npm-cache\_logs\2020-03-09T15_58_04_021Z-debug.lognpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-lsp@1.0.0 compile: `npm run compile:types && npm run compile:textDocument && npm run compile:jsonrpc && npm run compile:protocol && npm run compile:server && npm run compile:client && npm run compile:client-tests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-lsp@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marko\AppData\Roaming\npm-cache\_logs\2020-03-09T15_58_04_049Z-debug.log
```

Now I get this kind of error.

...Oh, it works when I do `npm run symlink` first.

5:10pm.

```
#!/usr/bin/env node

const path = require('path');
const ln = require('./linking');

const root = path.dirname(path.dirname(__dirname));

(async function main() {
 console.log('Symlinking node modules for development setup');

 // protocol folder
 let protocolFolder = path.join(root, 'protocol');
 await ln.tryLinkJsonRpc(protocolFolder);
 await ln.tryLinkTypes(protocolFolder);

 // server folder
 let serverFolder = path.join(root, 'server');
 await ln.tryLinkJsonRpc(serverFolder);
 await ln.tryLinkTypes(serverFolder);
 await ln.tryLinkProtocol(serverFolder);

 // client folder
 let clientFolder = path.join(root, 'client');
 await ln.tryLinkJsonRpc(clientFolder);
 await ln.tryLinkTypes(clientFolder);
 await ln.tryLinkProtocol(clientFolder);

 // test-extension
 let extensionFolder = path.join(root, 'client-tests');
 await ln.tryLinkJsonRpc(extensionFolder);
 await ln.tryLinkTypes(extensionFolder);
 await ln.tryLinkProtocol(extensionFolder);
 await ln.tryLink(extensionFolder, 'vscode-languageserver', path.join('..', '..', 'server'));
 await ln.tryLink(extensionFolder, 'vscode-languageclient', path.join('..', '..', 'client'));
})();
```

I can't believe what they are doing here - symbolic linking of module folders so they end up in `node_modules` folder.

5:15pm. Ok, let me leave this aside for now. This is something I will have to think about for Spiral itself, but there should be way better choices than doing this kind of thing.

Now that everything is building properly, what is next on my agenda?

5:40pm. I am just thinking right now.

I suppose I could make it a project to fit the `lsp-sample` files into this project, but...I am thinking that if I want to really learn something, I should start from there bottom.

As I look at the server files, I feel absolutely swamped! The sheer quantity of the code I have to go through feels like a weight on my shoulder.

6pm. I've been going through the `jsonrpc` project's `main.ts`. There is such a thing as breaking referential transparency, and then there is outright raping it. The stuff here tends towards the later. I can't connect to this code at all.

6:05pm. Without a doubt, if I am going to start building, `jsonrpc` is where I should start.

Previously, I thought I should start from the top rather than bottom, but this stuff with sym linking cooled me down on that idea. Maybe that issue I opened will gain some traction and I will be able to download the package with the sources later.

Right now I am thinking...what if I tried rewriting the stuff in `jsonrpc` in F#? The stuff in here seems completely impenetrable, but if I applied myself, I could potentially make some progress.

After I understand the stuff in the `jsonprc` project then I could make my way upward.

6:15pm. My intention with this will not be to create a faithful reproduction of the VS Code Node project, but rather just to get a feeling for the source. Right now the code by Dirk is completely opaque to me, and this is a big problem.

Yeah, lack of inspiration is a sinister problem. I have no choice but to roll up my sleeves and start shoveling crap around.

6:35pm. Done with lunch. I definitely won't start such an undertaking now. But tomorrow, what I will do is pick a few pieces that I understand and start recreating them.

As a bonus, once I am done with this I will have actually written a server and a client from scratch. Plus it will familiarize myself with Node and .NET internals in this domain.

6:40pm. Let me stop here for the day.

I think I did okay. Yesterday I established my convictions and today I made a firm goal.

For the next month or two it seems, all I will be doing is playing around.

It is a pity that I cannot start work on the typechecker any time soon, but such is the phase of my life that I am in."