"5:20pm. I had my ten minutes of fun.
Let me see what I can do about the parsing. After that no doubt I will have to debug the prepass and the partial evaluation after that. I probably won't manage it all today.

5:30pm.

```
let process_parser_exprs (exprs, in') (d : ParserEnv) =
    let f x s = match x with ParserExpr a -> l "" (unop ErrorNonUnit a) s | ParserStatement a -> a s
    match in' with
    | Some in' -> Ok(List.foldBack f exprs in')
    | None ->
        match List.rev exprs with
        | ParserStatement _ :: _ -> d.FailWith StatementLastInBlock
        | ParserExpr x :: xs -> Ok(List.fold (fun a b -> f b a) x xs)
        | [] -> failwith "impossible"

let rec indentations expr d =
    let i = col d
    let inline if_ op tr s = expr_indent i op tr s

    (many1 (if_ (=) expr) .>>. opt (if_ (<=) in_ >>. if_ (<=) (indentations expr)) >>= process_parser_exprs) d
```

Agh, I have no idea. For the time being, how about I just put `()` at the end? I will definitely come back to this as I will have to figure out why errors are not being propagated properly.

I want to see what errors are there in prepass and peval. If I am lucky maybe I will manage to get get the test to work in the next 30m. I doubt it though.

```
Error trace on line: 3, column: 1 in module test1.
inl b = 10
^
Expected one of: global function

C:\Users\Marko\Source\Repos\The Spiral Language\Testing v0.2\bin\Release\netcoreapp3.1\Testing v0.2.exe (process 9184) exited with code 0.
```

Finally a sensible error.

5:30pm.

```
let test1: SpiralModule =
    {
    name="test1"
    prerequisites=[]
    description="Does it run?"
    code=
    """
inl main () =
    inl a = 5
    inl b = 10
    dyn (a + b)
()
    """
    }
```

```
{ parse = 00:00:00.1792269
  prepass = 00:00:00.0009204
  peval = 00:00:00
  codegen = 00:00:00 }
main has to be present in the last module.

C:\Users\Marko\Source\Repos\The Spiral Language\Testing v0.2\bin\Release\netcoreapp3.1\Testing v0.2.exe (process 5652) exited with code 0.
```

Is it not present?

```
        match env.values.[x.name] with
        | Module l ->
            printfn "%A" l
```

Hmmm, it is empty?

```
{ keywords = Spiral.Prepass+KeywordEnv
  types = map [("test1", TModule (map []))]
  values = map [("test1", Module (map []))] }
```

What the hell? There is literally nothing in it.

```
let rec prepass_top (t_glob : Map<string,TExpr>) (v_glob : Map<string,Expr>) x =
```

Ah, it does not seem that I am actually using this function anywhere in the prepass.

```
Unhandled exception. System.Exception: Compiler error in prepass_top.
   at Spiral.Prepass.prepass_top@275(KeywordEnv keywords, Dictionary`2 dict_rawinline, List`1 errors, List`1 v_new, FSharpFunc`2 value_add_local, FSharpMap`2 t_glob, FSharpMap`2 v_glob, RawExpr x) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Prepass.fs:line 302
```

```
    let rec prepass_top (t_glob : Map<string,TExpr>) (v_glob : Map<string,Expr>) x =
        let assert_free_vars_empty env =
            env.value.free_vars |> Seq.iter (fun kv -> errors.Add(ErMissingValueVar kv.Key))
            env.type'.free_vars |> Seq.iter (fun kv -> errors.Add(ErMissingTypeVar kv.Key))
        match x with
        | RawLet(a,b,on_succ) ->
            let env = {type'=env t_glob; value=env v_glob}
            let b = prepass_value env b
            assert_free_vars_empty env
            v_new.Add(a,b)
            prepass_top t_glob (Map.add a b v_glob) on_succ
        | RawRecBlock(l,on_succ) ->
            let r,v_glob =
                Array.mapFold (fun env (k,_) ->
                    let r = ref Unchecked.defaultof<_>
                    let r' = Glob r
                    v_new.Add(k,r')
                    r, Map.add k r' env
                    ) v_glob l
            let env = {type'=env t_glob; value=env v_glob}
            Array.iter2 (fun r (_,e) -> r := prepass_value env e) r l
            assert_free_vars_empty env
            prepass_top t_glob v_glob on_succ
        | RawModuleOpen(a,b,on_succ) ->
            let t,v = module_open (t_glob, v_glob) a b
            prepass_top t v on_succ
        | RawB -> ()
        | _ -> failwith "Compiler error in prepass_top."
```

Ok, so what is it getting here?

```
Unhandled exception. System.Exception: Compiler error in prepass_top.
Got: RawPos RawB
```

Ah, for fuck's sake.

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'to' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Spiral.Prepass.prepass@310.Invoke(PrepassError x) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Prepass.fs:line 325
```

```
            | ErLocalShadowsGlobal x ->
                show_position b var_positions.[x]
                b.AppendFormat("Error: Local variable {0} shadows the global of the same name.", x) |> ignore
```

That would be this. And indeed I am using `to` in the core library.

Why are var positions not...

Ah, yes. I am only adding the vars to the dictionary. Not the bindings - because how could those ever raise an error. Like this apparently.

I am going to have to rename `to` to something else, as `to` is too frequently used in ranges.

```
    let pat_var = small_var' |>> fun x -> if is_box then PatBoxVar x else PatVar x
    let pat_active pattern = exclamation >>. ((small_var' |>> v) <|> rounds expr) .>>. pattern |>> PatActive
    let pat_union pattern = pipe2 big_var' (many ((small_var' |>> PatVar) <|> rounds pattern)) (fun a b -> PatUnion(a,b))
    let pat_value = (value_ |>> PatValue) <|> (def_value_ |>> PatDefaultValue)
    let pat_record_item pattern =
        let inline templ var k = pipe2 var (opt (eq' >>. pattern)) (fun a -> function Some b -> k(a,b) | None -> k(a,PatVar a))
        templ small_var' (fun (str,name) -> PatRecordMembersKeyword(str,name)) <|> templ (dollar >>. small_var') PatRecordMembersInjectVar
```

I should be using `small_var` instead of `small_var'` in quite a few places it seems.

```
    let pat_keyword_fun l = concat_keyword (fun str -> function Some pat -> pat | None -> PatVar str) l
    let pat_keyword pattern = many1 (keyword' .>>. opt pattern) |>> (pat_keyword_fun >> PatKeyword) <|> pattern
```

Right, I forgot about this. I really should be adding positional information everywhere.

5:50pm.

```
Error: Variable ~!!!! not found in the environment.Error trace on line: 177, column: 18 in module Core.
        else !!!!EQ(a,b)
                 ^
Error: Variable EQ not found in the environment.

C:\Users\Marko\Source\Repos\The Spiral Language\Testing v0.2\bin\Debug\netcoreapp3.1\Testing v0.2.exe (process 4512) exited with code 0.
```

And I broke everything.

```
let expressions s = (expressions (raw_expr false) |> operators_unary |> application_tight |> application |> operators) s
```

Let me swap the precedence of unary operators and tight application.

In fact, maybe it would be good to just put unary operators into the expressions themselves.

6pm.

```
let inbuilt_op expr =
    (exclamationx4 >>. big_var) .>>. (rounds (sepBy1 (expr <|> (type' |>> RawType)) comma))
    >>= fun (a, b) d ->
        match string_to_op a with
        | true, op' -> Ok(RawOp(op',List.toArray b))
        | false, _ -> d.FailWith(InbuiltOpNotFound a)

let operators_unary expr =
    choice [|
        type' |>> RawType
        inbuilt_op expr
        pipe2 (opt unary_op) expr (fun op e -> match op with Some op -> ap (v op) e | None -> e)
        |]
```

Would something like this be fine.

6:05pm.

```
Error trace on line: 82, column: 16 in module Core.
inl (`=) a b = !EqType(a,b)
               ^
Error: Variable ~! not found in the environment.Error trace on line: 82, column: 17 in module Core.
inl (`=) a b = !EqType(a,b)
                ^
Error: Variable EqType not found in the environment.Error trace on line: 112, column: 25 in module Core.
inl string_slice x from:to: = !!!!StringSlice(x,from,to)
                        ^
Error: Local variable to shadows the global of the same name.Error trace on line: 134, column: 12 in module Core.
        if lit_is c then error_type
           ^
Error: Variable lit_is not found in the environment.Error trace on line: 146, column: 8 in module Core.
    if lit_is a && lit_is b then op a b
       ^
Error: Variable lit_is not found in the environment.

C:\Users\Marko\Source\Repos\The Spiral Language\Testing v0.2\bin\Debug\netcoreapp3.1\Testing v0.2.exe (process 6496) exited with code 0.
```

Now I am getting the prepass errors properly. Nice.

6:05pm.

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'default_value' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Spiral.Prepass.prepass@310.Invoke(PrepassError x) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Prepass.fs:line 313
```

What is this?

```
let def_value' x = ap (v "default_value") (lit_string x)
```

Hmmm, this is strange.

```
let def_value' x = RawDefaultValue x
```

Ok...let me add `RawDefaultValue`.

6:15pm. Done with that part. Now I am debugging partial eval errors.

```
    | UnitTest(a,on_succ,on_fail)->
        match v a with
        | TyB -> ev d on_succ
        | _ -> ev d on_fail
```

Here it is trying to access a null reference.

6:20pm. Ah, I get it. Shit. What is going on here is that it is expecting the unit to be in the first place, and is testing for it.

I'll fix this right away.

```
| Some (Inl(a,b)) ->
```

Rather than diving into this right away, what I should do is evaluate the application of this.

```
                let d : LangEnv = {
                    trace = []
                    seq = seq
                    cse = [Dictionary(HashIdentity.Structural)]
                    i = ref 0
                    env_global_type = [||]
                    env_global_value = [||]
                    env_stack_type = [||]
                    env_stack_type_ptr = 0
                    env_stack_value = [||]
                    env_stack_value_ptr = 0
                    }

                let _ : Data = timeit timings.peval <| fun _ -> partial_eval_value dex d (Op(Apply,[|a;B|]))
```

Let me try doing it like this.

```
{ parse = 00:00:00.2354414
  prepass = 00:00:00.0246552
  peval = 00:00:00.0526984
  codegen = 00:00:00.0196183 }
let ((var_0 : int64)) = 15L

C:\Users\Marko\Source\Repos\The Spiral Language\Testing v0.2\bin\Debug\netcoreapp3.1\Testing v0.2.exe (process 1312) exited with code 0.
```

Wooooooooooooooo!!!

It finally works!!!

6:25pm. This is nice. Not only did I finish the core library, but I also got the first example to run.

Tomorrow I am going to see whether I can get rid of the need to append () at the end of every module, and after that I will continue with the further examples.

6:35pm. I've already wound down and am wondering whether I should put a few words in.

I've been thinking about math lately. I told myself never again, and indeed I am never touching pure math again.

When I am done with this whole Spiral thing in a year or two, what I should do is study physics. If I am going to break the backprop induced stalemate, I am going to need some inspiration, and what better way to get it than to study actual physical systems.

At this point I have programming mostly wrapped up.

Only ML is really giving me trouble and this whole thing is going to come to a head eventually.

Spiking NNs will be a battering ram once I get access to them, so I should make sure to aim it properly. This time. No more of the same embarrassing bullshit like in 2018 where I have enormous inspiration that just dies every time. Also no more schizophrenic pestering of various authors. I got my fill of that to last me a lifetime. I definitely regret that one.

6:40pm. For the next year or so, I'll aim to rescue Intel/some other random startup from having to write their libraries all in C.

For once I am going to have to get a job, no way around it, so the ideal outcome would be to get early access to these neurochips after Spiral is in a decent state. This would get me funds that I could not get through RL, the opportunity to upgrade my rig in addition to the those chips that I need, and would place the in the very near vicinity of where all this is going to blow up.

Fundamentally, since GPUs are a bust, these chips are what I should be playing with.

I need to absolutely aim for this.

Spiral v0.2 is what is going to get me through the door, so I should not hesitate to complete it."