"1:20pm. Done with breakfast. Since it is pouring outside, I'll leave chores for later.
Let me figure out how to deal with the VS Code C plugin.

1:30pm. Hmmm, I do a two line program and it compiles it to a 2k line C file. Poor show. I'll consider a backend myself at some point. The `.c` file is including "Python.h" which the compiler cannot find. I am going to have to use the form in `setup.py` to get this to work.

Let me just try out a simple hello word program in C. I want to make sure that it works.

Ah, the edit configuration(UI) is in the command palette.

And I can build the file from it as well. Nice.

1:40pm. file:///C:/Users/Marko/Source/Repos/The%20Spiral%20Language/Spiral%20Compilation%20Tests/cython_experiments/test1/test.html

```python
x = 10
print(x)
```

Here is the Python file. Here is what I see in the browser.

```
+1: x = 10
  if (PyDict_SetItem(__pyx_d, __pyx_n_s_x, __pyx_int_10) < 0) __PYX_ERR(0, 1, __pyx_L1_error)
+2: print(x)
  __Pyx_GetModuleGlobalName(__pyx_t_1, __pyx_n_s_x); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 2, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  if (__Pyx_PrintOne(0, __pyx_t_1) < 0) __PYX_ERR(0, 2, __pyx_L1_error)
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
```

This html is really helpful for seeing what gets generated. The generated code is ugliness itself though.

Let me do that loop from the video.

```py
def test(x):
    y = 0
    for i in range(x):
        y += i
    return i

print(test(5))
```

Was this it?

Let me check the vid.

1:45pm. Yeah, that was it. Let me make an annotated version next.

```
cpdef int test(int x):
    cdef int y = 0
    cdef int i
    for i in range(x):
        y += i
    return i
```

Now what does Cython say about this?

```
+1: cpdef int test(int x):
static PyObject *__pyx_pw_4test_1test(PyObject *__pyx_self, PyObject *__pyx_arg_x); /*proto*/
static int __pyx_f_4test_test(int __pyx_v_x, CYTHON_UNUSED int __pyx_skip_dispatch) {
  int __pyx_v_y;
  int __pyx_v_i;
  int __pyx_r;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("test", 0);
/* … */
  /* function exit code */
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* Python wrapper */
static PyObject *__pyx_pw_4test_1test(PyObject *__pyx_self, PyObject *__pyx_arg_x); /*proto*/
static PyObject *__pyx_pw_4test_1test(PyObject *__pyx_self, PyObject *__pyx_arg_x) {
  int __pyx_v_x;
  PyObject *__pyx_r = 0;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("test (wrapper)", 0);
  assert(__pyx_arg_x); {
    __pyx_v_x = __Pyx_PyInt_As_int(__pyx_arg_x); if (unlikely((__pyx_v_x == (int)-1) && PyErr_Occurred())) __PYX_ERR(0, 1, __pyx_L3_error)
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("test.test", __pyx_clineno, __pyx_lineno, __pyx_filename);
  __Pyx_RefNannyFinishContext();
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_r = __pyx_pf_4test_test(__pyx_self, ((int)__pyx_v_x));
  int __pyx_lineno = 0;
  const char *__pyx_filename = NULL;
  int __pyx_clineno = 0;

  /* function exit code */
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

static PyObject *__pyx_pf_4test_test(CYTHON_UNUSED PyObject *__pyx_self, int __pyx_v_x) {
  PyObject *__pyx_r = NULL;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("test", 0);
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_f_4test_test(__pyx_v_x, 0)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 1, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_r = __pyx_t_1;
  __pyx_t_1 = 0;
  goto __pyx_L0;

  /* function exit code */
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_AddTraceback("test.test", __pyx_clineno, __pyx_lineno, __pyx_filename);
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
```

It compiles it fine. But looking at the above, I have absolutely no idea how much of this bloat is necessary. if I have to do all this, the task of dealing with the Python runtime system will be very hard indeed.

I'd be better off just compiling to cython.

Let me make `setup.py`. I need to see if I can go through it.

```
(base) PS C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\test1> python setup.py build_ext --inplace
Compiling test.pyx because it changed.
[1/1] Cythonizing test.pyx
C:\Users\Marko\anaconda3\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\test1\test.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'test' extension
error: Unable to find vcvarsall.bat
```

It is trying to find the MSVC compiler. I am going to have to instruct Cython to look for the right thing. Forget the video for a while here. Let me read the docs again.

> Run the cython command-line utility manually to produce the .c file from the .pyx file, then manually compiling the .c file into a shared object library or DLL suitable for import from Python. (These manual steps are mostly for debugging and experimentation.)

Ok, let me try compiling it manually then...but what do I do about that `python.h` include?

https://stackoverflow.com/questions/60322655/how-to-use-cython-on-windows-10-with-python-3-8

> You need to get a supported compiler. MinGW works only till Python3.4:
> Is this just the usual issue that you need need a specific version of the Windows compiler to match the one Python was built with wiki.python.org/moin/WindowsCompilers

So I wasted my time installing MingW.

https://wiki.python.org/moin/WindowsCompilers

> Each Python version uses a specific compiler version (e.g. CPython 2.7 uses Visual C++ 9.0, CPython 3.3 uses Visual C++ 10.0, etc). So, you need to install the compiler version that corresponds to your Python version :

So I should not have even tried MingW.

> Visual Studio 2019 contains Visual C++ 14.2 compiler. The setuptools Python package version must be at least 34.4.0.

Since I have VS I might as well try getting this to work.

https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160

Such confusion. Let me read this.

"c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools"

Ah, I see it. There are bat files to run the dev env from the command line here.

> More command files are available to set up specific build architectures. The command files available depend on the Visual Studio workloads and options you've installed. In Visual Studio 2017 and Visual Studio 2019, you'll find them in the VC\Auxiliary\Build subdirectory.

I don't have any here. I guess I'll install the C stuff for VS.

It is 1.25Gb it seems. Maybe 5gb in total if the space estimate is taken seriously.

...Did I do something stupid again? I could have just installed it standalone and it would have saved me a lot of space.

https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#create-your-own-command-prompt-shortcut

> %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

I've been wondering how to do this.

2:35pm. Let me do the chores here since I am just waiting for the install to finish.

https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#in-this-section

There are a bunch of tutorials I'll go through after MSVC is installed. I'll also have to configure the VS Code editor to use it. That will be my first challenge.

3:10pm. Done with chores.

I see the thing has installed. Now, let me see how to compile things from the command line with MSVC. Then I'll configure the plugin.

3:15pm. Focus me, focus. The tasks I have to do today are merely time intensive. They aren't difficult in of themselves.

After I clear this hurdle I'll already be able to start work on the Cython backend. But I'll want to take some time to look into how Python's runtime system works.

This is it - this is the hardship. Such a heavy feeling, like the weight of the world is pressing down on me. It is like trying to run while carrying a boulder.

I can accept it.

The difference between me during my trading days, and the difference between me and during my school days is that back then I endured harship, but I could not accept it.

So what if my efforts do not get recognized. So what if my attempts to get to get a sponsor fail.

So what if by the time I have enough power to cast the Necromutation spell I am a withered husk. So what if ahead of me is a life of disappointment and tragedy.

As long as there is even a tiny bit of hope that I can exceed human limitations I will spare no effort at chasing it. It does not matter if I have to give up sanity. I will shed my humanity in the end or die trying.

The original self improvement method requires post-Singularity technology, and the refined one requires me to abandon common sense. They might be harsh, but to me they are hope itself. I want to live in an era where technology becomes magic. If my life can contribute towards bringing it about, then let it be so. I will sacrifice it all for it.

3:25pm. I'll plan for the worst, and hope this universe sends a bit of luck my way. Because the literal worst would kill me pretty quickly.

It is a meme. It is not really possible to plan or accept the worst.

The most it is possible is to accept the toil.

Let me start this thing instead of philosophizing.

```
C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\test1\hello.c : fatal error C1083: Cannot open compiler generated file: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\hello.obj': Permission denied
```

This whole thing is annoying.

Forget this. Right now I do not know how to deal with having to run the command line in an env. I'd like to run it inside VS Code if possible.

I have no idea how to deal with the fact that both Anaconda and MSVC have their own separate envs.

https://code.visualstudio.com/docs/cpp/config-msvc

Let me try configuring the plugin.

> From the Developer Command Prompt, create an empty folder called "projects" where you can store all your VS Code projects, then create a subfolder called "helloworld", navigate into it, and open VS Code (code) in that folder (.) by entering the following commands:

Ah, interesting. I won't have to do this every time will I?

3:40pm. I managed to compile it by opening VS Code like so.

> If on Windows with Visual Studio installed, or if a compiler is specified in the compilerPath setting, it is not necessary to list the system include paths in this list.

Now the includes are broken. This is not working for me.

Maybe I just need to restart here. Let me try it.

3:55pm. Nope. That did shit.

Let me try running the thing in Visual Studio itself.

Yeah, there it works.

> https://code.visualstudio.com/docs/cpp/config-msvc#_check-your-microsoft-visual-c-installation

I'll try filling in the options manually. Who knows why it can't find the include right now.

```json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "cStandard": "gnu11",
            "cppStandard": "c++17",
            "intelliSenseMode": "msvc-x64",
            "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"
        }
    ],
    "version": 4
}
```

Let me try setting the compiler as this suggests.

4:05pm. Yes, things work now, although the tooltip does not show me the descriptions for library functions.

Well, nevermind. It is not like I am going to be doing C++ programming here.

Now the plugin has been setup.

Now I should figure out how to make cythonize work. It would be great if I could pass in the compiler path directly...

```
PS C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests> conda activate base
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Running setup.py tries to run `coda activate`. So it should have been put in path. Or I should run it from the dev prompt.

```
%windir%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy ByPass -NoExit -Command "& 'C:\Users\Marko\anaconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\Users\Marko\anaconda3' "
```

This is what happens at the start.

Ah, I see...I just have to run `C:\Users\Marko\anaconda3\shell\condabin\conda-hook.ps1` and then do `conda activate base`.

What was the command I have to run again?

`python setup.py build_ext --inplace`

Let me try running this.

It worked!

I can try running the `.pyd` file now!

Let me see how the video did it.

```py
import timeit

cy = timeit.timeit("test_cy.test(5000)", setup="import test_cy", number=1000)
py = timeit.timeit("test_py.test(5000)", setup="import test_py", number=1000)

print(py, cy)
print("Cython is {} times faster than Python.".format(py/cy))
```

Let me try running this.

Had to recompile it after renaming, but it worked.

```py
import test_cy
print(test_cy.test(300))
```

This kind of regular importing works as well. Ok.

4:30pm.

```
PS C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests> conda activate base
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I open a new terminal and this command auto executes. Why is this happening?

Ah, it only happens when the Python plugin is active. But the problem is that the hook needs to run first.

https://medium.com/@udiyosovzon/how-to-activate-conda-environment-in-vs-code-ce599497f20d

> Now you need to change the workspace settings in VS code so it will run these commands for your every time you start a terminal.

```json
"terminal.integrated.shellArgs.windows": ["/K", "C:/Users/Marko/anaconda3/shell/condabin/conda-hook.ps1"]
```

Let me try setting it to this. Now it should activate the conda env at the start.

...No this does not work. Powershell craps out with this.

```
%windir%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy ByPass -NoExit -Command "& 'C:\Users\Marko\anaconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\Users\Marko\anaconda3' "
```

Let me try putting in the stuff here.

```
"terminal.integrated.shellArgs.windows": ["'C:/Users/Marko/anaconda3/shell/condabin/conda-hook.ps1'"]
```

Let me try doing it just like this.

Ah, if I point it at a script it exists immediately.

```
"terminal.integrated.shellArgs.windows": ["-ExecutionPolicy ByPass -NoExit -Command \"& 'C:\\Users\\Marko\\anaconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate 'C:\\Users\\Marko\\anaconda3' \""]
```

I should have just put the extra slashes myself. Let me do it like this.

```
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe '-ExecutionPolicy ByPass -NoExit -Command "& 'C:\Users\Marko\anaconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\Users\Marko\anaconda3' "'" terminated with exit code: 1.
```

This is the error message. This is wrong. It is surrounding the thing in ''.

```
"-ExecutionPolicy", "ByPass", "-NoExit", "-Command", "& 'C:\\Users\\Marko\\anaconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate 'C:\\Users\\Marko\\anaconda3' \""
```

Let me try it like this.

```
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe '-ExecutionPolicy ByPass -NoExit -Command "& 'C:\Users\Marko\anaconda3\shell\condabin\conda-hook.ps1' ; conda activate 'C:\Users\Marko\anaconda3' "'" terminated with exit code: 1.
```

4:55pm. Finally figured it out.

```
"-ExecutionPolicy", "ByPass", "-NoExit", "-Command", "& 'C:\\Users\\Marko\\anaconda3\\shell\\condabin\\conda-hook.ps1' ; conda activate 'C:\\Users\\Marko\\anaconda3'"
```

This works.

```
    "terminal.integrated.shellArgs.windows": [
        "-ExecutionPolicy", "ByPass", "-NoExit", "-Command", "& 'C:/Users/Marko/anaconda3/shell/condabin/conda-hook.ps1' ; conda activate 'C:/Users/Marko/anaconda3'"
    ]
```

This works as well.

```py
from distutils.core import setup
from Cython.Build import cythonize
import os

path = "test_cy.pyx" # os.path.join(os.path.dirname(__file__),"test_cy.pyx")
setup(ext_modules=cythonize(path))
```

I've even set it to use the file directory as the default python directory.

Ok.

It took a ton of time, but I finally managed to get through this.

Now I can use Cython. I am just at the starting gate here.

What I need to do next is look through the docs.

5:20pm. https://www.youtube.com/watch?v=yr6E7FwK_Hw
Talk: Elizaveta Shashkova - The Hidden Power of the Python Runtime

Cython docs are not particularly interesting to me. What I should be studying next in the Python runtime. I'd like a little tutorial on how to use Python from C. I want to know a little bit about this at least before I decide to commit to building a Cython backend.

That I am doing this is definitely a victory of Python, not so much over Spiral, but over myself.

5:25pm. I am tired at this point. Let me watch this talk and I will call it a day.

5:30pm. Yeah, the next thing I have to do is to have Cython + C with Python runtime fight it out in my head.

I'd really prefer Cython, but the code it produces is just so ugly.

5:45pm. Forget this talk. Let me read about using Python from C. I am strongly leaning towards Cython right now. Despite all of its disadvantages, chosing a target that has a sensible introp with Python is a good idea.

https://docs.python.org/3/extending/extending.html
https://docs.python.org/3/extending/embedding.html

> To support extensions, the Python API (Application Programmers Interface) defines a set of functions, macros and variables that provide access to most aspects of the Python run-time system. The Python API is incorporated in a C source file by including the header "Python.h".

Where do I get this `Python.h`?

https://cython.readthedocs.io/en/latest/src/tutorial/cdef_classes.html

I can use this to implement unions in Cython.

Does it have anything for C tuples?

https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#types

`cdef (double, int) bar`

Oh, nice.

Let me make a thread on the PL sub asking about Cython vs C + Python runtime.

https://www.reddit.com/r/Python/comments/kjxq9l/accelerating_python_on_gpus_with_nvc_and_cython/
https://www.reddit.com/r/learnpython/comments/j20gj2/why_isnt_cython_more_popular/

I found these while looking up Cython.

6:30pm. https://www.reddit.com/r/ProgrammingLanguages/comments/l43rtq/would_it_be_worth_it_to_do_a_c_backend_that_uses/

I made this one.

7:05pm. Done with lunch. Let me call it a day here. Tomorrow, I'll start work on a Cython backend."