"11:15am. I am up. I spent a long time in bed today it seems. Let me chill a bit and then I will start. I am rather tense right now.
Yeah, I am afraid of this next part. There is so much I do not understand in ML. My programmer's intuition is not good enough to pierce through it. So I will have to take risks. And I hate that.

11:30am. Agh, who can start right now? I do not feel like it. Let me have my fun and then I'll do it properly after breakfast. No point in trying to fit an hour of work here. The most important thing for is to work up the nerve to start.

11:50am. Let me open the editor. I think right now is the ideal time to put that `ToCythonRecord` op that I've been meaning to.

```
rm.add buffer $"{'trace': !trace, 'reward': !reward, 'prob_self': !prob_self, 'prob_op': !prob_op, 'actions': !actions}"
```

Writing this out by hand like so is just too much.

```
        | EOp(_,ToCythonRecord,[a]) ->
            match term s a with
            | DRecord _ & a -> push_op_no_rewrite s ToCythonRecord a (YMacro [Text "object"])
            | a -> raise_type_error s $"Expected a record.\nGot: {show_data a}"
```

Let me go with this here. The next thing is to do it in the codegen.

```
| ToCythonRecord,[DRecord x] -> Map.foldBack (fun k v l -> $"'{k}': {tup v}" :: l) x [] |> String.concat ", " |> sprintf "{%s}"
```

Not hard to do.

Let me try it out.

```
inl obj forall t. (x : t) : obj = !!!!ToCythonRecord(x)
```

I'll put this into base.

Actually, maybe I should name it record.

12:05pm.

```
inl main () : () =
    !!!!Import("ui_leduc")
    inl root : obj = $"ui_leduc.root"
    let human_dispatch (((p1,p2,card : leduc.game_state),observations),dist,(next : _ -> ())) : () =
        {
        trace = agent.human.show_trace p1.id observations
        actions =
            inl actions = mut {fold= $"False"; call= $"False"; raise= $"False"}
            dist |> am.iter (fun x =>
                open leduc
                match x with
                | Fold => actions.fold <- fun () => next x
                | Call => actions.call <- fun () => next x
                | Raise => actions.raise <- fun () => next x
                )
            record *actions
        table_data =
            inl show_card =
                open leduc
                function King => 'K' | Queen => 'Q' | Jack => 'J'
            record {
                my_card = show_card p1.card
                my_pot = p1.pot
                op_card = show_card p2.card
                op_pot = p2.pot
                community_card = match card with Some: c => show_card c  | None => ' '
                }
        } |> fun r => $"!root.data = !r"
    inl p1 = agent.neural.create(agent.neural.create_net())
    inl p2 = agent.human.create human_dispatch
    inl f (): () =
        open nodes
        leduc.game (nodes.cps.nodes_2p (p1.funs, p2.funs)) ((p1.init,p2.init),fun r => ())
    $"ui_leduc.start_game(!f)"
```

It looks nicer immediatelly. Let me give this a try.

```
   File "<string>", line 92, in <module>
 TypeError: 'ui_test.Tuple4' object is not subscriptable
 Exception ignored in: 'ui_test.method26'
```

Ugh.

```
v0.data = Tuple4(v22, v28, v12)
```

Ah, I see. I forgot a record.

Yeah, it works. Let me do the other thing.

```
        inl reward = x.game_state |> fst |> fun {card id pot} => if id = 0 then x.reward else -(x.reward)
        inl reward = pstr (x.reward : f64)
```

What the hell am I doing here? I completely missed the point of getting the reward of the current player.

```
inl main () =
    !!!!Import("ui_replay")
    inl buffer : ra u64 obj = am.empty
    inl p1 = agent.neural.create_buffer (agent.neural.create_net()) fun x =>
        open leduc
        inl show_card = function
            | King => "[color=ff0000]K[/color]"
            | Queen => "[color=ff0000]Q[/color]"
            | Jack => "[color=ff0000]J[/color]"
        inl show_action = function
            | Fold => "F"
            | Call => "C"
            | Raise => "R"
        open nodes
        inl pstr x = $"'{:.5f}'.format(!x)" : string
        {
        trace =
            inl trace : ra u64 _ = am.empty
            listm.iterBack ((function Observation: x => show_card x | Action: x => show_action x) >> rm.add trace) x.player.observations
            inl op_card = x.game_state |> snd |> fst |> fun {card id pot} => show_card card
            rm.add trace $"f' (vs. {!op_card})'"
            rm.join' "" trace
        reward = x.game_state |> fst |> fun {card id pot} => pstr (if id = 0 then x.reward else -(x.reward) : f64)
        prob_self = pstr (exp_log_prob x.player.probSelf)
        prob_op = pstr (exp_log_prob x.player')
        actions =
            inl trace : ra u64 _ = am.empty
            am.iter (show_action >> rm.add trace) x.actions
            rm.join' "" trace
        } |> record |> rm.add buffer
    inl p2 = agent.uniform.createEnum()
    inl populate_call () =
        leduc.game (nodes.nodes_2p (p1.funs, p2.funs)) (p1.init,p2.init) |> ignore
        buffer
    $"ui_replay.run(!populate_call)"
    ()
```

Let me give this a try. Yeah, it works.

Ok, this is good.

Yes, I am starting to get into it.

...Let me change the dictionary `toArray` a bit. Ah, it is `u64` in dim. Nevermind. It is fine.

12:35pm. This is a good bit of work as an icebreaker. My next goal should be to deal with tabular full CFR+. I'll want to make an UI to do a single iteration of training and then display the state of the dictionary.

12:40pm. After that I'll plug the optimizing agents into the game itself. I'll want to reuse what I've done in ui_test.

That should be a good goal. After that I'll repeat the same with sampling agents.

After that come the big leagues - trained neural agents! For those, I won't bother with full CFR like in my original plan. Instead I'll do the sampling version right off the bat.

Once I manage this, I'll be able to smoothly move to flop holdem and then to the full thing.

After that I'll have my first expert trained agent.

It will take about a few days of full time training before I feel confident about using in the real world.

I'll start off small, and then use transfer learning to initialize bigger nets.

I am going to have a real beast after doing this for a while.

12:50pm. Let me stop here. I have my path, now I just need follow it. Nothing will stop me from succeeding at this in 2021. Nothing!"