"9:25am. I am up. Let me change some things from yesterday. I'll remove the RNN link from the resume as it was not the optimized RNN that I did. That thing is buried in a past commit somewhere.
...Oh, it has been removed. It seems I fixed that already. Good. Let me just make sure that runtime casting has no overhead.

```
import numpy
cimport numpy
cdef class Tuple0:
    cdef readonly signed long v0
    cdef readonly double v1
    def __init__(self, signed long v0, double v1): self.v0 = v0; self.v1 = v1
cdef class Tuple1:
    cdef readonly signed long v0
    cdef readonly double v1
    cdef readonly double v2
    def __init__(self, signed long v0, double v1, double v2): self.v0 = v0; self.v1 = v1; self.v2 = v2
cpdef void main():
    cdef numpy.ndarray[object,ndim=1] v0
    cdef Tuple1 v1
    v0 = numpy.empty(10,dtype=object)
    v0[0] = Tuple0(1, 2.000000)
    v1 = v0[0]
```

Will this give me an error at runtime?

```
TypeError: Cannot convert testm.Tuple0 to testm.Tuple1
```

It does a checked cast.

```
v1 = <Tuple1>v0[0]
```

I can disable them like so though.

9:35am. Let me see if there have been any updates in the issues I opened yesterday.

Ok, the size 0 bug has been known for a while.

10:10am. Did some talking in the Cython issues.

What a waste of time this is. It took me 4 days to do the backend, and the array issue and Cython limitations wasted a few extra of them. I am done with this garbage. I do not care if there is a performance impact from safe casting. I'll stick with this.

Let me chill a bit today. I want to watch some Cython talks. After that I'll ease myself into ML. I do not want to bother myself with interviews for the rest of the week.

Forget Spiral. I finally fixed the 64-bit array, string and hashing issues. The codegen isn't doing any usafe conversion under the hood that could corrupt data at runtime.

Spiral is done.

TODO: Monadic syntax.
TODO: Autocomplete.
TODO: Highlight unused vars.
TODO: List and array patterns and literals.
TODO: Guard against stack overflows in the partial evaluator. Try running it on a separate thread.
TODO: Make literal suffices (such as `i64`) be highlighted differently from the rest of the number.
TODO: Make a VS Code theme for Spiral.
TODO: Spiral build option: Compile monomorphic functions in file. This will allow modules to be compiled as C style libraries. Monomorphic functions would be compiled without name mangling.

I will these TODOs far later.

10:15am. I do not want to think about the compiler, applying to companies or boosting my prestige. None of that matter.

10:20am. I thought of what I should do to raise me prestige, and I've gotten an idea. Wrap around the PyTorch library and extend it. Do with Spiral what would not be otherwise possible.

But this will happen naturally if traverse the main path. I won't need to have to put special effort on the side to this.

...

These weird language issues aside, I am actually quite enjoying Cython. It opened a huge range of possibilities for me.

10:25am. I gained a huge power now that I have it.

I didn't want to menion it, but now that I've positioned myself like this, I can stick it to Julia. The way I am doing it with Spiral is the right way to devour Python. I finally have a credible response to competitor languages in this space.

10:40am. https://www.youtube.com/watch?v=I1xyjc-JgGM
Tools for High Performance Python - Ian Ozsvald | ODSC Europe 2019

Let me watch this for a bit.

11:20am. Had to take a break. Let me watch this for a bit and I will have breakfast.

So far, I got up at a record early time, but completely wasted the advantage.

https://pytorch.org/get-started/locally/#windows-anaconda
`conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch`

Let me run this.

Maybe I should also get Cuda 11. Ah, it seems Anaconda will install this as well.

PyTorch itself is 1Gb.

11:45am. It is a good thing I rememberd to do this in advance.

11:55am.

https://www.youtube.com/watch?v=NfnMJMkhDoQ
Easy wins with Cython: fast and multi-core by Caleb Hattingh

Let me watch this. After that comes breakfast. I'll want to watch all the Cython talks eventually. Some of them are 3.5h long.

https://www.youtube.com/watch?v=gMvkiQ-gOW8
Cython: Blend the Best of Python and C++ | SciPy 2015 Tutorial | Kurt Smith

Let me check this out for a bit. I'll watch it while having breakfast."