"9:50am. I slept well tonight. I thought I was done with the Cython backend, but it turns out it is possible to type Numpy arrays. Let me play with it.
https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory

I am getting the error that some header file cannot be found.

```
Error compiling Cython file:
------------------------------------------------------------
...
cdef class Tuple0:
    cdef readonly signed long v0
    cdef readonly signed long v1
    def __init__(self, signed long v0, signed long v1): self.v0 = v0; self.v1 = v1

cdef void qwe(numpy.ndarray[Tuple0, ndim=1] a): pass
                           ^
------------------------------------------------------------

cython_experiments\test3\testm.pyx:9:28: dtype must be "object", numeric type or a struct
```

Oh, I see.

10:15am.

```
import numpy
import pyximport
pyximport.install(language_level=3,setup_args={"include_dirs":numpy.get_include()})
from testm import (main)
print(main())
```
```
    cdef numpy.ndarray[double,ndim=1] a
    a = numpy.array([1,2,3],dtype=numpy.float64)
```

Ok, I figured it out. Let me implement this in the compiler.

```fs
        | YArray a ->
            import "numpy"; cimport "numpy"
            let a = match a with YPrim x -> prim x | _ -> "object"
            $"numpy.ndarray[{a},ndim=1]"
```

This should do for printing the types.

Now what comes next?

```
| TyArrayCreate(a,b) -> return' (sprintf "[None] * %s" (tup b))
```

This.

```
let numpy_ty = function
    | YPrim Int8T -> "numpy.int8"
    | YPrim Int16T -> "numpy.int16"
    | YPrim Int32T -> "numpy.int32"
    | YPrim Int64T -> "numpy.int64"
    | YPrim UInt8T -> "numpy.uint8"
    | YPrim UInt16T -> "numpy.uint16"
    | YPrim UInt32T -> "numpy.uint32"
    | YPrim UInt64T -> "numpy.uint64"
    | YPrim Float32T -> "numpy.float32"
    | YPrim Float64T -> "numpy.float64"
    | _ -> "object"
```

This should do it.

```fs
| TyArrayCreate(a,b) -> return' $"numpy.empty({tup b},dtype=${numpy_ty a})"
```

Here is the array create.

10:40am.

```fs
open arraym
inl main() =
    inl x : array (i32 * i32) = arraym.create 10
    arraym.set x 0 (1,2)
```
```
import numpy
cimport numpy
cdef class Tuple0:
    cdef readonly signed long v0
    cdef readonly signed long v1
    def __init__(self, signed long v0, signed long v1): self.v0 = v0; self.v1 = v1
cpdef void main():
    cdef numpy.ndarray[object,ndim=1] v0
    v0 = numpy.empty(10,dtype=object)
    v0[0] = Tuple0(1, 2)
```

This is an improvement on what I had before. Too bad, Numpy types can only be primitives, structs and objects.

10:55am. Updated that issue. What is next?

Let me push the patch. Done. Let me make some notes on the readme.

11:15am.

TODO: Cython: Add ops for imports and cimports.

I'll have to do this at some point. Nevermind it for now.

...No actually, let me do it now.

```fs
    // Cython imports
    | Import
    | CImport
```

Let me add these two ops.

```fs
        | EOp(_,(CImport | Import) & op,[a]) ->
            match term s a with
            | DLit (LitString _) & a -> push_op_no_rewrite s op a YB
            | a -> raise_type_error s $"Expected a string literal.\nGot: {show_data a}"
```

Let me put them into the codegen next.

```fs
        | TyOp(Import,[DLit (LitString x)]) -> import x
        | TyOp(CImport,[DLit (LitString x)]) -> cimport x
```

11:25am. I can't find anything by Googling on how to use the fast math functions.

Let me ask about that.

https://cython.readthedocs.io/en/latest/src/tutorial/external.html
https://github.com/cython/cython/tree/master/Cython/Includes/libc

Actually here are the files.

```
    float logf(float)
```

Ah, it does exist. Then why can't I run it?

```
// Natural Logarithm.
inl log forall t {float}. (x : t) : t = !!!!Log(x)
// Exponent.
inl exp forall t {float}. (x : t) : t = !!!!Exp(x)
// Hyperbolic tangent.
inl tanh forall t {float}. (x : t) : t = !!!!Tanh(x)
// Square root.
inl sqrt forall t {float}. (x : t) : t = !!!!Sqrt(x)
```

Let me put these into the core library. let me also add the float constraint.

Added it. Now the above typechecks.

```
Error compiling Cython file:
------------------------------------------------------------
...
cimport libc.math
cpdef float main():
    cdef float v0
    v0 = 10.000000
    return libc.math.logf(v0)
                   ^
------------------------------------------------------------

cython_experiments\test3\testm.pyx:5:20: cimported module has no attribute 'logf'
```

Let me ask about this.

https://stackoverflow.com/questions/65967020/why-is-the-logf-function-missing-from-libc-math

I'll get an answer at some point. Nevermind this for now.

11:45am. Let me push another patch.

11:50am. Let me wind off the morning session here. I did an impromptu improvement. Once I deal with the math imports, the Cython backend will be complete for the time being. The wishlist items can deal with themselves.

11:55am. Mornings like this are satisfying. I got up fairly early today too and had time to do the work. If I started at the usual time, it would be 3pm by the time I've finished this.

...Right now, I want to lay off the programming for a while.

12pm. Yesterday when I stopped for the day, I had full intention of spending today doing the review.

12:05pm. I want to slack for a while, but instead of just staring blankly at the screen, let me get breakfast."