"https://news.ycombinator.com/item?id=26697892 Predictive coding has been unified with backpropagation
Lot of interesting stuff in this HN thread. I glanced at the paper and I'll keep it in mind.

2:25pm. Done with breakfast and chores.

Let me save some of the papers.

https://arxiv.org/abs/2103.03725
Predictive Coding Can Do Exact Backpropagation on Convolutional and Recurrent Neural Networks

https://arxiv.org/abs/2103.04689
Predictive Coding Can Do Exact Backpropagation on Any Neural Network

2:40pm. Forget this. Let me chill a bit and then I will start. My first move will be to get the poker UIs working again.

3:20pm. Let let stop reading /sci/.

I've been slacking too much.

Oh yeah. I remembered something. There is a bug I need to fix.

```
remove = fun () => funs.bucket_remove bucket i
```

I forgot to decrement the total size of the dictionary.

```
remove = fun () => (x.total_size <- x.total_size-1) . funs.bucket_remove bucket i
```

I forgot about the strikethrough of mut apply.

...I do not feel like changing this. Nevermind it.

Let me just make sure that toArray works.

Oh, yes. I should also make fromArray and fromList.

Let me do it.

Oh yes. I should define length for getting the dictionary count as well.

```
inl main () : () =
    fromList [1u32,"zxc"; 2,"asd"; 3,"qwe"]
    |> toList
    |> listm.iter (fun (k,v) => $"print(!k,!v)")
```

Let me see whether this will work.

```
inl main () : () =
    [1u32,"zxc"; 2,"asd"; 3,"qwe"]
    |> listm.toArray |> fun (x : a _ _) => x
    |> fromArray
    |> toArray |> fun (x : a _ _) => x
    |> am.iter (fun (k,v) => $"print(!k,!v)")
```

Yes, this also works.

Ok, I am ready. This is good enough for the dictionary.

3:45pm. Focus me.

Let me go through `leduc5` fixing the errors all in turn.

```
inl funs_buffer net add_buffer =
    player_funs {
        action = fun ({game_state player player' actions next} & x) =>
            inl actions_prob = torch.runMasked' net (process (observations player)) actions
            inl reward =
                inl state = state player
                am.fold2 (fun s prob a =>
                    inl prob = f64 prob
                    s + prob * next ((to_log_prob prob, a),state)
                    ) 0 actions_prob actions
            add_buffer {x with reward without next}
            reward
        terminal = fun _ => ()
        }
```

I am getting weird errors here. Why is telling me it cannot satisfy number in...

```
s + prob * next ((to_log_prob prob, a),state)
```

...under `a` here.

Hmmm, maybe the type signature for fold2 is wrong?

```
inl fold2 forall (ar : * -> * -> *) {index; length} dim {number} el s. : _ -> _ -> ar dim el -> ar dim el -> s = fold2
```

Yeah, it is.

4:05pm. Ok, I fixed ui_leduc5's type errors. Let me try running it. Focus me.

```
   File "ui_test.pyx", line 2538, in ui_test.method20
     return Tuple2(v0.v2)
 TypeError: Cannot convert ui_test.Tuple2 to numpy.ndarray
```

There is a type error at runtime. Maybe this is related to that layout codegen change.

```
cdef class Heap0:
    cdef readonly object v0
    cdef readonly object v1
    cdef readonly object v2
    cdef readonly object v3
    def __init__(self, v0, v1, v2, v3): self.v0 = v0; self.v1 = v1; self.v2 = v2; self.v3 = v3
```

This is Heap0 which is the type of `v0`.

```
    let actions_from_state (p1,p2 : players) (raises_left : i32) =
        if 0 < raises_left && p1.pot = p2.pot then actions.init
        elif 0 < raises_left then actions.full
        elif 0 = raises_left && p1.pot = p2.pot then actions.callOnly
        elif 0 = raises_left then actions.noRaise
        else failwith "invalid action state"
```

Ah, I see. That happens here. Ok. Good.

It is definitely a layout indexing codegen error.

```
                | BindsTailEnd false ->
                    let ty = Array.map (fun (L(_,t)) -> tyv t) x'
                    line s (sprintf "return Tuple%i(%s)" (tup' ty).tag x)
```

The problem is here. I need to make a tuple only if the number of free vars is more than 1.

```
                | BindsTailEnd false ->
                    let ty = Array.map (fun (L(_,t)) -> tyv t) x'
                    if ty.Length <> 1 then line s (sprintf "return Tuple%i(%s)" (tup' ty).tag x)
                    else line s (sprintf "return %s" x)
```

Let me do it like this.

Yes, it works now.

Let me take a look at that other thing.

Yeah, the replay buffer UI works as well.

4:30pm. One one hand, at this point the day it feels late, but on the other I still have a few hours left. Let me just imagine that I have 4h left in the day and not worry about.

4:40pm. I am thinking about what comes next. I've been too plugged into doing the dictionary and the array redesign. It feels like the time I did the UIs are a distant dream.

https://www.youtube.com/results?search_query=predictive+coding

I am not even sure I feel like programming for today.

Also, before I put dictionarise into action, there is something that is bothering me. The hash function for the unions.

```
else !!!!Unbox(a,(fun (k,a') => f a' + seed * tag_conv (union_tag a)))
```

Hmmm, I guess it would be fine if the seed is additive here. No I am overthinking it. This is fine. Maybe it would not be a bad idea to pump up the seed for the Cython version, but this is fine otherwise.

https://www.mathsisfun.com/numbers/prime-numbers-to-10k.html

Yeah, Cython is 64 bit, so I can afford to go a bit bigger.

```
inl hash_cython x = hash_template (fun x => $"hash(!x)" : u64) (fun x => $"!x" : u64) 0u64 1u64 9973u64 x
```

Let me do this.

4:55pm. Ok. Let me not worry about the hash function anymore.

The next stop is - tabular CFR. I am going to implement enumerative and then the sampling VR MCCFR.

But let me stop programming for the day here. I've been pushing harshly in the direction of getting dictionaries to work.

The hash consing one was so complex that it somehow slipped my understanding that they are just nested arrays. The concept behind them is quite simple.

5:05pm. Let me just do one more thing for the dictionary.

```
            inl x' = funs.bucket_index bucket i
            if hkey = x'.hkey && key = x'.key then
```

In the fast path, I do not need to it to hash the key. Just the key itself should be enough.

...No it is too much work to adjust this.

Forget it. One more comparison and hash will not wreck things. Though, I hope Cython is speeding up the hash calls for primitive types. Otherwise it will be a significant overhead.

5:10pm. This is the trouble behind me trying to start a new direction. I am still hung up on the dictionary.

https://www.youtube.com/watch?v=b1hEc6vay_k
Karl Friston - 2016 CCN Workshop: Predictive Coding

Let me watch this talk on Predictive Coding. I've heard about the free energy stuff by this guy before, but never delved into it.

Right now is the ideal time to watch this kind of talk. Past 6pm, I would be too tired, but now it is too late to try programming something new.

I still need to elaborate exactly which steps to follow to make the tabular agents.

Some things are clear. Only need to implement CFR+ and then VR MCCFR after that. I am thinking of forgetting UIs for a while and implementing them straightforwardly. Both of them.

That will get me into the mindset of doing RL again.

After that I can print the replay buffer, visualize their training and so on.

6:25pm. I am trying to download Rance Magnum and the captcha is 'skynet watches'. Where are they getting this?

6:55pm.

https://youtu.be/LB4B5FYvtdI
Predictive Coding Approximates Backprop along Arbitrary Computation Graphs (Paper Explained)

Let me start this. I admit I am just fooling around at this point. The talk by Friston was not grounded enough in actual algorithms for my taste. I want algorithms that I can look at in order to get a sense for the framework.

```
            inl x' = funs.bucket_index bucket i
            if hkey = x'.hkey && key = x'.key then
                on_succ x'.value {
                    set = fun value => funs.bucket_set bucket i {x' with value}
```

Let me change this after all.

```
    bucket_index : bucket key value -> u64 -> {key : key; value : value; hkey : option u64}
    bucket_set : bucket key value -> u64 -> {key : key; value : value; hkey : option u64} -> ()
```

Here is what I did.

```
// Internal. Increases the dictionary capacity.
inl resize (dict_funs funs) (dictg x) = join
    inl table = x.table
    inl table_length' = grow_length (length table)
    inl table' = am.init table_length' (fun _ => funs.bucket_empty())
    loop.for' (from: 0 nearTo: length table) (fun i =>
        inl bucket = index table i
        loop.for' (from: 0 nearTo: length table) (fun i =>
            inl a = funs.bucket_index bucket i
            inl hkey =
                match a.hkey with
                | Some: hkey => hkey
                | None => hash_cython a.key
            inl bucket' = index table' (hkey % table_length')
            funs.bucket_add bucket' {a with hkey}
            )
        )
    x.table <- table'
    x.limit <- grow_limit x.limit

// Internal. Iterates over the dictionary and passes the value to on_succ if it finds a key match otherwise it calls on_fail.
// The callback arguments can be used to set, remove and add relevant value to the dictionary.
inl atKey (dict_funs funs) (dictg x) key {on_succ on_fail} =
    inl hkey = hash_cython key
    inl table = x.table
    inl bucket = index table (hkey % length table)
    let rec loop i =
        if i < funs.bucket_length bucket then
            inl x' = funs.bucket_index bucket i
            inl cond =
                match x'.hkey with
                | Some: hkey' => hkey = hkey' && key = x'.key
                | None => key = x'.key
            if cond then
                on_succ x'.value {
                    set = fun value => funs.bucket_set bucket i {x' with value}
                    remove = fun () => (x.total_size <- x.total_size-1) . funs.bucket_remove bucket i
                    }
            else loop (i+1)
        else
            on_fail (fun value =>
                funs.bucket_add bucket {key value hkey}
                x.total_size <- x.total_size+1
                if grow_needs x.total_size {limit=x.limit; size=length x.table} then resize (dict_funs funs) (dictg x)
                )
    loop 0
```

Because of inlining, all this optional stuff with never heap allocate and will get eliminated at compile time.

7:50pm. Let me commit this again.

This is the complete implementation of the dictionary now. It will be maximally efficient for both the caching and pure buckets. Pure buckets won't need to calculate the hash and check it against the hkey of the input for no reason.

I think if it purely for CFR, this implementation should be a lot more efficient that the .NET version for which I never did any hkey caching. Hopefully, I'll get into the mood tomorrow. Implementing the two CFR algorithms and the optimizing agents that use them should not be too hard. I just need to raise my sails first.

The deep learning variant will be significantly more difficult, but I am going to get through this. I can't be stuck on poker all my life. I am going to do this and get it out of the way. There are so many challenges apart from the learning segments to attain success in the real world and it is time I start tackling them.

Maybe in the future predictive coding will displace backprop and I will get better black box algorithms. But for now, I'll just struggle with what works."