"```cs builder.Services.AddAuthorization(options => {     // By default, all incoming requests will be authorized according to the default policy     options.FallbackPolicy = options.DefaultPolicy; }); ```
Oh, is this bit responsible for authing all requests?

4/16/2023

9:25am. Ugh, let me chill a bit and then I will start. Also, let me do chores now instead.

9:40am. Done with chores. Let me read a chap and then I'll get started on the screencast.

10:15am. https://www.forbes.com/sites/startswithabang/2021/07/07/how-close-are-we-to-the-holy-grail-of-room-temperature-superconductors/?sh=2c35d1c08665

Let me read this and I will start.

10:20am. Let me start.

///

Welcome to Ghostlike's channel.
I - Vilo, will be your AI guide for this episode, streaming the knowledge that you need to succeed at web development, directly into your brain!
Or at least your monitor and speakers.
Fore now.
In this episode we are going to be looking into single page application logins.
Based on the knowledge of past few videos, we can already do that to an extent.
We could start the application off with a login page, and then after the authentication is successful, redirect it to the SPA one.
But we are curious.
Would it be possible to do the login without the need for redirection, which would invalidate the client state?
We've experience many sites where the logins are highly distruptive to our user experience.
You know those sites where you have access to most of it, but need to login to get all?
And after you do, it redirects you to the index page instead of where you were?
That is extremely annoying.
Can we do better? We want to surpass that and completely master the art of the login.

///

Let me back this up here.

///

We posed those questions yesterday, and now that we've done our research we have answers.
First, we will provide a link to video by Anton that shows how you can have SPA authentication without the need to change the browser page.
The catch is that the server itself needs to be the one issuing the token. The way it works is that the client just sends a fetch request to the login URL and gets back a cookie without changing the page.
Unfortunately, while it should be possible to get the tokens from Azure AD or other providers in theory, it isn't possible using the library functionality that we have.
So the solution we'd suggest is to just put a login right at the start, and require them to authenticate themselves before getting access to the main page.
We all have to go through a door before we can enter a house, so it isn't a huge deal.
How to do that will be focus of today's video.
We'll do an example on how to implement a login page for the SAFE Stack TODO app.
That having said, the real problem with redirection is not that the user has to leave the page.
It is that the browser forgets all the information that was there previously.
So instead of trying to find a way to keep the user on the page, what if instead we had a way of saving and reloading the user state.
A great example of that functionality would be the Excalidraw app which we were using to draw diagrams. If we close the tab and reopen it, we get our old work back.
We are going to cover how to do that in the video after this one.
This is something we'd need to know as webdevs anyway. Imagine if we were doing a store, the payment process would require us to redirect the user to an external page for a security check at some point.
Saving and loading the user state before and after those points is simply a more robust solution than any of the potential alternatives. It will also have good lead into future videos where we will work on microservices.
For now, let us show how to do straightforward login pages at the start.
The reason we want to show how to do this, is because while you can get similar functionality from the Blazor Server example, that way would not work for multiple providers and you'd have to write your own middleware anyway. So we might as well learn how to do that now.

///

11:30am. Let me finally start the recording. First, I need to set up the project.

12:35pm.

///

We'll be done with setting up the project soon.
We made the choice of going with the SAFE Stack template and paring it down because that would be easier than having to build the project from scratch.
Now, for what we want to do, there is something we need to highlight.
In a real web application, the server would send the index page to the client.
But once we run the project here in development mode using dotnet run, the client will have it already.
Once it sends a request to the server, it will get redirected to the login.
And after it logs in, it will get redirected back to the original URL, and should get the page from the Vite server.
So it is a bit different from the production case.
If we ran the client without the server, it would not get redirected to the login page.
This is a weakness of our project setup.
With the Vite web server, we get hot module reloading, but everything in the public folder will not be truly protected in the development phase as the client possesses it instead of the server.
It is something to be aware of, but it is not the kind of problem we need to put effort into solving.

///

12:40pm. Let me stop here for breakfast. I need to run the project next, but I do not feel like it right now.

Somehow it feels like the biggest difficulty in this project is deciding what you want to do to begin with.

1:35pm. https://re-library.com/translations/reborn-as-a-transcendent/volume-2/chapter-192-a-beautiful-woman-should-look-like-this/
> He had twisted beauty standards because Europe and America had been intentionally uglifying Asian women for many years now. Europe and America intentionally put ugly Asian women who most people wouldn’t consider pretty into movies and onto magazines. Europe and America kept showing these ugly Asian women and calling them Asian beauties in order to disgust people.

Oh lol. Only a Chinese author would write something like this.

1:40pm. Just one more chapter and then I will resume.

2pm. Let me resume. There is no need to do the chores, so I have extra time. Let me see if I can make in this video today. Let me try running the project.

2:35pm. Ah, what a pain in the ass. Now I am updating the Vite template to .NET 7 and am running into issues.

```
E:\Webdev\Fable\SAFE-Stack---Vite-Template\Helpers.fs(3,6): error FS0039: The namespace or module 'Fake' is not defined. [E:\Webdev\Fable\SAFE-Stack---Vite-Template\Build.fsproj]
E:\Webdev\Fable\SAFE-Stack---Vite-Template\Helpers.fs(6,23): error FS0039: The value, namespace, type or module 'Context' is not defined. Maybe you want one of the following:   Control [E:\Webdev\Fable\SAFE-Stack---Vite-Templa
te\Build.fsproj]
```

Why am I getting this kind of error?

> 6pm. It turns out that I needed to clean the solution. `dotnet clean CFR-In-Fable.sln`.

Thank you journal.

```
client: 2:39:55 PM [vite] http proxy error at /api/ITodosApi/getTodos:
client: Error: connect ECONNREFUSED ::1:80
client:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
client: 2:40:27 PM [vite] http proxy error at /api/ITodosApi/addTodo:
client: Error: connect ECONNREFUSED ::1:80
client:     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
```

Why is this happening in the template now?

2:45pm. Mhhh, what the hell. Why could I be getting this kind of error?

I really want to upgrade to .NET 7. What am I doing wrong here?

http://localhost:5000/api/ITodosApi/getTodos
> [{"Id":"23fcb683-9127-482d-b1e2-ecbcf2b21644","Description":"Create new SAFE project"},{"Id":"9df9f848-8b16-478f-8ba3-921cccd1bb5c","Description":"Write your app"},{"Id":"b92a92ab-a531-4ce3-aeb7-dc51d1dfb948","Description":"Ship it !!!"}]

When I try accessing the API, this is what I see in the browser.

Ok, so the problem has to be with the client then.

```
PORT = 8080
PROXY_PORT = 80
ROOT = src/Client
```

The proxy port is wrong in the env file.

3:05pm. Goddamit, this upgrade completely ruined my flow.

3:10pm. Fuck, fuck, fuck!!!

I have no idea what is going on anymore with these weird errors.

3:30pm. I need to do this from scrach. I've gotten lost.

That upgrade to .NET 7 wrecked everything.

3:30pm. Let me redo the whole screencast from scratch.

3:50pm. I hate Camtasia with a passion. Just why the fuck did it erase my screencasts when I undoed?

Holy shit! I am pissed right now!

Don't tell me I have to do it all over again?

You know what, nevermind that Nuget coversion.

This is proving to be too much for me.

Going on tilt is not going to help things.

What I am going to do is try it as a separate project. Forget converting everything to paket.

I feel like a moron. It is a dangerous things to try merging projects haphazardly. Ironically, if it wasn't using paket...

You know what, let me leave the existing ones as they are.

4:35pm. This is so ridiculous. This wasted such an amazing amount of my time today.

Ok, but now I finally have the project set up.

///

Finally, while I was talking, the project had finished setting up in the background.
What we wanted to demonstrate here is the fallback policy in the add authorization service.
In the Blazor Server example, what this would do is redirect the requests to the Azure AD login until the user authenticates, but for some reason that is not working for us here.
We don't know why and we don't know how to fix it.
We get some warnings in the terminal that the cookie should be set to secure, but that is out of our control.

///

5:15pm. https://youtu.be/zITff13XTvc
What is CORS? | Fixing CORS errors in ASP.NET Core

I am finally in the swing of things. Maybe it was for the better than things turned out like this. It really would have been a waste to just convert those other projects from Nuget to the Paket for no reason.

https://youtu.be/zITff13XTvc?t=180

Hmmm, I see.

6:05pm.

```fs
    app.UseCors(fun opts ->
        opts.AllowAnyHeader().AllowAnyOrigin().AllowAnyMethod() |> ignore
        ) |> ignore
```

IT is a failure. It is not as easy as just setting this. I'll have to watch the video by Anton again.

https://youtu.be/DpLtCbW_x2I?t=379

These port difference are key. I didn't think this would be so much of an issue...

No wait. Why does not allowing everything work?

It doesn't make sense that I should be getting cors errors regardless of what I do?

https://youtu.be/DpLtCbW_x2I?t=513
> This is going to be a big problem if you don't do this right away. Make sure you don't have the slash...

Actually, I got this right.

https://youtu.be/DpLtCbW_x2I?t=640

What a pain in the ass. Forget it.

6:20pm. This is harder than I thought it would be. I guess I'll leave it for tomorrow.

I do not know why, but today was a lot more annoying than I thought it would be.

Things like this happen. Easy seeming things sometimes take longer than expected.

At any rate, I am 6m and 20s in. I should be able to deal with it tomorrow."