"10:35am.
```spiral
// Do functions returned from join points work?
inl main () =
    inl tes' n = join
        inl tes a = join
            fun b => join
                fun c => join
                    fun d => join a,b,c
        tes 1i32 2i32 (2.2f64,3f32,4.5f64)
    tes' 10i32 "qwe"
    |> fun a,b,_ => a+b
```

This 10 line fragment gets compiled to 210 lines of C code.

10:40am. Ah right. Let me actually run some of these.

```c
Array0 * ArrayCreate0(uint32_t size, bool init_at_zero){
    x->refc = 0;
    Array0 * x = (init_at_zero ? calloc : malloc)(sizeof(Array0) + sizeof(char) * size);
    x->len = size;
    return x;
}
```

Whops.

```fs
Array0 * x = (init_at_zero ? calloc : malloc)(sizeof(Array0) + sizeof(char) * size);
```

It is telling me there is a pointer mismatch.

https://www.tutorialspoint.com/c_standard_library/c_function_calloc.htm

Calloc takes two args, really?

How annoying. Can I just clear the memory instead? That could be easier.

Yeah, let me just memset it.

```fs
| _ -> line s_fun $"Array{i} * x = (init_at_zero ? calloc : malloc)(sizeof(Array{i}) + sizeof({ptr_t}) * size);"
```

There isn't an easy way for me to break down the structure into a particular number of elements.

```fs
            line s_fun (sprintf "Array%i * ArrayCreate%i(%s size, bool init_at_zero){" i i size_t)
            let _ =
                let s_fun = indent s_fun
                match ptr_t with
                | "void" -> line s_fun $"size = sizeof(Array{i});"
                | _ -> line s_fun $"size = sizeof(Array{i}) + sizeof({ptr_t}) * size;"
                line s_fun $"Array{i} * x = malloc(size);"
                line s_fun "if (init_at_zero) { memset(x,0,size); }"
                line s_fun "x->refc = 0;"
                line s_fun "x->len = size;"
                line s_fun "return x;"
            line s_fun "}"
```

Let me try it like this.

10:55am. There were a bunch of error, but I got it to compile.

Oh, right. I've realized something.

```fs
            | EQ, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) == 0" (tup_data a) (tup_data b) // TODO: Optimize string structural comparison in the real_core
            | NEQ, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) != 0" (tup_data a) (tup_data b)
            | GT, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) > 0" (tup_data a) (tup_data b)
            | GTE, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) >= 0" (tup_data a) (tup_data b)
```

I forgot that I need to get the pointer of the string here. More troublingly...

```fs
        | TyFailwith(a,b) ->
            let fmt = @"%s\n"
            match b with DLit (LitString b) -> lit_string b | _ -> $"{tup_data b}->ptr"
            |> fun b -> line s $"fprintf(stderr, \"{fmt}\", {b})"
            line s "exit(EXIT_FAILURE);" // TODO: Print out the error traces as well.
```

Unless I do the same thing that I did with the string here I am going to get memory leaks.

```fs
let string_in_op = function DLit (LitString b) -> lit_string b | b -> $"{tup_data b}->ptr"
```

```fs
            | EQ, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) == 0" (string_in_op a) (string_in_op b) // TODO: Optimize string structural comparison in the real_core
            | NEQ, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) != 0" (string_in_op a) (string_in_op b)
            | GT, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) > 0" (string_in_op a) (string_in_op b)
            | GTE, [a;b] when is_string a -> sprintf "strcmp(%s->ptr, %s->ptr) >= 0" (string_in_op a) (string_in_op b)
```

Much better. I should not that this is not an error I found in the tests, but simply by thinking about it. I am really focusing on the code that is coming out, so I am realizing all sorts of things.

11:15am.

```spiral
// Do mutually recursive functions compile correctly?
let rec f s x = if x = 0 then s else g s (x-1)
and let g s x = if x = 0 then s else f s (x-1)
inl main () = f 123i32 10u64
```

I've made this test. Let me give it a try.

```c
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
typedef enum {REFC_DECR, REFC_INCR, REFC_SUPPR} REFC_FLAG;
int32_t method1(int32_t v0, uint64_t v1){
    bool v2;
    v2 = v1 == 0ull;
    if (v2){
        return v0;
    } else {
        uint64_t v3;
        v3 = v1 - 1ull;
        return method0(v0, v3);
    }
}
int32_t method0(int32_t v0, uint64_t v1){
    bool v2;
    v2 = v1 == 0ull;
    if (v2){
        return v0;
    } else {
        uint64_t v3;
        v3 = v1 - 1ull;
        return method1(v0, v3);
    }
}
int32_t main(){
    int32_t v0;
    v0 = 123l;
    uint64_t v1;
    v1 = 10ull;
    return method0(v0, v1);
}
```

This compiles just fine. I thought it might need forward declarations, but it seems not. Let me also test mutually recursive types while I am at it.

```spiral
// Do mutually recursive types compile correctly?
union rec a = AQ | AW : b
and union b = BQ | BW : a

inl main () =
    inl ~_ = AW <| BW <| AW <| BQ
    0i32
```

Let me try this one. This might fail.

Hmm, it is complaining the return type of main should be a 32 bit int. But it clearly is that. What is going on?

```fs
| TyLet(end_dat',a,(TyJoinPoint _ | TyIf _ | TyIntSwitch _ | TyUnionUnbox _ | TyUnionBox _ | TyLayoutToHeap _ | TyLayoutToHeapMutable _ | TyArrayLiteral _ | TyArrayCreate _ | TyFailwith _) & b) -> d.seq.[d.seq.Count-1] <- TyLocalReturnOp(a,b,end_dat')
```

I did something wrong here. According to this...ah, I see.

```fs
let is_tco_compatible = function TyJoinPoint _ | TyIf _ | TyIntSwitch _ | TyUnionUnbox _ | TyUnionBox _ | TyLayoutToHeap _ | TyLayoutToHeapMutable _ | TyArrayLiteral _ | TyArrayCreate _ | TyFailwith _ -> true | _ -> false

let seq_apply (d: LangEnv) end_dat =
    let inline end_ () = d.seq.Add(TyLocalReturnData(end_dat,d.trace))
    if d.seq.Count > 0 then
        match d.seq.[d.seq.Count-1] with
        | TyLet(end_dat',a,b) when Object.ReferenceEquals(end_dat,end_dat') && is_tco_compatible b -> d.seq.[d.seq.Count-1] <- TyLocalReturnOp(a,b,end_dat')
        | _ -> end_()
    else end_()
    d.seq.ToArray()
```

Let me simplify it like this. Not the bug I expected to find, but I am glad to have found it nonetheless.

```c
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
typedef enum {REFC_DECR, REFC_INCR, REFC_SUPPR} REFC_FLAG;
typedef struct UH1 UH1;
struct UH1 {
    int refc;
    int tag;
    union {
        struct {
            UH0 * v0;
        } case1; // AW
    };
};
```

It is complaining that the type is not there. I am going to have to factor out the forward type declaration from the rest. There is no way around it.

```fs
let codegen (env : PartEvalResult) (x : TypedBind []) =
    let imports = ResizeArray()
    let types_fwd = ResizeArray()
    let types = ResizeArray()
    let functions = ResizeArray()

    let print show r =
        let s_typ_fwd = {text=StringBuilder(); indent=0}
        let s_typ = {text=StringBuilder(); indent=0}
        let s_fun = {text=StringBuilder(); indent=0}
        show s_typ_fwd s_typ s_fun r
        let f (a : _ ResizeArray) (b : CodegenEnv) =
            let text = b.text.ToString()
            if text <> "" then a.Add(text)
        f types_fwd s_typ_fwd
        f types s_typ
        f functions s_fun
```

I should consider myself lucky that I only have to deal with types.

```fs
line s_typ_fwd (sprintf "typedef struct UH%i UH%i;" i i)
```

I just have to do this.

```fs
types_fwd.Add("typedef enum {REFC_DECR, REFC_INCR, REFC_SUPPR} REFC_FLAG;\n")
```

And this. Let me try it again.

11:55am. Had to take a short break. Let me continue testing.

```fs
                line s_fun "switch (x.tag) {"
                map_iteri (fun tag k v ->
                    let s_fun = indent s_fun
                    line s_fun (sprintf "case %i: {" tag)
                    let _ =
                        let s_fun = indent s_fun
                        v |> refc_change (fun i -> $"x.case{tag}.v{i}") "q" |> line' s_fun
                    line s_fun "}"
                    ) x.free_vars
                line s_fun "}"
            line s_fun "}"
```

Ah forgot the fucking `break` here.

```fs
                    let s_fun = indent s_fun
                    let refc = v |> refc_change (fun i -> $"x.case{tag}.v{i}") "q"
                    if refc.Length <> 0 then
                        line s_fun (sprintf "case %i: {" tag)
                        let _ =
                            let s_fun = indent s_fun
                            refc |> line' s_fun
                            line s_fun "break;"
                        line s_fun "}"
```

Let me do it like this.

12:25pm. So far so good.

```c
v0 = ArrayCreate0(1ull,False);
```

How did this happen?

```fs
        | TyArrayCreate(a,b) ->
            let is_heap : string = a |> env.ty_to_data |> data_free_vars |> Array.exists (fun (L(_,t)) -> is_heap t) |> sprintf "%b"
            $"ArrayCreate{(carray a).tag}({tup_data b}, {is_heap})" |> return'
```

Let me do this like so.

12:30pm. In save the pricess there are some errors.

```
/tmp/xx9PVvFb0A.c: In function 'ArrayRefcBody1':
/tmp/xx9PVvFb0A.c:108:20: error: invalid type argument of '->' (have 'US0' {aka 'struct <anonymous>'})
  108 |         USRefc0(&(v->v0), q);
      |                    ^~
```

```c
static inline void ArrayRefcBody1(Array1 * x, REFC_FLAG q){
    for (uint32_t i=0; i < x->len; i++){
        US0 v = x->ptr[i];
        USRefc0(&(v->v0), q);
    }
}
```

Does it think that v is a tuple?

```fs
            line s_fun (sprintf "static inline void ArrayRefcBody%i(Array%i * x, REFC_FLAG q){" i i)
            let _ =
                let s_fun = indent s_fun
                let refcs = x.tyvs |> refc_change (fun i -> if 1 < x.tyvs.Length then $"v.v{i}" else "v") "q"
                if refcs.Length <> 0 then
                    line s_fun (sprintf "for (%s i=0; i < x->len; i++){" size_t)
                    let _ =
                        let s_fun = indent s_fun
                        line s_fun $"{ptr_t} v = x->ptr[i];"
                        refcs |> line' s_fun
                    line s_fun "}"
            line s_fun "}"
```

Maybe the array setter needs to be like this. Imagine if I had this functionality in multiple places, how hard it would be to fix it. I definitely made the right choice to keep it all here.

```
/tmp/xx9PVvFb0A.o
Initing
Starting
Segmentation fault
```

Nice.

Since it sussed it out, this is a good test.

```fs
let is_heap = function
    | YUnion a when a.Item.layout = UHeap -> true
    | YPrim StringT | YLayout _ | YArray _ | YFun _ -> true
    | a -> false
```

I think the problem is this. The union might be a heap type too.

```fs
let rec is_heap = function
    | YUnion a -> a.Item.layout = UHeap || Array.exists (snd >> is_heap) a.Item.tag_cases
    | YPrim StringT | YLayout _ | YArray _ | YFun _ -> true
    | a -> false
```

Let me do the test like this.

Instead of doing it in the codegen every time, it might be better to move this to the pevaller. But let me just try it out first. Something else might be the cause of segfaults.

Nope, I still get the same error.

```fs
let save_the_princess (field : a u64 (a u64 _)) mario_pos : list string =
    $"printf(\"%s\\n\",\"qwe\")"
    inl cells_visited : a u64 (a u64 _) =
        am.init (length field) (fun b =>
            am.init (length (index field b)) (fun _ => false)
            )
    $"printf(\"%s\\n\",\"asd\")"
```

The problem is right here. So I am dealing with an array of arrays.

Array of arrays of bools.

```c
AssignMut0(&v11->v0, v14);
```

Could it be that I just need a parenth here?

Nope.

12:50pm.

```c
    printf("%s\n","qwe");
    while (method0(v3, v5)){
        printf("%s\n","q1");
        uint64_t v7;
        v7 = v5->v0;
        Array1 * v8;
        v8 = v0->ptr[v7];
        printf("%s\n","q2");
        ArrayRefc1(v8, REFC_INCR);
        printf("%s\n","q3");
        uint64_t v9;
        v9 = v8->len;;
        ArrayRefc1(v8, REFC_DECR);
        Array4 * v10;
        v10 = ArrayCreate4(v9, false);
        ArrayRefc4(v10, REFC_INCR);
        Mut0 * v11;
        v11 = MutCreate0(0ull);
        MutRefc0(v11, REFC_INCR);
        while (method0(v9, v11)){
            uint64_t v13;
            v13 = v11->v0;
            AssignArray2(v10->ptr+v13, false);
            uint64_t v14;
            v14 = v13 + 1ull;
            AssignMut0(&(v11->v0), v14);
        }
        printf("%s\n","q4");
        MutRefc0(v11, REFC_DECR);
        AssignArray3(v4->ptr+v7, v10);
        ArrayRefc4(v10, REFC_DECR);
        uint64_t v15;
        v15 = v7 + 1ull;
        AssignMut0(&(v5->v0), v15);
        printf("%s\n","q5");
    }
    printf("%s\n","asd");
```

I've isolated it. The error happens between q2 and q3.

1pm. Ah, crap. It is not the problem I have, but I figured out a problem nonetheless.

I should not have use the flattened representation in functions. Imagine what will happen when an array tries allocating space for the closures. It will completely misinterpret the size.

I do not know what the problem is here.

1:05pm. Let me take a break here. Dealing with memory errors is difficult. I might have to get my own C compiler along with valgrind. Who knows what the problem is here. I'll try inserting print statements all over the place to make sure that free is not being done by accident."