"12:20pm. Done with breakfast. Next comes chores. After that I will put a dent in this book. I want to get through the JS stuff today. Part two I will just skim unless the examples turn out to be really applied. Part 3 is where the meat of the book will lie.
12:35pm. Done with chores. Let me start.

Unusual that I am doing this so soon. But now that I have a hook, I feel that I am more motivated.

Let's get this thing going.

1:10pm. 97/551.

This part is so annoying. Having to deal with learning inheritance hierarchies. Honestly, I am tempted to just leave this for later.

I want to rant a bit, but I'll leave that for much later. Let me just focus on getting through part 1 of the book first.

1:15pm. The code on this page is stupidly convoluted and I am not that interested in learning it.

1:25pm.

```
let Product = function(name, price) {
    this.name = name;
    this.price = price;
    }

Product.prototype.toString = function() {
    return `toString: Name: ${this.name}, Price: ${this.price}`;
    }

console.log(`prot: ${Object.toString()}`);
```

Ugh, I hadn't learned anything. I don't even want to learn this shit.

Should `Product.prototype` be `Object`? And then shouldn't this mutate it?

1:40pm.

```
class Product {
    constructor(name, price) {
        this.name = name;
        this.price = price;
        }
    toString() {
        return `toString: Name: ${this.name}, Price: ${this.price}`;
        }
    }

function createProductIterator() {
    const hat = new Product("Hat", 100);
    const boots = new Product("Boots", 100);
    const umbrella = new Product("Umbrella", 23);
    let lastVal;
    return {
        next() {
            switch (lastVal) {
                case undefined:
                    lastVal = hat;
                    return { value: hat, done: false };
                case hat:
                    lastVal = boots;
                    return { value: boots, done: false };
                case boots:
                    lastVal = umbrella;
                    return { value: umbrella, done: false };
                case umbrella:
                    return { value: undefined, done: true };
                }
            }
        }
    }

let iterator = createProductIterator();
let result = iterator.next();
while (!result.done) {
    console.log(result.value.toString());
    result = iterator.next();
    }
```

JS pretty much took all the worst aspects of C and modern OO languages and smushed it together in one big pile of shit. There is really a case to be made that C causes brain damage. Agh, why couldn't SML have become the dominant PL of the modern era?

```
function* createProductIterator() {
    yield new Product("Hat", 100);
    yield new Product("Boots", 100);
    yield new Product("Umbrella", 23);
    }
[...createProductIterator()].forEach(p => console.log(p.toString()));
```

This is much nicer, but generators are one thing completely subsumed by monadic computation. Well, I'll keep this pattern in mind.

The same goes for async/await. I always look askance at language features that are completely subsumed by more general ones.

Still, I can understand why one would do things this way.

Monadic computation are hard to do without the type system holding your hand.

2pm. 108/551. This is so boring. I've already started surfing the ML sub on the side. Let me take a short break. How much longer till the chapter is over?

2:05pm. 10 more pages. Then I am done with the JS primer. So I might as well bear with it.

After that comes the TS stuff. I should be able to go through that quickly.

Ok, let me focus hard for 10 more pages and then I'll take a break. After that I'll start skimming the stuff that I've already been through so many times.

2:15pm. https://github.com/WebAssembly/gc

Oh, there are proposals to add GC to WebAssembly. GC is the most important single feature I would need to Spiral top level targets to have. At the top level it really does need GC to allocate arrays, closures and recursive union types.

Still, this is just a proposal so I do not need to hurry here.

```
E:\Typescript\essential-ts\primer\index.js:1
import calcTax from "./tax";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Why is this happening?

2:35pm. I get this same error even in the sample code. What the hell?

I am looking at SO answers and it seems for browsers I need to specify that I am compiling a module. I am guessing the same goes for JS.

https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module

"At the time of writing, Node.js only provides support for standard modules as an experimental feature. To work around this limitation, stop the nodemon process you started in Listing 4-2 and use the command prompt to run the command shown in Listing 4-23 in the primer folder. This command installs a package called esm that provides support for working with modules."

Ah, whops, I should have read the book more carefully.

Also there is a very recent update to that question.

"2020 Update (Node 13.2.0+)
Verify that you have the latest version of Node installed. The --experimental-modules flag is no longer necessary. Simply do one of the following:

Add "type": "module" to the nearest parent package.json. With this, all .js and .mjs files are interpreted as ES modules. You can interpret individual files as CommonJS by using the .cjs extension.
OR

Explicitly name files with the .mjs extension. All other files, such as .js will be interpreted as CommonJS, which is the default if type is not defined in package.json."

2:45pm. Hmmm, I surprised I have a lower node version number than the above given how recently I've installed it.

I guess I'll just get the latest nodejs rather than mess with experimental packages.

```
E:\Typescript\essential-ts\primer>node --experimental-modules index.js
(node:12472) ExperimentalWarning: The ESM module loader is experimental.
```

With this it works, but it complains that JS modules are experimental.

Let me just get the latest node rather than installing packages to get this functionality.

3pm. Damn it, even with the latest everything installed I still get that annoying experimental warning.

3:05pm. I am looking around and it does not seem there is any way to disable the warning without disabling all of them. Forget this for now.

...Maybe I should have just gotten the esm package after all. What the hell.

3:20pm. Well, at any rate I am done with the chapter and am taking a short breather here. The next chapter is on the TS compiler specifically, so I am going to go through it top to bottom.

3:30pm. Let me chill for a while longer."