"1:15pm. Done with breakfast. Time for chores. Let me chill a bit more first though.
2:15pm. Done. Let me resume. First let me see if I got any replies.

Nope.

2:20pm. Ok then...I've figured out how to bundle `alert.js` previously. Now I have to figure out how to not bundle it.

Let me spend some time reading the docs again.

...Uf, let me try the js project from scratch. I redid it so I could import the extensions, but that is not good.

2:45pm. I am thinking. I got the binding example going again, but now I am not sure what to do. I really do not know what the next step should be here.

https://fable.io/docs/miscellaneous/fable-in-videos.html

```
let activate (context : vscode.ExtensionContext) =
  registerCommand("extension.sayHello", fun _ ->
    showInformationMessage "Hello world!" |> unbox )
  |> context.subscriptions.Add
```

This is how that guy did this.

2:55pm. I am thinking.

Yeah, the obvious choice here is just to use the `fable-splitter`. But with that thing I won't be able to import 3rd party libraries.

I need to make a compromise. Until my compilation question gets answered let me just go with it.

3pm. Let me just do it. I know I have this attitude that I have to do everything in turn, but let me not waste the next 3-4 hours just sitting here.

I should be able to make my own binding and compile it.

https://github.com/fable-compiler/fable-import/issues

The issue number 3 here is pertinent to my interests.

Let me do some digging. My rational mind is telling me to do one thing, but my feelings are pulling me in the direction of figuring this out.

I want to put some effort into doing it this way.

```
[<Global>]
let Waud: IWaudStatic = jsNative

// You can also pass a name if you want to use a different name in F#
[<Global("Waud")>]
let waud: IWaudStatic = jsNative
```

How does this work. This confuses me.

3:10pm. Right now I am reading issue 75.

"But I can't imagine someone crazy enough doing it an API like electron or worst VSCode. But I would be really happy to be proven wrong 😉."

3:20pm. I feel really blocked at the moment. I am thinking if the global would pass, but no way that it would. I need to get it to emit `import * as vscode from 'vscode';`.

I do not get it. Just how do the basic API imports work?

3:25pm. Let me crosspost my SO issue on the Fable import page.

3:30pm. https://github.com/fable-compiler/fable-node

Let me clone this. I'll go over it.

3:35pm.

```
namespace rec Node.Base

open System
open Fable.Core
open Fable.Core.JS

// type [<AllowNullLiteral>] Console =
//     abstract ``assert``: value: obj * ?message: string * [<ParamArray>] optionalParams: obj[] -> unit
//     abstract dir: obj: obj * ?options: obj -> unit
//     abstract error: ?message: obj * [<ParamArray>] optionalParams: obj[] -> unit
//     abstract info: ?message: obj * [<ParamArray>] optionalParams: obj[] -> unit
//     abstract log: ?message: obj * [<ParamArray>] optionalParams: obj[] -> unit
//     abstract time: label: string -> unit
//     abstract timeEnd: label: string -> unit
//     abstract trace: ?message: obj * [<ParamArray>] optionalParams: obj[] -> unit
//     abstract warn: ?message: obj * [<ParamArray>] optionalParams: obj[] -> unit

// TODO: Use System.Exception instead?
type [<AllowNullLiteral>] Error =
    abstract name: string with get, set
    abstract stack: string with get, set
    abstract message: string with get, set

type ItNext<'T> =
    abstract ``done``: bool
    abstract value:'T

type Iterator<'T> =
    abstract next : unit -> ItNext<'T>

type [<AllowNullLiteral>] NodeRequireFunction =
    [<Emit("$0($1...)")>] abstract Invoke: id: string -> obj

type [<AllowNullLiteral>] NodeRequire =
    inherit NodeRequireFunction
    abstract cache: obj with get, set
    abstract extensions: obj with get, set
    abstract main: NodeModule with get, set
    abstract resolve: id: string -> string

type [<AllowNullLiteral>] NodeModule =
    abstract exports: obj with get, set
    abstract require: NodeRequireFunction with get, set
    abstract id: string with get, set
    abstract filename: string with get, set
    abstract loaded: bool with get, set
    abstract parent: U2<NodeModule, obj> with get, set
    abstract ``null``: obj with get, set
    abstract children: ResizeArray<NodeModule> with get, set

type [<AllowNullLiteral>] ErrnoException =
    inherit Error
    abstract errno: float option with get, set
    abstract code: string option with get, set
    abstract path: string option with get, set
    abstract syscall: string option with get, set
    abstract stack: string option with get, set

type [<AllowNullLiteral>] ProcessVersions =
    abstract http_parser: string with get, set
    abstract node: string with get, set
    abstract v8: string with get, set
    abstract ares: string with get, set
    abstract uv: string with get, set
    abstract zlib: string with get, set
    abstract modules: string with get, set
    abstract openssl: string with get, set

type [<AllowNullLiteral>] MemoryUsage =
    abstract rss: float with get, set
    abstract heapTotal: float with get, set
    abstract heapUsed: float with get, set

type [<AllowNullLiteral>] CpuUsage =
    abstract user: float with get, set
    abstract system: float with get, set

type [<StringEnum>] Arch =
    | Arm | Arm64 | Ia32 | Mips | Mipsel | Ppc | Ppc64 | S390 | S390x | X32 | X64 | X86

type [<StringEnum>] Platform =
    | Aix | Android | Darwin | Freebsd | Linux | Openbsd | Sunos | Win32

type [<AllowNullLiteral>] Timer =
    abstract ref: unit -> unit
    abstract unref: unit -> unit

// TODO: Move this to API?
type [<AllowNullLiteral>] Global =
    // abstract Array: obj with get, set
    // abstract ArrayBuffer: obj with get, set
    // abstract Boolean: obj with get, set
    // abstract Buffer: obj with get, set
    // abstract DataView: obj with get, set
    // abstract Date: obj with get, set
    // abstract Error: obj with get, set
    // abstract EvalError: obj with get, set
    // abstract Float32Array: obj with get, set
    // abstract Float64Array: obj with get, set
    // abstract ('FIn->'FOut): obj with get, set
    // abstract GLOBAL: Global with get, set
    // abstract Infinity: obj with get, set
    // abstract Int16Array: obj with get, set
    // abstract Int32Array: obj with get, set
    // abstract Int8Array: obj with get, set
    // abstract Intl: obj with get, set
    // abstract JSON: obj with get, set
    // abstract Map: MapConstructor with get, set
    // abstract Math: obj with get, set
    // abstract NaN: obj with get, set
    // abstract Number: obj with get, set
    // abstract Object: obj with get, set
    // abstract Promise: ('FIn->'FOut) with get, set
    // abstract RangeError: obj with get, set
    // abstract ReferenceError: obj with get, set
    // abstract RegExp: obj with get, set
    // abstract Set: SetConstructor with get, set
    // abstract String: obj with get, set
    // abstract Symbol: ('FIn->'FOut) with get, set
    // abstract SyntaxError: obj with get, set
    // abstract TypeError: obj with get, set
    // abstract URIError: obj with get, set
    // abstract Uint16Array: obj with get, set
    // abstract Uint32Array: obj with get, set
    // abstract byte[]: obj with get, set
    // abstract Uint8ClampedArray: ('FIn->'FOut) with get, set
    // abstract WeakMap: WeakMapConstructor with get, set
    // abstract WeakSet: WeakSetConstructor with get, set
    // abstract console: Console with get, set
    // abstract decodeURI: obj with get, set
    // abstract decodeURIComponent: obj with get, set
    // abstract encodeURI: obj with get, set
    // abstract encodeURIComponent: obj with get, set
    // abstract escape: Func<string, string> with get, set
    // abstract eval: obj with get, set
    // abstract ``global``: Global with get, set
    // abstract isFinite: obj with get, set
    // abstract isNaN: obj with get, set
    // abstract parseFloat: obj with get, set
    // abstract parseInt: obj with get, set
    // abstract root: Global with get, set
    // abstract undefined: obj with get, set
    // abstract unescape: Func<string, string> with get, set
    abstract gc: Func<unit, unit> with get, set
    abstract v8debug: obj option with get, set
```

I am looking at this and I am completely confused.

`[<Global>]` is nowhere used. I saw it used elsewhere, but it is not in context I would expect.

There are issues everywhere as far as I can think of. The annoying thing is, unlike with ReasonML, using webpack would hide the generated code from me so I cannot find easily how it is being used.

3:55pm. https://tpetricek.github.io/Fable/docs/interacting.html
"If the module or value is globally accessible in JavaScript, you can use the Global attribute without parameters instead. If a method accepts a lambda make sure to use System.Func in the signature to force the compiler uncurry any lambda passed as parameter"

So `global` works on modules as well.

You know what I think - Fable is a huge mess. It is actually incredibly annoying to set up a project from scratch. In contrast, setting up a Typescript project is pretty much seamless.

Right now I am thinking, and it is occurring to me that I should be experimenting with that global attribute. Except with Webpack I can't really look at the generated code. And setting up that `fable-splitter` is a huge chore.

I won't even talk about adding Paket on top of all of this and various other build systems like FAKE.

Is there some option to have webpack generate readable code?

https://webpack.js.org/guides/output-management/

4pm. Bad Google. Giving me crap again.

No this is not working for me. Forget this. All this difficulty is a sign from the heavens that I should just use Typescript.

I'll give it another try if I manage to suss out some answers from the devs, but my main plan should be to use Typescript after all. I love functional programming enough to try Fable, but the tooling and the interop is just not there.

4:05pm. I am not ready to just switch gears right here. Let me watch some talks and then I'll call it a day.

https://www.youtube.com/watch?v=5191ytFmG_A
From F# to JavaScript with Fable

There was also that metalearning talk that I wanted to watch a while ago.

Tomorrow, I am going to go through the samples and translate them from TS to TS. It will be annoying to learn that way, but I will try to get some flow going if possible.

https://reasonml.github.io/docs/en/interop

I feel that ReasonML is more streamlined compared to Fable.

///

So what does the compiled JavaScript look like?

```
'use strict';
var tau = Math.PI * 2.0;
alert("hello");
var myCanvas = ( document.getElementById("mycanvas") );
var ctx = myCanvas.getContext("2d");
ctx.fillRect(0.0, 0.0, 100.0, 100.0);
```

///

This is really important while you are learning. Fable really leaves a lot to be desired.

4:15pm.

///

```
Js.log("this is reason");

[%bs.raw {| console.log('here is some javascript for you') |}];
```

```
// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';
console.log("this is reason");
console.log('here is some javascript for you');
```

///

I really need this. If I could dump some raw shit, it would really make things easier for me.

```
type canvas;

type context;

/* we're leaving these types abstract, because we won't
 * be using them directly anywhere */
[@bs.send] external getContext : (canvas, string) => context = "getContext";

let myCanvas: canvas = [%bs.raw {| document.getElementById("mycanvas") |}];

let ctx = getContext(myCanvas, "2d");
```

And these opaque types. I could really use these as stumps for interop.

https://rrdelaney.github.io/ReasonablyTyped/

> Is it ready? NO! But it passes 111/316 tests.

4:35pm. "https://reasonml.github.io/docs/en/interop

I am comparing Fable to Reason and am wondering if I can simply dump some JS in the middle of my F# file. That would make it easy to output `const vscode = require('vscode');` in the emitted file. It probably is not the right solution, but it would beat just sitting here just wracking my brain and waiting for the answer to come to me.

On that note, I saw some readable Fable code when I used `fable-splitter` ([see here](https://blog.nojaf.com/2018/12/17/writing-a-vscode-extension-with-fable-2-1/)), but the use of webpack as the default template suggests makes it impossible to know what is coming out in the bundle. Though I do not see it as a necessity for large projects, when it comes to small examples being studied for the sake of learning the ability to see what kind of code is being outputted is a great benefit."

I added this to that issue.

4:50pm.

```
let vscode: obj = Fable.Core.JsInterop.importAll "vscode"

()
```

I can't figure out how to resolve this. There isn't a bare emit anywhere as far as I can see.

Ok...let me do it like this - rather than Typescript, since I am having difficulties, let me change my target to ReasonML.

I had some time to think. In ReasonML I would have no trouble importing `vscode`, but I am not sure how dealing with third party libraries works.

5pm. I am a bit emotionally drained from this, I've been ready to commit to Fable, but now I have to switch.

Very well. If I am going to switch to ReasonML, let me try installing some packages.

https://redex.github.io/package/bs-vscode

Let me try getting this.

So do I just `npm install bs-vscode` to get this?

5:10pm. Yeah, but the plugin is really sparse.

https://redex.github.io/package/@ewert-online/re-crypt

Right now I am looking at ReasonML specific libraries.

> How do I install it?

`npm install @ewert-online/re-crypt --save`

So this is how it works? This is much more smooth than me messing with strange compiler plugins and Paket.

5:10pm.

```
type person = {
  name: string,
  mutable age: int
};
let baby = {name: "Baby Reason", age: 5};
baby.age = baby.age + 1; /* alter `baby`. Happy birthday! */
```

Ah, yeah, I forgot that mutable records are a thing in both Ocaml and F#. It makes me wonder why the Fable guys opted for interfaces everywhere. Efficiency maybe? ...No that reason is not applicable in the context of compiling to JS.

5:20pm. Let me get over my disappointment and I will call it a day. Maybe I'll watch a talk to round the day out.

Today was just so disappointing. But either way everything is set. Tomorrow work on translating those sample to functional code will begin. I did say that ReasonML is a good alternative to Fable, and that card is going to get played here. Ultimately, my true allegiance is not to F#, but the functional programming that it introduced me to.

5:25pm. The Spiral project will come to fruition.

Let me watch that talk.

https://www.youtube.com/watch?v=xIwDqf8oN68
Meta-Learning: Why It’s Hard and What We Can Do - Ke Li

5:35pm. Forget it, this talk just drones on and on about definitions. I do not need people to explain what metalearning is and give me a history tour, but how to do it efficiently. I can imagine two loops just fine on my own.

Yeah, I'll finish it early here. Let me smash some demons."