"https://soundcloud.com/denny-schneidemesser/with-gun-crucifix-1
This caught my attention amongst the music.

7:25pm. Damn, am I tired right now.

https://twitter.com/NathanLands/status/1662881442651869184

Photoshop is getting generative AI tools. This is pretty amazing.

https://www.bbc.com/news/business-65675027
> Microsoft is also reportedly developing an AI chip, and Meta has its own AI chip project.

There are two links in this quote.

https://www.theverge.com/2023/4/18/23687912/microsoft-athena-ai-chips-nvidia
https://techcrunch.com/2023/05/18/meta-bets-big-on-ai-with-custom-chips-and-a-supercomputer/

I really do feel like AI chip startups are like vermin. They just exist to get my expectations up for nothing. We'd be better of waiting for the big players to come up with something good.

https://www.theverge.com/2023/5/18/23728748/the-ai-boom-is-a-big-leg-up-for-the-people-who-profit-from-debt

> Some of the companies that stand to benefit most from AI integration are those that purely exist to collect debt. These companies, known as debt buyers, purchase “distressed” debt from other creditors at steep discounts—usually pennies on the dollar—then try as hard as they can to get debtors to repay in full. They don’t issue loans, or provide any kind of service that clients might owe them for; it’s a business model built on profiting from people who fell behind on payments to someone else.

8:45pm. I am going to bed.

5/30/2023

7:30am. Right now I am waiting for the bathroom to clear so I can take a bath.

8:15am. Done with the bath. Let me start.

9:20am. Damn it, I am still migrating the project. Why isn't finding the Apex Chart js files?

9:45am. I am still stuck on this issue.

9:50am. Let me try a different package that requires .js files just to see if they load.

https://blazorstrap.io/VNext/V5

Let me try this.

No, the js files for this package aren't loading either.

Fuck. Goddamit. How much time is this issue going to waste for me.

Ah, let me ask Bing.

It is telling me to ssh into the server. Wait, maybe the problem is the fucking launch profile?

Yeah, that was it!

if I log into through https, the errors go away!

Just why isn't the IIS setting working though?

https://soundcloud.com/star-conflict-1/a-romanov-produced-by-13

This caught my eye.

```fs
        override this.Update(msg) =
            let model = this.Model
```

Wait, shit. I am so retarded. I thought this could be a problem, but it slipped my mind.

1:50pm. Let me resume.

3:30pm. Damn it, I am so tired of this shit.

4pm. Finally done with the rewrite. I honestly, don't have any energy left to deploy this application.

https://learn.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr

> In this scenario, the backplane might be a bottleneck if the number of messages scales with the number of clients; that is, if the rate of messages grows proportionally as more clients join.

Hmmm...

Ah, I see. SignalR scaleouts aren't what I thought they were.

You can just use these backplates to connect multiple nodes in a network.

4:20pm. Ok, let's try to do the deployment.

5:25pm. https://mrakgr-cfr-in-blazor.azurewebsites.net/

I'll put this on my resume.

5:35pm. Done. Let me update my LinkedIn profile.

5:45pm. Done publishing, done updating the resume and LinkedIn profile.

I've gotten some good skills through this.

5:45pm. The video is 2:33 hours long, and it will be a minute or two longer after I add the outro.

https://soundcloud.com/purecomposition

This artist is free and has good tracks.

6:35pm. 2:36:41 hours.

Now I have to find soundtracks for all that empty space.

I simply don't have enough in my library to fill that, so what I am going to is cram it full of Antti's.

I'll get his albums from Soundcloud and if he complains, I'll swap them out for something else.

https://www.reddit.com/r/Python/comments/270k3m/a_script_to_download_a_soundcloud_users_music_all/

> neat. if folks weren't aware, youtube-dl can grab soundcloud tracks. I've use curl+grep+youtube-dl to download entire users before.

> Could you give an example of this? It sounds useful.

///

from my history file, it looks like I did this:

curl http://soundcloud.com/markusschulz | grep "http://soundcloud.com/markusschulz/" >> list
youtube-dl `cat list`
crude, but mostly effective. it probably doesn't download all the tracks because of pagination. but it also took me >3 mins to develop and it solved the problem to my immediate satisfaction.

///

I wish I knew command line tools.

///

basically, the script does this:

download the HTML for the page "http://soundcloud.com/markusschulz"
=> send the downloaded HTML to a pattern matcher looking for the string "http://soundcloud.com/markusschulz/"
=> save matches to a file called "list"

youtube-dl, download $this, where $this is the contents of file "list".
all the cleverness of this is in the grep statement. the user page contains links to song pages. I manually inspected the HTML for the user page and noticed that all song pages are in the form of http://soundcloud.com/user/song-title. feed that into a pattern matcher and bam.

if you're interested in grabbing bulk content, Linux is a great platform. much like Python, you can construct a shell pipeline interactively: run curl, look for data you care about. run curl | grep, see if that data looks like what you care about. optionally add more grep, awk, sed, cut to process data further. Python is an awesome language but simple UNIX tools can be used to great effect for data processing and web scraping. if you want a tool that can be used repeatedly across a varied set of data and maintained for a long period of time, Python is great. if you just want to scrape a site right now, curl+shell is probably faster. wget --spider is pretty cool too.

[edit: here's a link to youtube-dl too. it's a Python tool that's grown into an all-purpose internet media downloader.]

///

I have to go through this workflow. My pride won't allow me to do anything less.

https://soundcloud.com/purecomposition

Wow these guys are so good.

///

You can run command line arguments from an F# script by using the System.Diagnostics.Process class. Here’s an example:

open System.Diagnostics

let cmd = "echo 'Hello, world!'"
let psi = new ProcessStartInfo("cmd.exe", "/c " + cmd)
psi.RedirectStandardOutput <- true
psi.UseShellExecute <- false

let p = Process.Start(psi)
let output = p.StandardOutput.ReadToEnd()

printfn "%s" output
This code runs the command echo 'Hello, world!' and prints the output to the console. You can replace cmd with your own command and modify the code as needed.

I hope this helps! Let me know if you have any other questions.

///

I asked this of Bing and it seems it gave me exactly what I want.

8:20pm. My god, this was way easier in Python, just what the hell am I doing trying to run things from the command line in F#?

```
./youtube-dl.exe https://soundcloud.com/purecomposition
```

I should have just ran this from the command line, but I got gripped with the desire to learn some shell scripting. That kind of thing never pays.

8:30pm. https://youtu.be/UVUd9_k9C6A
PowerShell For Beginners Full Course | PowerShell Beginner tutorial Full Course

8:35pm. Wow, it is going to download all of Antti's songs, but it is not putting them in order.

https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template

Who is going to rename all those things by hand.

```
$ youtube-dl --get-filename -o '%(title)s.%(ext)s' BaW_jenozKc
youtube-dl test video ''_ä↭𝕐.mp4    # All kinds of weird characters

$ youtube-dl --get-filename -o '%(title)s.%(ext)s' BaW_jenozKc --restrict-filenames
youtube-dl_test_video_.mp4          # A simple file name

# Download YouTube playlist videos in separate directory indexed by video order in a playlist
$ youtube-dl -o '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/playlist?list=PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re

# Download all playlists of YouTube channel/user keeping each playlist in separate directory:
$ youtube-dl -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/user/TheLinuxFoundation/playlists

# Download Udemy course keeping each chapter in separate directory under MyVideos directory in your home
$ youtube-dl -u user -p password -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/java-tutorial/

# Download entire series season keeping each series and each season in separate directory under C:/MyVideos
$ youtube-dl -o "C:/MyVideos/%(series)s/%(season_number)s - %(season)s/%(episode_number)s - %(episode)s.%(ext)s" https://videomore.ru/kino_v_detalayah/5_sezon/367617

# Stream the video being downloaded to stdout
$ youtube-dl -o - BaW_jenozKc
```

I wish I could put this into a script.

> .\youtube-dl.exe -o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" https://soundcloud.com/anttimartikainen/sets/carmina-gloria

Oh, if I just put in an entire album like this it works to fetch them all.

9:05pm.

```
$path = "youtube-dl.exe"
$url = "https://soundcloud.com/anttimartikainen/sets/carmina-gloria"
$arglist = "-o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' $url"
Invoke-Command "./$path $arglist"
```

Damn it, I am trying to run shit, but nothing is working as intended. At this time I really wish I was using Python.

```
$path = "youtube-dl.exe"
$url = "https://soundcloud.com/anttimartikainen/sets/carmina-gloria"
$arglist = "-o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' $url"
Start-Process -FilePath $path -ArgumentList $arglist
```

When I try this the script starts and then turns off. How can I make it show the output?

```
By default, the Start-Process cmdlet does not show the output of the process that it starts. To show the output, you can use the -NoNewWindow parameter to start the process in the current console window.
```

Bing is actually helpful. I keep underestimating it.

```
$path = "youtube-dl.exe"
$url = "https://soundcloud.com/anttimartikainen/sets/carmina-gloria"
$oargs = "'%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s'"
Start-Process -FilePath $path -ArgumentList "-o", $oargs, $url -NoNewWindow -Verbose -Wait
```

I am making progress, but this shit just refuses to run.

```
PS E:\Simulacrum - Heaven's Key\Youtube-dl> ./script.ps1
VERBOSE: Performing the operation "Start-Process" on target "youtube-dl.exe -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://soundcloud.com/anttimartikainen/sets/carmina-gloria".
ERROR: '-' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:-" ) to search YouTube
```

Just, why, why?

```ps1
$path = "youtube-dl.exe"
$url = "https://soundcloud.com/anttimartikainen/sets/carmina-gloria"
$oargs = '"%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"'
Start-Process -FilePath $path -ArgumentList '-o', $oargs, $url -NoNewWindow -Verbose -Wait
```

This works, for fuck's sake.

```ps1
$path = "youtube-dl.exe"
$url = "https://soundcloud.com/anttimartikainen/albums"
$oargs = '"%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"'
Start-Process -FilePath $path -ArgumentList '-o', $oargs, $url -NoNewWindow -Verbose -Wait
```

Now, I can get all his albums in the order I want.

```ps1
$path = "youtube-dl.exe"
$url = "https://soundcloud.com/anttimartikainen/albums"
$output = '-o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"'
Start-Process -FilePath $path -ArgumentList $output, $url -NoNewWindow -Verbose -Wait
```

This should work as well.

I can just run this script directly `./script.ps1`. Also VS Code has good Intellisense for these. It is easier to use than Rider.

This also tells me where I went wrong with F# when trying to open these.

```fs
open System.Diagnostics

let psi = ProcessStartInfo("qwe","qwe")
psi.CreateNoWindow <- true
let q = Process.Start("")
q.WaitForExit()
```

Sigh, now I'll know how to start a process.

Nevermind it. I'll admit the ps1 way is more elegant. But I could more easily abstract things in F#.

```fs
open System.Diagnostics

// Start-Process -FilePath $path -ArgumentList $output, $url -NoNewWindow -Verbose -Wait
let run path args =
    let psi = ProcessStartInfo(path,args |> String.concat " ")
    psi.RedirectStandardOutput <- true
    psi.CreateNoWindow <- true
    let q = Process.Start(psi)
    q.WaitForExit()

let path = "youtube-dl.exe"
let url = "https://soundcloud.com/anttimartikainen/albums"
let output = """-o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" """
run path [output; url]
```

No, it is not good. Unlike with the powershell, I can't figure out how to redirect the output to the terminal.

Those FAKE build scripts had the answer.

Let me check them out.

```fs
open System.Diagnostics

// Start-Process -FilePath $path -ArgumentList $output, $url -NoNewWindow -Verbose -Wait
let run path args =
    let psi = ProcessStartInfo(path,args |> String.concat " ")
    psi.RedirectStandardOutput <- true
    psi.CreateNoWindow <- true
    let q = Process.Start(psi)
    task {
        while q.StandardOutput.EndOfStream = false do
            let! x = q.StandardOutput.ReadLineAsync()
            printfn "%s" x
    } |> ignore
    q.WaitForExit()

let path = "youtube-dl.exe"
let url = "https://soundcloud.com/anttimartikainen/albums"
let output = """-o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" """
run path [output; url]
```

Yeah, this is the correct way.

```fs
open System.Diagnostics

let run path args =
    let psi = ProcessStartInfo(path,args |> String.concat " ")
    psi.RedirectStandardOutput <- true
    psi.CreateNoWindow <- true
    let q = Process.Start(psi)
    while q.StandardOutput.EndOfStream = false do
        let x = q.StandardOutput.ReadLine()
        printfn "%s" x
    q.WaitForExit()

let path = "youtube-dl.exe"
let url = "https://soundcloud.com/anttimartikainen/albums"
let output = """-o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" """
run path [output; url]
```

In fact, it doesn't need to be async at all.

But this is 16 lines of F# to do what 4 lines of PS would out of the box. It also has a longer startup.

10:10am. Sigh, I do not know what has gotten into me. I guess I really wanted to know how to execute commands from inside scripts like I would from the command line. Well, now I sure know how.

The Youtube-dl tool will be quite useful.

10:20am. Sigh, so many of his sounds are great.

Sound of Courage especially.

Do I want to risk copyright infringement just to put these in my video?

Realistically, I can't.

10:25pm. But is it really infringment or just regular sharing and fair use. I am not actually sure in my case. I sent him a message a few days ago and since he hasn't answered, maybe it would be fine?

5/31/2023

7:25am. I ended up pushing myself too hard yesterday, what with messing with running command line scripts and now I am paying the price. I didn't get enough sleep. I guess overwork puts me in a mental state where I cannot rest properly.

I didn't think I was overworking myself, but my mental condition is quite poor right now.

I wish I could just press a switch and go back to sleep.

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=net-7.0

Now I am reading up on this.

```fs
let run path args =
    let psi = ProcessStartInfo(path,args |> String.concat " ")
    psi.RedirectStandardOutput <- true
    psi.CreateNoWindow <- true
    let q = Process.Start(psi)
    q.StandardOutput <- System.Console.OpenStandardOutput()
    while q.StandardOutput.EndOfStream = false do
        let x = q.StandardOutput.ReadLine()
        printfn "%s" x
    q.WaitForExit()
```

I thought the it might be possible to just set the standard output to input rather than reading it all the way like this, but that is not the case.

7:45am. Forget this. Let me put the soundtracks into the video. It is just too much for me to fill out 2.5 hours with free content.

7:50am. This is causing me some consternation, but if it become an issue, I'll apologize to the guy, take the video down and reupload it with different tracks.

It is free advertizing for the author, and I am not making money of these videos, so it shouldn't cause an issue.

8:10am. I am going to just relax a while today. Forget programming.

8:50am. I watched my own screencast for a while with the music. It is pretty good. Let me render it.

8:55am. It will take a while. While that is happening let me make a thumbnail.

9:10am. It is only a bit further than 30m in into the video. Rendering does take a while.

I did the thumb.

9:30am. Uah, I am just wasting time right now.

Did I commit yesterday?"