"9:55am.
```
    from∘to : ∀ {A : Set} {P : A → Set} (xs : List A) → (prf : (¬_ ∘′ Any P) xs)
              → from xs (to xs prf) ≡ prf
    from∘to {P = P} [] prf = extensionality λ ()
```

Yeah, extensionality was the solution.

Should have seen this coming. But my creativity goes way down when I am tired.

```
    from∘to (x ∷ xs) prf = extensionality {!!}
```

```
Goal: (x₁ : Any P₁ (x ∷ xs)) →
      from (x ∷ xs)
      ((λ x₂ → prf (here x₂)) ∷ to xs (λ z → prf (there z))) x₁
      ≡ prf x₁
————————————————————————————————————————————————————————————
prf      : (¬_ ∘′ Any P₁) (x ∷ xs)
xs       : List A₁
x        : A₁
P₁       : A₁ → Set  (not in scope)
A₁       : Set  (not in scope)
xs = xs₁ : List A  (not in scope)
P        : A → Set
A        : Set  (not in scope)
```

Now what do I do about this?

10:05am.

```
    from∘to' : ∀ {A : Set} {P : A → Set} (xs : List A) → (prf : (¬_ ∘′ Any P) xs)
              → (x : Any P xs) → from xs (to xs prf) x ≡ prf x
```

Let me get rid of extensionality. I need to try recursing on the proof.

10:10am.

```
    from∘to' : ∀ {A : Set} {P : A → Set} (xs : List A) → (prf : (¬_ ∘′ Any P) xs)
              → (x : Any P xs) → from xs (to xs prf) x ≡ prf x
    from∘to' xs ¬any any = ⊥-elim (¬any any)
    from∘to : ∀ {A : Set} {P : A → Set} (xs : List A) → (prf : (¬_ ∘′ Any P) xs)
              → from xs (to xs prf) ≡ prf
    from∘to xs prf = extensionality (from∘to' xs prf)
```

Shiiit. This is it?

Funny how a good description makes a difference. I had not even realized I could just apply the thing directly.

10:15am.

```
¬Any≃All¬ P xs =
  record { to = to xs
         ; from = from xs
         ; from∘to = λ prf → extensionality (from∘to xs prf)
         ; to∘from = to∘from
         }
  where
    to : ∀ {A : Set} {P : A → Set} (xs : List A)
         → (¬_ ∘′ Any P) xs → All (¬_ ∘′ P) xs
    to [] prf = []
    to (x ∷ xs) prf = (λ x → prf (here x)) ∷ to xs (λ z → prf (there z))
    from : ∀ {A : Set} {P : A → Set} (xs : List A)
           → All (¬_ ∘′ P) xs → (¬_ ∘′ Any P) xs
    from (x ∷ xs) (¬x-here ∷ ¬all) (here x-here) = ¬x-here x-here
    from (x ∷ xs) (¬x-here ∷ ¬all) (there any) = from xs ¬all any
    from∘to : ∀ {A : Set} {P : A → Set} (xs : List A) → (prf : (¬_ ∘′ Any P) xs)
              → (x : Any P xs) → from xs (to xs prf) x ≡ prf x
    from∘to xs ¬any any = ⊥-elim (¬any any
```

Let me do it like this. No need to back up the traffic.

```
Goal: (y : All (¬_ ∘′ P) xs) → to xs (from xs y) ≡ y
————————————————————————————————————————————————————————————
xs : List A
P  : A → Set
A  : Set  (not in scope)
```

Now let me do the last case. First comes the type signature.

10:20am.

```
open import Data.Empty using (⊥-elim)

¬Any≃All¬ : ∀ {A : Set} (P : A → Set) (xs : List A)
  → (¬_ ∘′ Any P) xs ≃ All (¬_ ∘′ P) xs
¬Any≃All¬ P xs =
  record { to = to xs
         ; from = from xs
         ; from∘to = λ prf → extensionality (from∘to xs prf)
         ; to∘from = to∘from xs
         }
  where
    to : ∀ {A : Set} {P : A → Set} (xs : List A)
         → (¬_ ∘′ Any P) xs → All (¬_ ∘′ P) xs
    to [] prf = []
    to (x ∷ xs) prf = (λ x → prf (here x)) ∷ to xs (λ z → prf (there z))
    from : ∀ {A : Set} {P : A → Set} (xs : List A)
           → All (¬_ ∘′ P) xs → (¬_ ∘′ Any P) xs
    from (x ∷ xs) (¬x-here ∷ ¬all) (here x-here) = ¬x-here x-here
    from (x ∷ xs) (¬x-here ∷ ¬all) (there any) = from xs ¬all any
    from∘to : ∀ {A : Set} {P : A → Set} (xs : List A) → (prf : (¬_ ∘′ Any P) xs)
              → (x : Any P xs) → from xs (to xs prf) x ≡ prf x
    from∘to xs ¬any any = ⊥-elim (¬any any)
    to∘from : ∀ {A : Set} {P : A → Set} (xs : List A) → (prf : All (¬_ ∘′ P) xs)
              → to xs (from xs prf) ≡ prf
    to∘from [] [] = refl
    to∘from (x ∷ x') (prf ∷ prf') with to∘from x' prf'
    ... | prf-rec = cong (prf ∷_) prf-rec
```

And it is done. I am awesome. I can't believe I actually did this.

Now, rather than going forward, I want to backtrack and do the exercises that I've missed. There is the sum in this chapter, but I also missed one in the previous one. Let me mop this up now that I know how to deal with it.

```
-- All-++-≃ :  ∀ {A : Set} {P : A → Set} (xs ys : List A) →
--             Any P (xs ++ ys) ≃ (Any P xs ⊎ Any P ys)
-- All-++-≃ {A} {P} [] ys =
--   record { to = inj₂
--          ; from = _⇔_.from (Any-++-⇔ [] ys)
--          ; from∘to = λ { (here x) → refl ; (there x) → refl}
--          ; to∘from = λ { (inj₂ y) → refl}
--          }
-- All-++-≃ {A} {P} (x ∷ xs) ys =
--   record { to = _⇔_.to (Any-++-⇔ (x ∷ xs) ys)
--          ; from =  _⇔_.from (Any-++-⇔ (x ∷ xs) ys)
--          ; from∘to = λ { (here x) → refl
--                          ; (there prf) → {!!} -- I need to destructure `to xs ys prf` here somehow.
--                          }
--          ; to∘from = λ { (inj₁ (here x)) → refl
--                        ; (inj₁ (there x)) → {!!}
--                        ; (inj₂ y) → {!!}
--                        }
--          }
```

Ah, there were more than one in this chapter. I need to convert this into the form I've been using in the exercise that I just finished.

I'll return to this later.

10:25am.

```
  sum-downFrom : ∀ (n : ℕ)
    → sum (downFrom n) * 2 ≡ n * (n ∸ 1)
```

Let me mess with this one for a while.

```
sum-downFrom (suc n) with sum-downFrom n
... | prf-rec = {!!}
```

```
Goal: (n + foldr _+_ 0 (downFrom n)) * 2 ≡ n + n * n
————————————————————————————————————————————————————————————
prf-rec : foldr _+_ 0 (downFrom n) * 2 ≡ n * (n ∸ 1)
```

Now if there is something I want, that would be figuring out how to distribute the multiplication.

10:40am.

```
*-distˡ : ∀ (a b c : ℕ) → c * (a + b) ≡ c * a + c * b
*-distˡ a b zero = refl
*-distˡ a b (suc c) with *-distˡ a b c
... | prf-rec rewrite
    prf-rec
    | +-assoc a b (c * a + c * b)
    | +-assoc a (c * a) (b + c * b)
    | sym (+-assoc b (c * a) (c * b))
    | sym (+-assoc (c * a) b (c * b))
    | +-comm b (c * a) = refl

*-distʳ : ∀ (a b c : ℕ) → (a + b) * c ≡ a * c + b * c
*-distʳ a b c rewrite *-comm (a + b) c | *-comm a c | *-comm b c = *-distˡ a b c
```

Here is right distributivity implemented in terms of the left.

Now let me lick this problem.

10:45am.

```
sum-downFrom : ∀ (n : ℕ)
  → sum (downFrom n) * 2 ≡ n * (n ∸ 1)
sum-downFrom zero = refl
sum-downFrom (suc n) with sum-downFrom n
... | prf-rec rewrite
              *-distʳ n (foldr _+_ 0 (downFrom n)) 2
              | prf-rec = {!!}
```

```
Goal: n * 2 + n * (n ∸ 1) ≡ n + n * n
————————————————————————————————————————————————————————————
prf-rec : foldr _+_ 0 (downFrom n) * 2 ≡ n * (n ∸ 1)
n       : ℕ
```

Now I finally have this is a form that I can solve it.

10:45am.

```
sum-downFrom (suc n) with sum-downFrom n
... | prf-rec rewrite
              *-distʳ n (foldr _+_ 0 (downFrom n)) 2
              | prf-rec
              | *-comm n 2
              | +-identityʳ n = {!!}
```
```
Goal: n + n + n * (n ∸ 1) ≡ n + n * n
————————————————————————————————————————————————————————————
prf-rec : foldr _+_ 0 (downFrom n) * 2 ≡ n * (n ∸ 1)
n       : ℕ
```

Maximally cleaned up. Let me prove that `n + n * (n ∸ 1) ≡ n * n`.

10:55am.

```
sqr-+∸ : ∀ n → n + n * (n ∸ 1) ≡ n * n
sqr-+∸ zero = refl
sqr-+∸ (suc n) rewrite *-comm n (suc n) = refl

sum-downFrom : ∀ (n : ℕ)
  → sum (downFrom n) * 2 ≡ n * (n ∸ 1)
sum-downFrom zero = refl
sum-downFrom (suc n) with sum-downFrom n
... | prf-rec rewrite
              *-distʳ n (foldr _+_ 0 (downFrom n)) 2
              | prf-rec
              | *-comm n 2
              | +-identityʳ n
              | +-assoc n n (n * (n ∸ 1)) = cong (n +_) (sqr-+∸ n)
```

I did it! Gauss has nothing on me. This proof is quite ugly though, I should rewrite it using chains of equations.

I'll master that at some later point though. Right now I just want to get through this.

Now what was the exercise that I skipped in one of the previous chapters?

```
ℕ-≃-Can : ℕ ≃ ∃[ x ](Can x)
ℕ-≃-Can = record { to = λ x → ⟨ to x , Can- (from-to-identity {x}) ⟩
                 ; from = λ { ⟨ x , x₁ ⟩ → from x}
                 ; from∘to = λ x → from-to-identity
                 ; to∘from = {!!}
                 }
```

It was this thing.

11:10am.

```
    to' : (x : ℕ) → Σ Bin Can
    to' = λ x → ⟨ to x , Can- (from-to-identity {x}) ⟩
    from' : (x : Σ Bin Can) → ℕ
    from' = λ { ⟨ x , x₁ ⟩ → from x}
    from∘to : (x : ℕ) → from (to x) ≡ x
    from∘to = λ x → from-to-identity
    to∘from : ( ⟨ a , b⟩ : Σ Bin Can) → to (from b) ≡ b
    to∘from ⟨ n , Can- x ⟩ = {!!}
```
```
E:\TheoremProving\plfa\Quantifiers.lagda:596,50-51
Not in scope:
  b at E:\TheoremProving\plfa\Quantifiers.lagda:596,50-51
    (did you mean 'B'?)
when scope checking b
```

I am having a lot of difficulty just writing the type signature for this.

11:15am.

```
    to∘from : (a : Bin) → (b : Can a) → to' (from' ⟨ a , b ⟩) ≡ ⟨ a , b ⟩
    to∘from = {!!}
```

Uah, finally.

https://mangadex.org/title/275/knight-run

Oh, more of this is out. Let me leave it for later.

```
    to∘from : (a : Bin) → (b : Can a) → to' (from' ⟨ a , b ⟩) ≡ ⟨ a , b ⟩
    to∘from a b = {!!}
```

Let me finally solve this thing.

```
    to∘from : (a : Bin) → (b : Can a) → to' (from' ⟨ a , b ⟩) ≡ ⟨ a , b ⟩
    to∘from n (Can- x) = {!!}
```
```
Goal: to' (from' ⟨ to n , Can- x ⟩) ≡ ⟨ to n , Can- x ⟩
————————————————————————————————————————————————————————————
n : Bin
x : from (to n) ≡ n
n : ℕ  (not in scope)
```

Hmmm...what do I do about this?

11:25am. `from' ⟨ to n , Can- x ⟩` In this part in particular why isn't it normalizing an extra step. If it did that I could...

```
to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
```

Let me just change the signature to this. That should take care of it.

```
    to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
    to∘from n (Can- prf) rewrite prf = {!!}
```

```
E:\TheoremProving\plfa\Quantifiers.lagda:597,5-44
w != from-helper 1 (to n) of type ℕ
when checking that the type
{n : ℕ} (prf : from-helper 1 (to n) ≡ n) (w : ℕ) (w₁ : w ≡ n) →
⟨ to w , Can- from-to-identity ⟩ ≡ ⟨ to n , Can- w₁ ⟩
of the generated with function is well-formed
```

I really have no idea what is going on here.

Just how does rewrite work?

11:30am. I am a bit confused about that n there.

```
Goal: to' (from (to n)) ≡ ⟨ to n , Can- prf ⟩
————————————————————————————————————————————————————————————
n   : Bin
prf : from (to n) ≡ n
n   : ℕ  (not in scope)
```

Yeah, n is bin here.

```
to : ℕ → Bin
to zero = (x0 nil)
to (suc x) = inc (to x)
```

Isn't this some kind of type error. What the hell?

```
    to∘from : (a : Bin) → (b : Can a) → to' (from a) ≡ ⟨ a , b ⟩
    to∘from n prf = {!!}
```
```
Goal: to' (from n) ≡ ⟨ n , prf ⟩
————————————————————————————————————————————————————————————
prf : Can n
n   : Bin
```

Both of these can't possibly be right.

11:35am. No I cannot solve this problem on my own after all.

I am going to have to ask.

But not on SO. I'll open an issue Agda's Github repo.

11:55am. I've opened an issue. I won't paste the link to it here because it will add a reference from my commit.

12pm. I guess I won't be beating this exercise today after all. I'll forget about it for the time being and move on to the rest.

Let me take a break here. Damn I am hungry."