"4:35pm. The next chapter is `Typechecking`.
4:45pm. Hmmm, I do not know why, but `MoreStlc` is not compiling for some reason. The IDE is shit though, so there is no error.

This is so annoying. I remember having these kinds of issues years ago. It is a miracle that I even go Coq to run back then.

Now rather than going into the next chapter, I will be messing with this.

4:55pm.

```
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe morestlc.v
Fatal error: not enough memory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe stlc.v
Fatal error: not enough memory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe equiv.v
Fatal error: not enough memory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe -Q equiv.v
coqc: -Q: no such file or directory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe equiv.v equiv.vo
Fatal error: not enough memory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe -compile equiv.v
coqc: -compile: no such file or directory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe equiv.v -compile
coqc: -compile: no such file or directory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe equiv.v --compile
coqc: --compile: no such file or directory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe --compile "E:\TheoremProving\plf\Equiv.v"
coqc: --compile: no such file or directory
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe -compile "E:\TheoremProving\plf\Equiv.v"
coqc: -compile: no such file or directory
```

Am I pissed right now. I sure am.

4:50pm. Let me try resetting.

```
PS E:\TheoremProving\plf> C:\Coq\bin\coqc.exe equiv.v
File ".\equiv.v", line 4, characters 24-28:
Error:
Cannot find a physical path bound to logical path matching suffix
<> and prefix PLF.
```

This sure is annoying.

Let me try the IDE again.

5pm. Nope. I guess I'll try updating Coq then. This version is a few months out of date.

Actually it is 9 months at this point. Let me get 8.9.1. Right now I have 8.8.2.

5:15pm. That did nothing. What a waste of time.

I am going to open a bug report.

5:20pm. No this does not feel like an out memory error now. The out of memory is because I kept repeatedly compiling.

5:30pm.

```
#### Description of the problem

I am trying to compile [MoreStlc.v](https://softwarefoundations.cis.upenn.edu/plf-current/MoreStlc.html) and the compilation won't go through. The IDE does not give any error messages (or any messages ever apart from the `Running: coqc -Q E:\TheoremProving\plf PLF "E:\TheoremProving\plf\MoreStlc.v" 2>&1` variants) and I am not sure how to try it from the command line due to having to supply paths manually.

At first I suspected that compilation takes too much memory, but that was probably due to me repeatedly trying to compile and the IDE not cleaning up. The particular chapter of the book has the most automation of anything up to date, so that may have something to do with this though.

Compilation does work for all the chapters leading up to this. Moreover `MoreStlc.v` works fine in the IDE.

What should I do here?

#### Coq Version

8.8.2 and just now 8.9.1. Windows 10.
```

I won't paste the link to the issue as it will get referenced from the Spiral repo, but how about I call it a day here? Shit like this happens sometimes, and there is nothing one can do but give it time.

5:45pm. How annoying. `LibTactics.v` won't compile either.

Oh, it does. I had to reset the IDE. It seems trying to compile `MoreStlc` froze it somehow.

5:50pm. Ok, I've gone through the book and only the `Typechecking` and `RecordSub` chapters depend on `MoreStlc`. `Typechecking` in particular has more of those dreary extension exercises as a part of a 5-star exercise so I am tempted to just skip it anyway. I do not care about this material in particular. I have the Agda book and volume 3 coming up after this.

I get the sense that I've gotten through the meat of the book already and the rest are just details.

5:55pm. With that out of the way, I'll call it a day here.

Until I can resolve the compilation issues, I'll skip the offending chapters.

In a way this is good for me as I have two chapters less to deal with. It won't be long until I am done with volume two. As a personal estimate, given how I am just gnawing through these exercises and using `eauto` like it is nothing, I get the sense that I really have gotten something for my 3 months of effort.

I am no longer like I was 3 months ago. At this intermediate point, I can honestly state that I am proficient at dependently typed programming and have no fear of using it at large. I am no longer getting stuck in dumb ways and baring super strange proof like the 5 star Hoare one, I can get to the solution with some effort even without help.

Idris or Agda, or if I wind up doing Haskell, I won't embarass myself using them at this current level.

6pm. As far as volume 2 is concerned, I've gone through the hardest part of the book, and the hardest part of my education in learning depenently typed programming.

Just like with natural ones, learning languages is always the hardest at the start.

From here on out, I will be able to look forward to getting tangible use out of them. That having said, getting to that fabled expert level and to the point where I am making advances in ML is quite a long trek.

I think I'll be able to polish off the rest of the book in the next week and then comes the Agda book. I am tempted to skip it, but I do need the exercise in Agda.

6:30pm. Let me commit here. Time for a well deserved rest."