"8:40am. I got up 15m ago. Maybe I should just start, but I am groggy from this early wakeup.
https://fsharp.org/history/hopl-final/hopl-fsharp.pdf

Yesterday I've been reading this paper on the history of F#.

Ok, let me read the chap of Hagure Idol, a bit of that paper and then I'll resume from yesterday.

9:30am. Enough. Let me start. I am over my grogginess, and for the next few hours, I need to focus on figuring out that monster function.

9:35am.

```
 function handleRequest(requestMessage: RequestMessage) {
  if (isDisposed()) {
   // we return here silently since we fired an event when the
   // connection got disposed.
   return;
  }

  function reply(resultOrError: any | ResponseError<any>, method: string, startTime: number): void {
   let message: ResponseMessage = {
    jsonrpc: version,
    id: requestMessage.id
   };
   if (resultOrError instanceof ResponseError) {
    message.error = (<ResponseError<any>>resultOrError).toJson();
   } else {
    message.result = resultOrError === void 0 ? null : resultOrError;
   }
   traceSendingResponse(message, method, startTime);
   messageWriter.write(message);
  }
  function replyError(error: ResponseError<any>, method: string, startTime: number) {
   let message: ResponseMessage = {
    jsonrpc: version,
    id: requestMessage.id,
    error: error.toJson()
   };
   traceSendingResponse(message, method, startTime);
   messageWriter.write(message);
  }
```

This is not hard at all.

I realized yesterday that `messageWriter` and `messageReader` args do not really have a dependency on those other modules. I can just treat them as opaque.

And `trace` functions I can ignore. With that, this becomes quite straightforward.

9:45pm. Focus me, stop with the social media.

```
  let element = requestHandlers[requestMessage.method];
  let type: MessageType | undefined;
  let requestHandler: GenericRequestHandler<any, any> | undefined;
  if (element) {
   type = element.type;
   requestHandler = element.handler;
  }
  let startTime = Date.now();
```

9:50am.

```
  let element = env.requestHandlers[requestMessage.method];
  let type: MessageType | undefined;
  let requestHandler: GenericRequestHandler<any, any> | undefined;
  if (element) {
   type = element.type;
   requestHandler = element.handler;
  }
  let startTime = Date.now();
  if (requestHandler || starRequestHandler) {
   let cancellationSource = new CancellationTokenSource();
   let tokenKey = String(requestMessage.id);
   requestTokens[tokenKey] = cancellationSource;
   try {
    let handlerResult: any;
    if (requestMessage.params === void 0 || (type !== void 0 && type.numberOfParams === 0)) {
     handlerResult = requestHandler
      ? requestHandler(cancellationSource.token)
      : starRequestHandler!(requestMessage.method, cancellationSource.token);
    } else if (Is.array(requestMessage.params) && (type === void 0 || type.numberOfParams > 1)) {
     handlerResult = requestHandler
      ? requestHandler(...requestMessage.params, cancellationSource.token)
      : starRequestHandler!(requestMessage.method, ...requestMessage.params, cancellationSource.token);
    } else {
     handlerResult = requestHandler
      ? requestHandler(requestMessage.params, cancellationSource.token)
      : starRequestHandler!(requestMessage.method, requestMessage.params, cancellationSource.token);
    }
```

This code is so shitty that it boggles my mind...but I sort of get it. Here all it is doing is calling the request handler. Except rather than passing in an array with the arguments, it is doing extra work for itself by doing this nonsense. Varargs are a serious design mistake.

I find it extremely ironic that whenever a language wants to be appealing to amateurs, it tries to resemble C.

9:55am.

```
env.requestTokens[tokenKey] = cancellationSource;
```

Oh, remember that dictionary idea from yesterday. It seems this is being done here.

10am. Let me move to the next part.

```
let handlerResult: any;
...
let promise = handlerResult as Thenable<any | ResponseError<any>>;
```

This code hasn't an ounce of grace nor class. Peasant work.

What is even the point of having a type system if you are not going to use it for correctness.

```
interface Thenable<T> extends PromiseLike<T> { }
```

I see this turd being imported everywhere.

10:05am.

```
    let promise = handlerResult as Thenable<any | ResponseError<any>>;
    if (!handlerResult) {
     delete requestTokens[tokenKey];
     replySuccess(handlerResult, requestMessage.method, startTime);
    } else if (promise.then) {
     promise.then((resultOrError): any | ResponseError<any> => {
      delete requestTokens[tokenKey];
      reply(resultOrError, requestMessage.method, startTime);
     }, error => {
      delete requestTokens[tokenKey];
      if (error instanceof ResponseError) {
       replyError(<ResponseError<any>>error, requestMessage.method, startTime);
      } else if (error && Is.string(error.message)) {
       replyError(new ResponseError<void>(ErrorCodes.InternalError, `Request ${requestMessage.method} failed with message: ${error.message}`), requestMessage.method, startTime);
      } else {
       replyError(new ResponseError<void>(ErrorCodes.InternalError, `Request ${requestMessage.method} failed unexpectedly without providing any details.`), requestMessage.method, startTime);
      }
     });
    } else {
     delete requestTokens[tokenKey];
     reply(handlerResult, requestMessage.method, startTime);
    }
```

So it executes the thing, and then in so many words it raises an error if it fails.

It also deletes those request tokens along the way.

10:15am.

```
function handleResponse(responseMessage: ResponseMessage) {
```

Now comes this thing.

```
  if (isDisposed()) {
   // See handle request.
   return;
  }

  if (responseMessage.id === null) {
   if (responseMessage.error) {
    logger.error(`Received response message without id: Error is: \n${JSON.stringify(responseMessage.error, undefined, 4)}`);
   } else {
    logger.error(`Received response message without id. No further error information provided.`);
   }
  } else {
   let key = String(responseMessage.id);
   let responsePromise = responsePromises[key];
```

10:15am.

```
interface ResponsePromise {
 method: string;
 timerStart: number;
 resolve: (response: any) => void;
 reject: (error: any) => void
}
```

```
  if (responseMessage.id === null) {
   if (responseMessage.error) {
    logger.error(`Received response message without id: Error is: \n${JSON.stringify(responseMessage.error, undefined, 4)}`);
   } else {
    logger.error(`Received response message without id. No further error information provided.`);
   }
  } else {
```

Why even allow it to be null, why not set it to a number?

```
if (responsePromise) {
```

Now it is checking here whether it is undefined.

Horrible taste. At this point it should be defined.

```
   if (responsePromise) {
    delete env.responsePromises[key];
    try {
     if (responseMessage.error) {
      let error = responseMessage.error;
      responsePromise.reject(new ResponseError(error.code, error.message, error.data));
     } else if (responseMessage.result !== void 0) {
      responsePromise.resolve(responseMessage.result);
     } else {
      throw new Error('Should never happen.');
     }
    } catch (error) {
     if (error.message) {
      logger.error(`Response handler '${responsePromise.method}' failed with message: ${error.message}`);
     } else {
      logger.error(`Response handler '${responsePromise.method}' failed unexpectedly.`);
     }
    }
   }
```

The stuff here is not that difficult. There is just a massive amount of boiler plate, and a massive lack of pattern matching, and a massive excess of cases being tested for due to the type looseness of the code.

```
 function handleNotification(message: NotificationMessage) {
  if (isDisposed()) {
   // See handle request.
   return;
  }
```

Let me move to this. Otherwise, the function of all of this is straightforward.

10:25am.

```
  let type: MessageType | undefined = undefined;
  let notificationHandler: GenericNotificationHandler | undefined;
  if (message.method === CancelNotification.type.method) {
   notificationHandler = (params: CancelParams) => {
    let id = params.id;
    let source = env.requestTokens[String(id)];
    if (source) {
     source.cancel();
    }
   };
  } else {
   let element = env.notificationHandlers[message.method];
   if (element) {
    notificationHandler = element.handler;
    type = element.type;
   }
  }
  if (notificationHandler || env.starNotificationHandler) {
   try {
    traceReceivedNotification(message);
    if (message.params === void 0 || (type !== void 0 && type.numberOfParams === 0)) {
     notificationHandler ? notificationHandler() : env.starNotificationHandler!(message.method);
    } else if (Is.array(message.params) && (type === void 0 || type.numberOfParams > 1)) {
     notificationHandler ? notificationHandler(...message.params) : env.starNotificationHandler!(message.method, ...message.params);
    } else {
     notificationHandler ? notificationHandler(message.params) : env.starNotificationHandler!(message.method, message.params);
    }
   } catch (error) {
    if (error.message) {
     logger.error(`Notification handler '${message.method}' failed with message: ${error.message}`);
    } else {
     logger.error(`Notification handler '${message.method}' failed unexpectedly.`);
    }
   }
  } else {
   env.unhandledNotificationEmitter.fire(message);
  }
 }
```

This one is similar in structure to the first handler. I won't dwell on it too much.

During the night, I've been dreaming of cutting this down to size, but right now I am thinking this needs a redesign. I can't really optimize the existing design straight up. All I can do is grasp its functionality and then impose my own vision.

```
 function handleInvalidMessage(message: Message) {
  if (!message) {
   logger.error('Received empty message.');
   return;
  }
  logger.error(`Received message which is neither a response nor a notification message:\n${JSON.stringify(message, null, 4)}`);
  // Test whether we find an id to reject the promise
  let responseMessage: ResponseMessage = message as ResponseMessage;
  if (Is.string(responseMessage.id) || Is.number(responseMessage.id)) {
   let key = String(responseMessage.id);
   let responseHandler = env.responsePromises[key];
   if (responseHandler) {
    responseHandler.reject(new Error('The received response has neither a result nor an error property.'));
   }
  }
 }
```

10:30am.

```
function traceSendingRequest(message: RequestMessage): void {
```

I am going to ignore these `trace` functions. Let me move on.

10:35am. They take up a lot of space, but they are mostly paste. I am already 4/5ths of the way in.

```
 function undefinedToNull(param: any) {
  if (param === void 0) {
   return null;
  } else {
   return param;
  }
 }
```

Hmmm, so `param === void 0` tests for undefined and not null. Interesting.

Agh, this is nasty. I looked into the signature, and this is literally `any -> any`.

10:40am.

```
    result = [];
    for (let i = 0; i < params.length && i < numberOfParams; i++) {
     result.push(undefinedToNull(params[i]));
    }
    if (params.length < numberOfParams) {
     for (let i = params.length; i < numberOfParams; i++) {
      result.push(null);
     }
    }
```

Does this codebase do anything except mess around with nulls?

Personally I would just throw exceptions everywhere until the other side sends me soundly formed data.

I do get that there is some advantage in JS being loose as it is given that it was originally designed for tiny web scripts. But that is not the kind of design you want to adopt when doing large library internals.

10:45am.

```
 let connection: MessageConnection = {
  sendNotification: (type: string | MessageType, ...params: any[]): void => {
```

What is this? I was the impression that messageReader and messageWriter took care of the message transfer.

10:50am.

```
  sendNotification: (type: string | MessageType, ...params: any[]): void => {
   throwIfClosedOrDisposed();

   let method: string;
   let messageParams: any | any[] | null;
   if (Is.string(type)) {
    method = type;
    switch (params.length) {
     case 0:
      messageParams = null;
      break;
     case 1:
      messageParams = params[0];
      break;
     default:
      messageParams = params;
      break;
    }
   } else {
    method = type.method;
    messageParams = computeMessageParams(type, params);
   }
   let notificationMessage: NotificationMessage = {
    jsonrpc: version,
    method: method,
    params: messageParams
   };
   traceSendingNotification(notificationMessage);
   messageWriter.write(notificationMessage);
  }
```

This confuses me. I thought the event loop was suppose to be handling the messages. Why is this writing to the system directly?

10:55am.

```
sendRequest: <R, E>(type: string | MessageType, ...params: any[]) => {
```

The same goes for this. I won't paste the whole thing as it is enormous, but this whole thing has heavily obscured intent.

11:05am.

```
return connection;
```

To me this is maybe the most surprising of the whole thing.

```
  listen: () => {
   throwIfClosedOrDisposed();
   throwIfListening();

   env.state = ConnectionState.Listening;
   messageReader.listen(callback);
  },
```

Ah, so this is where the `messageQueue` actually comes into play.

11:10am. No, I can't refactor this, but now that I've gone through this motion I have some grasp on what all this is doing.

I'd never used something as shoddy as this, but I have a rough idea of what it is.

At any rate, the `_createMessageConnection` function is a red herring. In order to really redesign it, I need to consider what comes after it. Doing it in isolation is no good after all. This is because I am not sure the thing is needed at all. If I were doing it, `_createMessageConnection` would be quite small indeed.

11:20am. Let me gather my thoughts.

...

Yeah, forget `main.ts`. Not only is the thing an abomination, but it does not seem needed at all.

I am looking at the wrong thing here.

The readers and the writers have the actual functionality that I need to study.

...And I did that yesterday. From what I've seen it is just straightforward passing of JSON.

The one thing I haven't figured yet are those connection and message tests.

11:25am.

```
let data: string = 'Content-Length: 43\r\n\r\n{"jsonrpc":"2.0","id":1,"method":"example"}';
```

Indeed the body is exactly 43 chars.

11:45am. I've already started browsing 4chan.

```
 test('Read partial', (done) => {
  let readable = new Readable();
  let reader = new StreamMessageReader(readable);
  reader.partialMessageTimeout = 100;
  let partOne = 'Content-Length: 43\r\n\r\n';
  let partTwo = '{"jsonrpc":"2.0","id":1,"method":"example"}';
  reader.listen((message: RequestMessage) => {
   assert.equal(message.id, 1);
   assert.equal(message.method, 'example');
   setTimeout(() => {
    done();
   }, 200);
  });
  reader.onPartialMessage((_info) => {
   setTimeout(() => {
    readable.push(partTwo);
    readable.push(null);
   }, 20);
  });
  readable.push(partOne);
 });
```

Is there really any point at all to partial messages? Or are they meaningless filler like the rest?

At any rate, with this I am done with message tests. Everything in `messages.test.ts` is clear to me.

The only thing left now are connection tests. They are 500 LOC long so it will take me a few hours to completely study them.

11:50am. Let me stop here then."