"1:35pm. Ok, enough slacking. Let me do the chores and it is back to studying webdev. I really am into CCG and am having difficulty prying myself away. Is my luck good or bad? I am finally having fun with manga and now programming is getting fun as well?
Well, this is a good time to be in. I should not regret the circumstances, but switch gears and dive back in.

2:05pm. Done with chores. Let me finally resume. I'll aim to get through the chapter I am currently doing and the next one today.

```
export function createElement(tag: any, props: Object, ...children: Object[])
    : HTMLElement {
    function addChild(elem: HTMLElement, child: any) {
        elem.appendChild(child instanceof Node ? child
            : document.createTextNode(child.toString()));
    }
    if (typeof tag === "function") {
        return Object.assign(new tag(), { props: props || {} }).getContent();
    }
    const elem = Object.assign(document.createElement(tag), props || {});
    children.forEach(child => Array.isArray(child)
        ? child.forEach(c => addChild(elem, c)) : addChild(elem, child));
    return elem;
}

declare global {
    namespace JSX {
        interface ElementAttributesProperty { props; }
    }
}
```

I am thinking about this currently. I definitely find this sort of code quite opaque.

Well, let me leave it aside for the time being.

2:35pm.

```
    getContent(): HTMLElement {
        return
            <h3 className="bg-secondary text-center text-white p-2">
                {this.getElementText()}
            </h3>
    }
```

Why is it telling me that this code is unreachable?

Actually, the problem is that it cannot find the `createElement` function...

2:40pm. Figure the above out.

```
Uncaught (in promise) TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at eval (index.ts:23)
```

...I am confused. How am I supposed to debug this again?

2:45pm.

```
            let rootElement = document.getElementById("app");
            rootElement.innerHTML = "";
            debugger;
            rootElement.appendChild(elem);
```

This is really great. The Chrome debugger will stop on this and show me the locals. There is also the option to pause on exceptions.

At any rate, the problem is that the elem here is undefined.

```
export function createElement(tag: any, props: Object, ...children: Object[])
    : HTMLElement {
    function addChild(elem: HTMLElement, child: any) {
        elem.appendChild(child instanceof Node ? child
            : document.createTextNode(child.toString()));
    }
    if (typeof tag === "function") {
        return Object.assign(new tag(), { props: props || {} }).getContent();
    }
    const elem = Object.assign(document.createElement(tag), props || {});
    children.forEach(child => Array.isArray(child)
        ? child.forEach(c => addChild(elem, c)) : addChild(elem, child));
    return elem;
}
```

The problem should definitely be in this function, but I am not sure what the issue is.

```
export function createElement(tag: any, props: Object, ...children: Object[])
    : HTMLElement {
    function addChild(elem: HTMLElement, child: any) {
        elem.appendChild(child instanceof Node ? child
            : document.createTextNode(child.toString()));
    }
    debugger;
    console.log("Hello factory.");
```

This is strange. This function is not even getting called.

```
class HtmlDisplay {
    getContent() {
        return;
        Object(_tools_jsxFactory__WEBPACK_IMPORTED_MODULE_0__["createElement"])("h3", { className: "bg-secondary text-center text-white p-2" }, this.getElementText());
    }
    getElementText() {
        return `${this.props.products.length} Products, `
            + `Order total: $${this.props.order.total}`;
    }
}
```

This is what it is getting compiled to. What is that `return` doing there?

```
    getContent(): HTMLElement {
        return
            <h3 className="bg-secondary text-center text-white p-2">
                {this.getElementText()}
            </h3>
    }
```

Ah, wait. It is telling me that this code is unreachable.

```
    getContent(): HTMLElement {
        const x =
            <h3 className="bg-secondary text-center text-white p-2">
                {this.getElementText()}
            </h3>;
        return x;
    }
```

Just as I thought.

```
        return <h3 className="bg-secondary text-center text-white p-2">
                {this.getElementText()}
                </h3>
```

Ah, so the statement has to begin on the same line as the return. Whops. Did not see this coming. I thought JS was no indentation sensitive?

Why did TS just accept an empty return?

...Strict typechecking breaks everything. Nevermind, I'll leave figuring this out for later.

2:55pm. At any rate this works now, though the way it works is highly convoluted.

3pm. Let me stop here so I can read Omega.

...Let me resume.

3:05pm. What is next? I feel like I did not get as much out of this as I could. If I had to do this in strict mode, I have no idea how I'd deal with this.

3:20pm. Ah, let me take a break. My focus is low.

3:30pm. Let me resume. Since I am slacking so much, I am going to put in some overtime today.

Let me do this thing.

To be honest, this latest tsx parts are disappointing. That magic global thing really makes me look askance at this.

3:40pm. My sense is that to really internalize this, I would need to practice this for a while so I am not going to bother with it too much at the moment. Just going through the motions here is enough to give me a basic gist of it.

3:45pm. 399/551. Done with that chapter. Let me move to the next one.

I get the sense that to really know what I want, I am going to learn the basics properly. This can only be a rough intro.

I thought I would focus deeply on this, but since the elegance of this is lacking, I think I'll do the minimum and move on. I am not sure what my reaction to the framework chapters will be at this rate.

I'll aim to do another 50 pages today at least, and I'll finish the book tomorrow. Then come the basics and ASP.NET tutorials (again). After this is done, I am going to do some real webdev programming. I am not sure what I'll do. The old exercise of doing a RL agent and graphing its progress is always a good one.

The main point is not to just do programming puzzles (I am expert at those), but to get some GUI stuff done. Well, I'll figure that out when it comes to it. I am sure I'll find something worth doing.

3:55pm.

```
Error: Cannot find module 'E:\Typescript\essential-ts\webapp\data.js'
```

Why am I getting this error when the file is right there?

4:20pm.

```
export const minimumValue = (propName: string, min: number) =>
    (constructor: any, methodName: string, descriptor: PropertyDescriptor): any => {
        const origFunction = descriptor.value;
        descriptor.value = async function wrapper(...args) {
            let results = await origFunction.apply(this, args);
            return results.map(r => ({
                ...r, [propName]: r[propName] < min
                    ? min : r[propName]
            }));
        }
    }
```

I admit, I thought I understood decorators. In Python they are just plain function composition. But here, I just do not see it. This definitely isn't that.

4:25pm. Hmmm, okay, I see it. I get this thing.

But is this really that better compared to simply using function composition? I am not sure.

I can't see these hacky features as anything other than design by committee.

4:40pm. Ok, 13 more pages left to go in this chapter. As much as I was into this in the morning, I now find this quite tedious.

5:05pm.

```
const express = require("express");
const jsonServer = require("json-server");
const app = express();
app.use("/", express.static("dist"));
app.use("/", express.static("assets"));

const router = jsonServer.router("data.json");
app.use(jsonServer.bodyParser);
app.use("/api", (req, resp, next) => router(req, resp, next));
const port = process.argv[3] || 4000;
app.listen(port, () => console.log(`Running on port ${port}`));
```

The stuff that is here is something I am going to have to understand.

5:20pm. Shit, docker is 900mb.

How about I just skip this step until I need it? Yes.

426/551. And I am done with the web chapters.

5:25pm. Mrrhhh...

The tedium is hitting me here.

I said that I could really gain by learning this stuff, but not like this with these overly complex examples.

Right now I really should keep going, but the tedium is hitting me.

Well, the towards the end, I would not say the examples were really too complex. They were borderline.

So what I am going to do here?

Let me just look ahead to see if this chapter is worth studying. If it is, I'll leave the focused study for tomorrow. If not, I'll skip it.

I want to be done with this book quickly so I can really start studying the fundamentals.

5:30pm. Only two days left in the month. I had less time left 'till the review than I'd thought.

5:45pm. I have no idea. I am out of focus. I am not at all sure of whether Angular is worth studying. One thing I am sure of is that I want to leave this for tomorrow.

Also, I only really one of the frameworks, not all 3, so that is what I am going to aim for.

That webguy mentioned that Vue is the easiest, so I might go for it just for that. Decorators aren't my favorite thing exactly.

5:50pm. It was fun for a bit, but TS is really not satisfying my FP urges. I really hate how `const` is 5 letters instead of something sensible. The code examples here put me ill at ease.

I want much more control over state.

6pm. Well, let me stop here. I'll wrap the book up properly tomorrow. Then I'll do the monthly review. It should not be long this time."