"9:15am. Let me chill a bit and then I will start.
9:25am. Done. Let me focus. Forget chilling. I do not know what I'll do today, but I know in which direction I must go.

9:30am. This latest issue really strikes at Spiral's weakness. My mental model of quite a lot of things is beyond the conception of what regular ML researchers can come up with. I took care of to maximize its strengths.

But now I need to deal with its weaknesses.

Yes, I can improve various aspects of it. I can put in string interpolation, the build and run command. I can take the time to do bindings. But I won't be able to beat Python in what it is strong.

A lot of the capabilities of Python are giving me heartache when I think of emulating them. Just forget it.

I do not want to work on Spiral anymore. I do not want to put in string interpolation or anything else at this moment in time. Solidifying editor support was a special case. Serious bugs that crash the language take precedence over everything else. But absolutely do not want to put in functionality I do not NEED.

Not before I get my first win.

Even if I can get even a single real world win, I could say: 'I beat poker and I can do it again whenever I want. It is my own piggy bank now. Since I do not need the money, let me instead improve the language.'

9:35am. Here is the time to fight.

But since I am always measuring the effectiveness of my moves, I can understand my problem. I am getting crushed by the amateur style.

https://processing.org/tutorials/

By that I mean code like in here - no abstractions whatsover, just plopping the instructions down. It is the same kind of thing like in the Kivy tutorials that I watched.

This is why I've been depressed. I can't mentally score a decisive win - on paper when it comes to UIs, Spiral should be superior than Python, but the circumstances are conspiring against me.

I need to evolve the way I program again.

In the future it will be different, I'll have exactly the libraries and the tools that I need. I will have the time to set everything up properly. Python and all those lesser languages will become the past. But now I can't beat them.

No matter how good my skills and my overall technique is, I can't beat the decades of effort put in by the overall community. I've been able to work around this, thus far, but at the same time this is how far I will go.

I am on the verge of success, but I won't be able to make the last step unless I do this.

9:45am. So what I will be doing today might seem extremely simple from the outside - I'll forget about my skill and program the way an amateur would. This is the style Python is made to support.

I struggled so much to learn good programming. I need to make my peace with the bad, otherwise I won't get anywhere.

9:50am. Let me see if I can get that UI going.

```
import torch
import torch.distributions
import torch.nn
import torch.nn.functional

def small(intro,mid,out): return torch.nn.Sequential(
    torch.nn.Linear(intro,mid),
    torch.nn.LayerNorm(mid),
    torch.nn.Tanh(),
    torch.nn.Linear(mid,mid),
    torch.nn.LayerNorm(mid),
    torch.nn.Tanh(),
    torch.nn.Linear(mid,out)
    )
```

The way to do ML models is also something that is unresolved for me. I did the serialization in Spiral as it is the best tool for the job, but the Python/Spiral interop will always have friction. Pretty much every single one of Python's language features is a huge hack, and it is giving me heartache to even think what it would take to support all of it.

I hate how Cython's types being non composable requires hacks and cludges in the codegen. The sooner the next wave of hardware starts, the sooner I'll be able to get away from Python. But they all seem to want PyTorch interop and are chasing the present hype. So maybe my assumption that local memory would not require resource management in the usual sense is wrong.

I thought there would be inter-core communication that I'd deal directly, but maybe local allocations will still require managing on the host side. In that case, maybe Python will be here to stay until I figure out how to put those chips in my head and break the dependency on the scientific and programming community.

9:55am. That resource management might be necessary even with the next generations of chips seems like a realistic assumption to me now. I'll pivot to it.

This just makes mastering the amateur style more important.

My problem is not that I do not know it. My problem is that I need to accept it.

This is what I need to do. Once I do this, I'll be able to put in regular effort and achieve proper synergy between Spiral and Python. When I have this, I'll deal with UIs, deal with the agents and will be able to become what I set out to be six years ago.

A single win is all that I need.

10am. Now focus me. Let me go back to the Kivy crash course. I'll play with animations. I want to familiarize myself with them and drawing shapes on a canvas.

I need to break the ice with this. I want to draw a stack of chips and be able to transfer them between stacks in an animated fashion.

The challenge here is no to much how to do this, but to find the ideal workflow for implementing all of my GUI ideas. I'll exclude the time I am spending being anxious and not doing work from my evaluation.

```
with self.canvas:
    Color(1., 1., 0)
    Rectangle(size=(50, 50))
```

I really wonder how this works. Hmmm...actually I have an idea. There is probably a global stack which when not empty, the Color and Rectangle push themselves to in their constructors.

https://kivy.org/doc/stable/api-kivy.graphics.instructions.html

What kind of shapes are there. For chips I'll need elipses. For proper chips though, they'd need to be 3d and cell shaded. I'll just go with 2d for now.

I want them to be oval, and I want the number 1 to be in their center correponding to their value.

10:30am. https://kivy.org/doc/stable/api-kivy.graphics.html?highlight=rectangle#kivy.graphics.Line.rectangle

There is a lot of stuff here. Still, I can't figure out where all these instructions are supposed to be.

10:40am.

```
from kivy.uix.gridlayout import GridLayout
from kivy.uix.button import Button
from kivy.uix.label import Label
from kivy.uix.widget import Widget
from kivy.uix.scrollview import ScrollView
from kivy.core.window import Window
from kivy.app import runTouchApp
from kivy.lang import Builder

root = Builder.load_string('''
<MyWidget>:
    canvas:
        Color:
            rgba: 1,0,0,1
        Rectangle:
            pos: 0,0
            size: 100,100
''')

class MyWidget(Widget):
    pass

runTouchApp(root)
```

So I am doing this and nothing is appearing. This is why I've been so wary of doing this in Spiral. I know well enough myself that all I've done is watched a few tutorials. I do not have real familiary with Kivy.

As annoying as this situation is, building familiarity through experimentation until it goes into my procedural memory is exactly the way to go here. This would be painful, rather than annoying if I also had to deal with Spiral while doing this.

```
Builder.load_string('''
<Root>:
    MyWidget:
        pos: 0, 0

<MyWidget>:
    canvas:
        Color:
            rgba: 1,0,0,1
        Rectangle:
            pos: self.pos
            size: 100,100
''')
```

Hmmm, I had not realized that 0,0 is bottom left unstead ot top left until now.

https://kivy.org/doc/stable/api-kivy.uix.widget.html#kivy.uix.widget.Widget.pos_hint

```
<Root>:
    FloatLayout:
        MyWidget:
            pos_hint: {'top': 0.8}
```

This is not working. How do I make this work?

https://kivy.org/doc/stable/api-kivy.uix.floatlayout.html

11:25am. Had to take a break. Let me resume. Right now I am playing with positional hints.

```
<Root>:
    FloatLayout:
        size: self.parent.size
        canvas.before:
            Color:
                rgba: 0,1,0,1
            Rectangle:
                pos: self.pos
                size: self.size
        MyWidget:
            pos_hint: {'center': (0.5, 0.5)}
            size_hint: 0.2,0.2
```

It is possible to set the center like this.

```
pos_hint: {'pos': (0.5, 0.5)}
```

This is also possible. But in this case, why does top not work here?

```
pos_hint: {'top': 0.99, 'right': 0.99}
```

Ah, it does work. I just misunderstood what `top` and `right` are.

Ok.

11:35am. Ok, now focus me. I've played with this enough.

```
root = Builder.load_string('''
FloatLayout:
    canvas:
        Color:
            rgba: 0,0.8,0,1
        Rectangle:
            pos: self.pos
            size: self.size
    MyWidget:
        pos_hint: {'top': 0.99, 'right': 0.99}
        size_hint: 0.2,0.2

<MyWidget>:
    canvas:
        Color:
            rgba: 1,0,0,0.5
        Rectangle:
            pos: self.pos
            size: self.size
''')
```
```
 Traceback (most recent call last):
   File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_leduc1/asd.py", line 11, in <module>
     root = Builder.load_string('''
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\lang\builder.py", line 408, in load_string
     self._apply_rule(
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\lang\builder.py", line 621, in _apply_rule
     cls = Factory_get(cname)
   File "C:\Users\Marko\anaconda3\lib\site-packages\kivy\factory.py", line 146, in __getattr__
     raise FactoryException('Unknown class <%s>' % name)
 kivy.factory.FactoryException: Unknown class <MyWidget>
```

Why does this not work for me. Let me check out the crash course.

As an aside, I really like how Python itself has working exceptions rather than the crap I get from Cython. This is a part of the heartache I was talking about. Cython's errors are nasty, and it always forces me to scroll up a few pages to see what it is.

I actually do not know how to deal with this later thing.

```
Builder.load_string('''
<MyWidget>:
    canvas:
        Color:
            rgba: 1,0,0,0.5
        Rectangle:
            pos: self.pos
            size: self.size
''')

root = Builder.load_string('''
FloatLayout:
    canvas:
        Color:
            rgba: 0,0.8,0,1
        Rectangle:
            pos: self.pos
            size: self.size
    MyWidget:
        pos_hint: {'top': 0.99, 'right': 0.99}
        size_hint: 0.2,0.2
''')
```

I am surprised that even separating it out like this does not work.

https://www.youtube.com/watch?v=ZmteLworB4E&list=PLdNh1e1kmiPP4YApJm8ENK2yMlwF1_edq&index=5

In one of the videos he shows how to mix widgets and their definitions. Was it this one?

https://youtu.be/1d709erhpdQ?list=PLdNh1e1kmiPP4YApJm8ENK2yMlwF1_edq&t=204

Ok, so here is the use of an Elipse. I'll also need to display text.

12pm. Agh, I can't find that video. Let me stop here for a bit."