"11:05am. I keep going to bed later and later and as a result I am also getting up later. Today I went near 2am.
But I did get sleep even though I am groggy.

Let me finish reading the article and then I will start work on the codegen.

https://fantasticanachronism.com/2021/03/23/two-paths-to-the-future/

This is pretty interesting. It has been a while since I had futurology related article.

> Our neolithic forefathers could not have divined the metallurgical destiny of their descendants, but today, perhaps for the first time in universal history, we can catch a glimpse of the next paradigm before it arrives. If you point your telescope in exactly the right direction and squint really hard, you can just make out the letters: "YOU'RE FUCKED".

I like this last sentence.

11:40am. Let me finally start.

```fs
type UnionRec = {free_vars : Map<string, TyV[]>; tag : int}
```

Let me add a is_degenerate field here.

```fs
        | TyUnionUnbox(is,x,on_succs,on_fail) ->
            let case_tags = x.Item.tags
            let prefix =
                let x = x.Item
                match x.layout with
                | UHeap -> sprintf "UH%i" (uheap x.cases).tag
                | UStack -> sprintf "US%i" (ustack x.cases).tag
            let mutable is_first = true
            Map.iter (fun k (a,b) ->
                let union_i = case_tags.[k]
                let branch =
                    let cond = is |> List.map (fun (L(v_i,_)) -> sprintf "v%i.tag == %i" v_i union_i) |> String.concat " and "
                    if is_first then
                        line s (sprintf "if %s: # %s" cond k)
                        is_first <- false
                    else line s (sprintf "elif %s: # %s" cond k)
                let s = indent s
                let mutable nvs = Set(nulls.[b])
                let vs = ResizeArray()
                List.iter2 (fun (L(data_i,_)) a ->
                    data_free_vars a |> Array.iteri (fun field_i (L(v_i,t)) ->
                        if Set.contains v_i nvs then
                            nvs <- Set.remove v_i nvs
                        else
                            line defs $"cdef {tyv t} v{v_i}"
                            vs.Add $"v{v_i} = (<{prefix}_{union_i}>v{data_i}).v{field_i}"
                        )
                    ) is a
                if 0 < vs.Count then line s (String.concat "; " vs)
                print_nullables' nvs s
                binds_loop nulls defs s ret b
                ) on_succs
            on_fail |> Option.iter (fun b ->
                line s "else:"
                binds nulls defs (indent s) ret b
                )
```

I have to admit, doing this optimization is a particular pain in the ass.

11:50am. Oh, yeah, it is barely worth mentioning, but the Groq recruiter is insisting on a video interview. Forget it. I will do it on my own terms or not at all. That is the way to go here.

11:55am.

```fs
        | TyUnionUnbox(is,x,on_succs,on_fail) ->
            let case_tags = x.Item.tags
            let prefix, dot_tag =
                let x = x.Item
                match x.layout with
                | UHeap ->
                    let q = uheap x.cases
                    sprintf "UH%i" q.tag, if q.is_degenerate then "" else ".tag"
                | UStack ->
                    let q = ustack x.cases
                    sprintf "US%i" q.tag, if q.is_degenerate then "" else ".tag"
            let mutable is_first = true
            Map.iter (fun k (a,b) ->
                let union_i = case_tags.[k]
                let branch =
                    let cond = is |> List.map (fun (L(v_i,_)) -> sprintf "v%i%s == %i" v_i dot_tag union_i) |> String.concat " and "
                    if is_first then
                        line s (sprintf "if %s: # %s" cond k)
                        is_first <- false
                    else line s (sprintf "elif %s: # %s" cond k)
                let s = indent s
                let mutable nvs = Set(nulls.[b])
                let vs = ResizeArray()
                List.iter2 (fun (L(data_i,_)) a ->
                    data_free_vars a |> Array.iteri (fun field_i (L(v_i,t)) ->
                        if Set.contains v_i nvs then
                            nvs <- Set.remove v_i nvs
                        else
                            line defs $"cdef {tyv t} v{v_i}"
                            vs.Add $"v{v_i} = (<{prefix}_{union_i}>v{data_i}).v{field_i}"
                        )
                    ) is a
                if 0 < vs.Count then line s (String.concat "; " vs)
                print_nullables' nvs s
                binds_loop nulls defs s ret b
                ) on_succs
            on_fail |> Option.iter (fun b ->
                line s "else:"
                binds nulls defs (indent s) ret b
                )
```

I thought of doing a separate branch for the degenerate case, but then thought better of it. A lot of involved reasoning went into making what I have here, and trying to make rash changes would definitely result in bugs. Thankfully all I needed was to remove the tag accessor.

```fs
        | TyUnionBox(a,b,c) ->
            let c = c.Item
            let i = c.tags.[a]
            let vars = args' b
            match c.layout with
            | UHeap ->
                let q = uheap c.cases
                if q.is_degenerate then sprintf "%i" i
                else sprintf "UH%i_%i(%s)" q.tag i vars
            | UStack ->
                let q = ustack c.cases
                if q.is_degenerate then sprintf "%i" i
                else sprintf "US%i_%i(%s)" q.tag i vars
            |> return'
```

This should take care of this.

```fs
    and union_template (prefix : string) s (x : UnionRec) =
        if x.is_degenerate then
            line s $"ctypedef signed long {prefix}{x.tag}"
        else
            line s $"cdef class {prefix}{x.tag}:"
            line (indent s) $"cdef readonly signed long tag"
            let mutable i = 0
            x.free_vars |> Map.iter (fun k a ->
                line s $"cdef class {prefix}{x.tag}_{i}({prefix}{x.tag}): # {k}"
                let s = indent s
                let tys = tyv_type_show a |> layout_arrays_to_objects
                tys |> Array.iteri (cdef_show "readonly " s)
                let args = tys |> Array.mapi arg_show |> String.concat ", " |> with_self
                let body = $"self.tag = {i}" :: List.init tys.Length (fun i -> $"self.v{i} = v{i}") |> String.concat "; "
                line s $"def __init__({args}): {body}"
                i <- i+1
                )
```

Yes, this is it. In the end, the changes turned out to be quite easy.

Oh, yeah, what about the int switch?

No, I do not need to modify that. What about the `UnionTag`?

```fs
| UnionTag, [x] -> sprintf "%s.tag" (tup x)
```

I need to check for the deneracy here.

```fs
            | UnionTag, [DUnion(_,l) | DV(L(_,YUnion l)) as x] ->
                let dot_tag =
                    let c = l.Item
                    match c.layout with UHeap -> uheap c.cases | UStack -> ustack c.cases
                    |> fun x -> if x.is_degenerate then "" else ".tag"
                sprintf "%s%s" (tup x) dot_tag
```

This should do it.

Now I could try compiling the example. This change turned out to be easier than I thought.

```
ctypedef signed long US0
cdef class Heap0:
    cdef readonly object v0
    cdef readonly object v1
    cdef readonly object v2
    cdef readonly object v3
    def __init__(self, v0, v1, v2, v3): self.v0 = v0; self.v1 = v1; self.v2 = v2; self.v3 = v3
ctypedef signed long US1
cdef class US2:
    cdef readonly signed long tag
cdef class US2_0(US2): # action_
    cdef readonly US0 v0
    def __init__(self, US0 v0): self.tag = 0; self.v0 = v0
cdef class US2_1(US2): # observation_
    cdef readonly US1 v0
    def __init__(self, US1 v0): self.tag = 1; self.v0 = v0
cdef class UH0:
    cdef readonly signed long tag
cdef class UH0_0(UH0): # cons_
    cdef readonly US2 v0
    cdef readonly UH0 v1
    def __init__(self, US2 v0, UH0 v1): self.tag = 0; self.v0 = v0; self.v1 = v1
cdef class UH0_1(UH0): # nil
    def __init__(self): self.tag = 1
```

This is how the types get printed now.

Oh, right. I also need to take care of numpy arrays. Do not want the degenerate unions to be objects.

```fs
    let rec numpy_ty x =
        match env.ty_to_data x |> data_free_vars with
        | [|L(_,x)|] ->
            match x with
            | YPrim x ->
                match x with
                | Int8T -> "numpy.int8"
                | Int16T -> "numpy.int16"
                | Int32T -> "numpy.int32"
                | Int64T -> "numpy.int64"
                | UInt8T -> "numpy.uint8"
                | UInt16T -> "numpy.uint16"
                | UInt32T -> "numpy.uint32"
                | UInt64T -> "numpy.uint64"
                | Float32T -> "numpy.float32"
                | Float64T -> "numpy.float64"
                | BoolT -> "numpy.int8"
                | _ -> "object"
            | YUnion l ->
                let c = l.Item
                match c.layout with UHeap -> uheap c.cases | UStack -> ustack c.cases
                |> fun x -> if x.is_degenerate then "numpy.int32" else "object"
        | _ -> "object"
    and tyv = function
```

The Cython codegen is a rat's nest of hacks at this point.

Let me try running this again.

```
        del v16; del v17; del v18; del v19; del v20; del v21
                                                        ^
------------------------------------------------------------

c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\performance_test.pyx:1171:57: Deletion of non-Python, non-C++ object
```

Agh, fuck.

Let me fix this.

```fs
let is_stack = function
    | YPrim (UInt8T | UInt16T | UInt32T | UInt64T
        | Int8T | Int16T | Int32T | Int64T
        | Float32T | Float64T | BoolT) -> true
    | _ -> false
```

Ah, crap. I am going to have to move the `is_degenrate` calculation into the partial evaluator.

```fs
type UnionRec = {free_vars : Map<string, TyV[]>; tag : int; is_degenerate : bool}
```

Let me wreck everything.

```fs
    and union_template (prefix : string) s (x : UnionRec) =
        if x.is_degenerate then
            line s $"ctypedef signed long {prefix}{x.tag}"
        else
```

Ugh, now I don't have it here.

```fs
        let f (a : Map<string,Ty>) : UnionRec =
            let free_vars = a |> Map.map (fun _ -> env.ty_to_data >> data_free_vars)
            {free_vars=free_vars; tag=dict.Count; is_degenerate=Map.forall (fun _ -> Array.isEmpty) free_vars}
```

Now I am stripping it only to recalculate it here again, but that is the easiest way to do this.

```fs
        | TUnion(_,(a,b)) ->
            let tags = Dictionary()
            let tag_cases = Array.zeroCreate (Map.count a)
            let mutable is_degenerate = true
            let cases =
                Map.map (fun k v ->
                    let v = ty s v
                    is_degenerate <- is_degenerate && (ty_to_data s v |> data_free_vars |> Array.isEmpty)
                    let i = tags.Count
                    tags.[k] <- i
                    tag_cases.[i] <- (k,v)
                    v
                    ) a
            YUnion(H {|cases=cases; layout=b; tags=tags; tag_cases=tag_cases; is_degenerate=is_degenerate|})
```

This is nasty, but I have to do it.

```fs
        let f (a : Map<string,Ty>, is_degenerate) : UnionRec =
            let free_vars = a |> Map.map (fun _ -> env.ty_to_data >> data_free_vars)
            {free_vars=free_vars; tag=dict.Count; is_degenerate=is_degenerate}
```

I've modified all the cases so I at least do not have to reduplicate the work already done here.

```fs
    let union show =
        let dict = Dictionary(HashIdentity.Reference)
        let f (a : Map<string,Ty>, is_degenerate) : UnionRec =
            let free_vars = a |> Map.map (fun _ -> env.ty_to_data >> data_free_vars)
            {free_vars=free_vars; tag=dict.Count; is_degenerate=is_degenerate}
        fun x ->
            let mutable dirty = false
            let r = Utils.memoize dict (fun x -> dirty <- true; f x) x
            if dirty then print true show r
            r
```

But this is exactly the wrong thing to do given that I am using a ref dict here.

```
Error trace on line: 1, column: 10 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\performance_test.spi.
inl main () =
         ^
Error trace on line: 2, column: 5 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\performance_test.spi.
    inl p1 = agent.uniform.funsEnum()
    ^
Error trace on line: 3, column: 5 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\performance_test.spi.
    inl p2 = agent.uniform.funsEnum()
    ^
Error trace on line: 4, column: 5 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\performance_test.spi.
    loop.for' (from:0u32 nearTo:100) (fun i =>
    ^
Error trace on line: 6, column: 33 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
inl for' (from: nearTo:) body = for (from:nearTo:) (fun i () => body i) ()
                                ^
Error trace on line: 4, column: 5 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
    loop from state
    ^
Error trace on line: 3, column: 20 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
    let rec loop i s = if i < nearTo then loop (i+1) (body i s) else s
                   ^
Error trace on line: 3, column: 24 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
    let rec loop i s = if i < nearTo then loop (i+1) (body i s) else s
                       ^
Error trace on line: 3, column: 43 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
    let rec loop i s = if i < nearTo then loop (i+1) (body i s) else s
                                          ^
Error trace on line: 3, column: 55 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
    let rec loop i s = if i < nearTo then loop (i+1) (body i s) else s
                                                      ^
Error trace on line: 6, column: 59 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
inl for' (from: nearTo:) body = for (from:nearTo:) (fun i () => body i) ()
                                                          ^
Error trace on line: 6, column: 65 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\loop.spi.
inl for' (from: nearTo:) body = for (from:nearTo:) (fun i () => body i) ()
                                                                ^
Error trace on line: 6, column: 9 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\performance_test.spi.
        leduc.game (nodes.nodes_2p (p1, p2)) (log_probm.from 1,init,init) |> ignore
        ^
Error trace on line: 6, column: 64 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\performance_test.spi.
        leduc.game (nodes.nodes_2p (p1, p2)) (log_probm.from 1,init,init) |> ignore
                                                               ^
Error trace on line: 4, column: 70 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\nodes\utils.spi.
inl init forall observation action. : player () observation action = init' ()
                                                                     ^
Error trace on line: 3, column: 19 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\nodes\utils.spi.
inl init' state = player {state prob=log_probm.from 1; observations=Nil} |> dyn
                  ^
Error trace on line: 3, column: 26 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\nodes\utils.spi.
inl init' state = player {state prob=log_probm.from 1; observations=Nil} |> dyn
                         ^
Error trace on line: 3, column: 69 in module: c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc6\nodes\utils.spi.
inl init' state = player {state prob=log_probm.from 1; observations=Nil} |> dyn
                                                                    ^
Error trace on line: 16, column: 20 in module: c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\core2\base.spi.
union rec list a = Nil | Cons: a * list a
                   ^
Type join points must not be unboxed during their definition.
```

Hmmm, is this?

```fs
is_degenerate <- is_degenerate && (ty_to_data s v |> data_free_vars |> Array.isEmpty)
```

Ah, right. This causes a recursive unboxing. Not good.

```fs
                    let v = ty s v
                    is_degenerate <- is_degenerate && match v with YB -> true | _ -> false
```

Let me just do it like this.

```fs
let is_stack = function
    | YPrim (UInt8T | UInt16T | UInt32T | UInt64T
        | Int8T | Int16T | Int32T | Int64T
        | Float32T | Float64T | BoolT) -> true
    | YUnion x -> x.Item.is_degenerate
    | _ -> false
```

Now I can add this here.

1:10pm. Let me finally try running it.

```
  File "performance_test.pyx", line 1176, in performance_test.main
    method0(v0)
  File "performance_test.pyx", line 1138, in performance_test.method0
    v5 = numpy.empty(2,dtype=numpy.int32)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'long'
```

Why?

```
cdef numpy.ndarray[object,ndim=1] v5
```

Ahhh. Did I not take care of this. Let me do it.

```fs
            let a =
                match env.ty_to_data a |> data_free_vars with
                | [|L(_,YPrim x)|] -> prim x
                | _ -> "object"
```

Let me modify things here as well.

```fs
            let a =
                match env.ty_to_data a |> data_free_vars with
                | [|L(_,x)|] ->
                    match x with
                    | YPrim x -> prim x
                    | YUnion x -> if x.Item.is_degenerate then "signed long" else "object"
                    | _ -> "object"
                | _ -> "object"
            $"numpy.ndarray[{a},ndim=1]"
```

I need to take a break here. I'll try it out when I get back."