"8:50am. Let me chill a bit.
https://www.reddit.com/r/MachineLearning/comments/o6j8qf/r_aliasfree_gan/

This seems interesting.

https://nvlabs.github.io/alias-free-gan/

The image quality is really impressive.

9:05am. Right now I am reading the paper. I had time to think about what I want to try tackling the Holdem training next.

What I am going to do is implement fast averaging on top of the slow one I am already doing and have the network train against the fast average. For all I know this might work even for GANs. If not, I always have the duality gap method to fall back on.

9:35am. Ok, focus me. Let me read that GAN paper, a few chapter of Hagure Idol and then I will implement my idea and let it run for a while.

10:05am. Done with the above. I do not get a thing of that paper. But it is quite impressive.

For the time being let me just do my own thing. GANs are something I will tackle when the hardware costs go down.

```py
    favg_iter = 100
    ...
    def make_avg(max_t):
        def avg_fn(avg_p, p, t): return avg_p + (p - avg_p) / min(max_t, t + 1)
        return AveragedModel(value,avg_fn=avg_fn), AveragedModel(policy,avg_fn=avg_fn), AveragedModel(head,avg_fn=avg_fn)

    valuea, policya, heada = make_avg(iter_chk)
    valuefa, policyfa, headfa = make_avg(favg_iter)
```

Let me do this.

10:20am.

```py
def create_nn_agent(iter_train,iter_avg,iter_chk,vs_self,vs_one,neural,uniform_player): # self play NN
    assert ((iter_train + iter_avg) % iter_chk == 0)
    batch_size = 2 ** 10
    favg_iter = 100
    head_decay = 1.0 - 2 ** -2

    value, policy, head = neural_create_model(neural.size)
    opt = SignSGD([
        {'params': value.parameters(), 'lr': 2 ** -6},
        {'params': policy.parameters()}
        ],{'lr': 2 ** -8})

    def make_avg(max_t):
        def avg_fn(avg_p, p, t): return avg_p + (p - avg_p) / min(max_t, t + 1)
        return AveragedModel(value,avg_fn=avg_fn), AveragedModel(policy,avg_fn=avg_fn), AveragedModel(head,avg_fn=avg_fn)

    valuea, policya, heada = make_avg(iter_chk) # The slow average
    valuefa, policyfa, headfa = make_avg(favg_iter) # The fast average

    def neural_player(value,policy,head,is_update_head=False,is_update_value=False,is_update_policy=False,epsilon=0.0):
        return neural.handler(partial(model_evaluate,value,policy,head,is_update_head,is_update_value,is_update_policy,epsilon))

    def run(is_avg=False):
        nonlocal head,heada
        opt.zero_grad(True)
        head.decay(head_decay)
        pl,plfa = neural_player(value,policy,head,True,True,True,2 ** -2), neural_player(valuefa,policyfa,headfa)
        vs_one(batch_size // 2,pl,plfa)
        vs_one(batch_size // 2,plfa,pl)
        # r = vs_one(batch_size,neural_player(True,True,True,2 ** -2),uniform_player)
        # logging.info(f"The reward vs the uniform is {r.mean()}")
        opt.step()
        valuefa.update_parameters(value); policyfa.update_parameters(policy); headfa.update_parameters(head)

        if is_avg: valuea.update_parameters(value); policya.update_parameters(policy); heada.update_parameters(head)

    logging.info("** TRAINING START **")
    t1 = time.perf_counter()

    for i in range(1,iter_train+iter_avg+1):
        is_avg = iter_train < i
        run(is_avg)
        if i % iter_chk == 0:
            with open(f"dump/nn_agent_{i}.nnreg",'wb') as f: torch.save((value,policy,head),f)
            if is_avg:
                with open(f"dump/nn_agent_{i}.nnavg",'wb') as f: torch.save((valuea.module,policya.module,heada.module),f)
            logging.info(f'Checkpoint {i}')

    logging.info("** TRAINING DONE **")
    t2 = time.perf_counter()
    logging.info(f"TIME ELAPSED: {t2-t1:0.4f}")

if __name__ == '__main__':
    import numpy as np
    import pyximport
    pyximport.install(language_level=3,setup_args={"include_dirs":np.get_include()})
    from create_args import main
    args = main()['train']

    log_path = 'dump/training.log'
    logging.basicConfig(
        filename=log_path,
        level=logging.DEBUG,
        datefmt='%m/%d/%Y %I:%M:%S %p',
        format='%(asctime)s %(message)s'
        )

    print("Running...")
    print(f"The details of training are in: {log_path}")
    create_nn_agent(2_000 // 4,30_000 // 4,2_000 // 4,**args)
    print("Done.")
```

The idea I had yesterday was to make a copy of the net at the present step and train the agent against that, but during the night it occurred to me that I could just have it train against its average. This should be an interesting experiment. Let me run it for a quarter of the iterations that I have yesterday.

```
AttributeError: 'AveragedModel' object has no attribute 'head'
```

Ah whops. I should extract the module.

10:25am.

```py
    valuea, policya, heada = make_avg(iter_chk) # The slow average
    valuefa, policyfa, headfa = make_avg(favg_iter) # The fast average
    valuefa.requires_grad_
```

Damn, I should really be turning off the requires_grad_ for this. I'll have to check out the state of that.

```py
import torch
import torch.nn
from torch.optim.swa_utils import AveragedModel

a = torch.nn.Linear(2,2,False)
b = AveragedModel(a)
b.requires_grad_(False)
a.weight.requires_grad
b.module.weight.requires_grad
```

There is no conflict. Turning off the grad on `b`, does not do it on `a`. And the avg model does have it on by default.

10:30am.

```py
valuefa.requires_grad_(False), policyfa.requires_grad_(False), headfa.requires_grad_(False)
```

No, it is not important forget this.

Ok, it already played 1k hands. Let me try it out.

...No, it just keeps raising like a moron again.

Let me try the 1.5k.

Oh it raise do 15 instead of half stack! This seems promising.

10:40am. It is still quite awful, but at least it is developing some sort of diversity in its actions. It still does not know how to fold though. Let me try the 2k player.

10:45am. 2k is trash. It has not moved at all from its policy. How about 2.5k?

Oh it raise to 5. That is different.

It still did not learn to fold.

10:50am. Let me try the 3.5k.

It has gone back to making huge raises. It seems the primary challenge today will be figuring out how to get it to fold.

Enough. I can't bear this anymore. I'll abort the training. If it cannot learn to fold I think the most likely culprit is the value function.

```
head_decay = 1.0 - 2 ** -2
```

Maybe this decay is way too high.

```py
head_decay = 1.0 - 2 ** -10
```

Let me try this. With Leduc finding the right value was no problem, but with what I have now, it might be forgetting too quickly.

I at least want to see it learning to fold trash hands.

Maybe I should go back to Leduc and see how it does when there is no decay.

Actually, let me try that out here. I'll turn off head decay just to see how it does.

I'd bet it would do just fine without decay. But too much decay could very well hurt it.

11am. This is not so bad. Training the agent and playing against it is something I should have been doing from the start.

This is the kind of work, I've dreamed about.

Let me try the 500 agent.

11:20am. I've aborted it again.

So far my theories have all turned out to be wrong. I thought it is an aggrodonk because of optimization vagaries, but now I am not sure.

Instead of doing what I have been doing so far, let me ditch playing against the average and increase the batch size by a factor of 2 ** 7. Combined with signSGD maybe the variance of the gradients is just too high.

11:25am.

```py
def create_nn_agent(iter_train,iter_avg,iter_chk,vs_self,vs_one,neural,uniform_player): # self play NN
    assert ((iter_train + iter_avg) % iter_chk == 0)
    batch_size = 2 ** 17
    favg_iter = 100
    head_decay = 1.0 - 2 ** -2

    value, policy, head = neural_create_model(neural.size)
    opt = SignSGD([
        {'params': value.parameters(), 'lr': 2 ** -6},
        {'params': policy.parameters()}
        ],{'lr': 2 ** -8})

    def make_avg(max_t):
        def avg_fn(avg_p, p, t): return avg_p + (p - avg_p) / min(max_t, t + 1)
        return AveragedModel(value,avg_fn=avg_fn), AveragedModel(policy,avg_fn=avg_fn), AveragedModel(head,avg_fn=avg_fn)

    valuea, policya, heada = make_avg(iter_chk) # The slow average
    # valuefa, policyfa, headfa = make_avg(favg_iter) # The fast average

    def neural_player(value,policy,head,is_update_head=False,is_update_value=False,is_update_policy=False,epsilon=0.0):
        return neural.handler(partial(model_evaluate,value,policy,head,is_update_head,is_update_value,is_update_policy,epsilon))

    def run(is_avg=False):
        nonlocal head,heada
        opt.zero_grad(True)
        head.decay(head_decay)
        pl = neural_player(value,policy,head,True,True,True,2 ** -2)
        vs_self(batch_size,pl)
        # plfa = neural_player(valuefa.module,policyfa.module,headfa.module)
        # vs_one(batch_size // 2,pl,plfa)
        # vs_one(batch_size // 2,plfa,pl)
        opt.step()
        # valuefa.update_parameters(value); policyfa.update_parameters(policy); headfa.update_parameters(head)

        if is_avg: valuea.update_parameters(value); policya.update_parameters(policy); heada.update_parameters(head)

    logging.info("** TRAINING START **")
    t1 = time.perf_counter()

    for i in range(1,iter_train+iter_avg+1):
        is_avg = iter_train < i
        run(is_avg)
        if i % iter_chk == 0:
            with open(f"dump/nn_agent_{i}.nnreg",'wb') as f: torch.save((value,policy,head),f)
            if is_avg:
                with open(f"dump/nn_agent_{i}.nnavg",'wb') as f: torch.save((valuea.module,policya.module,heada.module),f)
            logging.info(f'Checkpoint {i}')

    logging.info("** TRAINING DONE **")
    t2 = time.perf_counter()
    logging.info(f"TIME ELAPSED: {t2-t1:0.4f}")
```

Let me try doing this.

```
    sample_probs += action_mask_inv / (action_mask_inv.sum(-1,keepdim=True) * (1 / epsilon))
RuntimeError: CUDA out of memory. Tried to allocate 82.00 MiB (GPU 0; 4.00 GiB total capacity; 2.80 GiB already allocated; 6.73 MiB free; 2.82 GiB reserved in total by PyTorch)
```

No helping it. Let me lower the batch size.

```py
for _ in range(2 ** 3): vs_self(batch_size,pl)
```

I've lowered the batch size to 2 ** 14. Let me try doing it like this.

11:40am. No forget this. Such a large batch size for a single step is just way too high.

12:25pm. I am thinking. Let me stop here for the morning."