"8:40am. Another day is here. My sleep was restless as I kept obsessing about design issues.
Let me chill just a tad and then I will start.

9:10am. Let me start. I before I get to investigating that concurrency issue, I do want to wax it a bit more.

```
links: links.filter(({ line }) => i === line).map(({ char }) => ({ range: char, uri })),
```

As expected I really do not like this.

9:25am.

```
    })().map(({ links, range: { from, nearTo } }): ClusterText => { // maps the ranges and the links to their textual representation
     const lines: DecoratedLine[] = [];
     const loop = (f : (i : number) => void) => { for (let i = from; i < nearTo; i++) { f(i); } };
     // converts the range to an array of text lines
     loop(i => { lines.push({ links: [], text: doc.lineAt(i).text }); });
     // adds the links for each line
     links.forEach(x => { lines[x.line-from].links.push({range: x.char, uri}); });
     // adds the line prefix
     loop(i => {
      const x = lines[i];
      const formatLineIndex = (minSize: number, lineIndex: number) => {
       const str = lineIndex.toString();
       return ' '.repeat(Math.max(0, minSize - str.length)) + str;
      };
      const lineNumberAsString = formatLineIndex(6, i + 1);
      const preamble = x.links.length > 0 ? `${lineNumberAsString}: ` : `${lineNumberAsString}  `;

      const prefixLine = (x: DecoratedLine, preamble: string) => ({
       links: x.links.map(({ range: { from, length }, uri }) => ({ range: { from: from + preamble.length, length }, uri })),
       text: preamble + x.text
      });
      lines[i] = prefixLine(x, preamble);
     });
     return lines;
```

This is a more natural way of doing it. Honestly, I can't really stick to my principles when it comes to JS.

9:30am. The rest is fine, I can't think of a way to improve it. I could do a better job in F#, but here I'll have to be happy with what I've got.

Oh yes, I also need to add the '...' between the clusters.

```
.map(lines => { // Prefixes the Uri to the cluster
      const mapToDecorated = (...x: string[]): ClusterText => x.map(text => ({ text, links: [] }));
      return [...mapToDecorated(uri.toString()), ...lines];
     })
```

Let me back this up here.

10am.

```
import { Range, Position, Location, workspace, languages, window, commands, ExtensionContext, Disposable, TextDocumentContentProvider, DocumentLinkProvider, EventEmitter, Uri, TextDocument, CancellationToken, DocumentLink } from 'vscode';
import * as _ from 'lodash';
import * as rx from 'rxjs';
import { merge, mergeAll, map, startWith, scan, mergeMap } from 'rxjs/operators';

const itemTrailingLines = 2;
const itemMaxDistance = 5;
const itemLeadingLines = 2;

interface ReferenceDocumentChunk {
 text: string[];
 links: DocumentLink[];
}
type ReferenceDocument = rx.Observable<ReferenceDocumentChunk>;

const showReferences = (locs: readonly Location[]): ReferenceDocument => {
 interface RangeFromLength {
  from: number;
  length: number;
 }

 interface RangeFromNearTo {
  from: number;
  nearTo: number;
 }

 interface Link {
  range: RangeFromLength;
  uri: Uri;
 }

 interface DecoratedLine {
  text: string;
  links: Link[];
 }

 type ClusterText = DecoratedLine[];
 const clusterTextCreate = (...x: string[]): ClusterText => {
  return x.map(x => ({ text: x, links: [] }));
 };

 const a = _.chain(locs)
  // JS is nasty in how it has no concept of comparable interfaces. Or equality or hashing.
  // Using toString() to do comparison could be dangerous.
  .groupBy(loc => loc.uri.toString())
  .map(async (loc): Promise<ClusterText> => {
   const uri = loc[0].uri; // assuming that locs all have the same Uri
   let doc : TextDocument;
   try { doc = await workspace.openTextDocument(uri); }
   catch (err) { return clusterTextCreate(`Failed to load ${uri.toString()}\nMessage: ${String(err)}\n`); }
   interface RangeLine {
    line: number;
    char: RangeFromLength;
   }
   interface State {
    links: RangeLine[];
    range: RangeFromNearTo;
   }
   const lines_ = ((): State[] => { // further groups the locations in the URI group to their cluster ranges along with the links
    const clusters: State[] = [];
    const pushCluster = ({ range, links }: State) => {
     const from = Math.max(0, range.from - itemTrailingLines);
     const nearTo = Math.min(range.nearTo + itemLeadingLines, doc.lineCount);
     clusters.push({ links, range: { from, nearTo } });
    };
    // Having the first element be null is unecessary, but doing it like this is less
    // error prone than writing a loop even if it takes a bit extra effort for the computer.
    type T = State | null;
    const cluster =
     loc.sort((x, b) => x.range.start.compareTo(b.range.start)) // assuming that locs all have the same Uri
      .map(({ range: x }): RangeLine => {
       if (!x.isSingleLine) { throw "Links have to be single line ranges"; }
       return { line: x.start.line, char: { from: x.start.character, length: x.end.character - x.start.character } };
      }).reduce((state: T, x: RangeLine): T => {
       const from = x.line;
       const nearTo = from + 1;
       const freshState = (): State => ({ range: { from, nearTo }, links: [x] });
       if (!state) { return freshState(); }
       const { range, links } = state;
       if (nearTo - range.nearTo > itemMaxDistance) { pushCluster(state); return freshState(); }
       else { links.push(x); return { links, range: { from: range.from, nearTo } }; }
      }, null);
    if (cluster) { pushCluster(cluster); }
    return clusters;
   })().map(({ links, range: { from, nearTo } }): ClusterText => { // maps the ranges and the links to their textual representation
    const lines: DecoratedLine[] = [];
    const loop = (f : (i : number) => void) => { for (let i = from; i < nearTo; i++) { f(i); } };
    // converts the range to an array of text lines
    loop(i => { lines.push({ links: [], text: doc.lineAt(i).text }); });
    // adds the links for each line
    links.forEach(x => { lines[x.line-from].links.push({range: x.char, uri}); });
    // adds the line prefix
    loop(i => {
     const x = lines[i];
     const formatLineIndex = (minSize: number, lineIndex: number) => {
      const str = lineIndex.toString();
      return ' '.repeat(Math.max(0, minSize - str.length)) + str;
     };
     const lineNumberAsString = formatLineIndex(6, i + 1);
     const preamble = x.links.length > 0 ? `${lineNumberAsString}: ` : `${lineNumberAsString}  `;

     const prefixLine = (x: DecoratedLine, preamble: string) => ({
      links: x.links.map(({ range: { from, length }, uri }) => ({ range: { from: from + preamble.length, length }, uri })),
      text: preamble + x.text
     });
     lines[i] = prefixLine(x, preamble);
    });
    return lines;
   });

   return ((): ClusterText => {
    const lines: ClusterText = [];
    // Prefixes the Uri to the cluster
    lines.push(...clusterTextCreate(uri.toString()));
    // intersperses the '...' between the clusters and flattens them.
    type T = ClusterText | null;
    const a = lines_.reduce((a:T,b):T => {
     if (!a) {return b;}
     lines.push(...a,...clusterTextCreate('...'));
     return b;
    },null);
    if (a) {lines.push(...a);}
    return lines;
   })();
 }).value();

 const b: rx.Observable<ClusterText> = rx.of(...a).pipe( // Merges all the observable streams.
  mergeAll(),
  startWith(clusterTextCreate(`Found ${locs.length} references.`)), // Prepends the initial line.
  mergeMap(x => [x, clusterTextCreate('')]) // Puts an empty line between the chunks
 );

 return rx.zip( // Keeps track of the number of processed lines
  b.pipe(scan((a, b) => { return a + b.length; }, 0), startWith(0)),
  b
 ).pipe(
  map(([line, x]): ReferenceDocumentChunk => { // Finally, converts the chunks to document links.
   const text = x.map(x => x.text);
   const links = _.flatten(x.map((x, i_) => {
    const i = line + i_;
    return x.links.map(({ range, uri }) =>
     new DocumentLink(
      new Range(i, range.from, i, range.from + range.length),
      uri.with({ fragment: String(i + 1) })
     )
    );
   }));
   return { text, links };
  })
 );
};
```

I am further improving things. I've factored out that try catch so it only works on the await. The rest can fall through.

```
  .groupBy(loc => loc.uri.toString())
  .map(async (loc): Promise<ClusterText> => {
   const uri = loc[0].uri; // assuming that locs all have the same Uri
```

Now the thing that bothers me are these location uris. Though I've grouped them by calling toString there is no way this can be right. I've been wondering all this time how links could possibly be valid, but the truth is the positional information has to be in the Uri itself if it is nowhere else.

```
const uri = loc[0].uri; // assuming that locs all have the same Uri
```

So this assumption cannot possibly be right.

10:10am. Ok, if I continue to work any more on this problem, I'll be able to get a Phd on it at this rate.

Let me figure out the concurrency bug instead and wrap this all up.

...Besides this, one thing I want to look into is those decode and encode functions for the Uri. I'll study that for a bit as well.

Hmmm...I am not sure where to begin researching how to run the thing on the proper thread. Let me open an issue like I'd planned.

10:25am. https://github.com/microsoft/vscode-extension-samples/issues/

Opened issue 287.

I am not sure what I'll do now. Let me check out the VS Code API bindings. They actually aren't that large - even though they are 10k most of them are comments. Maybe I'll manage to pick out something to help me schedule the thread properly.

10:35am. https://tsh.io/blog/simple-guide-concurrency-node-js/

Also let me read this for a bit.

10:50am. 5k in. So far, the bindings were mostly regular editor stuff. Let me go through the other half as well.

11:10am. There is a lot of useful stuff in the API, but nothing with regard to the editor. I have no idea. I guess I'll study Node concurrency.

11:25am. Am taking a breather. Let me read that article as I said I would.

```
Node took a slightly different approach to handling multiple concurrent requests at the same time if you compare it to some other popular servers like Apache. Spawning a new thread for each request is expensive. Also, threads are doing nothing when awaiting other operations’ result (i.e.: database read). That’s why Node is using one thread instead. Such an approach has numerous advantages. No overhead comes with creating new threads. Also, your code is much easier to reason about, as you don’t have to worry about what will happen if two threads access the same variable. It’s because that simply cannot happen. There are some drawbacks as well. Node isn’t the best choice for applications that mostly deal with CPU intensive computing. On the other hand, it excels at handling multiple I/O requests. So, let’s focus on this part for a bit.
```

If this is how Node operates, I really do not see how what I wrote in that post can be right.

11:50am. Now I am Reddit posting on the ML sub. Let me just read that article and then I will take a break.

12:05pm. I have no idea. I wish I could say I understood what was written in the previous article, but it is quite vague to me. I mean obviously something is going on out of turn, but if Node is single threaded I can't imagine why this error would occur. Even if it were multi threaded the event fire should occur after the array has been modified.

12:20pm.

```
   for (const group of groups) {
    const ranges = group.map(loc => loc.range);
    await this._fetchAndFormatLocations(group[0].uri, ranges);
    // const snooze = (ms : number) => new Promise(resolve => setTimeout(resolve, ms));
    // await snooze(1000);
    window.showInformationMessage("Firing.");
    this._emitter.fire(uri);
   }
  })();
 }

 get value() {
  const r = this._lines.join('\n');
  return r;
  }
```

I am using breakpoints to inspect this and even though the emitter gets called, the value does not fire.

This is strange.

12:25pm.

```
 fire(event: T): void {
  if (this._listeners) {
   // put all [listener,event]-pairs into delivery queue
   // then emit all event. an inner/nested event might be
   // the driver of this

   if (!this._deliveryQueue) {
    this._deliveryQueue = new LinkedList();
   }

   for (let listener of this._listeners) {
    this._deliveryQueue.push([listener, event]);
   }

   while (this._deliveryQueue.size > 0) {
    const [listener, event] = this._deliveryQueue.shift()!;
    try {
     if (typeof listener === 'function') {
      listener.call(undefined, event);
     } else {
      listener[0].call(listener[1], event);
     }
    } catch (e) {
     onUnexpectedError(e);
    }
   }
  }
 }
```

I've stepped into the event listener and it seems an exception is being thrown.

12:30pm.

```
 // scheme, must be set
 if (!ret.scheme && _strict) {
  throw new Error(`[UriError]: Scheme is missing: {scheme: "", authority: "${ret.authority}", path: "${ret.path}", query: "${ret.query}", fragment: "${ret.fragment}"}`);
 }
```

I finally noticed the exception mechanism. This is being raised.

12:35pm.

```
Exception has occurred: Error
Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "", query: "", fragment: "Disposable"}
```

I have no idea.

12:50pm. Did a little update in the issue. Let me try something. Maybe the problem got fixed in the newer versions of VS Code. Now that I've investigated this a bit, this seems more like an editor bug than a concurrency bug.

```
 "engines": {
  "vscode": "^1.39.0"
 },
```

Let me change the engine to latest.

Nope. The `ContentProvider` simply does not work properly period.

Let me get breakfast. I'll refactor the example so it works normally later. It will have to be all at once, but not much I can do about this. Thankfully I do not really need this to be fully async.

For Spiral, maybe I'll find a use in the content provider for the sake of printing out stack traces with links attached.

Now that I've gone over the API, it does not seem like there is an easy way to do waypoints. But that is fine. I can use this, or maybe I can use the call hierarchy window. I'll be able to figure out something. Some kind of pane with list of items that can be navigated with keypresses should be within the realm of reason.

1pm. Goddamit. I am going to master this even if it kills me. As a language designer I really can't go without an editor for the language, but I am just so bad at this. It has been 3 months and I am making plodding progress. That I am this slow probably means I am making strategic errors, but I can't do it any better.

I'll just stick to the plan."