"1:25pm. Let me resume the Blazor course.
https://youtu.be/QKr1HPq6YlI?t=9219

Hmmm, I see.

1:50pm. https://youtu.be/QKr1HPq6YlI?t=9800

Quite magical. I do not mind this as much now.

1:55pm. https://youtu.be/QKr1HPq6YlI?t=9970

I see. I thought the cascading params would be name sensitive, but it turns out it matches based on the type.

2pm. https://youtu.be/QKr1HPq6YlI?t=10115

I am bored again. Let me watch to the end of this chapter, which is another 15m and I will take a break.

2:10pm. https://youtu.be/QKr1HPq6YlI?t=10359

It is not so bad.

2:25pm. https://youtu.be/QKr1HPq6YlI?t=10957

I am at the 3h mark. At this point I am over 50% into the course.

https://www.youtube.com/watch?v=DuNLR_NJv8U
Learn .NET MAUI - Full Course for Beginners

This caught my eye on the sidebar. I didn't know there was such a thing. I guess MS is giving its all at competing with frameworks like React.

https://www.youtube.com/watch?v=CqCDOosvZIk
.NET Microservices – Full Course for Beginners

They caught my eye.

2:45pm. Let me resume. I am of course not going to do the above courses, even Blazor is too much, but just in case. Who knows how these ML jobs are going to turn out. If that fails I'll have to get some full stack dev job.

Anyway, let me see if I can get to the 4h mark today. Study hard!

2:55pm. https://youtu.be/QKr1HPq6YlI?t=11305

What is rel? Let me see if I can find that out.

https://www.w3schools.com/tags/att_a_rel.asp

Easy enough.

3:05pm. Had to pour some water over myself. Let me resume. 4h, just 4h. I have to reach that mark today.

3:10pm. https://youtu.be/QKr1HPq6YlI?t=11902

Huh, this really works. Should the name of the class be the same as the one being extended. Or is the `this` keyword in the first argument responsible for that. That might be it.

https://youtu.be/QKr1HPq6YlI?t=11912

In some ways, this is filler. Once I figured out callbacks and parameters, I got 95% of what I need from a reactive library. I suppose this is important, but they are still extras.

3:40pm. Had to take a break. I am ready to resume. Let me just take a look at the MAUI course for 10m. After that I'll focus on getting that JS library operational. JS interop is important.

https://youtu.be/KmLQLSKqvvI
.NET MAUI Explained: What is it, How does it work, and What about Blazor?

3:55pm. https://youtu.be/KmLQLSKqvvI?t=432

Let me leave this for later. Now focus me.

Watching that Blazor course made me sick of it, so now that the homework is due I just want to run away. Even though the homework is the fun part.

I need to overcome my inertia. Let me just focus on doing some coding. When I said that my goal is to hit the 4h mark an hour ago, you'd think it be easy given that I had 4h, but not so much. An hour has passed and I only have 2h left.

https://youtu.be/QKr1HPq6YlI?t=12053

Focus me. Let me put these buttons where they should be. First let me implement the toastr thing. Then I'll do the other library.

4:05pm. https://github.com/CodeSeven/toastr

Focus me. Can I figure out how to import this without just copying what the lecturer is doing?

I vaguely get that I need to add these scripts. Then after that how do I access the library? Ah, the thing is on Nuget as well.

Ok, first of all, what is a value task?

https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/

4:15pm. I can't be bothered to read all of that. Basically I can just treat it as task. It is not a stack allocated version of Task, but a wrapper around a Task.

It seems Tasks do some memoization under the hood for whatever reason.

```cs
    public async Task testRun()
    {
        await JSrun.InvokeVoidAsync("toastr.info('Are you the 6 fingered man?')");
    }
```

Will something like this work?

4:25pm. No it does not.

```cs
public async Task testRun() => await JSrun.InvokeVoidAsync("toastr.info","'Are you the 6 fingered man?'");
```

But at least this is activating my neurons and I am not dead bored anymore.

Why is toastr...wait, it is because I didn't import the library. Silly me.

> Refused to apply style from 'https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js' because its MIME type ('application/javascript') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

I am getting this error in the console.

```
Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'extend')
```

I get a different kind of error when I try to run it.

Hmmm, instead of that, let me try triggering `console.log`.

Oh it works. Now I can be sure of what that thing is going. It is in fact running the function somewhere. Though I have the Google Chrome dev environment, trying to walk through the code is too much for me right now. I see that I have a while ago before I can become a pro webdev. I'll only consider it if I can't get an ML related job.

Ok, now I have no idea. I am going to have to rewatch the video in order to figure out why it is not importing.

https://youtu.be/QKr1HPq6YlI?t=11625

Why is he having to write a wrapper for a js library?

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0

Let me think about this.

https://www.w3schools.com/js/js_window.asp
> The window object is supported by all browsers. It represents the browser's window. All global JavaScript objects, functions, and variables automatically become members of the window object. Global variables are properties of the window object. Global functions are methods of the window object.

Ok, then why do I need to assign it manually inside the code?

Let me think...

4:45pm.

```js
window.qwe = (x) => {
    toastr.warning('My name is Inigo Montoya. You killed my father, prepare to die!')
}
```

I put it inside a js file and then accessed it like this, but it is not working properly. It says it is trying to access undefined.

https://youtu.be/QKr1HPq6YlI?t=11635

Does it also require jquery?

4:50pm. Yes, it seems it does.

https://youtu.be/QKr1HPq6YlI?t=11652

I am no longer getting weird exceptions, but nothing is showing up possibly due to style errors.

4:55pm. It is not showing up. At this rate, it seems doubtful I am going to hit the 4h mark. Where am I going wrong? What about that native prompt? Also let me try getting rid of the css.

```
public async Task testRun() => await JSrun.InvokeVoidAsync("prompt","'qwe'");
```

Yeah, this works properly.

```
public async Task testRun() => await JSrun.InvokeVoidAsync("toastr.infow","'qwe'");
```

When I try putting in a method that does not exist, I get an exception. Good.

Why would the css be wrong, I have no idea.

https://github.com/Blazored/Toast

Interesting, but not what I am looking for.

```
<link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
	toastr.info("qwe")
</script>
```

I tried putting this into a html file and running it. Nothing shows up. What the hell? No wait.

Looking at that first line, why is it not .css?

FFFFUCK! That was the error!

I was sure I put in .css, but I was wrong!

I thought there might be weird library incompatibilities or something like that.

5:10pm. Ok, now I can move forward.

```
@page "/blazorjs"
@inject IJSRuntime JSrun

<h3>BlazorJS</h3>

<div class="row p-2">
    <button class="btn btn-success col-2"
        @onclick=@(e => JSrun.InvokeVoidAsync("toastr.success","'Great!'"))
        >
        Toastr Success
    </button>
    <button class="btn btn-danger col-2"
        @onclick=@(e => JSrun.InvokeVoidAsync("toastr.error","'Bad!'"))>
        >
        Toastr Failure
    </button>
</div>
<div class="row p-2">
    <button class="btn btn-success col-2">SweetAlert Success</button>
    <button class="btn btn-danger col-2">SweetAlert Failure</button>
</div>

@code {
}
```

This works. Now I need SweetAlerts functionality. But before that, let me check out how he styled the buttons.

```
@onclick=@(e => JSrun.InvokeVoidAsync("toastr.success","Great!"))
```

Not what I thought. It seems it does not need the quotes. Does it only...Ah, I get it. It is not that it only accepts strings. But it does the smart thing when converting them to JS native datatypes. It takes in .NET `obj`s as arguments.

5:15pm. https://youtu.be/QKr1HPq6YlI?t=11999

Let me focus on sweet alerts. The styling will have to come last. Styling is always my weakness.

https://www.jsdelivr.com/package/npm/sweetalert2

The sweet alert it here.

But what about the stylesheet for it?

Let me try it without it.

```
Swal.fire({
  icon: 'error',
  title: 'Oops...',
  text: 'Something went wrong!',
  footer: '<a href="">Why do I have this issue?</a>'
})
```

How do I pass in this kind of argument?

Let me check out C# anonymous records.

```cs
var v = new { Amount = 108, Message = "Hello" };

// Rest the mouse pointer over v.Amount and v.Message in the following
// statement to verify that their inferred types are int and string.
Console.WriteLine(v.Amount + v.Message);
```

Ok.

```
    <button class="btn btn-danger col-2"
        @onclick=@(e => JSrun.InvokeVoidAsync("Swal.fire",new {
            icon= "error",
            title= "Oops...",
            text= "Something went wrong!",
            footer= "<a href=\"\">Why do I have this issue?</a>"
            }))
        >
        SweetAlert Failure
    </button>
```

Let me try it like this.

Oh, it works perfectly. Nice. It does not seem like I need the style sheets. the style is the same as on the website.

Ok...

Let me watch the video. This kind of assignment should not have taken me more than 5m.

https://youtu.be/QKr1HPq6YlI?t=12098

Ah, that is how he is setting the width. I forgot about `style`.

5:35pm. https://youtu.be/QKr1HPq6YlI?t=12351

Now focus me. For the next hour it is only videos. He really took the long way in making those alerts, in contrast my own solution is the most succinct.

https://youtu.be/QKr1HPq6YlI?t=12428

Oh I see. So this is how I could have accessed a different page.

6pm.

```cs
var q = async () =>
{
    await Task.Delay(500);
    Console.WriteLine("qwe");
    return 3;
};

var x = async (Task<int> t) =>
{
    var a = await t;
    var b = await t;
    return a + b;
};

Console.WriteLine(await x(q()));
```

It is interesting that the most recent C# has a simplified top level. I am amazed. I can even do async things in it. Now a hello world program is just an one liner in it.

Anyway, I was curious as to how many times qwe would get printed and the answer is 1. So once a task runs, the result for it gets memoized. Yeah, I recall reading that this is how it works, but that was so long ago, that I was not sure. Ok, let me move on.

https://youtu.be/QKr1HPq6YlI?t=12921

It is 6pm and I am only at the 3:35h mark. It is such a grindfest trying to follow this along. Let me put in more effort until it is time for lunch.

https://youtu.be/QKr1HPq6YlI?t=13279

He is really messing up this demonstration. He should be outputting to log. That way I'd know the actual order.

https://youtu.be/QKr1HPq6YlI?t=13892

I can barely watch this, but I should be able to manage for 10m more.

6:30pm. https://youtu.be/QKr1HPq6YlI?t=14322

Now it is connecting back to what I studied in the ASP.NET course.

Let me just hit the next chapter in 3m and then I'll go have lunch.

6:05pm. https://youtu.be/QKr1HPq6YlI?t=14479

Let me stop here. Just how much of the course have I covered today? A bit over 2h. That 3h taken in real life for every hour of the course. Seems about right. Anyway, that means since there is less than 2h left in the course that I should be able to finish it tomorrow. Hopefully that cards get here tomorrow so I can start my cloud studies. Cloud ML is the most important for me follow by cloud apps if I have the time.

While I look for the job, I'll just study and use my time wisely.

It is not a given that I'll get an offer for the 4 hits I have alive currently. And even if I get an offer who knows whether they'll be high enough to interest me. I am my own worst enemy here, so I should be approachable and not to imposing with my own interests during the interviews. I doubt I'll fluke the programming assignments, so the way the conversation goes is what will decide it.

6:40pm. Why not check out the AI chips I am so interested in? I mean, if TensTorrent has them on the cloud somewhere, why not try out programming them?

A year ago, this did not even occur to me. It just shows how deluded I am about the real world. Right now, I have just about returned to sanity. It is really a pity about Heaven's Key, but I'd rather make money, but be a peniless artist after all. If I have time during work, maybe I'll direct some of that into writing. It is not a given that I'll be busy all the time.

Given how much these programming jobs pay, I could work for a few years and then have enough money to retire in Croatia. Even sooner if I can make money in the stock market. I certainly have the skills for it now.

6:40pm. Looking at the market, it does not really feel like bear market action. Sure the current decline might be protracted, but I do not think it is dangerous just yet.

So I'd buy here and wait 3 months.

Or rather, what if BTC collapses, but the market shows resiliency? That would be good buy signal. Since I do not have a brokerage account right now, I can wait in leisure.

Let's compromise, I'd be long here, but not on margin. 50% should be enough. I could always increase the position once the bear goes away.

Time for lunch. I am done for the day."