"2pm. Let me start by just running the thing. That will get me to focus.
2:05pm.

```
Error trace on line: 986, column: 59 in file "Learning".
                                map = inl {state with cd} _ -> {state with cd = cd.RegionMem.create}
                                                          ^
For the sake of consistency directly updating a layout type is disallowed. Unseal it using 'indiv' first.
```

...

```
Error trace on line: 1016, column: 21 in file "Learning".
                    s.data.region_create s.data.buffer.last ()
                    ^
Error trace on line: 1017, column: 21 in file "Learning".
                    |> s.data.buffer.add state
                    ^
Variable state not bound.
```

Yeah, this is getting me to focus. Let me deal with these dumb errors.

...

```
Error trace on line: 91, column: 9 in file "learning2".
    inl agent = agent.region_create
        ^
Error trace on line: 92, column: 16 in file "learning2".
    inl cost = agent.alloc_cost
               ^
Invalid type string application. Got: [] and alloc_cost
```

Now `region_create` returns unit so it is no wonder. I am going to get rid of the feedforward agent after this is done and replace the one in `learning1`. That thing is unsafe. If anybody else was using Spiral, it would be an embarrassment for me to explain why the thing is even in the language.

Let me fix the test. It is good that it got through the initialization. It means that the rest won't be far off.

2:10pm.

```
Error trace on line: 97, column: 16 in file "learning2".
    inl cost = agent.get cost / to float train_images.basic.span_outer3
               ^
Variable train_images not bound.
```

I am close to getting it to compile.

2:10pm.

```
Error: Naked type detected on the F# side. Please check the generated code for details.
Error: Naked type detected on the F# side. Please check the generated code for details.
Error: Naked type detected on the F# side. Please check the generated code for details.
Error: Naked type detected on the F# side. Please check the generated code for details.
Error: Naked type detected on the F# side. Please check the generated code for details.
Error: Naked type detected on the F# side. Please check the generated code for details.

Process is terminated due to StackOverflowException.
```

Hmmm...

```
    inl cost = agent.get cost / to float input.basic.span_outer3
    if nan_is cost then
        Console.writeline "Training diverged. Aborting..."
        agent.region_clear
    else
        Console.printfn "Training: {0}" cost

        agent.region_clear
        next ()
```

The problem is in here somewhere.

Either `region_clear` or `get`.

2:15pm. Ah, focus me. Comment out the if statement.

```
inl cost = agent.get cost / to float input.basic.span_outer3
```

The error is here then.

I am suspecting `cd` here of being a troublemaker.

```
cd = inl s -> s.data.buffer.last |> inl {cd} -> cd
```

This thing.

```
cd = inl s -> s.data.buffer.last |> inl {cd} -> join heap cd
```

Let me try it like this.

Yeah, like this is compiles without trouble.

Let me try running it."