"12:15pm. ">>192106956 >Mastah we'll always be with you >Yes, Ill always keep you in my heart >That's very sweet but we meant your hat. Hello."
Cute and funny.

12:40pm. Let me resume. Let me see if I can compile a toy program from scratch. I need to get to the bottom of this.

1pm. I find myself reading the Symphogear thread again instead of the Coq manual. I need to focus. Let me just do this and I will take another break.

1:55pm. I could not do it. I had to take a bath. Let me give it another shot.

https://stackoverflow.com/questions/31930197/proof-general-cannot-find-library-or-its-source-file-even-with-coq-load-path-inc

Before I left I saw this post. This exactly my problem, but it is too bad it does not have an answer. I am going to have to some research to get it done. I am tempted to ask him whether he figured it out, but the account did not have any activity in the last 4 years, so that would be a waste.

https://mathoverflow.net/questions/210888/what-technical-and-or-theoretical-challenges-are-involved-in-automatically-extra
https://cstheory.stackexchange.com/questions/32011/computation-of-reals-floating-point-vs-tte-vs-domain-theory-vs-etc
https://cstheory.stackexchange.com/questions/32060/humanifying-computer-generated-or-computer-assisted-proofs

Saw this in the top networked posts in his profile. I guess I'll read this.

https://cstheory.stackexchange.com/questions/32011/computation-of-reals-floating-point-vs-tte-vs-domain-theory-vs-etc

Oh, this questions is really interesting.

"Currently, computation of reals in most popular languages is still done via floating point operations. On the other hand, theories like type two effectivity (TTE) and domain theory have long promised exact computation of reals. Clearly, the problem of floating point precision has not dwindled in relevance, so why haven't these theories become more mainstream and why aren't there more conspicuous implementations of them?

For example, are there domains of applications where we don't care much about floating point errors? Are there significant complexity concerns?"

I never heard about TTE and domain theory.

"I work in real-number computation, and I wish I knew the real answer. But I can speculate. It's a sociological problem, I think.

The community of people who work on exact real arithmetic consists of theoreticians who are not used to developing software. So they usually [relegate the task of implementation to students][1] (a notable exception is Norbert Müller's [iRRAM][2]), or they have their own [toy implementations][3].

People who *do* have the necessary programming mojo do not have the necessary theoretical background. Without solid theoretical footing it is difficult to design exact real arithmetic correctly. For instance, it is a mistake to add lots of real numbers in a `for` loop, as you will get unacceptable performace due to loss of precision. If you want to add lots and lots of reals, you should do it with a tree-like structure, taking into account the magnitudes of the partial sums. Another thing which is difficult to get across is that `<` and `=` as total boolean function on the reals simply do not exist (you can have `=` but it either returns `false` or it diverges, and `<` diverges when given two equal reals).

Lastly, it is not clear at all that we know how to implement libraries for exact real arithmetic. They're not the usual pieces of libraries which just define some datatypes and some functions on them. Often exact real arithmetic requires special modes of control. For instance, iRRAM takes over the main execution of the program (it literally hijacks `main`), as well as standard input and output, so that it can rerun the program when loss of precision occurs. My library for real arithmetic in Haskell happens in a `Staged` monad (which is essentially the `Reader` monad). Most people expect the real numbers to be "just another datatype", but I have my doubts about that.

  [1]: http://www.dcs.ed.ac.uk/home/mhe/plume/
  [2]: http://irram.uni-trier.de
  [3]: https://github.com/andrejbauer/marshall"

Ah, the reply is by Bauer.

2:15pm. https://mathoverflow.net/questions/210888/what-technical-and-or-theoretical-challenges-are-involved-in-automatically-extra

"I am going to answer the question as if you asked about massive *formalization of proofs*, not automatic extraction of formal proofs from existing informal proofs written in books, because that's a fairly hopeless task. One of the major lessons learned by Gonthier et al. was that published proofs rely on large amounts of implicit knowledge that is insufficiently recorded by current ways of writing mathematical texts.

---
**[Added 2015-07-07]** To address the comments, let me explain what the "missing knowledge" is. It is not about missing parts of a proof or missing details, we know how to deal with a lot of those through automation. Rather, the missing knowledge is more like what Andy Putman's comments suggested. For instance, the text might not explain the overall structure of the argument. Or, without telling, it just does a special case, and never explains why that is sufficient. Or, it forgets to mention that all vector spaces appearing in a given construction are actually subspaces of an ambient space, and therefore it makes sense to speak of their intersections and inclusions of one in another. These things are typically obvious to an experienced mathematician, but are *not written anywhere in the text*. And so they are hard for computers and graduate students to understand.

One of the major points of Gonthier et al. effort was to make sure that the formalization stayed very close to the actual text. The formalized proofs follow very closely the reasoning in the text, with as little extra details added in as possible. It was difficult to do this and it lead to several new techniques of formalization. Essentially, the proof assistants were adapted so that they could do the same sort of guesswork that a mathematician does when presented with insufficient information. Proof assistants have gotten much better at understanding what the user wants without having all the details spelled out for them.

People who promote formalization do *not* expect anyone to actually waste their time on boring details. *Of course* we want our proof assistants to be able to follow high-level arguments and fill in the details automatically, and so the community has worked hard to develop tools and techniques for doing this sort of thing, but much remains to be done. Dismissing the proof assistant as if by necessity they are clumsy tools that hinder mathematical ideas is like dismissing lasers because they require a roomful of equipment to function. In those areas where proof assistants actually work well, their users will tell you that *the first thing* they do when they want to try a new idea is to type it into a proof assistant. This for example has been my experience with the Twelf system which is designed for the purposes of formalizing formal systems (so a special-purpose tool).

---

Our experience with formalization of mathematics shows that formalization is possible, but with a lot of extra effort with available technology. It requires rethinking about how to organize mathematics so that it is amenable to formalization. For a moderately large formalization effort the issues arising are not mathematical but software-engineering: how to organize libraries so that they can be reused, what naming conventions to use, how to search existing libraries of theorems, etc.

Adoption of formalized mathematics is relatively slow because mathematicians have little reason to formalize their proofs. They can easily publish them unformalized, they feel that formalization just obscures matters (when in fact it forces one to really clean up after oneself), and that it is generally not worth doing. And so formalization is left to a few enthusiasts and computer scientists who need formal proofs in their work.

It is instructive to look at sub-communities that adopted formalization as a standard. In theoretical computer science this has happened in the programming language community. There many, many proofs proceed by consideration of a large number cases, of which only a couple are usually interesting. This is the perfect situation for proof assistants which can dispose of the boring stuff while making sure nothing is missed. The first ones to formalize their proofs were people who actually implemented the proof assistants. Then it was their students, the other people's students, and once the young people knew how to use the tools, the senior people joined the bandwagon (and many still prefer to use students). At any rate, in a conference on programming languages it has become the norm to say "and we formalized our proofs". To give you an idea where we are now: students who are just beginning their PhD's in this area often already are accomplished proof assistant hackers.

If we had to engineer massive adoption of formalization in mathematics, I would recommend two things:

1. Better tools.
2. Teach young people how to formalize mathematics.

There is a lot of room for improvement of the tools we use, and we can't teach old dogs new tricks.

Let me also explain why I think formalization is worth doing. It is *not* because we will know for sure that all that math is correct – it's irrelevant for most published math whether it is correct because the most important purpose of publication is academic promotion and not dissemination of ideas (cynical but true, just think why Elsevier is possible). The great potential of formalized mathematics is that it will give humans the ability to solve mathematical problems whose proofs are so complicated that no single human or small group of humans can comprehend or oversee using traditional methods. Another great promise is that formalized mathematics can be understood and used by machines. I guess I am looking forward to becoming the Borg."

This stuff is really interesting and I only found it by accident.

Ah, this reply is also by Bauer.

2:30pm. https://www.andrew.cmu.edu/user/avigad/Papers/cacm.pdf

Let me read this paper. I may have read it before, I am not sure. Is this the I linked in the mid-year update?

3pm. I am not sure that this is the one I've linked.

> An early milestone was Jutting’s 1977 Ph.D. thesis in which he presented a complete formalization of Landau’s book on a foundational construction of the real numbers as “Dedekind cuts,” deducing that the reals so constructed are a complete ordered field.

So the computer formalization of reals is only 52 years old by this point.

4:05pm. Some chores came up, but I am finally done with the paper.

Let me see if I can at least figure out how to compile something today.

```
-*- mode: compilation; default-directory: "e:/TheoremProving/Coq stuff/" -*-
Compilation started at Sun Aug 18 16:07:36

make hello.vo
make: *** No rule to make target 'hello.vo'.  Stop.

Compilation exited abnormally with code 2 at Sun Aug 18 16:07:36
```

Ah, I see. It really requires a make file after all.

I forgot about this.

```
-*- mode: compilation; default-directory: "e:/TheoremProving/Coq stuff/" -*-
Compilation started at Sun Aug 18 16:09:23

make hello.vo
coq_makefile -f _CoqProject | sed 's/$(COQCHK) $(COQCHKFLAGS) $(COQLIBS)/$(COQCHK) $(COQCHKFLAGS) $(subst -Q,-R,$(COQLIBS))/' > Makefile.coq
Fatal error: exception Sys_error("_CoqProject: No such file or directory")
make -f Makefile.coq makefile
make[1]: Entering directory 'e:/TheoremProving/Coq stuff'
make[1]: Nothing to be done for 'makefile'.
make[1]: Leaving directory 'e:/TheoremProving/Coq stuff'
make -f Makefile.coq hello.vo
make[1]: Entering directory 'e:/TheoremProving/Coq stuff'
make[1]: *** No rule to make target 'hello.vo'.  Stop.
make[1]: Leaving directory 'e:/TheoremProving/Coq stuff'
make: *** [makefile:4: hello.vo] Error 2

Compilation exited abnormally with code 2 at Sun Aug 18 16:09:23
```

4:10pm. https://stackoverflow.com/questions/47242800/coqide-make-on-windows

---

coq_makefile -f _CoqProject -o Makefile.coq
make -f Makefile.coq Frap.vo

---

Let me try this.

4:35pm. I am going crazy. When it was in `e:\asd` I managed to get the empty `hello.v` to compile, but here I am getting nothing.

...Now I am getting nothing again in `asd`. Uah, I probably wrote something different to get it to compile, but what exactly?

```
PS E:\asd> coq_makefile -o Makefile.coq -f _CoqProject
PS E:\asd> make hello
make: *** No rule to make target 'hello'.  Stop.
PS E:\asd> make hello.v
make: Nothing to be done for 'hello.v'.
PS E:\asd> make
make: *** No targets specified and no makefile found.  Stop.
PS E:\asd> make
make: *** No targets specified and no makefile found.  Stop.
PS E:\asd> make hello.v
make: Nothing to be done for 'hello.v'.
PS E:\asd> make -f Makefile.coq
COQDEP VFILES
C:\Coq\bin\coq_makefile.exe -o Makefile.coq -f _CoqProject
COQC hello.v
```

Ah, this.

4:40pm. Ok, now it works, but I find this awkward. There is a lot of messing about with configuration files and I still cannot get individual files to compile.

5:10pm. https://stackoverflow.com/questions/57545797/how-to-compile-coq-files-with-proof-general-emacs

I've opened an issue. I'll see what I get by tomorrow. This is not a hard question so hopefully I should get something.

5:25pm. Phew. I am finally done for the day. I certainly do not feel like dealing with this anymore for the time being.

You'd think that hello world would be easy, but it is actually rather time consuming and labor intensive.

5:30pm. Forget this stuff. It is time for some XCOM."