"1:35pm. Let me resume this thing. I got a reply saying that the order in the `_CoqProject` file does not matter. Meanwhile I am having to spend a good chunk of my time ordering the things by hand. Let me get the library to compile and then I'll reply to that.
```
PS E:\TheoremProving\coquelicot-3.0.2> coq_makefile -f _CoqProject -o makefile; make
COQC theories/Rcomplements.v
File ".\theories/Rcomplements.v", line 124, characters 10-15:
Warning: Zpred is Z.pred [compatibility-notation,deprecated]
File ".\theories/Rcomplements.v", line 124, characters 10-15:
Warning: Zpred is Z.pred [compatibility-notation,deprecated]
COQC theories/Rbar.v
COQC theories/Markov.v
File ".\theories/Markov.v", line 78, characters 10-18:
Warning: Zabs_nat is Z.abs_nat [compatibility-notation,deprecated]
File ".\theories/Markov.v", line 78, characters 10-18:
Warning: Zabs_nat is Z.abs_nat [compatibility-notation,deprecated]
File ".\theories/Markov.v", line 86, characters 8-15:
Warning: Zabs_eq is Z.abs_eq [compatibility-notation,deprecated]
File ".\theories/Markov.v", line 86, characters 8-15:
Warning: Zabs_eq is Z.abs_eq [compatibility-notation,deprecated]
COQC theories/Iter.v
COQC theories/Lub.v
COQC theories/Hierarchy.v
File ".\theories/Hierarchy.v", line 4399, characters 10-25:
Warning: Tactic Fourier.fourier is deprecated since 8.9.0. Use lra instead.
[deprecated-tactic,deprecated]
File ".\theories/Hierarchy.v", line 4415, characters 2-17:
Warning: Tactic Fourier.fourier is deprecated since 8.9.0. Use lra instead.
[deprecated-tactic,deprecated]
File ".\theories/Hierarchy.v", line 4425, characters 8-23:
Warning: Tactic Fourier.fourier is deprecated since 8.9.0. Use lra instead.
[deprecated-tactic,deprecated]
COQC theories/Lim_seq.v
COQC theories/SF_seq.v
COQC theories/Compactness.v
COQC theories/Continuity.v
COQC theories/RInt.v
File ".\theories/RInt.v", line 487, characters 0-7:
Warning: The Focus command is deprecated; use '2: {' instead
[deprecated-focus,deprecated]
File ".\theories/RInt.v", line 3007, characters 2-9:
Warning: The Focus command is deprecated; use '3: {' instead
[deprecated-focus,deprecated]
File ".\theories/RInt.v", line 3012, characters 2-9:
Warning: The Focus command is deprecated; use '3: {' instead
[deprecated-focus,deprecated]
File ".\theories/RInt.v", line 3578, characters 0-7:
Warning: The Focus command is deprecated; use '2: {' instead
[deprecated-focus,deprecated]
File ".\theories/RInt.v", line 4613, characters 2-9:
Warning: The Focus command is deprecated; use '2: {' instead
[deprecated-focus,deprecated]
File ".\theories/RInt.v", line 4638, characters 2-9:
Warning: The Focus command is deprecated; use '2: {' instead
[deprecated-focus,deprecated]
COQC theories/Series.v
COQC theories/Seq_fct.v
File ".\theories/Seq_fct.v", line 366, characters 8-17:
Error: The reference is_derive was not found in the current environment.

make[1]: *** [makefile:663: theories/Seq_fct.vo] Error 1
make: *** [makefile:327: all] Error 2
```

I am not sure what is going on. I am going to have to mail the authors about this `is_derive` thing. Let me make a reply for now.

```
theories/Equiv.v
theories/Derive.v
theories/Seq_fct.v
```

Ah, I had to put Derive before `Seq_fct`.

1:55pm.

```
File ".\theories/Complex.v", line 491, characters 0-135:
Warning: Ignoring canonical projection to C by ModuleSpace.sort in
C_R_ModuleSpace: redundant with C_ModuleSpace
[redundant-canonical-projection,typechecker]
File ".\theories/Complex.v", line 494, characters 0-167:
Warning: Ignoring canonical projection to C by NormedModuleAux.sort in
C_R_NormedModuleAux: redundant with C_NormedModuleAux
[redundant-canonical-projection,typechecker]
File ".\theories/Complex.v", line 497, characters 0-113:
Warning: Ignoring canonical projection to C by NormedModule.sort in
C_R_NormedModule: redundant with C_NormedModule
[redundant-canonical-projection,typechecker]
File ".\theories/Complex.v", line 574, characters 0-175:
Warning: Ignoring canonical projection to C by CompleteNormedModule.sort in
C_R_CompleteNormedModule: redundant with C_CompleteNormedModule
[redundant-canonical-projection,typechecker]
```

I get this error in both versions of the library.

```
-R theories Coquelicot
theories/Rcomplements.v
theories/Rbar.v
theories/Markov.v
theories/Iter.v
theories/Lub.v
theories/Hierarchy.v
theories/Lim_seq.v
theories/SF_seq.v
theories/Compactness.v
theories/Continuity.v
theories/RInt.v
theories/Series.v
theories/Equiv.v
theories/Derive.v
theories/Seq_fct.v
theories/PSeries.v
theories/Derive_2d.v
theories/RInt_analysis.v
theories/ElemFct.v
theories/RInt_gen.v
theories/AutoDerive.v
theories/Complex.v
theories/KHInt.v
theories/Coquelicot.v
```

At any rate, I finally have this thing down. I'll study the library in this order.

2:15pm. Let me resume. For some reason I started surfing /pol/ even though I did not mean to.

I admit this whole experience is souring me on Coq once more. I never expected the package management situation to be so horrible.

You can just see how much time it took from me by reading the commits. I absolutely loathe the Linux-style user experience of messing with configuration files and command line tools.

There are 25 files to go through and approximately 20k lines of code in here. It is going to take a while to go through this start to finish, but by the time I am done, I should have some idea what formal math is about. I mean I already got the gist of it since I've been doing proofs for a while, but I never even touched high school math. This should help me fill up the gap.

2:20pm. I thought `Rcomplement` was the last in line, but it turns out it is the first. Let me go for it.

3 more hours of this and then I will get back to gaming."