"5:10pm. I am back.
5:30pm. And I am done with lunch and that orange.

Now I can finally start the web chapter, but I feel so drowsy. For these parts I'll definitely need focus. So I'll save most of this for the next few days, but let me at least open it today.

5:50pm. This went by quickly.

```
// "outFile": "./",                       /* Concatenate and emit output to single file. */
```

I wonder why I need a bundler if this option exists.

6pm.

```
ERROR in ./src/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Cannot find module 'typescript'
```

Why does webpack keep giving me this error. I even installed `typecript` locally.

6:10pm. What a bizarre error. I have no idea what is going on and Google is giving me nothing. Yeah, this is the kind of trouble I'd expect from command line shit, though things have been remarkably smoothly up to this point.

Let me follow the instructions exactly this time.

6:15pm. Oh it works. Most likely the reason why it failed for me previously is because I used `tsc --init` and that thing uses `jscommon` modules.

6:30pm. 379/551. The chapter is going quite smoothly, but I think I will call it a day here.

So far, this book has been excellent from start to finish. I am definitely learning here.

I think that once I have an understanding of these projects, I will be able to use them as a template when I turn to studying ASP.NET. I definitely want to understand servers through and through."