"10:35am. I am up. Let me chill a little and I will start.
10:40am. Let me start. Surprised to see Hero's Daughter on top of MangaDex popularity list.

Forget that, I should get a move on. I really want to get local recursive statements working. I am almost 100% sure that the runtime bug is due to a compile time one, but to start things off, let me make sure.

10:50am.

```
inl rec loop nearTo body ~i ~s = join if i < nearTo then loop nearTo body (i+1) (body i s) else s
inl for (from: nearTo:) body state = loop nearTo body from state
```

I got the idea for this yesterday. Let me put it into action. Is the resulting program from this the same as the previous one. If it is not then that means 100% that I have a compiler bug.

10:50am. Hmmm, not at all what I expected. There is no difference. How can this be?

Does that mean that both versions have a compiler bug? I'd have thought that global rec statements would be sound, but I'll have to reconsider that now.

Let me try running this again. After that, I'll insert print statements for `nearTo` and `i`. I want to make sure that the way they change makes sense. What I am expecting is that incorrect variables are being captured due to some prepass bug.

```
inl rec loop nearTo body ~i ~s = join
    $"printfn \"i = %i, nearTo = %i\" !i !nearTo"
    if i < nearTo then loop nearTo body (i+1) (body i s) else s
```

Let me see what comes out of this.

11am.

```
i = 0, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 1, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 2, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 3, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 4, nearTo = 4
i = 0, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 1, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 2, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 3, nearTo = 4
i = 0, nearTo = 4
i = 1, nearTo = 4
i = 2, nearTo = 4
i = 3, nearTo = 4
i = 4, nearTo = 4
i = 4, nearTo = 4
i = 0, nearTo = 1
q
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FSI_0005.method6(Int32 v0, Boolean[][] v1, US0[][] v2, Mut0 v3, ValueTuple`3[] v4, ValueTuple`3[][] v5, Int32 v6) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Script1.fsx:line 70
   at FSI_0005.method5(Boolean[][] v0, US0[][] v1, Mut0 v2, ValueTuple`3[] v3) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Script1.fsx:line 388
   at FSI_0005.method2(US0[][] v0, Int32 v1, Int32 v2) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Script1.fsx:line 413
   at <StartupCode$FSI_0005>.$FSI_0005.main@() in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Script1.fsx:line 429
Stopped due to error
```

Some of these printouts are weird. But there is nothing obviously weird like vars getting switched.

Those 'weird' printouts are there due to nested loops.

```
    inl cells_visited =
        array.init (array.length field) (fun b =>
            array.init (array.length (array.index field b)) (const false)
            )
```

I have to initialize the arrays.

```
i = 0, nearTo = 1
q
```

Then most likely I try to index an array at 0 and get an exception. Right now my view has changed - this is most likely a programming bug after all rather than a compiler one.

11:10am. Still...

Let me run the script itself in debug mode.

I'll pause it just before the index.

```fs
and method6 (v0 : int32, v1 : ((bool []) []), v2 : ((US0 []) []), v3 : Mut0, v4 : (struct (int32 * int32 * UH0) []), v5 : ((struct (int32 * int32 * UH0) []) []), v6 : int32) : unit =
    let v7 : bool = v6 < v0
    if v7 then
        let v8 : int32 = v6 + 1
        let struct (v9 : int32, v10 : int32, v11 : UH0) = v4.[v6]
        printfn "q"
        let v12 : int32 = v9 - 1
        let v13 : bool = v12 <= 0
        let v14 : bool =
            if v13 then
                let v14 : int32 = v2.Length
                let v15 : bool = v12 < v14
                if v15 then
                    let v16 : (US0 []) = v2.[v12]
```

I've been thinking about this all wrong. For some reason I thought the error was on the ...

```fs
let struct (v9 : int32, v10 : int32, v11 : UH0) = v4.[v6]
```

...line. But the debugger is telling me that it is on the last line in the segment I've pasted. This changes everything.

```fs
        let v13 : bool = v12 <= 0
        let v14 : bool =
            if v13 then
                let v14 : int32 = v2.Length
                let v15 : bool = v12 < v14
                if v15 then
                    let v16 : (US0 []) = v2.[v12]
```

It is telling me that `v12` is -1 here...

```fs
let v13 : bool = v12 <= 0
```

-1 <= 0. That is true. I meant to check that `0 <= v12`!

This is a good lesson for me. I need to stop running large scripts in FSI. Instead I'll paste them into that side project.

11:15am. Let me revert the loop to the previous version. Since there is no difference anyway, I can conclude that it is being compiled correctly.

```
inl main () =
    inl ~field_size = 4
    inl ~princess_pos = 2,3
```

I am trying out different setting of `princess_pos` and they all work correctly. I did it.

11:25am. Right now I am just chilling.

Focus me. Usually my morning sessions have lasted past 12pm, but since I met my goals, my focus has loosened.

Let me do some cleaning up. Now that I have this test done, let me remove it from core.

...That was already done. Ok, good.

11:30am. Before I take a break, let me think about what should be done next? What should be my next short term goal?

I should be doing more tests. I think at this point I have the local recursive statements nailed down. And with that the language implementation should be clean design-wise.

For the next two weeks I should be doing testing. This latest one was more complex than the previous ones - I should be going in that direction.

11:35am. I need more prototype tests...

Hmmmm...

Ok, what I should aim for next is to convert the rest of the examples from `tc.spi` into tests. That should be my biggest short term goal. Then after that I'll do more prototype tests, though I am not sure what I should fit for those. Maybe I will skip those as I am decently confident in prototypes at this stage.

After I am done with that, I should either bring in more tests from v0.09 or try converting some of my own work to Spiral v0.2.

I can convert the CFR algorithm + games to v0.2. That looks like it would be fun. And remember that CFR proof I expressed in terms of randomized testing? A randomized testing library in Spiral sounds like a decent project for testing out prototypes.

11:45am. This sounds good to me.

Let me get the `tc.spi` out of the way, and then I will program my own stuff in v0.2. The best test is always actual programming. The reason the v0.09 tests are the way they are is because the way v0.09 was developed. I had to go around testing everything in turn, developing both the language and my skills at it gradually.

The current me and the me from 2017 can hardly be compared. I am at a far higher level now and that is reflected in the Spiral's implementation. I do not need to be conservative here. I should just dive in.

It is definitely too early to start showcasing Spiral to potential sponsors. I should have at least 2 and preferably 3 months of experience in programming v0.2 before I move to that stage. So February-March. No doubt those are optimistic estimates and it will take longer in real time.

Until things are ready I should just engross myself in Spiral and tidy it up.

I still have plenty of TODOs on the top of my journal that I should deal with. They will take time too.

When it is time to move to the next stage, I will release Spiral in alpha stage on the VS Code marketplace. And seriously try to both monetize it and get my hands on those neurochips.

According to that paper, they will come out commercially in a few years, getting them right now will be far ahead of schedule.

I will be amongst the very first adopters, and thanks to Spiral, I have what it takes to become the very best in the world at using them. The capability to always be at the bleeding edge of hardware and make optimal use of it is a huge edge, not even the guys at Deepmind or OpenAI will have it.

Well, unless they also take up Spiral, but who ever takes me seriously? In the natural world living beings tend to perish instead of adapt, and people and their worldviews aren't any different. They'd often let go of their lives rather than beliefs. And programming languages even though they should be nothing more than garments, tend to held dearly as actual religion.

12pm. Let me have breakfast instead of just ranting here. I should have done this half an hour ago."