"10:30am. Since this journal file is already 155k lines, maybe it is time to start thinking about starting a new one.
10:35am. Ok, let me start. The sooner I finish this scene, and the sooner I get good at art, the sooner I can get a handle on my life. I need a proper money making skill, right now I could only wage slave with programming.

10:45am. Focus me. Let me the flower into a subnet.

Hmmm, how do I reuse subnets? Also how do I add params to it.

https://youtu.be/SiT4r22BWY8
Houdini Basics - 6 Tips and Tricks when working with Houdini Digital Assets!

I am confused. Let me just watch stuff related to digital assets.

11:05am. I am confused. Why do subnets have 4 inputs. What if I needed more or less?

Let me continue watching the HDA vid.

11:15am. https://youtu.be/SiT4r22BWY8?t=781

Oh, this is a really good way of moving stuff to the main level.

...Let me just ask about subnet inputs.

///

Why do subnets have 4 inputs? Is it possible to change this so they have more or less?

Also, I want to factor some of the functionality that I've made, do I have to turn those parts into HDAs? HDAs end up being separate files, while I just want some functions (in programming parlance) that I could easily reuse. Having a file for every function would create a mess.

I suppose I could try reusing subnets, but I am not sure how to do that from different objects for example.

///

11:35am. Shit.

///

>>880774
>not sure what your objection to hdas is, esp vs subnets. you don't have to load all your hdas in with every project. asset > install asset library will let you bring in hdas on a per project basis.
Imagine if you were programming in Python and had to have a different file for each function. I don't yet understand how to deal with HDAs properly.

```
  File "<stdin>", line 1
    { 'event_type': hou.hdaEventType.LibraryInstalled, 'library_path' : 'E:/Art Projects/YYY/XXX_Flower.hdanc' }
                                                                                              ^
SyntaxError: invalid syntax
```

Also, for some reason I got a Python error when turning a subnet into a HDA. I obfuscated the YYY and XXX, but otherwise it is the same. Should I be worried about this?

///

12:05pm. It seems to have something to do with input labels. No matter.

Right now I've turned a subnet into a HDA. But how do I edit the HDA after I've created it?

https://www.youtube.com/playlist?list=PLXNFA1EysfYnnm2-UZmxrd-MWC7LTWEVl

This is so annoying and confusing. Let me watch this playlist on HDAs.

I factored out that flower, but I have no idea how to deal with it after that. I am also going to have to look into advanced instancing. I am not sure how to select between leaves and branches. Well, let me do it one step at a time. First of all, let me figure out how to edit the HDAs.

Ah, I see. There is a Save Asset option that I need to click in order for it to take effect.

If I want to edit the asset from somewhere else, I just need to unlock it. Ok, good. I figured out the HDA basics. Let me continue with the video.

Once I finish the playlist, what I will have to do is dive deeper into scattering. I might have studied this in the past, but I haven't properly internalized how to copy objects to points while selecting. There are different ways of doing it too. I have to go with an approach that satisfies me.

Also I realized that I've made a mistake in never using copy to curve. But it is not a big deal.

12:50pm. https://youtu.be/tWjIWEgoOf8?list=PLXNFA1EysfYnnm2-UZmxrd-MWC7LTWEVl
Houdini Digital Assets | 3. Create Parameters

Let me stop here. I am warming up towards the HDAs. They'll be super useful.

1:50pm. Done with breakfast. Let me do the chores here. Then I will resume.

2:55pm. Today the chores took a while.

At any rate, I am finally ready to start. What is next? I need to go through the HDA playlist. Also I need to figure out how to scatter properly. Let me start with the scatter tutorials. I'll go over the ones that I've already watched.

Actually, let me chill with the Baki raw thread first.

https://youtu.be/N7CDHwgWKVo
Advanced Scattering in Houdini 18.5

Let me start this.

3:10pm. I must have been completely blind. How did I miss the `Copy To Points` and `Copy To Curves` having piece attributes?

Let me try it out.

3:20pm. Huh, I do not know. It is not working for some reason.

3:30pm. This is wonderful. I figured it out completely. It turns out that attribute randomize can be used to assign weights to a particular string. That will make it easy to deal with.

Still when it comes to distributing leaves and branches, I won't be able to use this to do that automatically. The scatter points require tagging ahead of time so that the copy to points node can select which geometry to instantiate.

3:45pm. As it turns out, it is possible to drag the UI element where you put down the distribution into the param interface. Things are really coming together for me. I can see now that I can simply pass in the packed geometry and then pass the distribution via a channel. Giving a leaf a weight of 9 and a branch a weight of 1 should be no problem at all thanks to Attribute Rnadomize.

One thing I do not get is how to do the default params. Right now it always starts at 0 or something like that instead of something sensible.

4pm. Focus me. I've figured out a big part of what will make scattering useful. This thing here is literally why I ditched Blender 3 weeks ago. Now let me go through the HDA playlist.

4:10pm. https://youtu.be/tWjIWEgoOf8?list=PLXNFA1EysfYnnm2-UZmxrd-MWC7LTWEVl&t=419

Here are the defaults. Under the `Channels` tab.

4:45pm. Had to take a break. Let me resume. What I will dedicate my time is getting through the playlist.

https://youtu.be/VHEBtm939FM?list=PLXNFA1EysfYnnm2-UZmxrd-MWC7LTWEVl
Houdini Digital Assets | 4. Create Toggles and Menus

Time for this.

I'll focus on the playlist and thne I am going to come in and deal with the vines.

5:20pm. https://youtu.be/g5E4GYKlY18?list=PLXNFA1EysfYnnm2-UZmxrd-MWC7LTWEVl
Houdini Digital Assets | 7. Structure the Interface

Having to watch these vids is torture by tedium. But let me just go through them. Then I will focus whole heartedly on the task at hand.

...No, forget it. I should be working on my own things. That is what will maximally motivate me. Let me finish the flower.

5:50pm. Good, I finally did the branch.

This was what tripped me up in Blender. So far though, I have only two variants, but should I want to, I could easily randomize it. I should turn the flower itself into a HDA. Right now, I only have its template as a HDA. But instead of having two objects, I can have two HDAs. That will allow me to vary the branches a lot more significantly.

Before I do anything though I should set up the camera. I want the shot to look good from below. Let me put in Luna's bounding box.

6:15pm. Damn it, putting the camera in the exact place I want sure is difficult. I really have to fight the natural navigation. Just why does first person navigation works so shitily? I am going to have to look into that more. At any rate, the angle I have should be fine.

7pm. Had to leave for lunch. Right now I should be making progress, but in a way I am even though I am not doing anything. Right now, I am taking a step back to admire my handiwork.

7:15pm. Let me close here. I am imagining what I should do here, and the answer I feel should be more variation. What I need at this moment is more variation. Then I'll do some mask work. Mask from feature should be what I need to get the right angles. Then I'll take out one of the beams.

Hrmmmm, should I then add another main wine?

That is what is really troubling me.

7:20pm. Amateurs always make the mistake of trying to put in too much detail. My sense is that what I have now should be enough.

7:25pm. Hmmm, yeah, it is good. I'll just translate Luna a bit to the left, in effect moving the stuff above to the right. That should bring it more into focus.

And after that what I want to do is put in a bit more variation. Doing it like I envision should also ensure that the leaves are always pointing downwards. Right now some of the branch flowers are defying gravity.

7:30pm. Let me close here. I am going to finish the vines tomorrow without fussing too much about it. That will allow me to deal with the rest afterwards. When the rest is done, what I will do is sculpt Luna. After that will come texturing and the fun shading stuff. Lastly will come painting.

I think at this point I can finally consider myself to have just a bit of skill at Houdini.

7:35pm. I need to keep pushing. This kind of mentally demanding owrk is also a good way getting my brain up to par after Covid. I think I am pretty good right now, but my senses of taste and smell still haven't come back properly.

7:40pm. Let's do this me. Now that I have HDAs in by toolbox, I have everything I need to create the right amount of variation. I need to tap into that and bring this scene to a close. After I properly internalize this, my speed on future projects should go way up."