"1:55pm. First entry in the new file. Hopefully I'll end up finding more success in the next 7 years than I have in the last ones.
I set the style transfer to download while I was taking a break, and some good stuff came out. A lot of it is good. I only have to chose what kind of effect I am going for. I am still partial to the great wave. I'll just lower the intensity a tad when the time comes.

https://www.sidefx.com/tutorials/city-building-with-osm-data/
https://vimeo.com/402297173

Now let me get back to watching the Houdini OSM tutorial. After that I'll give it a try myself.

2:05pm. Exported a piece of Malinska from OSM. Let me load it in Houdini.

...It seems Labs was not installed properly.

https://www.sidefx.com/faq/question/how-do-i-install-sidefx-labs/

What the hell, it is not working properly.

Ah, damn it. I forgot to go into the Geo level, that is more likely why it did not work.

2:05pm. I am starting to get into it. But the street view data it seems does not have elevation information. Malinska is not flat, it is pretty much built on a hill which goes lower the closer one gets to the sea.

Focus me. Let me move on to part 2 which is building generation.

https://vimeo.com/402297219
City Building with OSM Data | Part 2 | Generate the Buildings

Rendering is a different matter, but if it is just modeling it, maybe I could do it all in Houdini. I am not going to be doing the buildings by hand. The more I procedurally generate, the better off I'll be.

2:30pm. Damn it, you know what. Let me pause here. I want to take a bath. I should have taken it yesterday, but I finished work past midnight so I did not feel like it. Let me do it now and then I will resume. I can set the style transfer to work while that is happening.

3:30pm. Done with the bath.

///

  File "C:\Users\Marko\anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 12708347904 bytes.

///

Damn. I guess there was an big image in there. Sigh, there was a scale width option in there, but when I tried it, it did not work. I am going to have to play with it.

Gahh...it's `barnett-newman_black-fire-i-1963.jpg`

It a minimalist image with an absurd resolution. In fact, it a poorly upscaled image, by about 4x. Just who the hell curated this dataset?

Let me delete it. I'll also get rid of it from the dataset.

3:40pm. I should have done this basic check up front. There are 5-9mb jpg images in this dataset. Some of them are good. I have no choice. I am going to have to figure out how to resize them if they are above the maximum.

Let me work on this a little.

```py
def get_params(opt, size):
    w, h = size
    new_h = h
    new_w = w
    if opt.preprocess == 'resize_and_crop':
        new_h = new_w = opt.load_size
    elif opt.preprocess == 'scale_width_and_crop':
        new_w = opt.load_size
        new_h = opt.load_size * h // w

    x = random.randint(0, np.maximum(0, new_w - opt.crop_size))
    y = random.randint(0, np.maximum(0, new_h - opt.crop_size))

    flip = random.random() > 0.5

    return {'crop_pos': (x, y), 'flip': flip}
```

I am going to have to modify the code to give me what I want.

```py
def get_transform(opt, params=None, grayscale=False, method=Image.BICUBIC, convert=True):
    transform_list = []
    if grayscale:
        transform_list.append(transforms.Grayscale(1))
    if 'fixsize' in opt.preprocess:
        transform_list.append(transforms.Resize(params["size"], method))
    if 'resize' in opt.preprocess:
        osize = [opt.load_size, opt.load_size]
        if "gta2cityscapes" in opt.dataroot:
            osize[0] = opt.load_size // 2
        transform_list.append(transforms.Resize(osize, method))
    elif 'scale_width' in opt.preprocess:
        transform_list.append(transforms.Lambda(lambda img: __scale_width(img, opt.load_size, opt.crop_size, method)))
    elif 'scale_shortside' in opt.preprocess:
        transform_list.append(transforms.Lambda(lambda img: __scale_shortside(img, opt.load_size, opt.crop_size, method)))

    if 'zoom' in opt.preprocess:
        if params is None:
            transform_list.append(transforms.Lambda(lambda img: __random_zoom(img, opt.load_size, opt.crop_size, method)))
        else:
            transform_list.append(transforms.Lambda(lambda img: __random_zoom(img, opt.load_size, opt.crop_size, method, factor=params["scale_factor"])))

    if 'crop' in opt.preprocess:
        if params is None or 'crop_pos' not in params:
            transform_list.append(transforms.RandomCrop(opt.crop_size))
        else:
            transform_list.append(transforms.Lambda(lambda img: __crop(img, params['crop_pos'], opt.crop_size)))

    if 'patch' in opt.preprocess:
        transform_list.append(transforms.Lambda(lambda img: __patch(img, params['patch_index'], opt.crop_size)))

    if 'trim' in opt.preprocess:
        transform_list.append(transforms.Lambda(lambda img: __trim(img, opt.crop_size)))

    # if opt.preprocess == 'none':
    transform_list.append(transforms.Lambda(lambda img: __make_power_2(img, base=4, method=method)))

    if not opt.no_flip:
        if params is None or 'flip' not in params:
            transform_list.append(transforms.RandomHorizontalFlip())
        elif 'flip' in params:
            transform_list.append(transforms.Lambda(lambda img: __flip(img, params['flip'])))

    if convert:
        transform_list += [transforms.ToTensor()]
        if grayscale:
            transform_list += [transforms.Normalize((0.5,), (0.5,))]
        else:
            transform_list += [transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
    return transforms.Compose(transform_list)
```

Oh, look at that. A lot of options are here.

```py
def __scale_width(img, target_width, crop_width, method=Image.BICUBIC):
    ow, oh = img.size
    if ow == target_width and oh >= crop_width:
        return img
    w = target_width
    h = int(max(target_width * oh / ow, crop_width))
    return img.resize((w, h), method)
```

Let me put a break point here.

```py
h = int(max(target_width * oh / ow, crop_width))
```

Oh shit, I see. The fact that scale width was not working is in fact an error in the code itself. That crop width definitely should not be here.

```py
def __crop(img, pos, size):
    ow, oh = img.size
    x1, y1 = pos
    tw = th = size
    if (ow > tw or oh > th):
        return img.crop((x1, y1, x1 + tw, y1 + th))
    return img
```

I am a bit confused how cropping works, but nevermind that.

```py
def __scale_width(img, target_width, crop_width, method=Image.BICUBIC):
    ow, oh = img.size
    if ow < target_width:
        return img
    w = target_width
    h = target_width * oh // ow
    return img.resize((w, h), method)
```

Let me do it like this. I'll get rid of cropping, I do not need it. I am not sure what it should be doing and do not want to waste my time reasoning it through.

And with these changes the big file works quite well. I regret erasing that minimalist example now from both places. I'd need to redownload it to get it back, and considering it looks like a green book cover, there is no way I will be doing that. The dataset is already too large as it is.

4:15pm. Ok, it is too bad this has happened, but I'll just have to let it run later. Right now let me get back to Houdini.

It will be a slow day again. I guess I'll make it up with volume as I did yesterday.

4:25pm. Why is the building generator not working for me?

I've done some playing around and it seems it requires the second input.

https://www.sidefx.com/tutorials/building-generator/

Let me puase the city tutorial so I can study this.

> Behold a building that would make the finest architect weep with jealousy (don’t worry, we’ll work up a better one after covering the basics):

They are being sarcasting, but I think this is quite decent. Most drawings aren't more detailed than this.

4:40pm. https://www.sidefx.com/tutorials/building-generator/

https://youtu.be/YsIM5pzIVk0
Houdini Modular Building Generator

Let me watch some youtube vids. The building generator does not have docs and it works a bit differently than it does in the tutorials. I am going to have to spend some time playing with it.

https://youtu.be/IwnbJIOSjxQ
House Generator Revisited || Houdini 18.5 Tutorial

https://www.sidefx.com/docs/houdini/nodes/sop/labs--building_generator-4.0.html

There are some docs for this. It does not show up when I use F1 for some reason.

5:15pm. Ok, I finally figured it out. I need to use the name attribute, name each of the modules and then in the building generator put them in as such.

Ok, I got it. I have the basic grasp on it. I really should have figured this out in 5m instead of 40.

5:20pm. > So far the pig panel has just sized itself to fit into the building, but what if we had explicit measurements to conform to? Also, we have to make sure to add @name to every panel. Feels like someone should make an HDA to do these things.

> Guess what? They have! The building generator utility node covers both these needs (and a few more). I replace the name sop with the utility node, specify the name there (using $OS so I can be lazy), and specify the width and height of this panel (2x2), so it won’t be resized in unexpected ways.

Ahhh, goddamit. Say that at the start.

5:30pm. Let me have lunch here.

5:55pm. I am back, but this is such a grind that I do not feel like doing it.

6:25pm. Done with the break. Let me watch the tutorial video on city building. Nothing is going right for me today. But that is the problem with Houdini. Once you move from doing art to doing programming, things start getting longer.

Still, this has to be the right decision. If I want to put together a city quickly, I need to learn this tool. Modeling a city in Blender by my lonesome is not going to be in any way efficient.

6:30pm. Let me pause. Just what are those variations in the utility node. it is eating away at me.

https://www.sidefx.com/docs/houdini/nodes/sop/labs--building_generator_utility.html

6:40pm. Nope, the variations aren't even in the docs. It just seems to be a string added in there in the spreadsheet, but it does not seem to be going much.

Wait, I think I have an inkling. The way things are now, if I name the modules the same, they will end up being considered as a single object. So how can I have things like different windows for the walls? Probably by using variations, but how exactly?

6:50pm. Let me ask in the Houdini thread what the variations are.

https://www.youtube.com/results?search_query=blender+city

I wonder if I am on the wrong track?

7:05pm. Finish the Houdini tutorial. I am dying here.

https://youtu.be/NW_djQS_N8U
Create any City in Blender in 20 Minutes

Let me watch this.

https://youtu.be/NW_djQS_N8U?t=48

Will it turns out that Blender is a better choice than Houdini for making cities?

I really hate it when I run into things that aren't clear in the nodes and just end up wasting time.

https://youtu.be/NW_djQS_N8U?t=63
> Buildings imported with randomly generated textures.

This is for the paid version of the OSM addon.

https://youtu.be/NW_djQS_N8U?t=294

It is a good thing I am watching this. I haven't thought of using satelite data for textures.

https://youtu.be/NW_djQS_N8U?t=464

Yeah, it is not a bad idea to just download the textures from somewhere instead of modeling building geometry myself. Though that was no my plan. My plan is just to put the flats where they should be.

https://youtu.be/NW_djQS_N8U?t=551

LIterally every video spends half a min explaining the node wrangler.

https://youtu.be/NW_djQS_N8U?t=587

This is an interesting way of texturing the roof.

https://youtu.be/NW_djQS_N8U?t=698

I am confused. How are these textures scaled uniformly over all the buildings?

https://youtu.be/NW_djQS_N8U?t=621

Wait, are all the buildings here a single object? I was not paying attentoin, but it seems that is so.

https://youtu.be/NW_djQS_N8U?t=730

The wall looks nice.

The floor is really low res, but that won't matter the look is upwards.

Still, I'd want to more juice from a single shot.

https://youtu.be/NW_djQS_N8U?t=959

From this distance it does not look bad at all. This is pro work.

https://youtu.be/NW_djQS_N8U?t=1110

They looked good enough that I thought they were implemented as actual volumes in the intro clip.

https://youtu.be/NW_djQS_N8U?t=1418

This does look quite good.

7:40pm. I feel humiliated by today.

https://www.sidefx.com/tutorials/city-building-with-osm-data/

I won't watch part 3 right now as I do not feel like it. I am going to finish it tomorrow. Maybe it was because I spent so much of my energy yesterday that I couldn't do much today.

At any rate I am starting to feel the urge after that Blender video.

Today I just felt very dull and unfocused.

I've decided - if Houdini is weak at providing explanations in its videos, I should just use Blender + texturing workflow. But before that let me give it an honest try. Tomorrow I will finish the last 2 vids in this series and then fiddle around with it. If it is just not coming to me, I should immitate what I learned in the Blender video.

The point is to leave my 2/5 self behind, not to get stuck doing random stuff in Houdini for months for the purpose of training. A real pro would do exactly the workflow as shown in the Blender video. Amateurs overrate skill and underrate getting things done.

7:50pm. I am going to give Houdini a day more. If I end up being forced to study the way the Labs nodes are implemented in order to figure them out, I'll go to Blender. But if not, I should give the geometry approach a try. Geometry is good and I like it. Actually even if it takes a few days, I should persevere so I can see the benefits and disadvantages of the approach.

I want to be able to zoom through the city. If I look down towards the city from closer to the grounds and see those dull textures, it will look bad. So I need to persevere.

I need to hone my mind into the learning mode and just do it.

7:55pm. No forget what I said before. It is not enough to just do it. I can master both approaches in half a week. I just need to focus on what Simon is doing and I will get it.

Once I have the city, at some point I will have to do crowds. The approach he showed me is just good for aerial shots. The geometry approach is what will allow me to develop it further. Even in the room scene, it is true that a lof of details did not make it into the scene, but I should be able to milk the scene further and from different angles.

8pm. Today I was simply too dazed, and words were going into one ear and out the other. Tomorrow I am going to focus on what he is doing properly. I've gotten a little used to Houdini again so I should be able to make progress."