"10:10am. 2am to 1am to 12am. I am getting better it seems, but I got up quite late today. The sleep was quite restful though. Let me chill for a while and then I will start. Today's first step will be to compile the library.
10:30am. Let me start. Let me mess around with compiling Coq files more. He says that the standard way of compiling is enough for him. I have no idea why this is.

First let me fix VFA.

```
PS E:\TheoremProving\vfa\vfa> make Perm.vo
coq_makefile -Q . VFA OTHERFLAGS = '-Q . VFA ' COQLIBS = '' -install none Maps.v Preface.v Perm.v Sort.v Multiset.v Selection.v SearchTree.v ADT.v Extract.v Redblack.v Trie.v Priqueue.v Binom.v Decide.v Color.v MapsTest.v PrefaceTest.v PermTest.v SortTest.v MultisetTest.v SelectionTest.v SearchTreeTest.v ADTTest.v ExtractTest.v RedblackTest.v TrieTest.v PriqueueTest.v BinomTest.v DecideTest.v ColorTest.v -o Makefile
```

I hadn't realized, but conf file only gets generated when I run the makefile.

10:45am. This just gets more and more confusing. When I run the above by hand I cannot get it to work for some reason. Also, I am trying a `_CoqProject` with two files and it is failing me. I should have put in more effort doing it experimentally instead of messing around with the `make` manual.

There are too many questions to deal with the comments right now. I am going to open an issue on the Coq repo.

11:15am. Forget this. Let me see if I can compile Coquelicot.

...The `coq_makefile` is as useless as usual here. The files are all there in the `theories` directory.

11:45am.

```
-R theories Coquelicot
theories/AutoDerive.v
theories/BacS.v
theories/Compactness.v
theories/Complex.v
theories/Continuity.v
theories/Coquelicot.v
theories/Derive.v
theories/Derive_d.v
theories/ElemFct.v
theories/Equiv.v
theories/Hierarchy.v
theories/Iter.v
theories/KHInt.v
theories/Lim_seq.v
theories/Lub.v
theories/Markov.v
theories/PSeries.v
theories/Rbar.v
theories/Rcomplements.v
theories/RInt.v
theories/RInt_analysis.v
theories/RInt_gen.v
theories/Seq_fct.v
theories/Series.v
theories/SF_seq.v
```

Got some advice and now I can get things to compile properly.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-6

Get-ChildItem -Path C:\Test -Name

Agh, I could have just done this rather than use regex to filter everything. Well it is fine. Let me give this a try.

12pm.

```
make[1]: *** [makefile:663: theories/Seq_fct.vo] Error 1
make: *** [makefile:327: all] Error 2
PS E:\TheoremProving\coquelicot-3.0.3> coq_makefile -f _CoqProject -o makefile; make
COQC theories/Series.v
COQC theories/Seq_fct.v
File ".\theories/Seq_fct.v", line 366, characters 8-17:
Error: The reference is_derive was not found in the current environment.

make[1]: *** [makefile:663: theories/Seq_fct.vo] Error 1
make: *** [makefile:327: all] Error 2
```

Right now I am playing whack a more with reordering the files by hand. Coq's package management quite frankly sucks massive balls.

Now I have a missing reference. It does not seem like I am going to be able to compile this.

```
Version 3.0.3
-------------

* ensured compatibility from Coq 8.8 to Coq 8.10

Version 3.0.2
-------------

* ensured compatibility from Coq 8.5 to Coq 8.9
```

Hmmmm...Let me try getting version 3.0.2.

`Download this release as ZIP`. Inside the `zip` is the `tar.gz` file. Yeah, wonderful.

I am getting a stomach ache. I'll resume this later."