"9:50am. Let me finish chilling and then I will start.
10:10am. Let me start. I need to focus.

I set out to carve out my own path, and I am going to accept all that comes with it. By the end of next week I will know where I stand with respect with Spiral. Most likely the feedback will be poor.

Ideally, I'd have had a good time with everyone seeing the advantages of Spiral right away. That would have been my golden ticket to a brighter timeline.

To make the annoyance of actually reaching out to sponsors even remotely worth it, the path should be smooth. I should not have to think especially hard how to convince them of its benefits. But that way of thinking is just naive. Even though the benefits of having sponsors are so mediocre to the alternative.

The demonic path beckons to me.

I cannot rely on humans. I must draw out the power of the machines and make it my own. I should slaughter and pilage to get my resources.

10:20am. This world is unfair. It would be so much better for everyone around if I could get benefits from Spiral based on its technical merits. But even though my skills are such a perfect fit for supporting the efforts of these hardware companies, I can already see the future where nothing comes from that.

I made that ML library in 2018 for nothing.

In the end, I'll get my benefits from being able to make UIs and concurrency.

10:25am.

```
inl children l c =
    inl len = listm.length l
    inl in_front = a64.init len (fun _ => 0)
    inl prev_widget = a64.init len (fun _ => None)
    inl disp = disposablem.composite.create()
    listm.fold (fun i x =>
        inl subs = subscribe x fun x =>
            match a64.index prev_widget i with
            | None => loop.forDown' (nearFrom: i to: 0) (fun i => a64.set in_front i (a64.index in_front i + 1))
            | Some: x => removeWidget x c
            addWidget x (a64.index in_front i) c
            a64.set prev_widget i (Some: x)
        disposablem.composite.add disp subs
        i+1
        ) 0 l
    |> fun _ => Some: toDisposable disp
```

10:30am. Doing a bit of cleaning and optimization.

...I really am scared of reverse UIs. Teaching agents poker will be a piece of cake in contrast to teaching them how to interact with the world. I am going to have to draw out all my programming skill to deal with this.

But if I could just deal with this I will be able to do anything.

10:30am. Right now, I could be considered an expert programmer in terms of skill, but I not...a what? A true AI practitioner? A true seeker of the Singularity?

I must go further. There is a level beyond the one I am currently. I am still too green to get what I want.

Until I reach that level, this journal which is my inheritance will continue.

At some point I will reach the threeshold of skill and make my passage into the shadows, but until then I might as well continue being a fool.

10:35am. What bothers me the most right now?

The fact that moving and deleting files is so messed up in Spiral! It is like having a bunch of garbage backing up the front porch. I can't stand it.

Damn it. Once I manage to finish DREAM and agent training has started on NL Holdem, I am going to make some time, even a whole month if need be to iron the kinks out.

Right now, I did a really good thing with those streams, but the very top level is such a mess.

I am sending those errors to the server in a mutable fashion, I keep stale data around, I do the deletions directly. Some of the memoization optimizations are working against me...

This just cannot stand. Even though I spent so much time working on this, I clearly haven't done it properly yet.

10:45am. I did it for the sake of the ML library, but it really is such a joy to work on a language. After tasting bitter limitation in 2016, Spiral is giving me so much freedom right now.

But if I want to gain benefits from that, I am going to have to keep working at it.

...

Let me focus on the task at hand.

Before I can make my first UI, I need to put something else into the library. For buttons, I should do the event handler.

```
        def f(args):
            args.text = "X"
            label.text = "The button has been pressed."
        btn.fbind("on_press",f)
```

Let me try out `fbind`.

```
btn.fbind("on_press",f)
```

Yes, this works. Ok.

```
open rx
prototype on_press m : (() -> ()) -> m -> disposable
```

Let me make the prototype this. I'll ignore the first argument which is just the control itself.

How do I create observables from a callback?

```
q = rx.disposable.disposable.Disposable(lambda *x: print("qwe"))
x = rx.disposable.serialdisposable.SerialDisposable()
x.disposable = q
x.disposable = q
x.disposable = q
x.disposable = q
```

This gets disposed once. Ok, I see.

```
// Creates a disposable.
inl create (f : () -> ()) : disposable = $"rx.disposable.disposable.Disposable(!f)"
```

This should do nicely.

https://kivy.org/doc/stable/api-kivy.event.html#kivy.event.EventDispatcher.unbind_uid

Actually instead of assuming the uid is u64, I should just leave it as an object.

11:15am.

```
inl bind_zero (event_name : string) (f : () -> ()) x =
    inl uid : obj = $"!x.fbind(!event_name,lambda x: !f())"
    disposablem.create fun () => $"!x.unbind_uid(!event_name,!uid)"
```

Made this helper. Ok...

```
instance on_press button = helpers.bind_zero "on_press"
```

Let me move them in their own module.

For now just being able to respond to button presses is enough.

11:20am. Focus me. What comes next?

...Besides realizing it is the end of the month, so I should download High Rise Invasion to spent a bit of my budget?

Let me make a lithe test file. It is too early to run anything, but I should be able to write out a simple UI and see if the types match. That is what I should do here.

```
-(orientation Vertical)
```

Whops, I got the - wrong.

```
inl (~-) f x c = f x c . None
inl (~+) f x c = Some: subscribe x (fun x => f x c)
inl (~@) f x c = Some: (f x c : disposable)
inl (~#) f x c =
```

This is how I should have done it.

Ok...

```
        children [

            ]
```

Ah, crap. I should have allowed empty lists.

```fs
let sequence_body d = (many1 (indent (col d) (=) (sepBy1 operators (skip_op ";"))) |>> List.concat) d
```

Let me remove that outer `remove1`.

Yeah, that should do it.

This is worth a patch.

```
open kivy
open lithe
inl UI =
    boxlayout [
        -orientation Vertical
        children [
            label [-text "Press the button."]
            button [
                -text "Press me."
                @on_press (fun () => $"print(\"The button has been pressed.\")")
                ]
            ]
        ]
```

This actually matches. It compiles down to an `() -> observable widget`.

Why don't I run it? I need to make an app, set the root and run this.

```
inl main () =
    inl app = appm.create()
    inl _ = rx.subscribe UI (appm.root app)
    appm.run app
```

This seems good.

Let me give it a try.

```
        v1 = kivy.uix.label.Label()
        v2 = rx.disposable.compositedisposable.CompositeDisposable()
            ^
------------------------------------------------------------

c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\rx1\lithe_test.pyx:13:13: undeclared name not builtin: rx
```

Keeping track of imports sure is annoying.

```
Error compiling Cython file:
------------------------------------------------------------
...
        v1 = kivy.uix.button.Button()
        v2 = rx.disposable.compositedisposable.CompositeDisposable()
        v1.text = "Press me."
        v3 = Closure2()
        v4 = v1.fbind("on_press",lambda x: v3())
        del v3
           ^
------------------------------------------------------------

c:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\rx1\lithe_test.pyx:48:12: can not delete variable 'v3' referenced in nested scope
```

You son of a bitch.

I am talking to the Cython compiler.

```
open rx
inl bind_zero (event_name : string) (f : () -> ()) x =
    inl f (x : obj) = f ()
    inl uid : obj = $"!x.fbind(!event_name,!f)"
    disposablem.create fun () => $"!x.unbind_uid(!event_name,!uid)"
```

Let me try this for the time being.

```
def __call__(self, object v2):
```

It is telling me that this takes a single argument.

11:55am. Mhhh, no there is something wrong. This v2 is the `observer`. Maybe it should also take in the scheduler?

```
 AttributeError: module 'kivy.uix' has no attribute 'boxlayout'
```

Ah, the problem was in subscribe. I need to pass it the optional arg as well.

But how will I get around the problem of the Cython lambdas being broken?

12pm.

```
inl create forall a. (f : observer a -> disposable) : observable a = $"rx.create(!f)"
```

Actually, I meant to say create. This is not working for me. I am going to have to put in var args into the language.

```
def qwe(* a) : pass
```

Thankfully this is valid syntax.

```
inl create forall a. (f : observer a -> disposable) : observable a = inl f (x : tuple) = f $"!x[0]" in $"rx.create(!f)"
```

Let me do it like this.

12:10pm. Wonderful.

The UI shows up! And the solution I have now is more efficient that partially applying closures. Hopefully I won't run into functions that require callbacks which have both tuple and dict arguments. That would suck."