"8:20am. Tonight was hell. I spent all night thinking about how to do row polymorphism only to realize that my rules were all unsound. Row polymorphism is out. It is too hard to do.
Damn, I am tired today. I am going to have to take it easy today. I barely got any rest.

Now I am thinking about typeclasses and they are the ones giving me trouble now. Uf.

Let me check out those threads from yesterday.

8:30am. I think my idea to just go with Emacs for Cygwin has merit. Though somebody did give me a Linux VM image in the Reddit thread.

The SO answer just suggests what I saw in that other answer, which is to install `chere` and add the shell open to the right click context menu. I upvoted it as some effort went into the answer, still, this is not the kind of answer that satisfies me. It does not really connect with what I am asking. I won't accept it.

8:35am. I really am exhausted. What was I supposed to be doing today? Investigating the Reason plugin I think.

8:40am. Ugh, let me just clone the repo.

https://github.com/jaredly/reason-language-server

I mean this.

8:45am. Wow, it is 157mb at only 50%. What is in that thing?

8:50am. I need some downtime today. I'll try to put a few hours into this, but otherwise I think I'll just slack.

9:30am. Let me do just a bit.

```
  "scripts": {
    "cp-test":
      "cp #{self.target_dir}/install/default/bin/RunTests.exe RunTests.exe",
    "package":
      "esy build && esy cp \"#{self.target_dir}/default/bin/Bin.exe\" editor-extensions/vscode/bin.native",
    "zip": "./release.sh",
    "check-self-definitions":
      "fd -E examples '.*\\.re$' | xargs ./bin.exe check -q -d .",
    "vsce": "cd editor-extensions/vscode && vsce package",
    "reprocess-ocaml": "(cd process_ocaml; ./build.sh); esy",
    "symlink":
      "esy ln -s '#{self.target_dir}/install/default/bin/Bin' bin.exe",
    "cp-bin": "cp #{self.target_dir}/install/default/bin/Bin bin.exe"
  },
```

I don't get this stuff at all.

All of these seems to be Linux commands. But what are the entry points?

Also typechecking does not work for me with this.

```
Reason Language Server not found! You specified e:\Webdev\Ocaml\reason-language-server\bin.exe
```

Ah, now that I am opening the project again I see this.

Is it possible to compile the project on Windows?

```
- Install `esy` if you don't have it (`npm install -g esy`)
- Clone this repo
- `cd` to the cloned dir
- Run `esy` from the main project dir
- Run `esy symlink` to link the built artifact into the root folder at `bin.exe`
- Install the VS Code extension's dependencies `cd editor-extensions/vscode && npm i && cd ../..`
- Open this project in VS Code
```

I guess I'll try.

Let me go for this. I guess I'll spend another few Gbs.

9:50am. The thing is still installing. As can be expected, the inefficiency when things get large becomes exponential.

One thing I really have to do is take a look at the module chapter again. I haven't quite gotten the module and the object material.

```
e:\Webdev\Ocaml\reason-language-server>npm install -g esy
C:\Users\Marko\AppData\Roaming\npm\esy -> C:\Users\Marko\AppData\Roaming\npm\node_modules\esy\_build\default\bin\esy.exe

> esy-solve-cudf@0.1.10 postinstall C:\Users\Marko\AppData\Roaming\npm\node_modules\esy\node_modules\esy-solve-cudf
> node ./postinstall.js

> esy@0.6.2 postinstall C:\Users\Marko\AppData\Roaming\npm\node_modules\esy
> node ./postinstall.js

Installing native compiler toolchain for Windows...
Native compiler toolchain installed successfully.
+ esy@0.6.2
added 2 packages in 533.072s
```

It took 9m, but it is finally done.

Let me run `esy`.

https://www.youtube.com/watch?v=7HkXVyYQ8ss
React Chicago Feb 2020 - "TypeScript vs. ReasonML - When Sh*t Gets Real" by Peter Piekarczyk

While this is going on, I'll listen to this in the background. Let me take a look at the modules again here.

One thing I do not get - I've been thinking about arrays.

Since comparable module is something like.

```
module type Compare =
    type t;
    compare : t -> t -> Ordering
```

Then you'd include this in the array.

But array would be...

```
module type Array =
    type t x = Array x;
```

This is what I could not get during the night. The type signature for array should be a function.

Am I doing this wrong. Can a module also have a type argument?

The module signature for array should definitely have a type argument.

```
module type Array x =
    type t = Array x;
```

Something like this then? Yeah, I've never used them so I've completely forgotten the Reason syntax from yesterday. I pretty much just blazed through it.

10:05am. https://reasonml.github.io/docs/en/module

Ah, I see.

There is something that is bothering me. I've been thinking about typeclasses during the night, but I am really uncomfortable with them after all. Things like orphan instances, and having to do layers of unification and whatnot.

The thing is, unlike Haskell, I actually do not need them for ad-hoc polymorphism. The bottom-up Spiral thing that I am doing already covers that. So if I could get extensibility without necessarily having to deal without having to pass a global dictionary around that would be great.

10:15am. So much trouble. Typeclasses are really causing me issues, but...

```
e:\Webdev\Ocaml\reason-language-server>esy
info esy 0.6.2 (using package.json)
info fetching: done
error command failed: "tar" "xf" "/cygdrive/e/Webdev/Ocaml/reason-language-server/_esy/default/dist/f34f64b259f0f67c9f07cb2331f9cbf8" "-C" "/cygdrive/c/Users/Marko/AppData/Local/Temp/esy-9cf9ef"
      stderr:
               tar: ocamlbuild-0.14.0/examples/07-dependent-projects/libdemo: Cannot create symlink to '../04-library/libdemo': Operation not permitted
               tar: Exiting with failure status due to previous errors

      stdout:

error: error running command
  unpacking @opam/ocamlbuild@opam:0.14.0
  installing @opam/ocamlbuild@opam:0.14.0
esy: exiting due to errors above
```

Now the install is failing for me here as well. I'll open an issue.

10:20am.

```
               tar: ocamlbuild-0.14.0/examples/07-dependent-projects/libdemo: Cannot create symlink to '../04-library/libdemo': Operation not permitted
```

Hmmm...Maybe I need to run `cmd` as admin?

https://superuser.com/questions/42537/is-there-any-sudo-command-for-windows/269750

10:30am.

```
PS E:\Webdev\Ocaml\reason-language-server> esy
esy : File C:\Users\Marko\AppData\Roaming\npm\esy.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ esy
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

Holy shit, this is so annoying! When I try to use runass to run cmd as admin it complains about empty passwords not being allowed.

10:30am. https://tecadmin.net/powershell-running-scripts-is-disabled-system/

Changing the execution policy to remote worked for me.

10:40am.

```
PS E:\Webdev\Ocaml\reason-language-server> esy
info esy 0.6.2 (using package.json)
info fetching: done
info installing: done
info building @esy-ocaml/substs@0.0.1@d41d8cd9
info building ocaml@4.8.1000@d41d8cd9
info building @esy-ocaml/substs@0.0.1@d41d8cd9: done
info building @opam/base-threads@opam:base@36803084
info building @opam/base-unix@opam:base@87d0b2eb
info building @opam/conf-m4@opam:1@3b2b148a
info building @opam/base-threads@opam:base@36803084: done
info building @opam/base-unix@opam:base@87d0b2eb: done
info building @opam/conf-m4@opam:1@3b2b148a: done
```

It feels like it is stuck here for a while. Is it doing anything. Well, I'll let it run for a while.

I've gotten sidetracked.

https://reasonml.github.io/docs/en/object

Let me study objects again.

10:50am. Oh, the `esy` run finished.

```
- Install `esy` if you don't have it (`npm install -g esy`)
- Clone this repo
- `cd` to the cloned dir
- Run `esy` from the main project dir
- Run `esy symlink` to link the built artifact into the root folder at `bin.exe`
- Install the VS Code extension's dependencies `cd editor-extensions/vscode && npm i && cd ../..`
- Open this project in VS Code
```

Now comes `esy symlink`.

10:55am.

```
PS E:\Webdev\Ocaml\reason-language-server> cd editor-extensions/vscode
PS E:\Webdev\Ocaml\reason-language-server\editor-extensions\vscode> npm i

> reason-vscode@1.7.8 postinstall E:\Webdev\Ocaml\reason-language-server\editor-extensions\vscode
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.22.0
Found minimal version that qualifies engine range: 1.22.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/6b4d53cdab8bcae1eaaa4934d93c077319b573db/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

added 298 packages from 470 contributors and audited 915 packages in 20.206s
found 24 vulnerabilities (10 low, 7 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS E:\Webdev\Ocaml\reason-language-server\editor-extensions\vscode>
```

With this I am done. Let me see if I can get some typechecking for the project now.

```
Couldn't start client Reason Language Server
```

Figures. What do I need to do now?

I guess, I'll ask the author.

11:15am. Opened an issue.

Right now, I feel obsessed about typeclasses.

I am really strongly leaning towards associating interfaces with nominal types instead. Something less flexible than typeclasses that would be easier to implement in the context of the rest of the language. Something that is not open ended. Something that does not have me make custom restriction code, but it is designed that way from the start.

11:20am. Typeclass functions can really do anything, but for the sake of my sanity, I'd much prefer if the first argument fully determines the typeclass instance.

11:25am. Yeah, this is right. The OO way of doing things is right for once. Having arbitrary global dictionaries is insane design.

I know that probably there are restrictions tacked on, but doesn't it make more sense to take a measured approach to begin with. Even with just interfaces, one can still have monads and applicatives if that is what id wanted.

I am just thinking about this, and it does not make sense.

The main difference from passing regular functions in a record which is a viable, if less efficient approach - is that the interfaces will be associated with the type rather than the value, meaning the join point specialization will not have to take special note of it.

12:10pm. Wow, this is absolutely killing me. I decided on interfaces - and this is very similar to the approach F# took, but now I realize that I have to account for interface constraints in that case! Another thing that would add significantly to the complexity of the language.

I think that for my initial foray, I should just ignore interface constraints. I have enough on my plate with everything else.

Like, everything would work even without constraints, it is just that I would get error at partial evaluation time.

12:20pm. I am dying here. Nothing is going the way I want. I had very simple ideas for how constraints should work and this is sending it all to hell.

I am going to have breakfast now, but let me do a little review.

If I weren't tired like a donkey, what would I be doing next? Studying VS Code specific events.

I've decided to deal away with `vscode-languageserver-node` and write my own client parts in Reason. I very sure that I should be able to bypass it and get various events from the editor itself. If I am really honest about this, that is what I should focus on.

For over a month now, I've been stuck in this morass of complexity, making very little progress. I really want to get going. I am going to put effort until I break through.

12:30pm. I am going to change my focus to this. Until I get a reply, I'll go back to Typescript and studying the `vscode-languageserver-node` project. That thing is the devil."