"9:45am. I am up. Let me chill a bit and then I will start.
9:50am. It is the resume day.

Tonight was not that good, but I will manage.

https://www.reddit.com/r/haskell/comments/l95mb6/edward_kmett_cadenza_building_fast_functional/

Maybe I will give this talk a watch first. Let me finish my morning reading first though.

10:35am. Holy shit, how long is this article going to go on for. Thankfully I am near to the end.

10:45am. Forget the talk by Kmett. Let me change the Numpy arrays to the Cython memory views.

```
let numpy_ty = function
    | YPrim Int8T -> "numpy.int8"
    | YPrim Int16T -> "numpy.int16"
    | YPrim Int32T -> "numpy.int32"
    | YPrim Int64T -> "numpy.int64"
    | YPrim UInt8T -> "numpy.uint8"
    | YPrim UInt16T -> "numpy.uint16"
    | YPrim UInt32T -> "numpy.uint32"
    | YPrim UInt64T -> "numpy.uint64"
    | YPrim Float32T -> "numpy.float32"
    | YPrim Float64T -> "numpy.float64"
    | _ -> "object"
```

Let me take this out.

11:05am.

```fs
        | TyArrayCreate(a,b) ->
            let format =
                match a with
                | YPrim Int8T -> 'b' | YPrim Int16T -> 'h' | YPrim Int32T -> 'l' | YPrim Int64T -> 'q'
                | YPrim UInt8T -> 'B' | YPrim UInt16T -> 'H' | YPrim UInt32T -> 'L' | YPrim UInt64T -> 'Q'
                | YPrim Float32T -> 'f' | YPrim Float64T -> 'd'
                | YPrim BoolT -> 'b'
                | _ -> 'O'
            let sizeof =
                match a with
                | YPrim Int8T -> "signed char" | YPrim Int16T -> "signed short" | YPrim Int32T -> "signed long" | YPrim Int64T -> "signed long long"
                | YPrim UInt8T -> "unsigned char" | YPrim UInt16T -> "unsigned short" | YPrim UInt32T -> "unsigned long" | YPrim UInt64T -> "unsigned long long"
                | YPrim Float32T -> "float" | YPrim Float64T -> "double"
                | YPrim BoolT -> "char"
                | _ -> "void *"
            return' $"cython.view.array(shape=({tup b}), itemsize=sizeof({sizeof}), format='{format}')"
```

This is even more of a pain in the ass than the numpy arrays, but I will roll with it.

```fs
| YArray a -> let a = match tup_ty a with "void" -> "object" | x -> x in $"{a} [:]"
```

How about I just disallow the void arrays?

```fs
        | YArray a ->
            match tup_ty a with
            | "void" -> raise_codegen_error "Void arrays are not allowed."
            | x -> $"{x} [:]"
```

I might as well make this behavior consistent with macros. Things will be cleaner like this.

Let me give it a try.

```fs
| x -> $"{x} [::1]"
```

Whops, let me make them contiguous.

```fs
v0 = cython.view.array(shape=(10), itemsize=sizeof(signed long), format='l')
```

The shape is not right.

```fs
cimport "cython"
```

Forgot the import.

```
inl main() =
    inl x : array (i32  * f64) = arraym.create 10
    ()
```
```
cimport cython
cdef class Tuple0:
    cdef readonly signed long v0
    cdef readonly double v1
    def __init__(self, signed long v0, double v1): self.v0 = v0; self.v1 = v1
cpdef void main():
    cdef Tuple0 [::1] v0
    v0 = cython.view.array(shape=(10,), itemsize=sizeof(void *), format='O')
```

Oh this works. Nice.

11:25am.

```
C:\Users\Marko\.pyxbld\temp.win-amd64-3.8\Release\pyrex\testm.c(2587): warning C4133: '=': incompatible types - from 'PyObject *' to '__pyx_obj_5testm_Tuple0 *'
```

I do get a warning that the type are incompatible. How should I deal with this?

...This should be a compiler error on the Cython end.

11:35am. Opened an issue.

Let me publish a patch. I've broken the dependency on Numpy arrays in favor on native Cython ones.

11:40am. Let me watch the talk by Kmett now.

https://www.youtube.com/watch?v=25RmUl88jSw&feature=youtu.be
YOW! Lambda Jam 2020 - Edward Kmett - Cadenza Building Fast Functional Languages Fast

It was posted on the PL sub.

11:55am. I am not in the mood for it after all. Maybe I'll watch it later. Let me take a break here. After that I'll get started on the resume."