"9:55am. I slept well. Let me start the experiment.
10:10am.

```log
07/19/2021 10:05:11 AM The mean is -0.1307082507701125 for the regular player.
07/19/2021 10:05:58 AM The mean is -0.0697053056974255 for the average player.
07/19/2021 10:06:50 AM The mean is -0.20168018857657444 for the regular player.
07/19/2021 10:07:37 AM The mean is -0.10617395222652704 for the average player.
07/19/2021 10:08:23 AM The mean is -0.13354286714820773 for the regular player.
07/19/2021 10:09:10 AM The mean is -0.09676724790188018 for the average player.
```

Such a superb run.

```log
07/19/2021 10:16:48 AM The mean is -0.1659561536325782 for the regular player.
07/19/2021 10:17:35 AM The mean is -0.11185419043613365 for the average player.
07/19/2021 10:18:27 AM The mean is -0.21185980896552792 for the regular player.
07/19/2021 10:19:14 AM The mean is -0.08440509686261066 for the average player.
07/19/2021 10:20:05 AM The mean is -0.14525638679333497 for the regular player.
07/19/2021 10:20:56 AM The mean is -0.0891815080140077 for the average player.
```

Yeah it is very good. Using these kinds of transformers is totally justifiable. Apparently, the top layer loves those multi-head inputs.

```log
07/19/2021 10:27:47 AM The mean is -0.15090830152621493 for the regular player.
07/19/2021 10:28:33 AM The mean is -0.08141987882117974 for the average player.
07/19/2021 10:29:23 AM The mean is -0.23013438137422781 for the regular player.
07/19/2021 10:30:09 AM The mean is -0.10444705067493487 for the average player.
07/19/2021 10:30:57 AM The mean is -0.1334090082164039 for the regular player.
07/19/2021 10:31:43 AM The mean is -0.10043967283490929 for the average player.
```

10:40am. It is decided. I'll go with this. The top encoder layer does not need residual connections.

```py
class ResTopEncoderBase(TopEncoderBase):
    def __init__(self,dim_head=2 ** 3,dim_emb=2 ** 5):
        super().__init__(dim_head*dim_emb,dim_head,dim_emb)

    def forward(self,x,rotary,mask=None):
        return x[:,0] + super().forward(x,rotary,mask)
```

Let me get rid of this.

```py
    def forward(self,x,rotary,mask=None) -> Tensor:
        dz,dk,_ = x.shape; dh,de = self.dim_head,self.dim_emb
        kv : Tensor = self.proj_kv(x).view(dz,dk,2,dh,de)
        q,k,v = self.proj_q(x[:,0]).view(dz,dh,de), rotary(kv[:,:,0]), normed_square(kv[:,:,1])
        seq_weights : Tensor = torch.einsum('zhe,zkhe->zkh',q,k)
        if mask is not None:
            seq_weights = seq_weights.masked_fill(mask.view(dz,dk,1),0.0)
        return normed(torch.einsum('zkh,zkhe->zhe',normed_square(seq_weights,-2),v).reshape(dz,dh*de))
```

I'll also add normed in the `TopEncoderBase`'s forward.

```log
07/19/2021 10:38:53 AM The mean is -0.1678351265945821 for the regular player.
07/19/2021 10:39:40 AM The mean is -0.0947806472886441 for the average player.
07/19/2021 10:40:31 AM The mean is -0.15065500931086717 for the regular player.
07/19/2021 10:41:19 AM The mean is -0.11726291807644884 for the average player.
07/19/2021 10:42:09 AM The mean is -0.12932024455221836 for the regular player.
07/19/2021 10:43:00 AM The mean is -0.11340164704233757 for the average player.
```

Only one more iteration left.

```py
    def __init__(self,depth,dim_head=2 ** 3,dim_emb=2 ** 5,dim_in=None,dim_top_head=None):
        super().__init__()
        self.rotary = Rotary(dim_emb)
        self.initial = EncoderBase(dim_in,dim_head,dim_emb) if dim_in is not None else None
        self.layers = ModuleList([ResEncoderBase(dim_head*dim_emb,dim_head,dim_emb) for _ in range(depth)])
        self.top = TopEncoderBase(dim_head*dim_emb,dim_head if dim_top_head is None else dim_top_head,dim_emb)
```

Let me put the capacity to parameterize the top encoder layer like this. I'll need the ability to split the heads when I implement my new algorithms.

10:50am. Now that I've done this, I'll want to try running with less heads, just 1 to see if the the number of heads is really the cause of the stability.

```log
07/19/2021 10:49:58 AM The mean is -0.1332284113013884 for the regular player.
07/19/2021 10:50:47 AM The mean is -0.12635188829517574 for the average player.
07/19/2021 10:51:34 AM The mean is -0.16529508279199945 for the regular player.
07/19/2021 10:52:20 AM The mean is -0.11297138826921582 for the average player.
07/19/2021 10:53:08 AM The mean is -0.13375132074725116 for the regular player.
07/19/2021 10:53:54 AM The mean is -0.09453295477578649 for the average player.
```

Here is the last iteration. That -0.126 was the worst for this past series.

11am. Let me try only a small number of heads.

```py
def neural_create_model(size,dim_head=2 ** 0,dim_emb=2 ** 9):
    value = EncoderList(0,dim_head,dim_emb,size.value)
    value_head = Head(dim_head*dim_emb,size.action)
    policy = EncoderList(0,dim_head,dim_emb,size.policy)
    policy_head = Linear(dim_head*dim_emb,size.action)
    return value.cuda(), value_head.cuda(), policy.cuda(), policy_head.cuda()
```

Like this.

```log
07/19/2021 11:07:05 AM The mean is -0.17588924454867083 for the regular player.
07/19/2021 11:07:47 AM The mean is -0.2041282369173132 for the average player.
```

Indeed, the smaller number of heads is making trouble for the optimizer.

```log
07/19/2021 11:07:05 AM The mean is -0.17588924454867083 for the regular player.
07/19/2021 11:07:47 AM The mean is -0.2041282369173132 for the average player.
07/19/2021 11:08:34 AM The mean is -0.3656536839698674 for the regular player.
07/19/2021 11:09:18 AM The mean is -0.2256569597084308 for the average player.
07/19/2021 11:10:02 AM The mean is -0.2337080656652688 for the regular player.
07/19/2021 11:10:46 AM The mean is -0.15209805902122753 for the average player.
```

This is enough to sate my curiosity. Let me go in the other direction. I'll increase the number of heads.

```py
def neural_create_model(size,dim_head=2 ** 4,dim_emb=2 ** 5):
```

This is what it was before.

```py
def neural_create_model(size,dim_head=2 ** 6,dim_emb=2 ** 4):
```

I'll decrease the emb size by 2x and the number of heads by 4x. That will result in a layer that is 2x bigger than before.

11:25am.

```log
07/19/2021 11:01:45 AM Training the NN agent.
07/19/2021 11:03:32 AM Averaging the NN agent.
07/19/2021 11:04:27 AM Averaging the NN agent.
07/19/2021 11:05:23 AM Averaging the NN agent.
07/19/2021 11:07:05 AM The mean is -0.17588924454867083 for the regular player.
```

```log
07/19/2021 11:12:41 AM Training the NN agent.
07/19/2021 11:18:07 AM Averaging the NN agent.
07/19/2021 11:20:44 AM Averaging the NN agent.
07/19/2021 11:23:28 AM Averaging the NN agent.
07/19/2021 11:27:18 AM The mean is -0.2678812003323401 for the regular player.
```

Having more heads really spikes the training times. I wonder why that is. I bet PyTorch is inefficient at doing the traversals.

Well, I'll let it run for an iteration or two. I suppose for real runs 16 heads will be fine.

Now let me get back to Kenja and Mahoako. I like this comfy way of working where I wait on the computer to do its own thing. After this experiment finishes I will focus on integrating the latest changes into the other project. Then I will get to work on my algorithm idea.

11:45am. It is really slow as a molass now. 30m went by and it is only in the middle of the second iteration.

```log
07/19/2021 11:12:40 AM ** TRAINING START **
07/19/2021 11:12:41 AM Training the NN agent.
07/19/2021 11:18:07 AM Averaging the NN agent.
07/19/2021 11:20:44 AM Averaging the NN agent.
07/19/2021 11:23:28 AM Averaging the NN agent.
07/19/2021 11:27:18 AM The mean is -0.2678812003323401 for the regular player.
07/19/2021 11:28:24 AM The mean is -0.10435628581763012 for the average player.
07/19/2021 11:29:51 AM The mean is -0.3255828883338836 for the regular player.
07/19/2021 11:30:57 AM The mean is -0.08798332577134715 for the average player.
07/19/2021 11:32:04 AM The mean is -0.08719831093185348 for the regular player.
07/19/2021 11:33:13 AM The mean is -0.07830802772514289 for the average player.
07/19/2021 11:33:13 AM ----
07/19/2021 11:33:13 AM Training the NN agent.
07/19/2021 11:39:02 AM Averaging the NN agent.
07/19/2021 11:41:51 AM Averaging the NN agent.
07/19/2021 11:44:37 AM Averaging the NN agent.
07/19/2021 11:48:21 AM The mean is -0.24750967288491665 for the regular player.
07/19/2021 11:49:22 AM The mean is -0.26013548079208704 for the average player.
```

How horrible. I guess lowering the emb size was ill advised. at any rate, it should take it only 6m to eval. For some reason the training is much slower.

12pm. Let me get breakfast. I want to let the run finish.

1pm.

```log
07/19/2021 11:12:40 AM ** TRAINING START **
07/19/2021 11:12:41 AM Training the NN agent.
07/19/2021 11:18:07 AM Averaging the NN agent.
07/19/2021 11:20:44 AM Averaging the NN agent.
07/19/2021 11:23:28 AM Averaging the NN agent.
07/19/2021 11:27:18 AM The mean is -0.2678812003323401 for the regular player.
07/19/2021 11:28:24 AM The mean is -0.10435628581763012 for the average player.
07/19/2021 11:29:51 AM The mean is -0.3255828883338836 for the regular player.
07/19/2021 11:30:57 AM The mean is -0.08798332577134715 for the average player.
07/19/2021 11:32:04 AM The mean is -0.08719831093185348 for the regular player.
07/19/2021 11:33:13 AM The mean is -0.07830802772514289 for the average player.
07/19/2021 11:33:13 AM ----
07/19/2021 11:33:13 AM Training the NN agent.
07/19/2021 11:39:02 AM Averaging the NN agent.
07/19/2021 11:41:51 AM Averaging the NN agent.
07/19/2021 11:44:37 AM Averaging the NN agent.
07/19/2021 11:48:21 AM The mean is -0.24750967288491665 for the regular player.
07/19/2021 11:49:22 AM The mean is -0.26013548079208704 for the average player.
07/19/2021 11:50:31 AM The mean is -0.13349107989051845 for the regular player.
07/19/2021 11:51:36 AM The mean is -0.09113763844288769 for the average player.
07/19/2021 11:52:56 AM The mean is -0.16546300572372274 for the regular player.
07/19/2021 11:54:01 AM The mean is -0.0972946205874905 for the average player.
07/19/2021 11:54:01 AM ----
07/19/2021 11:54:01 AM Training the NN agent.
07/19/2021 11:59:28 AM Averaging the NN agent.
07/19/2021 12:02:01 PM Averaging the NN agent.
07/19/2021 12:04:38 PM Averaging the NN agent.
07/19/2021 12:08:18 PM The mean is -0.18860293045872822 for the regular player.
07/19/2021 12:09:22 PM The mean is -0.12116955403325846 for the average player.
07/19/2021 12:10:25 PM The mean is -0.1271784311538795 for the regular player.
07/19/2021 12:11:29 PM The mean is -0.10206932819710346 for the average player.
07/19/2021 12:12:33 PM The mean is -0.12370543945871759 for the regular player.
07/19/2021 12:13:35 PM The mean is -0.08495809838495916 for the average player.
07/19/2021 12:13:35 PM ----
07/19/2021 12:13:35 PM Training the NN agent.
07/19/2021 12:18:40 PM Averaging the NN agent.
07/19/2021 12:21:23 PM Averaging the NN agent.
07/19/2021 12:24:04 PM Averaging the NN agent.
07/19/2021 12:27:58 PM The mean is -0.17824836867657723 for the regular player.
07/19/2021 12:29:11 PM The mean is -0.12538856088212924 for the average player.
07/19/2021 12:30:21 PM The mean is -0.159097345022019 for the regular player.
07/19/2021 12:31:37 PM The mean is -0.1338688284085947 for the average player.
07/19/2021 12:32:55 PM The mean is -0.1556541563841165 for the regular player.
07/19/2021 12:34:04 PM The mean is -0.09447115289003705 for the average player.
07/19/2021 12:34:04 PM ----
07/19/2021 12:34:04 PM Training the NN agent.
07/19/2021 12:39:20 PM Averaging the NN agent.
07/19/2021 12:41:55 PM Averaging the NN agent.
07/19/2021 12:44:34 PM Averaging the NN agent.
07/19/2021 12:48:16 PM The mean is -0.0860828839140595 for the regular player.
07/19/2021 12:49:20 PM The mean is -0.09937926850761869 for the average player.
07/19/2021 12:50:29 PM The mean is -0.244616325275274 for the regular player.
07/19/2021 12:51:34 PM The mean is -0.08447687185616815 for the average player.
07/19/2021 12:52:40 PM The mean is -0.1669965145883907 for the regular player.
07/19/2021 12:53:47 PM The mean is -0.08957971092968364 for the average player.
07/19/2021 12:53:47 PM ----
07/19/2021 12:53:47 PM ** TRAINING DONE **
```

Done with breakfast. This does give me some insight into how all this works. If I want the best kind of performance and stability, I can't sacrifice embedding size for heads. I need both.

This time, why don't I run it like...

```py
def neural_create_model(size,dim_head=2 ** 6,dim_emb=2 ** 6):
```

This will no doubt take a while. The last run took 1.5 hours. But after that I will be done. I'll move to implement SARSA and the new exploration method.

```py
    return torch.cat((-x2, x1), dim = -1)
RuntimeError: CUDA out of memory. Tried to allocate 76.00 MiB (GPU 0; 4.00 GiB total capacity; 2.72 GiB already allocated; 52.73 MiB free; 2.78 GiB reserved in total by PyTorch)
```

Not enough memory. I'll actually have to lower the batch size.

```py
def create_nn_agent(n,m,vs_self,vs_one,neural,uniform_player,tabular): # self play NN
    batch_size = 2 ** 9
    iter_batch = 2 ** 1
```

```py
    def run(is_avg=False):
        for _ in range(iter_batch):
            vs_self(batch_size,neural_player(neural,modules,True,True,True,2 ** -2))
```

Let me do it like this.

```py
    batch_size = 2 ** 8
    iter_batch = 2 ** 2
```

I still get out of memory errors. Let me try this then.

```log
07/19/2021 01:05:27 PM Training the NN agent.
```

It still did not even get to the averaging stage. It seems 2 ** 4 and 2 ** 5 combo was the ideal one.

1:25pm. Holy shit, it is still at training the NN agent stage. Ok, just one iteration.

1:35pm.

```log
07/19/2021 01:05:27 PM Training the NN agent.
07/19/2021 01:31:16 PM Averaging the NN agent.
```

Yeah, this is too long. But I'll let it run for a single iteration.

I get the sense that the backward pass is the culprit for why this is taking so long. The transformers aren't effcient with it.

2:15pm. This is just taking so long. I want the current run to finish before I start anything else. The training is so intense that it is slowing down the entire computer.

I need to run the holdem example once just to make sure the work I've done is spotless. Once that is done I'll make a commit.

2:20pm. It finally moved to eval, and the system has gone to a crawl.

```log
07/19/2021 02:15:49 PM The mean is -0.1987709956447361 for the regular player.
07/19/2021 02:22:34 PM The mean is -0.1476770271474379 for the average player.
07/19/2021 02:40:13 PM The mean is -0.183764670342498 for the regular player.
07/19/2021 02:45:39 PM The mean is -0.13676997692527948 for the average player.
```

Sigh, this is horrible. I have no idea why.

```log
07/19/2021 01:05:25 PM ** TRAINING START **
07/19/2021 01:05:27 PM Training the NN agent.
07/19/2021 01:31:16 PM Averaging the NN agent.
07/19/2021 01:44:10 PM Averaging the NN agent.
07/19/2021 01:57:39 PM Averaging the NN agent.
07/19/2021 02:15:49 PM The mean is -0.1987709956447361 for the regular player.
07/19/2021 02:22:34 PM The mean is -0.1476770271474379 for the average player.
07/19/2021 02:40:13 PM The mean is -0.183764670342498 for the regular player.
07/19/2021 02:45:39 PM The mean is -0.13676997692527948 for the average player.
07/19/2021 02:52:44 PM The mean is -0.11278871210743091 for the regular player.
07/19/2021 02:59:32 PM The mean is -0.08486282560261316 for the average player.
07/19/2021 02:59:32 PM ----
```

Well, it did end up improving to -0.08 towards the last iteration.

This was the longest single run ever. It took almost 2h for it to finish.

It seems that at 2 ** 4 and 2 ** 5, the architecture already pushes the GPU to the limit of its capacity. When I train on full Holdem it is likely I will have to lower the batch size a tad or decrease the size of the architecture to something like 2 ** 3 and 2 ** 5.

3:05pm. It would be far simpler to just train an ensemble instead of increasing the architecture size if stability was the goal.

3:10pm. But I do need a sequence model, everything else be damned. I can't go back to MLPs.

Transformers are the right choice for sequences. I'll lower the head size to 2 ** 3, pump up the depth, and make my way that way in Holdem. That reminds me, let me just run it so I can be sure there aren't any type errors. I want to leave the project in a pristine condition.

```
    self.layers = ModuleList([ResEncoderBase(dim_head*dim_emb,dim_head,dim_emb) for _ in range(depth)])
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given
```

Yes, this type error makes sense. But why did I not get it when I ran Leduc?

```py
class ResEncoderBase(EncoderBase):
    def __init__(self,dim_head=2 ** 3,dim_emb=2 ** 5):
        super().__init__(dim_head*dim_emb,dim_head,dim_emb)

    def forward(self,x,rotary,mask=None):
        return x + super().forward(x,rotary,mask)

class EncoderList(Module):
    def __init__(self,depth,dim_head=2 ** 3,dim_emb=2 ** 5,dim_in=None,dim_top_head=None):
        super().__init__()
        self.rotary = Rotary(dim_emb)
        self.initial = EncoderBase(dim_in,dim_head,dim_emb) if dim_in is not None else None
        self.layers = ModuleList([ResEncoderBase(dim_head*dim_emb,dim_head,dim_emb) for _ in range(depth)])
        self.top = TopEncoderBase(dim_head*dim_emb,dim_head if dim_top_head is None else dim_top_head,dim_emb)
```

This is insane. Why did it not warn me that I am passing in too many params into EncoderBase?

```
self.layers = ModuleList([ResEncoderBase(dim_head*dim_emb,dim_head,dim_emb,'') for _ in range(depth)])
```

I do not get an error even when I do something like this.

...Ah, right, because the range is 0. Silly me. No way will the errors here affect the training adversely.

Ok, let me let it train for a while vs the callbot. I want to see how it does by iterations 20.

3:25pm. Ok, that is good enough. It seems the depth itself does not matter too much on its own. Even with 5 extra layers that holdem requires, that is not enough to grind the system to a crawl. It is wideness that does it in. Maybe I am underestimating how harsh the longer Leduc sequences are on the GPU though. I can't forget the algorithm is n^2.

3:30pm. But if longer sequences of size over 10 are so troublesome, that would be reason to go back to MLPs. Since if 10 is high, no way am I going to train on 100.

Well, I'll see how things go. They won't be that frequent.

Let me take a break here. I might as well commit while I am at it, just like I said I would.

I need to prime my brain for the next step. Once I deal with this, I'll be able to train agents on full Holdem and my RL research adventure will come to a close.

I did a really good job at making the trasformer architecture stable on RL. I can add that to my list of accomplishments. But I do not want to fiddle with this forever. Once you know how to sort you just stick with it. The same goes for RL.

The architecture, and the algorithm I've discovered will last me for a while once I implement it. The fun parts of the journey will start soon."