"8:10am. I am up really early for some reason. I am groggy right now. Yesterday it occured to me that once I get NNST working, I could turn it into an app or a Blender plugin and sell it.
https://youtu.be/5j8I7V6blqM
NVIDIA’s New AI Grows Objects Out Of Nothing! 🤖

https://youtu.be/yl1jkmF7Xug
NVIDIA's Ray Tracing AI - This is The Next Level! 🤯

Then I watched these two. For the last one, I realized that I could try TensTorrent with an offer to make a ray tracer. I've always thought that NNs could be used to accelerate rendering, but now I see that in action for the first time successfuly. AI chips would be more suited for this than GPUs, though I do not understand rendering well enough to say if global memory is needed or if local memory will suffice. Probably the later.

8:20am. This is an element of the true path. It gives you opportunities to make money on the side. It is not like I have to rely solely on Patreon donations for Heaven's Key. Since I have strong programming and NN skills, I should use that to supplement my 3d journey.

It is far from hopeless for me, I just have to put in the effort. ML will pay off for me in the end. It is not right to expect to do everything by hand for a person like me.

8:25am. Ok, let me chill for a while. First comes Egg of the Elf.

9:10am. Let me finish ch 48 of Legendary Mechanic and I will get started. Forget the nonsense about doing a ray tracer for TensTorrent. I should just do what would benefit me directly. If I make a Blender plugin of NNST and some Youtuber covers it, I could get 100s and 1000s of sales.

9:40am. Let me get started. That was fun, but I should put some work into it. Forget patching. I realized that due to upscaling, the effective patch size would need to be larger. Still, the upscaling happens only 3 times. It is not a big deal. But what about...no, I don't get. Nevermind this. Let me go with checkpointing. I think that even with upscaling the upper levels can draw in data beyond the bounds. Patching is not the solution.

Also, rather that checkpointing, an idea came to me just now. Since I am dealing with a CNN, if I do some smart padding, I can split the image into patches and get a result equivalent to the original. This would have the advantage of allowing me to work on images of any size.

```py
# Free gpu memory in case something else needs it later
if misc.USE_GPU:
    torch.cuda.empty_cache()

```

I had no idea this was possible.

9:50am. Let go over the source for all of this.

10:05am. It sure has a lot of stuff. It is well commented I'll give it that. Regardless, this kind of undertaking is not for the faint of heart.

10:15am.

```py
    def forward(self, x_in, inds=[1, 3, 6, 8, 11, 13, 15, 22, 29], concat=True):

        x = x_in.clone()  # prevent accidentally modifying input in place
        # Preprocess input according to original imagenet training
        mean = [0.485, 0.456, 0.406]
        std = [0.229, 0.224, 0.225]
        for i in range(3):
            x[:, i:(i + 1), :, :] = (x[:, i:(i + 1), :, :] - mean[i]) / std[i]

        # Get hidden state at layers specified by 'inds'
        l2 = []
        if -1 in inds:
            l2.append(x_in)

        # Only need to run network until we get to the max depth we want outputs from
        for i in range(max(inds) + 1):
            x = self.vgg_layers[i].forward(x)
            if i in inds:
                l2.append(x)
```

I see it having 4 slices, but what are these indices?

10:25am. Let me take a break here. This is going to be a pain in the ass to get to work with checkpointing. Most likely I will have to change things, but I'll manage it somehow.

10:55am. Let me get back into it. Reading code is always a boring activity.

https://bottosson.github.io/posts/oklab/

A lot of novel stuff is in the repo.

```py
    x_norm = torch.sqrt((x**2).sum(1).view(-1, 1))
    y_norm = torch.sqrt((y**2).sum(1).view(-1, 1))
```

Using the specialized norm functions would have made things more efficient.

11:05am.

```py
def dec_lap_pyr(x, levs):
    """ constructs batch of 'levs' level laplacian pyramids from x
        Inputs:
            x -- BxCxHxW pytorch tensor
            levs -- integer number of pyramid levels to construct
        Outputs:
            pyr -- a list of pytorch tensors, each representing a pyramid level,
                   pyr[0] contains the finest level, pyr[-1] the coarsest
    """
    pyr = []
    cur = x  # Initialize approx. coefficients with original image
    for i in range(levs):

        # Construct and store detail coefficients from current approx. coefficients
        h = cur.size(2)
        w = cur.size(3)
        x_small = F.interpolate(cur, (h // 2, w // 2), mode='bilinear')
        x_back = F.interpolate(x_small, (h, w), mode='bilinear')
        lap = cur - x_back
        pyr.append(lap)

        # Store new approx. coefficients
        cur = x_small

    pyr.append(cur)

    return pyr
```

What's a laplacian pyramid? I goggled it. I'll have to dive deeper in order to figure out what is it for.

11:10am.

```py
def whiten(x, ui, u, s):
    '''
    Applies whitening as described in:
    https://openaccess.thecvf.com/content_ICCV_2019/papers/Chiu_Understanding_Generalized_Whitening_and_Coloring_Transform_for_Universal_Style_Transfer_ICCV_2019_paper.pdf
    x -- N x D pytorch tensor
    ui -- D x D transposed eigenvectors of whitening covariance
    u  -- D x D eigenvectors of whitening covariance
    s  -- D x 1 eigenvalues of whitening covariance
    '''
    tps = lambda x: x.transpose(1, 0)
    return tps(torch.matmul(u, torch.matmul(ui, tps(x)) / s))
```

Let me check out the paper just for a bit.

11:35am. I've gone over the code. There is not a small amount of it, but it is not large by any means either. It is nicely commented, and this all seems like a decent short job, suitable for my skills. The next try is to try running it. Before I try it on my own, I've noticed that it has a web demo. Let me try passing in my own big image after downscaling it.

11:40am. Damn it, what style did I use for that room image?

Ah, the butterfly. I can check out the results in my account rather than just the folder.

'Copied style images cannot be downloaded.' What a ripoff.

I did it manually. Right now it says it is warming up the server.

```
## Hardware Requirements
Primarily tested in gpu mode with nvidia gpus using cuda, cpu mode implemented but not tested extensively (and is very slow).
Generating 512x512 outputs requires ~6GB of memory, generating 1024x1024 outputs requires ~12GB of memory.
```

Ah, I see where the youtuber got his hardware reqs, from the repo readme.

11:50am. Forget anything too fancy.

```py
python styleTransfer.py --content_path inputs/content/C1.png --style_path inputs/style/S4.jpg --output_path ./output.jpg
```

Let me just run this once.

11:50am. Looks nice. Let me try the high res web version.

11:55am.

```
(base) PS E:\NeuralNeighborStyleTransfer> python styleTransfer.py --content_path inputs/content/C1.png --style_path inputs/style/S4.jpg --output_path ./output.jpg
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to C:\Users\Marko/.cache\torch\hub\checkpoints\vgg16-397923af.pth
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 528M/528M [02:15<00:00, 4.07MB/s]
C:\Users\Marko\anaconda3\lib\site-packages\torch\nn\functional.py:3609: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
-(0, 64)-
C:\Users\Marko\anaconda3\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important
until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
-(1, 128)-
-(2, 256)-
-(3, 512)-
Traceback (most recent call last):
  File "styleTransfer.py", line 65, in <module>
    output = produce_stylization(content_im_orig, style_im_orig, phi,
  File "E:\NeuralNeighborStyleTransfer\utils\stylize.py", line 107, in produce_stylization
    target_feats = replace_features(feats_c, feats_s)
  File "E:\NeuralNeighborStyleTransfer\utils\stylize.py", line 166, in replace_features
    d_mat = pairwise_distances_cos_center(ref_flat, src_flat)
  File "E:\NeuralNeighborStyleTransfer\utils\distance.py", line 66, in pairwise_distances_cos_center
    return pairwise_distances_cos(center(x), center(y))
  File "E:\NeuralNeighborStyleTransfer\utils\distance.py", line 26, in pairwise_distances_cos
    d = 1. - torch.mm(x / x_norm, y_t)
RuntimeError: CUDA out of memory. Tried to allocate 1.06 GiB (GPU 0; 4.00 GiB total capacity; 1.87 GiB already allocated; 822.46 MiB free; 1.94 GiB reserved in total by PyTorch)
```

What trouble. Couldn't it go for another Gb? Can I pre-allocate 3gb manually in PyTorch.

12pm. At any rate, given that it came to this point, I can assume that nothing would have prevented me from running the script if I had enough memory. There is nothing I need to do to adapt it to Windows.

12:10pm. Right now I am passing in Nostalgia from the /wip/ thread. I want to see what NNST gives me back.

12:20pm. I am thinking about it. The result is actually pretty impressive. Way better than DDG.

NNST is worth optimizing so it runs at higher res.

It will give me a huge advantage in the art journey. Even if it took me a month it would still be worth it, let alone a few days. And more than just using it for myself, this is something worth selling. If I can make an addon that does style transfer as well as upscaling, it would be worth putting on Blendermarket and Gumroad.

12:25pm. Let me have breakfast here. After that I will look into finding out my system's GPU memory capacity. PyTorch might have an easier time allocating 3gb all at once rather than in chunks."