"https://youtu.be/p_sLhKeo6ys?list=PL5Q2soXY2Zi8KzG2CQYRNQOVD0GOBrnKy&t=1247
Here is the 64mb bank. Sigh, I have no idea what was wrong with me.

https://youtu.be/zF70xuhesME?list=PL5Q2soXY2Zi8KzG2CQYRNQOVD0GOBrnKy&t=404

I think I need to think in terms of banks, but I am not sure how that works.

https://youtu.be/zF70xuhesME?list=PL5Q2soXY2Zi8KzG2CQYRNQOVD0GOBrnKy&t=563

`v8 = DpuSet(nr_dpus=1, binary=f'kernels/g{v7}.dpu')`

So this is literally the number of dpus, not the number of ranks?

https://youtu.be/zF70xuhesME?list=PL5Q2soXY2Zi8KzG2CQYRNQOVD0GOBrnKy&t=794

I hate this company so much it is unreal.

https://youtu.be/zF70xuhesME?list=PL5Q2soXY2Zi8KzG2CQYRNQOVD0GOBrnKy&t=1244

How do ranks come into this?

12:55pm. It does not matter how they comes into it. I am 100% sure that I need to be thinking in terms of individual DPU banks when passing in data. Though it does make it confusing to me as how this would work when the array cannot be split into equal chunks. Knowing UPMEM it probably wouldn't.

1:15pm. Let me do the chores here. Then I'll do some more work in the C backend. I need to make sure that the UPMEM backend calls the buddy allocator. I forgot about that.

2pm. Let me plug in that buddy allocator.

2:10pm.

```fs
    let malloc, free =
        match backend_type with
        | Prototypal -> "malloc", "free"
        | UPMEM_C_Kernel _ -> "buddy_malloc", "buddy_free"

    let print_decref s_fun name_fun type_arg name_decref =
        line s_fun (sprintf "void %s(%s * x){" name_fun type_arg)
        let _ =
            let s_fun = indent s_fun
            line s_fun (sprintf "if (x != NULL && --(x->refc) == 0) { %s(x); %s(x); }" name_decref free)
        line s_fun "}"
```

Piece of cake. I had to fold `print_decref` in, but that was not a problem.

2:10pm. Now what do I do for the rest of the day?

I caught up to my reads, but my stress is very high. I'd be a lot more motivated to program if the UPMEM contact matched some of my energy, but right now...

Let me switch.

Let me do some writing for a couple of days. I've programming like a madman for the past 10 days. Right now everything is set, but I just don't feel like going at it. I hate this kind of responsibility that has uncertain payoff.

It is not like owe it to UPMEM to finish it.

I've been losely thinking of doing a Graphcore backend instead.

But no. I should at least do the map kernel to completion

Ok, let me write for a few hours. It is important to let the programming stuff linger for a few days. Right now I feel sick of it, but later I won't be able to stop myself from doing it. There is no point in pushing myself.

Times like these are painful, because I 'want' to program, but I can't for psychological reasons. I want to keep going, but I feel shackled by mental fatigue.

'Those are just feelings.' You might say. But stress is very much a real thing. I remember how in the 2015-2017 I used to just push through. And then I started thinking that the lump in my stomach was an actual illness and went around seeing doctors.

2:30pm. Forget that, let me write for a few days until I really want to program again.

2:45pm. I had an idea. Let me just test whether I can read from the `DPU_MRAM_HEAP_POINTER`. The `mram_read` functions do not have offsets.

```py
>>> 1048576
1048576
>>> hex
<built-in function hex>
>>> hex(1048576)
'0x100000'
```

Python is so convenient. I wanted to know what the pointer is in hexadecimal, but didn't even have look up the documentation to get it to work. The interpreter is so fast to start too. Ok, I love Python all of a sudden.

```
printf("%u\n",DPU_MRAM_HEAP_POINTER+1);
```

Pushing it forward increments the offset linearly.

```c
int32_t main(){
    __dma_aligned uint8_t v0[512];
    printf("%u\n",DPU_MRAM_HEAP_POINTER+1);
    mram_read(DPU_MRAM_HEAP_POINTER, v0, sizeof(v0));
    return 0l;
}
```

This could work. I need to make sure to align the offsets on byte 8 addresses, but other than that it will be fine.

I won't need to print out global static arrays thankfully.

I'll have to figure out how to copy it on the Python end, but I should be able to figure that out. Forget that.

Writing.

3:10pm. Or more precisely peeking at the UPMEM Python library. It was easy to get PyLance to do what I want. Thought I had to first set the env and then run `code .`. Going straight into editor did not work.

`profile: str = '',`

Here is the profile. This is what I should be passing into the function.

```
    def copy(
            self,
            dst: DpuCopyBuffer,
            src: DpuCopyBuffer,
            size: Optional[int] = None,
            offset: int = 0,
            async_mode: Optional[bool] = None):
        """
        Copy data between the Host and the DPUs

        Args:
            dst (DpuCopyBuffer): the destination buffer for the copy.
                If the buffer is on the Host, this must be a bytearray, or a list of optional bytearrays.
                If the buffer is on the DPUs, this must be a str, representing a DPU symbol, or directly a DpuSymbol.
            src (DpuCopyBuffer): the source buffer for the copy.
                If the buffer is on the Host, this must be a bytearray, or a list of optional bytearrays.
                If the buffer is on the DPUs, this must be a str, representing a DPU symbol, or directly a DpuSymbol.
            size (Optional[int]): number of bytes to transfer.
                By default set to None, which will use the length of the Host buffer. If multiple Host buffers are
                provided, all buffers must have the same size.
            offset (int): offset in bytes for the DPU symbol.
                By default set to 0.
            async_mode (Optional[bool]): override the default behavior set in the constructor.

        Raises:
            DpuError: if the copy fails, because of invalid arguments, unknown symbols or out-of-bound accesses
        """
```

It turns out the UPMEM has good documentation.

Let me check out `DpuSymbol`s.

```
class DpuSymbol():
    """
    Symbol in a DPU program

    Attributes:
        name (str): the name of the symbol
    """

    def __init__(self, name: str,
                 c_symbol: Union[ffi.struct_dpu_symbol_t, Tuple[int, int]]):
        self.name = name
        if isinstance(c_symbol, ffi.struct_dpu_symbol_t):
            self.c_symbol = c_symbol
        else:
            self.c_symbol = ffi.struct_dpu_symbol_t()
            self.c_symbol.address = c_symbol[0]
            self.c_symbol.size = c_symbol[1]

    def value(self) -> int:
        """
        Fetch the symbol value (ie. when done on a variable, its address)

        Returns:
            int: the symbol value
        """
        return self.c_symbol.address

    def size(self) -> int:
        """
        Fetch the symbol size

        Returns:
            int: the symbol size
        """
        return self.c_symbol.size
```

Oh you can in fact get the address. I'll have to test whether `DPU_MRAM_HEAP_POINTER` works as a symbol. I should try doing a search.

Let me just try it out. What the hell.

3:35pm.

```py
#!/usr/bin/env python3

from dpu import DpuSet
from dpu import ALLOCATE_ALL

BUFFER_SIZE = 1 << 16

def populate_mram(dpus):

    buffer = bytearray([1,2,3,4])
    dpus.copy('buffer', buffer)

with DpuSet(1, binary = "trivial_checksum_example") as dpus:

    populate_mram(dpus)
    dpus.exec()

    checksum = [bytearray(4) for _ in dpus]
    dpus.copy(checksum, 'checksum')
    print("Computed checksum = 0x%08x" %(int.from_bytes(checksum[0], 'little')))
```

This works. But when I try my own example it does not.

```c
#include <mram.h>
#include <stdbool.h>
#include <stdint.h>

#define CACHE_SIZE 256
#define BUFFER_SIZE (1 << 16)

__mram_noinit uint8_t buffer[BUFFER_SIZE];
__host uint32_t checksum;

int main() {
  __dma_aligned uint8_t local_cache[CACHE_SIZE];
  checksum = 0;

  for (unsigned int bytes_read = 0; bytes_read < BUFFER_SIZE;) {
    mram_read(&buffer[bytes_read], local_cache, CACHE_SIZE);

    for (unsigned int byte_index = 0; (byte_index < CACHE_SIZE) && (bytes_read < BUFFER_SIZE); byte_index++, bytes_read++) {
      checksum += (uint32_t)local_cache[byte_index];
    }
  }

  return checksum;
}
```

Why is the symbol defined when I try this example, but not my own?

```c
__mram_noinit uint8_t buffer[128];
__host uint32_t checksum;

int main() {
    __dma_aligned uint8_t local_cache[CACHE_SIZE];
    mram_read(&buffer[0], local_cache, CACHE_SIZE);
}
```

Ah. I get it. I think it will get pevaled away if it is not used. UPMEM can be annoying like that. I have to `mram_read` it in order to prevent that from happening.

But how do I use the heap pointer from Python?

3:55pm. I sent an email to support asking them about it. My luck with interacting with others has been attrocious lately, but maybe they will field this question. If not it does not matter, I'll just create symbol to take the place of that pointer. Right now I have what I need to make what I need work.

4pm. Let me try writing again. I should assume I have everything set. Forget about that crappy pointer.

7:45pm. 34.8k. Let me stop writing here. It has been a while since I uploaded anything new to Patreon so let me do it now.

7:50pm. Looking at the Heaven's Key dashboard I see that views are at 5,990. Avg at 133. 509 pages. Followers at 29 and faves at 8.

It is more bearable to look at this slow progression every few days. I am not going to get anywhere as a writer, so it good to mix up the two hobbies. It really felt refreshing writing this.

It is important to find a writing style that feels natural. Trying to write like a robot would be too hard for a human like me.

How much have I written today?

Oh, over 2.8k words. Yeah. this is why breaks are good. It is easier to get a release when I you are pent up.

The reason why I botched the social interaction with the UPMEM guy was due to overabundance of programming energy. It will be a good lesson for when I interact with other companies.

I am changing my plans a little. I am only going to do the generic map kernel. After that I'll wrap up the UPMEM backend and write a short article about it. My main target is the Tenstorrent discord where my old post is squating, but I'll also fish on HN, the PL sub and the Python one. That will give me time to look at the Graphcore device. It would be a better expenditure of my time that doing more stuff for UPMEM. Finishing the Python kernel was useful for me because it gave me the change to tighten up the language, but working on more kernels will not gain me anything. Instead that Graphcore free instance on Paperspace is what I should be looking for.

It just can't be helped that it came to this with UPMEM. I write nasty things in this journal and that is how it should be. My based spirit is here for all to see!"