"9:45am. I should really be getting started, but let me chill for a bit first. Somehow I am terrified of this part.
10:10am. Done with chilling. Let me start. I need this experiment. If sampling policies from a batch and optimizing that does not give me the benefits of averaging then I am screwed.

I cannot reason it out exactly. So it feels like what I am doing is a gamble.

```
import numpy as np

a = np.zeros((3,5))
b = a[1,:]
b[0] = 23
print(a)
```

This edits the original array. Ok, good. I'll reuse the old thing then.

```
inl key = $"numpy.random.randint(0,!MatrixSize)"
```

Didn't I fix this so that bigvars could be used macros? I guess I did not.

I really do regret all the experimental tricks I put into the parser. Most of them are barely useful. I should just had regular symbols, plus maybe unary pairs.

```
// Can also be used for normalizing the avg policy.
let regret_match regret =
    inl temp, normalizing_sum = am.mapFold (fun s x => inl x = max 0 x in x, x + s) 0 regret

    if normalizing_sum = 0 then inl v = 1 / f64 (length temp) in am.mapInplace (fun _ _ => v) temp
    else am.mapInplace (fun _ x => x / normalizing_sum) temp
    temp

inl MatrixSize = 2u64
inl get_cur_policy (regret : obj) : a u64 f64 =
    inl len_ii = MatrixSize
    inl len_i = $"len(!regret)" / len_ii
    inl ar : a u64 f64 = am.init len_i (fun _ => 0)
    loop.for' (from:0 nearTo: len_ii) fun ii =>
        inl dist : a u64 f64 = regret_match $"!regret[!ii,:]"
        $"!ar += !dist / !len_ii"
    ar
inl get_keyed_policy (regret : obj) (key : u64) : a u64 f64 = regret_match $"!regret[!key,:]"

type state key act = dictm.dict key {regret : obj; actions : a u64 act}
inl value (d : state _ _) actions = dictm.memoize d fun _ =>
    inl len = length actions
    inl size = MatrixSize
    inl Empty = $"numpy.zeros((!len,!size),dtype=numpy.float64)"
    {regret = Empty; actions}

inl terminal _ = ()

open nodes
inl funsPlay (d : state _ _) = player_funs {
    terminal action = fun {player actions next} =>
        inl num_actions = length actions
        inl policy = (value d actions player.observations).regret |> get_cur_policy
        inl i = $"numpy.random.choice(!num_actions,p=!policy)"
        inl p,a = index policy i, index actions i
        next (log_prob_from_sample p,a)
    }

union cfr_mode = PlayCurrentPolicy | TrainCurrentPolicy
inl funsTrain is_print mode (d : state _ _) = player_funs {
    terminal action = fun {chance_prob player player' id actions next} =>
        inl d = value d actions player.observations
        inl op_prob = @@(chance_prob +@ player')

        inl next prob a =
            if prob = 0 && op_prob = 0 then r2 0 // the pruning optimization
            else next (log_prob_from_policy prob,a)

        inl weighted_sum policy = am.fold2 (fun s prob a => s +! next prob a *! prob) (r2 0) policy actions

        match mode with
        | PlayCurrentPolicy => weighted_sum (get_cur_policy d.regret)
        | TrainCurrentPolicy =>
            inl size = MatrixSize
            inl key : u64 = $"numpy.random.randint(0,!size)"

            inl regret = d.regret |> fun x => $"!x[!key,:]"
            inl u,us =
                am.mapFold2 (fun s prob a =>
                    inl r = next prob a
                    r, s +! r *! prob
                    ) (r2 0) (regret_match regret) actions
            regret |> am.mapInplace (fun i x => max 0 <| x + op_prob * !!(index u i -! us) id)
            us
    }
```

How about this? This should do it.

Actually first let me test it with a matrix size of 1. This can serve as a sanity check.

```
  File "rps_test.pyx", line 986, in rps_test.method7
    raise Exception("The two arrays have to have the same size.")
Exception: The two arrays have to have the same size.
```

I get an exception somewhere.

```
            $"print('qwe')"
            inl u,us =
                am.mapFold2 (fun s prob a =>
                    inl r = next prob a
                    r, s +! r *! prob
                    ) (r2 0) (regret_match regret) actions
            $"print('asd')"
```

The problem is here. Why?

```
            inl regret = d.regret |> fun x => $"!x[!key,:]"
            $"print(len(!regret),len(!actions))"
```

It is telling me that regret is size of 1 here.

```
[[0.]
 [0.]
 [0.]]
1 3
```

Ah, is there something special about initializing the 1 size arrays.

```
inl Empty = $"numpy.zeros((!len,!size),dtype=numpy.float64)"
```

Ah, I got the sizes wrong.

```
    v1 += v6 / (<unsigned long long>1)
ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (3,)
```

Let me just do a normal loop.

```
inl get_cur_policy (regret : obj) : a u64 f64 =
    inl len_ii = MatrixSize
    inl len_i = $"len(!regret)" / len_ii
    inl ar : a u64 f64 = am.init len_i (fun _ => 0)
    loop.for' (from:0 nearTo: len_ii) fun ii =>
        inl dist : a u64 f64 = regret_match $"!regret[!ii,:]"
        ar |> am.mapInplace (fun i x => x + index dist i / f64 len_ii)
    ar
```

This should be promising.

```
    raise Exception("The length of the two arrays has to the same.")
Exception: The length of the two arrays has to the same.
```

Huh, again with this.

```
        inl weighted_sum policy =
            $"print('qwe')"
            inl x = am.fold2 (fun s prob a => s +! next prob a *! prob) (r2 0) policy actions
            $"print('asd')"
            x
```

Is it here? Why would it be here?

```
        inl weighted_sum policy =
            $"print(len(!policy),len(!actions))"
            inl x = am.fold2 (fun s prob a => s +! next prob a *! prob) (r2 0) policy actions
            $"print('asd')"
            x
```

Yeah, the first one is 1, and the second is 3. Why?

```
inl get_cur_policy (regret : obj) : a u64 f64 =
    inl len_ii = MatrixSize
    inl len_i = $"len(!regret)" / len_ii
    $"print(!len_ii,!len_i)"
```

Why are both of these 1?

```
[[0. 0. 0.]]
1 1
```

Agh, it is just telling me the length of the outer dimension!

https://note.nkmk.me/en/python-numpy-ndarray-ndim-shape-size/

```
inl get_cur_policy (regret : obj) : a u64 f64 =
    inl len_ii = MatrixSize
    inl len_i = $"!regret.dim" / len_ii
```

Let me do it like this then.

```
AttributeError: 'numpy.ndarray' object has no attribute 'dim'
```

Whops, that is meant to be size.

```
summary - 0 -0.04115948480348969
summary - 1 -0.019726010588613584
summary - 2 -0.09780954241066103
summary - 3 -0.04619059180475471
summary - 4 -0.09337999008268105
summary - 5 -0.031022672482779234
summary - 6 -0.09570912018356642
summary - 7 -0.011738413202603618
summary - 8 -0.023247690028464246
summary - 9 -0.037166923638381255
summary - 10 -0.039084519688492525
summary - 11 -0.02708870268478302
summary - 12 -0.015248881265332775
summary - 13 -0.07553770130841447
summary - 14 -0.09072571416385261
summary - 15 -0.06222454660989579
summary - 16 -0.045655879549343525
summary - 17 -0.008875179885428595
summary - 18 -0.012381230432532989
summary - 19 -0.033600344997437914
```

Oh, this is better I think. No wait. This is with a matrix size of 1. I still haven't put in the improvements.

```
summary - 0 -0.2490912271024713
summary - 1 -0.0036944444141605477
summary - 2 -0.19836845865373248
summary - 3 -0.1520602842237777
summary - 4 -0.08674950766409284
summary - 5 -0.024987043473227936
summary - 6 -0.024540264294131683
summary - 7 -0.059578655123293744
summary - 8 -0.14826173330486606
summary - 9 -0.04115948480348969
summary - 10 -0.15148791435897385
summary - 11 -0.05485611402992813
summary - 12 -0.05109995520285149
summary - 13 -0.1177691750165955
summary - 14 -0.12741639136657923
summary - 15 -0.13935941204864766
summary - 16 -0.1263463835264476
summary - 17 -0.1234737601165743
summary - 18 -0.08150650037885876
summary - 19 -0.019726010588613584
```

I am using a smaller number of subiterations here, 100 rather than 1000. Let this serve as the baseline. Now, let me increase the matrix size to 2.

```
summary - 0 -0.15811520268405868
summary - 1 -0.10447024280518774
summary - 2 -0.059149348703846694
summary - 3 -0.09772503979400776
summary - 4 -0.08655830450775326
summary - 5 -0.04019678198877702
summary - 6 -0.04651934010523073
summary - 7 -0.05504974854081501
summary - 8 -0.06320671152374946
summary - 9 -0.016644406026360498
summary - 10 -0.04039381487770717
summary - 11 -0.011586928500482624
summary - 12 -0.0655469107223357
summary - 13 -0.038590310831418784
summary - 14 -0.00026015470395668316
summary - 15 -0.031054347144945538
summary - 16 -0.03129715902155507
summary - 17 -0.034327966223700185
summary - 18 -0.03598361405174222
summary - 19 -0.049515158178806806
```

This seems like an improvement. Let me use 4 buckets.

```
summary - 0 -0.03522595736456541
summary - 1 -0.054343698010748565
summary - 2 -0.04102792176721476
summary - 3 -0.02901682977999766
summary - 4 -0.04116543404356293
summary - 5 -7.207144230631478e-05
summary - 6 -0.024855629418051084
summary - 7 -0.03746145285038982
summary - 8 -5.054954767376614e-05
summary - 9 -0.0001588654258108755
summary - 10 -0.020953788972170734
summary - 11 -0.021857917361923197
summary - 12 -0.028121355670191108
summary - 13 -0.002663835099245171
summary - 14 -0.029778089417817177
summary - 15 -0.031258905324271835
summary - 16 -0.026112553072081657
summary - 17 -0.023531165932271808
summary - 18 -0.01803214021602409
summary - 19 -0.004357468744299611
```

Let me try 1000 iterations each.

```
summary - 0 -0.014067606128186777
summary - 1 -2.3306906629932e-06
summary - 2 -0.0013049596852564571
summary - 3 -0.0018678696934612687
summary - 4 -0.00027930200578990885
summary - 5 -0.001035691745029304
summary - 6 -0.0008605690693214256
summary - 7 -0.00909066990101999
summary - 8 -0.010173751079772433
summary - 9 -0.0005917935172697411
summary - 10 -0.011931990465905512
summary - 11 -0.011322911297065516
summary - 12 -6.725191183088071e-05
summary - 13 -0.010924740519250575
summary - 14 -0.00010738628861684321
summary - 15 -0.00017452847602313255
summary - 16 -0.00015798750521000757
summary - 17 -0.00017385356708075374
summary - 18 -1.0379508001688055e-05
summary - 19 -1.253429089034851e-05
```

This is actually exactly what I'd hoped for. For every bucket, the error goes down exponentially. Let me try 8 buckets next.

```
summary - 0 -0.01567622750469863
summary - 1 -0.003802394225012218
summary - 2 -0.008294610642473263
summary - 3 -0.01181595203121702
summary - 4 -1.540768758640041e-06
summary - 5 -8.247716626221847e-05
summary - 6 -0.018895263250997163
summary - 7 -0.02035838484888857
summary - 8 -0.0014467460694720102
summary - 9 -0.013462200461640775
summary - 10 -0.012106453886054094
summary - 11 -0.021256923708357217
summary - 12 -0.0011058294129251134
summary - 13 -0.013622940687619017
summary - 14 -0.000644441050115279
summary - 15 -0.000126878306447583
summary - 16 -0.0002483898121761752
summary - 17 -1.8576143494676393e-05
summary - 18 -9.871750322274636e-06
summary - 19 -3.34040886594859e-06
```

Hmmm, not as good as it could be. The variance is high...

Let me try 16. I want to see what it would take to squeeze it down.

```
summary - 0 -0.01234436882340903
summary - 1 -0.006222273849239179
summary - 2 -0.003998578341075823
summary - 3 -0.008134390283876192
summary - 4 -0.004574933138160098
summary - 5 -0.0003204761806223297
summary - 6 -0.0020053018803383726
summary - 7 -0.004124759988265392
summary - 8 -0.004363293733521775
summary - 9 -0.003759641416644116
summary - 10 -0.005631414288133005
summary - 11 -0.0007382157819145613
summary - 12 -0.004336642663628473
summary - 13 -0.00039596294903396223
summary - 14 -0.009995068303778276
summary - 15 -0.0035442909301589554
summary - 16 -0.004846030894485251
summary - 17 -0.009734195433755644
summary - 18 -0.0031180238271416166
summary - 19 -0.0052455574693185125
```

The time it takes to run doubles every time I double the matrix size. I guess calculating the average policy is hard.

Let me try 32 next.

```
summary - 0 -0.003450018225783502
summary - 1 -0.0038619872769076607
summary - 2 -0.003926064770410919
summary - 3 -0.003307083224006274
summary - 4 -0.0017040837247274954
summary - 5 -3.799238248147958e-05
summary - 6 -0.0008459464080735057
summary - 7 -0.0008925499795451632
summary - 8 -0.0015857635320618638
summary - 9 -0.0015843145654932111
summary - 10 -0.000548196610941281
summary - 11 -0.0012521810951827417
summary - 12 -0.000864714960895234
summary - 13 -0.0016482193086086172
summary - 14 -0.0015130615044314372
summary - 15 -0.001898949144080203
summary - 16 -0.0020861367524923763
summary - 17 -0.003128590193455766
summary - 18 -0.00018861133066506997
summary - 19 -0.004298440279101257
```

With a decent size in buckets, the variance goes way down, and so does the error. Let me try 64 next. I'll go up to 128.

```
summary - 0 -0.013267673573172434
summary - 1 -0.011527920652504436
summary - 2 -0.005431584736032391
summary - 3 -0.00899804459019024
summary - 4 -0.002069559700163759
summary - 5 -0.002239113340570295
summary - 6 -0.0006814593722343984
summary - 7 -0.001060027538337234
summary - 8 -0.00040328637832880154
summary - 9 -6.588155336973702e-05
summary - 10 -0.0019684939381086064
summary - 11 -0.0008433788336347087
summary - 12 -0.0010510536142796303
summary - 13 -0.00025983405592007805
summary - 14 -0.00046120509222407485
summary - 15 -0.0006606695795956449
summary - 16 -0.001006236920106457
summary - 17 -0.0008171989445280789
summary - 18 -0.00021325817864691998
summary - 19 -0.0007259017272450777
```

128 is next. But at this stage 1000 iterations is not enough samples. Let me increase it by 10x. Then I'll go to averaging 128 different policies.

```
summary - 0 -0.001400971927750641
summary - 1 -0.002312481084568177
summary - 2 -0.0049003900720457905
summary - 3 -0.002707807800812062
summary - 4 -0.000934956812940195
summary - 5 -0.00044127738389561355
summary - 6 -6.356397586221654e-05
summary - 7 -3.8199921810831705e-05
summary - 8 -4.4004307229658646e-05
summary - 9 -0.0011466141238332117
summary - 10 -0.00014298137209144482
summary - 11 -0.00043844816462682706
summary - 12 -0.00027699401455962697
summary - 13 -0.00019941349460328786
summary - 14 -3.332520179947715e-05
summary - 15 -2.6168292267925164e-05
summary - 16 -4.981651767983937e-05
summary - 17 -6.843883468515485e-05
summary - 18 -0.0003154320691253626
summary - 19 -4.2288244512224404e-05
```

Success! I won't bother going up to 128. It is clear to me that my idea works!

Averaging policies, and optimizing a bucket of policies are both viable approaches towards cycle breaking.

With this I have the empirical backing to not bother with keeping old policy nets around. I'll just plop in dropout in the first layer and call it a day.

11:25am. This is exquisite. I thought it was more likely to work than noise keying, but everything happened exactly the way I hoped this time. Adding more buckets seems to have an exponential effect on reducing the error.

11:30am. I am ready. Let me update the PL post. Let me commit here so I can link to it."