"9:35am.
```
let keyword_key_value = Parsing.string_to_keyword "key:value:"
let keyword_key_state_value = Parsing.string_to_keyword "key:state:value:"
```

I am going to get rid of the arguments changing positions between `foldr` and `foldl`. It is just a source of confusion.

```
        | RecordMap,[|a;b|] ->
            match ev2 d a b with
            | a, TyMap l ->
                Map.map (fun k x ->
                    apply d (a, TyKeyword(keyword_key_value,[|TyKeyword(k,[||]); x|]))
                    ) l
                |> TyMap
```

Let me go with this.

Damn, the IDE is sluggish. Let me reset it.

9:40am.

```
        | RecordMap,[|a;b|] ->
            match ev2 d a b with
            | a, TyMap l ->
                Map.map (fun k x -> apply d (a, TyKeyword(keyword_key_value,[|TyKeyword(k,[||]); x|]))) l
                |> TyMap
            | _, b -> raise_type_error d <| sprintf "Expected a record.\nGot: %s" (show_typed_data b)
        | RecordFilter,[|a;b|] ->
            match ev2 d a b with
            | a, TyMap l ->
                Map.filter (fun k x ->
                    match apply d (a, TyKeyword(keyword_key_value,[|TyKeyword(k,[||]); x|])) with
                    | TyLit(LitBool x) -> x
                    | x -> raise_type_error d <| sprintf "Expected a bool literal in ModuleFilter.\nGot: %s" (show_typed_data x)
                    ) l
                |> TyMap
            | _, b -> raise_type_error d <| sprintf "Expected a record.\nGot: %s" (show_typed_data b)
        | RecordFoldL,[|a;b;c|] ->
            match ev3 d a b c with
            | a, s, TyMap l -> Map.fold (fun s k x -> apply d (a, TyKeyword(keyword_key_state_value,[|TyKeyword(k,[||]); s; x|]))) s l
            | _, _, r -> raise_type_error d <| sprintf "Expected a record.\nGot: %s" (show_typed_data r)
        | RecordFoldR,[|a;b;c|] ->
            match ev3 d a b c with
            | a, TyMap l, s -> Map.foldBack (fun k x s -> apply d (a, TyKeyword(keyword_key_state_value,[|TyKeyword(k,[||]); s; x|]))) l s
            | _, r, _ -> raise_type_error d <| sprintf "Expected a record.\nGot: %s" (show_typed_data r)
```

This is justice. It will definitely make the language more verbose, but it will also make it more readable. It would be different if Spiral had HM at every point, but I need to improve the integrity in other ways in its absence.

9:50am.

```
/// Folds over a record left to right.
inl record_foldl f (state:) a = !recordFoldL(f,state,a)
/// Folds over a record right to left.
inl record_foldr f (state:) a = !recordFoldR(f,state,a)
```

Holy shit, note how I got the state argument wrong previously. I did not even notice until I replace `s` with `state`.

9:50am.

```
prim_is
```

Ah, I have `prim_is` nowhere defined. Definitely missing the IDE here.

9:50am.

```
inl Is = [
    /// Returns boolean whether the expression is a literal.
    lit: x = !LitIs(x)
    /// Returns boolean whether the expression is a primitive type.
    prim: x = !PrimIs(x)
    /// Returns boolean whether the expression is a layout type.
    layout: x = !LayoutIs(x)
    /// Returns boolean whether the expression is an union type.
    union: x = !UnionIs(x)
    /// Returns boolean whether the expression is a recursive union type.
    rec_union: x = !RecUnionIs(x)
    /// Returns boolean whether the expression is a runtime union type.
    runtime_union: x = !RuntimeUnionIs(x)
    /// Returns boolean whether the expression is a runtime recursive union type.
    runtime_rec_union: x = !RuntimeRecUnionIs(x)
    ]
```

Let me do it like this.

```
        | a, b when Is (prim: a) -> !EQ(a,b)
        | a, b when Is (layout: a) -> indiv a = indiv b
```

Much better.

```
| {} & a, {} & b -> record_foldr (fun k x next res -> res && (match b with {$k=x'} -> next (x = x'))) a id true
```

Now let me modify this confusing mess.

10am.

```
/// Structural polymorphic equality for every type in the language (apart from functions, objects and keywords.)
inl (=) a b =
    inl rec (=) a b =
        match a,b with
        | a, b when Is (prim: a) -> !EQ(a,b)
        | a, b when Is (layout: a) -> indiv a = indiv b
        | a :: as', b :: bs -> a = b && as' = bs
        | (), () -> true
        | {} & a, {} & b -> record_foldr (fun (key:_ state:next value:x') res -> res && (match b with {$k=x'} -> next (x = x'))) (state:id) a true
        | a, b when Is (union: a) || Is (rec_union: a) ->
            inl f a b =
                inl #a, #b = a, b
                eq_type a b && a = b
            if Is (runtime_rec_union: a) && Is (runtime_rec_union: b) then join f a b : true
            else f a b
        | _ -> false
    if eq_type a b then a = b
    else error_type ("Trying to compare variables of two different types. Got:",a,b)
```

This is the way to do this.

```
/// Creates a macro.
/// type: a body: string lit -> a
inl macro type: t text: = !Macro(text,t)
/// Creates a macro type.
/// type: (string lit & a) body: string lit -> a macro
inl macro_extern type: t text: = !MacroExtern(text,t)
```

10:05am.

```
    /// Checks whether the float is a nan.
    nan: x = !NanIs(x)
```

Let me also put this into `Is`

10:10am.

```
inl String = [
    /// Returns the length of a string.
    length: x = !StringLength(x)
    /// The .NET String.Format function.
    /// https://msdn.microsoft.com/en-us/library/system.string.format(v=vs.110).aspx
    /// When its arguments are literals, it evaluates at compile time.
    format:args: = !StringFormat(format,args)
    /// The F# String.concat function
    /// https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/string.concat-function-%5Bfsharp%5D
    /// When its arguments are literals, it evaluates at compile time.
    concat: separator args: = !StringConcat(separator,args)
    ]
```

Let make String like this.

10:15am.

```
/// Does a map operation over a record while threading state.
inl record_map_foldl f (state:) =
    record_foldl (inl key: state:(record:state:) value: ->
        inl value, state = f (key:key state:state value:value)
        {record with $key = value}, state
        ) (record:{} state:state)
```

I should put the record function into Record.

10:20am.

```
inl Record = [
    /// Maps over a record.
    map=inl f a -> !RecordMap(f,a)
    /// Iterates over a record.
    iter=inl f a -> self.map (inl k a -> f k a; ()) a |> ignore
    /// Filters a record at compile time.
    filter=inl f a -> !RecordFilter(f,a)
    /// Folds over a record left to right.
    foldl=inl f (state:) a -> !RecordFoldL(f,state,a)
    /// Folds over a record right to left.
    foldr=inl f (state:) a -> !RecordFoldR(f,state,a)
    /// Returns the record length.
    /// record -> int64
    length: m = !RecordLength(m)
    map_fold_helper = inl key: state:(record:state:) value: ->
        inl value, state = f (key:key state:state value:value)
        {record with $key = value}, state
    /// Does a map operation over a record while threading state.
    map_foldl=inl f (state:) -> self.foldl self.map_fold_helper (state:(record:{} state:state))
    /// Does a map operation (starting from the back) over a record while threading state.
    map_foldr=inl f (state:) -> self.foldr self.map_fold_helper (state:(record:{} state:state))
    ]
```

Found some find rename related errors as well.

This is decent for a library design.

```
split box stack heap heapm indiv term_cast
```

Let me put these functions into Type.

10:25am.

```
inl Type = [
    /// Splits the union or recursive type into a tuple.
    split: x = !TypeSplit(x)
    /// Boxes a type.
    box: a to: b = !TypeBox(a,b)
    /// Converts a data type to a stack layout data type.
    stack: x = !LayoutToStack(x)
    /// Converts a data type to a heap layout data type.
    heap: x = !LayoutToHeap(x)
    /// Converts a data type to a mutable heap layout data type.
    heapm: x = !LayoutToHeapMutable(x)
    /// Converts a layout data type to a standard data type.
    indiv: x = !LayoutToNone(x)
    /// Cast a function to the term level.
    term_cast:to: = !TermCast(to,term_cast)
    ]
```

This is pretty good.

10:30am.

```
    /// Returns boolean whether the two expressions are equal in their types.
    eq: a to: b = !EqType(a,b)
```

Putting this into `Type`.

...I think I will put `mutable_record_set` into `Record`.

```
    /// Sets a mutable record.
    set:field:to: = !SetMutableRecord(set,field,to)
```

This should do nicely.

```
/// Returns the size a type.
/// type -> int64
inl sizeof x = !SizeOf(x)
```

This should go into `Type`.

```
/// Raises a type error.
inl error_type x = !ErrorType(x)
```

This as well.

```
/// Does unchecked conversion for primitives.
inl to from:to: = !UnsafeConvert(to,from)
```

This.

```
    /// Does unchecked conversion for primitives.
    from:to: = !UnsafeConvert(to,from)
```

No way of getting this wrong now.

10:40am.

```
| a, b when Is (layout: a) -> Layout (none: a) = Layout (none: b)
```

Let me introduce Layout instead.

```
inl Layout = [
    /// Converts a data type to a stack layout data type.
    stack: x = !LayoutToStack(x)
    /// Converts a data type to a heap layout data type.
    heap: x = !LayoutToHeap(x)
    /// Converts a data type to a mutable heap layout data type.
    heapm: x = !LayoutToHeapMutable(x)
    /// Converts a layout data type to a standard data type.
    none: x = !LayoutToNone(x)
    ]
```

Quite nice.

10:45am.

```
    /// Raises an uncatchable type error.
    error: x = !ErrorType(x)
    /// Raises an exception at the type level. `type_catch` should be used to contain and extract the type within it.
    raise: x = !TypeRaise(x)
```

Whops, can't mix up these two.

10:55am. I've done quite a bit of redesign of the Core library. It is much nicer now.

```
inl array =
    inl facade ar = [
        /// Returns the length of an array. Not applicable to Cuda arrays.
        length = !ArrayLength(ar)
        /// Gets the value from the array at index `get`.
        get: = !GetArray(ar, get)
        /// Sets the value `to` the array at index `set`
        set:to: = !SetArray(ar, set, to)
        /// Gets the value from the array at index `apply`.
        apply: = !GetArray(ar, apply)
        ]

    inl x ->
        facade ([
            /// Creates an array with the given type and the size.
            type: t size: = !ArrayCreateDotNet(t,size)
            type: t = type !ArrayCreateDotNet(t,1)
            cuda = [
                /// Creates a Cuda local memory array with the given type and the size.
                local = [
                    type: t size: -> !ArrayCreateCudaLocal(t,size)
                    type: t -> type !ArrayCreateCudaLocal(t,1)
                    ]
                /// Creates a Cuda shared memory array with the given type and the size.
                shared = [
                    type: t size: -> !ArrayCreateCudaShared(t,size)
                    type: t -> type !ArrayCreateCudaShared(t,1)
                    ]
                ]
            ] x)
```

Let me get rid of this though. I'll put this stuff in the `Array` module later.

```
/// Creates a reference.
inl ref x =
    inl x = !ReferenceCreate(x)
    [
    get = !GetReference(x)
    set: v = !SetReference(x,v)
    ]
```

Here is the reference. It has just the right kind of simplicity now.

11:15am. Let me just review the Record.

```
    /// Does a map operation over a record while threading state.
    map_foldl=inl f (state:) -> self.foldl self.map_fold_helper (state:(record:{} state:state))
    /// Does a map operation (starting from the back) over a record while threading state.
    map_foldr=inl f (state:) -> self.foldr self.map_fold_helper (state:(record:{} state:state))
```

This thing...

11:25am.

```
inl Record = [
    /// Maps over a record.
    map:f =inl a -> !RecordMap(f,a)
    /// Iterates over a record.
    iter:f =inl a -> self (map:inl x -> f x; ()) a |> ignore
    /// Filters a record at compile time.
    filter:f =inl a -> !RecordFilter(f,a)
    /// Folds over a record left to right.
    foldl:f state: = inl a -> !RecordFoldL(f,state,a)
    /// Folds over a record right to left.
    foldr:f state: = inl a -> !RecordFoldR(f,state,a)
    /// Returns the record length.
    /// record -> int64
    length: x = !RecordLength(x)
    map_fold_helper=inl key: state:(record:state:) value: ->
        inl value, state = f (key:key state:state value:value)
        {record with $key = value}, state
    /// Does a map operation over a record while threading state.
    map_foldl:f state: = self (foldl: self.map_fold_helper state:(record:{} state:state))
    /// Does a map operation (starting from the back) over a record while threading state.
    map_foldr:f state: = self (foldr: self.map_fold_helper state:(record:{} state:state))
    /// Sets a mutable record.
    set:field:to: = !SetMutableRecord(set,field,to)
    ]
```

I really like this sort of thing.

Yeah, this is how Spiral should be.

11:30am.

```
/// Creates a macro.
/// type: a body: string lit -> a
inl macro type: t text: = !Macro(text,t)
/// Creates a macro type.
/// type: (string lit & a) body: string lit -> a macro
inl macro_extern type: t text: = !MacroExtern(text,t)
```

Ah, I know how to deal with this. I forgot about the damn `apply`.

...No wait, wait.

I had not thought about this, but the if the argument is not a keyword, what happens to it.

11:35am.

```
inl Macro = [
    /// Creates a macro.
    /// type: a text: string lit -> a
    type: t text: = !Macro(text,t)
    /// Creates a macro using the string literal as its type.
    /// text: (string lit & a) text: string lit -> a macro
    string: t text: = !MacroExtern(text,t)
    ]
```

There is no need to complicate this. I can just do it like so.

11:35am.

```
inl infinity = [
    f64 = !InfinityF64()
    f32 = !InfinityF32()
    ]
```

Actually dragging infinity as so is much better than manifesting it explicitly.

11:40am.

```
{
Type Macro Layout String Is Record
ref infinity threadIdx blockIdx
(=>) (+) (-) (*) (**) (/) (%) (:>) (:?>) (=) (|>) (<|)
(>>) (<<) (<=) (<) (=) (<>) (>) (>=) (&&&) (|||) (^^^) (::) (<<<) (>>>)
max min lit_min lit_max abs log exp tanh sqrt negate to print_static dyn
ignore id const unconst fst snd not
failwith assert
}
```

This is quite nice. I am really into it. I really pushed the size of the Core library down.

11:45am. I could do more with `Macro`s. Eventually I will give them their own module.

But this is is good. Now there are no more raw types in `Core`.

11:50am. Let me stop here so I can have breakfast."