"12:35pm. Let me finish reading Astrid and then I'll resume.
12:55pm. I finished it like 10m ago and then started reading Reddit ML sub threads...

Tch!

It is time to focus.

I know this is annoying as shit, but I have to do it.

I have to do the testing. There are like 100 tests to go through before I can conclude that the language is in decent shape.

I'll ignore those tests related to the union types, but I am going to have to put macros in before I am done.

1pm. No matter how this thing turns out, I absolutely must do the typechecking. I need the power of top-down reasoning unless I want to end up going through the same hardship that I did in 2018.

Editor support, jobs and whatever else is optional.

Without typechecking on the other hand, I can forget about ever scaling the language.

If I can at least do typechecking then I will have a lot of options open to me.

If I can do typechecking I will be capable of writing programs in the language properly the same as I do in F#.

1:05pm. Just this, just this much...

Ahhhh...damn it, I really should be doing ML...

But more than that, I need to be making strides into new things, I won't win a war by just standing in place.

Typechecking definitely qualifies as something new.

1:05pm.

```
let test4: SpiralModule =
    {
    name="test4"
    prerequisites=[]
    description="Does the and pattern work correctly?"
    code=
    """
inl f (a, b) (c, d) = dyn (a+c,b+d)
inl q & (a, b) = dyn (1,2)
inl w & (c, d) = dyn (3,4)
f q w
    """
    }
```

```
Error trace on line: 3, column: 7 in module test4.
inl q & (a, b) = dyn (1,2)
      ^
Expected one of: end of file
```

At least the error position is precise.

1:10pm. I have no idea, why is the pattern not getting parsed correctly?

...Ah, maybe because I forgot to put the `main`. Whops.

```
Unhandled exception. System.ArgumentException: The input array was empty. (Parameter 'array')
   at Spiral.Parsing.parse(SpiralModule m) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Parsing.fs:line 875
   at Spiral.Compile.p@63.Invoke(Unit _arg1) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Compile.fs:line 63
```

I've commented out the core library and I am getting this error now.

```
if d.Index = d.Length then fail [Array.last l, UnexpectedEof]
```

How unusual that this is raising an error.

```
        | Error [] ->
            if d.Index = d.Length then
                match Array.tryLast l with
                | Some x -> fail [x, UnexpectedEof]
                | None -> Error "Unknown parse error."
            else Error "Unknown parse error."
```

Let me do this.

1:20pm. I'll also change so that modules can have zero statements.

No need to push this any harder than it needs to be.

Now...

```
let test4: SpiralModule =
    {
    name="test4"
    prerequisites=[]
    description="Does the and pattern work correctly?"
    code=
    """
inl main _ =
    inl q & w = 1
    1
    //inl f (a, b) (c, d) = dyn (a+c,b+d)
    //inl q & (a, b) = dyn (1,2)
    //inl w & (c, d) = dyn (3,4)
    //f q w
    """
    }
```

I have to figure out why the and here is not getting parsed correctly.

Now that I have the core library commented out, tracking this down should be easier.

1:30pm.

```

        let inline name_pats_body on_else =
            tuple3 var_op (many pattern') (statement_body expr) >>= fun (name,pats,body) d ->
                match List.foldBack (<|) pats (join_point_entry_method body) with
                | RawInl _ | RawForall _ as x -> Ok(name,x)
                | x -> if is_global then d.FailWith ExpectedGlobalFunction else on_else (name,x) d
```

Ah crap. Note how it is expecting a `var_op` in the first place rather than a pattern.

```
inl main _ =
    inl (q, w) = 1, 2
    1
```

This does not work either.

Uf.

1:55pm.

```
let pattern_to_rawinl pat body =
    let inline f expr_pos = function
        | PatE -> RawInl("", expr_pos body)
        | PatVar name -> RawInl(name, expr_pos body)
        | _ -> RawInl(pat_main, expr_pos <| pattern_to_rawexpr(pat_main, [|pat, body|]))
    match pat with
    | PatPos x -> f (expr_pos x.Pos) x.Expression
    | x -> f id x
```

Agh, this stupid thing.

Let me adjust it a bit.

2pm.

```
let name_body pat body =
    let inline f expr_pos = function
        | PatE -> ("", expr_pos body)
        | PatVar name -> (name, expr_pos body)
        | _ -> (pat_main, expr_pos <| pattern_to_rawexpr(pat_main, [|pat, body|]))
    match pat with
    | PatPos x -> f (expr_pos x.Pos) x.Expression
    | x -> f id x
let pattern_to_rawinl pat body = name_body pat body |> RawInl
```

This is the power of abstraction.

2:10pm. Actually this part is giving me quite a bit of trouble.

```
let pat_body = pattern true false expr .>>. statement_body expr |>> fun (pat,body) -> name_body pat body
```

```
        | Error _ ->
            let name_pats_body d = name_pats_body (fun x _ -> Ok x) d
            if is_global then (name_pats_body |>> handle_inl_statement) d
            else ((attempt pat_body <|> name_pats_body) |>> handle_inl_statement) d
```

I just do not see how to do this one without backtracking.

Well, the error reporting right now is such a horrid state that it does not even matter.

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key ' pat_main' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Spiral.Prepass.prepass@312.Invoke(PrepassError x) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Prepass.fs:line 315
```

Ouh.

```
let handle_inl_statement (name, body) = fun on_succ -> l name body on_succ
```

This might be wrong.

2:20pm. I am such an imbecile. I mean I already had a solution a while ago, but I skipped it just because I wanted to optimize the expressions a little. Fuck.

```
        let pat_body = pattern true false expr .>>. statement_body expr |>> fun (pat,body) ->
            fun on_succ -> l pat_main body (pattern_to_rawexpr(pat_main, [|pat, on_succ|]))
```

Let me just go with this. For fuck's sake.

```
        let pat_body = pattern true false expr .>>. statement_body expr |>> fun (pat,body) ->
            fun on_succ ->
                match pat with PatPos x -> x.Expression | x -> x
                |> function
                    | PatE -> l "" body on_succ
                    | PatVar name -> l name body on_succ
                    | _ -> l pat_main body (pattern_to_rawexpr(pat_main, [|pat, on_succ|]))
```

Fuck. Let me go with this.

I often in situation like these have the urge to try to reuse past code and just end up spending time for no reason on this.

```
let pat_pos pos x = PatPos(Pos(pos,x))
let patpos expr d = (expr |>> function PatPos _ as x -> x | x -> pat_pos (pos' d) x) d
```

Let me do it like this so I absolutely do not make a mistake...

```
let expr_pos pos = function
    | RawPos _ as x -> x
    | x -> RawPos(Pos(pos,x))
let exprpos expr d =
    let pos = pos' d
    (expr |>> function RawB | RawType _ | RawInline _ | RawRecBlock _ | RawInl _ | RawForall _ as x -> x | x -> expr_pos pos x) d
let pat_pos pos = function
    | PatPos _ as x -> x
    | x -> PatPos(Pos(pos,x))
let patpos expr d = (expr |>> pat_pos (pos' d)) d
```

Let me do this.

2:30pm.

```
let test4: SpiralModule =
    {
    name="test4"
    prerequisites=[]
    description="Does the and pattern work correctly?"
    code=
    """
inl main _ =
    inl f (a, b) (c, d) = dyn (a+c,b+d)
    inl q & (a, b) = dyn (1,2)
    inl w & (c, d) = dyn (3,4)
    f q w
    """
    }
```

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: f
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Spiral.ParserCombinators.ParserEnv.Ok[a](TokenPosition pos, String t) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\ParserCombinators.fs:line 81
```

Now what is going on here?

...Ah yes. Backtracking behavior is causing a var to get added twice.

Ok...

```
    member d.Ok (pos : TokenPosition, t) =
        d.var_positions.[t] <- {module_=d.module_; column=pos.start_column; line=pos.start_line}
        Ok(t)
```

Let me go with this.

2:35pm.

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '+' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Spiral.Prepass.prepass@312.Invoke(PrepassError x) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language v0.2\Prepass.fs:line 315
```

This is unusual.

This should just be a regular error, why is it raising an exception?

```
match d.ReadOp' with
```

Ah, note that I am using the wrong op.

So far every time I did not take account of positional information, I've regretted it.

```
Error trace on line: 3, column: 27 in module test4.
    inl f (a, b) (c, d) = dyn (a+c,b+d)
                          ^
Error: Variable dyn not found in the environment.Error trace on line: 3, column: 33 in module test4.
    inl f (a, b) (c, d) = dyn (a+c,b+d)
                                ^
Error: Variable + not found in the environment.
```

Finally the thing parses properly.

2:40pm. Let me put the core library back in.

```
let ((var_0 : int64)) = 1L
let ((var_1 : int64)) = 2L
let ((var_2 : int64)) = 3L
let ((var_3 : int64)) = 4L
let ((var_4 : int64)) = var_0 + var_2
let ((var_5 : int64)) = var_1 + var_3
```

This seems right.

2:45pm. It is really amazing how many bugs there are even in simplest things.

Let me continue moving forward.

...Actually both Kumo and Kengan Omega are out. Let me take a break here."