"https://re-library.com/translations/heros-daughter/volume-13/chapter-621-the-heros-new-beginning/
///

“Heere, I made a sex change potion!”
“Fina?!”

///

Kek. Based.

2/11/2023

9:30am. I am up. Any mail? Nothing.

https://angel.co/jobs/applications

So far, all the jobs I have applied 3 weeks ago on AngelList have been rejected.

Sigh, let's just go forward. It is impossible to live honestly in this world it seems. But I knew that. I guess, the way I set up my resume, I must have been hoping for an entry level position. But those are very rare. So what I will do is really learn web development, and then put whatever it takes to get me that job once I am ready.

I'll learn the popular libraries in the .NET stack. And I will become a master concurrent programmer.

9:35am. I wonder if the Valora thread is dead as well? It would be great if it was not, but luck is not on my side.

It is pretty sad. Everything is trying to discourage me. I cannot do what I want. I have to experience this profound loneliness.

Before the AI apocalyspe inevitably starts, I'll at least make it so that I clear a single assignment and get paid. I should be competent enough for at least that.

Now, let me make a video on how to use the Elmish.Debugger.

https://mangakakalot.com/manga/bloomed_in_action

I'll leave this for later.

10am. Huh, this is confusing. I managed to use it yesterday. Where the hell is the time travel thing?

https://pixabay.com/music/beats-abstract-style-121455/

https://youtu.be/82oL1yuh96c
Getting Weird Websocket Error Messages In The Browser Console? Learn How To Use The Elmish Debugger

Here it is.

Now I need the Vite video.

But I do not know how to cover everything that I want yet, so let play a little. I need to see...

12:10pm. My god, why does it take so long to copy a folder with a lot of files in Total Commander. Maybe I should try a newer version of it?

```
PS E:\Webdev\Fable\test\safe-template-full-tutorial> npm run start

> start
> vite

▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]

    vite.config.js:4:12:
      4 │ console.log(import.meta.env.test);
        ╵             ~~~~~~~~~~~

  You need to set the output format to "esm" for "import.meta" to work correctly.
```

I just want to see if the env variables get set correctly.

```
file:///E:/Webdev/Fable/test/safe-template-full-tutorial/node_modules/vite/dist/node/cli.js:443
          throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
                ^

CACError: Unknown option `--env`
    at Command.checkUnknownOptions (file:///E:/Webdev/Fable/test/safe-template-full-tutorial/node_modules/vite/dist/node/cli.js:443:17)
    at CAC.runMatchedCommand (file:///E:/Webdev/Fable/test/safe-template-full-tutorial/node_modules/vite/dist/node/cli.js:641:13)
    at CAC.parse (file:///E:/Webdev/Fable/test/safe-template-full-tutorial/node_modules/vite/dist/node/cli.js:580:12)
    at file:///E:/Webdev/Fable/test/safe-template-full-tutorial/node_modules/vite/dist/node/cli.js:894:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
```

Hmmm...

https://vitejs.dev/guide/env-and-mode.html#modes

Maybe I could just change the mode?

Hmmm, instead of passing them from the command line, why don't I make the env files?

https://vitejs.dev/guide/env-and-mode.html#env-files

For some reason it is not really working.

https://stackoverflow.com/questions/67378099/import-meta-env-undefined-on-production-build-vitejs
> I just realized what the ViteJS documentation says and I'll leave it in case someone also suffers from this.

Ahhh, let me give this a try.

...I still get undefined!

> You don't have to use VITE_. You can use any prefix you like as long as you define it in the envPrefix option on the vite config.

https://www.youtube.com/results?search_query=vite

This is why Youtube vids are useful. Let me watch some of them.

12:35pm. I'll watch them after breakfast."