"8:10am. I am up. Let me chill a bit. Any mail? No.
I'll try seeing if the Insiders version of the Julia plugin fixes things. If not I'll try Atom.

8:50am. Chilled a bit. It is time to start.

First I'll close the Tessian job thread. If I were the type to get a job, I'd have done the sane thing years ago. But as long as the goal is alive, I'll do anything to get closer to it. Accumulating paper I do not need won't get me closer. It might turn out that the job is not demanding on my time, but even in such a case that would be up to luck. And whatever time is consumed cannot go invested in training my ML skills.

8:55am. I'll do the common sense thing in some other life. In this one, I chase the dream of entering the self improvement loop.

...And done. Closed the Tessian thread. I'll do the same for the Green Hills if I get back from them.

Now let me try installing the insiders version of the Julia VS Code plugin.

```
Exception has occurred: ErrorException
Method is @generated; try `code_lowered` instead.
```

Nope. I guess I'll try Atom then.

https://junolab.org/
> Juno will receive no more feature updates. Development focus has shifted to the Julia extension for VSCode.

I thought that this would maybe be the Atom plugin but it was a standalone editor. If the energy for the shifted to VS Code then VS Code will be the dominant editor.

> Juno is built on Atom, which means it's a powerful editor as well as a pretty face.

Oh, it was.

9:10am. Uh, I guess...do I still want to try Atom? I do not think I do. I thought that it would maybe have two active plugins. Knowing that the Atom one is abandonware makes it less likely for me to try this because whatever bugs the current debugger has, the old one is likely to have as well.

9:15am. I guess I'll just rewrite the generated functions into normal ones as I come across them.

9:20am. Ok, focus me. Forget about the debugger issues. Let me just keep going. I'll rewrite the generated functions as I come across them. Let me start stepping through again. The PPL skills will not get build by themselves.

```jl
@generated function apl(rv::RandVar, tω::TaggedΩ{I, Tags{K, V}, ΩT}) where {I, K, V, ΩT <: ΩBase}
  if hastags(tω, :replmap)
    :(Omega.Causal.replaceapl(rv, tω))
  elseif hastags(tω, :cache)
    :(memapl(rv, tω))
  else
    :(ppapl(rv, proj(tω, rv)))
  end
end
```

Let me comment this out. And then...

```jl
function apl(rv::RandVar, tω::TaggedΩ{I, Tags{K, V}, ΩT}) where {I, K, V, ΩT <: ΩBase}
  if hastags(typeof(tω), :replmap)
    Omega.Causal.replaceapl(rv, tω)
  elseif hastags(typeof(tω), :cache)
    memapl(rv, tω)
  else
    ppapl(rv, proj(tω, rv))
  end
end
```

Let me just do it like this for the time being.

9:30pm. https://www.youtube.com/watch?v=43EomQzcaMQ
梶浦由記「Yuki Kajiura LIVE vol.#16 〜Soundtrack Special〜『prelude to ACT1〜Numquam vincar』」

Somebody posted this and it is great.

9:45am.

```jl
"Parameters of `rv`"
@generated function params(rv::PrimRandVar)
  fields = [Expr(:., :rv, QuoteNode(f)) for f in fieldnames(rv) if f !== :id]
  Expr(:tuple, fields...)
end
```

The other one was easy to rewrite, but what about this one? Oh boy.

Well, let me play around with it.

```jl
@generated function params(rv)
    Expr(:tuple,1,2,3)
end
```

Ok, this just creates a tuple 1,2,3.

10:05am.

```
"Parameters of `rv`"
@generated function params(rv::PrimRandVar)
  fields = [Expr(:., :rv, QuoteNode(f)) for f in fieldnames(rv) if f !== :id]
  Expr(:tuple, fields...)
end
```

Can I macro expand this? Let me take a short break here.

10:35am. Let me resume. In the metaprogramming docs there was an example of a generated function being explanded. Yeah, things will be slow. I am going to have to painstakingly go through this library. Will this take me a month, or maybe two? After that I'll have to try implementing the PPL features on my own.

One goal I should reach from this study is to figure how to run all of Zenna's example.

I have to meet at least that. Once I understand how the library is used I'll be able to fully grasp what its functionality should be for.

I can't infer that from just stepping through the code. If I step through the code I'll be able to see what the machine does, but not why it does it. And the later is actually more important for understanding a piece of code.

https://docs.julialang.org/en/v1/manual/metaprogramming/#An-advanced-example

It was here. Ah, I can remove the generated and it will show me what comes out.

```
struct Qwe2
    id
    a
    b
end

function params(rv)
  fields = [Expr(:., :rv, QuoteNode(f)) for f in fieldnames(rv) if f !== :id]
  Expr(:tuple, fields...)
end

params(Qwe2)
```
```
:((rv.a, rv.b))
```

I see. Ok, now I understand the purpose of this.

Is there a way to apply a struct with a symbol in a variable?

https://discourse.julialang.org/t/access-a-struct-field-from-a-string/44337

```jl
q = Qwe(1,2)
getproperty(q,:b)
```

I can just use the `getproperty` function. Ok. Expertise is built with small steps like these.

11am.

```jl
"Parameters of `rv`"
function params(rv::PrimRandVar)
  Tuple(getproperty(rv,prop) for prop in fieldnames(PrimRandVar) if prop !== :id)
end
```

Let me go with this.

```
Exception has occurred: ArgumentError
ArgumentError: type does not have a definite number of fields
```

Huh.

```
Tuple(getproperty(rv,prop) for prop in fieldnames(typeof(rv)) if prop !== :id)
```

How about this then?

11:15am.

```jl
using Omega

x = normal(0,1)
rand(x)
```

Ok, I've stepped all the way through this simple program.

11:20am. Hmmmm, maybe it is simpler than it seems, but Julia is a rough language to be making a compiler in. The extreme amount of indirection is one aspect of it. The other aspect is that the lack of top down typing will make refactoring difficult.

Going what I've seen so far, Zenna is quite skilled at programming. Though I can't grade the overall design until I've grasped it completely. The best way to do that will be to work on my own PPL using Omega as a reference.

I'll have to go through the Omega docs again and step through the examples.

11:30am.

```jl
using Omega

nflips = 4
weight = β(2.0, 2.0)
coinflips_ = [bernoulli(weight, Bool) for i = 1:nflips]
coinflips = randarray(coinflips_)
observations = [true, true, true, false]
condition = coinflips ==ᵣ observations
weight_samples = rand(weight, condition, 10; alg = RejectionSample)
```

This is a more complex one.

Ok, let me do it. I need to have courage. I'll go through all the example in the docs. Even by the end of it I'll still be far from grasping the library, but I will have learned something. And that will allow me to build on the subsequent steps.

11:45pm.

```jl
@generated function maybelift(f, args...)
  if any([arg <: RandVar for arg in args])
    :(liftciid(f, args...))
  else
    :(f(args...))
  end
end
```

Now this is giving me trouble. Well, it will be easy to rewrite.

```jl
function maybelift(f, args...)
  if any([arg <: RandVar for arg in args])
    liftciid(f, args...)
  else
    f(args...)
  end
end
```

Let me try this.

```jl
if any([typeof(arg) <: RandVar for arg in args])
```

This should be a typeof.

12:15pm. This is rough as expected. Let me have breakfast here.

Stepping through the code was instructive for a bit, but it is not giving me much inspiration. I should aim to design a basic library that can just do conditioning. That will get my neurons firing.

But I want to go a bit further first and try out some of the lifting examples.

I should read the Intro to PPL paper after that. Maybe it updated between now and when I got it 3 years ago.

1:35pm. Let me watch the latest MagiReco ep and I will resume."