"10:10am. I am up.
10:15am. Let me chill a bit and then I will start. I am thinking what I should do today. Before I move to training I want to take a look at a certain issue. It happened even on that toy task.

When training the critic, after a while it would saturate and diverge. I want to know why the divergence happens. Should it not just stop optimizing once it saturates. Why does the divergence happen?

10:45am. Done chilling. Let me finally start. I'll do that by playing with the softmax.

I do not want to set it to run only to have it diverge after a while. I need to figure out how far do I need to go in order to stabilize it.

10:55am.

```
import torch
x = torch.tensor([100,10,0],dtype=torch.float,requires_grad=True)
b = torch.tensor([0,10,100],dtype=torch.float)
o = torch.softmax(x*100000000,-1)
o.backward(b)
x.grad
```
```
tensor([0., 0., 0.])
```

I can't get it to blow up by simply multiplying the inputs. This is roughly what I expected and it confuses me. Just how is it possible that it is blowing up in the first place?

Let me copy the last ui_leduc and then I'll look into simple test again. It was blowing up on it after all.

```
return reward, state_probs
```

Let me modify this so I get state probs back. Now let me play with simple test again. I need to figure out why it could be diverging.

```
def loop(n):
    for b in range(n):
        probs = run(True,False,False)
        probs = run(True,False,False)
        # print('head:',head)
        probs = run(False,True,False)
        # print('probs',probs)
        # print('-value.weight.grad',-value.weight.grad)
        control.optimize([value],learning_rate=0.1)
        head[:,:] *= 0.01
    probs = run(True,False,False)
    # print(probs.sum(0))
    print(probs.mm((head[:size_action,:] / head[size_action:,:]).t()))
torch.set_printoptions(sci_mode=False)
loop(50)
loop(100)
loop(300)
loop(1000)
```

```
tensor([[  1.0040],
        [ 10.0699],
        [102.4825],
        [964.0833]], grad_fn=<MmBackward>)
tensor([[    1.0000],
        [   10.0000],
        [  100.0000],
        [ 1000.0001]], grad_fn=<MmBackward>)
tensor([[   1.0000],
        [  10.0000],
        [ 100.0000],
        [1000.0000]], grad_fn=<MmBackward>)
tensor([[nan],
        [nan],
        [nan],
        [nan]], grad_fn=<MmBackward>)
```

Yes. Why do I get nans here?

Just what is happening to the weights?

```
print(value)
```

Let me print out the value matrix.

```
tensor([[  1.0147],
        [ 10.0878],
        [119.3894],
        [781.7453]])
Parameter containing:
tensor([[-4.9264,  5.4825, -3.3818, -3.6008],
        [-4.9401,  5.1579, -3.2608, -3.1113],
        [ 5.3922, -5.4056, -4.8022, -5.0616],
        [-4.7883, -2.4747, -2.4115, -3.0712],
        [ 5.3529, -5.4698, -5.1240, -5.4797],
        [-4.5366, -3.4796,  0.4898,  5.4871],
        [-5.0243, -2.9175,  3.9980, -1.7632],
        [ 5.4685, -5.4045, -5.0744, -5.0336]], requires_grad=True)
tensor([[    1.0000],
        [   10.0000],
        [  100.0000],
        [ 1000.0000]])
Parameter containing:
tensor([[-14.9265,  14.0825, -13.3818, -13.6008],
        [-14.9401,  13.7579, -13.2608, -13.1113],
        [ 15.3922, -15.4057, -14.8022, -15.0616],
        [-14.7883, -12.4747, -12.4115, -13.0712],
        [ 15.3529, -15.4698, -15.1240, -15.4798],
        [-14.5366, -13.4796,  -9.5102,  15.4871],
        [-15.0243, -12.9175,  13.9980, -11.7632],
        [ 15.4685, -15.4045, -15.0744, -15.0337]], requires_grad=True)
tensor([[   1.],
        [  10.],
        [ 100.],
        [1000.]])
Parameter containing:
tensor([[-44.9263,  24.3826, -43.3817, -43.6007],
        [-44.9400,  24.0579, -43.2607, -43.1112],
        [ 45.3920, -45.4055, -44.8021, -45.0615],
        [-44.7882, -42.4746, -42.4115, -43.0711],
        [ 45.3527, -45.4697, -45.1239, -45.4796],
        [-44.5365, -43.4795, -39.5102,  18.4871],
        [-45.0242, -42.9174,  43.9979, -41.7631],
        [ 45.4684, -45.4044, -45.0743, -45.0335]], requires_grad=True)
tensor([[nan],
        [nan],
        [nan],
        [nan]])
Parameter containing:
tensor([[-51.2262,  32.7826, -51.6816, -85.3001],
        [-51.2399,  32.6579, -51.6606, -85.3106],
        [ 51.8919, -72.2051, -52.4020, -85.3609],
        [-51.1881, -71.3741, -51.2113, -85.3705],
        [ 51.8526, -72.2693, -52.6237, -85.3790],
        [-51.0364, -71.7791, -49.8100,  18.6871],
        [-51.2241, -71.5170,  54.2978, -84.5625],
        [ 51.9683, -72.2040, -52.5741, -85.3329]], requires_grad=True)
```

It sometimes does not blow up.

Ah, this is actually very convenient. Probably the weights are intact because `torch.sign` of a nan is 0.

```
    probs = run(True,False,False)
    print(probs)
    print(probs.mm((head[:size_action,:] / head[size_action:,:]).t()).detach())
    print(value.weight)
```

Let me print out the probs. In fact, why am I optimiznig here.

```
probs = run(False,False,False)
```

Let me do this.

```
tensor([[    0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.4463,
             0.5537,     0.0000],
        [    0.0000,     0.0673,     0.0000,     0.0000,     0.0000,     0.0000,
             0.0000,     0.9327],
        [    1.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,
             0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000,     1.0000,     0.0000,     0.0000,
             0.0000,     0.0000]], grad_fn=<SoftmaxBackward>)
tensor([[nan],
        [nan],
        [nan],
        [nan]])
Parameter containing:
tensor([[-52.0148, -70.6848,  53.9059, -82.8704],
        [-51.6705,  30.6870, -54.4270, -85.3165],
        [-45.9462, -70.6984, -54.3122, -85.6000],
        [-51.8623, -70.6755, -50.2236,  18.4224],
        [-51.7992, -70.6652, -53.0179, -82.8914],
        [ 57.9199, -70.6724, -54.5803, -85.6408],
        [ 58.1356, -70.6672, -54.6438, -85.3999],
        [-51.8516,  33.3159, -54.5467, -85.4582]], requires_grad=True)
```

Ah, the probs are fine.

```
print(probs.mm((head[:size_action,:] / head[size_action:,:]).t()).detach())
```

Maybe it is this division that is the problem. Damn. That can only be it.

```
head[size_action:,:] = max(2 ** -149,head[size_action:,:])
```

Let me try it like this.

```
head[size_action:,:] += 2 ** -149
```

It won't broadcast. Let me try this then.

Yes, now it is decent.

11:20am.

```
head_decay = 2 ** -2
```

I've set the set to 0.25. As long as it is >0.5 it cannot decay to zero, but otherwise it could.

11:35am. Why do I have such an old version of torch?

https://pytorch.org/docs/stable/generated/torch.nan_to_num.html

I really need this damn function after all.

11:35am. Did it go up by 0.2 versions since I last installed it? Well whatever. Right now I need to wait for it to download 2.6Gb. This won't take too long.

After that instead of fiddling with that smallest float value I'll be able to just convert the nans to zeroes.

```
values = torch.nan_to_num_(head_weighted_values / head_value_weights) # [action_dim,state_dim]
```

Like this.

11:45am.

```
optimize([policy],learning_rate=2 ** -8)
```

I am going to try training with this again just to see if it blows up.

11:50am. For some reason the install seems to be stuck at 100. Oh it is done.

```
Traceback (most recent call last):
  File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_leduc18 (signSGD + infNorm + EM value nets)/control.py", line 186, in <module>
    run(**main())
TypeError: run() argument after ** must be a mapping, not create_args.Closure0
(base) PS C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\ui_leduc18 (signSGD + infNorm + EM value nets)>
```

Why am I getting this kind of error here?

```
values = torch.nan_to_num_(head_weighted_values / head_value_weights,0.0) # [action_dim,state_dim]
```

Let me do it like this. It says the default is zero.

```
values = torch.nan_to_num_(head_weighted_values / head_value_weights) # [action_dim,state_dim]
```

No it is fine. I've checked.

Ah, the stupid thing is probably confusing the holdem create_args for the one I have here.

12pm. I'll let the create_nn_agent with the 2 ** -8 learning rate run for a bit. That one time where it blew up I did not print out the intermediate steps so I am not sure whether it was towards the end that the training collapsed. I am also not sure if this was the crucial issue.

```
Training.
24
49
74
99
124
149
174
199
224
249
274
299
324
349
374
399
424
449
474
499
Averaging.
29
The mean reward vs_self is -0.3396604061126709
59
The mean reward vs_self is -0.1704833209514618
89
The mean reward vs_self is 0.06835100054740906
119
The mean reward vs_self is -0.11712346971035004
149
The mean reward vs_self is -0.07773110270500183
179
The mean reward vs_self is 0.21756164729595184
209
The mean reward vs_self is -0.17396749556064606
239
The mean reward vs_self is -0.326713502407074
269
The mean reward vs_self is -0.11830351501703262
299
The mean reward vs_self is -0.06860412657260895
329
The mean reward vs_self is 0.23224356770515442
359
The mean reward vs_self is -0.10014495998620987
```

This definitely did not blow up. Let me try evaluating it.

```
The mean is -0.168604776263237
```

Hmmm, this is not that good. Maybe it would benefit from a lower LR.

```
The mean is -0.17606402933597565
```

I run it again and yes this is it.

I think running it with something like 2 ** -8 for 250 iterations, 2 ** -9 for 250 iterations and then doing averaging with 2 ** -10 for 250 iterations would be the best.

12:20pm.

```py
    n = 250
    m = 250
    def train(policy_lr=2 ** -8):
        print('Training.')
        for a in range(n):
            run(policy_lr=policy_lr)
            if (a + 1) % 25 == 0: print(a)
    def avg(policy_lr=2 ** -10):
        print('Averaging.')
        for a in range(m):
            run(policy_lr,True)
            if (a + 1) % 25 == 0:
                print(a)
                r : np.ndarray = vs_self(batch_size * 2 ** 4,neural_player())
                print(f'The mean reward vs_self is {r.mean()}')
    train()
    train(2 ** -9)
    avg()
    with open(f"dump/nn_agent_{2*n+m}.obj",'wb') as f: pickle.dump((value,policy,head),f)
```

Let me do this.

12:20pm. I'll admit -0.17 is bad, but it should not be a blowup.

12:25pm.

```
Training.
24
49
74
99
124
149
174
199
224
249
Training.
24
49
74
99
124
149
174
199
224
249
Averaging.
24
The mean reward vs_self is -0.013280516490340233
49
The mean reward vs_self is -0.42692673206329346
74
The mean reward vs_self is -0.47462165355682373
99
The mean reward vs_self is -0.21579861640930176
124
The mean reward vs_self is -0.27605539560317993
149
The mean reward vs_self is -0.20030830800533295
174
The mean reward vs_self is -0.1726757138967514
199
The mean reward vs_self is -0.29776525497436523
224
The mean reward vs_self is -0.1699642688035965
249
The mean reward vs_self is -0.31906914710998535
```

Hmmm, will this be fine? All the rewards are to the negative side.

Well, let me try running it.

```
The mean is -0.153333380818367
```

Harsh.

```
The mean is -0.15237531065940857
```

I got 0.6-0.7 points better last time.

```
    train(2 ** -9)
    train(2 ** -10)
    avg(2 ** -10)
```

Let me try training it like this then. I want to figure out what a sensible setting is. Maybe 2 ** -8 is too much either way. Maybe the init is bad. Who knows.

12:30pm. Let me get breakfast here.

There is no point in wasting time just watching this run.

```
Training.
24
49
74
99
124
149
174
199
224
249
Training.
24
49
74
99
124
149
174
199
224
249
Averaging.
24
The mean reward vs_self is -0.3365296721458435
49
The mean reward vs_self is -0.2586092948913574
74
The mean reward vs_self is -0.202321857213974
99
The mean reward vs_self is -0.3308716416358948
124
The mean reward vs_self is -0.2742278277873993
149
The mean reward vs_self is -0.1398211270570755
174
The mean reward vs_self is -0.1644824743270874
199
The mean reward vs_self is -0.16069552302360535
224
The mean reward vs_self is -0.3061845898628235
249
The mean reward vs_self is -0.16831129789352417
The mean is -0.19135403633117676
The mean is -0.19275611639022827
The mean is -0.19324909150600433
```

It is getting worse and worse.

At this level, is it just not getting enough training?

```
torch.nn.LayerNorm(mid,elementwise_affine=False),
```

Let me turn off the afine operations.

```
    train(2 ** -9)
    train(2 ** -9)
    avg(2 ** -9)
```

Let me just do this. This worked for me last time.

Let me get breakfast.

```
Training.
24
49
74
99
124
149
174
199
224
249
Training.
24
49
74
99
124
149
174
199
224
249
Averaging.
24
The mean reward vs_self is -0.2506672739982605
49
The mean reward vs_self is 0.10051149129867554
74
The mean reward vs_self is -0.4323579668998718
99
The mean reward vs_self is -0.08950936794281006
124
The mean reward vs_self is -0.20247682929039001
149
The mean reward vs_self is -0.07092894613742828
174
The mean reward vs_self is -0.10144341737031937
199
The mean reward vs_self is 0.0343448668718338
224
The mean reward vs_self is -0.17629456520080566
249
The mean reward vs_self is -0.02894347533583641
The mean is -0.14094123244285583
The mean is -0.13815122842788696
The mean is -0.13880586624145508
```

Maybe those few times were particularly good runs? I tend have beginner's luck when it comes to training NNs.

```
    n,m=600,300
    train(2 ** -9,n)
    avg(2 ** -9,m)
    with open(f"dump/nn_agent_{n+m}.obj",'wb') as f: pickle.dump((value,policy,head),f)
```

Let me try for 900 iterations then.

1:10pm. Still even a 0.1 difference is not that particularly huge unless you are trying to squeeze it down as much as possible. The trained agent would be usable and fun to play against. Bad inits I cannot get around easily, but deeper architectures and more parameters will help. I will also iterate the agents which will give me a sampling of initializations.

Training against the baselines in a supervised fashion should speed things up a significant amount.

1:10pm. Let me watch an ep or two Thunderbolt Fantasy S3 and then I'll get back to this. Right now it is running in the background and I should be having breakfast instead of focusing on this."