"1:35pm. Let me resume. Today things are going nicely. I spent the night thinking about what I should expect. I did think that rarer cases might get offset by the earlier ones, so dividing by the self probability might not turn out too horrible, but the stability I am encountering exceeded my expectations.
A batch size of 1024, no doubt plays a role in this. Maybe I'll need to use a large one for NL Holdem, but either way is fine for me.

Right now, let me see what happens when I let it self play. Will it diverge or do well.

```
inl main () =
    !!!!Import("torch")
    !!!!Import("torch.distributions")
    !!!!Import("torch.optim")
    inl game = leduc.game()
    inl net = agent.neural.create_small_leduc_net()
    inl policy,value = agent.neural.models net
    inl lr : f32 = 2 ** -13 // Note: Be careful of Cython integer power bug. `integer ** negative_integer == 0` in raw Cython.
    $"print('The learning rate is 2 **',torch.log2(torch.scalar_tensor(!lr)).item())"
    inl opt : obj = $"torch.optim.SGD([{'params':!policy.parameters()},{'params':!value.parameters()}],lr=!lr)"
    loopw.for' (from: 0i32 nearTo: 100) fun _ =>
        $"!opt.zero_grad()"
        inl r = train.vs_self 1024 (agent.neural.policy 0 net) game
        $"!opt.step()"
        $"print(numpy.mean(!r))"
    inl r = train.vs_one 1024 (agent.neural.policy 0 net) agent.uniform.policy game
    $"print(numpy.mean(!r))"
```

Let me give this a shot. One incidental benefit that I've gotten is that it is easy to evaluate the current reward since optimization is left for after the gradients have been accumulated.

```
The learning rate is 2 ** -13.000831604003906
0.1376043
-0.61579585
-0.046606265
0.0025028177
-0.39538646
-0.6283753
-2.480432
-3.0
-0.020507812
-0.021484375
-0.234375
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
Traceback (most recent call last):
  File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_leduc14 (batch)/neural_test_run.py", line 5, in <module>
    print(main())
  File "neural_test.pyx", line 2719, in neural_test.main
    cpdef void main() except *:
  File "neural_test.pyx", line 2951, in neural_test.main
    v78 = method11(v21, v20, v26)
  File "neural_test.pyx", line 1741, in neural_test.method11
    v205 = method11(v0, v1, v195)
  File "neural_test.pyx", line 1741, in neural_test.method11
    v205 = method11(v0, v1, v195)
  File "neural_test.pyx", line 1741, in neural_test.method11
    v205 = method11(v0, v1, v195)
  File "neural_test.pyx", line 1766, in neural_test.method11
    raise Exception("The value prediction is nan.")
Exception: The value prediction is nan.
```

It diverges. For self play, I am going to have to use a lower LR.

```
inl lr : f32 = 2 ** -15 // Note: Be careful of Cython integer power bug. `integer ** negative_integer == 0` in raw Cython.
```

Let me do this. -13 is unealistic after all.

...Why is it taking Cython so long to finish compilation. It is super slow.

```
The learning rate is 2 ** -14.977372169494629
-0.24620278
-1.0444626
-0.07010141
-0.1904796
0.1142395
-0.08927864
0.042909294
-1.469594
-0.01846522
0.45337725
0.2096734
0.24029428
0.020518411
-0.21579847
1.1223785
-0.070751995
1.5429723
0.048829548
0.2981849
0.7031648
0.11914453
0.055245478
-0.20410483
0.9335662
0.7288915
0.3046875
0.12695312
-0.16503912
0.05078125
-0.16503906
-0.08886719
-0.038085938
0.16503906
0.07617188
0.46972656
0.11425781
0.06347656
-0.19042969
-0.48242188
0.36816406
-0.076171875
-0.13964844
0.36816406
-0.5078125
0.0
-0.35546863
0.050781474
-0.05078125
-0.26660156
-0.15234375
5.9604645e-08
-0.46972644
0.08886719
0.55859375
-0.26660147
-0.44433597
-0.11425781
-0.19042969
-0.11425769
0.95214844
-0.5458986
0.11425779
-0.01269532
0.16503912
0.6855469
-0.12695307
0.8125
-0.7871094
0.114257805
0.10156249
-0.025390595
0.1015625
0.2666015
0.36816406
-0.079868704
-0.43164057
0.2158204
0.16503906
-0.088851094
0.17379105
0.42578125
0.3798828
0.33016944
1.3837891
0.59375
0.35156247
0.8671875
0.5205079
-0.013671875
0.73535156
0.4208984
0.6240234
0.3310547
0.09765616
0.13671875
0.27734363
1.1513698
0.5487902
0.3398014
0.21290678
---
1.2880859
```

Seems fine. Let me try a large batch size against the uniform player.

```
inl r = train.vs_one 102400 (agent.neural.policy 0 net) agent.uniform.policy game
```

Something like this.

```
The learning rate is 2 ** -14.977372169494629
-0.08537504
-0.29259914
0.046919912
-3.0
-2.9999633
-4.158407
0.6474609
0.5202337
0.45703125
0.3046875
-0.7109375
0.2919922
-0.5078125
0.11425232
-0.42330262
-0.4520875
-0.98289394
-0.09136866
-0.40527344
-0.036132812
-0.083984375
-0.06542969
-0.12780294
-0.67582417
-0.22465037
-0.1777342
-1.6713989
-0.62402403
-0.9156213
-0.4124698
0.50302166
0.69841707
0.13609123
0.57128906
0.5078125
0.1015625
-0.40625
0.3046875
-0.12695312
-0.64746094
0.7236328
-0.15234375
-0.3173828
0.46972656
0.77441406
0.8251953
0.17773438
1.1933594
-0.25390613
-0.26660156
0.33007812
0.24121094
1.4901161e-08
0.2285156
-0.08886719
-0.3935547
0.24121094
0.07617185
-0.30468744
0.7998047
0.48242188
0.4189453
-0.0126953125
-0.076171875
-0.03808596
0.33007812
0.12695312
-0.34277338
-0.64746094
0.025390685
0.13964856
0.17773429
0.20312513
0.34277344
0.0126953125
-0.114257954
-0.22851558
-0.31738275
0.3935547
-0.3808593
-0.1015624
0.0126953125
0.3173828
-0.20312501
0.07617186
0.64746106
-0.19042975
0.40625
-0.44433585
0.67285156
0.012695342
-0.2919922
-0.076171875
0.25390625
0.27929693
0.49511722
-0.15234375
-0.5839843
-0.17773446
-0.43164057
---
1.2369629
```

Seems accurate.

```
    loopw.for' (from: 0i32 nearTo: 100) fun _ =>
        $"!opt.zero_grad()"
        inl r = train.vs_self 1024 (agent.neural.policy 0 net) game
        $"!opt.step()"
        $"print(numpy.mean(!r))"
    $"print('---')"
    inl r = train.vs_one 102400 agent.uniform.policy (agent.neural.policy 0 net) game
    $"print(numpy.mean(!r))"
```

What if I changed the position to player two?

Hmmm, this run was weird. It oscilated much less wildly.

```
The learning rate is 2 ** -14.977372169494629
0.03921088
-0.05696024
-0.04548525
0.020609299
0.009824835
-0.035120744
-0.024392098
0.018567968
-0.001946656
-0.028316807
-0.0009742901
-0.0078114234
-0.043944787
-0.044921547
0.010742352
-0.040039
-0.030273404
-0.020507785
-0.02832029
-0.017578127
0.038085945
0.021484375
0.01171875
-3.7252903e-09
-0.052734375
-0.0107421875
-0.016601562
-0.006835932
-0.003906249
0.015625004
-0.049804688
-0.028320312
0.018554691
0.00097656157
-0.028320318
0.0234375
-0.0019531231
-0.038085938
-0.038085938
-0.0009765625
-0.0029296866
0.033203136
0.0087890625
-0.0068359384
0.03125
-0.03222656
-0.014648439
-0.009765625
-0.0009765625
0.041015625
-0.030273434
0.01660156
0.010742187
0.010742189
0.0068359375
0.009765623
0.053710945
0.033203125
-0.009765625
0.022460934
0.056640632
0.009765643
0.006835969
-0.0058593694
0.009765629
0.020507827
-0.009765621
0.044921875
1.8626451e-09
-0.016601562
0.0107421875
-0.0107421875
-0.04394532
-0.0048828144
0.033203106
0.022460938
0.018554699
-0.0126953125
0.02734375
0.008789077
0.046875007
-0.012695292
0.021484384
0.01855469
-0.03027343
0.011718739
0.0019531245
0.048828125
0.0234375
-0.01953125
0.00390625
0.041992188
0.028320352
-0.01660156
-0.0546875
-0.041015625
-0.02636721
0.006835931
-0.0009765625
-0.024414062
---
0.01569336
```

No this is not good. What the hell?

```
The learning rate is 2 ** -14.977372169494629
-0.32119146
-0.4231985
0.6856677
-0.02539028
-0.10156205
0.017578125
0.0068359375
-0.20312364
-0.33007798
0.22851562
0.076171905
-0.022460938
11.26477
-3.0
0.06738281
-0.038085938
-0.01953125
-0.0087890625
-0.016601562
0.015625
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
939524100.0
Traceback (most recent call last):
  File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_leduc14 (batch)/neural_test_run.py", line 5, in <module>
    print(main())
  File "neural_test.pyx", line 2727, in neural_test.main
    cpdef void main() except *:
  File "neural_test.pyx", line 2959, in neural_test.main
    v78 = method11(v21, v20, v26)
  File "neural_test.pyx", line 1669, in neural_test.method11
    v161 = torch.distributions.Categorical(v160).sample().numpy()
  File "C:\Users\Marko\anaconda3\lib\site-packages\torch\distributions\categorical.py", line 107, in sample
    samples_2d = torch.multinomial(probs_2d, sample_shape.numel(), True).T
RuntimeError: invalid multinomial distribution (encountering probability entry < 0)
```

Now it outright crashed.

It failed the previous run as well.

```
The learning rate is 2 ** -14.977372169494629
-0.22163987
-0.20036934
-0.67984587
-1.7878007
-3.323073
0.22702801
-0.017578132
0.0048828125
0.01562501
0.041992195
0.018554686
-0.014648443
-0.04101563
0.00097656157
0.0234375
0.008789059
-0.02343749
0.009765625
0.009765627
0.031249989
-0.025390625
0.021484375
-0.02148437
0.046874974
-0.0546875
-0.018554702
5.5879354e-09
-0.025390625
0.014648449
0.017578125
-0.04101562
-0.005859459
-0.0712912
-0.035173666
-0.0060599027
-0.23747058
-0.26534715
-0.21499649
-0.33453092
-0.24709637
-0.2378708
-0.28429595
-0.3227797
-0.20814355
-0.28861827
-0.22282904
-0.29743916
-0.34347683
-0.18097055
-0.38463667
-0.21788126
-0.17766173
-0.34880704
-0.12720674
-0.106993705
-0.023705868
0.032025017
-0.027382936
0.018551685
-0.02832035
-0.03027344
-0.038085938
-0.010742199
-0.0048828106
-0.009765627
0.011718749
-0.0009765625
-0.023437493
0.0019531199
-0.02832032
0.024414062
0.003906264
-0.005859375
0.0234375
0.03125
-0.009765625
-0.0068359347
0.0126953125
0.0
0.028320312
-0.0048828158
0.028320312
-0.0058593675
-0.0068359394
-0.0068359375
0.0078125
0.020507816
-4.656613e-10
0.040039062
0.012694891
0.06041792
-0.003768906
-0.055232912
-0.04635337
-0.024439692
-0.0100982245
-0.044921875
0.050781224
0.009765627
-0.039062507
---
0.00078063546
```

Does this have to do anything with me switching places in the test? It really should not.

```
...
-0.043945305
-0.024414076
0.032226562
0.008789077
---
0.01415039
```

It starts off mad, and then it become subdued. Let me swap the places back.

```
inl r = train.vs_one 102400 agent.uniform.policy (agent.neural.policy 0 net) game
```

```
inl r = train.vs_one 102400 (agent.neural.policy 0 net) agent.uniform.policy game
```

Checking this really should not have anything to do with anything. I am 99% I just got lucky during the first two runs.

```
0.025390625
-0.0390625
-0.041992188
-0.033203125
---
0.007578125
```

It keeps collapsing. I am guessing both sides converge to just folding or something.

It is really funny that I initially got it to work.

```
    inl r = train.vs_one 102400 agent.uniform.policy (agent.neural.policy 0 net) game
    // inl r = train.vs_one 102400 (agent.neural.policy 0 net) agent.uniform.policy game
```

Let me go back to this.

```
    inl lr : f32 = 2 ** -14 // Note: Be careful of Cython integer power bug. `integer ** negative_integer == 0` in raw Cython.
    $"print('The learning rate is 2 **',torch.log2(torch.scalar_tensor(!lr)).item())"
    inl opt : obj = $"torch.optim.SGD([{'params':!policy.parameters()},{'params':!value.parameters()}],lr=!lr)"
    loopw.for' (from: 0i32 nearTo: 100) fun _ =>
        $"!opt.zero_grad()"
        inl r = train.vs_self 1024 (agent.neural.policy 0 net) game
        $"!opt.step()"
        $"print(numpy.mean(!r))"
    $"print('---')"
    inl r = train.vs_one 1024 (agent.neural.policy 0 net) agent.uniform.policy game
```

Let me try -14.

Nope, it collapsed again.

2:05pm. -16 fails. I am amazed that the very first two runs worked, and now everything else is failing.

If it weren't for that I'd start suspecting a code error.

```
inl lr : f32 = 2 ** -17 // Note: Be careful of Cython integer power bug. `integer ** negative_integer == 0` in raw Cython.
```

Let me try -17.

```
The learning rate is 2 ** -16.931568145751953
-0.15122908
-0.34179226
0.11505626
0.118165016
-0.08325203
0.037396416
-0.4478014
0.30270976
0.05854044
-0.018153176
-0.24027808
0.30503452
0.07537705
0.07190435
-0.10352208
-0.2086649
-0.078428
0.031534053
0.100839354
0.11734636
0.04639128
-0.019702446
0.09310622
-0.042858075
0.048064657
-0.012758322
0.11608489
0.40516514
-0.12556651
0.20109883
-0.1263285
0.031008452
0.104126595
0.016280632
0.15478694
-0.07069421
0.29671645
0.3379214
0.13013008
0.017260283
0.04104491
0.027482297
0.030565046
-0.056781176
-0.02248228
0.04690636
-0.004970759
0.008861694
-0.01865349
0.020503163
-0.028323542
-0.009767575
0.015623745
0.00097583793
-0.021484712
0.00097632874
-0.017578192
-0.08203128
-0.007812418
-0.018554598
0.02832039
0.07324228
0.019531326
-0.003906183
-0.0009765215
-0.007812474
0.004882846
-0.0029296519
0.031250022
0.024414068
-0.035156243
-0.016601544
0.03808596
0.006835933
0.050781257
-0.02050781
0.012695308
-0.024414064
-0.0019531241
-0.027343754
0.0078125065
-0.07910158
-0.065429695
-0.041992188
0.03222657
0.037109375
0.008789066
0.0234375
-0.010742189
0.000976556
0.034179688
0.028320314
0.029296875
-0.005859375
0.02734375
-0.0234375
-0.014648443
-0.015625
-0.02246094
-0.008789062
---
-0.14453125
```

It keeps collapsing.

Let me try removing the CFR reweighting.

```
inl regret_prob _ = 1
```

I'll just do this little thing.

2:15pm. It does well initialy but it collapses. Removing the reweighting had nothing to do with it.

Ok. I have two ideas in mind.

1) Dropout.
2) Duality gap training.

I am really, really lucky that I got two good runs right off the bat which clearly shown me that minimax training itself is busted.

```
The learning rate is 2 ** -14.977372169494629
0.03631962
0.03279014
-0.58498156
-0.72331274
0.34045973
-0.34059477
0.20469394
-0.5277668
-0.39368886
-0.18598592
0.17756292
1.2772789
1.6371204
0.30468774
0.11425781
0.38085938
-0.27929688
-0.1015625
-0.48242185
-0.1015625
-0.55859375
0.64746094
0.101562545
0.24121094
0.08886719
0.012695283
-0.3046875
-0.25390625
0.1015625
-0.24121094
-0.3554687
-0.21582031
0.10156271
-0.3300552
0.034375384
-0.19015002
0.43095404
-0.6850923
0.437342
0.61811626
0.8381638
-0.5042224
-0.2030608
0.2667876
-0.29198825
-0.8250692
-0.11775556
0.55917156
0.07617522
0.12695357
0.31738293
0.11425783
-0.203125
0.16503906
0.26660156
0.26660156
0.77441424
0.2285156
0.08886719
0.050781175
-0.05078122
0.31738308
-0.24121095
0.4824221
0.13964844
0.012695283
0.08886719
0.025210097
-1.1305945
-0.31540757
-0.16016847
0.25416017
-0.1679687
0.041992124
0.17089832
0.1640625
-0.23535156
-0.09863283
-0.033203065
-0.022460923
0.14550781
-0.37988284
-0.3974609
0.21191406
-0.13671875
-0.42285156
-0.55566394
-0.15332043
0.12792972
-0.55078125
0.04296875
-0.18164062
-0.016601562
-0.17382812
-0.015625
-0.029296804
0.63964844
-0.24316406
0.12792969
0.004882727
---
-2.1357422
```

Oh interesting. It being subdued might not mean that it collapses. It might have pockets of stability.

This bit here was not too bad.

```py
    if p < 0. or p > 1.:
        raise ValueError("dropout probability has to be between 0 and 1, "
                         "but got {}".format(p))
    return (_VF.dropout_(input, p, training)
            if inplace
            else _VF.dropout(input, p, training))
```

This is really annoying. This is how dropout is implemented. There is no way for me to get the key like this.

```py
class _DropoutNd(Module):
    __constants__ = ['p', 'inplace']
    p: float
    inplace: bool

    def __init__(self, p: float = 0.5, inplace: bool = False) -> None:
        super(_DropoutNd, self).__init__()
        if p < 0 or p > 1:
            raise ValueError("dropout probability has to be between 0 and 1, "
                             "but got {}".format(p))
        self.p = p
        self.inplace = inplace

    def extra_repr(self) -> str:
        return 'p={}, inplace={}'.format(self.p, self.inplace)
```

This is how the dropout module is implented. It seems `self.training` is automatically passed along by the autograd engine.

Ok. I am going to have to implement my own dropout function.

2:40pm. It seems I will have chores to do soon.

Let me do this for 15m and I will take some time away from the screen. I am thinking how to do dropout right now.

Let me copy the project. I want to leave what I here as it is. I am not sure if dropout will work, and if it does not, I'll move to the duality gap method.

How did they get it to train in that paper anyway without the DG method?

Let me investigate that first.

https://arxiv.org/abs/1810.09026
Actor-Critic Policy Optimization in Partially Observable Multiagent Environments

Does this thing have code? Nope.

> In the domains we tested, we observed that the variance in returns was high and hence we performed multiple policy evaluation updates (q-update for ∇QPG , ∇RPG, and ∇RMPG, and v-update for A2C) followed by policy improvement (policy gradient update). These updates were done using separate SGD optimizers with their respective learning rates of fixed 0.001 for policy evaluation, and annealed from a starting learning rate to 0 over 20M steps for policy improvement. (See Appendix G for exact values). Further, the policy improvement step is applied after Nq policy evaluation updates. We treat Nq and batch size as a hyper parameters and sweep over a few reasonable values. In order to handle different scales of rewards in the multiple domains, we used the streaming Z-normalization on the rewards, inspired by its use in Proximal Policy Optimization (PPO) [76]. In addition, the agent’s policy is controlled by a(n inverse) temperature added as part of the softmax operator. The temperature is annealed from 1 to 0 over 1M steps to ensure adequate state space coverage. An additional entropy cost hyper-parameter is added as is standard practice with Deep RL policy gradient methods such as A3C [58, 76]. For NFSP, we used the same values presented in [49]

This is quite complicated. If I am going to be doing this, I might as well implement the duality gap method instead.

Let me copy the project, and I'll implement my own dropout class.

3pm. Let me stop here."