"9pm. Got some advice to just use del instead of setting things to none. Let me do that then.
11:20pm. https://bartoszsypytkowski.com/writing-high-performance-f-code/

This is something to keep in mind. The way to write high performance F# code is something even I am not familiar with.

> Many other languages with algebraic data types optimize the size according to formula sizeof(tag field) + max([sizeof(ADT case)]). But not F# - what we see here is sizeof(int) + sum([sizeof(ADT case)]):

This is interesting. I wonder why this is the case?

> The reason behind this is a limtation of .NET platform - while technically it's possible to use LayoutKind.Explicit to implement F# in similar manner to i.e. Rust, it works only as long as we don't try to use it together with generics: .NET cannot make safe guesses in that situation. In result, used memory space for struct-based DU is a sum of all fields defined all cases. For this reason good candidates for struct DU's are usually the ones with very small overall number of fields. F# standard library makes good use of these in form of Result<'t,'e> and 't voption types.

I had no idea this was the case.

2/5/2021

10am. Focus me.

Let me do the pass right now.

Ah, no wait. I need to do some testing first.

```
cdef int loop_tail(int s, int i, int nearTo):
    if i < nearTo: return loop_tail(s+i,i+1,nearTo)
    else: return s
cpdef int sequence_tailrec(int fron, int nearTo):
    return loop_tail(0,fron,nearTo)

cdef int loop(int i, int nearTo):
    if i < nearTo: return i + loop(i+1,nearTo)
    else: return 0
cpdef int sequence(int fron, int nearTo):
    return loop(fron,nearTo)
```

Let me be thorough in testing tailrec.

```
cdef int loop_tail(int s, int i, int nearTo):
    if i < nearTo:
        q = "qwe"
        return loop_tail(s+i,i+1,nearTo)
    else: return s
```

What happens if I do this?

It diverges. This is what I feared.

```
cdef int loop_tail(int s, int i, int nearTo):
    if i < nearTo:
        q = "qwe"
        del q
        return loop_tail(s+i,i+1,nearTo)
    else: return s
```

Suppose I do this?

It works!

```
cdef int loop_tail(int s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        del q
        return loop_tail(s+i,i+1,nearTo)
    else: return s
```

What about this. This one is a big deal.

...It works!

```
cdef int loop_tail(int s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        return loop_tail(s+i,i+1,nearTo)
    else: return s
```

This?

Diverges.

This is great. Let me try making the acumulator an object.

```
cdef int loop_tail(s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        del q
        return loop_tail(s+i,i+1,nearTo)
    else: return s
```

Let me try this.

It works. How about...

```
cdef int loop_tail(s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        del q
        w = s + i
        return loop_tail(s,i+1,nearTo)
    else: return s
```

Whops, I meant to pass in w there. But this diverges which is interesting.

```
cdef int loop_tail(s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        del q
        w = s + i
        return loop_tail(w,i+1,nearTo)
    else: return s
```

This should diverge then as well. Yes.

```
cdef int loop_tail(s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        del q
        w = s + i
        del s
        return loop_tail(w,i+1,nearTo)
    else: return s
```

This should work...

No, it does not. It diverges.

How about...

```
cdef int loop_tail(s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        del q
        w = s + i
        del s
        return loop_tail(w,i+1,nearTo)
    else:
        del w
        return s
```

It complains that I am referencing a variable before assignment.

```
cdef int loop_tail(s, int i, int nearTo):
    if i < nearTo:
        return loop_tail(s+i,i+1,nearTo)
    else:
        return s
```

This does not work for me anymore. Am I getting fooled?

```
cdef int loop_tail(s, int i, int nearTo):
    q = "qwe"
    if i < nearTo:
        del q
        return loop_tail(s+i,i+1,nearTo)
    else: return s
```

Didn't I say that this works? What the hell?

No, it does not work. But in this case the problem might be simply the computer running out of memory. Not necessarily because of the tail call either. Python has unbounded ints.

```
cdef int loop_tail(s, int i, int nearTo):
    if i < nearTo: return loop_tail(s+0,i+1,nearTo)
    else: return s
```

What if I tried this?

Even this fails.

I am going to have to look at the generated code for this and contrast it with the one when the s is an int.

```
+1: cdef int loop_tail(s, int i, int nearTo):
static int __pyx_f_7tailrec_loop_tail(PyObject *__pyx_v_s, int __pyx_v_i, int __pyx_v_nearTo) {
  int __pyx_r;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("loop_tail", 0);
/* … */
  /* function exit code */
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_WriteUnraisable("tailrec.loop_tail", __pyx_clineno, __pyx_lineno, __pyx_filename, 1, 0);
  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
+2:     if i < nearTo: return loop_tail(s+0,i+1,nearTo)
  __pyx_t_1 = ((__pyx_v_i < __pyx_v_nearTo) != 0);
  if (__pyx_t_1) {
    __pyx_t_2 = __Pyx_PyInt_AddObjC(__pyx_v_s, __pyx_int_0, 0, 0, 0); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 2, __pyx_L1_error)
    __Pyx_GOTREF(__pyx_t_2);
    __pyx_r = __pyx_f_7tailrec_loop_tail(__pyx_t_2, (__pyx_v_i + 1), __pyx_v_nearTo);
    __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
    goto __pyx_L0;
  }
+3:     else: return s
  /*else*/ {
    __pyx_t_3 = __Pyx_PyInt_As_int(__pyx_v_s); if (unlikely((__pyx_t_3 == (int)-1) && PyErr_Occurred())) __PYX_ERR(0, 3, __pyx_L1_error)
    __pyx_r = __pyx_t_3;
    goto __pyx_L0;
  }
```

This is bad. I won't be able to do tail recursive loops in Cython. Let me see if anything happens when I pass a plain object.

```
cdef int loop_tail(s, int i, int nearTo):
    if i < nearTo: return loop_tail(s,i+1,nearTo)
    else: return s
```

Something like this.

```
cdef int loop_tail(s, int i, int nearTo):
    if i < nearTo: return loop_tail(s,i+1,nearTo)
    else: return s
```

This works. What if I pass in a heap mutable.

```
cdef class T:
    cdef int i
    def __init__(): self.i = 0
cdef int loop_tail(T s, int i, int nearTo):
    if i < nearTo:
        T.i += i
        return loop_tail(s,i+1,nearTo)
    else: return s
cpdef int sequence_tailrec(int fron, int nearTo):
    return loop_tail(T(),fron,nearTo)
```

Something like this.

```
cdef class T:
    cdef public int i
    def __init__(self): self.i = 0
cdef int loop_tail(T s, int i, int nearTo):
    cdef int q
    if i < nearTo:
        q = T.i
        print(q)
        T.i = q + i
        return loop_tail(s,i+1,nearTo)
    else: return s
cpdef int sequence_tailrec(int fron, int nearTo):
    return loop_tail(T(),fron,nearTo)
```

Why is this happening. I am getting errors.

```
  File "cython_experiments/test2/run.py", line 5, in <module>
    print(tailrec.sequence_tailrec(0,2_000_000_000))
TypeError: an integer is required
```

What the hell is this error.

```fs
cdef class T:
    cdef int i
    def __init__(self, int i): self.i = i
cdef int loop_tail(T s, int i, int nearTo):
    if i < nearTo:
        s.i = s.i + i
        return loop_tail(s,i+1,nearTo)
    else: return s.i
cpdef int sequence_tailrec(int fron, int nearTo):
    return loop_tail(T(0),fron,nearTo)
```

Ah, I am such a fool. Let me try this.

This works. Let me print out the code.

```
+04: cdef int loop_tail(T s, int i, int nearTo):
static int __pyx_f_7tailrec_loop_tail(struct __pyx_obj_7tailrec_T *__pyx_v_s, int __pyx_v_i, int __pyx_v_nearTo) {
  int __pyx_r;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("loop_tail", 0);
/* … */
  /* function exit code */
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
+05:     if i < nearTo:
  __pyx_t_1 = ((__pyx_v_i < __pyx_v_nearTo) != 0);
  if (__pyx_t_1) {
/* … */
  }
+06:         s.i = s.i + i
    __pyx_v_s->i = (__pyx_v_s->i + __pyx_v_i);
+07:         return loop_tail(s,i+1,nearTo)
    __pyx_r = __pyx_f_7tailrec_loop_tail(__pyx_v_s, (__pyx_v_i + 1), __pyx_v_nearTo);
    goto __pyx_L0;
+08:     else: return s.i
  /*else*/ {
    __pyx_r = __pyx_v_s->i;
    goto __pyx_L0;
  }
```

This works. It is actually amazing that it does since it is not at all tail recursive.

10:40am.

```
cdef int loop_tail(s, int i, int nearTo):
    if i < nearTo: return loop_tail(s+0,i+1,nearTo)
    else: return s
cpdef int sequence_tailrec(int fron, int nearTo):
    return loop_tail(T(0),fron,nearTo)
```

Let me investigate this again. I want to see where that one var is declared.

```cpp
static int __pyx_f_7tailrec_loop_tail(PyObject *__pyx_v_s, int __pyx_v_i, int __pyx_v_nearTo) {
  int __pyx_r;
  __Pyx_RefNannyDeclarations
  int __pyx_t_1;
  PyObject *__pyx_t_2 = NULL;
  int __pyx_t_3;
  int __pyx_lineno = 0;
  const char *__pyx_filename = NULL;
  int __pyx_clineno = 0;
  __Pyx_RefNannySetupContext("loop_tail", 0);

  /* "tailrec.pyx":2
 * cdef int loop_tail(s, int i, int nearTo):
 *     if i < nearTo: return loop_tail(s+0,i+1,nearTo)             # <<<<<<<<<<<<<<
 *     else: return s
 * cpdef int sequence_tailrec(int fron, int nearTo):
 */
  __pyx_t_1 = ((__pyx_v_i < __pyx_v_nearTo) != 0);
  if (__pyx_t_1) {
    __pyx_t_2 = __Pyx_PyInt_AddObjC(__pyx_v_s, __pyx_int_0, 0, 0, 0); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 2, __pyx_L1_error)
    __Pyx_GOTREF(__pyx_t_2);
    __pyx_r = __pyx_f_7tailrec_loop_tail(__pyx_t_2, (__pyx_v_i + 1), __pyx_v_nearTo);
    __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
    goto __pyx_L0;
  }

  /* "tailrec.pyx":3
 * cdef int loop_tail(s, int i, int nearTo):
 *     if i < nearTo: return loop_tail(s+0,i+1,nearTo)
 *     else: return s             # <<<<<<<<<<<<<<
 * cpdef int sequence_tailrec(int fron, int nearTo):
 *     return loop_tail(0,fron,nearTo)
 */
  /*else*/ {
    __pyx_t_3 = __Pyx_PyInt_As_int(__pyx_v_s); if (unlikely((__pyx_t_3 == (int)-1) && PyErr_Occurred())) __PYX_ERR(0, 3, __pyx_L1_error)
    __pyx_r = __pyx_t_3;
    goto __pyx_L0;
  }

  /* "tailrec.pyx":1
 * cdef int loop_tail(s, int i, int nearTo):             # <<<<<<<<<<<<<<
 *     if i < nearTo: return loop_tail(s+0,i+1,nearTo)
 *     else: return s
 */

  /* function exit code */
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_WriteUnraisable("tailrec.loop_tail", __pyx_clineno, __pyx_lineno, __pyx_filename, 1, 0);
  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
```

Here is the full thing.

```
    __pyx_r = __pyx_f_7tailrec_loop_tail(__pyx_t_2, (__pyx_v_i + 1), __pyx_v_nearTo);
    __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
```

It is this dereference that is really killing it. There is no avoiding it.

But this is interesting. Based on this I can surmise that functions do not increase and decrease the reference of their arguments. That means I do not have to free those. Ok.

10:50am. I am trying to think of how I would design a language with ref counting to avoid that deref and I am not getting anything.

This is something I am going to have to simply be aware of.

Ok, I learned from this.

Let me take a short break here.

After that I'll get back to work on the pass. I need to redo it.

11:15am. Let me start. First since I know I don't need to del the method args, let me adjust that first.

Done.

Now, let me do a little subpass that I thought up last night.

```fs
let rec binds is_tail (init_freeable : Tag Set) (init_used : Tag Set) (x : TypedBind []) =
```

This `is_tail` argument is not good enough. I should do an analysis to see whether there is a function call in the tail position. If it does, only then should I try folding the `del`s into it. If it is just a tail call, I do not need to insert `del`s anyway.

11:20am. Also I have come up with a scheme of how a language with RC would enable TCO of object args, but it is not something I can use with Cython.

It is simple, if the last use is a function call then deref the args, but don't dispose them even if they hit 0. The function itself would increment the count in the body. This would make the function calls a tad more expensive, but it would enable TCO to work as it should.

11:25am. The C compiler is very impressive to be able to do TCO of a function such as the one shown though. I've completely raised my estimate of it.

Just who was saying that MSVC is bad?

...Let me do this thing. I think I have the pass fully thought out now. I'll be able to finish it today or tomorrow and put it into action.

11:40am.

```fs
let tco_enabler (x : TypedBind []) =
    let is_tailend = HashSet(HashIdentity.Reference)
    let reqs_tco = HashSet(HashIdentity.Reference)

    let rec binds x =
        match x with
        | TyLet _ -> failwith "Compiler error: This function should only be called on the last statement of a sequence."
        | TyLocalReturnOp(_,o,_) ->
            let a, b = ops o
            if a then is_tailend.Add(x) |> ignore
            if b then reqs_tco.Add(x) |> ignore
            a, b
        | TyLocalReturnData _ ->
            is_tailend.Add(x) |> ignore
            true, false
    and ops = function
        | TyWhile _ -> false, false
        | TyJoinPoint(JPMethod _,_) -> true, true
        //| TyUnionUnbox of TyV list * Union * Map<string,Data list * TypedBind []> * TypedBind [] option
        //| TyIntSwitch of Tag * TypedBind [] [] * TypedBind []
        //| TyIf of cond: Data * tr: TypedBind [] * fl: TypedBind []
        | _ -> true, false
```

Now I am confused again. Why do I want to block TyWhile from being tailend?

```fs
let tco_enabler (x : TypedBind []) =
    let is_tailend = HashSet(HashIdentity.Reference)
    let reqs_tco = HashSet(HashIdentity.Reference)

    let rec binds x =
        match x with
        | TyLet _ -> failwith "Compiler error: This function should only be called on the last statement of a sequence."
        | TyLocalReturnOp(_,o,_) ->
            let has_jp = ops o
            is_tailend.Add(x) |> ignore
            if has_jp then reqs_tco.Add(x) |> ignore
            has_jp
        | TyLocalReturnData _ ->
            is_tailend.Add(x) |> ignore
            false
```

Let me go with this.

```fs
let tco_enabler (x : TypedBind []) =
    let is_tailend = HashSet(HashIdentity.Reference)
    let reqs_tco = HashSet(HashIdentity.Reference)

    let rec binds x =
        let x = Array.last x
        match x with
        | TyLet _ -> failwith "Compiler error: This function should only be called on the last statement of a sequence."
        | TyLocalReturnOp(_,o,_) ->
            let has_jp = ops o
            is_tailend.Add(x) |> ignore
            if has_jp then reqs_tco.Add(x) |> ignore
            has_jp
        | TyLocalReturnData _ ->
            is_tailend.Add(x) |> ignore
            false
    and ops = function
        | TyJoinPoint(JPMethod _,_) -> true
        | TyUnionUnbox(_,_,a,b) -> Map.exists (fun _ (_,x) -> binds x) a || match b with Some x -> binds x | _ -> false
        | TyIntSwitch(_,a,b) -> Array.exists binds a || binds b
        | TyIf(_,a,b) -> binds a || binds b
        | _ -> false

    let _ = binds x
    is_tailend, reqs_tco
```

This should do it.

Let me make use of this.

```fs
            is_tailend.Add(x) |> ignore
            if has_jp then reqs_tco.Add(x) |> ignore
```

Actually, let me adjust this.

```fs
        | TyLocalReturnOp(_,o,_) ->
            let has_jp = ops o
            is_tailend.Add(o :> obj) |> ignore
            if has_jp then reqs_tco.Add(o :> obj) |> ignore
            has_jp
        | TyLocalReturnData(d,_) ->
            is_tailend.Add(d) |> ignore
            false
```

Let me do it like this.

```fs
            | TyLocalReturnData(d,_) ->
                let d = tags d
                let next_used = init_used
                if is_tailend.Contains(d) then
                    nulls.[st] <- Set.empty
                else
                    let d_nulls = d |> Set.filter (fun i -> Set.contains i next_used = false)
                    nulls.[st] <- d_nulls
                d + next_used
```

Now in the pass I will just set the nulls here to empty. This will simplify things.

```fs
            | TyLocalReturnOp(_,o,_) ->
                let next_used = init_used
                let op_nulls, op_used = ops freeable next_used o
                nulls.[st] <- op_nulls
                op_used
```

This on the other hand will only be considered in the ops itself. Let me deal with that.

12:10pm.

```fs
    and ops (freeable : Tag Set) (used : Tag Set) (x : TypedOp) =
        let return_op used' =
            let nulls =
                if is_tailend.Contains(x) then Set.empty
                else used' |> Set.filter (fun i -> Set.contains i freeable && Set.contains i used = false)
            nulls, used + used'
        match x with
        | TyMacro l -> List.fold (fun s -> function CMTerm d -> s + tags d | _ -> s) Set.empty l |> return_op
        | TyOp(_,l) -> List.fold (fun s x -> s + tags x) Set.empty l |> return_op
```

This seems fine.

```fs
        | TyFailwith(_,x) | TyArrayCreate(_,x) | TyArrayU64Create(_,x) -> tags x |> return_op
        //| TyWhile of cond: JoinPointCall * TypedBind []
        //| TyUnionBox of string * Data * Union
        //| TyLayoutToHeap of Data * Ty
        //| TyLayoutToHeapMutable of Data * Ty
        //| TyLayoutIndexAll of L<Tag,Ty * Layout>
        //| TyLayoutIndexByKey of L<Tag,Ty * Layout> * string
        //| TyLayoutHeapMutableSet of L<Tag,Ty> * string list * Data
        //| TyJoinPoint of JoinPointCall
        //| TyUnionUnbox of TyV list * Union * Map<string,Data list * TypedBind []> * TypedBind [] option
        //| TyIntSwitch of Tag * TypedBind [] [] * TypedBind []
        //| TyIf of cond: Data * tr: TypedBind [] * fl: TypedBind []
```

Let me take a break here. I'll fill out the rest later.

I am not that far away from finishing this. Everything is set. I just need to seal the deal."