"1:45pm. Yeah, this is the correct way. Literally anything would work better than end to end training of a NN on Holdem.
Ok, let me pry myself off Higu. I'll chill just for a bit more and then I'll resume the tutorial.

2:20pm. Let me start. Before I give into normality, I should exhaust all the possibilities. I should try pushing probabilistic programming to its limit and see where that gets me. That should be my big project for the next year or so. When I get an AI chip I'll be able to translate everything on it without too much effort.

But I am not going to get anywhere with 2/5 in ML even with much better hardware. I need not just more computation, but more efficiency in what I do now.

```jl
using Omega
using Random
using UnicodePlots

function x_(rng)
  if bernoulli(rng, 0.5, Bool)::Bool
    normal(rng, 0.0, 1.0)::Float64
  else bernoulli(rng, 0.5, Bool)
    betarv(rng, 2.0, 2.0)::Float64
  end
end

# q = ~x_

x_(Random.GLOBAL_RNG)
```
```
ERROR: MethodError: no method matching bernoulli(::MersenneTwister, ::Float64, ::Type{Bool})
Closest candidates are:
  bernoulli(::Real, ::Real, ::Type{RT}) where RT at C:\Users\Marko\.julia\packages\Omega\zOdli\src\primitive\univariate.jl:26
  bernoulli(::Ω, ::Real, ::Any) at C:\Users\Marko\.julia\packages\Omega\zOdli\src\primitive\univariate.jl:28
  bernoulli(::Ω, ::Any, ::Any) at C:\Users\Marko\.julia\packages\Omega\zOdli\src\primitive\univariate.jl:29
  ...
Stacktrace:
 [1] x_(::MersenneTwister) at e:\ProbProg in Julia\01-Omega\tutorial.jl:6
 [2] top-level scope at none:0
```

Hmmm, not only does the `~` operator not work, neither does this code fragment.

```
"Uniform distribution between `a` and `b`"
unif(rng, a, b) = rand(rng) * (b - a) + b

# x is uniformly distributed between 10 and 20
x = ciid(unif, 10, 20)
```

I was right, he got this wrong. It should have been + a.

2:50pm. Wow, unlike for Python it sure takes it a while to restart.

```jl
uniform(a, b) = ciid(rng -> rand(rng) * (b - a) + b)

# x is distributed between 30 and 40 (and independent of x)
x = ciid(unif, 30, 40)

# x is distributed between 30 and 40 (and independent of x)
y = ciid(unif, 30, 40)
```

This example is completely broken. What the hell?

3pm.

```jl
add Omega#master
```

Ahhh, I see. This might be a better way of getting the master version. It might be worth a try.

3:20pm. Ok, I won't bother installing the newest version of Julia just yet.

This documentation is literally broken everywhere, I have 4 PRs and 1 issue open right now.

http://www.zenna.org/Omega.jl/latest/conditionalindependence/

Let me continue going through the docs.

```jl
using Omega

μ = uniform(0.0, 1.0)
y1 = normal(μ, 1.0)
y2 =~ y1
```
```
ERROR: UndefKeywordError: keyword argument id not assigned
Stacktrace:
 [1] ciid(::Omega.Prim.Normal{Omega.Prim.Uniform{Float64,Float64},Float64}) at C:\Users\Marko\.julia\packages\Omega\uNcYk\src\prim\univariate.jl:131
 [2] ~(::Omega.Prim.Normal{Omega.Prim.Uniform{Float64,Float64},Float64}) at C:\Users\Marko\.julia\packages\Omega\uNcYk\src\nondet\ciid.jl:72
 [3] top-level scope at none:0
```

This example does not actually work.

```
function x_(ω)
  x = normal(ω, 0, 1)
end
x = ciid(x_)
rand(x)
```

This works.

3:40pm.

```jl
using Omega

numflips = poisson(2)

flips_(ω) = [bernoulli(ω, 0.5, Bool) for i = 1:numflips(ω)]
flips = ciid(flips_)

"At least one of numflips is true"
anyheads_(ω) = any(flips(ω))
anyheads = ciid(anyheads_)

"All flips are true"
allheads_(ω) = all(flips(ω))
allheads = ciid(allheads_)  # `allheads` and `anyheads` share `flips`

rand((numflips, flips, anyheads, allheads))
```

This confuses me. What are the flips shared here, I thought that `allheads_` and `anyhead_` are independent from their parents.

Also the way `any` and `all` are implemented for empty arrays is different from how it is in functional languages. `any` gives false and `all` gives true. In functional languages the operation would resemble a fold with the neutral element which is true for `any` and false for `all`.

Do I ask him about this. I think I already have enough issues opened.

Well, I'll leave this mystery for later. I'll only report things which are outright broken.

https://www.geeksforgeeks.org/checking-for-true-values-in-an-array-in-julia-any-and-all-methods/

```
any([false,true])
```

Ah, it is not like Omega in regular Julia either.

Ah, no wait, I was wrong. Omega did it right. F# does it this way as well. My memory was faulty.

3:55pm. http://www.zenna.org/Omega.jl/latest/inference/

Let me move on to this.

```jl
weight = β(2.0, 2.0)
x = bernoulli()
rand(weight, x == 0)
```

This example is broken.

```jl
weight = β(2.0, 2.0)
x = bernoulli(weight)
rand(weight, x == 0)
```

Maybe it is meant to be done like this, but this gives me nothing.

4:05pm.

```jl
using UnicodePlots

weight = β(2.0, 2.0)
x = bernoulli(weight)
UnicodePlots.histogram(rand(weight, x ==ᵣ 0, 1000; alg=RejectionSample))
```

Let me go with this.

```jl
using UnicodePlots

x1 = normal(0.0, 1.0)
UnicodePlots.histogram(rand(x1, x1 > 0.0, 1000; alg=RejectionSample))
```

This works perfectly fine, surprisigly enough. I thought I would have problems much like for equality.

4:15pm.

```jl
x1 = normal(0.0, 1.0)
x2 = normal(0.0, 10)
rand((x1, x2), x1 > x2; alg=RejectionSample)
```

This is another example that needed fixing. It seems conditions need to be given the inference algorithm explicitly.

4:20pm.

```jl
x = cond(normal(0.0, 1.0), rv -> rv > 0.0)
rand(x; alg=RejectionSample)
```

This fails to work for me.

```jl
x = cond(poisson(3.0), iseven)
rand(x, 5; alg = RejectionSample)
```

This fails to work as well.

Let me go at it from the top.

4:35pm. http://www.zenna.org/Omega.jl/latest/soft/

The next article is this one.

```
==ₛ
>ₛ
>=
<=ₛ
<ₛ
```

Note how the middle operator is missing a `ₛ`.

4:50pm. http://www.zenna.org/Omega.jl/latest/inferencealgorithms/

The docs are quite incomplete.

I won't bother doing anything here as there aren't any examples.

5:05pm.

```jl
using Callbacks, Lens
x = ~ ω -> (sleep(0.001); normal(ω, 0, 1))
@leval Loop => showprogress(10000) rand(x, 10000)
```

I thought this was compiling a package and went off reading random articles. Focus me.

```jl
using Omega.Inference: SSMHLoop
x =~ ω -> (sleep(0.001); normal(ω, 0, 1))
@leval SSMHLoop => plotloss() rand(x, x >ₛ 0.0, 10000; alg = SSMH)
```

Plotloss is not defined. Nevermind this.

5:05pm. Let me go to the next thing, I won't report this.

http://www.zenna.org/Omega.jl/latest/causal/

The next is this.

https://www.inference.vc/untitled/

I guess I'll read these articles.

5:25pm. I am taking a break. Is any Tog out? Ah, it came out 1 day ago. Ok, let me read that and then I will finish that series of articles.

6pm. Done with lunch.

6:05pm. Done with part two of the inference.vc article.

https://www.inference.vc/causal-inference-3-counterfactuals/

I'll leave this for later. I'll finish the docs tomorrow, and then track down the examples that Zenna showed me during the meet. I'll play with it for a while and then dig into the code. This should give me some insight about how to use the Omega library and what he is doing.

Then I am going to try repeating the poker project - I'll port the whole thing to Julia and continue from where I left off in Python + Spiral. I'll ditch the NNs for the time being and simply try to build a probabilistic model - I'll estimate the aggression factors and hand ranges at every step of the way.

I'll try to get better that way. It is not like it is written in stone that I have to only do end to end training of NNs. Nature had to build a lot of instincts into its creations, and I should tread the same path as it.

New goal - master the language of probability.

Do I have anything better to do for the next months, years or even decades? I think not.

I cannot possibly fail at ML any harder that I already have. I have nothing to lose at all by abandoning my old methods and embracing new ones."