"2:45pm. Let me chill for a bit more and I'll get started.
3:10pm. Let me start.

First let me finish the Hops tutorial. Then I'll check out the Mesh Machine ones.

https://youtu.be/N6mfFv_7jYo?t=730

Something like this would be highly convenient for doing those pool decals.

https://youtu.be/N6mfFv_7jYo?t=1341

Here he mentions step bevels. I've never heard about those.

https://youtu.be/UAofaP8h2IU
Quick guide to understanding bevels in HARD OPS

Let me pause the video and I will watch this.

3:55pm. https://youtu.be/UAofaP8h2IU?t=291

Oh wow, it can add supporting loop cuts. That would have made working with subdiv way easier.

https://youtu.be/UAofaP8h2IU?t=422

I am not sure I get what he is doing here.

https://youtu.be/UAofaP8h2IU?t=523

I am confused. How is he controling the bevels of the surfaces that are cutting in?

https://youtu.be/UAofaP8h2IU?t=606

Here he will talk about step bevels.

https://youtu.be/Lpyy0F5nsWg
All about Mesh Machine addon for hard surface in Blender

Let me watch this. It is only 15m.

https://youtu.be/Lpyy0F5nsWg?t=171

Hmmm, how did he select a loop directly like this?

I got it. You can do select shortest path by holding Ctrl!

How the hell did I miss this?

I had to make a shortcut for this, but it was here all along.

Damn.

https://youtu.be/Lpyy0F5nsWg?t=214

This is amazing, I spent hours fixing bevels yesterday by hand. This would have made is so much faster.

https://youtu.be/Lpyy0F5nsWg?t=257

Yeah, this is impressive functionality. Hops was all about modifiers, but this here is different. Maybe I'd be able to do the desk piece in the way I wanted to using this with just bevels.

https://youtu.be/Lpyy0F5nsWg?t=453

You know that video by Josh where he selected all over the place for that torus. He could just just selected in a similar direction.

4:35pm. https://youtu.be/zYuYu41-YGo
SHOULD you SUBDIVIDE the mesh? - HARD SURFACE dilemma in Blender.

Let me watch this. I am quite into it.

https://youtu.be/zYuYu41-YGo?t=17
> There are people out there you know who think that you need quads to run a subd modifier. We tried to hunt them down, eventually we are going to get them all.

This is something I've noticed as well. I read that subd needs quads, but it my own testing it works fine even without them.

https://youtu.be/zYuYu41-YGo?t=71
> The question now, right, is why would you need subd and when, and not to use it. The answer is very simple - if you don't need it stay the fuck away from it. Because it's just bad news.

https://youtu.be/zYuYu41-YGo?t=235

He identifies the loop cuts as being the main problem. Yes, this is exactly why I was reluctant to use it as well.

https://youtu.be/dhGJB_7JNvg
The FUTURE of SUBD modelling in Blender - Offset Cut with Mesh Machine

This is 5m so let me watch it. After that I'll go back to the Hops tutorial.

https://youtu.be/dhGJB_7JNvg?t=91

Offset cuts are nice. I saw him do something like that when cleaning up booleans and wondered whether I could use this more generally. Back when he did that offset cut in the sphere video, it did not clean up the verts that were inbetween. But this one does so it is much better.

https://youtu.be/dhGJB_7JNvg?t=284
> There is a new tool being developed called hyper bevel.

5:15pm. https://youtu.be/7xojWBmfx84
How to Create Variable Radius Bevel in Blender

This caught my eye. Even though I've done all sorts of studying, I still do not know how to make bevels with varaibles widths on different face sides. Maybe this will answer it.

https://youtu.be/7xojWBmfx84?t=74

He is going to use the weight mode. I don't like that. But at the start of the video he did show some impressive examples. Also, he says that mods like Mesh Machine can do it. So I'll find a way.

https://youtu.be/7xojWBmfx84?t=109

% mode?

https://youtu.be/7xojWBmfx84?t=151

I admit, it did not occur to me to use edge loops to control bevels.

5:35pm. Let me finally finish that hops tutorial. After that I'll try out mesh machine.

https://youtu.be/N6mfFv_7jYo?t=1448

Clean mesh seems like it would be useful for after subdiv. I am not really happy how decimate puts ngons all over the place.

https://youtu.be/N6mfFv_7jYo?t=1484
> By default what Hops does is parent the cutter to the object.

This is a good idea.

https://youtu.be/N6mfFv_7jYo?t=2102

I had no idea that this was possible in vanilla.

https://youtu.be/N6mfFv_7jYo?t=2316

Instead of doing a radial array in vanilla using the array modifier, it would be far easier to put a circle and then use geometry nodes to do this. But this video is from 1.5 years ago, so those weren't in yet.

6:05pm. Ok.

I am most attracted to mesh machine right now so why not go for it?

///

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'MESHmachine_0'

///

I am having trouble installing it.

Ah, I think I get it. Most likely the name of the module is the directory. I have it as something else. I actually had to rezip the plugin. I have no idea why this is happening.

Nice, I got it running!

6:25pm. Some more naming issues. I got around it, but it crashed when I tried fusing. Maybe 3.2 Alpha is not the way to go for these plugins.

6:30pm. My god, it keeps crashing. I press Y, fuse it, press Y again and it crashes in both versions.

Let me install 3.1.2 of Blender. Maybe I should get 3.0 as well.

I had it but I got rid of it just today.

https://blendermarket.com/products/MESHmachine/

MESHmachine 0.11 works with Blender 2.93 - 3.1!

3.1 is supported.

6:25pm. It keeps crashing without error. Could this be yet another naming issue? Unlikely as the first fuse works.

6:45pm. Damn it, I should put some effort into figure out why this is happening. I was really lucky that I managed to find such an up to date version of Mesh Machine.

///

# Blender 3.1.2, Commit date: 2022-03-31 17:40, Hash cc66d1020c3b
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.ops.mesh.split()  # Operator
bpy.data.window_managers["WinMan"].addon_search = "meshm"  # Property
bpy.ops.machin3.call_mesh_machine_menu(idname="mesh_machine")  # Operator
bpy.ops.machin3.call_mesh_machine_menu(idname="mesh_machine")  # Operator
bpy.ops.mesh.shortest_path_pick(edge_mode='SELECT', use_fill=False, index=105)  # Operator
bpy.ops.machin3.call_mesh_machine_menu(idname="mesh_machine")  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.machin3.unfuse(sharps=False, cyclic=False)  # Operator
bpy.ops.machin3.call_mesh_machine_menu(idname="mesh_machine")  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.object.editmode_toggle()  # Operator
bpy.ops.object.editmode_toggle()  # Operator

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF7C113D340
Exception Module      : blender.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0xFFFFFFFFFFFFFFFF

///

Found the crash report.

7:05pm. Damn it. This is the worst. Simply the worst. Let me download an older version so I can make sure of the naming.

HOps on the other hand works.

https://gfx-hub.cc/plugins/gfx-plug-ins/71417-meshmachine-v09-for-blender.html

Never saw this site before.

7:25pm. Had to leave for lunch. Let me get Mechmachine 0.8.2. The way the original file was packed is weird. I need one with the actual module name. Originally when I put in a wrong one it still loaded, but then crashed. The error I am getting now might be a more subtle version of that.

GFXHub seems to be some scam site given how it is pestering me to create an account.

7:40pm. I do not think it is a naming issue. Sigh, I have no idea what could possibly be wrong.

As expected 0.8.2 fails to install in 3.1

But no, I did not get the module name wrong. I am sure of it now.

Sigh, I only have Hops operational.

7:50pm. Damn it, this really messed up my endgame for the day.

I thought I had the addon, but now it has been snatched away from me.

https://machin3.io/MESHmachine/docs/#overview

> Moreover, the width of a chamfer will directly determine the width of a fillet(the radius if you want, but it's not precisly circular and depends on the tension setting). This in turn allows for the creation of variable fillets and even washouts, which are impossible to do with the bevel tool and modifier.

Ugh, ugh...

8:05pm. https://youtu.be/2l7JCNG54sQ
MESHmachine 0.7 - Installation & Support

Let me watch this. Hops is not what I want, it is just for managing modifier stacks.

https://youtu.be/Lw00s01nmGY
The Next BEST Feature in Subd Modeling for Blender??

Let me watch this. I give up on MeshMachine for the time being.

https://youtu.be/Lw00s01nmGY?t=158

I really hope he does not just end up demoing vertex weights.

8:30pm. https://youtu.be/DwYd_JstW-c
Blender 3.1 Subdivision Modifier is WAY FASTER!

> If you haven't heard about it the subdivision modifier can be up to 10 times faster in Blender 3.1.

It is due to the GPU and the mod needs to be the last in the stack.

https://youtu.be/1IQbXf-MgL0
SubD with Booleans.. how the heck do we do it?

Let me watch this. I am really tempted to just shell out 40$ for the addon, but..I can't justify it for just the mastery challenge.

8:35pm. https://youtu.be/1IQbXf-MgL0?t=130

The way to show the topology in object mode by turning on the wireframe and turning off the optimal display.

https://youtu.be/1IQbXf-MgL0?t=218

This is what I've been interested in. How could you clean up the stuff around the hole without applying the subd and doing it by hand?

8:45pm. https://www.youtube.com/watch?v=8qv6DbWr6zw
26 Essential Blender Tips for UV Unwrapping Subdivision Surfaces

I'll leave this for later.

https://youtu.be/zeyOO-S6BcE?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD
SUBD + BOOLS + BEVELS - ultimate control in BLENDER

Let me watch this.

I am going to have to push the subd workflow. The biggest problem with it is beveling the cutouts. Blender's bevel capabilities are so bad. It wouldn't be hard for the cutout to do an offet itself, but it does not.

https://youtu.be/zeyOO-S6BcE?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD&t=368

I don't get this. But I do not like how you need to move things around to the right spot so you don't get shearing.

https://youtu.be/u3PFgmsxktI?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD&t=137

I wish I could have multiple weight groups. This is of limited use to me.

But if I am doing hard surface modeling, what if I used a program other than Blender?

I can't find the addon, but that tutorial mentioned a few competing products.

On the side, besides all this trouble with bevels, I am really not sure how those hardened normals and sharpening work.

https://youtu.be/mh7hhbMALno?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD
Blender's real-time boolean on subdivision surface with smooth bevel without addons

Hmmm, how did he manage this? This video opened on its own as a part of the playlist. Being able to do this would make beveling subdiv'd surfaces so much easier.

It seems he is remeshing. i am not sure that this is what I want.

9:20pm. https://www.youtube.com/watch?v=Xk6IsUR1yN4&list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD&index=6

I didn't really understand what he was doing with boxcutter, but having the cutting object itself place the bevels does seem to be the way to go.

I feel that applying the subdiv, then cleaning up by hand and then only then beveling is the wrong way to go about it.

https://youtu.be/pHpTSLZKIC4?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD
Hard Surface Tutorial for Blender - BOOLEAN to SUBD Workflow.

No forget this.

https://youtu.be/NvDIYChSak4?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD
Introduction to QuickShape 2022 for Blender 3.1

Let me watch this just for a bit.

9:25pm. https://youtu.be/mSK1o-4wGgs?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD
Understanding Bevel Tool in Blender (Quick Blender Tip 30)

> Bevel means split not smooth.

Let me watch this and I will close for the day.

To be honest, I think that having MESHmachine would be quite useful even for a subdiv workflow. Even if it is just to put down champers and udo them. Putting loops cuts everywhere is not the way to go.

https://youtu.be/mSK1o-4wGgs?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD&t=307

Turning split points into quads like this never occured to me.

https://youtu.be/mSK1o-4wGgs?list=PLXcWp7sW4pN-1F2HAovVDoAOCZPzIlsdD&t=460

I was making heave use of this particular trick.

11pm. I am at a loss here.

https://www.autodesk.com/products/fusion-360/personal

I am thinking about checking out Fusion 360.

I am starting to think that it is not a problem with me, but with Blender. Subdiv workflow is not something I really want. And without Mesh Machine I am really at a loss. I could install an old version of Blender and use it with that, but maybe it would be possible to go beyond what Blender could offer me even with its addons.

I've been fixated on it for modeling. It is certainly better than Houdini for this role.

But seriously - just how much trouble are these bevels going to give me?

https://www.youtube.com/results?search_query=fusion+360

https://www.youtube.com/watch?v=VTTuQZdzM6M
Fusion 360 vs Blender for Car Modeling - Which car shapes work best when modeling with Fusion 360

Let me watch these just for a bit. The best way to get better is to learn a new tool.

https://youtu.be/VTTuQZdzM6M?t=149

This feels a bit like a subdiv workflow.

But just looking at this does give me insight. I should definitely get rid of my quad obsession if I want to be good at subdiv.

https://youtu.be/VTTuQZdzM6M?t=517

He is talking about control. But should just maxing out the creases work for that?

11:35pm. https://youtu.be/VTTuQZdzM6M?t=1190

This talk is interesting. I would run into all these issues if I used the subdiv workflow in Blender.

https://youtu.be/VTTuQZdzM6M?t=1433
> Getting a result like this using Fusion 360 forms, honestly, I don't think its possible.

He is talking about Blender.

Oh, he did it using subdiv. So then Fusion 360 forms aren't that?

https://youtu.be/VTTuQZdzM6M?t=1666

He really makes Blender sound a lot better than Fusion. I was thinking about studying it because it might give me more control, but according to this it would give me less.

11:50pm. He says that Blender is a tool that is extremely overwhelming to learn. Does that imply Fusion is easier?

https://youtu.be/QkYAcFs_YrU
Fusion 360 vs Blender Challenge

Let me watch this as well.

https://youtu.be/QkYAcFs_YrU?t=304
> You can use bevels in Blender, but those are quuite a pain in terms of updating those later.

12:10pm. This last video was really good at informing me what the differences between Blender and Fusion are.

Ok, I get it. It seems that Blender really is the program I should stick with.

One thing that will help me is if I try to get away from bevels instead of trying to dive into them.

Hops and Mesh Machine really two different kinds of poly workflows. Right now I am too obsessed about control. I know that nothing in my room really needs the kind of exquisite control Mesh Machine would bring me.

12:55pm. Found mesh machine 0.9.

No, whatever I do, I need the ability to adjust the width of chamfers and potentailly remove them.

This would actually be hugely beneficial for a subdiv workflow. Subdiv does not avoid the issues with beveling, it just streamlines them a bit.

I need to cross this hurdle at all costs even if it means diving into the code for the plugin and figuring out what is making it crash.

Let me try 0.9. Maybe it will work with Blender 3.2.

1:10pm. Nope. Let me try it with 3.0. There is nothing wrong with 3.0. If that fails I'll try 2.9.

If all of that fails, I'll try putting the files through diff to make sure that the problem isn't due to some failed malware. If that fails, I guess I'll just buy the thing.

Let me get dinner.

1:20pm. This path is right. Rather than buying it just for the sake of the mastery challenge, I should do the mastery challenge in 3.0 and buy it after that if I still need the tool for something real.

1:40pm. Let me try Blender 2.9. This is ridiculous. With 3.0 I don't get a crash, instead what happens is that all the menu items disappear instead. Is this some kind of anti piracy measure?

1:45pm. Let me ask online.

1:50pm. I'll check whether I've gotten an answer tomorrow. It is time for bed. I sure am tired. Maybe I'll really try studying MM's source. Not the way I expected to get back into programming, but it will do."