"1:15pm. Done with breakfast. I've been reading the parametric inversion paper. Not much I can do going by it. I'll check out his examples.
1:35pm. Let me finally start.

https://github.com/zenna/Mjolnir.jl

I am checking out the stuff in his repo. This is a partial evaluator.

1:40pm. https://github.com/zenna/OmegaModels.jl

He has a bunch of project in his repo with no readmes. I get the sense that this one might be what I am looking for. Let me skim the rest and then I'll clone it.

2pm. Ok, not much I can do about most of these repos. I'll clone the above.

Why is this so hard? If the dominant poker algorithms had anything at all to do with Bayesian infernece, I would have jumped on it right away. Instead none of the successful research applications every have anything to do with gambling which is one place I'd expect to find it.

I absolutely have to do this. There is no way that regular algorithms will suffice.

Go and Chess are one thing. But poker is definitely another. If there is one place you'd expect Bayesian methods to shine, it would be there. They have to win there. Absolutely.

I have no doubt at this point that regular methods won't scale.

2:10pm. Let me clone the OmegaModels repo.

Hmmm, why is the repo so large?

Hmmm, it is not too large, only 100mb.

2:20pm.

```
(OmegaModels) pkg> add WebIO
  Updating registry at `C:\Users\Marko\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: path C:\Users\Marko\.julia\packages\Callbacks\h151u for package Callbacks no longer exists. Remove the package or `develop` it at a new path
```

Sigh.

https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/

> For troubleshooting information, visit the [WebIO Not Detected](https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/providers/@ref) section of the documentation.

That link is 404.

2:25pm. The bad cars notebook is broken as a result.

Let me take a different track. I'll uninstall 1.0 and install 1.6 again. Maybe the master will work with Omega then.

It is troublesome to dig through Zenna's examples. They are all top level stuff and their purpose is known only in the author's mind. On top of that the notebook versions are broken. It is not like I don't understand why this is the case - he worked on the language and the documentation and the examples became stale as a result.

Ok, here is what I'll do - let me install the latest Julia. Then I'll make my goals to go through Julia's docs and Omega's source. For the later I'll do a skim to get familiar with the codebase's structure. I hope it won't be too large.

```
(@v1.6) pkg> add Omega#master
    Updating git-repo `https://github.com/zenna/Omega.jl.git`
    Updating registry at `C:\Users\Marko\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed Tracker ─ v0.2.16
    Updating `C:\Users\Marko\.julia\environments\v1.6\Project.toml`
  [1af16e33] ~ Omega v0.1.1 ⇒ v0.1.1 `https://github.com/zenna/Omega.jl.git#master`
    Updating `C:\Users\Marko\.julia\environments\v1.6\Manifest.toml`
  [4fba245c] - ArrayInterface v3.1.30
  [bbc10e6e] - DynamicHMC v2.2.0
  [6a86dc24] - FiniteDiff v2.8.1
  [615f187c] - IfElse v0.1.0
  [d3d80556] - LineSearches v7.1.1
  [d41bc354] - NLSolversBase v7.8.1
  [1af16e33] ~ Omega v0.1.1 ⇒ v0.1.1 `https://github.com/zenna/Omega.jl.git#master`
  [429524aa] - Optim v1.4.1
  [85a6dd25] - PositiveFactorizations v0.2.4
  [aedffcd0] - Static v0.3.1
  [9f7883ad] + Tracker v0.2.16
Precompiling project...
  2 dependencies successfully precompiled in 22 seconds (89 already precompiled)
```

Oh, it seems that it worked. Nice.

2:40pm. Something fishy is going on with how long the editor needs to open Omega. Now I am doing it all in the REPL. I want to make sure that everything is going properly. Usually I get Cuda errors. With 1.6.2 that seems to have gone away, but let me repeat the import.

Just why is it downloading the CUDNN package? Shouldn't that have been done earlier when I imported it in the editor?

Yeah, it works fine.

2:55pm. Closed that issue and did another PR to redirect the install to the latest version.

Now let me clone Omega.

```jl
import ForwardDiff
using Spec
```

Oh, I had no idea that import was also a keyword in Julia. When I talked about importing packages in Julia, I meant that using the `using` statement.

```
# The Omega Lanaguage (Not Library)
include("lang/lang.jl")
```

Found a typo here.

4:30pm. Mhhhh...done with the pass. That sure was boring.

Since I can't build a mental model of novel code at a glance I didn't learn that much, but I have a sense for how the project is built now and for the author's coding style.

One thing that is good is that it is mostly made of small functions. On the negative side, I find it rough how in place of unions it insteads leans on Julia's operator overloading.

This is a compiler project in a dynamic language. Hovering over a variable and expecting its type to come up is useless.

I am not sure what order the modules are in, I just went from bottom to top.

4:40pm. Ok, here are the next goals:

* Master Julia fundamentals. I need to go through its docs and play with it.
* Figure out how its packaging system works.
* After that, fire up the debugger and go through the Omega examples that way. That will allow me to learn a lot more.

I'll want to take everything one step at a time. If I could get deeply familiar with the library I could do my own smallish PPL project to make sure that everything makes sense.

Omega is a pretty good target. I did not get the sense that the project is particularly big.

5:20pm. Had to take a short break.

The Bayesian side has a lot of influence in academia, but for all the fancy math, I am yet to see a real example of its purported exponential efficiency improvements in practice. For example, I wonder why the Alberta group did not reach for these methods instead of using a supercomputer to scale crappier methods when making their poker agents? Perhaps making a probabilistic language would have been too much for them.

It is not too much for me.

5:25pm. Let me study Julia itself here.

https://docs.julialang.org/en/v1/

5:35pm. https://docs.julialang.org/en/v1/manual/getting-started/

One by one, I'll get through this. I guess I couldn't escape the grasp of Julia in the end.

It sure would be great to be skilled at ML and have all of my moves be definite improvements in my circumstance. Now I've lost Spiral again and am in the situation I was in the early 2019.

5:45pm. https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/

I should be reading this instead of HackerNews. Well, it is almost 6pm and I've reached my tolerance limits.

6:20pm. Had to leave for lunch.

Actually rather than rewriting the library in F#, a much easier goal I could take at first is to take the whole Omega library and cut pieces of it out until I get to the point that only the simplest programs would compile. I should be capable of breaking it down and building it up.

That will give me a grasp of its structure in ways that just glancing through the code cannot. Once I am capable of that, I'll gradually add the pieces back one by one while inspecting their functionality along the way.

A true mastery challenge would be to attain such a grasp of its structure that I could do a refinement of it. I need to work towards such a goal. If I could do that hopefully that will really convince Zenna to send paid work my way. Of course, I am doing this for myself - the interview with him was pure luck as far as I am concerned, but going without making a dollar like for the last 6.5 years all the way to the Singularity would suck and I hope that does not happen. Right now, I'd be in danger if my computer breaks down or if my dad suffers a tragedy. I'd really have to scramble for a job in such case no matter how lowly paid it might be. I'd have to ask my relatives to hook me up with something. I'd guess I'd be making 1.5-2k per month in such a scenario. This is the main reason why I never even bothered looking for a job here.

I'd be busy with paid work, and my quest would die right there.

Right now, there might be people out there making over 10k per month telling themselves they will try tackling AI seriously as soon as they save up enough. Job, family, friends...those are all obstacles on the path of power. They sap time and energy that could be spend doing programming.

6:40pm. Maybe it is good that I am not making anything. If somebody offered me 10k per month, I'd be tempted to become a wage slave myself, if only for 6 months. And then I'd start loving money and make it another 6 more. And more. After all there is plenty of time until the Singularity...

Ultimately, the time left till the human era comes to an end is just a prediction. One can take responsibility to shorten it significantly.

If Newton died prematurely, there was Liebnitz, but if both them weren't there to invent calculus who would be the next in line? There is not an infinite supply of such people waiting to do boring drudge work and make speculative long term bets with their lives.

It would be best to have the mindset that every day is precious and must be spent working towards it. That if I am not the one to cause it, that nobody else will either. People like Newton must think that they are special and apart from the masses. They must think that they stand on the shoulders of giants and not the common people."