"8:40am. No reply from the UPMEM dev yet regarding the globals. Yesterday I was happy to see an email from him, but it was from last Friday. So now I am once again wary of getting ghosted. Though, the value of this work is that I will be able to post it on HN, so UPMEM itself doesn't matter in particular. Still, I do not want to end the article with a takedown of the company for what I think is its bothed programming model, so I'd like to get an explanation regardless.
The reason why I suspect I might get ghosted is my messaging and blogging style on this journal. Just take a look at the last paragraph for an example of my style. It might be fun to read on the outside, but it is a social faux when you are interacting with somebody. I just lack chill. This is probably why I can't really win as a writer.

Right now I am only half the man I could be. I need to get access to that AI hardware and fulfil my dreams. Writing Heaven's Key is just escapism.

Either way, the UPMEM dev will have my gratitude for getting me back into programming. I'll do this last project, post it on HN, PL sub and maybe somewhere else. The Tenstorrent discord. After that since I feel like programming I should post that I am looking on the F# Twitter or something like that. Though I bet I'll get some contacts once I make the post on HN.

Let me check my dashboard. I haven't looked at it in a while.

Views at 5,329. Avg at 124. Followers at 29. Favorites and ratings at 7.

That crappy review got taken off, so my rating is back at 3.71. Rather than gaining a follower, I actually lost one since my last check

Yeah, writing is a serious business and I am not doing it properly. This is probably as far as I go. Yesterday I did some writing, and I guess I will treat it like a hobby. I just do not have the power to be successful at it professionaly. The Singularity plan hasn't changed. Get better hardware, figure out the algorithm, attain great wealth and pursue transcendence.

I'll work on Euclid's story in my spare time rather indulge in other hobbies. I care about it that much.

Now, let me read Frieren.

9:40am. Let me get started. I've been wasting too much time in my own thoughts and on 4chan.

I had time to think about how this UPMEM thing is going to go, and it is going to end with the article telling the company that for 8gb chips you in fact need 64-bit pointers otherwise nobody is going to program your devices. I've never expected that passing in arguments into the main kernel would be this messed up.

Oh, right. Let me just do a little redesign. Just one last thing and then the backend will be done.

```fs
    let incref_cancellation () =
        let g_incr' : Dictionary<TypedBind, TyV Set> = Dictionary(g_incr.Count, HashIdentity.Reference)
        for KeyValue(k,(incr,is_in_container)) in g_incr do
            let f (g : Dictionary<_,_>) = match g.TryGetValue(k) with true, x -> x | _ -> Set.empty
            let decr, suppr = f g_decr, f g_suppr
            let g a b = let r = Set.intersect a b in a - r, b - r
            let incr, decr = if is_in_container then g incr decr else incr, decr
            let incr, suppr = g incr suppr
            let add (d : Dictionary<TypedBind, TyV Set>) x = if Set.isEmpty x then ignore (d.Remove(k)) else d.[k] <- x
            add g_incr' incr; add g_decr decr; add g_suppr suppr
        {g_incr=g_incr'; g_decr=g_decr; g_suppr=g_suppr}
```

It is this thing. I am going to separate it out.

```fs
type RefcVars = {g_suppr : Dictionary<TypedBind,TyV Set>; g_decr : Dictionary<TypedBind,TyV Set>; g_incr : Dictionary<TypedBind,TyV Set>}
```

I am also going to turn the above into...

```fs
type RefcVars = {g_incr : Dictionary<TypedBind,TyV Set * bool>; g_decr : Dictionary<TypedBind,TyV Set>; g_suppr : Dictionary<TypedBind,TyV Set>}
```

```fs
let incref_cancel (incr,is_in_container) decr suppr =
    let g a b = let r = Set.intersect a b in a - r, b - r
    let incr, decr = if is_in_container then g incr decr else incr, decr
    let incr, suppr = g incr suppr
    {|incr=incr; decr=decr; suppr=suppr|}
```

Perfect.

I am just going to get rid of `incref_cancellation` completely.

```fs
let refc_prepass' incref_canc (new_vars : TyV Set) (x : TypedBind []) =
```

Won't need the flag here anymore either.

```fs
let refc_prepass (new_vars : TyV Set) (x : TypedBind []) =
```

Perfect.

```fs
            let _ =
                let f (g : Dictionary<_,_>) = match g.TryGetValue(x) with true, x -> Seq.toArray x | _ -> [||]
                refc_incr (f vars.g_incr) |> line' s; refc_decr (f vars.g_decr) |> line' s; refc_suppr (f vars.g_suppr) |> line' s
```

I will have to modify this, but that won't be hard.

```fs
            let _ =
                let f (g : Dictionary<_,_>) def = match g.TryGetValue(x) with true, x -> x | _ -> def
                let q = incref_cancel (f vars.g_incr (Set.empty, false)) (f vars.g_decr Set.empty) (f vars.g_suppr Set.empty)
                refc_incr (Set.toArray q.incr) |> line' s; refc_decr (Set.toArray q.decr) |> line' s; refc_suppr (Set.toArray q.suppr) |> line' s
```

Perfect.

The reason why I did that is simple, so I could optimize the indexing and binding operations.

```fs
                    List.iter2 (fun (L(data_i,_)) a ->
                        let a, s = data_free_vars a, indent s
                        Array.mapi (fun field_i (L(v_i,t)) -> $"{tyv t} v{v_i} = v{data_i}{acs}case{union_i}.v{field_i};") a |> line' s
                        ) is a
```

```fs
let inline get_default (memo_dict: Dictionary<_,_>) k def =
    match memo_dict.TryGetValue k with
    | true, v -> v
    | false, _ -> def()
```

I'll put this function into Utils.

```fs
            let _ =
                let q = incref_cancel (get_default vars.g_incr x (fun () -> Set.empty, false)) (get_default vars.g_decr x (fun () -> Set.empty)) (get_default vars.g_suppr x (fun () -> Set.empty))
                refc_incr (Set.toArray q.incr) |> line' s; refc_decr (Set.toArray q.decr) |> line' s; refc_suppr (Set.toArray q.suppr) |> line' s
```

Now, let me optimize away those unused vars.

```fs
                Map.iter (fun k (a,b) ->
                    let union_i = case_tags.[k]
                    let decr = get_default vars.g_decr (Array.head b) (fun () -> Set.empty)
                    line s (sprintf "case %i: { // %s" union_i k)
                    List.iter2 (fun (L(data_i,_)) a ->
                        let a, s = data_free_vars a, indent s
                        let qs = ResizeArray(a.Length)
                        Array.iteri (fun field_i (L(v_i,t) as v) ->
                            if Set.contains v decr = false then qs.Add $"{tyv t} v{v_i} = v{data_i}{acs}case{union_i}.v{field_i};"
                            ) a
                        line' s qs
                        ) is a
                    binds (indent s) ret b
                    line (indent s) "break;"
                    line s "}"
                    ) on_succs
```

Good. Now there are also 3 places more.

```fs
| TyLayoutIndexAll _ | TyLayoutIndexByKey _ | TyOp(ArrayIndex,_) -> (new_vars, true), r
```

Those would be here.

```fs
        let layout_index (x'_i : int) (x' : TyV []) =
            let decr = get_default vars.g_decr (Array.head b) (fun () -> Set.empty)
            let gs = Array.map (fun (L(i',_)) -> $"v{x'_i}->v{i'}") x'
            match ret with
            | BindsLocal x -> Array.map2 (fun (L(i,_)) g -> $"v{i} = {g};") x gs |> line' s
            | BindsTailEnd -> raise_codegen_error "Compiler error: Layout index should never come in end position."
```

Not really. How do I get the particular binding here.

```fs
            let decr = get_default vars.g_decr bind (fun () -> Set.empty)
            let gs = Array.choose (fun (L(i',_) as v) -> if decr.Contains v = false then Some $"v{x'_i}->v{i'}" else None) x'
            match ret with
            | BindsLocal x -> Array.map2 (fun (L(i,_)) g -> $"v{i} = {g};") x gs |> line' s
```

No what the hell?

```fs
| BindsLocal x -> Array.map2 (fun (L(i,_)) (L(i',_) as v) -> $"v{i} = v{x'_i}->v{i'};") x x' |> line' s
```

Instead of doing it...

```fs
        let layout_index (x'_i : int) (x' : TyV []) =
            match ret with
            | BindsLocal x ->
                let decr = get_default vars.g_decr bind (fun () -> Set.empty)
                let q = ResizeArray(x.Length)
                Array.iter2 (fun (L(i,_) as v) (L(i',_)) -> if decr.Contains v = false then q.Add $"v{i} = v{x'_i}->v{i'};") x x'
                line' s q
            | BindsTailEnd -> raise_codegen_error "Compiler error: Layout index should never come in end position."
```

This is the way to do it. Lastly arrays.

```fs
            | ArrayIndex, [DV(L(_,YArray t)) & a;b] ->
                match tup_ty t with
                | "void" -> "/* void array index */"
                | _ -> sprintf "%s->ptr[%s]" (tup_data a) (tup_data b)
```

Is this how it works? It has to be an error. Have I never tested arrays with tuples before in the C backend?

```c
int32_t main(){
    Array0 * v0;
    v0 = ArrayCreate0(1l, false);
    AssignArray0(&(v0->ptr[0l]), TupleCreate0(1ll, 2ll));
    int64_t v1; int64_t v2;
    Tuple0 tmp0 = v0->ptr[0l];
    v1 = tmp0.v0; v2 = tmp0.v1;
    ArrayDecref0(v0);
    return 0l;
}
```

Hmmm, it does work.

```fs
        let return' (x : string) =
            match ret with
            | BindsLocal [||] -> line s $"{x};"
            | BindsLocal [|L(i,_)|] -> line s $"v{i} = {x};"
            | BindsLocal ret ->
                let tmp_i = tmp()
                line s $"{tup_ty_tyvs ret} tmp{tmp_i} = {x};"
                Array.mapi (fun i (L(i',_)) -> $"v{i'} = tmp{tmp_i}.v{i};") ret |> line' s
            | BindsTailEnd -> line s $"return {x};"
```

I guess for arrays, I need to take care of it here then.

```fs
        let return' (x : string) =
            match ret with
            | BindsLocal ret ->
                let decr = get_default vars.g_decr bind (fun () -> Set.empty)
                let ret = Array.filter decr.Contains ret
                match ret with
                | [||] -> line s $"{x};"
                | [|L(i,_)|] -> line s $"v{i} = {x};"
                | _ ->
                    let tmp_i = tmp()
                    line s $"{tup_ty_tyvs ret} tmp{tmp_i} = {x};"
                    Array.mapi (fun i (L(i',_)) -> $"v{i'} = tmp{tmp_i}.v{i};") ret |> line' s
            | BindsTailEnd -> line s $"return {x};"
```

That should do it, let me just go forward with it.

I didn't strictly need to do this. It was just a whim.

```c
int32_t main(){
    Array0 * v0;
    ArrayCreate0(1l, false);
    AssignArray0(&(v0->ptr[0l]), TupleCreate0(1ll, 2ll));
    int64_t v1; int64_t v2;
    v0->ptr[0l];
    ArrayDecref0(v0);
    return 0l;
}
```

Let's see if it complains about unused vars now.

```c
    Array0 * v0;
    ArrayCreate0(1l, false);
```

It leads to erroneous results here. Note how it is not assigning the array after array create.

...But might reveal a bug in the refc counting analysis pass.

```fs
| TyArrayLiteral(_,l) | TyOp(_,l) -> List.fold (fun s x -> s + fv x) Set.empty l
```

No, it does not feel like that.

```fs
            | BindsLocal ret ->
                //let decr = get_default vars.g_decr bind (fun () -> Set.empty)
                //let ret = Array.filter decr.Contains ret
```

Let me comment this out for a bit.

```c
int32_t main(){
    Array0 * v0;
    v0 = ArrayCreate0(1l, false);
    AssignArray0(&(v0->ptr[0l]), TupleCreate0(1ll, 2ll));
    int64_t v1; int64_t v2;
    Tuple0 tmp0 = v0->ptr[0l];
    v1 = tmp0.v0; v2 = tmp0.v1;
    ArrayDecref0(v0);
    return 0l;
}
```

This really troubles me. It filtering out `v1 = tmp0.v0; v2 = tmp0.v1;` is fine.

```fs
v0 = ArrayCreate0(1l, false);
```

Ah, but the reason it is filtering out `v0` is because it is used right there.

Instead of passing in the current used var dictionary, I need to pass in the one at the next statement.

10:40am. And what about the used variable elimination in the if statements. I declare them on the outside of the if statements and they might not get used on the next one. So if I remove them, and they get assigned inside the if statement that will result in a compilation error.

I was wrong. This is too much of a pain in the ass.

Removing them in `UnionUnbox` was fine, but this is too much of a bother.

The C compiler is going to keep whining about unused vars no matter what I do anyway.

```fs
        let layout_index (x'_i : int) (x' : TyV []) =
            match ret with
            | BindsLocal x ->
                let decr = get_default vars.g_decr bind (fun () -> Set.empty)
                let q = ResizeArray(x.Length)
                Array.iter2 (fun (L(i,_)) (L(i',_) as v) -> if decr.Contains v = false then q.Add $"v{i} = v{x'_i}->v{i'};") x x'
                line' s q
            | BindsTailEnd -> raise_codegen_error "Compiler error: Layout index should never come in end position."
```

I guess I'll leave the optimization in layout index...

No, no, let me just wipe it all away. Remember what I said about needing to pass in the next statement?

```fs
        let layout_index (x'_i : int) (x' : TyV []) =
            match ret with
            | BindsLocal x -> Array.map2 (fun (L(i,_)) (L(i',_)) -> $"v{i} = v{x'_i}->v{i'};") x x' |> line' s
            | BindsTailEnd -> raise_codegen_error "Compiler error: Layout index should never come in end position."
```

I'll fold that outer map into the inner.

10:50am. Sigh, now let me test it out all again.

11am. Good enough. Let me publish a new version.

Published. No trouble this time. Changelog.

Added.

Now let me commit here. Hopefully I won't have to deal with the C backend anymore. It took up too much of my time and energy."