"The spot in the middle is too empty. Let me put down the Grand Casino.
4pm. It crashed so hard it took down the whole rig with it. Thankfully I am saving as I go along.

Right now I am trying to get the overall color composition right. Having an emissive floor is not a good idea. It messed with the light from other sources.

4:10pm. It crashed again. Maybe it is linked to Cycles being on.

4:15pm. And again. Ugh. Reminds me of V-Ray in Houdini.

4:25pm. This is the 4th time Cycles took down my entire system. Sigh...

4:35pm. 5th time. Blender is very crash happy in the latest version. Let me play around with the monkey head. I want to refresh my memory of the volume shader.

4:40pm. 6th time, this time on just the monkey head. Were the older version this unstable? Cycles in unusable here.

https://developer.blender.org/T96133

Let me play around in 3.1. Then I will check out 3.0.

Since the file appears to be forward compatible, let me take advantage of that to open it in 3.1.

4:55pm. Too bad Scatter 5 does not work in 3.1. I am obligated to use 3.2 now.

5:10pm. It crashes even with F12. 7th time.

Yeah, Cycles in unusable in 3.2.

I could try upgrading the graphics driver and seeing if that helps. But otherwise, let me just use Eevee. Or even Luxcore.

5:35pm. It seems this scene will get done one reset at a time. Let me take a break so I can upgrade my graphics drivers. Maybe that will help. This is not just an ordinary crash. Each time it took down the entire system.

5:45pm. The driver seems to be a decent behind. I had 517 while the latest is 571. The driver install does not allow me to leave out GeForce Experience. Well, as long as it does not bother me on startup I'll be happy.

Ok, let me give it a try. But I am not too hopeful. This is serious issue. If this does not work, I might end up having to use Eevee.

The save is actually corrupted.

5:55pm. Thankfully there are backups. I am not losing much except time.

I need to stop. I can't work like this.

Did Cycles work in 3.1, I think it did not crash there.

Ok, can I convert the Scatter 5 scene into Blender instances and import them in 3.2.

7:05pm. Done with lunch. While I was busy with that the render finished properly in the background. It seems that 3.1 is stable for me. Now that I have this, let me put it through style transfer.

```py
def save_path(data,path):
    """Returns the save path."""
    def get_name(x):
        base_name = ntpath.basename(data[x][0])
        return ntpath.splitext(base_name)[0]

    a_path = get_name('A_paths')
    image_name = '%s (%s).png' % (a_path, get_name('B_paths'))
    return os.path.join(path, a_path, image_name)
```

Let me change the way saving is done a little. I'll have it create it own dir for every image.

```py
os.makedirs(save_path,exist_ok=True)
```

I think I need to plug this in. Let me try it.

```
PermissionError: [Errno 13] Permission denied: './results/floating city v0\\floating city v0 (anime glasses girl).png'
```

Hmmm...

```
os.makedirs(os.path.dirname(save_path),exist_ok=True)
```

Let me try this.

7:20pm. Yeah, that works. While that is going on I might as well do a bug report.

No, I want to test 3.1 more thoroughly before I jump to conclussion that it is more stable.

7:25pm. Right now what happened is that the style transfer crashed and took the OS with it. Is my GPU dying?

7:35pm. I suppose this will do.

7:55pm. https://developer.blender.org/T99116
Cycles crashes after a few minutes of work

I opened this, but the bug report is not very informative, so I am not sure if anything will come of it.

This scene is cursed!

How is it possible that I am running into problems with Cycles all of a sudden. Just how am I supposed to do this scene?

8:05pm. Let me post one of the images that came out well in /wip/ and then I'll close.

///

This scene is cursed. I got a grasp on Scatter 5, and minus the bugs, its manual mode is revolutionary. It is to scattering what sculpting is to modeling.

I ran into all sorts of bugs with it, found workarounds with the help of the author, but now that I am doing shading I can't go more than 2m without Cycles crashing and taking the OS with it. This is not happening with previous 3.1 version of Blender so I managed to export the building instances and render it there.

I have no choice, but to keep going forward. I have a vague sense of what I want to do, but I am having trouble understanding how to make the scene impactful.

This particular style is not bad in isolation, but I don't think it will work once I add the other half of the scene. The way I am visualizing it is a view of the floating city from below as the golden light from it washes over the landscape. This particular style will make everything golden and that detail would get washed out.

///

I guess I'll post it on Twitter as well.

8:40pm.

> This sounds like a bug in OS or your hardware is failing. I would recommend to check system temperatures, and voltages in case of PSU failiure.
> I don't think remember any issue with similar symptoms to be ever confirmed as bug in Blender.

Got this reply from a Blender dev. Maybe I should open the rig and dust it off. Maybe there is a program that can help me diagnose temperatures and voltages? I should look for it.

8:45pm. Getting called a schizo and told to take my meds on /wip/ is really annoying. Maybe I should drop that place, like I said I would the last two times? Let me do a style transfer on a crab image, reply with it and then I am done for the day.

It actually did crash once while doing style transfer earlier. This really makes me concerned about the state of my hardware. It is quite scary. If the PC gives out before I can make money from Heaven's Key to replace it I really will drop all the art practice and get a job. Some things you simply have to take as an omen.

9pm. https://openhardwaremonitor.org/
> The Open Hardware Monitor is a free open source software that monitors temperature sensors, fan speeds, voltages, load and clock speeds of a computer.

I'll try this program tomorrow. I'll close here today.

*

9:20pm. I got told that it looks like an AI made it. This is due to there being too little variation in the image. Ignoring the big unique one in the middle, the city has only 4 different types of buildings. I need at least 7, and that is 6 of different sizes and rotations. Since this is not a forest, but a city, I can't do rotations and scaling arbitrarily, so I probably need even more. 4 versions for each of the 4 types of buildings. This rule of 7 is a pro tip from Blender Bob, it makes sense to me.

Edit: Also, come to think of it, phrasing it that way is also an attempt at suppression since they know well enough I want to use AI. There is a good cop/bad cop routine going on there, whether purposeful or not. If I fall into the mindset of being petulant and responding to their framing, I'll end up acting like a schizo for real. Much like leaving the PL sub, it is time to abort the /wip/ thread for good.

9:30pm. Forget this. It is time to relax.

11:10pm. > Behind every one of the four beyond Grade A Supers in the Shattered Star Ring were numerous financial groups. A powerful organization would always draw a large number of willing sponsors; thus, these powerful beings never needed to be afraid of going broke. Many of the financial groups in the universe were past the stage of accumulating wealth, and if they were not able to convert their wealth into influence or something useful, their wealth was no more than a useless string of numbers. Investing their wealth into such organizations that housed powerhouses was the best option for them.

Wise author. This is a good point for why people would give money to Ames.

11:55am. Given that it crashed once during style transfer, the CPU itself might be getting overheated. I am going to have to think about what I want to do carefully. I'll take the measurements tomorrow, if it turns out the temps are the problem, I'll open up the rig, dismantle the CPU and the GPUs and clean up the dust inside.

If that fails...then I'll stop work on Heaven's Key and get a programming job. It is one thing to not have hardware to do ML, but if I can't do rendering or style transfer, then there is no point in pursing this plan anymore. The rig is over 7 years old now, so it would not be strange if it started showing signs of wear and tear at some point.

12:20am. This is not the first time it has happened, remember those Luxcore renders before? This might be linked to that.

6/24/2022

11:40am. Damn, I went to bed at 2am, but had trouble falling asleep, so it is not wonder I am this late. My anxiety was high tonight, but surprisingly just telling myself to stop thinking about the troublesome stuff and go to sleep was enough. Even though I am up this late, I actually slept well. Not ideally, but I am not fatigued like I would be usually.

Right now, my main priority will be to check the temps as rendering is done in Blender. If this trouble does not have an easy explanation like CPU or the GPU overheating, then I am going to abort the Heaven's Key quest. What the dev says about this possibly being a hardware error makes complete sense to me. I couldn't write a program to crash the whole OS even if I wanted to. If something was really wrong with Cycles it would crash just Blender, not the whole system.

If the CPU and the GPU are overheating, I can make the problem better by cleaning up the dust inside the rig, but if not, I am screwed. So let me make sure of that.

12pm. Mhhhh, I do not see an option to do regular logging to hard disk. I really want to compare the start and just before it crashes. Right now there is too much info in the application, I can't follow it and play with Blender at the same time.

It has some kind of web server that I could use to exchange data, but I do not know how to make use of that.

12:05pm. https://www.reddit.com/r/buildapc/comments/8dg2op/software_that_can_save_cpu_temperature_vs_time_to/

///

I use Open Hardware Monitor and it is great. You dismissed it, but it does exactly what you want - if you toggle Log Sensors under Options, it will automatically save all sensor data as a function of time to a dated file in the directory the executable is in. The logging interval can be set as well. You can also use the Plot function to visualize your data as they are being recorded.

It is also open source, which is a big plus for me.

///

Oh, really? Great. That solves all my problems.

Before I start, let me chill a little. I guess I'll skip the morning session."