"3:40pm. The thing actually finished before I left for the bath, but I decided to go for it anyway. I really with I did not use v2-install and instead had been more patient. Now I just used up a bunch of space over nothing. Let me finally try to get some examples going.
---

Once this works go to a suitable directory and run

```
> git clone https://github.com/agda/cubical
> cd cubical
> make
```

This should compile all of the agda/cubical files. To test that it
works in emacs run

```
> emacs Cubical/Core/Primitives.agda
```

and then type `C-c C-l`. This should now load the file and you can
start developing your own cubical files.

---

```
E:\TheoremProving\Cubical Agda Stuff\cubical\Cubical\Core\Primitives.agda:193,3-196,16
A (i ∧ i0) → A (i ∧ i1) !=< A i of type
Set (ℓ-max (ℓ′ (i ∧ i0)) (ℓ′ (i ∧ i1)))
when checking that the inferred type of an application
  A (i ∧ i0) → A (i ∧ i1)
matches the expected type
  A i
```

Well, I did not do the first step yet though.

```
PS E:\TheoremProving\Cubical Agda Stuff\cubical> make
cabal exec -- fix-agda-whitespace --check
Warning: The exec command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-exec command
or the legacy v1-exec alias as new-style projects will become the default in
the next version of cabal-install. Please file a bug if you cannot replicate a
working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

cabal: The program 'fix-agda-whitespace' is required but it could not be
found.

make: *** [GNUmakefile:11: check-whitespace] Error 1
```

Yeah, I expected issues such as these.

This stuff tends to happen. But even if I did not run `make`, I still do not think I should have gotten that type error.

I am going to have to open an issue for this.

4:15pm. I opened an issue. There was something about the file only compiling on the dev version of Agda. I am going to have to install it.

```
This should put the agda and agda-mode executables in the folder ~/.cabal/bin (the location can be configured with --symlink-bindir flag).
```

It is really annoying that sym links do not work on Windows. This is why I could not run Agda from the command line when I did the v2-install.

4:25pm.

```
PS E:\TheoremProving\CubicalAgdaStuff\agda> cabal v2-install agda agda-mode
Wrote tarball sdist to
E:\TheoremProving\CubicalAgdaStuff\agda\dist-newstyle\sdist\Agda-2.6.1.tar.gz
Wrote tarball sdist to
E:\TheoremProving\CubicalAgdaStuff\agda\dist-newstyle\sdist\fix-agda-whitespace-0.0.4.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - Agda-2.6.1 (lib:Agda, exe:agda, exe:agda-mode) (requires build)
Starting     Agda-2.6.1 (all, legacy fallback)
Building     Agda-2.6.1 (all, legacy fallback)
Warning: Some package(s) failed to build. Try rerunning with -j1 if you can't
see the error.

PS E:\TheoremProving\CubicalAgdaStuff\agda> cabal v2-install agda agda-mode -j1
Wrote tarball sdist to
E:\TheoremProving\CubicalAgdaStuff\agda\dist-newstyle\sdist\Agda-2.6.1.tar.gz
Wrote tarball sdist to
E:\TheoremProving\CubicalAgdaStuff\agda\dist-newstyle\sdist\fix-agda-whitespace-0.0.4.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - Agda-2.6.1 (lib:Agda, exe:agda, exe:agda-mode) (requires build)
[1 of 1] Compiling Main             ( C:\Users\Marko\AppData\Local\Temp\cabal-install.-5016\dist-newstyle\tmp\src-5016\Agda-2.6.1\dist\setup\setup.hs, C:\Users\Marko\AppData\Local\Temp\cabal-install.-5016\dist-newstyle\tmp\src-5016\Agda-2.6.1\dist\setup\Main.o )
Linking C:\Users\Marko\AppData\Local\Temp\cabal-install.-5016\dist-newstyle\tmp\src-5016\Agda-2.6.1\dist\setup\setup.exe ...
Configuring Agda-2.6.1...
Preprocessing executable 'agda-mode' for Agda-2.6.1..
Building executable 'agda-mode' for Agda-2.6.1..
[1 of 2] Compiling Paths_Agda       ( dist\build\agda-mode\autogen\Paths_Agda.hs, dist\build\agda-mode\agda-mode-tmp\Paths_Agda.o )
[2 of 2] Compiling Main             ( src\agda-mode\Main.hs, dist\build\agda-mode\agda-mode-tmp\Main.o )
Linking dist\build\agda-mode\agda-mode.exe ...
Preprocessing library for Agda-2.6.1..
Building library for Agda-2.6.1..
[  1 of 372] Compiling Agda.Interaction.BasicOps[boot] ( src\full\Agda\Interaction\BasicOps.hs-boot, dist\build\Agda\Interaction\BasicOps.o-boot )
[  2 of 372] Compiling Agda.Interaction.Options.IORefs ( src\full\Agda\Interaction\Options\IORefs.hs, dist\build\Agda\Interaction\Options\IORefs.o )
[  3 of 372] Compiling Agda.Syntax.Builtin ( src\full\Agda\Syntax\Builtin.hs, dist\build\Agda\Syntax\Builtin.o )
[  4 of 372] Compiling Agda.Termination.CutOff ( src\full\Agda\Termination\CutOff.hs, dist\build\Agda\Termination\CutOff.o )
[  5 of 372] Compiling Agda.Termination.Semiring ( src\full\Agda\Termination\Semiring.hs, dist\build\Agda\Termination\Semiring.o )
[  6 of 372] Compiling Agda.Utils.AffineHole ( src\full\Agda\Utils\AffineHole.hs, dist\build\Agda\Utils\AffineHole.o )
[  7 of 372] Compiling Agda.Utils.Applicative ( src\full\Agda\Utils\Applicative.hs, dist\build\Agda\Utils\Applicative.o )
[  8 of 372] Compiling Agda.Utils.BiMap ( src\full\Agda\Utils\BiMap.hs, dist\build\Agda\Utils\BiMap.o )
[  9 of 372] Compiling Agda.Utils.Environment ( src\full\Agda\Utils\Environment.hs, dist\build\Agda\Utils\Environment.o )
[ 10 of 372] Compiling Agda.Utils.Except ( src\full\Agda\Utils\Except.hs, dist\build\Agda\Utils\Except.o )
[ 11 of 372] Compiling Agda.Utils.Float ( src\full\Agda\Utils\Float.hs, dist\build\Agda\Utils\Float.o )
[ 12 of 372] Compiling Agda.Utils.Function ( src\full\Agda\Utils\Function.hs, dist\build\Agda\Utils\Function.o )
[ 13 of 372] Compiling Agda.TypeChecking.SizedTypes.Utils ( src\full\Agda\TypeChecking\SizedTypes\Utils.hs, dist\build\Agda\TypeChecking\SizedTypes\Utils.o )
[ 14 of 372] Compiling Agda.Utils.Functor ( src\full\Agda\Utils\Functor.hs, dist\build\Agda\Utils\Functor.o )
[ 15 of 372] Compiling Agda.Utils.Graph.TopSort ( src\full\Agda\Utils\Graph\TopSort.hs, dist\build\Agda\Utils\Graph\TopSort.o )
[ 16 of 372] Compiling Agda.Utils.Haskell.Syntax ( src\full\Agda\Utils\Haskell\Syntax.hs, dist\build\Agda\Utils\Haskell\Syntax.o )
[ 17 of 372] Compiling Agda.Utils.IO    ( src\full\Agda\Utils\IO.hs, dist\build\Agda\Utils\IO.o )
[ 18 of 372] Compiling Agda.Utils.IO.Binary ( src\full\Agda\Utils\IO\Binary.hs, dist\build\Agda\Utils\IO\Binary.o )
[ 19 of 372] Compiling Agda.Utils.IO.Directory ( src\full\Agda\Utils\IO\Directory.hs, dist\build\Agda\Utils\IO\Directory.o )
[ 20 of 372] Compiling Agda.Utils.IO.UTF8 ( src\full\Agda\Utils\IO\UTF8.hs, dist\build\Agda\Utils\IO\UTF8.o )
[ 21 of 372] Compiling Agda.Utils.IO.TempFile ( src\full\Agda\Utils\IO\TempFile.hs, dist\build\Agda\Utils\IO\TempFile.o )
[ 22 of 372] Compiling Agda.Utils.IORef ( src\full\Agda\Utils\IORef.hs, dist\build\Agda\Utils\IORef.o )
[ 23 of 372] Compiling Agda.Utils.Impossible ( src\full\Agda\Utils\Impossible.hs, dist\build\Agda\Utils\Impossible.o )
[ 24 of 372] Compiling Agda.Utils.Empty ( src\full\Agda\Utils\Empty.hs, dist\build\Agda\Utils\Empty.o )
[ 25 of 372] Compiling Agda.Utils.Bag   ( src\full\Agda\Utils\Bag.hs, dist\build\Agda\Utils\Bag.o )
[ 26 of 372] Compiling Agda.ImpossibleTest ( src\full\Agda\ImpossibleTest.hs, dist\build\Agda\ImpossibleTest.o )
[ 27 of 372] Compiling Agda.Auto.NarrowingSearch ( src\full\Agda\Auto\NarrowingSearch.hs, dist\build\Agda\Auto\NarrowingSearch.o )
[ 28 of 372] Compiling Agda.Utils.IntSet.Infinite ( src\full\Agda\Utils\IntSet\Infinite.hs, dist\build\Agda\Utils\IntSet\Infinite.o )
[ 29 of 372] Compiling Agda.Utils.Lens  ( src\full\Agda\Utils\Lens.hs, dist\build\Agda\Utils\Lens.o )
[ 30 of 372] Compiling Agda.Utils.IndexedList ( src\full\Agda\Utils\IndexedList.hs, dist\build\Agda\Utils\IndexedList.o )
[ 31 of 372] Compiling Agda.Interaction.Library.Base ( src\full\Agda\Interaction\Library\Base.hs, dist\build\Agda\Interaction\Library\Base.o )
[ 32 of 372] Compiling Agda.Auto.Options ( src\full\Agda\Auto\Options.hs, dist\build\Agda\Auto\Options.o )
[ 33 of 372] Compiling Agda.Utils.Lens.Examples ( src\full\Agda\Utils\Lens\Examples.hs, dist\build\Agda\Utils\Lens\Examples.o )
[ 34 of 372] Compiling Agda.Utils.Map   ( src\full\Agda\Utils\Map.hs, dist\build\Agda\Utils\Map.o )
[ 35 of 372] Compiling Agda.Utils.Maybe ( src\full\Agda\Utils\Maybe.hs, dist\build\Agda\Utils\Maybe.o )
[ 36 of 372] Compiling Agda.Utils.ListT ( src\full\Agda\Utils\ListT.hs, dist\build\Agda\Utils\ListT.o )
[ 37 of 372] Compiling Agda.Interaction.Options.Warnings ( src\full\Agda\Interaction\Options\Warnings.hs, dist\build\Agda\Interaction\Options\Warnings.o )
[ 38 of 372] Compiling Agda.Interaction.Options.Help ( src\full\Agda\Interaction\Options\Help.hs, dist\build\Agda\Interaction\Options\Help.o )
[ 39 of 372] Compiling Agda.Utils.Memo  ( src\full\Agda\Utils\Memo.hs, dist\build\Agda\Utils\Memo.o )
[ 40 of 372] Compiling Agda.Utils.Monoid ( src\full\Agda\Utils\Monoid.hs, dist\build\Agda\Utils\Monoid.o )
[ 41 of 372] Compiling Agda.Utils.NonemptyList ( src\full\Agda\Utils\NonemptyList.hs, dist\build\Agda\Utils\NonemptyList.o )
[ 42 of 372] Compiling Agda.Utils.Null  ( src\full\Agda\Utils\Null.hs, dist\build\Agda\Utils\Null.o )
[ 43 of 372] Compiling Agda.Utils.Maybe.Strict ( src\full\Agda\Utils\Maybe\Strict.hs, dist\build\Agda\Utils\Maybe\Strict.o )
[ 44 of 372] Compiling Agda.Utils.Parser.ReadP ( src\full\Agda\Utils\Parser\ReadP.hs, dist\build\Agda\Utils\Parser\ReadP.o )
[ 45 of 372] Compiling Agda.Utils.PartialOrd ( src\full\Agda\Utils\PartialOrd.hs, dist\build\Agda\Utils\PartialOrd.o )
[ 46 of 372] Compiling Agda.Utils.POMonoid ( src\full\Agda\Utils\POMonoid.hs, dist\build\Agda\Utils\POMonoid.o )
[ 47 of 372] Compiling Agda.Utils.Pointer ( src\full\Agda\Utils\Pointer.hs, dist\build\Agda\Utils\Pointer.o )
[ 48 of 372] Compiling Agda.Utils.SemiRing ( src\full\Agda\Utils\SemiRing.hs, dist\build\Agda\Utils\SemiRing.o )
[ 49 of 372] Compiling Agda.Utils.Singleton ( src\full\Agda\Utils\Singleton.hs, dist\build\Agda\Utils\Singleton.o )
[ 50 of 372] Compiling Agda.Utils.Cluster ( src\full\Agda\Utils\Cluster.hs, dist\build\Agda\Utils\Cluster.o )
[ 51 of 372] Compiling Agda.Utils.Size  ( src\full\Agda\Utils\Size.hs, dist\build\Agda\Utils\Size.o )
[ 52 of 372] Compiling Agda.Utils.Pretty ( src\full\Agda\Utils\Pretty.hs, dist\build\Agda\Utils\Pretty.o )
[ 53 of 372] Compiling Agda.Utils.Parser.MemoisedCPS ( src\full\Agda\Utils\Parser\MemoisedCPS.hs, dist\build\Agda\Utils\Parser\MemoisedCPS.o )
[ 54 of 372] Compiling Agda.Utils.FileName ( src\full\Agda\Utils\FileName.hs, dist\build\Agda\Utils\FileName.o )

src\full\Agda\Utils\FileName.hs:117:19: error:
    Variable not in scope: and2M :: IO Bool -> IO Bool -> IO Bool
    |
117 |   doesFileExist f `and2M` do
    |                   ^^^^^^^
Warning: Some package(s) failed to build. Try rerunning with -j1 if you can't
see the error.
```

Oh boy. The `-j1` option is cool as I can see the progress of compilation rather wondering whether it froze at some point, but I guess this development branch is too raw.

What should I do now? Maybe I could try some earlier version of the Cubical library. Is there one that is compatible with Agda 2.6.0.1?

I am completely new to this cubical stuff, so I do not need the latest version anyway.

4:40pm. I am going to change targets for the time being. Maybe I'll get somewhere with RedPRL or RedTT.

https://arxiv.org/abs/1802.01170
On Higher Inductive Types in Cubical Type Theory

For now I guess I'll read this. These installation issues always seem to crop up whenever I try anything new. It is such a useless timewaster.

4:50pm. https://github.com/redprl/sml-redprl

```
First, fetch all submodules. If you are cloning for the first time, use

git clone --recursive git@github.com:RedPRL/sml-redprl.git
If you have already cloned, then be sure to make sure all submodules are up to date, as follows:

git submodule update --init --recursive
Next, make sure that you have the MLton compiler for Standard ML installed. Then, simply run

./script/mlton.sh
Then, a binary will be placed in ./bin/redprl, which you may run as follows

./bin/redprl example/README.prl
```

```
Editor Support: Vim
Our best-supported editor is currently Vim. See the RedPRL plugin under vim/.
```

Please spare me. Not only do I have to install a compiler just to get it, but I also have to deal with Vim.

4:55pm. https://github.com/RedPRL/redtt

```
Prerequisites
prerequisite  version how to install
Opam >= 2.0.1 manually or via package manager
If this is your first time configuring OPAM, please run opam init; this will automatically install OCaml. If you are using a version of OCaml other than 4.07.0, you must run opam switch 4.07.0.

Other recommended packages
We recommend installing merlin and ocp-indent using opam; the easiest way to edit OCaml code out of the box is to install Visual Studio Code along with the OCaml and Reason IDE package by Darin Morrison.
```

The issue with RedTT is that it is completely undocumented. It would be one thing if I knew everything there is to know about type theory and am picking it up or if I knew at least the syntax of the tactics language, but right now my goal is just to figure out the basics of the new cubical type theory.

Even though I've seen Harper and Bauer do it on the blackboard, that really meant nothing to me. What I really need is some first hand experience to at least get a sense for how they work.

5:10pm. https://github.com/RedPRL/redtt/blob/master/library/prelude/path.red

This does not look too bad, but it is sufficiently unfamiliar that I really do require documentation to grook this.

I suppose at some point, if I am really that serious about formalization of math, I am going to require diving into both Cubical Agda and RedTT's source. I am going to need the understanding how dependently typed languages are implemented.

But that is not now.

Since Cubical Agda is my only real choice here, I think I am going to go back a bunch of comits until I find a version of the Cubical library that typechecks.

5:20pm. I guess this will be my goal for the next week or two - to play with the Cubical library.

I won't set anythin concrete as my goal. Merely - figure out how HITS and all this higher dimensional type stuff is used.

I do not exactly have a lot of options here. Despite its hype, HoTT is only really understood by a small circle of experts at this point in time and there are only isolated efforts to bring it into the world of computing. Cubical Agda is my best bet at the moment.

5:25pm. Apart from that, after I am done with this, what is waiting for me is an investigation of existing math formalization efforts in regular extensional type theory. There is no doubt that I will find plenty this in Coq, Agda and Lean. So I just have to pick my poison and go for it.

Once I gain sufficient experience in this and have done my survey, I will know which way do I need to go in order to start formalizing ML algorithms. The hunt for THE metaheuristic algorithm will start there.

Spiral might be sufficient for implementation of advanced learning algorithms of any platform imaginable, but to actually find those algorithms I need something more. A new, better language. I am not really talking about the kind of language one programs in, but the language in which one thinks.

Remember back to late 2016. At that time thanks to all the effort I've put into functional programming, the seeds of Spiral had already been planted in me. So in 2017, all I had to do is to put the necessary effort into manifesting it.

Right now I am far from that as far as mathematics is concerned. I am going to have to put in constant, steady effort into this just like I had to with Spiral. I had to suffer a lot to bring Spiral up to v0.1, and it won't be any different with this. Only hell awaits going from here, but I am going to go forward and plunge myself into the portal.

I've been naive. There is no way this could have played out any other way. There is no way a bunch of people who cannot even see the essential properties of the self improvement loop could ever be left to work out the important details of learning algorithms.

I know I suck. There is always a 100 reasons not to undertake something like this - you were always bad at math, you are not good at it now, there is too much of it to go around, doing math in theorem provers is too tedious, because it is tedious it makes sense to just 'think' instead, there are so many people smarter than you working on this, they are actually getting paid to do this, even if you suceed then what - the self improvement loop will just kill you, they have so much more resources at their disposal, doing it like this is sheer insanity - just for how long do you think you will be able to do this, you most likely won't suceed and will have wasted your life doing nothing - in this time would it not make more sense to get a job and have some fun with life? Just like in the past 4.5 years you did not attain what you sought and just like in your 6 years of trading you did not make a cent. You do not have infinite time, but there is still room in your life to become normal and maybe get a job. Leave math to somebody else! There is nothing wrong with living like that in this era peace!

Of course it is.

Two decades ago when I realized that the meaning of life is to obtain omnipotence, I was really serious when I asserted that any price is worth paying for it. From that point on that was the only thing I ever wanted in life - complete and absolute power.

I must not forget, as insignificant as I am, there is still a chance for me to be something more than normal. Win or lose, it is only in this era that one will have a chance to chase after the Singularity. Why live and die as a human when you can leave your humanity behind and do something more?

Even if it requires going beyond what is possible. Even if it requires challenging two different fields at once, and even going as far as to completely destroy one of them. Any idiot can just go with the flow. It takes strength to reject it.

I admire those people who leave the easy paths to other in order to challenge the desert.

I want to live my life as somebody who never abandoned his purpose no matter what challenges came his way. And no matter the blows he never abandoned the pride to do that one thing.

6pm. Though it will have many substeps and might be a long stretch of work, this will in fact be the final stretch. The one thing I've really needed at the outset to really do this undertaking, I will do from here on out.

When I find the algorithm, the Singularity - and the end of the era of man - will begin.

But for now, let me call it a day here. It has been a very slow start, but tomorrow I should be able to knock something out. Mastering HoTT and cubical TT languages will be a recuring theme as time goes on and here is where the first real step will get made.

A few more years of this and I should be complete and peerless as a programmer. When I finally break the dependency on the current crop of ML researchers that is when the real fun will start. But even before that, since it will be a long trek the most important thing is to find fun wherever I may along the way and get some good rests during the stops.

Let me do that now."