"1:35pm. Done with breakfast. Let me read another chapter or two of Girls Frontline and then I will resume. I'll want to figure out how packages are setup and how the compilation order works in Julia. Then I need to figure out how to step through the programs. That will allow me to investigate the Omega library.
1:50pm. Let me resume. I can't stand this standing still. Let just do this, and I will have full proficiency with Julia. After that it will be time to master probabilistic programming. Maybe my luck is not completely horrible that I found an out in it. If it wasn't for that job post by Zenna who knows what I would be doing now.

I think that my quest for the Singularity would have ended right there. So I am pretty lucky.

It really would have taken a much larger leap of intuition to pick up probabilistic programming on my own. I am not sure I would have been capable of it.

2:15pm. https://pkgdocs.julialang.org/v1/getting-started/

This is pretty confusing. I managed to create a fresh project using the instruction here, but adding functions and new files is failing for me. Just how does this work?

2:35pm. https://pkgdocs.julialang.org/v1/environments/

This is so convoluted. Even adding a module in the Example file won't let me import it. What the hell?

Let me skim this until I get what I want.

2:40pm. This is so confusing. No `add` is not the right command to add those modules.

2:45pm. No, I do not get it. The documentation is too incomplete. It is really a wonder that they ommitted such a vital step. I'll have to rely on the Internet.

https://www.youtube.com/results?search_query=julia+package

Let me check this out.

https://discourse.julialang.org/t/what-is-the-preferred-way-to-use-multiple-files/30687/13

This is confusing me. Is there no way to have multiple files in a package? But Omega did have that.

Why is this so confusing?

https://www.youtube.com/watch?v=QVmU29rCjaA
Developing Julia Packages

Ah what the hell, let me watch this.

https://youtu.be/QVmU29rCjaA?t=535

Ok, here he is doing an `include`? Huh really? Is this how it should work? Raw `include`s?

3:05pm. Ok, that was a mind twister. I guess I know how to deal with packages now. I did find it confusing about there being nothing about the extra files in the toml files for Omega. I think if I look more closely, I will see that all dependencies are through includes.

Though this is ugly, this will ensure that there are no circular dependencies. Like with F# and Spiral, Julia should have a linear compilation order.

Ok, the next thing on my list is the debugger.

But first...

///

Hi Marko,

Thank you for your interest in Tessian and for successfully completing our HackerRank!

We're delighted to invite you to the next steps from our side which will be a call with one of the Team, either Engineering Manager, Ahmed Opeyemi, or Team Lead, Sam Cox . Following the call we expect the next steps to include a codepair challenge then a final stage interview where you will meet some more of the team.

There's nothing specific to prepare for in this call; you'll be discussing your recent experience. Please see below a link to schedule in a time that's suitable for you.

///

There is a link to schedule the call, but at this point I've completely lost interest in these interviews.

I've decided to fully commit to doing work on PPLs.

Now if I could only find the courage to reject this offer that would be swell. One thing I worried about is part time work by Zenna not being sent my way and my computer breaking down. A voice inside of me is telling me to play it safe and not reject the interview outright. I've regretted burning my bridges with Groq.

Sigh, what do I do?

Ok, I'll defer the decision. They made me wait a week, so I can treat them the same way.

I mean, if I get mail from Z that he won't be able to send paid work my way for whatever reason, I'd have to think really hard whether I want to reject this offer. Do I want to spend a few more years going without any funds like I have in the past? It took a fair amount of effort just to get to the second step here.

Though the next time if I try this it should be easier as I'll have pared down my resume and pretended to be a freelancer. I'll also turn my resume into a buzzword soup for the HR drones to chew on.

3:25pm. For that reason I won't reject it outright until I get feedback from the thread I am really interested in.

Of course ideally I'd complete the poker agent and ransack the online gambling dens, but who knows how long that would take me. Years? I've already failed at that for long enough. To do that I'd need to become a PPL expert, build the game in Julia and have trained the agent. That would take too long.

https://julialang.org/blog/2019/03/debuggers/

Let me focus on this. Forget about that email.

3:35pm. Ok, let me ignore the issue of generating a project with a git. For some reason `generate SubExample` did it without. Forget about this.

How do I debug Julia in VS Code?

3:40pm.

```jl
q = 2+2
w = q * 3
r = w + w
using .Example
println(Example.plusone(r))
```

Setting breakpoints here works just fine.

Great. Getting the debugger to work was no trouble at all. Though it has a mean startup.

3:50pm. Looking at function wrappers. I've found it strange that Julia never mentioned having function types like `Int -> Int`. Right now that is an open issue.

Ok, let me take a short break here. I do not feel like diving into Omega right away. Maybe I'll watch more of that talk from the morning.

4:10pm. Let me watch that vid for a bit and then I'll instantiate the Omega library and step through some simple examples.

Instead of making things complicated, I really should just close the Tessian and Green Hills threads and free up my mental space. Ok, I'll do it tomorrow morning for Tessian, and for Green Hills whenever the reply arrives. So what even if I do not make any money for the next few years? In the worst case that my comp breaks down, I'll take a loan from my family and make it a priority to pay it off.

In that case of absolute need I'll get work wherever and temporarily abandon my quest.

But otherwise, poverty is fine. Poverty and hunger cultivate the appetite of the soul. Hasn't my pursuit of the last 6.5 years been a mark of greatness?

Why don't I do more of that and bring this arc to its conclusion? Yeah, this legendary pursuit of mine should be enshrined for all eternity in these Spiral commits.

4:20pm. I've thoroughly mastered regular logic, so I should master its extended version as well.

Onwards. Let me watch some of the talk I left off in the morning. Then I'll step through Omega for the first time.

4:25pm. No, nevermind. Let me just step through Omega. I do not feel like watching the talk. It is time to get this done.

https://pkgdocs.julialang.org/v1/environments/#Using-someone-else's-project

Let me try this.

4:30pm. Ok, I have a sense for what the main structure is. `Omega.jl` in src is made up of includes and exports.

https://github.com/simonster/Reexport.jl

This explains the @reexport macro.

Right now I am waiting for it to finish precompiling various packages.

4:40pm. Precompiling Omega itself is sure taking a while. Hopefully it won't end with an error.

///

Precompiling project...
  76 dependencies successfully precompiled in 644 seconds (11 already precompiled)

///

Wonderful. It would have been hard had I ran into any errors.

```
julia> using Omega
WARNING: using Omega.Omega in module Main conflicts with an existing identifier.
ERROR: importing Omega into Main conflicts with an existing identifier
```

Huh...Maybe it is because I tried running the module itself in VS Code. Let me restart it then.

Oh, it worked.

```jl
using Omega

x = normal(0,1)
rand(x)
```

This works fine. Now let me step into it. I'll put a breakpoint on `x`. I'll gradually move to more complex examples.

```
normal(μ, σ; id::ID = uid()) = Normal(μ, σ, id)
```

Oh it is interesting. It gives it an `uid()`. It did not step into that function, but nevermind.

It turns out Normal is a struct that just holds these 3 params.

```jl
struct Normal{A, B} <: PrimRandVar
  μ::A
  σ::B
  id::ID
  Normal(μ::A, σ::B, id = uid()) where {A, B} = new{A, B}(μ, σ, id)
end
```

```jl
"Single sample form from `x`"
function Base.rand(x::RandVar;
                   alg::SamplingAlgorithm = defalg(x),
                   ΩT = defΩ(alg),
                   kwargs...)
  first(rand(Random.GLOBAL_RNG, x, 1, alg; ΩT = ΩT, kwargs...))
end
```

What is that `ΩT`? It is not the RNG.

```jl
function Base.rand(rng::AbstractRNG,
                   x::RandVar,
                   n::Integer,
                   alg::FailUnsatAlg;
                   ΩT::Type{OT} = defΩ(alg)) where {OT <: Ω}
  pred = Omega.indomain(x)
  ωsamples = rand(rng, ΩT, pred, n, alg)
  map(ω -> apl(x, ω), ωsamples)
end
```

So `ΩT` is a type?

4:55pm. I am getting lost in thoughts. Let me just go through this.

```jl
"`n` samples from `x`"
function Base.rand(rng::AbstractRNG,
                   ΩT::Type{OT},
                   pred::RandVar,
                   n::Integer,
                   alg::FailUnsatAlg) where {OT <: Ω}
  ωsamples = ΩT[]
  ωsamples = Vector{ΩT}(undef, n)
```

I guess he must have forgotten to remove the dual assignment here.

5pm.

```jl
LinearΩ{I, SEG, V}() where {I, SEG, V} = LinearΩ{I, SEG, V}(Dict{I, SEG}(), emp(V))
```

This is what happens when the constructor for `ΩT` gets called. Incidentally, the experience of going through the manual really does make this a lot easier.

```jl
# zt: should Linear Omega be default?
"""
LinearΩ: Stores data in single `AbstractVector{V}`

`lω[i] = lω.ωvec[lω.ids[i]]`

- No overhead for linearization / delinearization
- Good for optimization / inference methods which require linear interface
- If heterogenous elements are used, must convert (which can be slow)
"""
struct LinearΩ{I, SEG, V <: AbstractArray} <: ΩBase{I}
  ids::Dict{I, SEG} # zt: too precise, any associable will do. Map from Ω index I to segment of omvec
  ωvec::V
end
```

5:15pm.

```jl
@generated function apl(rv::RandVar, tω::TaggedΩ{I, Tags{K, V}, ΩT}) where {I, K, V, ΩT <: ΩBase}
  if hastags(tω, :replmap)
    :(Omega.Causal.replaceapl(rv, tω))
  elseif hastags(tω, :cache)
    :(memapl(rv, tω))
  else
    :(ppapl(rv, proj(tω, rv)))
  end
```

Agh, this caused the debugger to crash. Let me try once again.

5:25pm. Hrrmmm...Let me try stepping over it. I guess my first challenge in Omega will be rewriting the above into a regular function.

Oh stepping over it works. Not bad. Let me just keep going.

5:30pm. Done with the first step through. Let me do a bit more I haven't seen what that apply does.

```
ERROR: Method is @generated; try `code_lowered` instead.
```

I keep getting this error. Let me open an issue.

6pm. Ok, done. And it is already 6pm.

It will be a long road to mastery. Even the small fragments that I've seen feel pretty complex.

As a stopgap measure, I'll try rewriting the @generated functions into normal ones tomorrow.

6:10pm. Getting a grip on this will involve refactoring exercises. I'll also have to try to isolate the functionality into my own smallish library to get a sense for it.

I suppose it is a good thing I am trying this now rather than a few years ago. Right now I am just at the right point in my development to even attempt something like this. Imagine if I had no PL or even ML experience. It would be very hard. Right now it should be fairly doable to completely master this.

6:15pm. I'll do this. If I can master Omega, I should be able to push my ML skills into the 3/5 area. That might be enough to inspire me in how to create the poker agent.

Let me have lunch here. I did enough for the day. Tomorrow, I am going to spend the entire day studying Omega."