"https://boards.4channel.org/g/thread/92480791/twg-tech-workers-general#p92486239
///

>>92485616
If you haven't worked in industry you don't know shit and interviewers will spot the hell out of you. Programming fundamentals and tool experience is only about half of the job. The other half you don't know the first thing about.

///

///

>>92486239
On the other hand, a lot of that other half can be time wasting bullshit depending on your employment, at which point learning and creating on your own can be far more effective.

///

///

>>92486239
Bullshit.
Although I wouldn't suggest doing it, it is possible to pull off.
If the guy has projects, it would be much better to publish them in git and showcase that. Managers love git profiles with lots of projects. At least mine do.

///

///

>>92486239
I agree with this anon. There is so much shit you'd never do as a hobbyist/student programmer, that you do in a professional environment.

///

///

>>92486361
Off the top of my head: SCRUM / Agile JIRA bullshit, slightly more complex git flow involving interactive rebases, DevOps, extensive testing, observability, documentation, anything involving a team like PRs and pair programming, and obviously documentation. Still, I feel like you can pick all this shit up on the job, if your fundamental skills are good I don't see why you wouldn't be able to get away with lying about this shit.

///

https://www.youtube.com/watch?v=1xLlUlmLgYs
Diagnosing ASP.NET Core Startup Issues in Azure App Service

I am going to watch this tomorrow.

https://www.youtube.com/results?search_query=azure+web+app+cli

It might be worth figuring out how to do it from the CLI as well. That would eliminate Farmer as the source of trouble. I'll try out the CLI tomorrow.

https://davecallan.com/uploading-files-to-azure-app-service-directly-azure-portal-without-ftp/

I am going to have to try this out tomorrow. I've been wondering how to look at the insides of my web app.

///

Despite its lack of visual feedback you can upload files directly into your Azure App Service via the Azure portal. This can be done via the Kudo Console or in the new App Service Editor (preview).

To open the Kudo Console navigate to YOUR APP SERVICE -> Development Tools -> Advanced Tools or bookmark https://yourappservice.scm.azurewebsites.net/DebugConsole. And then just drag and drop the files you want uploaded onto the relevant folder.

///

///

To open App Service Editor navigate to YOUR APP SERVICE -> Development Tools -> App Service Editor (Preview) or bookmark https://yourappservice.scm.azurewebsites.net/dev. You can upload files by dragging them onto the Explore pane on the LHS.

///

I'll save this here.

https://enso.org/

I really should try Enso instead of ComfyUI.

https://enso.org/docs/reference

But its docs despite the bright landing page are non existent. Too bad they didn't hire me. Oh well.

https://compositionalit.github.io/farmer/tutorials/webapp-deploy/

The instructions here are really simple. I doubt the farmer template in the build file is wrong.

10:30pm. Ah, let me go to bed. I am just wasting time. I'll have some choice questions for the farmer guy. But first I'll figure out how to debug web app issues.

4/2/2023

9am.

///

Yeah, I got that far yesterday, but for some reason the deployed application isn't doing anything. I'll have to figure out why that is happening today.

I did manage to push a Blazor app through the IDE yesterday and it works, so that confirmed to me that I do not have to set the server port to 80. For the SAFE Stack project, based on the way the original webpack template was set up, I realized that the Client data needed to be in the `deploy/public` folder, and I've done that. I did verify that it works by running the server locally and connecting to it via the browser.

As for Azure, I have no idea what is going on in the background or how Azure would even know what to run, so I'll have to figure out how to debug that today.

///

9:10am. Replied this to F# the thread I opened yesterday.

https://boards.4channel.org/v/thread/632805486/april-limbus

Wow, the Limbus thread has its own April Fools template.

Nothing There and one of the Bird abnos are dancing on the bottom.

Also, yesterday I figure out that rather than bots posting, most likely the board is trying to trick me into thinking regular users are bots.

9:25am. Let me start instead of just thinking about it.

Where should I start?

https://davecallan.com/uploading-files-to-azure-app-service-directly-azure-portal-without-ftp/

///

Despite its lack of visual feedback you can upload files directly into your Azure App Service via the Azure portal. This can be done via the Kudo Console or in the new App Service Editor (preview).

To open the Kudo Console navigate to YOUR APP SERVICE -> Development Tools -> Advanced Tools or bookmark https://yourappservice.scm.azurewebsites.net/DebugConsole. And then just drag and drop the files you want uploaded onto the relevant folder.

///

///

To open App Service Editor navigate to YOUR APP SERVICE -> Development Tools -> App Service Editor (Preview) or bookmark https://yourappservice.scm.azurewebsites.net/dev. You can upload files by dragging them onto the Explore pane on the LHS.

///

Let me do it with this. Thankfully I haven't erased what I had yesterday.

9:30am. Oh indeed, there is a dev tools tab.

```
   _____
  /  _  \ __________ _________   ____
 /  /_\  \\___   /  |  \_  __ \_/ __ \
/    |    \/    /|  |  /|  | \/\  ___/
\____|__  /_____ \____/ |__|    \___  >
        \/      \/                  \/
A P P   S E R V I C E   O N   L I N U X

Documentation: http://aka.ms/webapp-linux
Dotnet quickstart: https://aka.ms/dotnet-qs
ASP .NETCore Version: 7.0.4
Note: Any data outside '/home' is not persisted
root@9d9e7d55af65:~/site/wwwroot# dir
root@9d9e7d55af65:~/site/wwwroot# cd ..
root@9d9e7d55af65:/# dir
DotNetCoreAgent  bin   defaulthome  diagServer                  etc   lib    media  opt   root  run-diag.sh            sbin  sys  usr
appsvctmp        boot  dev          dotnet_monitor_config.json  home  lib64  mnt    proc  run   run-dotnet-monitor.sh  srv   tmp  var
```

Ok, this is interesting. It put me right into wwwroot and there is nothing there.

```
root@9d9e7d55af65:/# dir
DotNetCoreAgent  bin   defaulthome  diagServer                  etc   lib    media  opt   root  run-diag.sh            sbin  sys  usr
appsvctmp        boot  dev          dotnet_monitor_config.json  home  lib64  mnt    proc  run   run-dotnet-monitor.sh  srv   tmp  var
root@9d9e7d55af65:/# cd wwwroot
-bash: cd: wwwroot: No such file or directory
```

Why did cd .. eject me so much.

./home/site/wwwroot/BlazorApp3.dll

I did a find for dlls and found this. WTF?

```
root@9d9e7d55af65:~/site/wwwroot# dir
BlazorApp3.deps.json  BlazorApp3.dll  BlazorApp3.exe  BlazorApp3.pdb  BlazorApp3.runtimeconfig.json  appsettings.Development.json  appsettings.json  web.config  wwwroot
```

Now there is actually something inside this folder.

9:40am. Ok, nevermind, let me exit this.

Let me go into the advanced dev tools next.

https://mrakgr-blazor-test.scm.azurewebsites.net/wwwroot/

This allows me to view thefile system.

https://mrakgr-blazor-test.scm.azurewebsites.net/wwwroot/BlazorApp3.deps.json

```json
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v7.0",
    "signature": ""
  },
  "compilationOptions": {},
  "targets": {
    ".NETCoreApp,Version=v7.0": {
      "BlazorApp3/1.0.0": {
        "runtime": {
          "BlazorApp3.dll": {}
        }
      }
    }
  },
  "libraries": {
    "BlazorApp3/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    }
  }
}
```

Take a look at this file. This might be what is responsible for telling Azure what to run.

9:45am. Let me erase that resource group. I'll try deploying the CFR project again and taking a look.

```fs
        url "http://localhost:80"
```

Don't need to mess with the server port. Let me remove this.

https://mrakgr-cfr-in-fable.azurewebsites.net/

Huh what the hell, it worked?!

Hot damn, I just ran it and it converged to -0.19. I didn't know it was possible to get it that good!

9:55am. I have no idea why it didn't work for me yesterday. Maybe it simply needed a while to start up?

```fs
        url "http://localhost:80"
```

I don't think it is because of this.

10am. Let me try updating my deployment. I'll try the old port again.

mrakgr-cfr-in-fable.azurewebsites.net

It still works. The app runs. I wonder how it calculates the vCPU hours.

https://portal.azure.com/#@mrakgrgmail.onmicrosoft.com/resource/subscriptions/ed6a3487-d3c7-41c5-9cf6-d4aeef81f20f/resourceGroups/Web-Apps/providers/Microsoft.Web/sites/mrakgr-cfr-in-fable/quotas

Oh in quotas, I can check out how much has been spent.

> index-587ac5c9.js:3 Error handling the message: TestingStartClicked DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

I wonder why the connection reset.

Ahhh, it might be due to the new deployment. I didn't think it would be so laggy!

```
        url "http://localhost:80"
```

10:10am. Let me get rid of this after all.

```
url "http://localhost:80"
```

Let me remove this from the vite template as well.

```
use_gzip
```

I'll also include this in the CFR project.

10:20am. Anyway, I have a grip on it now. It doesn't seem like having open WebSocket connections takes up vCPU time. Running the training does.

```fs
let app =
    application {
        use_router webApp
        app_config Giraffe.useWebSockets
        use_static "public"
        use_gzip
    }
```

Let me do it like this.

10:25am. Now, I could get started with the video, but let me watch some of the tutorials from yesterday.

https://youtu.be/1xLlUlmLgYs
Diagnosing ASP.NET Core Startup Issues in Azure App Service

This was informative. Now I know I have event logs.

https://www.youtube.com/results?search_query=azure+web+app+cli

This...I don't need.

Let me move to making the video. It's just, now that I've changed the project settings, let me try uploading it again.

10:45am. Shit, when I trained it for 50 iterations, I got -0.19 again.

Let me try the URL again. I am still not convinced it is not working.

10:50am. I've lowered the number of iterations to 50, and now it is converging to -0.22. This is unbelievable.

Also the URI of

```fs
url "http://localhost:80"
```

Works as well.

1pm. Only the outro is left.

2:40pm. Done with breakfast and chores. Let me resume.

https://youtu.be/p5_0drz1JCY
How To Deploy A SAFE Stack Application To The Cloud As An Azure Web App

Here is my latest masterpiece.

3:45pm. https://support.google.com/youtube/answer/11221953?hl
Video editing tips

Youtube suggested me this. Edit: It was super tepid.

Let me post the deployment video on the F# sub.

3:55pm. Done.

Now what I will do is study the T3 stack video.

4pm. I am taking a breather right now. Now that I've come this far, I can put this project on my resume.

But it won't be enough to really get me jobs. I need to go even further.

As much as it would be cool to build a popular platform, that would be a long term project. It would be stupid to refuse a 100-150k per year job just because of it.

The main benefits of doing these projects are still web dev experience and using them as resume boosters.

4:05pm. Now, it is time to go forward.

I admit, building a whole clone of Twitter that can scale to millions of users is not something I would have thought possible for a single person, so I am interested in seeing what that guy does.

After I go through that course, my skills as a webdev will be elevated to a whole new level.

4:10pm. https://youtu.be/YkOSUVzOAA4?t=988
T3 Stack Tutorial - FROM 0 TO PROD FOR $0 (Next.js, tRPC, TypeScript, Tailwind, Prisma & More)

Let me take a few days to digest this properly. I won't be going through all of this in a single day.

https://www.youtube.com/@t3dotgg/videos

I really don't feel like diving into a thick course right now. I might as well enjoy my succeses a little and let them sink in.

https://youtu.be/Kte-t1pQQ3I
Getting A Tech Job In 2023

https://youtu.be/Kte-t1pQQ3I?t=50

Oh, he is using Excalidraw as well.

https://youtu.be/Kte-t1pQQ3I?t=334

This guy is really good.

https://youtu.be/Kte-t1pQQ3I?t=465

Maybe there was something to Bran's advice about contributing to OSS.

https://youtu.be/AEQGlSzdQWE
How To Keep Your Tech Job

The previous vid was more interesting, but this one was not bad either.

https://youtu.be/kK-iR6g-V1g
The REAL Cost Of Avoiding AWS

Let me watch this.

https://youtu.be/kK-iR6g-V1g?t=40

Maybe I'll venture outside of Azure rather than just stick to it.

https://youtu.be/kK-iR6g-V1g?t=395
> You can just hit it from an edge function?

What is that?

4:55pm. https://youtu.be/YkOSUVzOAA4?t=988
T3 Stack Tutorial - FROM 0 TO PROD FOR $0 (Next.js, tRPC, TypeScript, Tailwind, Prisma & More)

Let me get back to this. I think I should watch this an hour in. In not sure how to tackle a project such as this.

Actually, let me go from the start. I know I've gone 15m in, but I can't remember anything that he has been talking about. It just went in one ear and out the other.

Maybe I'll watch it all the way through and then figure out where to go from there.

https://youtu.be/YkOSUVzOAA4?t=383
> PlanetScale is the world's most advanced serverless MySQL platform.

https://youtu.be/YkOSUVzOAA4?t=394
> It is important to make sure that the location of your database is the same or as close as possible to where your Vercel functions are being deployed.

Oh, it seems they are built on AWS.

I am going to ask on the F# sub what Azure related technologies I should look into.

https://youtu.be/YkOSUVzOAA4?t=437

Oh, I should not be pushing my env files out. I'll move to that.

https://www.reddit.com/r/fsharp/comments/129oih7/what_azure_related_technologies_should_i_cover_in/

https://youtu.be/YkOSUVzOAA4?t=552

I won't be needing Prisma given that I have EF Core.

https://youtu.be/YkOSUVzOAA4?t=667

I do not need to worry too much about these parts. He is just setting up some services.

https://youtu.be/YkOSUVzOAA4?t=1059

Since it is all on the JS side, is there a reason not to use this?

6:10pm. Done with lunch.

https://youtu.be/YkOSUVzOAA4?t=1101

Do I feel like watching more of this right now?

6:30pm. https://youtu.be/YkOSUVzOAA4?t=1818

Let me close here. I'll have to look at the source in order to really grasp this. Maybe I should try following along. Sure it would mean spending time configuring all these services, but that wouldn't be too bad.

6:35pm. I'll watch this, I'll watch the .NET beginner tutorials, I'll watch more Azure stuff and see where that gets me.

This shouldn't be that difficult of a project. That hard part was in all the services he is recommending. As soon as I know which tech to use, I'll know it well enough myself.

Now let me have some fun."