"10:55am. It is time to get this thing going.
Focus me.

https://stackoverflow.com/questions/19130986/python-equivalent-of-golangs-select-on-channels

I need to import threading and Queue.

11:30am.

```
union msg =
    | Train: u64
    | Stop

inl main () =
    inl d : dict.t _ _ = dict.empty
    inl play_avg, play_cur, train_cur =
        open agent.cfrq
        funsTrain PlayAvgPolicy d, funsTrain PlayCurrentPolicy d, funsTrain TrainCurrentPolicy d
    inl uniform = agent.uniform.funsEnum()
    inl _ =
        open nodes
        open leduc
        inl f (x : player_funs ({card : card; id : u8; pot : i32} * {card : card; id : u8; pot : i32} * option card) () card action r2) = ()
        f play_avg . f play_cur . f train_cur . f uniform
    let run a,b =
        inl init = (log_probm.from 1,nodes.init,nodes.init)
        leduc.game (nodes.nodes_2p (a, b)) init

    inl train () =
        inl _ = run (train_cur,play_cur)
        inl _ = run (play_cur,train_cur)
        run (play_avg, play_avg)

    inl show_buffer () : ra u64 _ = (dict.toArray d : a _ _) |> am.generic.map fun k,v =>
        open leduc
        open nodes
        inl show_card = function
            | King => "[color=ff0000]K[/color]"
            | Queen => "[color=ff0000]Q[/color]"
            | Jack => "[color=ff0000]J[/color]"
        inl show_action = function
            | Fold => "F"
            | Call => "C"
            | Raise => "R"
        inl pstr x = $"'{:.5f}'.format(!x)" : string
        record {
        trace =
            inl trace : ra u64 _ = am.empty
            listm.iterBack ((function Observation: x => show_card x | Action: x => show_action x) >> rm.add trace) k
            rm.join' "" trace
        avg_policy =
            am.generic.map2 (fun k v =>
                inl k,v = show_action k, pstr v in $"f'{!k}: {!v}'" : string
                ) v.actions v.avg_policy
            |> rm.join' "\n"
        regret =
            am.generic.map2 (fun k v =>
                inl k,v = show_action k, pstr v in $"f'{!k}: {!v}'" : string
                ) v.actions v.q
            |> rm.join' "\n"
        }

    !!!!Import("threading")
    !!!!Import("Queue")
    !!!!Import("ui_train")

    inl queue : obj = $"Queue.Queue()"
    let rec waiting i =
        match $"!queue.get()" with
        | Train: i' => training i (i+i')
        | Stop => waiting i
    and let training from nearTo =
        if from < nearTo then
            if $"!queue.empty()" then
                inl x = record {reward = train(); buffer = show_buffer(); from nearTo}
                $"ui_leduc.msg(!x)"
                training (from+1) nearTo
            else
                match $"!queue.get()" with
                | Train: i' => training from (nearTo+i')
                | Stop => waiting nearTo
        else waiting from

    inl start () : obj = waiting 0
    $"threading.Thread(!start).start()"

    inl train i : () = inl x = Train: i in $"!queue.put(!x)"
    inl stop () : () = inl x = Stop in $"!queue.put(!x)"

    $"ui_train.run(!train,!stop)"
```

Python/Spiral interop is a nightmare, but I will hack it somehow.

Let me make the `msg` function on the other end.

```
from random import randint

from kivy.app import App
from kivy.base import runTouchApp
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput import TextInput
import numpy as np
from kivy.properties import StringProperty, BooleanProperty, NumericProperty

class RowFields(BoxLayout):
    trace = StringProperty('')
    avg_policy = StringProperty('')
    regret = StringProperty('')

class Main(BoxLayout):
    def play(self):
        print('playing')

class U64Input(TextInput):
    is_valid = BooleanProperty(True)
    value = NumericProperty(1)
    def on_text(self,ins,text):
        try:
            self.value = int(text)
            self.is_valid = 0 <= self.value <= 18446744073709551615
        except ValueError:
            self.is_valid = False

root = Builder.load_string("""
#:import graph kivy_garden.graph
#:import MeshLinePlot kivy_garden.graph.MeshLinePlot

<U64Input>:
    text: '1'
    multiline: False
    valign: 'center'
    foreground_color: [0,0,0,1] if self.is_valid else [1,0,0,1]

<FieldLabel@Label>:
    font_name: 'RobotoMono-Regular'
    text_size: self.size
    halign: 'left'
    valign: 'center'

<RowFields>:
    FieldLabel:
        size_hint_x: 0.3
        text: root.trace
        markup: True
    FieldLabel:
        size_hint_x: 0.4
        text: root.avg_policy
    FieldLabel:
        size_hint_x: 0.4
        text: root.regret

<Row@RecycleDataViewBehavior+RowFields>:
    canvas.before:
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Rectangle:
            size: self.size
            pos: self.pos

Main:
    buffer_view: rv
    chart: chart
    progress_bar: progress_bar
    canvas:
        Color:
            rgba: 0.0, 0.0, 0.0, 1
        Rectangle:
            size: self.size
            pos: self.pos
    orientation: 'vertical'
    BoxLayout:
        size_hint_y: None
        height: dp(45)
        padding: dp(8)
        spacing: dp(16)
        Label:
            text: 'Num iterations:'
            size_hint_x: None
            size: self.texture_size
        U64Input:
            id: num_iter
        Button:
            text: 'Train'
            disabled: not(num_iter.is_valid)
            on_press: root.train(num_iter.value)
        Button:
            text: 'Stop'
            on_press: root.stop()
        Button:
            text: 'Play'
            on_press: root.play()
    Accordion:
        orientation: 'vertical'
        min_space: dp(30)
        AccordionItem:
            min_space: self.parent.min_space
            title: 'Dictionary'
            collapse: False
            BoxLayout:
                orientation: 'vertical'
                Label:
                    canvas.before:
                        Color:
                            rgba: 0.6, 0.6, 0.6, 1
                        Rectangle:
                            size: self.size
                            pos: self.pos
                    size_hint_y: None
                    height: dp(30)
                    text: "Count: " + str(len(rv.data))
                RowFields:
                    canvas.before:
                        Color:
                            rgba: 0.7, 0.7, 0.7, 1
                        Rectangle:
                            size: self.size
                            pos: self.pos
                    size_hint_y: None
                    height: dp(40)
                    trace: 'Trace'
                    avg_policy: 'Average Policy'
                    regret: 'Regret'
                RecycleView:
                    id: rv
                    scroll_type: ['bars', 'content']
                    scroll_wheel_distance: dp(114)
                    bar_width: dp(10)
                    viewclass: 'Row'
                    RecycleBoxLayout:
                        default_size_hint: 1, None
                        default_size: None, dp(80)
                        size_hint_y: None
                        height: self.minimum_height
                        orientation: 'vertical'
                        spacing: dp(2)
        AccordionItem:
            min_space: self.parent.min_space
            title: "Chart"
            Graph:
                id: chart
                meshline: MeshLinePlot(color=[1,0,0,1])
                xlabel:'X'
                ylabel:'Y'
                x_ticks_minor:5
                x_ticks_major:5
                y_ticks_major:1
                y_grid_label:True
                x_grid_label:True
                padding:5
                x_grid:True
                y_grid:True
                xmin:0
                xmax:5
                ymin:-15
                ymax:15
    ProgressBar:
        id: progress_bar
        max: 10
        value: 5
        size_hint_y: None
        height: dp(20)
""")

def msg(x):
    chart = root.chart
    root.progress_bar.value = x['value']
    root.progress_bar.max = x['nearTo']
    reward = x['reward']
    root.buffer_view.data = x['buffer']
    m = chart.meshline
    chart.add_plot(m)
    m.points.extend([(len(m.points),reward)])
    chart.xmax = max(1,len(m.points))

def run(train,stop):
    root.train = train
    root.stop = stop
    runTouchApp(root)

if __name__ == '__main__':
    runTouchApp(root)
```

Here it is. Let me try running this. Focus me. If there are errors, I need to run through them. Trying to reason them out is a waste of time.

11:45am. I really need some kind of progress bar in the plugin itself to tell me when it is safe to compile on the Python side. Right now I have no idea how long the actual compilation takes on the Spiral side.

```py
import threading
import Queue
```

Huh, it is telling me that Queue is not found.

```py
import threading
import queue

x = queue.Queue()
```

So it is like this. The SO code is outdated in places. Ok.

```
 Traceback (most recent call last):
   File "C:\Users\Marko\anaconda3\lib\threading.py", line 784, in __init__
     assert group is None, "group argument must be None for now"
 AssertionError: group argument must be None for now
 Exception ignored in: 'ui_train_test.main'
 Traceback (most recent call last):
   File "C:\Users\Marko\anaconda3\lib\threading.py", line 784, in __init__
     assert group is None, "group argument must be None for now"
 AssertionError: group argument must be None for now
```

Agh, what the hell?

```
 Traceback (most recent call last):
   File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_leduc5/ui_train_test_run.py",
line 5, in <module>
     print(main())
   File "ui_train_test.pyx", line 4268, in ui_train_test.main
     cpdef void main() except *:
   File "ui_train_test.pyx", line 4291, in ui_train_test.main
     threading.Thread(v7).start()
   File "C:\Users\Marko\anaconda3\lib\threading.py", line 784, in __init__
     assert group is None, "group argument must be None for now"
 AssertionError: group argument must be None for now
```

Hmmm...

```
$"threading.Thread(target=!start).start()"
```

Let me try it like this.

11:55am. It is a complete failure. I managed to get it to run just now, but doing the computations on a different thread still freezes the UI!

Damn.

I'll have to go for a multiprocessing solution. Hmmm, maybe...

12pm. Seriously, what did I spend the entire day yesterday thinking for?

```
    !!!!Import("multiprocessing")
    !!!!Import("ui_train")

    inl queue : obj = $"multiprocessing.Queue()"
```

Let me try it like this.

```
 RuntimeError:
         An attempt has been made to start a new process before the
         current process has finished its bootstrapping phase.

         This probably means that you are not using fork to start your
         child processes and you have forgotten to use the proper idiom
         in the main module:

             if __name__ == '__main__':
                 freeze_support()
                 ...
```

What is this?

I am doing this wrong. Let me go to that video yesterday and see how he deals with multiprocessing.

https://www.youtube.com/watch?v=fKl2JW_qrso
Python Multiprocessing Tutorial: Run Code in Parallel Using the Multiprocessing Module

Let me study this.

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support

No that video is useless. Let me just add this.

```
cpdef void main() except *:
    cdef unsigned long long v0
    cdef unsigned long long v1
    cdef Mut0 v2
    cdef object v3
    cdef object v4
    cdef object v5
    cdef object v6
    cdef object v7
    cdef object v8
    cdef object v9
    v0 = 3
    v1 = 7
    v2 = method0(v0, v1)
    v3 = Closure0(v2)
    v4 = Closure1(v2)
    v5 = Closure2(v2)
    pass # import multiprocessing
    multiprocessing.freeze_support()
```

Hmmm, am I doing this wrong? If not here, then where am I supposed to put this?

```
import numpy as np
import pyximport
pyximport.install(language_level=3,setup_args={"include_dirs":np.get_include()})
from ui_train_test import main
import multiprocessing
multiprocessing.freeze_support()
print(main())
```

Not here either.

What should I do now?

12:25pm. This is not working. Let me make a simplified example and I'll post a question on the Cython repo.

```
import multiprocessing
def f(): print("ok")

cpdef void main() except *:
    multiprocessing.freeze_support()
    multiprocessing.Process(target=f).start()
    print("done")
```

This fails for me.

12:40pm. I decided to ask on the Cython issues page.

https://github.com/cython/cython/issues/

This issue 4116 here.

12:45pm. This is such a dissapointment. But maybe it is an opportunity as well.

12:50pm. Let me think. It is strange that the threading solution does not work. Do the threads not switch in a Robin fashion?

I guess they don't, instead that is only done during blocks.

1pm. But multiprocessing really has a lot of disadvantages even if I could get it to work. These tabular players are one thing, but how am I going to share player data and integrate with the game itself?

1:15pm. Got a reply from Groq yesterday wanting to set up a video conference interview. Wow, I am amazed at how slow they are. How many weeks ago did I send an email to them? And a video interview. Get lost.

1:20pm. I am at a loss here, I have no idea how to deal with this situation. Threading failed and multiprocessing is at an impasse.

There is not much I can do until I get a reply and get multiprocessing to work.

...Why does data have to be pickled anyway? GIL is one thing, but wouldn't it be possible to have multiple intepreter instances in one process? Forget that. I am not going to get anywhere with this line of thinking.

///

1) Free up the UI loop while training is being done in the background. Right now the chart is not even updating while the training is going on.

2) Integrate this with the game and play against the CFR agent.

3) Optimize the whole program. Right now the training is way to slow. It will take forever once I move on to flop poker.

///

Ok, forget about the first goal. I am putting in effort, but it a huge can of worms.

I'll focus on 2 and 3 next.

1:30pm. Reverted the previous version. Let me have breakfast here."