"2pm. Done with breakfast and chores, but I was so busy yesterday I did not even do my morning reading. Let me just fire that bank email and I'll take a proper break.
2:15pm. Time for a break.

3:15pm. Time to resume.

Focus me.

```
(base) PS C:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin> cythonize
Usage: cythonize [options] [sources and packages]+

cythonize: error: no source files provided
```

I saw this in an Nvidia article yesterday.

https://developer.nvidia.com/blog/accelerating-python-on-gpus-with-nvc-and-cython/

`cythonize -i cppsort.pyx`

Instead of doing that `setup.py` I could have just used this.

```
cdef int range(int fron, int nearTo):
    cdef int loop(int s, int i):
        if i < nearTo: return loop(s+i,i+1)
        else: return s
    loop(0,fron)

range(0,100000)
```

It is telling me that the nested function is not allowed there.

```
(base) PS C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\test2> python tail_rec.cp38-win_amd64.pyd
  File "tail_rec.cp38-win_amd64.pyd", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file tail_rec.cp38-win_amd64.pyd on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

How annoying.

3:35pm.

```fs
cdef int loop(int s, int i, int nearTo):
    if i < nearTo: return loop(s+i,i+1,nearTo)
    else: return s
cpdef int sequence(int fron, int nearTo):
    return loop(0,fron,nearTo)
```

Yes, this does get TCO'd.

```fs
cdef int loop(int s, int i, int nearTo):
    if i < nearTo: return loop(s+i,i+1,nearTo)
    else: return s
cpdef int sequence_tailrec(int fron, int nearTo):
    return loop(0,fron,nearTo)

cdef int loop(int i, int nearTo):
    if i < nearTo: return i + loop(i+1,nearTo)
    else: return s
cpdef int sequence(int fron, int nearTo):
    return loop(0,fron,nearTo)
```

Let me try this. Though for all I know the C compiler might be good enough to transform this as well.

Yeah, it is.

What if I just do a def?

Actually, no I fucked up the above.

```
cdef int loop(int i, int nearTo):
    if i < nearTo: return i + loop(i+1,nearTo)
    else: return 0
```

Let me do it like this.

```
import tail_rec
print(tail_rec.sequence(0,2_000_000_000))
```

Ah, wait, nothing is getting printed when I do this.

```
print(tail_rec.sequence(0,2_000_0))
```

If I add another zero to the end, it stack overflows silently in the background.

```
import tail_rec
print(tail_rec.sequence_tailrec(0,2_000_000_000))
```

The tail recursive version works just fine. Ok.

Let me do that automatic Cython import. It was in the docs.

> Use Pyximport, importing Cython .pyx files as if they were .py files (using setuptools to compile and build in the background). This method is easier than writing a setup.py, but is not very flexible. So you’ll need to write a setup.py if, for example, you need certain compilations options.

3:50pm.

```
import pyximport
pyximport.install()
import tail_rec
print(tail_rec.sequence_tailrec(0,2_000_000_000))
```

This works, but it does not produce a residual that I could use. Because of that, `import tail_rec` is an import error in the editor.

Ok...

What happens if I try passing a string into the Cython function that expects an int?

```
(base) PS C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cython_experiments\test2> python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    print(tail_rec.sequence_tailrec(0,"2_000_000_000"))
  File "tail_rec.pyx", line 4, in tail_rec.sequence_tailrec
    cpdef int sequence_tailrec(int fron, int nearTo):
TypeError: an integer is required
```

Not bad. Ok.

```
import pyximport
pyximport.install(language_level=3)
import tailrec
# print(tail_rec.sequence(0,2_000_000_000)) # Diverges
print(tailrec.sequence_tailrec(0,2_000_000_000))
```

Figured out how to set the language level as well.

Ok...

4:05pm. I am thinking.

At this point there is nothing really stoping me from starting work on the backend. If I start now, it won't take long at all.

Yes...

Before I start let me just figure out what the type of python objects is.

https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html

Also before I start making a compiler backend, I should at least study the basics of the language I am targetting.

https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#c-variable-and-type-definitions

Oh, it has C unions!

This will make it a lot easier to implement union types.

>  Arrays use the normal C array syntax, e.g. int[10], and the size must be known at compile time for stack allocated arrays. Cython doesn’t support variable length arrays from C99.

Interesting. I wonder why this is so?

But I won't by using C arrays, but Python ones instead as the default.

> declares a parameter called int which is a Python object. You can also use object as the explicit return type of a function, e.g.:

Ah, I see.

```
cpdef object test_obj((object,object) x):
    a,b = x
    return a + b

cpdef object qwe(object a, object b):
    cdef (object, object) x = a,b
    return test_obj(x)
```

> tuple_test.pyx:6:9: Tuple types can't (yet) contain Python objects.

Ah crap.

4:45pm. Let me not give up here. What about structs?

4:50pm.

```
cdef struct QWE:
    object a
    object b
```

This is so useless of it.

4:55pm. Let me not get too pessimistic here. I'll try installing the prerelease and seeing how that goes.

https://pypi.org/project/Cython/#history

How do I install the prerelease using conda?

https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-packages

It is not on the conda package list. What do I do here?

https://pypi.org/search/?q=cython

I don't think it is possible to install the prerelease through pip either.

5:30pm. https://github.com/cython/cython/issues/

Opened issue 3985 here requesting to support Python objects in cdef structs, unions and tuples.

5:35pm. This was actually quite a shock to me. It wrecked my compilation plan. This is definitely a point in favor of doing a direct C/Python backend.

5:40pm. The thing I had in mind would have been extremely performant, but I'll have to lower my expectations here.

Ah, forget it. I'll give it an extra week. I need to study the way Python works before I make a decision.

6:10pm.

https://cython.readthedocs.io/en/latest/src/tutorial/cdef_classes.html

Let me try out if structs work in `cdef classes`.

```
cdef class Qwe:
    cdef object x
    def __init__(self, q):
        self.x = q

cpdef object test_obj(object x):
    q,w = x
    return q+w

cpdef object qwe(object a, object b):
    x = a,b
    cdef Qwe z = Qwe(x)
    return z #test_obj(x)
```

Oh, it does work in cdef classes.

6:20pm. No this is not what I need. Obviously I won't start work on the backend today. Let me take a look at embedding Python section of its documentation.

I think I am going to put in some overtime today. I really need more time in the day. Today I literally only started at 3pm for some reason. It is all the winter's fault making me stay in bed until the fire gets started.

https://docs.python.org/3/extending/embedding.html

6:20pm.

```cpp
#define PY_SSIZE_T_CLEAN
#include <Python.h>

int
main(int argc, char *argv[])
{
    wchar_t *program = Py_DecodeLocale(argv[0], NULL);
    if (program == NULL) {
        fprintf(stderr, "Fatal error: cannot decode argv[0]\n");
        exit(1);
    }
    Py_SetProgramName(program);  /* optional but recommended */
    Py_Initialize();
    PyRun_SimpleString("from time import time,ctime\n"
                       "print('Today is', ctime(time()))\n");
    if (Py_FinalizeEx() < 0) {
        exit(120);
    }
    PyMem_RawFree(program);
    return 0;
}
```

I can't tell at all how much of these are macros and how much are actual function calls. If these are not macros, then is the Python interpreter state global? That is shit. I guess I now know why the GIL is necessary. I was expecting the interpreter to be passed as a pointer, but it is nowhere to be found.

https://docs.python.org/3/extending/index.html

Let me go through this all in turn. I need to focus on this. It is not a given that I am going to use Cython. I want the best possible option.

...If I am just doing the Python backend in C, assuming I can accept it being global, then I can see how it would make things easier.

7:15pm. https://docs.python.org/3/c-api/refcounting.html#c.Py_DECREF

Having to do reference counting manually in a direct backend would be pain itself.

8:05pm. Let me stop here for the day.

I've decided. Despite the recent blow, I can't deal with reference counting. Neither can I deal calling Python library functions manually. This C style code is absolutely attrocious. Even if I could deal with ref counting, I cannot possibly subject the user to this.

If something like Cython did not exist, I'd compile to straight Python instead. I should be glad that I at least have it.

8:20pm. Got a reply. I do not understand why structs and tuples would get treated differently. Nevermind that for now.

Let me close here. I need to unwind.

Tomorrow I will start work on the Cython backend. It won't be hard. I've preped my mind for the task, and I just need to execute it. In fact, Cython not having some of the vital stuff that I'd need for Spiral's compilation will actually make implementing those features easier. I am thinking of unions here. Both the recursive and the non-recursive unions would need to be heap allocated in Cython. I have no choice, but to do this here.

I am guessing that tuples will land in Cython at some point, until then I'll just compile the compound types containing objects to objects. I'll deal with it that way.

It won't be hard.

8:30pm. I am going to make a dent in that backend tomorrow. I'll have something to show for it next month."