"10:35am. Right now I might be dead tired, but with such intense emotions still driving me, there is no way I would spend my morning consuming fiction or doing arbitrary things. I am not sure whether I will be effective, but today is the day I want to sink into programming most of all. If nothing else, I will just sit in this chair thinking of nothing but the code.
Today I want nothing else. I want to become better at programming. Even the Singularity is a distraction for this.

10:45am. Even though it might seem like a waste of time, I want to dedicate myself to small goals.

```ts
const errorsServer = (uriServer : string, errors : DiagnosticCollection, tok : CancellationToken) => {
    const sock = new zmq.Reply()
    sock.bind(uriServer)
    const stop = new Promise(tok.onCancellationRequested)
    const process = async () => {
        const [x] = await sock.receive()
        const msg : [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
        errorsSet(errors,Uri.parse(msg[0]),msg[1])
        sock.send(null)
    }
    while (!tok.isCancellationRequested) { Promise.race([stop,process()]) }
    sock.unbind(uriServer)
}
```

Yesterday I did this, and I want to test it now.

I do not really like this. Is there really a point to this stopping code?

Yeah, it would work, but there isn't a time the extension would be disabled that would warrant this. The only way to disable the extension would be to close the editor. In that case, would stop even get triggered here?

10:50am. Yeah, I have this urge to do proper clean up which is why I've written it like the above. But similarly to avoiding the use of timeouts in the server, I can't see a way to connect this urge to anything tangible here. There is no benefit and...

```ts
const errorsServer = async (uriServer : string, errors : DiagnosticCollection) => {
    const sock = new zmq.Reply()
    sock.bind(uriServer)
    while (true) {
        const [x] = await sock.receive()
        const msg : [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
        errorsSet(errors,Uri.parse(msg[0]),msg[1])
        sock.send(null)
        }
}
```

...the version of the function that does no disposal is much cleaner.

Maybe it would be worth making the sockets global since that is the case. Or rather than that race, it might be good to try out the timeout.

Well, regardless, I know that I am disposing of all the other things, but I am going to break form with this for the sake of clarity. If it turns out that disposal is needed, I will just go back to the racing version.

```ts
    const cancellationSource = new CancellationTokenSource()
    errorsServer(uriParserErrors,errorsParse,cancellationSource.token)
```

Let me change this to what it was before.

11am.

```ts
import * as zmq from "zeromq"
```

If anything, I feel like the plugin should have its own zmq context which I would then pass to dispose.

11:10am. There are just too many issues with ZeroMQ's design. Like for example, it might get stuck on sending a message back if the other side is not there. Should I do a race there as well.

No I can't have the races everywhere.

Even though my current design breaks plugin disposal, I'll go along with it and only really change it if it turns out that it causes problems.

I've been thinking for a long time - while ZeroMQ is useful, if I were the one designing it and doing the implementation in Spiral, I could have done a lot better job. Suppose I had the goal of doing this, extending the Spiral language so that compiling C style libraries is possible would be a great undertaking.

11:15am. ZeroMQ is culmination of Hintjens' life experience as programmer, so I am not going to spend a few years trying to exceed him.

```ts
// Note: Should this have disposal code related to it? Check out the first 8/21/2020 commit for a disposing version.
// The use of this breaks plugin disposal, but I'll only change this to an uglier version if it turns out to be necessary.
const errorsServer = async (uriServer : string, errors : DiagnosticCollection) => {
```

Let this note just stand here.

11:20am.

```ts
{ pattern: '**/*.{spi,spir}'},
```

Oh yes, could...

```ts
{ pattern: '**.{spi,spir}'},
```

...this work? Let me give it a try.

```
Spiral plugin is active.
index.js:53
rejected promise not handled within 1 second: Error: Socket is blocked by a bind or unbind operation
extensionHostProcess.js:1007
stack trace: Error: Socket is blocked by a bind or unbind operation
 at errorsServer (c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\out\index.js:46:32)
 at exports.activate (c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\out\index.js:56:5)
 at Function._callActivateOptional (c:\Users\Marko\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:877:509)
```

I am having this problem now. Before I deal with this, let me try the pattern thing.

...No the pattern does not work.

Let me try removing the timeout on the socket. Alternatively, I could change to the router one.

```fs
const errorsServer = async (uriServer : string, errors : DiagnosticCollection) => {
    const sock = new zmq.Reply()
    sock.receiveTimeout = -1
```

Let me go with this.

```ts
const uriParserErrors = `tcp://*:${port}/parser_errors`
```

Also let me replace the `localhost` with `*`. I remember having issues with this sort of thing.

Mhhh, no it is behaving strangely. Is it the case that I cannot bind to `/parser_errors`?

```fs
sock.bind(uriServer)
```

Ah wait. This shit needs an await.

```ts
const errorsServer = async (uriServer : string, errors : DiagnosticCollection) => {
    const sock = new zmq.Reply()
    sock.receiveTimeout = -1
    await sock.bind(uriServer)
    while (true) {
        const [x] = await sock.receive()
        const msg : [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
        errorsSet(errors,Uri.parse(msg[0]),msg[1])
        sock.send(null)
        }
}
```

```
Spiral plugin is active.
index.js:54
rejected promise not handled within 1 second: TypeError: x.forEach is not a function
extensionHostProcess.js:1007
stack trace: TypeError: x.forEach is not a function
 at errorsSet (c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\out\index.js:30:7)
 at errorsServer (c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\out\index.js:49:9)
```

It is shit like this why don't like ZeroMQ's design. What is going on here?

```ts
const uriParserErrors = `tcp://*:${port+1}`
```

The error goes away when I do it on a different port like this.

Ah, maybe...

```ts
const uri = `tcp://localhost:${port}/lang_server`
const uriParserErrors = `tcp://*:${port}/client_errors`
```

What if I did this?

```
Spiral plugin is active.
index.js:54
rejected promise not handled within 1 second: Error: Invalid argument
extensionHostProcess.js:1007
stack trace: Error: Invalid argument
```

What a wreck.

```ts
const uri = `tcp://localhost:${port}`
const uriParserErrors = `tcp://*:${port+1}`
```

It seems I have no choice but to do this then.

11:40am. This changes things a bit.

I do not want to have too many ports.

I am going to have to use timeouts. I'll set something like 2s for both send and receive and use flag variable in the loop.

```fs
// sock.receiveTimeout = -1
```

First, do I get an error without the timeout?

```ts
const errorsServer = async (uriServer : string, errors : DiagnosticCollection) => {
    const sock = new zmq.Reply()
    sock.receiveTimeout = 2000
    sock.sendTimeout = 2000
    await sock.bind(uriServer)
    while (true) {
        const [x] = await sock.receive()
        const msg : [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
        errorsSet(errors,Uri.parse(msg[0]),msg[1])
        sock.send(null)
        }
}
```

Let me do this.

Now, how exactly do I catch those failed to receive messages?

https://basarat.gitbook.io/typescript/type-system/exceptions

I am not that familiar with TS exceptions, so let me take a look at this.

11:50am.

```ts
// Note: Should this have disposal code related to it? Check out the first 8/21/2020 commit for a disposing version.
// The use of this breaks plugin disposal, but I'll only change this to an uglier version if it turns out to be necessary.
const errorsServer = async (uriServer: string, errors: DiagnosticCollection) => {
    const sock = new zmq.Reply()
    sock.receiveTimeout = 2000
    sock.sendTimeout = 2000
    await sock.bind(uriServer)
    while (true) {
        try {
            const [x] = await sock.receive()
            const msg: [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
            errorsSet(errors, Uri.parse(msg[0]), msg[1])
            sock.send(null)
        } catch (e) {
            if (e.errno === 11) { } // If the error is a timeout just repeat.
            else { throw e }
        }
    }
}
```

Let me also bring back the cancellation token.

11:55am.

```ts
const errorsServer = async (uriServer: string, errors: DiagnosticCollection, tok : CancellationToken) => {
    const sock = new zmq.Reply()
    sock.receiveTimeout = 2000
    sock.sendTimeout = 2000
    await sock.bind(uriServer)
    try {
        while (!tok) {
            try {
                const [x] = await sock.receive()
                const msg: [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
                errorsSet(errors, Uri.parse(msg[0]), msg[1])
                sock.send(null)
            } catch (e) {
                if (e.errno === 11) { } // If the error is a timeout just repeat.
                else { throw e }
            }
        }
    } finally {
        sock.unbind(uriServer)
    }
}
```

Now, I think I will fold this into the main plugin function.

12:05pm.

```ts
export const activate = async (ctx: ExtensionContext) => {
    console.log("Spiral plugin is active.")

    const errorsTokenization = languages.createDiagnosticCollection()
    const errorsParse = languages.createDiagnosticCollection()
    const errorsType = languages.createDiagnosticCollection()
    let isProcessing = true;
    (async () => {
        const sock = new zmq.Reply()
        sock.receiveTimeout = 2000
        sock.sendTimeout = 2000
        await sock.bind(uriClient)
        try {
            while (isProcessing) {
                try {
                    const [x] = await sock.receive()
                    const msg: [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
                    errorsSet(errorsParse, Uri.parse(msg[0]), msg[1])
                    sock.send(null)
                } catch (e) {
                    if (e.errno === 11) { } // If the error is a timeout just repeat.
                    else { throw e }
                }
            }
        } finally {
            sock.unbind(uriServer)
        }
    })();
```

I've decided to inline this. For now I'll only handle parser errors in this, but later I will use a generic type for both parse and type errors.

In particular, for partial evaluation errors, I willneed something special.

```ts
const msg: [string, [string, RangeRec | null][]] = JSON.parse(x.toString())
```

This null thing here, let me streamline this. The only reason why I ever have nulls is because the config parser can sometimes fail without a position.

The regular tokenizer and the parser always have positions.

```fs
enum ClientMessageTag {
    ParserError,
    TypeError
}
```

Let me start with this.

```ts
enum ClientMessageTag {
    ParserError,
    TypeError
}
type ClientMessage =
    {tag: ClientMessageTag.ParserError, uri: string, errors: [string, RangeRec][]}
```

Let me do this for now. I'll leave out the `TypeError` case.

12:15pm.

```ts
                    const msg: ClientMessage = JSON.parse(x.toString())
                    errorsSet(errorsParse, Uri.parse(msg.uri), msg.errors)
```

Yeah, this is much better now.

```ts
    (async () => {
        const sock = new zmq.Reply()
        sock.receiveTimeout = 2000
        sock.sendTimeout = 2000
        await sock.bind(uriClient)
        try {
            while (isProcessing) {
                try {
                    const [x] = await sock.receive()
                    const msg: ClientMessage = JSON.parse(x.toString())
                    errorsSet(errorsParse, Uri.parse(msg.uri), msg.errors)
                    sock.send(null)
                } catch (e) {
                    if (e.errno === 11) { } // If the error is a timeout just repeat.
                    else { throw e }
                }
            }
        } finally {
            await sock.unbind(uriServer)
        }
    })();
```

Forgot the `await` in front of `unbind`. It really goes to show how useful F#'s non-unit return warning really is.

I've made the mistake of ignoring the return a few times now today.

Well, since `unbind` is in the very last position and nothing happens after that, I doubt this would be a big deal.

12:20pm. What is next, well besides breakfast?

I am really glad how the morning session went. Despite being so tired, I feel like today's morning session would not compare shamefully to any of the other ones. If I can keep going like this, I can reach my ideal.

Basically, what I've done today is merely moving things around, but these sorts of exercises are important.

12:30pm. Yeah, mastering unification and doing typechecking was a grand challenge, but this thing here is not a piece of cake by any means.

Right now I am thinking about the hover provider again. And I am realizing that if I use the same port as for the other messages, it might block the edits.

I guess I'll use a short timeout of 0.1s for the hover.

I did not talk about this, but I've figured out how to batch multiple edits now on the VS Code side. I'll have to implement it at some point, but it is not really important...

12:35pm. Yeah, I am not going to use a different socket just for hovers.

...No actually I might. I should use the client uri for hover results. If I did that I would not even need the timeout.

When it comes to sending the errors to the client, I am going to in fact have to use that thread safe queue.

Also, I've completely forgotten how `Fsharp.JSON` packs union types.

...

Yes, I need to do this slowly. If I try to do it quickly - if I try hurry things along by looking down on the task in front of me and set a short term time limit to get it done as a result, I am definitely going to regret it. Every little pebble needs its place.

I am going to get rid of my gambler's mentality completely and approach life as a craftsman. I need to accept that I am weak, and play the game more tactfully - with the realiziation that some battles need to be run from."