"2:30pm. Let me read the latest chap of Overlord and I will resume.
2:50pm. It is this late? I really need to start even though I'd rather slack more.

2:55pm. Focus me, focus. Let me try out the ReasonML bindings generator.

https://github.com/rrdelaney/ReasonablyTyped

```
e:\Webdev\Typescript\vscode-extension-samples\helloworld-sample\node_modules\@types\vscode>retyped index.d.ts
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module './js/src/compiler'
Require stack:
- C:\Users\Marko\AppData\Roaming\npm\node_modules\reasonably-typed\lib\index.js
- C:\Users\Marko\AppData\Roaming\npm\node_modules\reasonably-typed\lib\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Marko\AppData\Roaming\npm\node_modules\reasonably-typed\lib\index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Marko\\AppData\\Roaming\\npm\\node_modules\\reasonably-typed\\lib\\index.js',
    'C:\\Users\\Marko\\AppData\\Roaming\\npm\\node_modules\\reasonably-typed\\lib\\cli.js'
  ]
}
```

Sigh, what do I do here?

https://github.com/rrdelaney/ReasonablyTyped/issues/

It is issue 62 on here. This stuff is super alpha quality. It should not have even been published to NPM.

3:05pm. https://reasonml.github.io/docs/en/null-undefined-option#interoperate-with-javascript-undefined-and-null

Oh, ReasonML does the sensible thing and compiles option to `undefined`.

https://itnext.io/reasonml-create-bindings-for-npm-package-b8a3c6d0703e

https://reasonml.github.io/docs/en/null-undefined-option#solution-more-sophisticated-undefined-null-interop

3:15pm. https://bucklescript.github.io/bucklescript/api/Js.Nullable.html

What about just `null`?

https://reasonml.org/apis/javascript/latest/js/null

Ah, it is just called `Js.null` as opposed to `Js.null_undefined`.

https://stackoverflow.com/questions/48331251/does-reason-support-nullable-types

3:25pm. Ok, I am doing my initial scan to make sure that I do not fall into the same pit again.

3:30pm. Let me gather my will and I will just do it. I am really so pissed. If only they have compiled the option type to undefined - this could be a minor compiler change, then things would have been so much easier for me.

3:35pm. At this point I think I have been playing with Fable for a week already though it seems less since I haven't been working on the example for more than a few days. Setting up the project and the initial study period seems to have taken just that much time. I honestly though it was less.

3:40pm. I need to start. Even though it is painful, I need to start this.

Let me open a new `ReasonML` project. I need to go at it all from the start.

...Well, let me take it easy. I need to gather my motivation to do it once again. It is not that easy. Let me do it step by step. I need to rebuild my skills.

```
bsb -init call-hierarchy-sample -theme basic-reason
```

Let me start with this.

3:40pm. https://reasonml.github.io/docs/en/interop

Just like I did for Fable, I am going to have to spend some time immersed in this.

4pm. By immersed, I did not mean surfing /a/ on the side. Right now I am debating whether I am overreacting here. But no, I think it was intentional that Fable's `option` acts like `Nullable`. This is truly JS-tier of language design.

They fucked up all the most important things whether it be interop or arrays.

In Spiral, the only thing I gambled on design wise and fucked up is making 64-bit ints the default. Thankfully once I get nominal prototypes the need for defaults will go away.

4:05pm. I need to gather my courage and go with what I believe in.

https://egghead.io/lessons/reason-async-await-in-reasonml

Oh, yes, I should really learn how to use async/await in ReasonML even if it means using a compiler extension.

This is another thing Fable got wrong - not using native Promises.

Interop nightmare list:
1) Options
2) Arrays
3) Promises

Tooling issues:
4) Setting up a project takes too long. Seeing clean output via fable splitter takes 10m
5) Editor support is less responsive than BuckleScript/ReasonML - and F# on VS. Fable is notably more laggy than Typescript.

4:10pm. https://github.com/reasonml-labs/bs-let

Let me watch this video.

4:15pm. `JS.WeakMap`

It seems that Fable has weak maps and sets in its library, but nothing for null and undefined.

`JsInterop.isNullOrUndefined`

Nothing for specifically testing for `undefined`. The library seems to want to pretend that they are the same thing. Yeah, I am not overreacting. Well, I'll know once I see the reaction of the authors.

Let me watch the bs-let video.

4:30pm. This is great. It is super cool that this is not some `async`, but supports general monadic binding. The fact that `Promise` does not have bind in Fable really hampered me.

4:35pm. Ok, that is one worry down. With ReasonML I will do it properly.

https://reasonml.github.io/docs/en/interop

Focus me, focus, on JS interop.

```
"C:\Users\Marko\AppData\Roaming\npm\node_modules\bs-platform\win32\bsc.exe"  -warn-error +101
-color always -ppx "E:\Webdev\ReasonML\call-hierarchy-sample\node_modules\bs-let\ppx"  -o src\Demo.reast -bs-syntax-only -bs-binary-ast E:\Webdev\ReasonML\call-hierarchy-sample\src\Demo.re'E:\Webdev\ReasonML\call-hierarchy-sample\node_modules\bs-let\ppx' is not recognized as an internal or external command,
operable program or batch file.
```

What is going on here?

Actually the extension is not working for me.

"A Note about Windows Currently this project only precomiles binaries for linux and OS X according to the needs of existing maintainers. If you're a Windows user and would like to use this PPX, We'd love a pull-request that moves the project from Travis to Azure Pipelines and builds for all three platforms."

Whops.

4:55pm. Well, it does not matter that much. I'll bear with it.

```
// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {
 // Use the console to output diagnostic information (console.log) and errors (console.error)
 // This line of code will only be executed once when your extension is activated
 console.log('Congratulations, your extension "call-hierarchy-sample" is now active!');

 let disposable = vscode.languages.registerCallHierarchyProvider('plaintext', new FoodPyramidHierarchyProvider());

 context.subscriptions.push(disposable);

 showSampleText(context);
}
```

Let me start from the top. Not only will I have to start from the top, but I will have to get familiar with the libraries as well.

5pm. https://bucklescript.github.io/docs/en/new-project

Ah, let me try this out. I'd much rather have Ocaml's syntax.

```
let () = Js.log "Hello, BuckleScript"

let y = 3;
```

I had no idea the editor supported Ocaml's syntax. This is great.

I am going to have to go through the docs to familiarize myself with it though.

5:10pm. https://bucklescript.github.io/docs/en/interop-overview

It seems there is not much on the BS site on the actual language. Rather the whole documentation is on interop.

"Major data structures in BuckleScript map over cleanly to JS. For example, a BS string is a JS string. A BS array is a JS array. The following BS code:"

Yeah, this is what I wanted with Fable.

5:20pm.

```
let f x y =
  [%debugger];
  x + y
```

This is cool.

5:35pm. https://bucklescript.github.io/bucklescript/api/

6pm. https://bucklescript.github.io/docs/en/object#records-as-objects

It seems there are chunks of code missing in the documentation. Ah, it is just with Ocaml syntax - the Reason versions are there.

6:25pm. Done with lunch. Let me finish what I am reading right now, and I will call it a day. It will take me a while until I ramp up to speed with Bucklescript.

I could have saved myself a whole week had I decided to skip Fable, but my intuition failed me. I could not imagine that JS interop would be this broken at such a fundamental level.

6:40pm. https://bucklescript.github.io/docs/en/object-2

Let me stop here."