"2:15pm. Done with breakfast. Let me resume.
2:20pm.

```py
    #
    # reshape q, k, v for multihead attention and make em batch first
    #
    q = q.contiguous().view(tgt_len, bsz * num_heads, head_dim).transpose(0, 1)
    if static_k is None:
        k = k.contiguous().view(-1, bsz * num_heads, head_dim).transpose(0, 1)
    else:
        # TODO finish disentangling control flow so we don't do in-projections when statics are passed
        assert static_k.size(0) == bsz * num_heads, \
            f"expecting static_k.size(0) of {bsz * num_heads}, but got {static_k.size(0)}"
        assert static_k.size(2) == head_dim, \
            f"expecting static_k.size(2) of {head_dim}, but got {static_k.size(2)}"
        k = static_k
    if static_v is None:
        v = v.contiguous().view(-1, bsz * num_heads, head_dim).transpose(0, 1)
    else:
        # TODO finish disentangling control flow so we don't do in-projections when statics are passed
        assert static_v.size(0) == bsz * num_heads, \
            f"expecting static_v.size(0) of {bsz * num_heads}, but got {static_v.size(0)}"
        assert static_v.size(2) == head_dim, \
            f"expecting static_v.size(2) of {head_dim}, but got {static_v.size(2)}"
        v = static_v
```

The comments are right about the statics. The way it is implemented currently is spew. I can just ignore this stuff here.

```py
    # add zero attention along batch dimension (now first)
    if add_zero_attn:
        zero_attn_shape = (bsz * num_heads, 1, head_dim)
        k = torch.cat([k, torch.zeros(zero_attn_shape, dtype=k.dtype, device=k.device)], dim=1)
        v = torch.cat([v, torch.zeros(zero_attn_shape, dtype=v.dtype, device=v.device)], dim=1)
        if attn_mask is not None:
            attn_mask = pad(attn_mask, (0, 1))
        if key_padding_mask is not None:
            key_padding_mask = pad(key_padding_mask, (0, 1))
```

I'll also ignore this stuff about cating zeros and biases. It is not essential to understanding what the function is doing. Right now I still find the attention mask mysterious.

https://pytorch.org/docs/stable/generated/torch.Tensor.expand.html

Huh interesting. What about repeat?

https://pytorch.org/docs/stable/generated/torch.Tensor.repeat.html?highlight=repeat#torch.Tensor.repeat

This does copy the tensor data.

```py
    # merge key padding and attention masks
    if key_padding_mask is not None:
        assert key_padding_mask.shape == (bsz, src_len), \
            f"expecting key_padding_mask shape of {(bsz, src_len)}, but got {key_padding_mask.shape}"
        key_padding_mask = key_padding_mask.view(bsz, 1, 1, src_len).   \
            expand(-1, num_heads, -1, -1).reshape(bsz * num_heads, 1, src_len)
        if attn_mask is None:
            attn_mask = key_padding_mask
        elif attn_mask.dtype == torch.bool:
            attn_mask = attn_mask.logical_or(key_padding_mask)
        else:
            attn_mask = attn_mask.masked_fill(key_padding_mask, float("-inf"))
```

Hmmmm...I find it stratenge that it is filling the mask with `-inf`.

```py
    # convert mask to float
    if attn_mask is not None and attn_mask.dtype == torch.bool:
        new_attn_mask = torch.zeros_like(attn_mask, dtype=torch.float)
        new_attn_mask.masked_fill_(attn_mask, float("-inf"))
        attn_mask = new_attn_mask
```

This has to be spew.

```py
    if need_weights:
        # average attention weights over heads
        attn_output_weights = attn_output_weights.view(bsz, num_heads, tgt_len, src_len)
        return attn_output, attn_output_weights.sum(dim=1) / num_heads
    else:
        return attn_output, None
```

Could have just used mean here.

```py
    attn_output, attn_output_weights = _scaled_dot_product_attention(q, k, v, attn_mask, dropout_p)
    attn_output = attn_output.transpose(0, 1).contiguous().view(tgt_len, bsz, embed_dim)
    attn_output = linear(attn_output, out_proj_weight, out_proj_bias)
```

There is so much stuff in this function, but the root is this first line here. Let me check it out.

https://discuss.pytorch.org/t/the-way-to-implement-attention-mask-uni-direction-attention-in-transformerdecoder/73124/4

```py
def _generate_square_subsequent_mask(self, sz):
    mask = (torch.triu(torch.ones(sz, sz)) == 1).transpose(0, 1)
    mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
    return mask
```

https://pytorch.org/docs/stable/generated/torch.triu.html

Ok, I see it.

3pm.

```py
    # convert mask to float
    if attn_mask is not None and attn_mask.dtype == torch.bool:
        new_attn_mask = torch.zeros_like(attn_mask, dtype=torch.float)
        new_attn_mask.masked_fill_(attn_mask, float("-inf"))
        attn_mask = new_attn_mask
```

Filling the mask here, and then...

```py
    if attn_mask is not None:
        attn += attn_mask
```

Adding it in dot product attention.

This is inefficient. It would be more sensible to just restrict the mask to bools.

The stuff here is too complicated, I'll redo it all from scratch at some point.

3:10pm. I understand how the mask works, but I am confused at what role it is supposed to play in the decoder? Was the thing in Lennart's video supposed to be for the encoder?

https://youtu.be/piT1_k8b9uM
Transformers - Part 7 - Decoder (2): masked self-attention

Let me watch this again.

https://youtu.be/piT1_k8b9uM?t=47

Ah, the mask is probably only applied to the first self attention layer.

https://youtu.be/piT1_k8b9uM?t=118

No wait, it is also putting in the encoder inputs here.

3:15pm. But not on the next slide.

Ok, let me check out the architecture from the top again. If I am right, the attention mask should only show up in the first part.

```py
        tgt2 = self.self_attn(tgt, tgt, tgt, attn_mask=tgt_mask,
                              key_padding_mask=tgt_key_padding_mask)[0]
        tgt = tgt + self.dropout1(tgt2)
        tgt = self.norm1(tgt)
        tgt2 = self.multihead_attn(tgt, memory, memory, attn_mask=memory_mask,
                                   key_padding_mask=memory_key_padding_mask)[0]
```

The first part is fine, but if I ever use a decoder I need to be careful as the `memory` and `tgt` padding masks aren't being merged.

3:30pm. Ok, let me take a break.

I've internalized the Decoder completely. The Encoder will just be a simpler version of it.

4:20pm. I am back. Let me take a look at the Encoder.

```py
    def forward(self, src: Tensor, src_mask: Optional[Tensor] = None, src_key_padding_mask: Optional[Tensor] = None) -> Tensor:
        r"""Pass the input through the encoder layer.

        Args:
            src: the sequence to the encoder layer (required).
            src_mask: the mask for the src sequence (optional).
            src_key_padding_mask: the mask for the src keys per batch (optional).

        Shape:
            see the docs in Transformer class.
        """
        src2 = self.self_attn(src, src, src, attn_mask=src_mask,
                              key_padding_mask=src_key_padding_mask)[0]
        src = src + self.dropout1(src2)
        src = self.norm1(src)
        src2 = self.linear2(self.dropout(self.activation(self.linear1(src))))
        src = src + self.dropout2(src2)
        src = self.norm2(src)
        return src
```

Yeah, this is a piece of cake to understand now. They really put dropout everywhere didn't they. I'll have to get rid of that.

4:30pm. Nevermind that right now though.

Hmmmm...

There is no need to play with passing random inputs into the layer. I understand it. Before I can finish this study session, I need to take a look at positional embedding.

https://pytorch.org/tutorials/beginner/transformer_tutorial.html

```py
class PositionalEncoding(nn.Module):

    def __init__(self, d_model, dropout=0.1, max_len=5000):
        super(PositionalEncoding, self).__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0).transpose(0, 1)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + self.pe[:x.size(0), :]
        return self.dropout(x)
```

Oh, I had no idea that it was possible to index like this into a tensor.

4:40pm. Right now I am thinking about it, and...

No I will require positional info for the calls.

4:45pm. How would rotational embedding be done?

https://blog.eleuther.ai/rotary-embeddings/

Let me read this.

> TL;DR:
> Rotary Positional Embedding (RoPE) is a new type of position encoding that unifies absolute and relative approaches. Developed by Jianlin Su in a series of blog posts earlier this year [12, 13] and in a new preprint [14], it has already garnered widespread interest in some Chinese NLP circles. This post walks through the method as we understand it, with the goal of bringing it to the attention of the wider academic community. In general we have found that across a large suite of setups including regular, linear, and local self-attention, it either matches or surpasses all other methods currently available for injecting positional information into transformers.

https://blog.eleuther.ai/rotary-embeddings/#runtime

> Unlike standard positional embeddings, however, rotary embeddings must be applied at every layer.

I should keep this in mind.

```py
class Rotary(torch.nn.Module):

    def __init__(self, dim, base=10000):
        super().__init__()
        inv_freq = 1. / (base ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer('inv_freq', inv_freq)
        self.seq_len_cached = None
        self.cos_cached = None
        self.sin_cached = None

    def forward(self, x, seq_dim=1):
        seq_len = x.shape[seq_dim]
        if seq_len != self.seq_len_cached:
            self.seq_len_cached = seq_len
            t = torch.arange(x.shape[seq_dim], device=x.device).type_as(self.inv_freq)
            freqs = torch.einsum('i,j->ij', t, self.inv_freq)
            emb = torch.cat((freqs, freqs), dim=-1).to(x.device)
            self.cos_cached = emb.cos()[:, None, None, :]
            self.sin_cached = emb.sin()[:, None, None, :]
        return self.cos_cached, self.sin_cached

# rotary pos emb helpers:

def rotate_half(x):
    x1, x2 = x[..., :x.shape[-1] // 2], x[..., x.shape[-1] // 2:]
    return torch.cat((-x2, x1), dim=x1.ndim - 1) # dim=-1 triggers a bug in torch < 1.8.0

@torch.jit.script
def apply_rotary_pos_emb(q, k, cos, sin):
    return (q _ cos) + (rotate_half(q) _ sin), (k _ cos) + (rotate_half(k) _ sin)
```

This code confuses me. The `_` is not a valid operator. Was that supposed to be `*`?

5:05pm. Hmmm, what are axial embeddings?

https://www.youtube.com/watch?v=hv3UO3G0Ofo
Axial-DeepLab: Stand-Alone Axial-Attention for Panoptic Segmentation (Paper Explained)

Let me have Yannic explain axial attention.

https://github.com/lucidrains/x-transformers/blob/a7cdab8e3099addd2d41fd8fdc784d2290ec799b/x_transformers/x_transformers.py#L165
```py
class RotaryEmbedding(nn.Module):
    def __init__(self, dim):
        super().__init__()
        inv_freq = 1. / (10000 ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer('inv_freq', inv_freq)

    def forward(self, max_seq_len, device):
        t = torch.arange(max_seq_len, device = device).type_as(self.inv_freq)
        freqs = torch.einsum('i , j -> i j', t, self.inv_freq)
        emb = torch.cat((freqs, freqs), dim=-1)
        return rearrange(emb, 'n d -> () () n d')

def rotate_half(x):
    x = rearrange(x, '... (j d) -> ... j d', j = 2)
    x1, x2 = x.unbind(dim = -2)
    return torch.cat((-x2, x1), dim = -1)

def apply_rotary_pos_emb(t, freqs):
    seq_len = t.shape[-2]
    freqs = freqs[:, :, -seq_len:]
    return (t * freqs.cos()) + (rotate_half(t) * freqs.sin())
```

There is an implementation of a rotary embedding here. I should definitely play with it for a bit until I understand what it is about. I do not understand most of those torch ops.

...Let me take a break again.

5:50pm. https://youtu.be/9-o2aAoN0rY
Fast reinforcement learning with generalized policy updates (Paper Explained)

I am watching this guy's videos again when I should be playing with the rotary embedding. Well, it does not matter, I'll put in some overtime. Let me check out what this video is about.

5:55pm. No I can't listen to this, it is too boring. Let me get back into the fray. I need to figure out what the hell of this is.

6pm. Focus me.

```py
def rearrange(tensor, pattern, **axes_lengths):
    """
    einops.rearrange is a reader-friendly smart element reordering for multidimensional tensors.
    This operation includes functionality of transpose (axes permutation), reshape (view), squeeze, unsqueeze,
    stack, concatenate and other operations.

    Examples for rearrange operation:

    >>> # suppose we have a set of 32 images in "h w c" format (height-width-channel)
    >>> images = [np.random.randn(30, 40, 3) for _ in range(32)]
    >>> # stack along first (batch) axis, output is a single array
    >>> rearrange(images, 'b h w c -> b h w c').shape
    (32, 30, 40, 3)
    >>> # concatenate images along height (vertical axis), 960 = 32 * 30
    >>> rearrange(images, 'b h w c -> (b h) w c').shape
    (960, 40, 3)
    >>> # concatenated images along horizontal axis, 1280 = 32 * 40
    >>> rearrange(images, 'b h w c -> h (b w) c').shape
    (30, 1280, 3)
    >>> # reordered axes to "b c h w" format for deep learning
    >>> rearrange(images, 'b h w c -> b c h w').shape
    (32, 3, 30, 40)
    >>> # flattened each image into a vector, 3600 = 30 * 40 * 3
    >>> rearrange(images, 'b h w c -> b (c h w)').shape
    (32, 3600)
    >>> # split each image into 4 smaller (top-left, top-right, bottom-left, bottom-right), 128 = 32 * 2 * 2
    >>> rearrange(images, 'b (h1 h) (w1 w) c -> (b h1 w1) h w c', h1=2, w1=2).shape
    (128, 15, 20, 3)
    >>> # space-to-depth operation
    >>> rearrange(images, 'b (h h1) (w w1) c -> b h w (c h1 w1)', h1=2, w1=2).shape
    (32, 15, 20, 12)

    :param tensor: tensor of any supported library (e.g. numpy.ndarray, tensorflow, pytorch, mxnet.ndarray).
            list of tensors is also accepted, those should be of the same type and shape
    :param pattern: string, rearrangement pattern
    :param axes_lengths: any additional specifications for dimensions
    :return: tensor of the same type as input. If possible, a view to the original tensor is returned.

    When composing axes, C-order enumeration used (consecutive elements have different last axis)
    Find more examples in einops tutorial.
    """
```

PyTorch really has a lot of interesting functionality.

6:15pm. This is so annoying. Right now I am reading the paper and I am getting lost as to what the theta parameter is supposed to be. This is so much more convoluted than it needs to be.

6:20pm. I am going to have to implement a simplified function in F#. What is m theta supposed to be?

file:///E:/Downloads/Metaheuristics/Attention/RoFormer%20-%20Enhanced%20Transformer%20with%20Rotary%20Position%20Embedding.pdf

```
is the rotary matrix with pre-defined parameters Θ = {θi = 10000^(−2(i−1)/d), i ∈ [1, 2, ..., d/2]}. An graphic
illustration of RoPE is shown in fig. (1).
```

Ah, I see.

7pm. Done with lunch. Let me just make a single pass through the thing normally. Then I am going to make a for loop version of the function.

Ah, m is the position. But now I do not understand what the dim is.

7:05pm. I am skimming too much. Figure 1 of the RoFormer paper tells me all I need.

7:35pm. Ok, I understand what the figured themselves in the paper are. But...

```py
def rotate_half(x):
    x = rearrange(x, '... (j d) -> ... j d', j = 2)
    x1, x2 = x.unbind(dim = -2)
    return torch.cat((-x2, x1), dim = -1)

def apply_rotary_pos_emb(t, freqs):
    seq_len = t.shape[-2]
    freqs = freqs[:, :, -seq_len:]
    return (t * freqs.cos()) + (rotate_half(t) * freqs.sin())
```

This stuff completely confuses me.

```py
def rotate_half(x):
    x1, x2 = x[..., :x.shape[-1] // 2], x[..., x.shape[-1] // 2:]
    return torch.cat((-x2, x1), dim=-1)
```

The same could be said for this.

```
            self.cos_cached = emb.cos()[:, None, None, :]
            self.sin_cached = emb.sin()[:, None, None, :]
```

What the hell is this indexing supposed to be doing?

7:45pm. Ahhhhhhh, I think I see it!

What makes it confusing is that the code here does not implement what was in the paper.

In the paper, you have `cos (m * theta_1)`, `cos (m * theta_1)`, `cos (m * theta_2)`...`cos (m * theta_d_half)`.

But what they do in the implementation is `cos (m * theta_1)`, `cos (m * theta_2)`...`cos (m * theta_d_half)`, and repeat `cos (m * theta_1)`, `cos (m * theta_2)`...`cos (m * theta_d_half)`.

They change the order of the rotations for the sake of an easier implementation. They do something similar for the sin, where they take the second half and negate it before concatenating it on the other end. Either way would work. But they should have left a comment so as to make it less confusing.

8:20pm. Ok, I understand this completely.

```py
import torch
import torch.nn
from einops import rearrange, repeat, reduce
from einops.layers.torch import Rearrange

class RotaryEmbedding(torch.nn.Module):
    def __init__(self, dim):
        super().__init__()
        inv_freq = 1. / (10000 ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer('inv_freq', inv_freq)

    def forward(self, max_seq_len, device):
        t = torch.arange(max_seq_len, device = device).type_as(self.inv_freq)
        freqs = torch.einsum('i , j -> i j', t, self.inv_freq)
        emb = torch.cat((freqs, freqs), dim=-1)
        return rearrange(emb, 'n d -> () () n d')

def rotate_half(x):
    x = rearrange(x, '... (j d) -> ... j d', j = 2)
    x1, x2 = x.unbind(dim = -2)
    return torch.cat((-x2, x1), dim = -1)

def apply_rotary_pos_emb(t, freqs):
    seq_len = t.shape[-2]
    freqs = freqs[:, :, -seq_len:]
    return (t * freqs.cos()) + (rotate_half(t) * freqs.sin())

q = torch.rand(2,6)
r = RotaryEmbedding(6)
r.forward(10,'cpu')[:,:,-2:]
```

I'll go with this implementation tomorrow.

Hmmm, actually no, I do not understand it completely yet. Am I expected to apply the rotary pos after in_proj multiplication for both the key and the query?

8:25pm. Yes, that is how things should go. Ok.

8:30pm. Phew, I think this should be enough for the day. I haven't written much code, but I've studied intensely and now I understand both the transformer (as is implemented in PyTorch) and the rotary embedding.

Hrrmmm...it won't be easy to use this in the PyTorch implementation. I should consider studying the x-transformer library code again. I should have more luck now that I've grokked the PyTorch implementation.

I want to go with the rotary embedding instead of the absolute one, but I do not want to reimplement everything for the game right off the bat. I suppose I could go with the absolute one for my first try.

I'll study the library and then decide.

8:35pm. Today was actually quite decent. It is great when you take the time to think and everything just comes to you. Another day of this and I will be ready to write the serializers for the transformer. After that it will really be a short step to putting these architectures to good use.

But I will have to take them apart and put in the cube activation and such.

But even so, this is like a week of work in my estimate. It is nothing too much. It should go quickly.

The first chapter of my ML journey is coming to a close. I'll have that elite Holdem agent by the end of the month."