"8:45am. I am surprised it is this early given that I've been in bed for a while. Any mail? Nope.
Yesterday I said I would email Z and the Turing guys, but forget that. It would not change anything. Instead I should take a risk and just start work on figuring out Turing and fix some of the open issues. That is the way to take initiative.

I realize now what I hadn't when I started the job hunt. The salary is one thing, but what really matters is working on what you want. There will be some compromises, but ultimately what matters is cultivating those skills relevant to your future goals. The salary is secondary. People who work on what they don't want now in hopes of working on what they want later are just fooling themselves.

When I get those AI chips I'll be working on a ML library in Spiral for it, and that library is likely to be a PPLs. The experience gained today will be a significant benefit.

Forget Z. If he comes back to me, that would be great, but I should go forward with the worst case in mind. Ultimately, if I put in the work to master Turing there is the risk that they might not hire me, but it is better than the job market lottery. And if I put in a few weeks of work to figure out Turing only to end up working on Omega that is fine too, it will make me that much valuable to be able to use an established library such as Turing as a reference.

8:55am. I have to take on this task.

Now, Turing will be particularly challenging to figure out. All the macro use will wreck the debugger and it is split into 3 different packages. So to start things off, I am going to have to figure out how `Debugger.jl` works since the built in VS Code one won't. After that I need to figure out how to do cross package debugging.

After I learn how to setup the project properly and how to trace through it, I'll be ready to start figuring out the library.

9am. I have to do this. I can't just read math books and go through courses. That won't teach me what I need to grasp the future. I need something challenging on this level. I did study for a bit and that improved my understanding, but that AI chip will not just come to me.

I need it in order to master a particular style of programming where I use NNs in order to guide program search. Without it, I might as well be fiddling with a pocket calculator in the quest for AI. My development will be frozen until I get better hardware.

9am. Respect to Hinton and guys like him who persevered through the 80s all the way to today. If I am feeling the pinch now, I can only imagine how it was for him during these decades having to deal with insufficient resources.

Let me chill a bit first and then I will start.

10:10am. I meant to start half an hour ago, let me do it now. I put a lot of pressure on me yesterday, but it is good that once the ball gets rolling to just let that unfold. I need to get back to a more leisurely pace.

I have to work, but I have to feel like I am doing it at my own rhythm otherwise I will burn out.

https://github.com/JuliaDebug/Debugger.jl

Forget figuring out all of Turing at once. First come the prereqs. Let me deal with Julia debugging.

10:15am. Right now it is installing.

Why is precompiling Plots? I hope that it won't precompile Flux because that would take an hour. Phew, it only took a minute.

```jl
using Debugger

function foo(n)
    x = n+1
    ((BigInt[1 1; 1 0])^x)[2,1]
end

@enter foo(20)
```

This is not working for me. For some reason...well, let me do what the error suggests.

```jl
using Debugger

function foo(n)
    x = n+1
    ((BigInt[1 1; 1 0])^x)[2,1]
end

Debugger.@enter foo(20)
```

This works when I run the last line directly in the REPL. Let me try making it a generate function.

```jl
using Debugger

@generated function foo(n)
    quote
    x = n+1
    ((BigInt[1 1; 1 0])^x)[2,1]
    end
end

Debugger.@enter foo(20)
```

The debugger works just fine. Ok great. It feels a good deal more responsive than the native editor one.

One thing I've noticed that it allows stepping into Core library functions. Actually, I think the original allowed that as well.

Ok, nevermind this. I should be stepping into Turing programs next. If the debuggers allows that, this will make figuring out the library a lot easier. If not, I am not sure how I will manage it.

https://turing.ml/dev/docs/using-turing/get-started

Let me try running this.

```jl
using Turing
using StatsPlots

# Define a simple Normal model with unknown mean and variance.
@model function gdemo(x, y)
  s² ~ InverseGamma(2, 3)
  m ~ Normal(0, sqrt(s²))
  x ~ Normal(m, sqrt(s²))
  y ~ Normal(m, sqrt(s²))
end

#  Run sampler, collect results
chn = sample(gdemo(1.5, 2), HMC(0.1, 5), 1000)

# Summarise results
describe(chn)

# Plot and save results
p = plot(chn)
savefig("gdemo-plot.png")
```

10:40am. The above works.

```jl
using Turing
using StatsPlots

# Define a simple Normal model with unknown mean and variance.
@model function gdemo(x, y)
  s² ~ InverseGamma(2, 3)
  m ~ Normal(0, sqrt(s²))
  x ~ Normal(m, sqrt(s²))
  y ~ Normal(m, sqrt(s²))
end

#  Run sampler, collect results
chn = sample(gdemo(1.5, 2), HMC(0.1, 5), 1000)

# # Summarise results
# describe(chn)

# # Plot and save results
# p = plot(chn)
```

Let me try stepping through this.

```
1|debug> o
ERROR: IOError: could not spawn `code -g 'C:\Users\Marko\.julia\packages\Turing\y0DW3\src\inference\Inference.jl:132'`: no such file or directory (ENOENT)
Stacktrace:
 [1] sample(model::DynamicPPL.Model{var"#5#6", (:x, :y), (), (), Tuple{Float64, Int64}, Tuple{}, DynamicPPL.DefaultContext}, alg::HMC{Turing.Core.ForwardDiffAD{40}, (), AdvancedHMC.UnitEuclideanMetric}, N::Int64; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Turing.Inference C:\Users\Marko\.julia\packages\Turing\y0DW3\src\inference\Inference.jl:132
 [2] sample(model::DynamicPPL.Model{var"#5#6", (:x, :y), (), (), Tuple{Float64, Int64}, Tuple{}, DynamicPPL.DefaultContext}, alg::HMC{Turing.Core.ForwardDiffAD{40}, (), AdvancedHMC.UnitEuclideanMetric}, N::Int64)
   @ Turing.Inference C:\Users\Marko\.julia\packages\Turing\y0DW3\src\inference\Inference.jl:132
```

Opening the line in the editor will take some work. Right now the problem is that it does not open me at the start of sample, but some strange function instead. Let me try again.

```
1|debug> s
In #sample#2(kwargs, , rng, model, alg, N) at C:\Users\Marko\.julia\packages\Turing\y0DW3\src\inference\Inference.jl:135
 138      alg::InferenceAlgorithm,
 139      N::Integer;
 140      kwargs...
 141  )
>142      return AbstractMCMC.sample(rng, model, Sampler(alg, model), N; kwargs...)
 143  end

About to run: <(DynamicPPL.Sampler)(HMC{Turing.Core.ForwardDiffAD{40}, (), AdvancedHMC.UnitEuclideanMetric}(0.1, 5),...>
1|debug> s
In Sampler(alg, model) at C:\Users\Marko\.julia\packages\DynamicPPL\yvQQ0\src\sampler.jl:42
>42  Sampler(alg, model::Model) = Sampler(alg, model, Selector())

About to run: (DynamicPPL.Selector)()
1|debug> s
In Selector(tag, rerun) at C:\Users\Marko\.julia\packages\DynamicPPL\yvQQ0\src\selector.jl:6
 6  function Selector(tag::Symbol=:default, rerun=tag != :default)
>7      return Selector(time_ns(), tag, rerun)
 8  end

About to run: (time_ns)()
1|debug> s
In time_ns() at Base.jl:65
>65  time_ns() = ccall(:jl_hrtime, UInt64, ())

About to run: (JuliaInterpreter.CompiledCalls.var"##compiledcall#291")()
1|debug> s
In time_ns() at Base.jl:65
>65  time_ns() = ccall(:jl_hrtime, UInt64, ())

About to run: return 0x0000a462f00ad564
1|debug> s
In Selector(tag, rerun) at C:\Users\Marko\.julia\packages\DynamicPPL\yvQQ0\src\selector.jl:6
 6  function Selector(tag::Symbol=:default, rerun=tag != :default)
>7      return Selector(time_ns(), tag, rerun)
 8  end

About to run: (DynamicPPL.Selector)(0x0000a462f00ad564, :default, false)
1|debug> s
In Selector(gid, tag, rerun) at C:\Users\Marko\.julia\packages\DynamicPPL\yvQQ0\src\selector.jl:2
>1  1 ─ %1 = %new($(QuoteNode(DynamicPPL.Selector)), gid, tag, rerun)
 2  └──      return %1

About to run: %new($(QuoteNode(DynamicPPL.Selector)), _J2, _J3, _J4)
1|debug> s
In Selector(tag, rerun) at C:\Users\Marko\.julia\packages\DynamicPPL\yvQQ0\src\selector.jl:6
 6  function Selector(tag::Symbol=:default, rerun=tag != :default)
>7      return Selector(time_ns(), tag, rerun)
 8  end

About to run: return DynamicPPL.Selector(0x0000a462f00ad564, :default, false)
1|debug> s
In Sampler(alg, model) at C:\Users\Marko\.julia\packages\DynamicPPL\yvQQ0\src\sampler.jl:42
>42  Sampler(alg, model::Model) = Sampler(alg, model, Selector())

About to run: <(DynamicPPL.Sampler)(HMC{Turing.Core.ForwardDiffAD{40}, (), AdvancedHMC.UnitEuclideanMetric}(0.1, 5),...>
1|debug> s
In Sampler(alg, model, s) at C:\Users\Marko\.julia\packages\DynamicPPL\yvQQ0\src\sampler.jl:43
>43  Sampler(alg, model::Model, s::Selector) = Sampler(alg, s)

About to run: <(DynamicPPL.Sampler)(HMC{Turing.Core.ForwardDiffAD{40}, (), AdvancedHMC.UnitEuclideanMetric}(0.1, 5),...>
```

This is what I was most afraid of. Omega was doable, but Turing feels like a nightmare to try to step through. Well, let me try going all the way through.

10:55am. Ok, I see there is a timer at the bottom showing exactly how long the sampling will take.

11am. This is no good. It keeps showing me the lowered code.

Yeah, this is the trouble with Turing. No wonder they had a help wanted sign out front. Nevertheless, I can't give up here. I should give it a day or two to get debugging to work at least. If that is impossible I am going to have a hell of time figuring out what the macros are doing and would be probably better off getting a regular job.

Trying to figure out what a macro heavy library is doing without the help of tooling would be too hard even for me. Now how do I deal with this?

Let me open Turing directly and I'll try the example there.

11:10am. It is precompiling Turing. It is going to be trouble to bring together the Turing package with DynamicPPL.

No this is not working. Should I try debugging DynamicPPL directly?

> If you feel you have some relevant skills and are interested in contributing then please do get in touch and open an issue on Github.

Actually, why did this feel like they could hire me if I had the skills? This does not indicate that at all.

11:20am.

```
AbstractMCMC = "3.2"
AdvancedHMC = "0.3.0"
AdvancedMH = "0.6"
AdvancedPS = "0.2.4"
AdvancedVI = "0.1"
```

It has a bunch of things split into different packages. It would be very hard for me to set it up all by myself by cloning the relevant repos.

If only I could have the Julia manager set it up locally.

https://docs.julialang.org/en/v1/stdlib/Pkg/

Let me read this.

```
Say we are working on Example and feel it needs new functionality. How can we modify the source code? We can use develop to set up a git clone of the Example package.

(tutorial) pkg> develop --local Example
...

(tutorial) pkg> status
    Status `/tmp/tutorial/Project.toml`
  [7876af07] Example v0.5.1+ [`dev/Example`]
Notice the feedback has changed. dev/Example refers to the location of the newly created clone. If we look inside the /tmp/tutorial directory, we will notice the following files:

tutorial
├── dev
│   └── Example
├── Manifest.toml
└── Project.toml
```

Yeah, this is what I need. I could use this to bring in DynamicPPL in Turing.

```
(Turing) pkg> develop --local DynamicPPL
     Cloning git-repo `https://github.com/TuringLang/DynamicPPL.jl.git`
   Resolving package versions...
ERROR: empty intersection between DynamicPPL@0.16.0 and project compatibility 0.15
```

https://stackoverflow.com/questions/52939603/julia-use-an-older-version-of-a-package

```
https://github.com/TuringLang/DynamicPPL.jl/tree/compathelper/new_version%2F2021-07-20-00-04-10-404-2776947565
```

Let me try adding this directly.

```
(Turing) pkg> develop --local https://github.com/TuringLang/DynamicPPL.jl/tree/compathelper/new_version%2F2021-07-20-00-04-10-404-2776947565
     Cloning git-repo `https://github.com/TuringLang/DynamicPPL.jl/tree/compathelper/new_version%2F2021-07-20-00-04-10-404-2776947565`
ERROR: failed to clone from https://github.com/TuringLang/DynamicPPL.jl/tree/compathelper/new_version%2F2021-07-20-00-04-10-404-2776947565, error: GitError(Code:ERROR, Class:HTTP, request failed with status code: 404)
```

Nope. No actually, let me try the tagged 0.15. This is not related to what I want.

11:35am. Ok, I have no choice. Let me open an issue on the Turing page. I need to ask the devs for some advice.

11:55am. https://github.com/TuringLang/Turing.jl/issues/

Opened issue 1710 asking for advice.

It is just too difficult to get into it normally without getting a push from the devs. I'll put the ball in their court. For some reason I am having trouble cloning from a specific commit. Hmmm, actually I am not sure that even normal cloning from a particular commit would work. Instead, I'd have to clone the whole thing and then checkout the tag.

https://discourse.julialang.org/t/check-out-tagged-commit-of-unregistered-package/4659
https://discourse.julialang.org/t/workflow-for-local-packages-with-local-dependencies/30636/2

```
(Turing) pkg> develop --local https://github.com/TuringLang/DynamicPPL.jl.git#0.15.0
ERROR: rev argument not supported by `develop`; consider using `add` instead
```

12:05pm. Hmmm, I have no idea. Ok, enough of this for now.

https://www.youtube.com/watch?v=aD_VEjDtOX0
JuliaCon 2020 | DynamicPPL: Stan-like Speed for Dynamic Probabilistic Models | Mohamed Tarek

I'll leave this video for after the break.

12:10pm. Macros are my weakness. Even if Turing guys were hiring, I am not sure I'll be able to deal with this codebase without some hand holding. Macros are like regexes, easy to write, hard to read.

I really absolutely need to set up the package locally so I can at least insert print statements and verify my thinking. Without that, it really will be hopeless.

I can't get a grasp on the whole library unless I am able to step through it whether with the debugger or mentally. When I did this with Omega, the experience of going through it served me later when I went through it top down.

12:15pm. Let me have breakfast here."