"9:50am. I got up earlier than I expected I would given how late I went to bed.
Yesterday I made a mistake of reading a paper and now I am thinking about my own ML ideas. Now my mind is preocupied with my own baseless ideas. I need to forget that.

10:30am. Let me start the day here. I am falling into my old pattern of obsessing about ML techniques. I just do not have what it takes to simulate their effects mentally so the exercise does not amount to anything.

Forget understanding them. Forget using the brain here. I need to use my hands to uncover the truth in this domain.

> So what I need to do is make a function that takes in a net, takes in a trace of observation and produces the output action. That is what is truly important. Let me stop here.

This is from yesterday. Let me focus on this.

10:35am. I've had a lot of focus during the night, but on the wrong thing.

https://www.reddit.com/r/MachineLearning/comments/llj80b/r_predictive_coding_is_a_consequence_of_energy/
Predictive coding is a consequence of energy efficiency in recurrent neural networks

I should not have taken the time to read this yesterday.

Let me open a new module.

```
union action = Fold | Call | Raise
union card = King | Queen | Jack
```

Let me make a function that takes in a sequence of these and then processes it into something the net can consume. I need to shake off my indecisiveness. I need toget into the swing of things.

I need to make a specialized file for PyTorch bindings.

```
type obj = $"object"
nominal tensor = obj
nominal net = obj
nominal distribution = obj
inl randn forall t {int}. (b,a : t * t) = tensor $"torch.randn(!b,!a)"
inl forward l (x : tensor) = tensor $"!l.forward(!x)"
inl fromArray (x : array _) : tensor = $"torch.from_numpy(!x)"
inl categorical (probs : tensor) : distribution = $"torch.distributions.Categorical(probs=!probs)"
inl sample (x : distribution) : tensor = $"!x.sample()"
```

Let me separate this out.

```
inl denseSerialize schema x =
    open serialization.dense.array
    inl (serialized x) = serialize schema x
    fromArray x
```

Let make this helper.

```
inl sparseDeserialize schema (x : tensor) =
    open serialization.sparse.int
    deserialize schema (serialized $"!x.item()")
```

This too. Ok.

```
inl serialize schema x =
    open serialization.dense.array
    inl (serialized x) = serialize schema x
    fromArray x

inl deserialize schema (x : tensor) =
    open serialization.sparse.int
    deserialize schema (serialized $"!x.item()")
```

Let me shorten their names.

Ok, with this I am safe.

Now what is next?

```
def leduc(intro,mid,out): return torch.nn.Sequential(
    torch.nn.Linear(intro,mid),
    torch.nn.LayerNorm(mid),
    torch.nn.Tanh(),
    torch.nn.Linear(mid,mid),
    torch.nn.Tanh(),
    torch.nn.Linear(mid,out)
    )
```

How about this?

Yeah, I have no idea what I am doing with the architecture. I remember being confused that putting layer norm before the activations worked better on Mnist, but the opposite worked better for a char RNN. Or was it the other way around? I'd have to check the journal.

```
def leduc(intro,mid,out): return torch.nn.Sequential(
    torch.nn.Linear(intro,mid),
    torch.nn.LayerNorm(mid),
    torch.nn.Tanh(),
    torch.nn.Linear(mid,mid),
    torch.nn.LayerNorm(mid),
    torch.nn.Tanh(),
    torch.nn.Linear(mid,out)
    )
```

Maybe this? Let me go with that.

Now let me do a function that takes in a list of observations and produces something the net can serialize.

```
union history = Action: action | Card: card
```

Let me go with this. Now let me make a function.

```
type dense_history = array (card * array action)
```

Like this for example.

```
let Schema =
    open serialization.dense.array
    inl card = alt {king=Unit; queen=Unit; jack=Unit} : pu card
    inl action = alt {fold=Unit; call=Unit; raise=Unit} : pu action
    array 2 (card ** array 4 action)
```

Here is the schema.

11:10am.

```
(base) PS C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests> dotnet "c:\Users\Marko\Source\Repos\The Spiral Language\VS Code Plugin\compiler\Spiral.dll" port=13805
Server bound to: tcp://*:13805 & tcp://*:13806
Unhandled exception: System.ArgumentException: An item with the same key has already been added. Key:  arg
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Spiral.Infer.term@942-10.Invoke(T s, RawExpr x) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language 2\Infer.fs:line 942
   at Spiral.Infer.term'@943(List`1 errors, Dictionary`2 generalized_statements, Dictionary`2 type_apply_args, Dictionary`2 module_type_apply_args, Dictionary`2 annotations, FSharpRef`1 autogened_forallvar_count, List`1 hover_types, FSharpFunc`2 unify, FSharpFunc`2 assert_bound_vars, FSharpRef`1 top_env, Int32 scope, Boolean is_in_left_apply, Env env, T s, RawExpr x) in C:\Users\Marko\Source\Repos\The Spiral Language\The Spiral Language 2\Infer.fs:line 1080
```

The server crashed. Let me investigate this error.

```
let process (l : list history) =
    let rec card l = function
        | Card: x => failwith "TODO"
        | Action: _ => failwith "Expected a card."
    and let action (c,l) = function
        | Card: x => failwith "TODO"
        | Action: x => failwith "TODO"
    ()
```

It is while I was doing this block.

Hmmm, maybe it has something to do with wildcards? Oh, it autocrashes on the above. This is good.

Let me compile the thing in debug mode.

Let me try to isolate it.

```
| RawV(r,a) -> rawv (r,a) (unify r s)
```

It happens right away when I try to isolate it. I did not even need to import core.

```
System.ArgumentException: 'An item with the same key has already been added. Key:  arg'
```

```
let rec let_join_point = function
    | RawFun(r,[a,b]) -> RawFun(r,[PatDyn(range_of_pattern a, a), let_join_point b])
    | RawFun(r,l) ->
        let empty = fst r, fst r
        let n = " arg"
        let a = PatDyn(empty,PatVar(empty,n))
        let b = RawMatch(empty,RawV(empty,n),List.map (fun (a,b) -> PatDyn(range_of_pattern a, a),b) l)
        RawFun(r,[a,join_point b])
    | x -> join_point x
```

Hmmm...It can only be this " arg" here.

11:20am. Hmmm, what do I do about this? I need an unique string, but doing it like this will intern it.

```fs
let rec let_join_point postfix = function
    | RawFun(r,[a,b]) -> RawFun(r,[PatDyn(range_of_pattern a, a), let_join_point postfix b])
    | RawFun(r,l) ->
        let empty = fst r, fst r
        let n = sprintf " arg%s" postfix // Don't remove the postfix otherwise the string will get staged by the .NET compiler.
        let a = PatDyn(empty,PatVar(empty,n))
        let b = RawMatch(empty,RawV(empty,n),List.map (fun (a,b) -> PatDyn(range_of_pattern a, a),b) l)
        RawFun(r,[a,join_point b])
    | x -> join_point x
```

This will do.

Now it is not crashing anymore.

Let me push this fix.

Now where was I?

```
let process (l : list history) =
    let rec action (c,l) = function
        | Cons: (Card: x), x' => (c,listm.rev l |> listm.toArray) :: action (x,Nil) x'
        | Cons: (Action: x), x' => action (c,x :: l) x'
        | Nil => (c,listm.rev l |> listm.toArray) :: Nil
    match l with
    | Cons: (Card: x), x' => action (x,Nil) x' |> listm.toArray
    | _ => failwith "Expected a card."
```

Done. Now focus me. What is next?

I have this function, I have the schema, I have the net.

```
inl SchemaInput =
    open serialization.dense.array
    inl card = alt {king=Unit; queen=Unit; jack=Unit} : pu card
    inl action = alt {fold=Unit; call=Unit; raise=Unit} : pu action
    array 2 (card ** array 4 action)

inl SchemaOutput =
    open serialization.sparse.int
    alt {fold=Unit; call=Unit; raise=Unit} : pu action
```

Here are both kinds of serializers.

Ok, let me get the net.

```
inl denseSize x = serialization.dense.array.size x
inl sparseSize x = serialization.sparse.int.size x

open bindings.torch
inl Net =
    !!!!Import("torch")
    !!!!Import("torch.nn")
    !!!!Import("torch.distributions")
    !!!!Import("nets")

    inl schemaIn =
        open serialization.dense.array
        inl card = alt {king=Unit; queen=Unit; jack=Unit} : pu card
        inl action = alt {fold=Unit; call=Unit; raise=Unit} : pu action
        array 2 (card ** array 4 action)
    inl schemaOut =
        open serialization.sparse.int
        alt {fold=Unit; call=Unit; raise=Unit} : pu action

    inl c = denseSize schemaIn
    inl b = 64u64
    inl a = sparseSize schemaOut

    $"nets.leduc(!c,!b,!a)" : net
```

Here is the net.

I should also return the serialize and deserialize functions while I am at it as well.

11:55am.

```
inl Net =
    !!!!Import("torch")
    !!!!Import("torch.nn")
    !!!!Import("torch.distributions")
    !!!!Import("nets")

    inl schemaIn =
        open serialization.dense.array
        inl card = alt {king=Unit; queen=Unit; jack=Unit} : pu card
        inl action = alt {fold=Unit; call=Unit; raise=Unit} : pu action
        array 2 (card ** array 4 action)
    inl schemaOut =
        open serialization.sparse.int
        alt {fold=Unit; call=Unit; raise=Unit} : pu action

    inl c = denseSize schemaIn
    inl b = 64u64
    inl a = sparseSize schemaOut

    open bindings.torch
    {
    net = $"nets.leduc(!c,!b,!a)" : net
    serialize = serialize schemaIn
    deserialize = deserialize schemaOut
    }
```

Getting to this form took way too long.

```
() -> {deserialize : tensor -> action; net : net; serialize : array (card * array action) -> tensor}
```

The type is right.

```
serialize = process >> serialize schemaIn
```

Let me do this one like so.

```
() -> {deserialize : tensor -> action; net : net; serialize : list history -> tensor}
```

Now the type is this.

Exactly what I need.

Let me take a break here. Time for breakfast."