"9:45am. Sure I could go to bed at an opportune time like 11pm...or I could play till 2am. I am up. I feel really groggy at the moment. Let me check out whether I got any replies.
https://meiosis.js.org/

10:05am. http://meiosis.js.org/tutorial/03-streams.html

Yeah, this is quite similar to what I had in mind.

10:15am. http://meiosis.js.org/tutorial/04-meiosis-with-function-patches.html

I anticipated they would do this. In JS you don't have pattern matching so it makes sense to pass functions directly as messages.

10:25am. Enough checking this out. Basically this is quite similar to what I had in mind. Leave it to the JS guys to figure out how to use streams functionally.

https://www.youtube.com/watch?v=faJ8N0giqzw
Tangible Functional Programming

I'll watch this later.

10:50am. What I want to do now is do some programming. Let me start work on Lithe. I want to do that damn library.

I'll save the Rx source for last. I had enough of studying for the time being.

11:05am.

```
open System
open FSharp.Control.Reactive

[<STAThread>]
[<EntryPoint>]
let main argv =
    let w = Windows.Window(Title="Hello")
    Windows.Application().Run(w)
    0 // return an integer exit code
```

This is how it starts. I've completely forgotten how WPF works by this point, but I am going to refresh my memory.

Let me aim for the counter demo for the time being.

...I've completely forgotten how to even create buttons. Let me take a look at that old repo where I put the examples I translated from Petzold's book.

...That is strange. I can't find it.

11:15am. https://github.com/dmitry-a-morozov/fsharp-wpf-mvc-series/wiki/Model

I remember this. This really scared me off.

11:20am. https://github.com/mrakgr/Exercises/tree/master/Fsharp%20Exercises

Finally found it!

Except, I fucked up the examples and did not write them in the chapter order.

...It is no good. I need the help of the book as well.

...I forgot that it was 1.5k pages long. That is something! Just the first part which is 600 pages took me 1 month to transcribe. What a waste of time that turned out to be in the end.

11:30am.

```
open System
open System.Windows
open System.Windows.Input
open System.Windows.Controls
open System.Windows.Media

type VaryTheBackground() as t =
    inherit Window()

    let brush = SolidColorBrush(Colors.Black)

    do
        t.Height <- 400.0
        t.Width <- 400.0
        t.WindowStartupLocation <- WindowStartupLocation.CenterScreen
        t.Background <- brush

    override t.OnMouseMove(args) =
        base.OnMouseMove args

        let width = t.ActualWidth - 2.0 * SystemParameters.ResizeFrameVerticalBorderWidth
        //printfn "ActualWidth = %f, ActualHeight = %f" t.ActualWidth t.ActualHeight
        //printfn "ResizeFrameVerticalBorderWidth = %f, ResizeFrameHorizontalBorderHeight = %f, CaptionHeight = %f" SystemParameters.ResizeFrameVerticalBorderWidth SystemParameters.ResizeFrameHorizontalBorderHeight SystemParameters.CaptionHeight
        let height = t.ActualHeight - 2.0 * SystemParameters.ResizeFrameHorizontalBorderHeight - SystemParameters.CaptionHeight

        let ptMouse = args.GetPosition(t)
        let ptCenter = Point(width/2.0, height/2.0)
        let vectMouse = ptMouse - ptCenter
        let angle = atan2 vectMouse.Y vectMouse.X
        let vectEclipse = Vector(width / 2.0 * (cos angle), height / 2.0 * (sin angle))
        printfn "vectMouse.Length = %A, vectEclipse.Length = %A" vectMouse.Length vectEclipse.Length
        let byLevel = 255.0 * (1.0 - min 1.0 (vectMouse.Length / vectEclipse.Length)) |> byte
        brush.Color <- Color.FromRgb(byLevel,byLevel,byLevel)

[<STAThread>]
[<EntryPoint>]
let main _ = Application().Run(VaryTheBackground())
```

I seem not to have done the very first example, but here is the one that I did.

11:40am. Er, I am confused. Do I need to manually remove the handlers here in order to dispose them or will they get disposed along with the control?

Forget that for now. Let me abstract this using streams.

11:45am.

```
let control c l = let c = c() in List.iter ((|>) c) l; c
let prop s v c = Observable.subscribe (s c) v
let event s f c = (s c : IEvent<_,_>).Add f
```

Here are the 3 utility functions. Later on I'll let control return an observable, but let me just get through this example.

Ah, whops. Subscribing to props produces disposables. I forgot about that.

11:55am.

```
    let m = MouseButtonEventHandler(fun x y -> ())
    t.MouseDown.AddHandler(m)
```

Shit, if I want to do these properly I need to clean up the handlers. All of these require these generic handlers rather than regular functions.

Agh, since I am doing a proof of concept forget about cleanup.

12:10pm.

```
open System
open System.Windows
open System.Windows.Input
open System.Windows.Controls
open System.Windows.Media

open FSharp.Control.Reactive

// TODO: Forget about cleanup for the time being. This is a proof of concept.
let control c l = let c = c() in List.iter ((|>) c) l; c
let prop' s v c = s c v
let prop s v c = Observable.subscribe (s c) v |> ignore
let event s f c = (s c : IEvent<_,_>).Add (f c)

let w =
    let brush = SolidColorBrush(Colors.Black)

    control Window [
        prop' (fun c v -> c.Height <- v) 400.0
        prop' (fun c v -> c.Width <- v) 400.0
        prop' (fun c v -> c.WindowStartupLocation <- v) WindowStartupLocation.CenterScreen
        prop' (fun c v -> c.Background <- v) brush
        event (fun c -> c.MouseMove) (fun c args ->
            let width = c.ActualWidth - 2.0 * SystemParameters.ResizeFrameVerticalBorderWidth
            let height = c.ActualHeight - 2.0 * SystemParameters.ResizeFrameHorizontalBorderHeight - SystemParameters.CaptionHeight

            let ptMouse = args.GetPosition(c)
            let ptCenter = Point(width/2.0, height/2.0)
            let vectMouse = ptMouse - ptCenter
            let angle = atan2 vectMouse.Y vectMouse.X
            let vectEclipse = Vector(width / 2.0 * (cos angle), height / 2.0 * (sin angle))
            let byLevel = 255.0 * (1.0 - min 1.0 (vectMouse.Length / vectEclipse.Length)) |> byte
            brush.Color <- Color.FromRgb(byLevel,byLevel,byLevel)
            )
        ]

[<STAThread>]
[<EntryPoint>]
let main _ = Application().Run(w)
```

12:10pm.

```
let event s f c = (s c : IEvent<'a,_>).Add (f c)
```

Maybe there could be a way to automatically create the delegate here using reflection.

At any rate, I quite like this form. It is starting to look functional already. I have to admit though, I've underestimated how mutable the example really is.

12:25pm.

```
module Try2

open System
open System.Windows
open System.Windows.Input
open System.Windows.Controls
open System.Windows.Media

open FSharp.Control.Reactive

// TODO: Forget about cleanup for the time being. This is a proof of concept.
let control c l = let c = c() in List.iter ((|>) c) l; c
let prop' s v c = s c v
let prop s v c = Observable.subscribe (s c) v |> ignore
let event s f c = (s c : IEvent<_,_>).Add (f c)

let w =
    let color = Subject.broadcast

    control Window [
        prop' (fun c v -> c.Height <- v) 400.0
        prop' (fun c v -> c.Width <- v) 400.0
        prop' (fun c v -> c.WindowStartupLocation <- v) WindowStartupLocation.CenterScreen
        prop' (fun c v -> c.Background <- v) (SolidColorBrush(Colors.Black))
        prop (fun c v -> (c.Background :?> SolidColorBrush).Color <- v) color
        event (fun c -> c.MouseMove) (fun c args ->
            let width = c.ActualWidth - 2.0 * SystemParameters.ResizeFrameVerticalBorderWidth
            let height = c.ActualHeight - 2.0 * SystemParameters.ResizeFrameHorizontalBorderHeight - SystemParameters.CaptionHeight

            let ptMouse = args.GetPosition(c)
            let ptCenter = Point(width/2.0, height/2.0)
            let vectMouse = ptMouse - ptCenter
            let angle = atan2 vectMouse.Y vectMouse.X
            let vectEclipse = Vector(width / 2.0 * (cos angle), height / 2.0 * (sin angle))
            let byLevel = 255.0 * (1.0 - min 1.0 (vectMouse.Length / vectEclipse.Length)) |> byte
            color.OnNext <| Color.FromRgb(byLevel,byLevel,byLevel)
            )
        ]

[<STAThread>]
[<EntryPoint>]
let main _ = Application().Run(w)
```

Here is the second try.

```
        prop' (fun c v -> c.Background <- v) (SolidColorBrush(Colors.Black))
        prop (fun c v -> (c.Background :?> SolidColorBrush).Color <- v) color
```

I did not anticipate having to do this, but it is fine.

Let me do a message pump.

12:40pm.

```
module VaryTheBackground.Try3

open System
open System.Windows
open System.Windows.Input
open System.Windows.Controls
open System.Windows.Media

open FSharp.Control.Reactive

let dispatch' = Subject.broadcast
let color =
    dispatch'
    |> Observable.scanInit (Color.FromRgb(0uy,0uy,0uy))
        (fun m x -> x)

let dispatch x = dispatch'.OnNext x

// TODO: Forget about cleanup for the time being. This is a proof of concept.
let control c l = let c = c() in List.iter ((|>) c) l; c
let prop' s v c = s c <- v
let prop s v c = Observable.subscribe (fun v -> s c <- v) v |> ignore
let event s f c = (s c : IEvent<_,_>).Add (f c)

let w =
    control Window [
        prop' (fun c -> c.Height) 400.0
        prop' (fun c -> c.Width) 400.0
        prop' (fun c -> c.WindowStartupLocation) WindowStartupLocation.CenterScreen
        prop' (fun c -> c.Background) (SolidColorBrush(Colors.Black) :> _)
        prop (fun c -> (c.Background :?> SolidColorBrush).Color) color
        event (fun c -> c.MouseMove) (fun c args ->
            let width = c.ActualWidth - 2.0 * SystemParameters.ResizeFrameVerticalBorderWidth
            let height = c.ActualHeight - 2.0 * SystemParameters.ResizeFrameHorizontalBorderHeight - SystemParameters.CaptionHeight

            let ptMouse = args.GetPosition(c)
            let ptCenter = Point(width/2.0, height/2.0)
            let vectMouse = ptMouse - ptCenter
            let angle = atan2 vectMouse.Y vectMouse.X
            let vectEclipse = Vector(width / 2.0 * (cos angle), height / 2.0 * (sin angle))
            let byLevel = 255.0 * (1.0 - min 1.0 (vectMouse.Length / vectEclipse.Length)) |> byte
            dispatch <| Color.FromRgb(byLevel,byLevel,byLevel)
            )
        ]

[<STAThread>]
let main _ = Application().Run(w)
```

I am surprised that this actually works. F# is nice. Quite nice.

```
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\01_VaryTheBackground\Try3.fs(21,19): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\01_VaryTheBackground\Try3.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\01_VaryTheBackground\Try3.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\01_VaryTheBackground\Try3.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\01_VaryTheBackground\Try3.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\File1.fs(21,19): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\File1.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\File1.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\File1.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\File1.fs(22,40): error FS0971: Undefined value 'copyOfStruct : 'b ref'
```

Ugh, the errors for this did not show up in Intellisense.

12:50pm. `prop' (fun c v -> c.Background <- v) (SolidColorBrush(Colors.Black))`

Now I am wondering why does this thing not need a cast, but I see that it did not need it before too.

Ok...

12:50pm.

```
module Bug

type Q() =
    member val t = 0 with get, set

let f c x = c () <- x

let q = Q()
f (fun _ -> q.t) 2
```

```
1>C:\Users\Marko\Source\Repos\Lithe\Lithe\bug.fs(6,13): error FS0971: Undefined value 'copyOfStruct : 'a ref'
```

Let me open this issue on the F# repo.

...Opened issue 8899.

1pm. Now where was I?

What comes next?

Well, I should really stop so I can have breakfast.

I am really into this, but I need to focus on my basic needs a bit.

After I get back though, what I should do is try some examples with child controls."