"1:15pm. Enough slacking. I am being far too lazy.
I need to focus. Though I do not feel like it, I need to solve the mystery of `transp`. I can't just wait for the answer.

Rather just trying things at random let me think about...

```
addp : PathP (λ i → ℕ≡Bin i → ℕ≡Bin i → ℕ≡Bin i) _+_ _+Bin_
addp i = transp (λ j → ℕ≡Bin (i ∧ j) → ℕ≡Bin (i ∧ j) → ℕ≡Bin (i ∧ j)) (~ i) _+_
```

For a bit instead.

What this is supposed to do is create a path from `N -> N -> N` to `Bin -> Bin -> Bin`.

```
-- We can transport addition on ℕ to Binℕ
_+Binℕ_ : Binℕ → Binℕ → Binℕ
_+Binℕ_ = transport (λ i → Binℕ≡ℕ (~ i) → Binℕ≡ℕ (~ i) → Binℕ≡ℕ (~ i)) _+_
```

This is how `+Bin` is is defined in the library.

1:30pm.

```
addp : PathP (λ i → ℕ≡Bin i → ℕ≡Bin i → ℕ≡Bin i) _+_ _+Bin_
addp i = transp (λ j → ℕ≡Bin (i ∧ j) → ℕ≡Bin (i ∧ j) → ℕ≡Bin (i ∧ j)) (~ i) _+_
```

1:35pm. This is confusing. I won't be able to make any progress until I figure out what `i1` as the second argument does.

1:45pm. I've run it again and again in my head. The above is not too difficult. When `i = i1`...

```
addp : PathP (λ i → ℕ≡Bin i → ℕ≡Bin i → ℕ≡Bin i) _+_ _+Bin_
addp i = transp (λ j → ℕ≡Bin j → ℕ≡Bin j → ℕ≡Bin j) i0 _+_
```

In this case this acts like a straightforward transport from `i0` to `i1`.

And when `i = i0` that `transp` should just reduce to `_+_`.

1:55pm. No the above is wrong.

```
addp : PathP (λ i → ℕ≡Bin i → ℕ≡Bin i → ℕ≡Bin i) _+_ _+Bin_
addp i = transp (λ j → ℕ≡Bin i1 → ℕ≡Bin i1 → ℕ≡Bin i1) i0 _+_
```

And when `i = i0`...

```
addp : PathP (λ i → ℕ≡Bin i → ℕ≡Bin i → ℕ≡Bin i) _+_ _+Bin_
addp i = transp (λ j → ℕ≡Bin j → ℕ≡Bin j → ℕ≡Bin j) i1 _+_
```

Damn it, now everything makes even less sense.

2pm. I need to get a grip on this.

2:10pm.

```
transport : ∀ {A B : Set} → I → A ≡ B → A → A
-- transport i p a = transp (λ i → p (~ i)) i1 a
```

This is getting me nowhere.

2:15pm. Hmmmm...

```
transport : ∀ {A B : Set} → A ≡ A → A → A
transport p a = transp (λ i → p i) i1 a
```
```
E:\TheoremProving\CubicalAgdaStuff\hello.agda:6,25-34
p i != A of type Set
when checking that the expression transp (λ i → p i) i1 a has type
A
```

I really did not expect this error.

```
transport : ∀ {A B : Set} → A ≡ A → A → A
transport p a = transp (λ i → p i0) i1 a
```
```
transport : ∀ {A B : Set} → A ≡ A → A → A
transport p a = transp (λ i → p i1) i1 a
```

These two on the other hand work.

I am confused as to what is going on here. Just what is `transp` doing and why was it designed like this?

Let me ask about this as well.

2:30pm.

```
      oddp : PathP (λ i → Binℕ≡ℕ i → Bool) oddBinℕ oddℕ
      oddp i = transp (λ j → Binℕ≡ℕ (i ∧ j) → Bool) (~ i) oddBinℕ
```

Yeah, I completely do not understand how this could function when `i = i1` here.

2:50pm. Got a reply just now.

https://agda.readthedocs.io/en/v2.6.0.1/language/cubical.html

I've pretty much forgotten that Cubical Agda has the docs.

```
refl : ∀ {ℓ} {A : Set ℓ} {x : A} → Path A x x
refl {x = x} = λ i → x

> Although they use the same syntax, a path is not exactly the same as a function. For example, the following is not valid:

refl : ∀ {ℓ} {A : Set ℓ} {x : A} → Path A x x
refl {x = x} = λ (i : I) → x
```

Subtle things like these escaped me last time I've checked this.

2:55pm. Ok, forget about trying to figure it out directly. Let me ask about function extensionality as well. I might as well ask everything that is on my mind.

3pm.

```
funExt : (f : ℕ → ℕ) → f ≡ f
funExt f i = {!!}
```

Ah, I've been meaning to ask about function extensionality, but I get it now. Here I get one argument, but if the thing is not a function I do not get anything. So the logic for extensionality is consistent.

3:05pm. Let me go back to `addp`.

```
addp : PathP (λ i → ℕ≡Bin i → ℕ≡Bin i → ℕ≡Bin i) _+_ _+Bin_
addp i = transp (λ j → ℕ≡Bin (i ∧ j) → ℕ≡Bin (i ∧ j) → ℕ≡Bin (i ∧ j)) (~ i) _+_
```

Rather than saying `i = ...` Let me just say that `~ i = i0` or `~ i = i1` from here on out.

So putting together that thing about constant functions...

When `~ i = i0` this is supposed to be a constant transport from `Bin -> Bin -> Bin` to `Bin -> Bin -> Bin`. And when `~ i = i1` then `ℕ -> ℕ -> ℕ` to `Bin -> Bin -> Bin`. Which makes no sense to me.

```
transp (λ j → ℕ≡Bin j → ℕ≡Bin j → ℕ≡Bin j) i1 _+_
```

But when i1 is in the second argument, there is doubt that the the function should reduce to the term that I've written out...

No wait, there is no doubt that I am wrong. I am mixing up some things I've read in the library.

```
  let -- We first build a path from oddBinℕ to oddℕ. When i=1 this is
      -- "transp (λ j → Binℕ≡ℕ j → Bool) i0 oddBinℕ" (i.e. oddℕ)
      oddp : PathP (λ i → Binℕ≡ℕ i → Bool) oddBinℕ oddℕ
      oddp i = transp (λ j → Binℕ≡ℕ (i ∧ j) → Bool) (~ i) oddBinℕ
```

No the library is right. I am just being an idiot. You igore 1 in the and operation, not the zero.

So then, the two cases I am looking at are.

```
transp (λ j → ℕ≡Bin j → ℕ≡Bin j → ℕ≡Bin j) i0 _+_
```

This makes sense.

```
transp (λ j → ℕ≡Bin i0 → ℕ≡Bin i0 → ℕ≡Bin i0) i1 _+_
```

And this is a constant function that matches the type of `_+_`. Ok, I see it now.

3:15pm. It is really amazing how many mental errors I've made in the past few hours that I've been studying this. Not only have I misunderstood the concepts, but I've also made elementary boolean algebra mistakes.

This is why programming is difficult especially when learning new things. Having to learn new type stuff must have overloaded my brain, but I do get this now.

3:25pm. It is time for me to start moving on.

```
J : ∀ {ℓ} {A : Set ℓ} {x : A} (P : ∀ y → x ≡ y → Set ℓ)
      (d : P x refl) {y : A} (p : x ≡ y)
    → P y p
J P d p = transport (λ i → P (p i) (λ j → p (i ∧ j))) d
```

Since I ma looking into the docs let me study `J` for a while.

AFter that I have the rest of the module waiting for me. There actually is not that much in Cubical Agda, but what is there I am going to go at it playfully like a kid would."