"```fs let numpy_ty = function     | YPrim Int8T -> "numpy.int8"     | YPrim Int16T -> "numpy.int16"     | YPrim Int32T -> "numpy.int32"     | YPrim Int64T -> "numpy.int64"     | YPrim UInt8T -> "numpy.uint8"     | YPrim UInt16T -> "numpy.uint16"     | YPrim UInt32T -> "numpy.uint32"     | YPrim UInt64T -> "numpy.uint64"     | YPrim Float32T -> "numpy.float32"     | YPrim Float64T -> "numpy.float64"     | _ -> "object" ```
Let me back this up here.

```fs
| TyArrayCreate(a,b) -> return' $"numpy.empty({tup b},dtype={numpy_ty a})"
```

I have this...

```fs
        | YArray a ->
            import "numpy"; cimport "numpy"
            let a = match a with YPrim x -> prim x | _ -> "object"
            $"numpy.ndarray[{a},ndim=1]"
```

This should be all it takes. Let me try it out.

```
ValueError: Buffer dtype mismatch, expected 'char' but got Python object
Exception ignored in: 'testm.method3'
Traceback (most recent call last):
  File "cython_experiments/test3/run.py", line 5, in <module>
    print(main())
ValueError: Buffer dtype mismatch, expected 'char' but got Python object
IndexError: Out of bounds on buffer access (axis 0)
Exception ignored in: 'testm.method6'
Traceback (most recent call last):
  File "cython_experiments/test3/run.py", line 5, in <module>
    print(main())
IndexError: Out of bounds on buffer access (axis 0)
TypeError: object of type 'NoneType' has no len()
Exception ignored in: 'testm.method7'
Traceback (most recent call last):
  File "cython_experiments/test3/run.py", line 5, in <module>
    print(main())
TypeError: object of type 'NoneType' has no len()
TypeError: object of type 'NoneType' has no len()
Exception ignored in: 'testm.method8'
Traceback (most recent call last):
  File "cython_experiments/test3/run.py", line 5, in <module>
    print(main())
TypeError: object of type 'NoneType' has no len()
```

This is what I get when I try this on test45. There is something wrong that was not a problem before.

6:15pm.

```
    print("asd")
    method3(v3, v0, v4, v5)
    print("qwe")
```

I am doing printf debugging now. I though I was done with this. Just how did these bugs come back in?

```
        v7 = len(v6)
        v8 = numpy.empty(v7,dtype=object)
        print("qqq")
```

`qqq` does not get printed.

let me print `v7`.

```
asd
v7 -  4
ValueError: Buffer dtype mismatch, expected 'char' but got Python object
Exception ignored in: 'testm.method3'
Traceback (most recent call last):
  File "cython_experiments/test3/run.py", line 5, in <module>
    print(main())
ValueError: Buffer dtype mismatch, expected 'char' but got Python object
qwe
```

v7 is 4 here, but `qqq` does not get printed. This feels like a compiler bug on the Cython side to me.

6:25pm. I am not replicating it on a simplified example.

6:30pm. I have no idea. Let me try going a few commits back on a temporary branch. I need a sanity check whether I really did or did not have an error on this last time.

...Nope, it did not work at that time either.

Let me go back.

Hmmm, I wonder if exceptions are being raised out of turn? Also am I sure that numpy does indexing from 0?

```
s in Python, all indices are zero-based: for the i-th index n_i, the valid range is 0 \le n_i < d_i where d_i is the i-th element of the shape of the array.
```

Maybe the exceptions happens before the call to method3?

7pm. Done with lunch.

```
import numpy
cimport numpy
cdef class US0:
    cdef readonly signed long tag
cdef class US0_0(US0): # empty
    def __init__(self): self.tag = 0
cdef class US0_1(US0): # princess
    def __init__(self): self.tag = 1
cdef class UH0:
    cdef readonly signed long tag
cdef class UH0_0(UH0): # cons_
    cdef readonly str v0
    cdef readonly UH0 v1
    def __init__(self, str v0, UH0 v1): self.tag = 0; self.v0 = v0; self.v1 = v1
cdef class UH0_1(UH0): # nil
    def __init__(self): self.tag = 1
cdef class US1:
    cdef readonly signed long tag
cdef class US1_0(US1): # none
    def __init__(self): self.tag = 0
cdef class US1_1(US1): # some_
    cdef readonly unsigned long long v0
    cdef readonly unsigned long long v1
    cdef readonly UH0 v2
    def __init__(self, unsigned long long v0, unsigned long long v1, UH0 v2): self.tag = 1; self.v0 = v0; self.v1 = v1; self.v2 = v2
cdef class Mut0:
    cdef public US1 v0
    def __init__(self, US1 v0): self.v0 = v0
cdef class Tuple0:
    cdef readonly unsigned long long v0
    cdef readonly unsigned long long v1
    cdef readonly UH0 v2
    def __init__(self, unsigned long long v0, unsigned long long v1, UH0 v2): self.v0 = v0; self.v1 = v1; self.v2 = v2
cdef void method1(unsigned long long v0, unsigned long long v1, unsigned long long v2, unsigned long long v3, numpy.ndarray[object,ndim=1] v4, unsigned long long v5):
    cdef char v6
    cdef unsigned long long v7
    cdef char v8
    cdef char v10
    cdef US0 v13
    v6 = v5 < v0
    if v6:
        v7 = v5 + 1
        v8 = v3 == v1
        if v8:
            v10 = v5 == v2
        else:
            v10 = 0
        if v10:
            v13 = US0_1()
        else:
            v13 = US0_0()
        v4[v5] = v13
        method1(v0, v1, v2, v3, v4, v7)
cdef void method0(unsigned long long v0, unsigned long long v1, unsigned long long v2, numpy.ndarray[object,ndim=1] v3, unsigned long long v4):
    cdef char v5
    cdef unsigned long long v6
    cdef numpy.ndarray[object,ndim=1] v7
    cdef unsigned long long v8
    v5 = v4 < v0
    if v5:
        v6 = v4 + 1
        v7 = numpy.empty(v0,dtype=object)
        v8 = 0
        method1(v0, v1, v2, v4, v7, v8)
        v3[v4] = v7
        method0(v0, v1, v2, v3, v6)
cdef void method3(unsigned long long v0, numpy.ndarray[object,ndim=1] v1, numpy.ndarray[object,ndim=1] v2, unsigned long long v3):
    cdef char v4
    cdef unsigned long long v5
    cdef numpy.ndarray[object,ndim=1] v6
    cdef unsigned long long v7
    cdef numpy.ndarray[char,ndim=1] v8
    cdef unsigned long long v9
    v4 = v3 < v0
    if v4:
        v5 = v3 + 1
        v6 = v1[v3]
        v7 = len(v6)
        print("v7 - ",v7)
        v8 = numpy.empty(v7,dtype=object)
        print("qqq")
cdef UH0 method2(numpy.ndarray[object,ndim=1] v0, unsigned long long v1, unsigned long long v2):
    cdef unsigned long long v3
    cdef numpy.ndarray[object,ndim=1] v4
    cdef unsigned long long v5
    cdef US1 v6
    cdef Mut0 v7
    cdef numpy.ndarray[object,ndim=1] v8
    cdef UH0 v9
    v3 = len(v0)
    v4 = numpy.empty(v3,dtype=object)
    v5 = 0
    print("Entering method3")
    method3(v3, v0, v4, v5)
    print("Exited method3")
cpdef void main():
    cdef unsigned long long v0
    cdef unsigned long long v1
    cdef unsigned long long v2
    cdef numpy.ndarray[object,ndim=1] v3
    cdef unsigned long long v4
    cdef unsigned long long v5
    cdef unsigned long long v6
    cdef UH0 v7
    v0 = 4
    v1 = 2
    v2 = 3
    print("Initing")
    v3 = numpy.empty(v0,dtype=object)
    v4 = 0
    method0(v0, v1, v2, v3, v4)
    v5 = 0
    v6 = 0
    print("Starting")
    v7 = method2(v3, v5, v6)
    print("Done")
```

I managed to pare it down to this.

```
    cdef numpy.ndarray[char,ndim=1] v8
    # print("v7 - ",v7)
    v8 = numpy.empty(4,dtype=object)
```

Ah, wait, the message does make sense. it is expecting a char.

```fs
let numpy_ty = function
    | YPrim Int8T -> "numpy.int8"
    | YPrim Int16T -> "numpy.int16"
    | YPrim Int32T -> "numpy.int32"
    | YPrim Int64T -> "numpy.int64"
    | YPrim UInt8T -> "numpy.uint8"
    | YPrim UInt16T -> "numpy.uint16"
    | YPrim UInt32T -> "numpy.uint32"
    | YPrim UInt64T -> "numpy.uint64"
    | YPrim Float32T -> "numpy.float32"
    | YPrim Float64T -> "numpy.float64"
    | _ -> "object"
```

I forgot the char here.

7:15pm. It works now. Let me push this patch.

7:20pm. I'll call it a day here.

I'll stick with Numpy arrays for the near term.

7:25pm. Let me have some fun here. Yesterday I went to bed early, so I did not sink much time into the Kumo novels.

Tomorrow, I will make my first step back to the road of ML. I had enough of compiler engineering."