"Average game value: -0.040474
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

3:40pm. Had to take a short break. At any rate, I figured this thing out in a minute. It can only be this...

```
let agent' = Array.init dice.Length (fun _ -> Array.replicate ((1 <<< claims.Length) - 1) None)
```

I need to make the thing longer by one.

```
let agent' = Array.init dice.Length (fun _ -> Array.replicate (1 <<< claims.Length) None)
```

Like so.

```
Average game value: -0.040474
```

Yeah, that was it.

Now let me time this stuff. I wish I'd timed the version that was using dictionaries.

Well, it is no biggie.

```
#time
train 100
#time
```

```
Average game value: -0.030120
Real: 00:00:02.424, CPU: 00:00:02.421, GC gen0: 2062, gen1: 1, gen2: 0
```

Not bad.

```
--> Timing now on

Average game value: -0.040474
Real: 00:00:14.930, CPU: 00:00:14.890, GC gen0: 6889, gen1: 9, gen2: 0
val it : unit = ()

--> Timing now off
```

Here is for the other thing.

So it is a 6x speed improvement. Not too bad.

Let me run it for 5k iterations. I want to see what I get.

3:50pm.

```
Average game value: -0.030696
Real: 00:01:56.266, CPU: 00:01:56.140, GC gen0: 103111, gen1: 18, gen2: 1
```

Here it is for 5k iterations.

Let me run it for 25k iterations.

I want to see if it goes closer to 0.02.

...Ah, it is not -0.02, but around -0.027 according to the paper. Yeah, this is right, no doubt about it.

3:55pm. I guess I'll read the paper while this thing runs. I'll commit after that.

No...actually let me do the chores here. I forgot about that.

4:20pm.

```
Average game value: -0.028627
Real: 00:10:05.119, CPU: 00:10:02.109, GC gen0: 515580, gen1: 62, gen2: 7
```

Done with chores. Yeah, this is right, totally.

A lot of GCing is going on for some reason which tells me there is still room for optimization, but forget that.

With this I am done with Dudo. Let me go on with the paper. I do not think I will be programming anymore for the day, but I still have some steam left."