"1:50pm. Done with breakfast and chores. Let me watch the Vite crash course.
...Actually, let me chill a bit first. After that I'll deal with Vite. And then I will be free from these build issues.

2:20pm. https://boards.4channel.org/g/thread/91557202/aivsg-ai-voice-synthesis-general#p91562848

https://vocaroo.com/1mcYA2LGqbJg

This was good. Well, let me start.

https://youtu.be/LQQ3CR2JTX8
Vite 2.0 Crash Course | Super Fast Build Tool for JavaScript, React, Vue, Svelte, & Lit (2021)

https://youtu.be/LQQ3CR2JTX8?t=27

This guy has a great editor.

https://youtu.be/LQQ3CR2JTX8?t=132

This is pretty fast.

https://youtu.be/LQQ3CR2JTX8?t=509

Yeah, it has been a while so I forgot, but Vite is very fast.

https://youtu.be/LQQ3CR2JTX8?t=538

Let me stop this here. I just want to know how env variables work in Vite.

https://youtu.be/yGNGtd-d3ro?t=1
Environment Variables in Vite + React

https://youtu.be/yGNGtd-d3ro?t=95

How do you do this in the vite config file?

https://stackoverflow.com/questions/66389043/how-can-i-use-vite-env-variables-in-vite-config-js

Finally!

```js
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default ({mode}) => {
    process.env = {...process.env, ...loadEnv(mode, process.cwd(), '')};
    const target = `http://localhost:${process.env.SERVER_PROXY_PORT || '5000'}`;
    console.log(process.env.PORT);
    console.log(target);

    return defineConfig({
        port: process.env.PORT,
        server: {
            proxy: {
                '/api': { target, changeOrigin: true },
                '/socket': { target, ws: true},
            }
        },
        plugins: [react()],
        define: {
            // remotedev will thrown an exception without this.
            global: {},
        },
    })
}
```

This works. Now I can make use of the env variables. Great.

But the port is not changing. Ah, maybe I need to parse it as int?

```
  VITE v4.1.2  ready in 538 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

Damn it what the hell?

https://vitejs.dev/config/server-options.html#server-port

Ah, I should do it in server, maybe?

```js
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default ({mode}) => {
    process.env = {...process.env, ...loadEnv(mode, process.cwd(), '')};
    const target = `http://localhost:${process.env.SERVER_PROXY_PORT || '5000'}`;

    console.log(mode);

    return defineConfig({
        server: {
            port: process.env.PORT,
            open: process.env.PATH_INDEX_HTML,
            proxy: {
                '/api': { target, changeOrigin: true },
                '/socket': { target, ws: true},
            }
        },
        build: {
            rollupOptions: {
            input: {
                app: process.env.PATH_INDEX_HTML,
               },
            },
        },
        plugins: [react()],
        define: {
            // remotedev will thrown an exception without this.
            global: {},
        },
    })
}
```

I am making progress, but setting a custom `index.html` entry point is not working.

```
PATH_INDEX_HTML='/src/Client/index.html'
```

```
open: 'E:/Webdev/Fable/test/safe-template-full-tutorial/tests/Client/index.html',
```

Why is this happening?

```

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  path: 'undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBlADoALwBXAGUAYgBkAGUAdgAvAEYAYQBiAGwAZQAvAHQAZQBzAHQALwBzAGEAZgBlAC0AdABlAG0AcABsAGEAdABlAC0AZgB1AGwAbAAtAHQAdQB0AG8AcgBpAGEAbAAvAHQAZQBzAHQAcwAvAEMAbABpAGUAbgB0AC8AaQBuAGQAZQB4AC4AaAB0AG0AbAAiAA=='
  ]
}
```

I always get this error.

```
open: '/index.html',
```

This is very weird.

https://stackoverflow.com/questions/68283635/spawn-c-windows-system32-windowspowershell-v1-0-powershell-enoent-error-while

```
client: node:events:505
client:       throw er; // Unhandled 'error' event
client:       ^
client:
client: Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
client:     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
client:     at onErrorNT (node:internal/child_process:478:16)
client:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
client: Emitted 'error' event on ChildProcess instance at:
client:     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
client:     at onErrorNT (node:internal/child_process:478:16)
client:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
client:   errno: -4058,
client:   code: 'ENOENT',
client:   syscall: 'spawn undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
client:   path: 'undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
client:   spawnargs: [
client:     '-NoProfile',
client:     '-NonInteractive',
client:     '?ExecutionPolicy',
client:     'Bypass',
client:     '-EncodedCommand',
client:     'UwB0AGEAcgB0ACAAIgBoAHQAdABwADoALwAvADEAMgA3AC4AMAAuADAALgAxADoAOAAwADgAMAAvAHMAcgBjAC8AQwBsAGkAZQBuAHQALwBpAG4AZABlAHgALgBoAHQAbQBsACIA'
client:   ]
client: }
```

Shit. I get this when use dotnet run.

...Let me try running dotnet run from the bash console as well.

```
<!doctype html>
<html>
<head>
    <title>SAFE Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/favicon.png"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
</head>
<body>
    <div id="elmish-app"></div>
</body>
</html>
```

I think I forgot `type="module"` again.

```
<div type="module" id="elmish-app"></div>
```

Shouldn't there be a script?

`<script type="module" src="main.jsx"></script>`

Ah whops. The script needs to be of type module.

3:30pm. I got it to work, finally!

```
http://127.0.0.1:8080/src/Client/index.html
```

Except, I'd prefer it rewrites te urls so it is not this.

3:35pm. Anyway, both bundling and tests pass now.

One thing I've realized too late now, is that I really should be looking for config files on github and seeing how they do things.

```
ROOT=tests/Client
OUTDIR=../../dist
```

Let me try setting it up like this. Actually...no, it is fine.

3:55pm. Since I am not using open, running it from the PS terminal works.

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3#winget

Right now I am thinking of upgrading it.

https://adamtheautomator.com/powershell-version/

Which version do I have?

```
PS E:\Webdev\Fable\test\safe-template-full-tutorial> (Get-Host).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  2364
```

An old one it seems.

What the hell. I installed it, but it still load the old thing.

https://learn.microsoft.com/en-us/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.3

> In Windows PowerShell, the PowerShell executable is named powershell.exe. In version 6 and above, the executable is named pwsh.exe. The new name makes it easy to support side-by-side execution of both versions.

I guess this is how it works. Can I update the VS Code path somehow?

https://code.visualstudio.com/docs/terminal/profiles

https://rnelson0.com/2020/03/05/using-powershell-7-in-vs-code/

```
    "terminal.integrated.profiles.windows": {
        "PowerShell 7": {
            "path": "C:/Program Files/PowerShell/7/pwsh.exe",
            "icon": "terminal-powershell"
        },
        "PowerShell 5": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
```

I tried creating a profile like this. Let me see if it works.

For some reason the old one keeps lingering, but neverind. The new one works well. Let me test the new file with it.

4:20pm. PS 7 has autocomplete, but I can't figure out how to trigger it. It just shows up as grayed out text.

Oh, by pressing Ctrl Space, it opens up a selector window! That makes navigation a lot easier.

4:30pm. Ok, let me do it all from scratch and I will record it. This time let me start with a `git init`.

4:55pm. FFFFFFUCK, I did a long recording, and Camtasia lost it all! Fuck.

FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF. What the hell!

...No, wait. It did not. It just didn't order it as I'd have expected it. It is all still there. Phew.

https://pixabay.com/music/beautiful-plays-please-calm-my-mind-125566/
https://pixabay.com/music/corporate-calm-background-for-video-121519/
https://pixabay.com/music/beats-weeknds-122592/

7:05pm. It is 12m. While it is rendering, let me make more fem spiderman images.

> Female spiderman web slinging through the city.

I logged into paperspace a couple of minutes ago, so I can start prompting right away.

> RuntimeError: No such operator xformers_flash::flash_fwd - did you forget to build xformers with `python setup.py develop`?

Ohhh, fuck you.

It seems I can only do a batch size of 3 at most. Thankfully I can raise the batch count higher instead.

7:15pm. I could do without the body horror. Hands always seems to be an issue.

7:20pm. I do not whether I am being more critical, but these are too low quality.

7:25pm. Got some good ones, let me move on.

7:40pm. https://youtu.be/OLBsNLIEjb8
Webpack Config Files Too Complicated? See Here How To Replace Webpack With Vite

The playlist got only 5 upvotes on the F# sub. it seems I have a way to go. Maybe they don't like female spiderman?

Actually, rather than it being a week, it is more like a week and a half that I am messing with this.

https://www.reddit.com/r/fsharp/comments/10w3yn6/how_do_i_understand_the_build_system_in_modern_f/

This post is from 10 days ago.

7:50pm. This is how long it took me to get some measure of skill. I guess I am doing these Youtube vids to alleviate my loneliness. Imagine I conquered this challenge, and just wrote about it in this blog. Nobody would know about it. I have a 100 followers, but they might as well be 0. I do not need followers that just lurk and do not support me.

Youtube on the other hand is great for knowledge transfer.

I should be able to demostrate my skills to a wider audience.

7:55pm. I am not under an illusion that these past 5 vids are going to be popular. But they will be useful for those in a similar situation such as me.

11:20pm. Whops, I forgot to commit.

Ep 20 of Shadow was kino."