"2:10pm. I could resume, but let me slack a bit more.
2:35pm. A bit more slacking. There is one thing I will do - I am going add support for comments in the parser. I'll just lift that straight from the Spiral's own parser.

2:45pm. Let me start. Comments. This one is simple. When I do the documentation I will have to note that some parser work till the end of line.

```
let spaces = Tokenize.spaces
```

I'll just fetch the one from tokenize.

Let me try it out.

```
dir_out: qwe
dir_source: c:\qwe
version: 1.2.3 (alpha)
//version: 1.2.3 (alpha)
name: Test
files:
    A
    Submodule/
        Q
        //W
        W
        E
```

Works perfectly.

Ok.

I am going to have to add the capability to the plugin so that `//` inserts comments into the config file.

2:50pm. Ok, with that out of the way let me move to the next step.

Editor support.

Here is where things get real.

3pm. I am thinking.

At this point I do know how to do IPC. That is fine. I know quite a lot. But I do not know the very first step which is how to set up a server. On the node side it is easy enough as the process won't terminate as long as the server is active, but on the .NET side I had to wait for a keypress.

I need to figure out how actual servers work.

3:05pm. There are 3 starter challenges I need to figure out before I can start work in earnest.

1) Setting up a nonterminating server as I've discussed.
2) The way to set it up and close it from the Node side.
3) How exactly do command line arguments get parsed.

3:05pm. I am just making a plan for making a plan.

Only once I establish communication firmly between the two ends will I be able to proceed.

Let me play a bit with command line args.

```
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 a s d
a
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab s d
ab
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab() s d
At line:1 char:16
+ ./reactive1 ab() s d
+                ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression

PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab(w) s d
w : The term 'w' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:16
+ ./reactive1 ab(w) s d
+                ~
    + CategoryInfo          : ObjectNotFound: (w:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab(1+2) s d
ab
3
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab (1+2) s d
ab
3
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab (w) s d
w : The term 'w' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:17
+ ./reactive1 ab (w) s d
+                 ~
    + CategoryInfo          : ObjectNotFound: (w:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab w s d
ab
w
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab ("qwe") s d
ab
qwe
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab-qwe s d
ab-qwe
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab -qwe s d
ab
-qwe
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab=qwe -qwe s d
ab=qwe
-qwe
s
d
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 ab= qwe -qwe s d
ab=
qwe
-qwe
s
d
```

The only surprise to me here are the args in parenths. Had no idea those get evaled directly.

Ok, now I have this.

```
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 "ab= qwe" -qwe s d
ab= qwe
-qwe
s
d
```

File paths will have to go in strings.

```
PS C:\Users\Marko\Source\Repos\Reactive1\Reactive1\bin\Release\netcoreapp3.1> ./reactive1 "ab\n= qwe" -qwe s d
ab\n= qwe
-qwe
s
d
```

They don't get escaped. Ok.

Though I can't be sure of that on the JS side. JS sure would transform the escape character. Don't know about JSON though.

Well, I'll figure it out. That is number 3 off the list.

Now comes the first item. Setting up a server.

3:25pm. http://www.fssnip.net/nQ/title/Agent-demo

Agh, I just do not know what to look for. Let me ask on SO.

3:30pm. Ah, actually...

```
open System
open System.Threading
open Suave

[<EntryPoint>]
let main argv =
  let cts = new CancellationTokenSource()
  let conf = { defaultConfig with cancellationToken = cts.Token }
  let listening, server = startWebServerAsync conf (Successful.OK "Hello World")

  Async.Start(server, cts.Token)
  printfn "Make requests now"
  Console.ReadKey true |> ignore

  cts.Cancel()

  0 // return an integer exit code
```

Note that here it starts it asynchronously.

```
open System
open System.Threading
open Suave
open Suave.Filters
open Suave.Operators
open Suave.Successful

[<EntryPoint>]
let main argv =
    let app =
      choose
        [ GET >=> choose
            [ path "/hello" >=> OK "Hello GET"
              path "/goodbye" >=> OK "Good bye GET" ]
          POST >=> choose
            [ path "/hello" >=> OK "Hello POST"
              path "/goodbye" >=> OK "Good bye POST" ] ]

    startWebServer defaultConfig app

    0 // return an integer exit code
```

Here it is started synchronously.

...You know what, let me clone Suave. Rather than ask on SO, I could just take a look at how they do it.

...It wants the 2.2 .NET Core SDK. Ok.

```
e:\Webdev\Fsharp\suave>dotnet --version
A compatible installed .NET Core SDK for global.json version [2.2.401] from [e:\Webdev\Fsharp\suave\global.json] was not found
Install the [2.2.401] .NET Core SDK or update [e:\Webdev\Fsharp\suave\global.json] with an installed .NET Core SDK:
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
```

It want's the exact version. Agh, let me just change the value the the latest one in `global.json`. I didn't take the error message seriously at first as I did not know what that `global.json` file is, but now I see it right there in the directory.

3:45pm.

```
  /// Runs the web server and blocks waiting for the asynchronous workflow to be cancelled or
  /// it returning itself.
  let startWebServer (config : SuaveConfig) (webpart : WebPart) =
    Async.RunSynchronously(startWebServerAsync config webpart |> snd, cancellationToken = config.cancellationToken)
```

So the synchronous start is just this.

```
// Lazily install DotNet SDK in the correct version if not available
let install = lazy DotNet.install (fun opt -> { opt with Version = DotNet.Version "2.2.401" })
```

This is in the `build.fsx` file.

```
e:\Webdev\Fsharp\suave>fsi build.fsx

build.fsx(3,1): error FS2301: 'paket: groupref Build //' is not a valid assembly name

e:\Webdev\Fsharp\suave>
```

3:55pm. Now this is what is taking up my time. Well, there are days like this. I am wracking my brain over this, but I am getting closer to the answer slowly.

Let me just take my time.

4pm.

```
type Agent<'T> = MailboxProcessor<'T>

/// Represents different messages
/// handled by the stats agent
type StatsMessage =
    | Add of float
    | Clear
    | GetAverage of AsyncReplyChannel<float>

let stats =
    Agent.Start(fun inbox ->

    // Loops, keeping a list of numbers
    let rec loop nums = async {
        let! msg = inbox.Receive()
        match msg with
        | Add num ->
            return! loop (num::nums)
        | GetAverage repl ->
            printfn "%A" nums
            repl.Reply(List.average nums)
            return! loop nums
        | Clear ->
            return! loop [] }

    loop [] )

// Add error handler
stats.Error.Add(fun e -> printfn "Oops: %A" e)

//// Post messages
stats.Post(Add(10.0))
stats.Post(Add(7.0))
stats.Post(Clear)
stats.PostAndReply(GetAverage)
```

I am surprised that this gives me an exception. Why is this happening?

```
stats.PostAndReply(GetAverage)
```

At any rate I could use this to wait for the exit message...somehow.

```
//// Post messages
stats.Post(Add(10.0))
stats.Post(Add(7.0))
stats.Post(Clear)
stats.PostAndReply(GetAverage)
```

Oh, I am such an idiot. I completely forgot the clear message.

4:05pm. Ok, I have an idea. Can I wait on an observable?

```
type Agent<'T> = MailboxProcessor<'T>

/// Represents different messages
/// handled by the stats agent
type StatsMessage =
    | Add of float
    | Clear
    | GetAverage of AsyncReplyChannel<float>

let stats =
    Agent.Start(fun inbox ->
    // Loops, keeping a list of numbers
    let rec loop nums = async {
        match! inbox.Receive() with
        | Add num ->
            return! loop (num::nums)
        | GetAverage repl ->
            repl.Reply(List.average nums)
            return! loop nums
        | Clear ->
            return! loop [] }

    loop [] )

// Add error handler
stats.Error.Add(fun e -> printfn "Oops: %A" e)

//// Post messages
stats.Post(Add(10.0))
stats.Post(Add(7.0))
stats.PostAndReply(GetAverage)
stats.Post(Clear)
```

The way infinite loops in servers work is like this. And the reason why they don't consume all the resources is because they are async.

Assuming I have an async something, I can block on it...

4:15pm. I am going to ask how to write a program that waits for an observable to complete.

4:25pm.

```
open System
//open System.Reactive.Linq
open FSharp.Control.Reactive

[<EntryPoint>]
let main argv =
    Observable.wait
```

Ah, I get it. Observable wait exists. It waits for the observable to finish and returns the last element in the sequence.

Let me try something...

```
open System
open FSharp.Control.Reactive

let i =
    Observable.interval (TimeSpan.FromSeconds(1.0))
    |> Observable.take 3
    |> Observable.iter (printfn "%i...")
    |> Observable.wait

printfn "Done. The last elem is %i." i
```

4:30pm.

```
open System
open FSharp.Control.Reactive

let i =
    Observable.interval (TimeSpan.FromSeconds(1.0))
    |> Observable.take 3
    |> Observable.iter (printfn "%i...")
    |> Observable.wait

printfn "Done. The last elem is %i." i
```

Yeah, this is it. When it comes to subjects, I can just call their OnComplete.

I wonder how `wait` is implemented?

4:35pm. Agh, the Rx source is convoluted as I remember it. Where is the thing implemented?

4:40pm.

```
namespace System.Threading
{
    //
    // Summary:
    //     Represents a thread synchronization event that, when signaled, must be reset
    //     manually. This class is a lightweight alternative to System.Threading.ManualResetEvent.
    public class ManualResetEventSlim : IDisposable
```

So there is this `ManualResetEventSlim` class in `System.Threading` and `LastBlocking` inherits from both it and `Observer`.

```
        public void OnCompleted()
        {
            Set();
        }
```

Ok, I get it. Let me do it without having to call wait.

4:45pm.

```
open System
open System.Threading
open FSharp.Control.Reactive

let app_terminator = new ManualResetEventSlim()
let i =
    Observable.interval (TimeSpan.FromSeconds(1.0))
    |> Observable.take 3
    |> Observable.subscribeWithCompletion (printfn "%i...") (fun _ -> app_terminator.Set())

app_terminator.Wait()
printfn "Done."
```

This works. This is great as I do not necessarily want separate subscriptions just to hit the wait.

4:50pm. Damn, it is nearly 5pm now. This issue actually took me over 1.5h to figure out.

...Actually I am being foolish. Another way to do this would have been...

```
open System
open System.Threading
open FSharp.Control.Reactive

let i =
    Observable.interval (TimeSpan.FromSeconds(1.0))
    |> Observable.take 3
    |> Observable.iter (printfn "%i...")
    |> Observable.wait

printfn "Done."
```

This way might be even better except it is not getting rid of the last value and that would leave it in memory.

So maybe I should do something like...

...Ah, and actually, this thing would throw an exception if at least one value is not generated. Really, there isn't anything like wait, except without returning a value in the library?

5:05pm.

```fsharp
open System
open System.Threading
open FSharp.Control.Reactive

module Observable =
    /// Blocks the thread until the observable completes.
    let waitUnit on_next (o : IObservable<_>) =
        use t = new ManualResetEventSlim()
        use __ = Observable.subscribeWithCompletion on_next (fun _ -> t.Set()) o
        t.Wait()

Observable.interval (TimeSpan.FromSeconds(1.0))
|> Observable.take 3
|> Observable.waitUnit (printfn "%i...")

printfn "Done."
```

This is satisfactory.

5:05pm. How about I ask the question and then answer it myself.

5:25pm. https://stackoverflow.com/questions/61714334/how-to-wait-for-an-observable-to-complete/61714335#61714335

I am such a diligent worker bee.

Let me take a small break.

Now that I have this piece, I can finally start thinking of how to actually do the server.

5:35pm.

```
module Pipes_1

open System
open System.IO.Pipes
open System.Text
open System.Threading
open System.Net
open System.Net.Sockets

let try' () =
    use client = new NamedPipeClientStream(".","TheSpiralLanguage",PipeDirection.InOut)

    printfn "Connecting to server..."
    client.Connect(1000)
    if client.IsConnected then
        printfn "Connected."
        let write (msg : string) =
            let x = Encoding.UTF8.GetBytes(msg)
            client.Write(x,0,x.Length)
        write """{"type":"message","data":"hello"}"""
    Console.ReadKey()
```

Hmmm, I might have the wrong thing here. I actually know only how to do single reads and writes, not how to set up a proper reactive pipeline.

Let me get a way from the screen a bit.

5:55pm. I am back. Had time to think about it. There is no way around it - I need a server, rather than a client here. I could turn the client into a server by hand by doing those async reads infinitely in a loop, but I should just look at the done solution instead. It probably comes with an event emitter that I can plug into.

6:10pm. The named pipe server is not what I thought it was. In terms of features it is the same as the client...and unfortunately it has no emitters.

If I thought the standard event concurrency was bad, this thing is another thing entirely. It only has async reads and writes. I was not counting on having to operate at such a low level. I can't even wait till the message is done.

```
    x.on("data", data => {
        const s = String(data);
        console.log(s);
        if (s === "close") {
            console.log("Will close.");
            server.close(); }
    });
```

This is actually making me wonder, will this only feed me data on the message finish or will I get it intermittently?

6:15pm. I can't be sure. But what I am sure is that I want to at least start on the level where I am passing complete messages around, not raw strings.

Let me give some of those Nuget IPC libraries a try. I'll try the Nethereum one to start with.

6:25pm. No docs. It is not really what I want.

https://github.com/UweKeim/ZetaIpc
https://github.com/zeromq/netmq
> ZeroMQ (also known as ØMQ, 0MQ, or zmq) looks like an embeddable networking library but acts like a concurrency framework. It gives you sockets that carry atomic messages across various transports like in-process, inter-process, TCP, and multicast. You can connect sockets N-to-N with patterns like fan-out, pub-sub, task distribution, and request-reply. It's fast enough to be the fabric for clustered products. Its asynchronous I/O model gives you scalable multicore applications, built as asynchronous message-processing tasks. It has a score of language APIs and runs on most operating systems. ZeroMQ is from iMatix and is LGPLv3 open source.

>We took a normal TCP socket, injected it with a mix of radioactive isotopes stolen from a secret Soviet atomic research project, bombarded it with 1950-era cosmic rays, and put it into the hands of a drug-addled comic book author with a badly-disguised fetish for bulging muscles clad in spandex. Yes, ZeroMQ sockets are the world-saving superheroes of the networking world.

Oh lol.

6:45pm. I am thinking...

```
PipeTransmissionMode.Message
```

What is this?

6:45pm.

```
let try' () =
    use client = new NamedPipeClientStream(".","TheSpiralLanguage",PipeDirection.InOut)
    client.ReadMode <- PipeTransmissionMode.Message
```

I was not ready for this. I really haven't put in any thought into how asynchronous buffers should transfer data ever in my career. And it does not feel like the libraries I am looking at are what I want.

I should have gone with a web server after all.

If I really wanted to do this using pipes, I'd need to do at least a week or two of research. I'll take a look at ZeroMQ though.

Why was I so wrong. I guess because I only sent data from the .NET side and that part is straightforward.

https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines

Hmmm...

Oh, this pretty much tells me all the issues that I could think of.

7:15pm.

```
let try' () =
    use client = new NamedPipeClientStream(".","TheSpiralLanguage",PipeDirection.InOut)
    let q = client :> Stream
```

Hmmm, `NamedPipeClientStream` is in fact a `Stream`.

And FParsec takes in streams....

7:20pm. I need to stop. A lot of fun stuff is coming to my mind, but I really should exercise discipline and just use http servers for what I want to do. Especially given that I'll want the language server to work on Linux and MacOS later, and free interop would be much more preferable to performance. Though, I really am entering a new world here.

It feels impossible to deal with these streams at first glance, but they are ultimately just that. I actually have plenty of options to choose from with regards to how to handle them.

The simplest scheme I can think of would be to read 4 bytes, convert it to an `int` to get the length of the message and then read that, convert it to a string.

7:25pm. But that would just be getting too fancy. I was mad at the Fable guys for picking bad interop options, I can't really start having fun with IPC here. It would be one thing if both sides had JSON interop out of the box, but they don't. So I am better just sticking to the tried and true TCP.

Let me go eat. I really overdid it. Though this is in interesting puzzle, I'll backtrack tomorrow and do it properly."