"8:20am. Let me start. I'll investigate probabilistic programming very thoroughly from here on out. Right now, I am way too obsessed with neural nets and RL. I need to loosen up.
It is not like I haven't thought about making a player using Bayesian methods, but I've never thought those things as anything more than a gimmick. I never saw those things having any kind of visible success in the RL arena. It is not like my current methods are something I believe in either, but they have some effectiveness for toy games. I thought that if I pushed hard enough I could get some kind of inspiration for how to break through.

I was wrong. I have absolutely no idea how to scale them to master something like Holdem given my computational resources. The wall I've hit is very hard.

It is such a bold thing to try to do reasoning from the top down. If I thought that were possible, I would've wanted to do that as well. But I knew I could not.

Reading the prob mods book did convince me of the rationality of Bayesian reasoning, and the probability theory book did convince me that the Bayesian sum and product rules are just an extension of regular logic to handle uncertainty. But how do I go beyond to something that I could run on a computer?

8:35am. If I got an AI chip and did all the training on it, with my current methods at most I could get the player to do GTO play on a per hand basis. Adapting to how the other player acts, something a human would do, is pure fiction. There is not a computer big enough to let me do something like that.

I am going at it bottom up and I simply have no way of breaking through. I am missing something.

8:40am. Let me check out the email instead of just ranting here and then I'll dive into prob prog. Nope. Ok, let me just go for it.

https://github.com/zenna/Omega.jl

All his stuff seems to be in Julia. I never thought I would seriously use that kind of language, but you really never know what comes in life.

Let me install Julia. Julia is the language I consider to be Spiral's rival. They target the same niche, but have very different strengths.

https://openreview.net/pdf?id=S1l8oANFDH
Synthesizing Programmatic Policies That Inductively Generalize

> Deep reinforcement learning has successfully solved a number of challenging control tasks. However, learned policies typically have difficulty generalizing to novel environments. We propose an algorithm for learning programmatic state machine policies that can capture repeating behaviors. By doing so, they have the ability to generalize to instances requiring an arbitrary number of repetitions, a property we call inductive generalization. However, state machine policies are hard to learn since they consist of a combination of continuous and discrete structures. We propose a learning framework called adaptive teaching, which learns a state machine policy by imitating a teacher; in contrast to traditional imitation learning, our teacher adaptively updates itself based on the structure of the student. We show that our algorithm can be used to learn policies that inductively generalize to novel environments, whereas traditional neural network policies fail to do so.

I am no match for these guys. I've been thinking what my actual level of skill in ML would be, and going purely by results I'd say it is 2/5.

> We may expect the LSTM policies to alleviate this issue. However, the LSTM policies often perform poorly even on the training distribution, and also generalize worse than the feed-forward neural network policies.

To get around this you'd need something like signSGD, plus the activations I've discovered. Not that it would work particularly well even with that.

> An added benefit of our state machine policies is interpretability. In particular, we demonstrate the interpretability of our policies by showing how a user can modify a learned state machine policy.

State machines, huh?

I'll do a no NN challenge and see how far does that get me in training a poker agent. No NNs, and no RL.

> Our policy inductively generalizes for a wide range of training distributions. In contrast, the test performance of the RL policy initially increases as the train distribution gets bigger, but it eventually starts declining. The reason is that its training performance actually starts to decline. Thus, in some settings, our approach (even when trained on smaller distributions) can produce policies that outperform the neural network policies produced by RL (even when trained on the full distribution).

9:15am. I am not sure what to do next. Let me install the Omega library and I'll go through the docs top to bottom. I'll try modeling some of the poker concepts in it after that.

9:20am. Let me chill a little first. The best thing in life are surely Ritz threads on /a/. Though work is important, I should not avert my eyes from the things that make life worth living.

9:55am. Let me resume. I'll go through the docs.

http://www.zenna.org/Omega.jl/latest/

Right now I am waiting for it to install. It seems to have been thoroughly documented.

10am. It has a bunch of dependencies it needs to install first.

Ok, at least with Julia I'll be able to do DL if I want it later. I can always just implement the poker game on it. It is no problem. I'd take it more seriously as a language if it had TCO and pattern matching, but those are not deal breakers.

I'll do anything if I could push my general 2/5 ML score higher. It really taking a while to precompile Omega for some reason. It is the last package in the sequence, and it has been stuck at 98/99 for over a minute.

10:05am. Wow it is still precompiling it. I'll give it a try for 10m more. I hope it did not get stuck due to me not using the LTS version of Julia.

10:15am. Holy shit, is it still installing. Is there something wrong going on under the hood?

```
  ✗ Omega
  98 dependencies successfully precompiled in 1106 seconds
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
```

Oh it just finished with an error.

```
julia> using Omega
[ Info: Precompiling Omega [1af16e33-887a-59b3-8344-18f1671b3ade]
ERROR: LoadError: LoadError: LoadError: UndefVarError: TrackedArray not defined
Stacktrace:
  [1] getproperty(x::Module, f::Symbol)
    @ Base .\Base.jl:26
  [2] top-level scope
    @ C:\Users\Marko\.julia\packages\Omega\zOdli\src\space\simple.jl:55
  [3] include(mod::Module, _path::String)
    @ Base .\Base.jl:386
  [4] include(x::String)
    @ Omega.Space C:\Users\Marko\.julia\packages\Omega\zOdli\src\space\Space.jl:1
  [5] top-level scope
    @ C:\Users\Marko\.julia\packages\Omega\zOdli\src\space\Space.jl:28
  [6] include(mod::Module, _path::String)
    @ Base .\Base.jl:386
  [7] include(x::String)
    @ Omega C:\Users\Marko\.julia\packages\Omega\zOdli\src\Omega.jl:2
  [8] top-level scope
    @ C:\Users\Marko\.julia\packages\Omega\zOdli\src\Omega.jl:22
  [9] include
    @ .\Base.jl:386 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base .\loading.jl:1235
 [11] top-level scope
    @ none:1
 [12] eval
    @ .\boot.jl:360 [inlined]
 [13] eval(x::Expr)
    @ Base.MainInclude .\client.jl:446
 [14] top-level scope
    @ none:1
in expression starting at C:\Users\Marko\.julia\packages\Omega\zOdli\src\space\simple.jl:55
in expression starting at C:\Users\Marko\.julia\packages\Omega\zOdli\src\space\Space.jl:1
in expression starting at C:\Users\Marko\.julia\packages\Omega\zOdli\src\Omega.jl:1
ERROR: Failed to precompile Omega [1af16e33-887a-59b3-8344-18f1671b3ade] to C:\Users\Marko\.julia\compiled\v1.6\Omega\jl_C4D3.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1385
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1329
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1043
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:936
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:923
```

I have no idea. I guess I'll open an issue on the Omega repo.

Let's see, I have Julia 1.6.2.

10:25am. https://github.com/zenna/Omega.jl/issues/

I opened issue 164. Zenna is pretty active here so I'll get a reply from him soon enough. For now, I might as well read the tutorial even if I cannot try things out directly. Maybe I'll try uninstalling Julia and installing the 1.0 version of it. When you try to switch versions, that is just tempting fate, I know that well enough. But I can't help but to gamble in these situations.

```julia
x =~ rng -> rand(rng) > 0.5 ? rand(rng)^2 : sqrt(rand(rng))
y = normal(0.0, 1.0)
z = x + y
```

What are these operators? I am guessing that `=~` user defined, but is `->` how Julia defines lambdas?

10:35am. Instead of waiting for him to reply, let me get rid of 1.6 and install 1.0.

https://docs.julialang.org/en/v1/manual/functions/#man-anonymous-functions

Yeah, this is it.

10:40am. This time I did not get an error when adding Omega. I'll see whether it manages to precompile it.

10:45am.

```
julia> using Omega
[ Info: Precompiling Omega [1af16e33-887a-59b3-8344-18f1671b3ade]
WARNING: Method definition adjoint(ZygoteRules.AContext, typeof(Base.conj), Number) in module Zygote at C:\Users\Marko\.julia\packages\Zygote\YeCEW\src\lib\number.jl:18 overwritten at C:\Users\Marko\.julia\packages\Zygote\YeCEW\src\lib\number.jl:71.
WARNING: Method definition _pullback(ZygoteRules.AContext, typeof(Base.conj), Number) in module Zygote at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:57 overwritten at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:57.
WARNING: Method definition _pullback(ZygoteRules.AContext, getfield(Base, Symbol("#kw##conj")), Any, typeof(Base.conj), Number) in module Zygote at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:63 overwritten at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:63.
WARNING: Method definition adjoint(ZygoteRules.AContext, typeof(Base.conj), Number) in module Zygote at C:\Users\Marko\.julia\packages\Zygote\YeCEW\src\lib\number.jl:18 overwritten at C:\Users\Marko\.julia\packages\Zygote\YeCEW\src\lib\number.jl:71.
WARNING: Method definition _pullback(ZygoteRules.AContext, typeof(Base.conj), Number) in module Zygote at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:57 overwritten at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:57.
WARNING: Method definition _pullback(ZygoteRules.AContext, getfield(Base, Symbol("#kw##conj")), Any, typeof(Base.conj), Number) in module Zygote at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:63 overwritten at C:\Users\Marko\.julia\packages\ZygoteRules\OjfTt\src\adjoint.jl:63.
[ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
```

Hmm, I think this worked. Let me try out some examples.

```jl
rand(normal(0.0, 1.0))
```

Yeah, it works. Those warnings worry me a bit.

10:55am.

```
julia> x_(Base.Random.GLOBAL_RNG)
ERROR: UndefVarError: Random not defined
```

This part is not working for me.

11am. Instead of doing things in the Repl, let me install the VS Code plugin.

11:05am. Yeah, it works nicely.

11:10am.

```jl
using Omega
using Random
x_(rng) = rand(rng) > 0.5
x_(Random.GLOBAL_RNG)
```

This is fine.

For some reason Random is not in Base, but is a separate package.

http://www.zenna.org/Omega.jl/dev/model/

I guess I'll open issues for the docs as I go along.

11:20am. Opened a PR. That is one way to get familiar with the library.

Let me also fix that minor grammar error that I found before. I'll do the chores after that.

```
However, in order to use x for conditional or causal inference we must turn it into a RandVar. One way to do this (we discuss others in [conditonalindependence]) is using ~.
```

Here a link is missing, but that is not the typo. I forgot where I saw it.

http://www.zenna.org/Omega.jl/latest/conditionalindependence/

11:40am. Let me backtrack just a bit.

```jl
using Omega
using UnicodePlots

weight = β(2.0, 2.0)
beta_samples = rand(weight, 10000)
UnicodePlots.histogram(beta_samples)
```
```
              ┌                                        ┐
   [0.0, 0.1) ┤▇▇▇▇▇▇ 279
   [0.1, 0.2) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 730
   [0.2, 0.3) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 1089
   [0.3, 0.4) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 1447
   [0.4, 0.5) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 1494
   [0.5, 0.6) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 1462
   [0.6, 0.7) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 1385
   [0.7, 0.8) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 1066
   [0.8, 0.9) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 769
   [0.9, 1.0) ┤▇▇▇▇▇▇ 279
              └                                        ┘
                              Frequency
```

Cute. In the REPL the plots are colored.

12:05pm. Did some editing of the documentation. This is best done during the first pass. Later, I'll have forgetten the issues.

Let me stop here for breakfast. My goal for the day will be to go through the tutorials for this. After that I'll use the library to try to do a no-NN run for the poker agent. This is also good prep if Zenna ever decided to send part time work my way."