"> Changing a property during the update (up to and including the render() method) updates the changedProperties map, but doesn't trigger a new update. Changing a property after render() (for example, in the updated() method) triggers a new update cycle, and the changed property is added to a new changedProperties map to be used for the next cycle.
Hmm, I see.

I think I should do my initialization in first updated then.

11:15 AM. https://youtu.be/IgOLBR9bHhE?list=PLZOToVAK85MpKG0JczY6PhM6yjFYsvzwD&t=452

My plan yesterday was to get started on those good libraries, but what I really want to do is do some studying content security policies as well as web security. The way flask works is different. How asp .net worked So I want to educate myself a bit more about this.

https://youtu.be/IgOLBR9bHhE?list=PLZOToVAK85MpKG0JczY6PhM6yjFYsvzwD&t=452

I think since we are using nonsense for a script, I don't think we need such a very restrictive policy regarding libraries.

https://youtu.be/TO7pmkMh1Tg?list=PLZOToVAK85MpKG0JczY6PhM6yjFYsvzwD&t=10

Is that how it looks? This is very sweet word. Amite wasn't really paying attention to it before. This is also so different from CORS.

```
cupy.cuda.compiler.CompileException: `nvcc` command returns non-zero exit status.
command: ['C:\\Program', 'Files\\NVIDIA', 'GPU', 'Computing', 'Toolkit\\CUDA\\v12.2\\bin\\nvcc.EXE', '-gencode=arch=compute_89,code=sm_89', '--cubin', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include', '-IC:\\Users\\mrakg\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-IC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.2\\include', '-ftz=true', 'C:\\Users\\mrakg\\AppData\\Local\\Temp\\tmp4k4qcdwa\\961a930d724b6ec9a952c2fb43021cc2d21444b1.cu']
return-code: 2
stdout/stderr:
C:\Users\mrakg\AppData\Local\Temp\tmp4k4qcdwa\961a930d724b6ec9a952c2fb43021cc2d21444b1.cu(8): fatal error C1083: Cannot open include file: 'mylib.h': No such file or directory
961a930d724b6ec9a952c2fb43021cc2d21444b1.cu
```

OK, now what I have to do is figure out how to include the libraries.

https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#command-option-description

Well, you can see right there how the Cuda Libraries themselves are being included.

///

CuPy is a Python library that allows you to use CUDA functions and kernels on GPU arrays. To include a 3rd party CUDA library with your CuPy program, you need to do the following steps:

- Install the 3rd party library and make sure it is compatible with your CUDA version and CuPy installation.
- Use the `-I` option of `nvcc` to specify the path to the header files of the 3rd party library. For example, if you want to use the oHNet library, you can write `nvcc -I/usr/local/include/oHNet -c your_program.cu`.
- Use the `-L` option of `nvcc` to specify the path to the library files of the 3rd party library. For example, if you want to use the oHNet library, you can write `nvcc -L/usr/local/lib -loHNet -o your_program`.
- Import the CuPy module in your Python code and use the `cupy.RawModule` or `cupy.RawKernel` classes to load and execute your CUDA code. See [CuPy documentation](^6^) for more details and examples.

I hope this helps you with your CuPy project. 😊

Source: Conversation with Bing, 1/2/2024
(1) undefined. https://docs-cupy.chainer.org/en/stable/install.html.
(2) How to run python on GPU with CuPy? - Stack Overflow. https://stackoverflow.com/questions/60027446/how-to-run-python-on-gpu-with-cupy.
(3) Does cupy automatically use cuda and the gpu? - Stack Overflow. https://stackoverflow.com/questions/56157018/does-cupy-automatically-use-cuda-and-the-gpu.
(4) How to use CuPy's headers in a CUDA file? #2530 - GitHub. https://github.com/cupy/cupy/issues/2530.
(5) c++ - how to #include third party libraries - Stack Overflow. https://stackoverflow.com/questions/17887265/how-to-include-third-party-libraries.
(6) cupy/cupy - Docker Image | Docker Hub. https://hub.docker.com/r/cupy/cupy/.

///

5:30 PM. https://stackoverflow.com/questions/77747360/how-do-i-include-cutlass-in-a-cupy-project

As usual, I'm Having trouble, including C++ libraries in the project.

I'm going to stop here for the day. My hand feels like it is falling off. It's definitely numb. I guess this really is carpal tunnel. But the EMG didn't come out Poorly. Will this really heal just by itself? I'm not sure. And probably fact, but whatever. It feels like lack definitely isn't on my side in this timeline."