"9:40am. Let me chill a bit and then I will try changing the boot record. Since I haven't received a reply thus far, I think by this point getting anything out of the UPMEM dev is hopeless. I really hate it when people say they will do something for you and then ghost after it looks like it will be more than 10m of work.
Forget it. The final part of the article I will write is going to be a takedown of UPMEM's poor architecture. It is up to me whether I want to give them a grace period to correct it or not, but at this point I do not owe the company anything. I've shown a lot of energy and the dev I've been contacted by 0. At some point you have to stop hoping the other party will turn up.

My main theory is that my questioning style ended up offending him, and he scuttled. Some people operate on a script and when things diverge from their expectations they act like robots and close the channel instead using their brain. I can only shrug at this. What can you do? Social skills aren't my forte.

10:10am. Let me try changing the boot record.

https://www.diskpart.com/articles/unallocated-space-cannot-create-partition-6289.html

I found this link a couple of days ago. It has a program that could do it without me having to wipe the whole drive.

> Method 2. Convert MBR to GPT via partition software (Data Safe)
> Since changing MBR to GPT using Disk Management causes data loss,  it is a wise move to employ third-party partition software. In such cases, the AOMEI Partition Assistant Professional is one ideal choice. It helps you directly convert MBR to GPT without deleting any partitions or data and then perfectly solve “unallocated space cannot create partition”  Let’s see how it works.

10:15am. Ok, here goes nothing. If this fails I'll lose e: . A lot of stuff on it has sentimental value, but not too much practical one. My most important property is the Spiral Language and that thing is safely away on Github. The old arcs of Simulacrum are online as well as my Google Drive.

Let me try it.

> The system partition and the boot partition are separated on different disks. If you convert the disk, your system will be unable to boot next time. So we strongly suggest you don't convert this disk.

I guess there goes this plan. But could I create a partition of the unallocated space?

> Cannot create new partition here, because the disk space is over 2TB and it is unable to use for this MBR disk. We suggest you convert the disk to GPT style, for using this disk space.

Hmmm...not what I expected. I can't make use of the unallocated space at all. Right now my e: is at only 2% and once it falls down even lower, I am going to have to erase some old stuff.

Sigh.

Well, erasing some of my old anime I will never watch again is no big deal. That same goes for saved anime images. I just collect them like an addict, but never is there a time where I will look at them again. I made a mistake 8.5 years ago when I got this computer of not going with GPT right away. But I didn't know this would be an issue. I thought I would be able to extend the partition when the time came.

Well, there is no way around it. Let me see if I can do anything with WSL. If that fails I will try the cloud route. Those Amazon free tiers would be perfect for something like this. I also have Paperscape, but I do not know which Linux distro they have.

https://learn.microsoft.com/en-us/windows/wsl/install

```
PS E:\> wsl
Windows Subsystem for Linux is now available in the Microsoft Store!
You can upgrade by running 'wsl.exe --update' or by visiting https://aka.ms/wslstorepage
Installing WSL from the Microsoft Store will give you the latest WSL updates, faster.
For more information please visit https://aka.ms/wslstoreinfo

Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Dec 24 10:28:59 CET 2022

  System load:  0.0                Processes:             8
  Usage of /:   4.0% of 250.98GB   Users logged in:       0
  Memory usage: 1%                 IPv4 address for eth0: 172.29.46.167
  Swap usage:   0%

12 updates can be installed immediately.
0 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update

This message is shown once a day. To disable it please create the
/home/mrakgr/.hushlogin file.
mrakgr@Lain:/mnt/e$
```

Kek, what the hell, I have it installed! Why did I bother downloading that 3gb Ubuntu Desktop ISO? Let me erase it.

```
mrakgr@Lain:~$ dir
open_spiel  spiral
```

Ah, I remember. I was playing with the Deeping OpenSpiel library years ago and never touched it again afterwards. I should have VS Code installed on this as well.

...Got rid of that.

Good.

https://sdk.upmem.com/

Here are the binaries. Er how am I supposed to install it?

https://sdk.upmem.com/2021.4.0/00_ToolchainAtAGlance.html

https://sdk.upmem.com/2021.4.0/01_Install.html#installation-from-tar-gz-binary-archive

http://sdk-releases.upmem.com/2021.4.0/ubuntu_20.04/upmem-2021.4.0-Linux-x86_64.tar.gz

I guess I just have to wget this?

Now how do I untar this?

https://linuxhint.com/untar_files_linux/

```
mrakgr@Lain:~/upmem-sdk$ dir
upmem-2021.4.0-Linux-x86_64  upmem-2021.4.0-Linux-x86_64.tar.gz
mrakgr@Lain:~/upmem-sdk$ rm upmem-2021.4.0-Linux-x86_64.tar.gz
mrakgr@Lain:~/upmem-sdk$ mv upmem-2021.4.0-Linux-x86_64/ ..
mrakgr@Lain:~/upmem-sdk$ dir
mrakgr@Lain:~/upmem-sdk$ cd ..
mrakgr@Lain:~$ dir
upmem-2021.4.0-Linux-x86_64  upmem-sdk
mrakgr@Lain:~$ rm upmem-sdk/
rm: cannot remove 'upmem-sdk/': Is a directory
mrakgr@Lain:~$ rm -r upmem-sdk/
mrakgr@Lain:~$ dir
upmem-2021.4.0-Linux-x86_64
mrakgr@Lain:~$ mv upmem-2021.4.0-Linux-x86_64/ upmem-sdk/
mrakgr@Lain:~$ dir
upmem-sdk
mrakgr@Lain:~$ dir
upmem-sdk
mrakgr@Lain:~$ cd upmem-sdk/
mrakgr@Lain:~/upmem-sdk$ dir
bin  include  lib  share  upmem_env.sh
mrakgr@Lain:~/upmem-sdk$ up
update-alternatives     update-locale           update-pciids           upnp.dll
update-binfmts          update-mime             update-rc.d             upnpcont.exe
update-ca-certificates  update-mime-database    updatecsp.dll           upnphost.dll
update-info-dir         update-motd             updatepolicy.dll        upshared.dll
update-initramfs        update-passwd           upfc.exe                uptime
mrakgr@Lain:~/upmem-sdk$ upmem_env.sh
upmem_env.sh: command not found
mrakgr@Lain:~/upmem-sdk$ ./upmem_env.sh
Setting UPMEM_HOME to /home/mrakgr/upmem-sdk and updating PATH/LD_LIBRARY_PATH/PYTHONPATH
```

Ok, after a bit of wrangling I've managed to put it all into place.

```
mrakgr@Lain:~/upmem-sdk$ python

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3

mrakgr@Lain:~/upmem-sdk$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

This is going to be trouble. But it does not matter too much unless I am using match cases, and I won't be using those during the testing of the UPMEM code.

Now how do I run those python scripts.

C:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\upmem_tests\test4

I have the test here.

C:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests/test4

Switch the \ to /.

Now...

```
mrakgr@Lain:/mnt/c$ cd 'mnt/c/Users/Marko/Source/Repos/'
-bash: cd: mnt/c/Users/Marko/Source/Repos/: No such file or directory
mrakgr@Lain:/mnt/c$ cd 'mnt/c/'
-bash: cd: mnt/c/: No such file or directory
mrakgr@Lain:/mnt/c$ cd "mnt/c/"
-bash: cd: mnt/c/: No such file or directory
mrakgr@Lain:/mnt/c$ cd mnt/c/
-bash: cd: mnt/c/: No such file or directory
mrakgr@Lain:/mnt/c$ cd "/mnt/c/"
mrakgr@Lain:/mnt/c$ cd '/mnt/c/'
mrakgr@Lain:/mnt/c$ cd '/mnt/c/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests/test4'
mrakgr@Lain:/mnt/c/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests/test4$
```

I am relatively new to Linux. Now...

```
mrakgr@Lain:/mnt/c/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests/test1$ python3 main.py

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
int32_t main(){
    int v0[1];
    return 0l;
}
```

Does this mean it works. Let me try it from VS Code.

```
mrakgr@Lain:/mnt/c/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests$ code .
Updating VS Code Server to version e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Removing previous installation...
Installing VS Code Server for x64 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161)
Downloading:  39%
```

It is nice enough to update itself.

> This workspace is on the Windows file system (/mnt/). For best performance, we recommend moving the workspace to the Linux file system (~/home).

I can ignore this.

> Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.

```
from dpu import DpuSet
```

I had to add this, but it is not taking notice of the library.

11:05am.

```bash
mrakgr@Lain:/mnt/c/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests/test1$ ~/upmem-sdk/upmem_env.sh
Setting UPMEM_HOME to /home/mrakgr/upmem-sdk and updating PATH/LD_LIBRARY_PATH/PYTHONPATH
mrakgr@Lain:/mnt/c/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests/test1$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from dpu import DpuSet
ModuleNotFoundError: No module named 'dpu'
mrakgr@Lain:/mnt/c/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/upmem_tests/test1$ dpu-upmem-dpurte-clang -o helloworld helloworld.c
dpu-upmem-dpurte-clang: command not found
```

11:10am. https://sdk.upmem.com/2021.4.0/01_Install.html

I am drawing a blank here. I am going to have to ask somewhere as to how to proceed.

mrakgr@Lain:~/upmem-sdk/bin$ dir
clang         clangd     dpu-lldb-attach-dpu               dpu-upmem-dpurte-clang  dpurtldoc  gen_spd.py  lldb             llvm-ar         llvm-link     llvm-objdump  upmem-dimm-configure.py
clang++       dpu-clang  dpu-pkg-config                    dpu_stack_analyzer      dputrace   ld.lld      lldb-argdumper   llvm-as         llvm-mc       llvm-readelf
clang-12      dpu-diag   dpu-profiling                     dpuasmdoc               ectool     llc         lldb-server      llvm-dis        llvm-nm       llvm-readobj
clang-format  dpu-lldb   dpu-profiling-memory-transfer.sh  dpugrind                gen_db.py  lld         lldb-server-dpu  llvm-dwarfdump  llvm-objcopy  opt

```
mrakgr@Lain:~/upmem-sdk/bin$ echo $PATH
/home/mrakgr/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/remote-cli:/home/mrakgr/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/Marko/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/Marko/AppData/Local/Programs/Python/Python311/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/dotnet/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/150/DTS/Binn/:/mnt/c/Program Files/erl-24.1.7/bin:/mnt/c/Program Files (x86)/Elixir/bin:/mnt/c/Program Files (x86)/Calibre2/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/nodejs/:/mnt/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn/:/mnt/c/Program Files/Azure Data Studio/bin:/mnt/c/Program Files/Amazon/AWSCLIV2/:/mnt/c/Users/Marko/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Marko/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/Marko/.dotnet/tools:/mnt/c/Users/Marko/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Marko/AppData/Local/Programs/Julia-1.6.2/bin:/mnt/c/Users/Marko/AppData/Roaming/npm:/mnt/c/Program Files/Azure Data Studio/bin:/snap/bin:/home/mrakgr/.dotnet/tools
```

Why is upmem not in PATH?

Let me check out the shell file that is suppose to configure then environment.

```
mrakgr@Lain:~/upmem-sdk$ more upmem_env.sh
#!/bin/bash

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")")"

export UPMEM_HOME="${SCRIPT_DIR}"
echo "Setting UPMEM_HOME to ${UPMEM_HOME} and updating PATH/LD_LIBRARY_PATH/PYTHONPATH"
export LD_LIBRARY_PATH="${UPMEM_HOME}/lib${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"
export PATH="${UPMEM_HOME}/bin:${PATH}"

PYTHON_RELATIVE_PATH=lib/python3/dist-packages

export PYTHONPATH="${UPMEM_HOME}/${PYTHON_RELATIVE_PATH}${PYTHONPATH+:$PYTHONPATH}"

_DEFAULT_BACKEND=$1

if [[ -n "${_DEFAULT_BACKEND}" ]];
then
    echo "Setting default backend to ${_DEFAULT_BACKEND} in UPMEM_PROFILE_BASE"
    export UPMEM_PROFILE_BASE=backend=${_DEFAULT_BACKEND}
fi
```

Hmmm...

```
mrakgr@Lain:~/upmem-sdk$ echo $UPMEM_HOME
```

I know I ran this. So why is nothing showing up?

```
mrakgr@Lain:~$ cd upmem-sdk/
mrakgr@Lain:~/upmem-sdk$ dir
bin  include  lib  share  upmem_env.sh
mrakgr@Lain:~/upmem-sdk$ more upmem_env.sh
#!/bin/bash

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")")"

export UPMEM_HOME="${SCRIPT_DIR}"
echo "Setting UPMEM_HOME to ${UPMEM_HOME} and updating PATH/LD_LIBRARY_PATH/PYTHONPATH"
export LD_LIBRARY_PATH="${UPMEM_HOME}/lib${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"
export PATH="${UPMEM_HOME}/bin:${PATH}"

PYTHON_RELATIVE_PATH=lib/python3/dist-packages

export PYTHONPATH="${UPMEM_HOME}/${PYTHON_RELATIVE_PATH}${PYTHONPATH+:$PYTHONPATH}"

_DEFAULT_BACKEND=$1

if [[ -n "${_DEFAULT_BACKEND}" ]];
then
    echo "Setting default backend to ${_DEFAULT_BACKEND} in UPMEM_PROFILE_BASE"
    export UPMEM_PROFILE_BASE=backend=${_DEFAULT_BACKEND}
fi
mrakgr@Lain:~/upmem-sdk$ echo $UPMEM_HOME

mrakgr@Lain:~/upmem-sdk$ echo $UPMEM_HOMEe

mrakgr@Lain:~/upmem-sdk$ ./upmem_env.sh
Setting UPMEM_HOME to /home/mrakgr/upmem-sdk and updating PATH/LD_LIBRARY_PATH/PYTHONPATH
mrakgr@Lain:~/upmem-sdk$ echo $UPMEM_HOME

mrakgr@Lain:~/upmem-sdk$
```

I have no idea. I am going to have to ask, maybe on SO.

...Before that, let me try making my own script just to make sure that export works.

```bash
#!/bin/bash

export TEST_EXPORT="HELLO"
```

I put this into a script file.

```
mrakgr@Lain:~/upmem-sdk$ ./test_export.sh
-bash: ./test_export.sh: Permission denied
mrakgr@Lain:~/upmem-sdk$ sudo ./test_export.sh
sudo: ./test_export.sh: command not found
```

Ugh. I think the reason the exports are not working due to me being in admin mode.

https://stackoverflow.com/questions/59744790/bash-wsl-how-to-run-command-as-root

> wsl -u root

You know what, fuck this. Let me try running wsl as per above.

```
root@Lain:/home/mrakgr/upmem-sdk# ./test_export.sh
-bash: ./test_export.sh: Permission denied
```

My god!

11:55am. Had to take a short break.

```
root@Lain:/home/mrakgr/upmem-sdk# export TEST_EXPORT="HELLO"
root@Lain:/home/mrakgr/upmem-sdk# echo $TEST_EXPORT
HELLO
```

Anyway this works.

12pm. I have no choice, let me ask on SO.

12:30pm.

///

I am working on an [UPMEM](https://www.upmem.com/) device backend for [my PL Spiral](https://github.com/mrakgr/The-Spiral-Language). I've followed [the instructions](https://sdk.upmem.com/2021.4.0/01_Install.html#installation-from-tar-gz-binary-archive) and extracted the files. When I run the `$HOME/upmem-sdk/upmem_env.sh` file it seems to work, but the compiler (and Python libraries) are not in `PATH` when I echo them. Here is the script file.

```bash
#!/bin/bash

SCRIPT_DIR="$(readlink -f "$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")")"

export UPMEM_HOME="${SCRIPT_DIR}"
echo "Setting UPMEM_HOME to ${UPMEM_HOME} and updating PATH/LD_LIBRARY_PATH/PYTHONPATH"
export LD_LIBRARY_PATH="${UPMEM_HOME}/lib${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}"
export PATH="${UPMEM_HOME}/bin:${PATH}"

PYTHON_RELATIVE_PATH=lib/python3/dist-packages

export PYTHONPATH="${UPMEM_HOME}/${PYTHON_RELATIVE_PATH}${PYTHONPATH+:$PYTHONPATH}"

_DEFAULT_BACKEND=$1

if [[ -n "${_DEFAULT_BACKEND}" ]];
then
    echo "Setting default backend to ${_DEFAULT_BACKEND} in UPMEM_PROFILE_BASE"
    export UPMEM_PROFILE_BASE=backend=${_DEFAULT_BACKEND}
fi
```

```
mrakgr@Lain:~/upmem-sdk$ ./upmem_env.sh
Setting UPMEM_HOME to /home/mrakgr/upmem-sdk and updating PATH/LD_LIBRARY_PATH/PYTHONPATH
mrakgr@Lain:~/upmem-sdk$ echo $UPMEM_HOME

mrakgr@Lain:~/upmem-sdk$
```

I am not familiar with Linux so I tried making a shell file just to see whether exports work.

```bash
#!/bin/bash

export TEST_EXPORT="HELLO"
```

Then I tried running it.

```
mrakgr@Lain:~/upmem-sdk$ ./test_export.sh
-bash: ./test_export.sh: Permission denied
mrakgr@Lain:~/upmem-sdk$ sudo ./test_export.sh
sudo: ./test_export.sh: command not found
```

Since I `sudo` was not working on the shell script and an googling for how to make it happen failed me, I instead closed the WSL and logged in a root by running `wsl -u root`, but am getting the same problem.

```
root@Lain:/home/mrakgr/upmem-sdk# ./test_export.sh
-bash: ./test_export.sh: Permission denied
```

```
root@Lain:/home/mrakgr/upmem-sdk# ./upmem_env.sh
Setting UPMEM_HOME to /home/mrakgr/upmem-sdk and updating PATH/LD_LIBRARY_PATH/PYTHONPATH
root@Lain:/home/mrakgr/upmem-sdk# echo $UPMEM_HOME

```

As you can see, I tried running `upmem_env.sh`, but nothing shows up in `UPMEM_HOME`.

I am running Ubuntu 20.04.1 from WSL. I need to do test it in WSL because I am working on the compiler in Visual Studio, and it would be too tedious to keep switching back and forth between Linux and Windows otherwise. I am developing the language on Windows, but the [UPMEM toolchain](https://sdk.upmem.com/) has only Linux binaries.

As an aside, the instructions specifically state this:

> Source the script `$HOME/upmem-sdk/upmem_env.sh` to set environment variables to appropriate values.

Does sourcing the script mean something different from just running it?

///

Seems good. Let me post it.

12:35pm. https://stackoverflow.com/questions/74907373/why-does-exporting-variables-in-a-shell-script-not-work

I guess I'll close the morning session here. Until I get this to run, maybe I should take a break and write Heaven's Key? SO has been good at giving me answers for these types of questions, but it might take time to get it resolved.

Let me have breakfast and do the chores here."