"1:50pm. Let me do the chores here.
2:10pm. Done. Let me start programming.

Today my goal is to push through the obstacles and get the net to train against the static uniform player. Focus me. Katahane No Ruku can wait for when the day is over.

```
    inl opt : obj = $"torch.optim.SGD([{'params':!value.parameters()}],lr=2 ** -3)"
    loopw.for' (from: 0i32 nearTo: 10) fun _ =>
        $"!opt.zero_grad()"
        $"print(!value[0].bias.grad)"
        inl r = train.vs_one 1024 (agent.neural.policy 0 net) agent.uniform.policy game
        $"print(!value[0].bias.grad)"
        $"!opt.step()"
```

Let me try this. Is the gradient being zeroed out?

The most sensible explanation for the error that is occuring is that I am passing the wrong parameters into the optimizer, but I don't see how I could possible get that wrong here.

If the grad is not being zeroed out then, the optimizer is not looking at the right things. If it is, then I just have no idea what my next move will be.

```
tensor([0., 0., 0.])
tensor([ 5.0409e+02, -1.0267e+03,  1.0254e+00])
tensor([0., 0., 0.])
tensor([  180.5195, -1093.8445,   -96.7939])
```

Yes, this seems right.

```
        $"print(!value[0].bias.grad)"
        $"!opt.zero_grad()"
        $"print(!value[0].bias.grad)"
```

Let me try this.

```
tensor([  -3.2369, -784.5806,  242.5038])
tensor([0., 0., 0.])
tensor([ 390.1413, -725.9543,  810.8793])
tensor([0., 0., 0.])
```

Yes, it is handling the gradients properly. This means it can see the params.

2:20pm. https://discuss.pytorch.org/t/model-weights-not-being-updated/1842/6

There seems to be some decent advice here. It never occured to me to try turning the parameters into a list.

```
        inl q1 : obj = $"list(!value.parameters())[0].clone()"
        inl r = train.vs_one 1024 (agent.neural.policy 0 net) agent.uniform.policy game
        $"!opt.step()"
        inl q2 : obj = $"list(!value.parameters())[0].clone()"
        $"torch.equal(!q1,!q2)"
```

Let me try this.

```
        $"print(list(!value.parameters())[1].grad)"
        inl r = train.vs_one 1024 (agent.neural.policy 0 net) agent.uniform.policy game
        $"!opt.step()"
        $"print(list(!value.parameters())[1].grad)"
```

What does this give me?

```
None
tensor([-600.2689, -962.0649, -203.6064])
tensor([0., 0., 0.])
tensor([ -675.3747, -1018.5420,   -68.2647])
tensor([0., 0., 0.])
tensor([-361.2878, -911.5947,   59.6618])
```

The gradients are there.

2:35pm. I am thinking. Just what is wrong with the optimizer.

```
inl main () =
    !!!!Import("torch")
    !!!!Import("torch.distributions")
    !!!!Import("torch.optim")
    inl game = leduc.game()
    inl net = agent.neural.create_small_leduc_net()
    inl policy,value = agent.neural.models net
    // inl opt : obj = $"torch.optim.SGD([{'params':!policy.parameters()},{'params':!value.parameters()}],lr=2 ** -10)"
    inl opt : obj = $"torch.optim.SGD([{'params':!value.parameters()}],lr=2 ** -3)"
    loopw.for' (from: 0i32 nearTo: 3) fun _ =>
        $"!opt.zero_grad()"
        $"print(list(!value.parameters())[1].grad)"
        inl r = train.vs_one 1024 (agent.neural.policy 0 net) agent.uniform.policy game
        $"!opt.step()"
        $"print(list(!value.parameters())[1].grad)"
        // inl mean : f32 = $"numpy.mean(!r)"
        // $"print(!mean)"
    ()
```

Let me get rid of the game. I'll clone the bias and put in the gradients onto it directly.

```
inl main () =
    !!!!Import("torch")
    !!!!Import("torch.distributions")
    !!!!Import("torch.optim")
    inl net = agent.neural.create_small_leduc_net()
    inl policy,value = agent.neural.models net
    inl opt : obj = $"torch.optim.SGD([{'params':!value.parameters()}],lr=2 ** -3)"
    $"!opt.zero_grad()"
    $"list(!value.parameters())[1].clone().backward(torch.tensor([1,2,3]))"
    $"!opt.step()"
    $"print(list(!value.parameters())[1])"
```

What happens when I try this?

```
inl main () =
    !!!!Import("torch")
    !!!!Import("torch.distributions")
    !!!!Import("torch.optim")
    inl net = agent.neural.create_small_leduc_net()
    inl policy,value = agent.neural.models net
    inl opt : obj = $"torch.optim.SGD([{'params':!value.parameters()}],lr=2 ** -3)"
    $"!opt.zero_grad()"
    $"list(!value.parameters())[1].clone().backward(torch.tensor([1,2,3]))"
    $"print(list(!value.parameters())[1].grad)"
    $"print(list(!value.parameters())[1])"
    $"!opt.step()"
    $"print(list(!value.parameters())[1])"
    ()
```

This does nothing. How strange. But at least now I've narrowed it down. Let me implement the thing above in a script.

2:45pm.

```py
import torch
import torch.optim
import torch.functional
import torch.nn
import torch.nn.functional
import torch.distributions
import numpy as np
import nets

value = nets.small(4,5,3)
opt = torch.optim.SGD([{'params':value.parameters()}],lr=2 ** -3)
opt.zero_grad()
list(value.parameters())[1].clone().backward(torch.tensor([1,2,3]))
print(list(value.parameters())[1].grad)
print(list(value.parameters())[1])
opt.step()
print(list(value.parameters())[1])
```

```
>>> print(list(value.parameters())[1])
Parameter containing:
tensor([ 0.2125,  0.3055, -0.0345], requires_grad=True)
>>> opt.step()
>>> print(list(value.parameters())[1])
Parameter containing:
tensor([ 0.0875,  0.0555, -0.4095], requires_grad=True)
```

This in fact works. I do not get it. Let me make the Spiral example just like this one.

```
inl main () =
    !!!!Import("torch")
    !!!!Import("torch.optim")
    !!!!Import("nets")
    inl value : obj = $"nets.small(4,5,3)"
    inl opt : obj = $"torch.optim.SGD([{'params':!value.parameters()}],lr=2 ** -3)"
    $"!opt.zero_grad()"
    $"list(!value.parameters())[1].clone().backward(torch.tensor([1,2,3]))"
    $"print(list(!value.parameters())[1].grad)"
    $"print(list(!value.parameters())[1])"
    $"!opt.step()"
    $"print(list(!value.parameters())[1])"
    ()
```

Let me try compiling and running this.

```
tensor([1., 2., 3.])
Parameter containing:
tensor([ 0.1740,  0.4621, -0.0847], requires_grad=True)
Parameter containing:
tensor([ 0.1740,  0.4621, -0.0847], requires_grad=True)
```

The Spiral's compiled example clearly has different behavior. What code got generated?

```
import torch
import torch.optim
import nets
cpdef void main() except *:
    cdef object v0
    cdef object v1
    pass # import torch
    pass # import torch.optim
    pass # import nets
    v0 = nets.small(4,5,3)
    v1 = torch.optim.SGD([{'params':v0.parameters()}],lr=2 ** -3)
    v1.zero_grad()
    list(v0.parameters())[1].clone().backward(torch.tensor([1,2,3]))
    print(list(v0.parameters())[1].grad)
    print(list(v0.parameters())[1])
    v1.step()
    del v1
    print(list(v0.parameters())[1])
```

This seems fine. Let me remove that del.

```
import torch
import torch.optim
import nets
cpdef void main() except *:
    v0 = nets.small(4,5,3)
    v1 = torch.optim.SGD([{'params':v0.parameters()}],lr=2 ** -3)
    v1.zero_grad()
    list(v0.parameters())[1].clone().backward(torch.tensor([1,2,3]))
    print(list(v0.parameters())[1].grad)
    print(list(v0.parameters())[1])
    v1.step()
    print(list(v0.parameters())[1])
```

Let me try running this. This feels like a Cython compiler bug at this point.

```
v1 = torch.optim.SGD([{'params':v0.parameters()}],lr=2 ** -3)
```

Let me print out this lr. It might be setting it to zero.

```
print(2 ** -3)
```

This prints zero. Motherfucker.

```
print(2.0 ** -3.0)
```

This is what I should have written.

https://groups.google.com/forum/#!topic/cython-users/goVpote2ScY

It turns out this was an issue from 10 years ago that still has not been fixed.

Oh, according to issue 3911 it is fixed in Cython 3. Great. I guess I don't have to open an issue for this.

How much time did waste for me today? At least 3 hours.

3:05pm. Let me backtrack.

```
$"print(torch.mean(!value_signal))"
```

Let me insert this again.

```
tensor(8850479.)
tensor(11469927.)
tensor(10205870.)
tensor(7675729.)
```

Whops, it is diverging.

```
inl lr : f32 = 2 ** -14 // Note: Be careful of Cython integer power bug. `integer ** negative_integer = 0` in raw Cython.
```

Let me try an even lower LR.

...The error just keeps getting worse. Don't tell me I got the LR wrong?

You know what, instead of those shitty inversions, how about I just pass in a negative LR?

```
inl pids : obj = am.generic.map (fun _,_,pid,_ => if pid = 0 then 1 else -1f32) l |> fun (x : a _ _) => $"torch.from_numpy(!x)"
```

Now I can remove the comment here.

```
inl lr : f32 = -(2 ** -14) // Note: Be careful of Cython integer power bug. `integer ** negative_integer = 0` in raw Cython.
```

Let me set it to this.

```
ValueError: Invalid learning rate: -6.0999998822808266e-05
```

Oh spare me.

```
$"!value_signal[!b,!a] -= !dif"
```

Let me invert this thing here then.

...Ah, yes this is right. Now it is not longer diverging.

```
inl lr : f32 = 2 ** -12 // Note: Be careful of Cython integer power bug. `integer ** negative_integer = 0` in raw Cython.
```

Let me increase the LR to this then. I get the sense that the results are too noisy. I should also put back the other layer.

```
def small(intro,mid,out): return torch.nn.Sequential(
    torch.nn.Linear(intro,mid),
    torch.nn.ReLU(),
    torch.nn.LayerNorm(mid),
    torch.nn.Linear(mid,out)
    )
```

With the second layer it nans out very quickly. Let me try lowering the LR again.

```
tensor(0.7482)
tensor(0.1318)
tensor(0.2248)
tensor(-0.2685)
tensor(0.0781)
tensor(-0.1102)
tensor(1.6884)
tensor(0.3052)
tensor(0.2805)
tensor(0.3191)
tensor(0.3342)
tensor(0.3984)
tensor(-1.6346)
tensor(-0.1245)
tensor(-0.2794)
tensor(-0.8469)
tensor(-0.6381)
tensor(-1.1076)
tensor(0.1529)
tensor(0.7255)
tensor(0.3051)
tensor(0.4964)
tensor(0.6852)
tensor(1.3762)
tensor(-1.9248)
tensor(-0.7197)
tensor(-0.0991)
tensor(-1.4755)
tensor(-0.8159)
tensor(-1.8359)
tensor(-0.7997)
tensor(1.3442)
tensor(0.4951)
tensor(1.9629)
tensor(1.3856)
tensor(3.6806)
tensor(-1.7714)
tensor(-0.8098)
tensor(-0.9032)
tensor(-2.9581)
tensor(-1.7303)
tensor(-3.1597)
tensor(2.9665)
tensor(4.0252)
tensor(3.1653)
tensor(9.0945)
tensor(6.2002)
tensor(12.3119)
tensor(429.0415)
tensor(304.9085)
tensor(267.5406)
tensor(756.2503)
tensor(592.1229)
tensor(1671.8174)
tensor(-1265921.7500)
tensor(-80897376.)
tensor(-49174088.)
tensor(-2.5296e+08)
tensor(-1.5730e+08)
tensor(-3.5933e+08)
tensor(-5.9446e+25)
tensor(-5.6057e+25)
tensor(-5.4558e+25)
tensor(-1.9741e+26)
tensor(-1.2534e+26)
tensor(-2.8744e+26)
tensor(nan)
```

It blows up, albeit a bit slower than before. Let me try lowering the lr even more that 2 ** -14.

```
tensor(0.1173)
tensor(-0.1827)
tensor(-0.0396)
tensor(-0.0719)
tensor(-0.7718)
tensor(-0.1772)
tensor(0.0823)
tensor(0.1742)
tensor(0.0051)
tensor(0.0519)
```

Now it is stable all the way. But no matter how you look at it, 2 ** -16 is too low for a learning rate. No doubt it diverges because the weights in the topmost layer grow large and start amplifying the gradients in the layers below.

I need to implement the gradient normalization idea I described in the monthly PL review in order to stabilize the situation.

I thought that things might be fine because I had LN between the two layers, but I was wrong.

///

1) Use the transformer architecture.
2) Implement the replay buffer and the training scheme I thought up using it.
3) Hack the linear so I keep track of the variances using moving averages.

///

I guess the last point will have to go first. At 2 ** -16 the net is worthless.

I might as well figure out how to hack the softmax while I am at it.

Plus keeping the moving average of the variances will be good for keeping track of NNs health.

3:35pm. Now focus me.

```
        inl pids : obj = am.generic.map (fun _,_,pid,_ => if pid = 0 then 1 else -1f32) l |> fun (x : a _ _) => $"torch.from_numpy(!x)"
        $"!policy_log_probs.backward(!pids.unsqueeze(-1) * (!means.unsqueeze(-1) - !value_sampled))"
```

Let me do this last change. It is better to have it like this, than to have to keep that comment.

Now...

Forget this for a while. Let me focus on figuring out how to hack the linear layer.

```py
class Linear(Module):
    r"""Applies a linear transformation to the incoming data: :math:`y = xA^T + b`

    This module supports :ref:`TensorFloat32<tf32_on_ampere>`.

    Args:
        in_features: size of each input sample
        out_features: size of each output sample
        bias: If set to ``False``, the layer will not learn an additive bias.
            Default: ``True``

    Shape:
        - Input: :math:`(N, *, H_{in})` where :math:`*` means any number of
          additional dimensions and :math:`H_{in} = \text{in\_features}`
        - Output: :math:`(N, *, H_{out})` where all but the last dimension
          are the same shape as the input and :math:`H_{out} = \text{out\_features}`.

    Attributes:
        weight: the learnable weights of the module of shape
            :math:`(\text{out\_features}, \text{in\_features})`. The values are
            initialized from :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})`, where
            :math:`k = \frac{1}{\text{in\_features}}`
        bias:   the learnable bias of the module of shape :math:`(\text{out\_features})`.
                If :attr:`bias` is ``True``, the values are initialized from
                :math:`\mathcal{U}(-\sqrt{k}, \sqrt{k})` where
                :math:`k = \frac{1}{\text{in\_features}}`

    Examples::

        >>> m = nn.Linear(20, 30)
        >>> input = torch.randn(128, 20)
        >>> output = m(input)
        >>> print(output.size())
        torch.Size([128, 30])
    """
    __constants__ = ['in_features', 'out_features']
    in_features: int
    out_features: int
    weight: Tensor

    def __init__(self, in_features: int, out_features: int, bias: bool = True) -> None:
        super(Linear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(torch.Tensor(out_features, in_features))
        if bias:
            self.bias = Parameter(torch.Tensor(out_features))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()

    def reset_parameters(self) -> None:
        init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in)
            init.uniform_(self.bias, -bound, bound)

    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)

    def extra_repr(self) -> str:
        return 'in_features={}, out_features={}, bias={}'.format(
            self.in_features, self.out_features, self.bias is not None
        )
```

Intellisense is really helpful here.

```py
def linear(input, weight, bias=None):
    # type: (Tensor, Tensor, Optional[Tensor]) -> Tensor
    r"""
    Applies a linear transformation to the incoming data: :math:`y = xA^T + b`.

    This operator supports :ref:`TensorFloat32<tf32_on_ampere>`.

    Shape:

        - Input: :math:`(N, *, in\_features)` N is the batch size, `*` means any number of
          additional dimensions
        - Weight: :math:`(out\_features, in\_features)`
        - Bias: :math:`(out\_features)`
        - Output: :math:`(N, *, out\_features)`
    """
    tens_ops = (input, weight)
    if not torch.jit.is_scripting():
        if any([type(t) is not Tensor for t in tens_ops]) and has_torch_function(tens_ops):
            return handle_torch_function(linear, tens_ops, input, weight, bias=bias)
    if input.dim() == 2 and bias is not None:
        # fused op is marginally faster
        ret = torch.addmm(bias, input, weight.t())
    else:
        output = input.matmul(weight.t())
        if bias is not None:
            output += bias
        ret = output
    return ret
```

I'll have to hack torch.addmm.

```py
...
@overload
def addmm(beta: Number, self: Tensor, alpha: Number, mat1: Tensor, mat2: Tensor, *, out: Tensor) -> Tensor: ...
@overload
def addmm(beta: Number, self: Tensor, mat1: Tensor, mat2: Tensor) -> Tensor: ...
@overload
def addmm(beta: Number, self: Tensor, mat1: Tensor, mat2: Tensor, *, out: Tensor) -> Tensor: ...
```

The problem is much like when I looked at the softmax, instead of giving me the source, it places me on these crappy overloads.

4:10pm. This will take a while. This is not the old Spiral library that I can just change whatever I want. I'll have to get familiar with how PyTorch works at a deeper level. Right now I am reading its source randomly.

4:15pm. My router is killing me. I can't click a link without the connection breaking. I have to keep pounding it just to get anywhere.

4:40pm. This is not working out for me. I need to fire up the Python debugger instead of blindly clicking through the source.

4:50pm. I am trying to do that, but the debugger keeps launching the wrong shell. I can't make it run the one that inits the Anaconda env first.

```
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
```

Can I edit that last one somehow?

```
"console": "externalTerminal"
```

Let me try this.

4:55pm. Nope. Let me just ask on SO.

///

I am trying to run a Python file in debug mode, and I get an error because the Powershell integrated terminal it starts is bare. To get it to work, I want it to use the following profile which initializes the Anaconda env first.

```
    "terminal.integrated.profiles.windows": {
        "PowerShell -conda": {
            "source": "PowerShell",
            "args": ["-ExecutionPolicy", "ByPass", "-NoExit", "-Command", "& 'C:/Users/Marko/anaconda3/shell/condabin/conda-hook.ps1' ; conda activate 'C:/Users/Marko/anaconda3'"]
            }
    },
    "terminal.integrated.defaultProfile.windows": "PowerShell -conda"
```

What should I do?

///

Actually this might be a better fit for the VS Code repo.

5:05pm. It just sent me back to SO.

https://stackoverflow.com/questions/67690696/how-to-make-the-python-debug-task-use-the-default-powershell-profile

Here is the question.

Without a debugger I won't be able to delve into the source.

Let me try reading the PyTorch docs. Though, I already went through that months ago and did not see anything too deep in them.

5:15pm. No there is nothing there on hacking the library to this degree.

5:20pm. Ah, what am I going to do? For once, maybe I should just call it a day early?

Seriously, just where are the PyTorch primitives?

5:30pm. Let me close here. I had enough. This is getting me nowhere. For such a popular framework there sure is a dearth of anything but dead basic tutorials. I'll have to ask questions. There might be some online chat I could use to get replies more quickly.

What I should start is figuring out how to init the gradients for my own backward pass.

https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html

Ah, it does not init them directly. It just returns the grad arrays. Ok.

I'll be able to make do with that for at least the linear layer even if I do not know where the primitives are just yet.

Ah, I had an idea. The primitives are probably forward and backward in functionals. I should test that theory, but not right now. Let me have lunch here and I'll call it a day."