"9:15am. I got up 10m ago.
Today is seems there is nothing interesting out. I just keep waiting and waiting for that Spec Ops Asuka chapter, but it won't come out. No progress on the SO question or the issue I opened. No upvote for that quick example that I did either. Lame.

Let me just go forward with my plan. For the next few weeks, my mission will be to figure out everything in the `jsonrpc` project. Since the thing is too complex, the best way to get a grasp on it is to rewrite it myself in F#. Doing that will force me to understand what every individual line is.

9:20am. Let me do it.

```
export enum Trace {
 Off, Messages, Verbose
}

export type TraceValues = 'off' | 'messages' | 'verbose';
export namespace Trace {
 export function fromString(value: string): Trace {
  if (!Is.string(value)) {
   return Trace.Off;
  }
  value = value.toLowerCase();
  switch (value) {
   case 'off':
    return Trace.Off;
   case 'messages':
    return Trace.Messages;
   case 'verbose':
    return Trace.Verbose;
   default:
    return Trace.Off;
  }
 }

 export function toString(value: Trace): TraceValues {
  switch (value) {
   case Trace.Off:
    return 'off';
   case Trace.Messages:
    return 'messages';
   case Trace.Verbose:
    return 'verbose';
   default:
    return 'off';
  }
 }
}
```

At the start there are a lot of imports. This is the first real function. A lot of the stuff in this module is due to TS's type unsafety. For example...

```
 export function fromString(value: string): Trace {
  if (!Is.string(value)) {
   return Trace.Off;
  }
```

Note how here it is checking whether the thing is really a string even though it says as much in the type annotation.

```
/* --------------------------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 * ------------------------------------------------------------------------------------------ */
'use strict';

export function boolean(value: any): value is boolean {
 return value === true || value === false;
}

export function string(value: any): value is string {
 return typeof value === 'string' || value instanceof String;
}

export function number(value: any): value is number {
 return typeof value === 'number' || value instanceof Number;
}

export function error(value: any): value is Error {
 return value instanceof Error;
}

export function func(value: any): value is Function {
 return typeof value  === 'function';
}

export function array<T>(value: any): value is T[] {
 return Array.isArray(value);
}

export function stringArray(value: any): value is string[] {
 return array(value) && (<any[]>value).every(elem => string(elem));
}
```

I certainly won't be needing the stuff in `is.ts` in the F# rewrite. Well, let me just go for it.

9:35pm.

```
  <ItemGroup>
    <Content Include="SpiralExperiments'.txt" />
    <Content Include="SpiralTypes'.txt" />
    <Content Include="SpiralTypes.txt" />
    <Compile Include="Program.fs" />
  </ItemGroup>
```

Oh, it is possible to include text files in F# projects. I just needed to change `Compile Include` to `Content Include`. Nice. Well, that is one thing down.

9:40am. Now...

```
export enum Trace {
 Off, Messages, Verbose
}

export type TraceValues = 'off' | 'messages' | 'verbose';
export namespace Trace {
 export function fromString(value: string): Trace {
  if (!Is.string(value)) {
   return Trace.Off;
  }
...
```

Let me put my attention to this again.

Now that I've thought about this for a bit, I can see that these are basic printer functions.

```
module JsonRPC

type Trace =
| Off
| Messages
| Verbose

let fromString (x : string) =
    match x.ToLower() with
    | "off" -> Off
    | "messages" -> Messages
    | "verbose" -> Verbose
    | _ -> failwithf "Expected on of 'off', 'messages' or 'verbose'. Got: %s" x
```

This is how I would do it in F#. I do not need toString as that some inbuilt.

9:45am.

```
export enum TraceFormat {
 Text = 'text',
 JSON = 'json'
}
export namespace TraceFormat {
 export function fromString(value: string): TraceFormat {
  value = value.toLowerCase();
  if (value === 'json') {
   return TraceFormat.JSON;
  } else {
   return TraceFormat.Text;
  }
 }
}

export interface TraceOptions {
 sendNotification?: boolean;
 traceFormat?: TraceFormat;
}
```

The next comes this thing.

Those optional fields might be needed for JS interop, but they are a horrible idea in as an actual language feature due to what kind of code they would encourage. It really would be much better to just set defaults up front rather than having the functions themselves decide. The later is a significantly more complex solution. These people don't have a lick of sense when it comes to this thing.

Considering they are writing this in TS, they should have had more restraint.

9:55am.

```
export namespace SetTraceNotification {
 export const type = new NotificationType<SetTraceParams, void>('$/setTraceNotification');
}
```

```
export namespace LogTraceNotification {
 export const type = new NotificationType<LogTraceParams, void>('$/logTraceNotification');
}
```

I am not really sure what I should do with these two. I'll leave putting it in for later when I understand what they do.

```
type ConnectionErrors =
    | Closed
    | Disposed
    | AlreadyListening
```

This one I will make an union type. In the TS code it is an enum.

10am.

```
module JsonRPC

type Trace =
    | Off
    | Messages
    | Verbose

    static member fromString (x : string) = function
        | "off" -> Off
        | "messages" -> Messages
        | "verbose" -> Verbose
        | _ -> failwithf "Expected one of: 'off', 'messages' or 'verbose'. Got: %s" x

type TraceFormat =
    | Text
    | JSON

    static member fromString (x : string) = function
        | "text" -> Text
        | "json" -> JSON
        | _ -> failwithf "Expected one of: 'text' or 'json'. Got: %s" x

type ConnectionErrors =
    | Closed
    | Disposed
    | AlreadyListening
```

Let me do it like this. There is no need to convert to lowercase. It is good to lower the state coverage of the code.

```
export class ConnectionError extends Error {

 public readonly code: ConnectionErrors;

 constructor(code: ConnectionErrors, message: string) {
  super(message);
  this.code = code;
  Object.setPrototypeOf(this, ConnectionError.prototype);
 }
}
```

What do I do about this?

```
Object.setPrototypeOf(this, ConnectionError.prototype);
```

...Does this mean that it is setting itself as its own prototype?

What is the purpose of this?

10:05am. I'll skip this for now.

So far the feeling I am getting is good. Compared to just passively reading things, here I am making decision and being active. I am definitely internalizing things at a higher level.

```
export namespace ConnectionStrategy {
 export function is(value: any): value is ConnectionStrategy {
  let candidate: ConnectionStrategy = value;
  return candidate && Is.func(candidate.cancelUndispatched);
 }
}
```

More boilerplate type testing.

```
export interface MessageConnection {
```

The stuff here is enormous so I won't bother pasting it all.

10:10am.

```
function _createMessageConnection(messageReader: MessageReader, messageWriter: MessageWriter, logger: Logger, strategy?: ConnectionStrategy): MessageConnection {
 let sequenceNumber = 0;
 let notificationSquenceNumber = 0;
 let unknownResponseSquenceNumber = 0;
 const version: string = '2.0';

 let starRequestHandler: StarRequestHandler | undefined = undefined;
 let requestHandlers: { [name: string]: RequestHandlerElement | undefined } = Object.create(null);
 let starNotificationHandler: StarNotificationHandler | undefined = undefined;
 let notificationHandlers: { [name: string]: NotificationHandlerElement | undefined } = Object.create(null);
 let progressHandlers: Map<number | string, NotificationHandler1<any>> = new Map();
```

Now comes the first real function after 400 lines of essentially type definitions and complex boilerplate. To set things as undefined...

This guy just does not get it.

I like this situation though. It feels like rewriting a compicated mess like this is a true challenge of my programming skill. I do not want to do too much of this in my life, but this time it is fine. It is this moment that matters.

```
 let timer: NodeJS.Immediate | undefined;
 let messageQueue: MessageQueue = new LinkedMap<string, Message>();
 let responsePromises: { [name: string]: ResponsePromise } = Object.create(null);
 let requestTokens: { [id: string]: CancellationTokenSource } = Object.create(null);

 let trace: Trace = Trace.Off;
 let traceFormat: TraceFormat = TraceFormat.Text;
 let tracer: Tracer | undefined;

 let state: ConnectionState = ConnectionState.New;
 let errorEmitter: Emitter<[Error, Message | undefined, number | undefined]> = new Emitter<[Error, Message, number]>();
 let closeEmitter: Emitter<void> = new Emitter<void>();
 let unhandledNotificationEmitter: Emitter<NotificationMessage> = new Emitter<NotificationMessage>();
 let unhandledProgressEmitter: Emitter<ProgressParams<any>> = new Emitter<ProgressParams<any>>();

 let disposeEmitter: Emitter<void> = new Emitter<void>();
```

Rather than treat this as a function, this is how old style C# programming tends to go. I won't bother to rewrite this line by line. Instead I am going to find ways of factoring this.

10:15am. Not knowing any of the specifics, rather than functions fetching this stuff from lexical scope, one thing I am going to do is put the subfunctions using these in global scope and pass the relevant arguments explicitly.

10:20am. Ok, focus me. Before I embark on this, let me remind myself of how .NET event emitters work.

https://docs.microsoft.com/en-us/dotnet/standard/events/

```
let x = EventHandler()
```

Uf, isn't it possible to start this off without an explicit constructor?

10:25am.

```
let mutable c = 0
let x = EventHandler<unit>(fun sender k -> c <- c + 1; printfn "c is %i" c)
x.Invoke(null,())
```

Ok, this works, but still I remember it going differently last time I looked at this. How do F# observables work?

I used to know this, but I almost completely forgot about it now.

https://fsharpforfunandprofit.com/posts/concurrency-reactive/

10:40am. Got back from Dirk. Suggested the source inline options, but rather than letting that to him, I should have tried it on my own.

Let's see. Normally the repo is 117mb.

Let me clone it, and I will try it the source inlining options.

...Freshly cloned the thing is 4.4mb...

Agh, no doubt the node packages are the problem.

10:40am. No forget it. If I tried doing it myself, I will be doing this for the next few hours.

Let me get back to what I was doing.

https://msdn.microsoft.com/visualfsharpdocs/conceptual/microsoft.fsharp.control-namespace-%5bfsharp%5d

Sigh...

What exactly do I need here?

10:50am.

```
let mutable c = 0
let x = Handler<_>(fun sender k -> c <- c + 1; printfn "c is %i" c)
x.Invoke(null,())
```

Agh, this is fine. I do not need the fully generic `DelegateEvent`. It would be surprising if it turns out that full multicast functionality is being used.

I'll deal with it as I go along.

Let me take a look at the individual functions.

10:55am. Ah, the guy is actually implementing his own `Emitter` for some reason.

I thought that Node provides one already, but whatever.

At any rate, this is why I won't do a full rewrite. For some reason there is a lot of functionality reimplemented in the project that should be a part of the standard library.

```
 function createRequestQueueKey(id: string | number): string {
  return 'req-' + id.toString();
 }

 function createResponseQueueKey(id: string | number | null): string {
  if (id === null) {
   return 'res-unknown-' + (++unknownResponseSquenceNumber).toString();
  } else {
   return 'res-' + id.toString();
  }
 }

 function createNotificationQueueKey(): string {
  return 'not-' + (++notificationSquenceNumber).toString();
 }
```

Let me keep skipping. I am going to commit this to memory and find a way to pare it down.

11:05am.

```
 messageReader.onClose(closeHandler);
 messageReader.onError(readErrorHandler);

 messageWriter.onClose(closeHandler);
 messageWriter.onError(writeErrorHandler);

 function triggerMessageQueue(): void {
  if (timer || messageQueue.size === 0) {
   return;
  }
  timer = setImmediate(() => {
   timer = undefined;
   processMessageQueue();
  });
 }
```

Hmmm, is he reimplementing a mailbox processor here? Is that what he is trying to do?

```
 function processMessageQueue(): void {
  if (messageQueue.size === 0) {
   return;
  }
  let message = messageQueue.shift()!;
  try {
   if (isRequestMessage(message)) {
    handleRequest(message);
   } else if (isNotificationMessage(message)) {
    handleNotification(message);
   } else if (isResponseMessage(message)) {
    handleResponse(message);
   } else {
    handleInvalidMessage(message);
   }
  } finally {
   triggerMessageQueue();
  }
 }
```

This function is innocuous, but it feels key.

11:10am.

```
function reply(resultOrError: any | ResponseError<any>, method: string, startTime: number): void {
```

`any | ResponseError<any>` This boggles my mind.

11:15am.

```
  function reply(resultOrError: any | ResponseError<any>, method: string, startTime: number): void {
   let message: ResponseMessage = {
    jsonrpc: version,
    id: requestMessage.id
   };
   if (resultOrError instanceof ResponseError) {
    message.error = (<ResponseError<any>>resultOrError).toJson();
   } else {
    message.result = resultOrError === void 0 ? null : resultOrError;
   }
   traceSendingResponse(message, method, startTime);
   messageWriter.write(message);
  }
  function replyError(error: ResponseError<any>, method: string, startTime: number) {
   let message: ResponseMessage = {
    jsonrpc: version,
    id: requestMessage.id,
    error: error.toJson()
   };
   traceSendingResponse(message, method, startTime);
   messageWriter.write(message);
  }
```

Here is where the replies are actually made.

...Let me take a little break.

11:30am. Let me resume. I'll go at it for another 30m and then take a proper break.

```
   if (resultOrError instanceof ResponseError) {
    message.error = (<ResponseError<any>>resultOrError).toJson();
   } else {
    message.result = resultOrError === void 0 ? null : resultOrError;
   }
```

This is nasty if workable. Who was it that said TS was elegant? The lack of ADTs really is a huge disadvantage.

```
  if (requestHandler || starRequestHandler) {
   let cancellationSource = new CancellationTokenSource();
   let tokenKey = String(requestMessage.id);
   requestTokens[tokenKey] = cancellationSource;
   try {
    let handlerResult: any;
    if (requestMessage.params === void 0 || (type !== void 0 && type.numberOfParams === 0)) {
     handlerResult = requestHandler
      ? requestHandler(cancellationSource.token)
      : starRequestHandler!(requestMessage.method, cancellationSource.token);
    } else if (Is.array(requestMessage.params) && (type === void 0 || type.numberOfParams > 1)) {
     handlerResult = requestHandler
      ? requestHandler(...requestMessage.params, cancellationSource.token)
      : starRequestHandler!(requestMessage.method, ...requestMessage.params, cancellationSource.token);
    } else {
     handlerResult = requestHandler
      ? requestHandler(requestMessage.params, cancellationSource.token)
      : starRequestHandler!(requestMessage.method, requestMessage.params, cancellationSource.token);
    }

    let promise = handlerResult as Thenable<any | ResponseError<any>>;
    if (!handlerResult) {
     delete requestTokens[tokenKey];
     replySuccess(handlerResult, requestMessage.method, startTime);
    } else if (promise.then) {
     promise.then((resultOrError): any | ResponseError<any> => {
      delete requestTokens[tokenKey];
      reply(resultOrError, requestMessage.method, startTime);
     }, error => {
      delete requestTokens[tokenKey];
      if (error instanceof ResponseError) {
       replyError(<ResponseError<any>>error, requestMessage.method, startTime);
      } else if (error && Is.string(error.message)) {
       replyError(new ResponseError<void>(ErrorCodes.InternalError, `Request ${requestMessage.method} failed with message: ${error.message}`), requestMessage.method, startTime);
      } else {
       replyError(new ResponseError<void>(ErrorCodes.InternalError, `Request ${requestMessage.method} failed unexpectedly without providing any details.`), requestMessage.method, startTime);
      }
     });
    } else {
     delete requestTokens[tokenKey];
     reply(handlerResult, requestMessage.method, startTime);
    }
```

Coming into a codebase with the notion of it being complete garbage is just so different from wanting to actually understand it.

I can do it. I will be able to simplify this complicated state machine.

11:55am.

```
  dispose: () => {
   if (isDisposed()) {
    return;
   }
   state = ConnectionState.Disposed;
   disposeEmitter.fire(undefined);
   let error = new Error('Connection got disposed.');
   Object.keys(responsePromises).forEach((key) => {
    responsePromises[key].reject(error);
   });
   responsePromises = Object.create(null);
   requestTokens = Object.create(null);
   messageQueue = new LinkedMap<string, Message>();
   // Test for backwards compatibility
   if (Is.func(messageWriter.dispose)) {
    messageWriter.dispose();
   }
   if (Is.func(messageReader.dispose)) {
    messageReader.dispose();
   }
  }
```

I started from `main`, but what I really need to cover next is those message readers and writers.

As well the other files.

I need to start from the auxiliaries. The `main` is a bit too much right now.

At any rate, this thing is a beast, no doubt about it. It will take me a while to really internalize and simplify it. But it should definitely be doable. For my own sake I will take on this challenge.

Multiple passes of my full focus effort will crack it.

12pm. The sheer degree of boilerplate in this is making it really difficult to understand the flow, but I am sure that underneath, what this program is trying to be is a simple message box processor.

Well, forget that. Let me have breakfast here. I'll resume in a few hours."