"10:20am. Uah, I did not mean to go to bed past 12am, but it happened. I really got into the game and just could not stop. At least I did not sleep badly, so I will be able to do some works as soon as I wipe off the cobwebs.
In other news, Ehentai is closing down. This cannot be. Just how could this tragedy happen? Had I been more powerful I could have stopped this. Rest in peace, Ehentai.

https://boards.4channel.org/a/thread/191162332/specops-asuka-46

Well, let me read this and then I'll try to get an exercise done.

10:40am. Let me finally start.

10:45am.

```
  intros.
  generalize dependent k.
  induction H; intros.
  - reflexivity.
  - simpl lookup.
    unfold t_update.
    unfold combine.
    rewrite (IHAbs1 k0).
    rewrite (IHAbs2 k0).
    bdestruct (k0 <? k).
    + bdestruct (k =? k0).
      -- omega.
      -- reflexivity.
    + bdestruct (k <? k0).
      -- bdestruct (k =? k0).
         ++ omega.
         ++ reflexivity.
      -- bdestruct (k =? k0).
         ++ reflexivity.
         ++ omega.
Qed.
```

Here is the old lookup relate.

10:45am.

```
    bdestruct (int2Z k0 <? int2Z k).
```

Oh, bdestruct does work on `Z`s? I really must have been in a hurry yesterday to have missed this.

10:55am.

```
(** **** Exercise: 3 stars (lookup_relate)  *)
Theorem lookup_relate:
  forall k t cts ,   Abs t cts -> lookup k t =  cts (int2Z k).
Proof.  (* Copy your proof from Extract.v, and adapt it. *)
  intros.
  generalize dependent k.
  induction H; intros.
  - reflexivity.
  - simpl lookup.
    unfold t_update.
    unfold combine.
    rewrite (IHAbs1 k0).
    rewrite (IHAbs2 k0).
    bdestruct (ltb k0 k).
    + bdestruct (int2Z k0 <? int2Z k).
      * bdestruct (int2Z k =? int2Z k0).
        -- omega.
        -- reflexivity.
      * bdestruct (int2Z k <? int2Z k0).
        -- bdestruct (int2Z k =? int2Z k0).
           ++ omega.
           ++ contradiction.
        -- bdestruct (int2Z k =? int2Z k0).
           ++ contradiction.
           ++ omega.
    + bdestruct (int2Z k0 <? int2Z k).
      * bdestruct (int2Z k =? int2Z k0).
        -- omega.
        -- contradiction.
      * bdestruct (int2Z k <? int2Z k0).
        -- bdestruct (int2Z k =? int2Z k0).
           ++ omega.
           ++ bdestruct (ltb k k0). reflexivity. omega.
        -- bdestruct (int2Z k =? int2Z k0).
           ++ bdestruct (ltb k k0). contradiction. reflexivity.
           ++ omega.
Qed.
```

This is one exercise down. The destructuring are a mess, but they will do.

10:55am.

```
(** **** Exercise: 4 stars (balance_relate)  *)
(** You will need proof automation for this one.  Study the methods used
  in [ins_not_E] and [balance_SearchTree], and try them here.
  Add one clause at a time to your [match goal]. *)

Theorem balance_relate:
  forall c l k vk r m,
    SearchTree (T c l k vk r) ->
    Abs (T c l k vk r) m ->
    Abs (balance c l k vk r) m.
Proof.
intros.
inv H.
unfold balance.
repeat match goal with
 | H: Abs E _ |- _ => inv H
end.
(** Add these clauses, one at a time, to your [repeat match goal] tactic,
   and try it out:
   -1. Whenever a clause [H: Abs E _] is above the line, invert it by [inv H].
             Take note: with just this one clause, how many subgoals remain?
   -2. Whenever [Abs (T _ _ _ _ _) _] is above the line, invert it.
             Take note: with just these two clause, how many subgoals remain?
   -3. Whenever [SearchTree' _ E _] is above the line, invert it.
             Take note after this step and each step: how many subgoals remain?
   -4. Same for [SearchTree' _ (T _ _ _ _ _) _].
   -5. When [Abs match c with Red => _ | Black => _ end _] is below the line,
          [destruct c].
   -6. When [Abs match s with E => _ | T ... => _ end _] is below the line,
          [destruct s].
   -7. Whenever [Abs (T _ _ _ _ _) _] is below the line,
                  prove it by [apply Abs_T].   This won't always work;
         Sometimes the "cts" in the proof goal does not exactly match the form
         of the "cts" required by the [Abs_T] constructor.  But it's all right if
         a clause fails; in that case, the [match goal] will just try the next clause.
          Take note, as usual: how many clauses remain?
   -8.  Whenever [Abs E _] is below the line, solve it by [apply Abs_E].
   -9.  Whenever the current proof goal matches a hypothesis above the line,
          just use it.  That is, just add this clause:
       | |- _ => assumption
   -10.  At this point, if all has gone well, you should have exactly 21 subgoals.
       Each one should be of the form, [  Abs (T ...) (t_update...) ]
       What you want to do is replace (t_update...) with a different "contents"
       that matches the form required by the Abs_T constructor.
       In the first proof goal, do this: [eapply Abs_helper].
       Notice that you have two subgoals.
       The first subgoal you can prove by:
           apply Abs_T. apply Abs_T. apply Abs_E. apply Abs_E.
           apply Abs_T. eassumption. eassumption.
       Step through that, one at a time, to see what it's doing.
       Now, undo those 7 commands, and do this instead:
            repeat econstructor; eassumption.
       That solves the subgoal in exactly the same way.
       Now, wrap this all up, by adding this clause to your [match goal]:
       | |- _ =>  eapply Abs_helper; [repeat econstructor; eassumption | ]
   -11.  You should still have exactly 21 subgoals, each one of the form,
             [ t_update... = t_update... ].  Notice above the line you have some
           assumptions of the form,  [ H: SearchTree' lo _ hi ].  For this equality
         proof, we'll need to know that [lo <= hi].  So, add a clause at the end
        of your [match goal] to apply SearchTree'_le in any such assumption,
        when below the line the proof goal is an equality [ _ = _ ].
   -12.  Still exactly 21 subgoals.  In the first subgoal, try:
          [contents_equivalent_prover].   That should solve the goal.
          Look above, at [Ltac contents_equivalent_prover], to see how it works.
          Now, add a clause to  [match goal] that does this for all the subgoals.

   -Qed! *)

(* FILL IN HERE *) Admitted.
```

Let me give this one a shot. Apparently there are only 21 subgoals in all. This is not a level that requires automation. Well, maybe some of them are automated away in the process. The instructions here are quite explicit in what In need to do so I do not think this problem will give me trouble.

11:05am. Focus me, focus. Let me just start this thing.

```
       | H: Abs E _ |- _ => inv H
```

Ah, I get it. So this is how one locks in premises.

```
Definition how_many_subgoals_remaining :=
    [1; 1; 1; 1; 1; 2; 2; 3; 1;

  ].
```

Let me track it in the journal.

11:20am.

```
repeat match goal with
       | H: Abs E _ |- _ => inv H
       | H: Abs (T _ _ _ _ _) _ |- _ => inv H
       | H: SearchTree' _ E _ |- _ => inv H
       | H: SearchTree' _ (T _ _ _ _ _) _ |- _ => inv H
       | c: color |- Abs (match c with Red => _ | Black => _ end) _ => inv c
       | r: tree |- Abs (match r with E => _ | T _ _ _ _ _ => _ end) _ => inv s
       end.
```

There is something wrong here. For some reason the 5th rule is not triggering.

```
Error: In nested Ltac calls to "inv" and "clear (var_list)", last call failed.
       c is used in conclusion.
```

Ah, it seems that maybe I just need to destruct it.

```
repeat match goal with
       | H: Abs E _ |- _ => inv H
       | H: Abs (T _ _ _ _ _) _ |- _ => inv H
       | H: SearchTree' _ E _ |- _ => inv H
       | H: SearchTree' _ (T _ _ _ _ _) _ |- _ => inv H
       | c: color |- Abs (match c with Red => _ | Black => _ end) _ => destruct c
       | r: tree |- Abs (match r with E => _ | T _ _ _ _ _ => _ end) _ => destruct r
       end.
```

Much better.

11:25am.

```
   -10.  At this point, if all has gone well, you should have exactly 21 subgoals.
```

Well, I have only 1, so things are not going well.

```
  Abs
    match l with
    | E =>
```

Why has this not gotten destructured?

```
       | s: tree |- Abs (match s with E => _ | T _ _ _ _ _ => _ end) _ => destruct s
```

This is bizarre. Should it not have gotten bound to the left?

11:30am. Ugh, I have no idea. For once I am going to have to look in the Coq manual.

```
repeat match goal with
       | H: Abs E _ |- _ => inv H
       | H: Abs (T _ _ _ _ _) _ |- _ => inv H
       | H: SearchTree' _ E _ |- _ => inv H
       | H: SearchTree' _ (T _ _ _ _ _) _ |- _ => inv H
       | |- Abs (match c with Red => _ | Black => _ end) _ => destruct c
       | |- Abs (match l with E => _ | T _ _ _ _ _ => _ end) _ => destruct l
       | |- Abs (match r with E => _ | T _ _ _ _ _ => _ end) _ => destruct r
       | |- Abs (T _ _ _ _ _) _ => apply Abs_T
       | |- Abs E _ => apply Abs_E
       | |- _ => assumption
       end.
```

```
  Abs
    match r1 with
    | E => match r2 with
           | T Red c z vz d => T Red (T Black E k vk r1) k0 v (T Black c z vz d)
           | _ => T Black E k vk (T Red r1 k0 v r2)
           end
```

This is wrong, how can I stop it from matching on the names exactly?

```
match goal with
| |- match ?c with Red => _ | Black => _  end <> _=> destruct c
end.
```

11:40am.

```
repeat match goal with
       | H: Abs E _ |- _ => inv H
       | H: Abs (T _ _ _ _ _) _ |- _ => inv H
       | H: SearchTree' _ E _ |- _ => inv H
       | H: SearchTree' _ (T _ _ _ _ _) _ |- _ => inv H
       | |- Abs (match ?c with Red => _ | Black => _ end) _ => destruct c
       | |- Abs (match ?s with E => _ | T _ _ _ _ _ => _ end) _ => destruct s
       | |- Abs (T _ _ _ _ _) _ => apply Abs_T
       | |- Abs E _ => apply Abs_E
       | |- _ => assumption
       end.
```

Yeah, now I have 21 subgoals.

```
   -10.  At this point, if all has gone well, you should have exactly 21 subgoals.
       Each one should be of the form, [  Abs (T ...) (t_update...) ]
       What you want to do is replace (t_update...) with a different "contents"
       that matches the form required by the Abs_T constructor.
       In the first proof goal, do this: [eapply Abs_helper].
       Notice that you have two subgoals.
       The first subgoal you can prove by:
           apply Abs_T. apply Abs_T. apply Abs_E. apply Abs_E.
           apply Abs_T. eassumption. eassumption.
       Step through that, one at a time, to see what it's doing.
       Now, undo those 7 commands, and do this instead:
            repeat econstructor; eassumption.
       That solves the subgoal in exactly the same way.
       Now, wrap this all up, by adding this clause to your [match goal]:
       | |- _ =>  eapply Abs_helper; [repeat econstructor; eassumption | ]
```

Done with this point.

```
   -11.  You should still have exactly 21 subgoals, each one of the form,
             [ t_update... = t_update... ].  Notice above the line you have some
           assumptions of the form,  [ H: SearchTree' lo _ hi ].  For this equality
         proof, we'll need to know that [lo <= hi].  So, add a clause at the end
        of your [match goal] to apply SearchTree'_le in any such assumption,
        when below the line the proof goal is an equality [ _ = _ ].
```

Let me do this one.

11:55am.

```
Theorem balance_relate:
  forall c l k vk r m,
    SearchTree (T c l k vk r) ->
    Abs (T c l k vk r) m ->
    Abs (balance c l k vk r) m.
Proof.
intros.
inv H.
unfold balance.

repeat match goal with
       | H: Abs E _ |- _ => inv H
       | H: Abs (T _ _ _ _ _) _ |- _ => inv H
       | H: SearchTree' _ E _ |- _ => inv H
       | H: SearchTree' _ (T _ _ _ _ _) _ |- _ => inv H
       | |- Abs (match ?c with Red => _ | Black => _ end) _ => destruct c
       | |- Abs (match ?s with E => _ | T _ _ _ _ _ => _ end) _ => destruct s
       | |- Abs (T _ _ _ _ _) _ => apply Abs_T
       | |- Abs E _ => apply Abs_E
       | |- _ => assumption
       | |- _ =>  eapply Abs_helper; [repeat econstructor; eassumption | ]
       | H: SearchTree' ?lo _ ?hi |- _ = _ => apply SearchTree'_le in H
       | |- _ = _ => contents_equivalent_prover
       end.
Qed.
```

Here it is. I am going to have to go at it from the top so I can get the subgoal counts properly.

```
(** Extend this list, so that the nth entry shows how many subgoals
    were remaining after you followed the nth instruction in the list above.
    Your list should be exactly 13 elements long; there was one subgoal
    *before* step 1, after all. *)

Definition how_many_subgoals_remaining :=
  [1; 1; 1; 1; 1; 2; 58; 203; 143; 21; 21; 21; 0].
```

Ok, I have this done. Now I see why he insisted upon automation. Ok.

12:05pm. Actually, this is pretty cool.

Had I known how to do ...

```
 repeat match goal with
  | |- context [if ?A then _ else _] => bdestruct A
 end;
```

Some of the past proofs where I had to do a lot of destructuring would have been a lot easier.

12:10pm.

```
(** **** Exercise: 3 stars (ins_relate)  *)
Theorem ins_relate:
 forall k v t cts,
    SearchTree t ->
    Abs t cts ->
    Abs (ins k v t) (t_update cts (int2Z k) v).
Proof.  (* Copy your proof from SearchTree.v, and adapt it.
     No need for fancy proof automation. *)
```

I'll do this one after the break."