"9:40am. I am up. Any mail? Nothing. Nothing from Valora, nothing from Enso and nothing from that Haskell place. Let me prompt Enso at least. It has been over 2 weeks.
> Hello, I haven't heard back from you in a while. Can I take that as you not being interested? If so, that would be a pity as I'd be a good fit for working on a language and its libraries thanks to the experience I have on working for my own.

I am not expecting anything from this. I think I will be a Youtuber for a while longer at this rate.

9:45am. I didn't sleep too well. Let me read Baki and I will struggle for a while longer. I really need to figure out how to pare down the template. And then I need to figure out how to deal with Elmish debugger.

Just what is the deal with those websockets? After that I'll be ready to start working on a new playlist.

9:55am. No matter how I look at it, I must take a wrong turn in life. What is the point of chasing the Singularity if the dollar ammount in your account is the all that matters in the end? Right now, these packaging issues in Fable are doing their best to make me regret favoring functional programming. From now on, I am going to pick up programming activities that make me money. That means learning webdev.

I can't really blame companies if they pass me up for web dev positions the way I am now. I need more knowledge and more skill, and that is not going to happen in a day. It will require steady accumulation over a period of time. I'd be more confident if it were for all these packaging issues that are slowing me down.

10:05am. Let me chill a while and then I will get started. I cannot do anything else, but do my best.

It feels like being in this situation is my punishment. How dare I simply try to accumulate skill and pursue my dream straightforwardly?

I am going to join some discord where F# guys are and ask them how to deal with the Elmish debugger and such. Once I learn to deal with these packaging issues, I will have passed the most severe hurdle and will be able to move on to something productive. All this is making me look like such an amateur, but I have no choice, but to keep going.

10:35am. Let me start. Forget Spiral. Forget Simulacrum. Forget the upcoming Singularity. Pursuing it only makes sense if you have a path powerful enough to see you through to it. I just lack the skills.

Focus on making money. Focus on acquiring the webdev skills that will make you it. Live life freely until the inevitable AI induced genocide. That is the way to go.

I pursued the Singularity with all my power because I thought it was the right thing to do, so now instead I should stay true to my being and pursue web development.

https://www.nuget.org/packages/Saturn
https://www.nuget.org/packages/Fable.Elmish

Take a look at the per day averages for these.

https://www.nuget.org/packages/Dapper

How popular a package is roughly related to how good it would be to know it.

https://www.nuget.org/packages/Microsoft.EntityFrameworkCore

If I am going to be a webdev, I should get familiar with my favored stack, as well as the most popular ones in the .NET land. I should do some projects in those. After that I'll be ready.

I am suffering for no reason at all. If I want money, then taking up popular frameworks, putting them on my resume, making videos about them...

That is the way to go as a programmer!

10:40am. Remember the rules that Youtuber guy gave me. Keyword research, popular videos - there should be a business line in taking popular packages, doing simple projects in them, and putting them on Youtube.

Now that F# compiles to Python, I can make a video - how to run a NN using Pytorch from F#. Things of that sort. F# has niche appeal, NNs and PyTorch have mainstream appeal, and I can strike both chords in one blow like that.

10:50am. I am taking a peek at the Heaven's Key dashboard from time to time, and compared to the start of the month, the story has only 400 extra views. I even lost a follower and a favorite.

...

Was I wrong to desire to make it through writing a story?

At its root all I wanted was to get ahead through my own effort.

Let me start. I absolutely have to do this. The fact that I got 3 interested parties through posting in the F# sub vs 0 from applying directly, speaks volumes about where I should focus my efforts. Youtube would be far more effective as an advertizing tool than that Reddit post.

I have to assume the worst when it comes to the Valora and Softfluency (Serbian guy) connections. The Valora guy was interested a few days ago, but who knows whether something will happen or the circumstrances would change at his end, and then I'd never hear from him again. I need to work on cultivating my own channels, and making educational Youtube videos is the best possible tool for that. Not to mention, the process of it will naturally increase both my communication skills, as well as the familiarity with the tech stack that I want to work in.

10:55am. I need to just do it. Right now, it is torture. Nobody is responding, and nobody is sending work my way. But if I could gain a little popularity things would be far easier.

Go forward!

First of all, I want to start with the full SAFE template, run `paket update` and figure out where the conflict is.

Once I have that done, I'll have enough of an understanding of how to deal with packages. I'll focus on the Elmish debugger after that.

11:25am. I've been taking a bathroom break.

https://www.nuget.org/packages/System.Reactive

Take a look at how popular this is. If I made a video series on how to make a UI library using it, I am sure it would get some views. Making a poker RL agent is sure to get views. I'll strike all the chords in one blow.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-sln

> dotnet sln todo.sln add (ls -r **/*.csproj)

Let me remove all the projects. I just want to first get the package dependencies out of the way.

```
  Total time taken: 0 milliseconds
E:\Webdev\Fable\Safe Stack Examples\full\tests\Server\Server.Tests.fsproj : error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 7.0.3 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.A
spNetCore.Authentication.JwtBearer 7.0.3 supports: net7.0 (.NETCoreApp,Version=v7.0) [E:\Webdev\Fable\Safe Stack Examples\full\full.sln]
E:\Webdev\Fable\Safe Stack Examples\full\src\Server\Server.fsproj : error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 7.0.3 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCor
e.Authentication.JwtBearer 7.0.3 supports: net7.0 (.NETCoreApp,Version=v7.0) [E:\Webdev\Fable\Safe Stack Examples\full\full.sln]
  Restored E:\Webdev\Fable\Safe Stack Examples\full\tests\Shared\Shared.Tests.fsproj (in 229 ms).
  Restored E:\Webdev\Fable\Safe Stack Examples\full\src\Shared\Shared.fsproj (in 229 ms).
  Failed to restore E:\Webdev\Fable\Safe Stack Examples\full\src\Server\Server.fsproj (in 229 ms).
  Failed to restore E:\Webdev\Fable\Safe Stack Examples\full\tests\Server\Server.Tests.fsproj (in 229 ms).
  Restored E:\Webdev\Fable\Safe Stack Examples\full\Build.fsproj (in 36 ms).
  Restored E:\Webdev\Fable\Safe Stack Examples\full\src\Client\Client.fsproj (in 47 ms).
  Restored E:\Webdev\Fable\Safe Stack Examples\full\tests\Client\Client.Tests.fsproj (in 49 ms).
Total time taken: 10 seconds
Paket failed with
-> dotnet restore "full.sln" failed
```

Oh, this happens in Server.Tests.

```
PS E:\Webdev\Fable\Safe Stack Examples\full> dotnet sln remove (ls -r tests/**/*.fsproj)
```

I removed them and now...

```
E:\Webdev\Fable\Safe Stack Examples\full\src\Server\Server.fsproj : error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 7.0.3 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCor
e.Authentication.JwtBearer 7.0.3 supports: net7.0 (.NETCoreApp,Version=v7.0) [E:\Webdev\Fable\Safe Stack Examples\full\full.sln]
  Restored E:\Webdev\Fable\Safe Stack Examples\full\src\Client\Client.fsproj (in 150 ms).
  Failed to restore E:\Webdev\Fable\Safe Stack Examples\full\src\Server\Server.fsproj (in 154 ms).
  Restored E:\Webdev\Fable\Safe Stack Examples\full\src\Shared\Shared.fsproj (in 150 ms).
  Restored E:\Webdev\Fable\Safe Stack Examples\full\Build.fsproj (in 150 ms).
```

Let me check this out in the log file.

```
Microsoft.AspNetCore.Authentication.JwtBearer (7.0.3)
```

Yeah, it is here. What happens in the old lock file?

```
    Microsoft.AspNetCore.Authentication.JwtBearer (7.0.3)
    Saturn (0.16.1)
      FSharp.Control.Websockets (>= 0.2.2)
      Giraffe (>= 6.0)
      Microsoft.AspNetCore.Authentication.JwtBearer (>= 6.0.3)
```

Actually, take a look at this. I can just downgrade it to 6.0.3 and it should work. Though it might not be a bad idea to just open an issue for paket.

https://github.com/fsprojects/Paket/issues

There are a shitload of them though.

https://github.com/fsprojects/Paket/issues/

Check out issue 4180.

Recruit additional maintainers or archive the project

///

This has become a critical build dependency for many, many project and it is essentially unmaintained. Pull requests languish without any review, most issues go unanswered, etc. etc.

If you are unable to recruit additional maintainers, I recommend archiving the project to let users know that it is deprecated and they should move to another tool.

///

There are 30 PRs pending. Maybe I am making a mistake going with Paket.

https://learn.microsoft.com/en-us/nuget/what-is-nuget

11:45am. Anyway, let me fix the issue that I have by hand.

I'll open an issue on Paket, even though it is unlikely to do much.

https://github.com/fsprojects/Paket/issues/

Opened issue 4197.

Let me just pin it by hand.

```
source https://api.nuget.org/v3/index.json
framework: net6.0
storage: none

nuget Fsharp.Core ~> 6
nuget Fable.Remoting.Giraffe
nuget Saturn
nuget Microsoft.AspNetCore.Authentication.JwtBearer ~> 6
nuget Expecto

nuget Fable.Core
nuget Fable.Elmish
nuget Fable.Elmish.React
nuget Fable.Elmish.Debugger
nuget Fable.Elmish.HMR
nuget Fable.Mocha
nuget Fable.React
nuget Fable.Remoting.Client
nuget Feliz
nuget Feliz.Bulma
nuget Fulma

nuget Fake.Core.Target
nuget Fake.IO.FileSystem
nuget Farmer
```

With this it works.

I said as much in the issue.

12pm. I managed to resolve it without much fuss.

https://github.com/fsprojects/Paket

I do not envy these guys at all. I certainly wouldn't want to be an OS maintainer unless I am paid for it. This is hard work and should be well compensated.

https://studio.youtube.com/video/ljP585GdTNQ/edit

Let me edit the title for this video. It only had 3 views.

> How To Setup The WebUI Defaults And Clear Up The Starter Script

I'll change this to:

> How To Speed Up Your Prompting Workflow By Setting The UI Defaults And Cleaning Up The Setup Script

12:10pm. That should get a bit more bites. By now, the other videos have gotten a decent amount of views. In fact. Let me also change:

> How To Free Up Used Space On Your Gradient Notebook

> Don't Go Over Your Storage Limit! Learn How To Free Up Used Space On Your Gradient Notebook

The later might catch more attention.

Now...

Let me try running the template.

It works. I had remove the npm requirements in the `package.json` file.

https://elmish.github.io/debugger/

Let me try getting this to run.

https://github.com/elmish/debugger

> Follow the monitor installation instructions at Remote DevTools site.

https://reactjs.org/blog/2015/09/02/new-react-developer-tools.html#installation

Let me install this.

https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

4m users. I should be making videos about this.

```
#if DEBUG
// |> Program.withDebugger
#endif
```

I uncommented this line, and now I do not get exceptions in the console.

> WebSocket connection to 'ws://localhost:8000/socketcluster/' failed:

Let me do a thing. I'll open an issue in the Elmish.Debugger repo asking for an explanation of how it should be used.

https://github.com/zalmoxisus/remotedev

Actually, first let me read the stuff here.

```js
import { connectViaExtension, extractState } from 'remotedev';
// It will try to use Redux DevTools extension first if installed
// In case you want only remote monitoring use `connect`:
// import { connect, extractState } from 'remotedev';

// Connect to the monitor
remotedev = connectViaExtension();

// Subscribe to change state (if need more than just logging)
remotedev.subscribe(message => {
  // Helper when only time travelling needed
  const state = extractState(message);
  this.setState(state);
});

// Send changes to the remote monitor
remotedev.send(action, state);
```

I have no idea. Do I just run this? Let me try it.

```
PS E:\Webdev\Fable\Safe Stack Examples\full> node remotedev.js
(node:28744) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
E:\Webdev\Fable\Safe Stack Examples\full\remotedev.js:1
import { connectViaExtension, extractState } from 'remotedev';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

Er, how do I even run it.

```
PS E:\Webdev\Fable\Safe Stack Examples\full> node remotedev.mjs
file:///E:/Webdev/Fable/Safe%20Stack%20Examples/full/remotedev.mjs:7
remotedev = connectViaExtension();
          ^

ReferenceError: remotedev is not defined
    at file:///E:/Webdev/Fable/Safe%20Stack%20Examples/full/remotedev.mjs:7:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

Hmmm.

https://youtu.be/1dhPjQlTDek
REALITY CHECK on Becoming a Remote Software Developer

Let me watch this. He says he has tips on getting programming jobs. Before that...

Let me open an issue.

https://github.com/elmish/debugger/issues/

Here is issue 59.

///

I've installed the SAFE template, updated it, and managed to get all the package errors out of the way.

```fs
#if DEBUG
|> Program.withDebugger
#endif
```

The debugger is set on as expected. But when I run the program using `dotnet run`, and enter the `http://localhost:8080/` page in the browser, I do not see anything related to debugging on the page itself. The only related to it are the `WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: ` in the Chrome console. What should I do about that?

They go away if I comment out the code fragment I posted, but I'd like to learn how to use the debugger.

///

12:50pm. I'll pass the ball in Maxime's court.

There is something else I want to accomplish. Join the F# slack. I really want the option of asking somebody knowledgeable for advice in times like these. But I've yet to receive an invite email despite joining the F# foundation 3 weeks ago. Let me contact them.

12:55pm. Sent a message to the F# foundation asking for an invite. Now, until I get an answer, my hands are tied.

What I am going to do is start recording some vids. I want to get this initial stage out of the way.

1pm. Let me do the chores here."