"8:15am. I am going to bed too late and getting up too early. I really shouldn't be this excited to try a new technique. If CAST was really that good, the authors would have provided higher res images as examples. But whatever, I am kind of person to suspend my disbelief anyway.
8:20am. Let me clone CAST.

8:45am. Damn it, I want to leave it for later, but let me try running it.

Hmmm, it runs. But the image is small. 256 x 256. How do I increase it? Let me ask the authors. Right now I am not longer skeptical about this being an outright scam, but I am wondering whether it is only capable of making 256 x 256 pics?

https://github.com/zyxElsa/CAST_pytorch/issues/

I've opened issue 3 here. Let me see if I can figure it out on my own. Who knows when the Chinamen will reply.

```py
    def initialize(self, parser):
        """Define the common options that are used in both training and test."""
        # basic parameters
        parser.add_argument('--dataroot', default='placeholder', help='path to images (should have subfolders trainA, trainB, valA, valB, etc)')
        parser.add_argument('--name', type=str, default='experiment_name', help='name of the experiment. It decides where to store samples and models')
        parser.add_argument('--easy_label', type=str, default='experiment_name', help='Interpretable name')
        parser.add_argument('--gpu_ids', type=str, default='0', help='gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU')
        parser.add_argument('--checkpoints_dir', type=str, default='./checkpoints', help='models are saved here')
        # model parameters
        parser.add_argument('--model', type=str, default='cast', help='chooses which model to use.')
        parser.add_argument('--input_nc', type=int, default=3, help='# of input image channels: 3 for RGB and 1 for grayscale')
        parser.add_argument('--output_nc', type=int, default=3, help='# of output image channels: 3 for RGB and 1 for grayscale')
        parser.add_argument('--ngf', type=int, default=64, help='# of gen filters in the last conv layer')
        parser.add_argument('--ndf', type=int, default=64, help='# of discrim filters in the first conv layer')
        parser.add_argument('--netD', type=str, default='basic', choices=['basic', 'n_layers', 'pixel', 'patch', 'tilestylegan2', 'stylegan2'], help='specify discriminator architecture. The basic model is a 70x70 PatchGAN. n_layers allows you to specify the layers in the discriminator')
        parser.add_argument('--netG', type=str, default='resnet_9blocks', choices=['resnet_9blocks', 'resnet_6blocks', 'unet_256', 'unet_128', 'stylegan2', 'smallstylegan2', 'resnet_cat', 'cluit', 'SA2_2'], help='specify generator architecture')
        parser.add_argument('--n_layers_D', type=int, default=3, help='only used if netD==n_layers')
        parser.add_argument('--normG', type=str, default='instance', choices=['instance', 'batch', 'none'], help='instance normalization or batch normalization for G')
        parser.add_argument('--normD', type=str, default='instance', choices=['instance', 'batch', 'none'], help='instance normalization or batch normalization for D')
        parser.add_argument('--init_type', type=str, default='xavier', choices=['normal', 'xavier', 'kaiming', 'orthogonal'], help='network initialization')
        parser.add_argument('--init_gain', type=float, default=0.02, help='scaling factor for normal, xavier and orthogonal.')
        parser.add_argument('--no_dropout', type=util.str2bool, nargs='?', const=True, default=True,
                            help='no dropout for the generator')
        parser.add_argument('--no_antialias', action='store_true', help='if specified, use stride=2 convs instead of antialiased-downsampling (sad)')
        parser.add_argument('--no_antialias_up', action='store_true', help='if specified, use [upconv(learned filter)] instead of [upconv(hard-coded [1,3,3,1] filter), conv]')
        # Model parameters.
        parser.add_argument("--style-dim", default=256, type=int)
        parser.add_argument("--feature_dim", default=256, type=int)
        parser.add_argument("--hypersphere-dim", default=256, type=int)
        parser.add_argument("--queue-size", default=1024, type=int)
        parser.add_argument("--temperature", default=0.07, type=float)
        parser.add_argument("--max_conv_dim", default=512, type=int)
        # dataset parameters
        parser.add_argument('--dataset_mode', type=str, default='unaligned', help='chooses how datasets are loaded. [unaligned | aligned | single | colorization]')
        parser.add_argument('--direction', type=str, default='AtoB', help='AtoB or BtoA')
        parser.add_argument('--serial_batches', action='store_true', help='if true, takes images in order to make batches, otherwise takes them randomly')
        parser.add_argument('--num_threads', default=4, type=int, help='# threads for loading data')
        parser.add_argument('--batch_size', type=int, default=1, help='input batch size')
        parser.add_argument('--load_size', type=int, default=286, help='scale images to this size')
        parser.add_argument('--crop_size', type=int, default=256, help='then crop to this size')
        parser.add_argument('--max_dataset_size', type=int, default=float("inf"), help='Maximum number of samples allowed per dataset. If the dataset directory contains more than max_dataset_size, only a subset is loaded.')
        parser.add_argument('--preprocess', type=str, default='resize_and_crop', help='scaling and cropping of images at load time [resize_and_crop | crop | scale_width | scale_width_and_crop | none]')
        parser.add_argument('--no_flip', action='store_true', help='if specified, do not flip the images for data augmentation')
        parser.add_argument('--display_winsize', type=int, default=256, help='display window size for both visdom and HTML')
        parser.add_argument('--random_scale_max', type=float, default=3.0,
                            help='(used for single image translation) Randomly scale the image by the specified factor as data augmentation.')
       # additional parameters
        parser.add_argument('--epoch', type=str, default='latest', help='which epoch to load? set to latest to use latest cached model')
        parser.add_argument('--verbose', action='store_true', help='if specified, print more debugging information')
        parser.add_argument('--suffix', default='', type=str, help='customized suffix: opt.name = opt.name + suffix: e.g., {model}_{netG}_size{load_size}')

        # parameters related to StyleGAN2-based network
        parser.add_argument('--stylegan2_G_num_downsampling',
                            default=1, type=int,
                            help='Number of downsampling layers used by StyleGAN2Generator')

        self.initialized = True
        return parser
```

Let me think about this a little.

```py
        parser.add_argument('--load_size', type=int, default=286, help='scale images to this size')
        parser.add_argument('--crop_size', type=int, default=256, help='then crop to this size')
```

This...

```py
        parser.add_argument("--style-dim", default=256, type=int)
        parser.add_argument("--feature_dim", default=256, type=int)
        parser.add_argument("--hypersphere-dim", default=256, type=int)
```

Hmmm, let me try the first one for now. I am going to just change the defaults directly here. Works without a problem. Let me try 1k.

Out of memory. I really will need to set up something online. Hmmm, wait, since I am just running a net in forward mode, the CPU could do fine as well. Before that, let me find out the limit.

512+128 works really well. I really like how the image looks.

9:25am.

///

```py
        parser.add_argument('--load_size', type=int, default=512+128+32, help='scale images to this size')
        parser.add_argument('--crop_size', type=int, default=512+128, help='then crop to this size')
```

I've changed the defaults to this and it works. I really like how the image looks.

I can't go beyond this on my 4gb GTX 970 without running out of memory. But since I am just running it in forward mode, I think the CPU would be a viable choice here. My main system has 8gb...which I am not sure would be enough for 1k if I assume linear scaling of memory consumption with regards to the image size.

I was going to ask how do I get it to run in CPU mode, but now that I think about it more deeply why isn't 4gb enough if it is just the forward mode? I've read the paper, and unlike vanilla neural style transfer it is not supposed to be doing any optimization, but is instead just passing the image through the generator, right? Is it possible that it is keeping the backwards pass intermediaries in memory by accident during test time?

///

Let me see if I can resolve the memory issue this time. If I can, I am going to pick CAST over NNST.

///

    def test(self):
        """Forward function used in test time.

        This function wraps <forward> function in no_grad() so we don't save intermediate steps for backprop
        It also calls <compute_visuals> to produce additional visualization results
        """
        with torch.no_grad():
            self.forward()
            self.compute_visuals()

///

I guess not.

```py
parser.add_argument('--gpu_ids', type=str, default='0', help='gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU')
```

Let me try putting -1 here.

```
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    model.parallelize()
  File "E:\CAST_pytorch\models\base_model.py", line 102, in parallelize
    setattr(self, 'net' + name, torch.nn.DataParallel(net, self.opt.gpu_ids))
  File "C:\Users\Marko\anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 134, in __init__
    output_device = device_ids[0]
IndexError: list index out of rang
```

Nope. Let me add this in the issue page.

9:40am.

```py
            print("qwe")
            model.data_dependent_initialize(data)
            print("asd")
```

Yeah, it runs out of memory in the data dependent init.

9:50am. It worked!

```py
    def data_dependent_initialize(self, data):
        """
        The feature network netF is defined in terms of the shape of the intermediate, extracted
        features of the encoder portion of netG. Because of this, the weights of netF are
        initialized at the first feedforward pass with some input images.
        Please also see PatchSampleF.create_mlp(), which is called at the first forward() call.
        """
        self.set_input(data)
        bs_per_gpu = self.real_A.size(0) // max(len(self.opt.gpu_ids), 1)
        self.real_A = self.real_A[:bs_per_gpu]
        self.real_B = self.real_B[:bs_per_gpu]
        with torch.no_grad():
            self.forward()  # compute fake images: G(A)
```

I added a no_grad block here. See the issue page for more info. Now I can get it to produce a 1k image without a problem. Let me try going up to 2k.

10:05am. 2k is too much, but it goes up to 1408.

Nice. This could be really good. Let me play around with it for longer. The butterfly looks great, but maybe it is too realistic.

10:25am. This model is really impressive. It leads to crisp images and it has really good style comprehension. I am trying it on Nostalgia and it does lead to some discoloration, but it is really good at telling where the original deviates from the intended style.

I am really happy with this. I want to play with it more, but let me post the results in the /wip/ thread. I want to check out the model's drawing skills.

10:35am. Now if I could only squeeze the files under 4mb.

https://ask.clip-studio.com/en-us/detail?id=9319

///

You want to reduce the file size when saving with PNG or JPEG?

When saving with JPEG, by using the library called Guetzli or Mozjpeg,
High compression ratio can be obtained while maintaining image quality.
These libraries can be used with some online sites and software.

Similarly, in PNG, it is possible to reduce file size by using software such as PNGoo or PNGGuntlet.

However, these software takes time to process.

To download software, please go from a trusted site.
Malware such as computer viruses may be mixed.

///

https://pngquant.org/

This utility worked pretty well. It cut the sizes of all the files by at lest 2/3rds.

Now let me post the work on the /wip/ thread.

11:15am. Done. What is my priority right now?

Let me check out how well it draws.

Oh, wow. Most impressive.

Let me post this as well.

11:35am. Agh, I accidentally posted the uncompressed version. Next time I'll just overwrite them.

11:40am. https://mangadex.org/chapter/ff28a068-c860-42fa-a0d1-27e7e92a3e3e/2

Let me try passing in this page of Satanophany as the style image.

12:40pm. Actually, just one more. Let me try pluggin in Dohna Dohna's backgrounds. I'll use the base.

12:55pm. https://boards.4channel.org/3/thread/899902/wip-works-in-progress#p901720

Let me take a break here. It is too bad these images will get lost when the thread moves on. I'll post the results on my Twitter. Too bad a lot of these style images are copyrighted so I can't put them there like in the wip thread.

1:10pm. Let me go have breakfast. It is time for some rest. Yesterday I went at it till 11pm, so I need some rest.

Today I had an unusually productive morning session. I gained a huge asset. This will make 3d much more viable, though the net I have here is not all the way there yet. 3.5m params and 18h of learning will not cut it. If I can get some proper computational resources it will be worth building on the CAST work."