"9am. Let me chill for a bit and I will start. I am starting to feel the urge to program. The real challenge is teaching AI systems social skills. It seems like a big deal and one imagines humans as the paragons of sociability, but plenty of lesser creatures such as insects have those kinds of desires.
The only way to take my revenge on the world is to do this. Death and destruction will happen anyway as the consequence of the Singularity, so my own rage on top of that is like drop in the bucket. Any kind of violence that I can envision would just be an addon. But having other people become connected to my drones who I have perfect control over is something I should be aiming for whole heartedly.

Unless I take on and internalize such a goal, it is just going to be one failure after another.

I'll make a superhuman agent and then get punished for not being normal enough. No.

Never again. I never again want to be punished for failing some kind of Turing test, whether it be because of my agents or because of myself.

9:30am. Let me start programming.

Social skills. Automating them is the ultimate goal. If I could do that, I could attain anything. All of the obstacles to using AI are some kind of Turing test.

Right now, I have no idea how I could do this. I was prepared to do the poker agent, but making the interface is something I've only paid lip service to. I do not have some great plan as to how I might achieve agents that can imitate my own activity patterns or be social.

9:35am. Just kind of game is the social game? What are the rewards and punishments? Maybe the fact that I cannot answer that is proof that I do not undertand it. I can only understand it at the level of - if I acted like 'this', then 'that' kind of result would happen. But it feels like I am just doing pattern matching.

I can see the flow of it, and how it depends on the context, but I can't find the true start and finish. It feels more like decentralized RL. If I get stung on the hand by a bee, is it the hand which influences the rest of the system, or is the brain which pretends it is like that. It should be the later, but the brain itself puts in great effort to convince me that it is the former.

I can't really cut through the layers of self deception to turn this into an algorithm.

9:40am. All I can be sure is that my life depends on figuring this out. Just like figuring out a stable and reward scale invariant RL algorithm was one of my great goals of the past six years, for the next six, figuring out the social aspects of AI is something that I must pursue.

I want money, but even with the RL algorithm I mentioned and the superhuman agent, actually attaining that feels hopeless.

It does not feel like I can win at all. And figuring out the social aspects and formalizing them into an algorithm feels beyond me. Even the hardware for this kind experimentation is not there. GPUs feel insuficient for anything significant.

9:50am. I'll accept it. Being at the bottom and on the losing end is what suits the human me the most. Glory, power, achievement are the furthest things from me. Not being able to get what I want is the standard. Letting opportunities pass me by is common occurence.

But I'll dream about grasping this. I'll make it my main goal. I'll aim to take revenge by completely formalizing and then trivializing the social aspects of interaction.

Did I think my journey was over just because I made the first step? The story of me cultivating my demonic heart continues.

9:55am. I need to start work on the Holdem game. Let me bring in `training.spi` and I will get started on it. I thought that the architecture would not be like last time, but it turns out that it will. The nodes are a bit different, but the old design turned out to be remarkably resilient to my attempts at changing them.

I guess that makes things simpler. For the past week, I've spent a remarkable amount of time in indecision and it is time to get some work done.

10am. I'll accept my own powerlessness and continue going forward. Maybe the future me will one day know what it is like to have power. But for the me of the present, I am still nobody different than when I have started. I've only made a few steps forward in the past six years.

Maybe something bad will happen and my quest will end prematurely without attaining victory. In that case, maybe I'd be better off spending my time on leisure. But the reason games and fiction are great is because of belief in it. When I was a kid, I thought that even though they aren't real, with some effort they could be.

The dreams of power that I had would have been empty without the actual pursuit of them.

10:05am. And that is why I will do programming today. To provide substance to my vision and life to my dreams. The eventual outcome is beyond my control, but it does not change that this way of living is the right one.

Who cares about right or wrong, and the lives and benefits of others? That only thing that matters is my own effort that I am putting in.

I need to remember that in order to overcome the tedium. When you feel tedium the perspective shifts and you can only see the enormous mountain of work that does need to be done ahead of you. When you are in the spirit of pursuit the mountain seems small and easily passable, just another hurdle in the passage of your journey.

Let me bring in the `train` module.

10:20am. In addition to `vs_self` and `vs_one` I'll have to do a function to let a human play against an agent, but I'll leave that for later. It is not important right now. I'll cross that hurdle when I get to it.

10:25am. Now...I think I am ready to start work on the Holdem game. Before I do that let me just put an eye Leduc for a moment.

10:30am. Mmmhhh...ok. There is nothing else but to start. For now, let me just aim to make a game where two players draw cards and then get a reward.

10:40am. This time I won't use union types for cards as it would be too much of a pain to get their ordering. And it could cause inefficiency due to using i32 tags.

Instead they should be i8s. How do I make an [0,51] array in Numpy?

https://numpy.org/devdocs/reference/generated/numpy.linspace.html

Let me try this.

```
import numpy
x = numpy.linspace(0,51,52,dtype=numpy.int8)
numpy.random.shuffle(x)
```

Yeah, this is how I will make the starting deck.

```
inl Game =
    inl deck : a u64 i8 = $"numpy.linspace(0,51,52,dtype=numpy.int8)"
    $"numpy.random.shuffle(!deck)"
    ()
```

Nice and easy. The next step would be to draw two cards for each player.

11am.

```
open hand_scorer
inl game (stack : i32) =
    inl deck : a u64 card = $"numpy.linspace(0,51,52,dtype=numpy.int8)"
    $"numpy.random.shuffle(!deck)"

    inl pot = 1i32
    inl id = 0i8
    draw (Some: id) deck fun (c1, deck) =>
    draw (Some: id) deck fun (c2, deck) =>
    inl p1 = {stack pot id hand = c1,c2}

    inl pot = 2i32
    inl id = 1i8
    draw (Some: id) deck fun (c1, deck) =>
    draw (Some: id) deck fun (c2, deck) =>
    inl p2 = {stack pot id hand = c1,c2}

    terminal (p1,p2) (r2 1)
```

This is a good initial step.

11:10am. Focus me. Let me make an union type for the actions.

11:15am.

```
union action = Fold | Call | Raise: i32

open hand_scorer
inl game (stack : i32) =
    inl deck : a u64 card = $"numpy.linspace(0,51,52,dtype=numpy.int8)"
    $"numpy.random.shuffle(!deck)"
    inl actions : a _ _ = am.init (1 + u64 stack) fun i =>
        if i = 0 then Fold
        elif i = 1 then Call
        else Raise: i32 i - 2

    actions |> am.map function
        | Fold => "Fold"
        | Call => "Call"
        | Raise: x => $"f'Raise: {!x}'"
```

Let me see if this creates the kind of array I am envisioning.

11:20am. Nope it is completely wrong. It starts at zero and is in reverse order.

https://numpy.org/doc/stable/reference/generated/numpy.arange.html

Ah, wait instead of linspace I could have used this as well.

```
union action = Fold | Call | RaiseTo: i32

open hand_scorer
inl game (stack : i32) = // Stack size should be at least 2.
    inl deck : a u64 card = $"numpy.linspace(0,51,52,dtype=numpy.int8)"
    $"numpy.random.shuffle(!deck)"
    inl actions : a _ _ = am.init (1 + u64 stack) fun i =>
        if i = 0 then Fold
        elif i = 1 then Call
        else RaiseTo: stack - i32 (i-2)

    actions |> am.map function
        | Fold => "Fold"
        | Call => "Call"
        | RaiseTo: x => $"f'RaiseTo: {!x}'"
```

This is right.

```
numpy.arange(0,52,dtype=numpy.int8)
```

Let me use this.

11:40am.

```
    inl actions : a _ _ = am.init (u64 stack) fun i =>
        if i = 0 then Fold
        elif i = 1 then Call
        else RaiseTo: stack - i32 (i-2)
```

Let me narrow the array down as much as possible. Than I will make the helpers for call only arrays and such.

```
    inl actions : a _ _ = am.init (u64 stack) fun i =>
        if i = 0 then Fold
        elif i = 1 then Call
        else RaiseTo: stack - i32 (i-2)
```

Hmmm, why does this break when I made the array an i32?

```
TypeError: only size-1 arrays can be converted to Python scalars
```

What does this error mean?

```
    actions |> am.map function
        | Fold => "Fold"
        | Call => "Call"
        | RaiseTo: x => $"f'RaiseTo: {!x}'"
```

It happens due to the conversion.

```
inl map f ar = init (length ar) (fun i => f (index ar i))
```

This is how the map is implemented. So the problem has to be in init.

```
inl init nearTo f =
    inl ar = create nearTo
    for' (from: 0 nearTo:) (fun i => set ar i (f i))
    ar
```

What is the problem?

```
  File "c:/Users/Marko/Source/Repos/The Spiral Language/Spiral Compilation Tests/cython_experiments/ui_holdem1/hu_holdem_test.py", line 7, in <module>
    print(main())
  File "hu_holdem.pyx", line 23, in hu_holdem.main
    cpdef numpy.ndarray[str,ndim=1] main():
  File "hu_holdem.pyx", line 68, in hu_holdem.main
    v15 = v1
TypeError: only size-1 arrays can be converted to Python scalars
```
```
cdef numpy.ndarray[object,ndim=1] v1
cdef signed long v15
```

Ok, this is an array...

Why is it trying to assign an array to a signed long?

```
    tmp0 = len(v1)
    if <signed long>tmp0 != tmp0: raise Exception("The conversion to signed long failed.")
    v15 = v1
    v16 = numpy.empty(v15,dtype=object)
```

Huh, I get the sense it is trying to pass the length and instead passes an array by accident. Let me take a look at the codegen.

```fs
        let length (a,b) =
            match a with
            | YPrim (Int64T | UInt64T) -> return' $"len({tup b})"
            | YPrim a ->
                let l = $"len({tup b})"
                let tmp_i = tmp()
                line defs $"cdef unsigned long long tmp{tmp_i}"
                line s $"tmp{tmp_i} = {l}"
                let a = prim a
                line s $"if <{a}>tmp{tmp_i} != tmp{tmp_i}: raise Exception(\"The conversion to {a} failed.\")"
                return' (tup b)
```

Yeah, the problem is here.

```
return' l
```

I probably meant to write this. What an eyesore.

```
inl game (stack : i32) = // Stack size should be at least 2.
    inl deck : a u64 card = $"numpy.arange(0,52,dtype=numpy.int8)"
    $"numpy.random.shuffle(!deck)"
    inl actions : a _ _ = am.init stack fun i =>
        if i = 0 then Fold
        elif i = 1 then Call
        else RaiseTo: stack - i + 2

    inl get_action is_fold (min_raise : i32) =
        inl min : i32 = if is_fold then 0 else 1
        $"!actions[!min:3+!stack-!min_raise]"

    actions |> am.map function
        | Fold => "Fold"
        | Call => "Call"
        | RaiseTo: x => $"f'RaiseTo: {!x}'"
```

Ok, now everything is fine. Let me publish a new Spiral version.

12pm. Did so.

```
    actions |> am.map function
        | Fold => "Fold"
        | Call => "Call"
        | RaiseTo: x => $"f'RaiseTo: {!x}'"
```

Let me take this out.

```
    inl actions : action_array = am.init stack fun i =>
        if i = 0 then Fold
        elif i = 1 then Call
        else RaiseTo: stack - i + 2

    inl get_action is_fold (min_raise : i32) : action_array =
        inl min : i32 = if is_fold then 0 else 1
        $"!actions[!min:3+!stack-!min_raise]"
```

This will suffice to generate the actions array and get the allowed actions. Good. Now I should start work on the preflop and flop.

Maybe I should just do flop poker to start things off. Let me take a break here."