"8:30am. Watched some drawing perspective videos yesterday. Before I completely give up, is it possible for me to learn how to draw in perspective?
I played around with one point perspective yesterday, and there might be something to it. I learned about it last year, but I thought it was some nonsense.

I tried moving a few cubes around in Blender, importing the screenshot and to my surprise the angles line up when I draw straight lines through the center. Visually I thought the wuoldn't. It just goes to show biased my own perspective is.

https://youtu.be/4L6ZBjOS48M
Drawing perfect backgrounds with perspective rulers! | Jake Hercy Draws

I learned about perspective tools in CSP last year, but instead of being arrogant about it, I think this time I will pay attention. If I could somehow draw in 3d space directly, that would be a huge improvement in my drawing ability. I already have a feel for 3d. Let me just chill a little first.

8:50am. I am not against drawing in 3d space directly with something like a grease pencil. I could lock the camera in place and do 3d modeling without moving around. That would be a lot closer to drawing in 2d. I should consider it.

Let me just read Inglis first. I went to bed at 11am yesterday as I was so exhausted.

https://youtu.be/4L6ZBjOS48M?t=138
> Your strokes will draw automatically along the guidelines as long as the ruler is enabled.

https://youtu.be/4L6ZBjOS48M?t=209

Right now she is doing here what I want to do.

https://youtu.be/4L6ZBjOS48M?t=226

Hmmm...

https://youtu.be/EqegNrJJh3g
How to master 3D... for comics! | Jake Hercy Draws

9:20am. This video is on using 3d assets in CSP. I guess it would not be bad to get familiar with it.

9:30am. https://youtu.be/_fn9ux9bL2A?t=8
How to extract an EASY perspective grid in Clip Studio Paint!

Let me watch this as well, then I am going to give these pespective rulers and grids a try.

https://youtu.be/_fn9ux9bL2A?t=46

Hmmm, CSP has basic primitive shapes. Well, of course it would, but it never occured to me to look for them. Yeah, this is a great opportunity to get familiar with 3d in CSP. I've been thinking as just a 2d app, but that is not true.

https://youtu.be/_fn9ux9bL2A?t=158

He is going to use the cube as the basis for his perspective grid. It was not a bad idea to click on this video.

9:40am. Let me play with perspective a little. I am going to give the room a try again and see how far that gets me. This is the way to get better, you get a new tool and then try to master it. Scribbling lines would get me nowhere even if I spent years doing it.

10:25am. Yeah, this is pretty powerful. I should have been using it. But just this won't make me a good artist. But mastering sculpting to a greater degree might. So that is what I should be doing much like I pivoted yesterday.

First of all, let me try the Malt example file again. After that I'll ask the author how to open it.

10:30am. Hmmm, I just found the screenshots from my old base mesh. Looking at the face, the lips are too small. The soles of the feet are bad. The hindarm is too muscular. I got the body itself right. Well, I'll get it right next time around.

Malt.

https://github.com/bnpr/Malt/releases

Maybe I just need an earlier version. Naw, let me try out the very latest from 15h ago.

///

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\startup\bl_operators\userpref.py", line 782, in execute
    shutil.rmtree(path)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Marko\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\BlenderMalt\\.MaltPath\\Bridge\\ipc\\Ipc.dll'

location: <unknown location>:-1

///

Now I can't unistall it. Let me try running Blender in admin mode.

That worked. Let me install it again.

10:40am. Maybe those socket errors from yesterday were because I was not running it in admin mode. It seems to be using IPC to commnicate. It reminds me of Spiral, though with Spiral I had to go over the network card.

10:50am. The examples work now.

11:05am. Let me take a break here. I need to think what is next anyway. Should I try shading the stuff in the room with Malt? It might be worth a try.

11:45am. Perspective is powerful. I think with it, I could sketch the room to a much greater degree of accuracy. But would doing that kind of thing be particularly better than doing it in Moi for example?

I guess it could be faster.

11:55am. I don't know. Do I go for Malt or no?

If I had time I should go for it, but would it really be useful for illustrations?

No forget it. Modeling is the sweet spot of 3d. I should stay in it. Adding a shitload of shading concerns on top would just make things difficult to deal with. I got good advice in that other thread to make the scene lighting theatrical.

https://blenderartists.org/t/how-do-i-render-a-scene-where-most-of-the-lights-comes-from-grills/1381668/30

///

Looks good.

Remember – when you have things like “light coming in through a door,” that’s a so-called “practical light.” It’s a thing which we know in real life is “a source of light.” But for rendering purposes, as with a theater set, it probably shouldn’t be a source of light. Instead, you “put lights up in the loft of the theater” and use those to provide the actual illumination, which just has to look plausible.

///

12pm. Though I do like the Luxcore solution quite a bit. I need to do less work, not more. If I focused on rendering I could make the scene better, but if I instead focused just on modeling, I could get many more scenes done.

Messing with Malt shaders is really technical and could take months to master in its current state. Let me start the Zbrush course by Pablo. I should break the ice with it.

12:05pm. For now, how about I just focus on getting clean line art for my art?

When I feel like I've mastered that subject than Malt, painting, whatever techniques will be next. This is a good way of going at it.

I mean sure, getting good painting from my models would be good. But I should tackle the challenges one step at a time.

I really needed to render the room, because that will be the basis from getting a good drawing from it, but I should say task complete and get on with it.

Moi will be very formidable when it comes to giving me good drawings.

12:10pm. Let me focus on the course.

I should not lose sight of my goals. My goal is not to get 3/5 in art, but to find ways of getting good results the fastest.

12:25pm. 10m in. This seems like it will be a good course as he is covering his entire workflow. There is even coloring at the end.

Yeah, I'll be able to make use of this. Let me go through the course, and then I will focus on getting line art of the room scene. Freestyle edges by themselves are not good enough, I'd want hatching at a minimum, and even painting after that. I am not sure how I will do it, but that will be my goal.

If I can do all of that smoothly, I can consider myself 3/5 in 3d. I'll be almost ready to start Heaven's Key on the art side. I'll want to refine my methods a bit further, and do the cover, but after that I'll move on to music.

12:40pm. I never checked out Pinterest. He says that the algorithm the website is using to match images is absolutely the best.

12:45pm. Let me stop here at 23m.

12:50pm. Actually all the trays are taken up, let me go at it for 10m more.

1pm. He mentions that Zbrush started as an illustration software.

Right now I am looking at a crappy sculpt of Darth Vader and he is showing me it from various angles and renders.

1:10pm. It seems he does the painting in Krita and PS. I thought he might be painting it directly in Zbrush, but it seems not. He says that Zbrush is just for forms and volumes.

He says that the really powerful part of Zbrush are the custom masks that can be taken into PS for a lot more control.

...Let me try stopping for breakfast here again. I get the sense that this course will be very instructive. Whatever masks Zbrush is generating, I bet I'll be able to get them from Blender as well.

2:15pm. Let me chill a bit more and then I will start. Yeah, I made the right choice going with the Zbrush course rather than messing with shaders. Although I do not know how yet, having Blender generate various kinds of AOVs that I can take into CSP to do something good will be a more workable workflow. I am going to wrap things up by the end of next month and have something that I can use.

2:40pm. I do not feel like it, but let me just get through this. I am not sure if I am interested in following along. I should just watch this stuff and extract his techniques. Though the course is 18h, only a third of that is watching, the rest involves self work. It is fine if I just learn his workflow and leave the rest for later.

3:10pm. > What would you suggest to drive a consistent color look when using Zbrush to illustrate an entire graphic novel?

He going into something involving polypaint masks and polygrouping masks.

...Let me get back to it. I'll rant later. I am getting distracted with this journal.

3:25pm. He really likes Meobius, but I don't in particular. Though, just from this little bit, I am starting to get an inkling how I should be working. Take a step back to take two steps forward. I also came to an understanding that I should be modeling with respect to how future filters will interpret the data. I need a bit more. I do not know whether I will be diving into Malt. Probably I am not going to be able to use PBRs like Cycles and Luxcore as they are too slow. I'll have to find a way to make Eevee work.

3:50pm. Time for part 2 of day 1.

4pm. Let me take a break.

4:30pm. Let me resume.

4:40pm. Come to think of it, back in Malt when I tried a light, it had a power and radius. Isn't radius what I need to control the falloff. I'll keep it in mind.

The choice of renderer here is not so trivial for me. I can't really afford to wait for Luxcore to finish, so after I am done with this Zbrush for Illustrators course I might have a reason to dive into it. If needed I'll open various issues and ask the author to explain what various shaders do.

4:40pm. He is really praising Krita's brush engine. He says it is superior to Photoshop. I wonder how it would compare to CSP.

Huh, what sort of brush is this? I never saw anything like it in CSP.

4:50pm. Yeah these brushes are amazing. They feel like like they have real texture rather than just random scattering like in CSP and Substance Painter. It is really a pity I do not have the skill to take advantage of them.

5:05pm. Right now I am just watching him scribble over the canvas. Let me pause for a bit so I can rant.

I am thinking what the secret behind that comic renderer could be and it really can't be else but simple threesholding. I could a lot of elaborate linework simply from that, for chara models. What he showed me was remarkable. I couldn't draw Darth Vader, but I could certainly make a crappy scult of him. And that scult when converted to a drawing looks very good.

Remember the first scene that I did - the one with the couch. The first thing I grasped for was falloff for the stars. I didn't really like how it came out, but it turns out Malt has rim light. And that might be exactly what I would have wanted back then.

I should make it a priority to investigate toon shading with both Eevee and Malt. I should try sculpting an anime character after I am done with the room.

5:35pm. Estab Life is out. Let me just finish this video.

6:10pm. Day one was really boring overall. I really want to move on to the next parts. I liked the Darth Vader stuff, I think tomorrow he should be going into that in more depth.

Right now I do not feel like putting another 3h of tutorials.

Right now I am thinking to the October of last year. Remember when I was studying Illustrator and thought about tracing Milim Nava before giving up because it would be easy. Tracing her would be easy, but trying to draw her from imagination from a different perspective would be impossible for me.

But I could sculpt her. There are some anime sculptors on Youtube like Yan and Flycat, but they aren't targeting 2d via 3d directly. I should really try it. Maybe I'll end up liking the results. I do not like the CG style 3d anime, but maybe I could make it feel more organic thought both sculpting and compositing.

Pablo's art does not look 3d at all, and yet it is. So there is potential for me to adapt sculpting to whatever I like.

6:15pm. To be fair, Estab Life is really going a long way to change my mind on CG anime, but it not what I am aiming for exactly.

I haven't done it right. I need to put on a filter and then make the sculpt conformal to it. I should have done that back in January. Instead of going into modeling I spend so much time messing with Houdini.

Even now doing this room feels like I am messing around.

I should know what I need to do by the end of this course.

My main mistake is not recognizing the benefits that grayscale and crunching out the midtones brings. I only cared about precision and scale. This really reflects my Jan-March obsession with scattering well. I haven't been just trying to get better, I've also been searching for what better is.

As far as sculpting is concerned, going anime style will allow me to get away with much crappier models and have them look well.

In fact, once I start turning the room into a drawing, it might turn out that a lot of the detailing I did was a waste of time.

6:25pm. Yeah, this is why I am still 2/5 and not 3/5. If I am doing 3d models that will get converted into 2d, the rules are different.

Getting good 2d drawing using 3d gives me a natural way to continue improving my skills.

6:30pm. With the photorealistic 3d of the kind I've been studying I have to do thing like UV unwrapping, texturing, rendering which would take a lot of my time. The models have to be good to be realistic. That means having to do beveling. It is really a lot longer process. Pro 3d artists would skip large parts of that process by buying assets online, but I do not have the cash for that workflow. I'll only be able to get so far with Persia.

6:35pm. I am going to figure this out. Even if I go the CG route, since I am aiming for illustrations, I do not have to have those obvious cell shaded shadows in the end product. 3d will find a way. I am going to take care of the room and that way deal with my environment drawing and painting needs. AFter that I'll get back to chara modeling. This time I will do it right.

6:40pm. Let me close here. This is going to be a hot summer, but I am going to break into 3/5 in art, 2d or not. I'll bust through my lack of visual acuity with raw technical prowess. A mark of a pro is being able to go from A to Z without getting stuck inbetween. I am going to grasp my method and move on to bigger things."